(window.COURSE_PARTS = window.COURSE_PARTS || {})['b2_2'] = [
  // ───────────────────────── ÜNİTE 6 ─────────────────────────
  {
    title: "Hukuk ve Suç",
    desc: "Suç ve mahkeme kelimeleriyle hukuki bir sorunu anlatabilecek, third conditional ile geçmişteki pişmanlıkları ifade edebileceksin.",
    cefr: "B2",
    guide: [
      { h: "Suç kelimeleri: steal mi, rob mu?", p: "Türkçede hepsine 'çalmak' veya 'soymak' deriz ama İngilizcede ayrım var. 'Steal' bir ŞEYİ çalmaktır (steal a phone), 'rob' ise bir KİŞİYİ veya YERİ soymaktır (rob a bank, rob someone). 'Burglary' eve/işyerine girerek hırsızlık, 'robbery' zorla soygun, 'theft' genel hırsızlıktır. Türklerin tipik hatası 'They robbed my phone' demek; doğrusu 'They stole my phone'.", ex: [["Someone stole my bike last night.", "Dün gece biri bisikletimi çaldı."], ["Two men robbed the bank on Friday.", "Cuma günü iki adam bankayı soydu."]] },
      { h: "Mahkeme ve sözleşme dili", p: "'Commit a crime' (suç işlemek) kalıbında fiil 'do' değil 'commit'tir. 'Guilty of' (suçlu), 'accused of' (ile suçlanan) ve 'sentenced to' (cezasına çarptırılan) edatlarıyla birlikte öğrenilmeli. Sözleşmede 'clause' madde, 'terms' şartlar, 'breach' ihlal demektir. 'Sign a contract' denir, 'make a signature to a contract' denmez.", ex: [["He was found guilty of fraud.", "Dolandırıcılıktan suçlu bulundu."], ["She was sentenced to two years in prison.", "İki yıl hapis cezasına çarptırıldı."]] },
      { h: "Third conditional: geçmişteki 'keşke'ler", p: "Geçmişte olmamış bir durumu ve onun hayali sonucunu anlatır. Kalıp: If + had + V3, would have + V3. Türkçedeki '-seydi, -irdi' / '-miş olsaydı, -miş olurdu' yapısına denk gelir. En sık hata 'If I would have known' demektir; if tarafında ASLA 'would' olmaz. 'Could have' (yapabilirdim) ve 'might have' (belki yapardım) de 'would' yerine kullanılabilir.", ex: [["If I had read the contract, I would have seen the fee.", "Sözleşmeyi okusaydım ücreti görürdüm."], ["If you had called me, I could have helped.", "Beni arasaydın yardım edebilirdim."]] },
      { h: "Should have, wish ve in hindsight", p: "'Should have + V3' geçmişte yapılması gereken ama yapılmayan şey içindir: 'I should have checked' (kontrol etmeliydim). 'I wish + had + V3' ise geçmişle ilgili 'keşke'dir: 'I wish I had known' (keşke bilseydim). 'In hindsight' (geriye dönüp bakınca) bu cümlelerin doğal bir girişidir.", ex: [["I should have taken photos of the flat.", "Dairenin fotoğraflarını çekmeliydim."], ["I wish I had asked a lawyer.", "Keşke bir avukata sorsaydım."]] }
    ],
    story: {
      title: "Depozito Savaşı", icon: "⚖️",
      lines: [
        ["Anlatıcı", "Deniz and Lina moved to a bigger flat, but their old landlord kept the whole deposit.", "Deniz ve Lina daha büyük bir daireye taşındı ama eski ev sahipleri depozitonun tamamını tuttu."],
        ["Deniz", "Mr. Hughes says we ruined the carpet. It was already ruined when we arrived!", "Bay Hughes halıyı mahvettiğimizi söylüyor. Biz geldiğimizde zaten mahvolmuştu!"],
        ["Lina", "If we had taken photos on the first day, we would have proof now.", "İlk gün fotoğraf çekseydik şimdi kanıtımız olurdu."],
        ["Deniz", "Actually, I did take photos. I just forgot, because they're hidden between four hundred pictures of my lunch.", "Aslında fotoğraf çektim. Sadece unuttum, çünkü öğle yemeğimin dört yüz fotoğrafının arasında kaybolmuşlar."],
        ["Emma", "Was your deposit protected in a government scheme? Landlords have to do that by law here.", "Depozitonuz devletin bir güvence sistemine yatırıldı mı? Burada ev sahipleri bunu yasa gereği yapmak zorunda."],
        ["Deniz", "He never mentioned any scheme. He only mentioned the rent, every single month.", "Hiçbir sistemden bahsetmedi. Sadece kirayı söyledi, her ay istisnasız."],
        ["Emma", "Then he has broken the law. You could even claim up to three times the deposit.", "O zaman yasayı çiğnemiş. Depozitonun üç katına kadar tazminat bile isteyebilirsin."],
        ["Anlatıcı", "Deniz sent a polite but very firm letter. Two days later, Mr. Hughes called him.", "Deniz kibar ama çok kararlı bir mektup gönderdi. İki gün sonra Bay Hughes onu aradı."],
        ["Mr. Hughes", "Let's not involve any lawyers, son. I'll transfer the full amount today.", "Hiç avukat işin içine girmesin evlat. Tüm parayı bugün gönderiyorum."],
        ["Deniz", "If I had known the law earlier, I would have slept much better this month.", "Yasayı daha önce bilseydim bu ay çok daha rahat uyurdum."]
      ],
      questions: [
        { after: 1, q: "Why did the landlord keep the deposit?", options: ["Because the rent was late", "Because he said the carpet was ruined", "Because a window was broken"], answer: 1 },
        { after: 3, q: "Where were Deniz's photos of the flat?", options: ["In a lawyer's office", "On Lina's phone", "Among hundreds of pictures of his lunch"], answer: 2 },
        { after: 6, q: "What did Emma say Deniz could claim?", options: ["Up to three times the deposit", "Only half of the deposit", "Nothing at all"], answer: 0 },
        { after: 9, q: "How did the problem end?", options: ["They went to court", "The landlord paid back the full amount", "Deniz lost the case"], answer: 1 }
      ]
    },
    extra: [
      ["prison", "hapishane", "🏢"], ["pay a fine", "para cezası ödemek", "💷"], ["police officer", "polis memuru", "👮"], ["suspect", "şüpheli", "🕵️"], ["victim", "kurban, mağdur", ""],
      ["prosecutor", "savcı", "👨‍⚖️"], ["defendant", "sanık", ""], ["bail", "kefalet", "💰"], ["appeal", "itiraz, temyiz", ""], ["solicitor", "avukat (danışman)", "💼"],
      ["testify", "tanıklık etmek", ""], ["confess", "itiraf etmek", ""], ["steal", "çalmak", ""], ["pickpocket", "yankesici", "👛"], ["smuggling", "kaçakçılık", "📦"],
      ["bribery", "rüşvet", "💵"], ["identity theft", "kimlik hırsızlığı", "🪪"], ["scam", "dolandırıcılık, düzenbazlık", ""], ["crime scene", "olay yeri", "🚨"], ["alibi", "mazeret, suç anında başka yerde olma kanıtı", ""],
      ["handcuffs", "kelepçe", "🔗"], ["lawsuit", "dava", "📄"], ["settlement", "uzlaşma, anlaşma", "🤝"], ["notary", "noter", "🖋️"], ["signature", "imza", "✍️"],
      ["receipt", "makbuz, fiş", "🧾"], ["proof", "kanıt", ""], ["inventory", "demirbaş listesi, envanter", "📋"], ["eviction", "tahliye", "🚪"], ["rent increase", "kira artışı", "📈"]
    ],
    lessons: [
      {
        title: "Suç türleri", icon: "🚨",
        words: [["crime", "suç", "🚨"], ["criminal", "suçlu", ""], ["theft", "hırsızlık", ""], ["burglary", "ev soygunu, hırsızlık", "🏠"], ["robbery", "soygun", "🔫"], ["fraud", "dolandırıcılık", "💳"], ["shoplifting", "mağaza hırsızlığı", "🛍️"], ["vandalism", "vandalizm", ""], ["commit", "işlemek (suç)", ""], ["arrest", "tutuklamak", "🚓"]],
        sentences: [
          ["There has been a sharp rise in shoplifting in our neighbourhood this year.", "Bu yıl mahallemizde mağaza hırsızlığında keskin bir artış oldu.", ["Shoplifting has risen sharply in our neighbourhood this year."], ["Bu yıl mahallemizde mağaza hırsızlığı ciddi şekilde arttı.", "Bu yıl mahallemizde dükkan hırsızlığında keskin bir artış oldu.", "Mahallemizde bu yıl mağaza hırsızlığında büyük bir artış oldu."]],
          ["The police arrested two men who had committed a burglary near the station.", "Polis, istasyonun yakınında ev soygunu yapan iki adamı tutukladı.", ["The police arrested two men who committed a burglary near the station."], ["Polis istasyonun yakınında ev soygunu yapan iki adamı tutukladı.", "Polis istasyon yakınında hırsızlık yapan iki adamı gözaltına aldı.", "Polis, istasyonun yakınında bir eve hırsızlık yapan iki adamı tutukladı."]],
          ["Online fraud is now more common than street robbery in most big cities.", "Çoğu büyük şehirde internet dolandırıcılığı artık sokak soygunundan daha yaygın.", ["In most big cities, online fraud is now more common than street robbery."], ["Büyük şehirlerin çoğunda çevrimiçi dolandırıcılık artık sokak soygunundan daha yaygın.", "Çoğu büyük şehirde internet dolandırıcılığı şu an sokak soygunundan daha yaygın.", "Çoğu büyük şehirde çevrimiçi dolandırıcılık artık sokak soygunundan daha yaygındır."]],
          ["Breaking a bus shelter window is vandalism, not just a silly joke.", "Otobüs durağının camını kırmak sadece aptalca bir şaka değil, vandalizmdir.", ["Breaking the window of a bus shelter is vandalism, not just a silly joke."], ["Otobüs durağının camını kırmak aptalca bir şaka değil, vandalizmdir.", "Bir otobüs durağının camını kırmak sadece saçma bir şaka değil, vandalizmdir."]],
          ["Most criminals get caught because they make one small but stupid mistake.", "Suçluların çoğu küçük ama aptalca bir hata yaptıkları için yakalanır.", ["Most criminals are caught because they make one small but stupid mistake."], ["Suçluların çoğu küçük ama aptalca bir hata yüzünden yakalanır.", "Çoğu suçlu küçük ama aptalca bir hata yaptığı için yakalanır.", "Suçluların çoğu küçük ama salakça bir hata yaptıkları için yakalanıyor."]],
          ["Theft from parked cars is the most common crime in this area.", "Park halindeki arabalardan hırsızlık bu bölgedeki en yaygın suçtur.", ["The most common crime in this area is theft from parked cars."], ["Bu bölgedeki en yaygın suç park halindeki arabalardan hırsızlıktır.", "Park edilmiş arabalardan hırsızlık bu bölgedeki en yaygın suç.", "Park halindeki arabalardan yapılan hırsızlık bu bölgedeki en yaygın suçtur."]]
        ]
      },
      {
        title: "Mahkemede", icon: "👨‍⚖️",
        words: [["court", "mahkeme", "🏛️"], ["judge", "hakim, yargıç", "👨‍⚖️"], ["jury", "jüri", ""], ["trial", "dava, duruşma", ""], ["witness", "tanık", "👁️"], ["evidence", "delil, kanıt", "🔍"], ["verdict", "karar, hüküm", ""], ["guilty", "suçlu", ""], ["innocent", "masum", "😇"], ["sentence", "ceza, hüküm", ""]],
        sentences: [
          ["The trial lasted three weeks, and the jury finally reached a verdict on Friday.", "Dava üç hafta sürdü ve jüri sonunda cuma günü karara vardı.", ["The trial went on for three weeks, and the jury finally reached a verdict on Friday."], ["Duruşma üç hafta sürdü ve jüri nihayet cuma günü karar verdi.", "Dava üç hafta sürdü ve jüri sonunda cuma günü bir karara vardı.", "Dava üç hafta sürdü, jüri de sonunda cuma günü karara vardı."]],
          ["The judge said there was not enough evidence to prove that he was guilty.", "Hakim, onun suçlu olduğunu kanıtlamak için yeterli delil olmadığını söyledi.", ["The judge said there wasn't enough evidence to prove he was guilty."], ["Hakim onun suçlu olduğunu kanıtlamak için yeterli delil olmadığını söyledi.", "Yargıç onun suçlu olduğunu kanıtlayacak yeterli kanıt olmadığını söyledi.", "Hakim, suçlu olduğunu kanıtlayacak yeterli delil olmadığını söyledi."]],
          ["A witness told the court that she had seen the man near the shop.", "Bir tanık mahkemeye adamı dükkanın yakınında gördüğünü söyledi.", ["A witness told the court she had seen the man near the shop."], ["Bir tanık, adamı dükkanın yakınında gördüğünü mahkemeye söyledi.", "Bir tanık mahkemeye adamı mağazanın yakınında gördüğünü söyledi.", "Bir tanık mahkemede adamı dükkanın yakınında gördüğünü söyledi."]],
          ["In theory, everyone is innocent until they are proven guilty in a court.", "Teoride herkes mahkemede suçu kanıtlanana kadar masumdur.", ["In theory, everyone is innocent until proven guilty in a court."], ["Teoride herkes mahkemede suçu ispatlanana kadar masumdur.", "Kâğıt üzerinde herkes mahkemede suçu kanıtlanana kadar masumdur.", "Teoride herkes mahkemede suçlu olduğu kanıtlanana kadar masumdur."]],
          ["He received a two-year sentence for selling stolen phones online.", "Çalıntı telefonları internetten sattığı için iki yıl ceza aldı.", ["He got a two-year sentence for selling stolen phones online."], ["İnternetten çalıntı telefon sattığı için iki yıl hapis cezası aldı.", "Çalıntı telefonları internette sattığı için iki yıl ceza aldı.", "Çalıntı telefonları çevrimiçi sattığı için iki yıllık ceza aldı."]],
          ["Serving on a jury is a civic duty, but many people find it stressful.", "Jüride görev yapmak bir vatandaşlık görevidir ama birçok kişi bunu stresli bulur.", ["Being on a jury is a civic duty, but many people find it stressful."], ["Jüride görev yapmak vatandaşlık görevidir ama birçok insan bunu stresli buluyor.", "Jüri üyeliği bir vatandaşlık görevidir ama pek çok kişi bunu stresli bulur."]]
        ]
      },
      {
        title: "Avukat ve sözleşme", icon: "📜",
        words: [["lawyer", "avukat", "💼"], ["contract", "sözleşme", "📜"], ["clause", "madde (sözleşme)", ""], ["landlord", "ev sahibi", "🏠"], ["tenant", "kiracı", ""], ["deposit", "depozito", "💷"], ["lease", "kira sözleşmesi", "📃"], ["terms", "şartlar, koşullar", ""], ["breach", "ihlal", ""], ["legally binding", "yasal olarak bağlayıcı", ""]],
        sentences: [
          ["Before you sign a contract, always ask a lawyer to check every clause.", "Bir sözleşme imzalamadan önce her maddeyi mutlaka bir avukata kontrol ettir.", ["Always ask a lawyer to check every clause before you sign a contract."], ["Sözleşme imzalamadan önce her zaman her maddeyi bir avukata kontrol ettirin.", "Bir sözleşmeyi imzalamadan önce her maddeyi bir avukata kontrol ettir.", "Bir sözleşme imzalamadan önce her zaman her maddeyi bir avukata kontrol ettir."]],
          ["My landlord refused to return my deposit even though the flat was spotless.", "Ev sahibim, daire tertemiz olmasına rağmen depozitomu iade etmeyi reddetti.", ["My landlord refused to give back my deposit even though the flat was spotless."], ["Ev sahibim daire pırıl pırıl olduğu halde depozitomu geri vermeyi reddetti.", "Ev sahibim daire tertemiz olmasına rağmen depozitomu geri vermeyi reddetti.", "Daire tertemiz olmasına rağmen ev sahibim depozitomu iade etmeyi reddetti."]],
          ["As a tenant, you should keep a copy of your lease somewhere safe.", "Kiracı olarak kira sözleşmenin bir kopyasını güvenli bir yerde saklamalısın.", ["As a tenant, you should keep a copy of the lease in a safe place."], ["Kiracı olarak kira sözleşmenizin bir kopyasını güvenli bir yerde saklamalısınız.", "Bir kiracı olarak kira sözleşmenin bir kopyasını güvenli bir yerde tutmalısın.", "Kiracı olarak kira kontratının bir kopyasını güvenli bir yerde saklamalısın."]],
          ["If one side simply ignores the terms, it is a breach of contract.", "Taraflardan biri şartları düpedüz görmezden gelirse, bu sözleşme ihlalidir.", ["If one side ignores the terms, it is a breach of contract."], ["Taraflardan biri şartları görmezden gelirse bu bir sözleşme ihlalidir.", "Bir taraf koşulları hiçe sayarsa bu sözleşme ihlalidir.", "Taraflardan biri şartları görmezden gelirse bu sözleşme ihlali olur."]],
          ["Once you sign it, this agreement is legally binding for both sides.", "İmzaladığın anda bu anlaşma her iki taraf için de yasal olarak bağlayıcıdır.", ["This agreement is legally binding for both sides once you sign it."], ["İmzaladığınız anda bu anlaşma iki taraf için de yasal olarak bağlayıcıdır.", "Bunu imzaladığın anda anlaşma her iki taraf için yasal olarak bağlayıcı olur.", "İmzaladıktan sonra bu anlaşma iki taraf için de yasal olarak bağlayıcıdır."]],
          ["The lawyer found a strange clause about cleaning fees on page twelve.", "Avukat on ikinci sayfada temizlik ücretleriyle ilgili garip bir madde buldu.", ["On page twelve, the lawyer found a strange clause about cleaning fees."], ["Avukat on ikinci sayfada temizlik ücretleri hakkında tuhaf bir madde buldu.", "Avukat, on ikinci sayfada temizlik ücretleriyle ilgili garip bir madde buldu."]]
        ]
      },
      {
        title: "Haklarını bil", icon: "🛡️",
        words: [["rights", "haklar", "🛡️"], ["legal", "yasal, hukuki", ""], ["illegal", "yasa dışı", "🚫"], ["sue", "dava etmek", ""], ["compensation", "tazminat", "💰"], ["complaint", "şikâyet", ""], ["tribunal", "hakem kurulu, özel mahkeme", ""], ["entitled to", "hakkı olmak", ""], ["law", "yasa, kanun", "📚"], ["unfair", "adaletsiz, haksız", ""]],
        sentences: [
          ["Many tenants do not know their rights, so some landlords take advantage of them.", "Birçok kiracı haklarını bilmiyor, bu yüzden bazı ev sahipleri bundan faydalanıyor.", ["Many tenants don't know their rights, so some landlords take advantage of them."], ["Birçok kiracı haklarını bilmediği için bazı ev sahipleri onlardan faydalanıyor.", "Pek çok kiracı haklarını bilmiyor, bu yüzden bazı ev sahipleri onları istismar ediyor.", "Birçok kiracı haklarını bilmiyor, o yüzden bazı ev sahipleri bunu fırsat biliyor."]],
          ["Keeping a deposit without a good reason is illegal in this country.", "Geçerli bir sebep olmadan depozitoyu tutmak bu ülkede yasa dışıdır.", ["In this country, it is illegal to keep a deposit without a good reason."], ["Bu ülkede geçerli bir neden olmadan depozitoyu tutmak yasa dışıdır.", "Geçerli bir sebep olmadan depozitoyu alıkoymak bu ülkede yasadışıdır.", "Bu ülkede haklı bir sebep olmadan depozito tutmak kanuna aykırıdır."]],
          ["You are entitled to a full refund if the product arrives damaged.", "Ürün hasarlı gelirse tam para iadesi almaya hakkın var.", ["If the product arrives damaged, you are entitled to a full refund."], ["Ürün hasarlı gelirse paranın tamamını geri almaya hakkınız var.", "Ürün hasarlı ulaşırsa tam iade alma hakkın var.", "Ürün hasarlı gelirse paranın tamamını geri alma hakkın var."]],
          ["She decided to sue the company and asked for compensation for the stress.", "Şirketi dava etmeye karar verdi ve yaşadığı stres için tazminat istedi.", ["She decided to sue the company and claimed compensation for the stress."], ["Şirketi dava etmeye karar verdi ve stres için tazminat talep etti.", "Şirkete dava açmaya karar verdi ve yaşadığı stres için tazminat istedi."]],
          ["I made a formal complaint, and in the end the case went to a tribunal.", "Resmi bir şikâyette bulundum ve sonunda dava hakem kuruluna gitti.", ["I made an official complaint, and in the end the case went to a tribunal."], ["Resmi şikâyette bulundum ve sonunda dava bir hakem kuruluna gitti.", "Resmi bir şikâyet yaptım ve sonunda dava özel mahkemeye gitti.", "Resmi bir şikâyette bulundum, sonunda da dava mahkemeye taşındı."]],
          ["Legal advice can be expensive, but here the law is clearly on your side.", "Hukuki danışmanlık pahalı olabilir ama burada yasa açıkça senin tarafında.", ["Legal advice can be expensive, but the law is clearly on your side here."], ["Hukuki danışmanlık pahalı olabilir ama burada kanun açıkça sizin tarafınızda.", "Hukuki tavsiye pahalı olabilir ama burada yasa açıkça senden yana.", "Avukat danışmanlığı pahalı olabilir ama burada kanun açıkça senin tarafında."]]
        ]
      },
      {
        title: "Keşke bilseydim", icon: "⏪",
        words: [["regret", "pişman olmak, pişmanlık", "😔"], ["would have", "-ardı, -miş olurdu", ""], ["should have", "-malıydı", ""], ["could have", "-ebilirdi", ""], ["in hindsight", "geriye dönüp bakınca", "🔙"], ["warn", "uyarmak", "⚠️"], ["small print", "küçük yazılar, ince ayrıntılar", "🔎"], ["otherwise", "aksi halde, yoksa", ""], ["wish", "keşke, dilemek", "🌠"], ["consequence", "sonuç, netice", ""]],
        sentences: [
          ["If I had read the small print, I would have noticed the cleaning fee.", "Küçük yazıları okusaydım temizlik ücretini fark ederdim.", ["I would have noticed the cleaning fee if I had read the small print."], ["Küçük yazıları okumuş olsaydım temizlik ücretini fark etmiş olurdum.", "İnce ayrıntıları okusaydım temizlik ücretini fark ederdim.", "Küçük harfleri okusaydım temizlik ücretini fark ederdim."]],
          ["If you had warned me earlier, I could have taken photos of the flat.", "Beni daha önce uyarsaydın dairenin fotoğraflarını çekebilirdim.", ["I could have taken photos of the flat if you had warned me earlier."], ["Beni daha erken uyarsaydın dairenin fotoğraflarını çekebilirdim.", "Beni daha önce uyarmış olsaydın dairenin fotoğraflarını çekebilirdim.", "Beni önceden uyarsaydınız dairenin fotoğraflarını çekebilirdim."]],
          ["In hindsight, I should have asked for a written receipt for every payment.", "Geriye dönüp bakınca her ödeme için yazılı makbuz istemeliydim.", ["Looking back, I should have asked for a written receipt for every payment."], ["Şimdi düşününce her ödeme için yazılı bir makbuz istemeliydim.", "Geriye dönüp bakınca her ödeme için yazılı bir makbuz istemem gerekirdi.", "Geriye baktığımda her ödeme için yazılı makbuz istemeliydim."]],
          ["Luckily I kept all the emails, otherwise I would have lost the whole case.", "Neyse ki tüm e-postaları sakladım, yoksa davanın tamamını kaybederdim.", ["Luckily I kept all the emails, or I would have lost the whole case."], ["Neyse ki bütün e-postaları saklamışım, aksi halde tüm davayı kaybederdim.", "Şansıma tüm e-postaları sakladım, yoksa davayı tamamen kaybederdim.", "Neyse ki bütün e-postaları sakladım, yoksa bütün davayı kaybederdim."]],
          ["I wish I had known my rights before I moved into that flat.", "Keşke o daireye taşınmadan önce haklarımı bilseydim.", ["I wish I had known my rights before moving into that flat."], ["Keşke o eve taşınmadan önce haklarımı bilseydim.", "Keşke o daireye taşınmadan önce haklarımı bilmiş olsaydım.", "O daireye taşınmadan önce keşke haklarımı bilseydim."]],
          ["He deeply regrets ignoring the letter, because the consequences were serious.", "Mektubu görmezden geldiği için çok pişman, çünkü sonuçları ciddiydi.", ["He really regrets ignoring the letter, because the consequences were serious."], ["Mektubu umursamadığı için derinden pişman çünkü sonuçlar ciddiydi.", "Mektubu görmezden geldiğine çok pişman, çünkü sonuçları ağır oldu.", "Mektubu görmezden geldiği için çok pişman çünkü sonuçları ciddi oldu."]]
        ]
      }
    ]
  },
  // ───────────────────────── ÜNİTE 7 ─────────────────────────
  {
    title: "Tartışma ve Fikir Bildirme",
    desc: "Fikrini kibarca ama net savunabilecek, katılıp katılmadığını söyleyebilecek ve bağlaçlarla ikna edici cümleler kurabileceksin.",
    cefr: "B2",
    guide: [
      { h: "Fikir belirtmenin yolları", p: "Her cümleye 'I think' ile başlamak tekrara düşürür. 'In my opinion' resmi, 'I reckon' gündelik İngiliz dilidir, 'As far as I'm concerned' ise 'bana kalırsa' tonundadır. Türklerin tipik hatası 'According to me' demektir; bu doğal değildir. 'According to' yalnızca başkaları için kullanılır: 'according to the report' (rapora göre).", ex: [["In my opinion, the plan is too risky.", "Bence plan fazla riskli."], ["According to Emma, sales went up.", "Emma'ya göre satışlar arttı."]] },
      { h: "Katılmak ve kibarca karşı çıkmak", p: "'I am agree' YANLIŞTIR; 'agree' bir fiildir, doğrusu 'I agree'. İngilizcede doğrudan 'You are wrong' demek çok serttir. Önce karşı tarafın haklı yanını kabul edip sonra itiraz etmek beklenir: 'I see what you mean, but...' ya da 'That's a fair point, however...'. 'I'm not so sure' aslında kibar bir 'katılmıyorum'dur.", ex: [["I agree with you completely.", "Sana tamamen katılıyorum."], ["I see what you mean, but I'm not so sure.", "Ne demek istediğini anlıyorum ama pek emin değilim."]] },
      { h: "Zıtlık bağlaçları: however, although, whereas, despite", p: "'Although / even though' bir yan cümle başlatır ve ardından özne + fiil gelir. 'Despite / in spite of' ise isim veya -ing ister: 'despite the rain', 'despite being tired'. 'Despite of' diye bir yapı YOKTUR. 'However' ve 'nevertheless' genelde yeni bir cümlenin başında, virgülle kullanılır. 'Whereas' iki şeyi karşılaştırır, Türkçedeki '-ken, ... ise' yapısına benzer.", ex: [["Although it was late, we kept talking.", "Geç olmasına rağmen konuşmaya devam ettik."], ["Despite the rain, she walked to work.", "Yağmura rağmen işe yürüdü."]] },
      { h: "Ekleme ve sonuç: moreover, therefore, as a result", p: "Argümana yeni bir nokta eklemek için 'moreover', 'furthermore', 'in addition' ya da daha gündelik 'besides' kullanılır. Sonuç bildirmek için 'therefore', 'as a result', 'consequently' gelir. Bunlar 'and' gibi iki cümleyi tek başına bağlayamaz, önlerine nokta veya 'and' gerekir. 'Not only... but also' yapısında cümle başındaysa devrik yapı kurulur: 'Not only did sales improve...'", ex: [["The flat is cheap. Moreover, it is close to work.", "Daire ucuz. Üstelik işe yakın."], ["Sales fell, and as a result, we cut costs.", "Satışlar düştü ve sonuç olarak masrafları kıstık."]] }
    ],
    story: {
      title: "Ofise Dönüş Tartışması", icon: "💬",
      lines: [
        ["Anlatıcı", "Mr. Walker called a meeting to discuss a new rule, five office days a week.", "Bay Walker yeni bir kuralı, haftada beş ofis gününü konuşmak için toplantı yaptı."],
        ["Mr. Walker", "Frankly, I believe teams work better when they share the same room.", "Açıkçası, ekiplerin aynı odayı paylaştıklarında daha iyi çalıştığına inanıyorum."],
        ["Emma", "With all due respect, our results improved while we were working from home.", "Kusura bakmayın ama evden çalışırken sonuçlarımız iyileşti."],
        ["Deniz", "Moreover, my commute takes ninety minutes. That's a whole film, every single day.", "Üstelik işe gidip gelmem doksan dakika sürüyor. Bu her gün koca bir film demek."],
        ["Mr. Walker", "That's a fair point. However, new staff need someone to learn from.", "Haklı bir nokta. Ancak yeni çalışanların öğrenecekleri birine ihtiyacı var."],
        ["Emma", "Although that's true, they could come in on fixed days with their mentors.", "Bu doğru olsa da belirli günlerde mentorlarıyla birlikte gelebilirler."],
        ["Deniz", "I've made a chart. It's beautiful, and it clearly proves that Emma is right.", "Bir grafik hazırladım. Çok güzel ve Emma'nın haklı olduğunu açıkça kanıtlıyor."],
        ["Mr. Walker", "Nevertheless, I'm not convinced. Charts can be beautiful and completely wrong.", "Yine de ikna olmadım. Grafikler hem güzel hem de tamamen yanlış olabilir."],
        ["Anlatıcı", "After an hour, they reached a compromise, three days in the office and two at home.", "Bir saat sonra uzlaştılar, üç gün ofiste ve iki gün evde."],
        ["Emma", "Nice chart, Deniz. Next time, try putting some numbers on it too.", "Güzel grafik Deniz. Bir dahaki sefere üstüne birkaç rakam da koymayı dene."]
      ],
      questions: [
        { after: 0, q: "What did Mr. Walker want at the start?", options: ["Three office days a week", "Five office days a week", "No office at all"], answer: 1 },
        { after: 3, q: "How long is Deniz's commute?", options: ["Ninety minutes", "Thirty minutes", "Two hours"], answer: 0 },
        { after: 8, q: "What was the final decision?", options: ["Everyone works from home", "Five days in the office", "Three days in the office and two at home"], answer: 2 },
        { after: 9, q: "What was missing from Deniz's chart?", options: ["Colours", "The numbers", "A title"], answer: 1 }
      ]
    },
    extra: [
      ["debate", "münazara, tartışma", "🎙️"], ["discussion", "tartışma, görüşme", "💬"], ["controversial", "tartışmalı", ""], ["valid", "geçerli", "✅"], ["assumption", "varsayım", ""],
      ["counterargument", "karşı argüman", ""], ["pros and cons", "artılar ve eksiler", "⚖️"], ["majority", "çoğunluk", ""], ["minority", "azınlık", ""], ["survey", "anket", "📊"],
      ["hybrid", "hibrit, karma", ""], ["distraction", "dikkat dağıtan şey", "📱"], ["work-life balance", "iş-yaşam dengesi", "⚖️"], ["isolation", "yalnızlık, yalıtılmışlık", ""], ["collaboration", "iş birliği", "🤝"],
      ["bias", "önyargı, taraflılık", ""], ["logical", "mantıklı", "🧠"], ["exaggerate", "abartmak", ""], ["interrupt", "sözünü kesmek", "✋"], ["clarify", "netleştirmek, açıklığa kavuşturmak", ""],
      ["emphasise", "vurgulamak", ""], ["point out", "belirtmek, dikkat çekmek", "👉"], ["admit", "kabul etmek, itiraf etmek", ""], ["deny", "inkâr etmek, reddetmek", ""], ["concede", "kabullenmek, hak vermek", ""],
      ["evidence-based", "kanıta dayalı", ""], ["weigh up", "tartmak, değerlendirmek", ""], ["take into account", "hesaba katmak", ""], ["rule out", "olasılık dışı bırakmak", ""], ["bring up", "gündeme getirmek", ""]
    ],
    lessons: [
      {
        title: "Fikrini söyle", icon: "🗣️",
        words: [["in my opinion", "bence, kanımca", ""], ["as far as I'm concerned", "bana kalırsa", ""], ["I reckon", "bence, sanırım (gündelik)", ""], ["point of view", "bakış açısı", "👀"], ["argue", "savunmak, tartışmak", ""], ["personally", "şahsen", ""], ["it seems to me", "bana öyle geliyor ki", ""], ["stance", "tutum, duruş", ""], ["perspective", "perspektif, bakış", ""], ["firmly believe", "kesinlikle inanmak", ""]],
        sentences: [
          ["In my opinion, working from home makes people calmer and more productive.", "Bence evden çalışmak insanları daha sakin ve daha verimli yapıyor.", ["In my opinion, working from home makes people more productive and calmer."], ["Bana göre evden çalışmak insanları daha sakin ve verimli kılıyor.", "Kanımca evden çalışmak insanları daha sakin ve daha üretken yapıyor.", "Bence evden çalışmak insanları daha sakin ve daha verimli kılıyor."]],
          ["As far as I'm concerned, the office is just a very expensive coffee shop.", "Bana kalırsa ofis sadece çok pahalı bir kafe.", ["As far as I'm concerned, the office is only a very expensive coffee shop."], ["Bence ofis sadece çok pahalı bir kahve dükkanı.", "Bana kalırsa ofis çok pahalı bir kafeden ibaret.", "Bana kalırsa ofis sadece çok pahalı bir kahveci."]],
          ["I reckon most managers simply want to see people sitting at their desks.", "Bence çoğu yönetici sadece insanları masalarında otururken görmek istiyor.", ["I reckon most managers just want to see people sitting at their desks."], ["Bana kalırsa yöneticilerin çoğu sadece insanları masalarında otururken görmek istiyor.", "Sanırım çoğu yönetici yalnızca insanları masalarında oturur görmek istiyor.", "Bence yöneticilerin çoğu sadece insanları masa başında görmek istiyor."]],
          ["From a manager's point of view, it is harder to build a team online.", "Bir yöneticinin bakış açısından, çevrimiçi bir ekip kurmak daha zor.", ["From a manager's perspective, it is harder to build a team online."], ["Yönetici gözüyle bakınca çevrimiçi bir ekip kurmak daha zor.", "Bir yöneticinin bakış açısından internet üzerinden ekip kurmak daha zordur.", "Yöneticinin bakış açısına göre çevrimiçi ekip oluşturmak daha zor."]],
          ["Some people argue that young employees learn faster when they sit next to experts.", "Bazıları genç çalışanların uzmanların yanında oturunca daha hızlı öğrendiğini savunuyor.", ["Some argue that young employees learn faster when they sit next to experts."], ["Bazı insanlar genç çalışanların uzmanların yanında daha hızlı öğrendiğini savunuyor.", "Bazıları genç çalışanların uzmanların yanında otururken daha çabuk öğrendiğini iddia ediyor."]],
          ["Personally, I firmly believe that trust matters more than location.", "Ben şahsen güvenin konumdan daha önemli olduğuna kesinlikle inanıyorum.", ["Personally, I strongly believe that trust matters more than location."], ["Şahsen güvenin yerden daha önemli olduğuna kesinlikle inanıyorum.", "Ben şahsen güvenin mekândan daha önemli olduğuna kesinlikle inanıyorum.", "Şahsen güvenin konumdan daha önemli olduğuna yürekten inanıyorum."]]
        ]
      },
      {
        title: "Katılıyorum, katılmıyorum", icon: "🤝",
        words: [["agree", "katılmak, aynı fikirde olmak", "👍"], ["disagree", "katılmamak", "👎"], ["absolutely", "kesinlikle", ""], ["exactly", "aynen, tam olarak", ""], ["that's a fair point", "haklı bir nokta", ""], ["I see what you mean", "ne demek istediğini anlıyorum", ""], ["I'm not so sure", "pek emin değilim", "🤔"], ["on the contrary", "aksine, tam tersine", ""], ["compromise", "uzlaşma, orta yol", "🤝"], ["object to", "itiraz etmek", ""]],
        sentences: [
          ["I completely agree with you, but we still need some days in the office.", "Sana tamamen katılıyorum ama yine de ofiste birkaç güne ihtiyacımız var.", ["I agree with you completely, but we still need some days in the office."], ["Size tamamen katılıyorum ama yine de ofiste birkaç güne ihtiyacımız var.", "Sana kesinlikle katılıyorum ama yine de birkaç gün ofiste olmamız gerekiyor.", "Seninle tamamen aynı fikirdeyim ama yine de ofiste birkaç güne ihtiyacımız var."]],
          ["I see what you mean, but I'm not so sure it would work for us.", "Ne demek istediğini anlıyorum ama bizim için işe yarayacağından pek emin değilim.", ["I see what you mean, but I'm not sure it would work for us."], ["Ne demek istediğinizi anlıyorum ama bizim için işe yarayacağından pek emin değilim.", "Ne demek istediğini anlıyorum ama bizde işe yarar mı pek emin değilim."]],
          ["That's a fair point, and I hadn't thought about the cost of commuting.", "Haklı bir nokta, işe gidip gelmenin maliyetini hiç düşünmemiştim.", ["That's a fair point, and I had not thought about the cost of commuting."], ["Bu yerinde bir tespit, yol masrafını hiç düşünmemiştim.", "Haklısın, işe gidip gelmenin maliyetini hiç düşünmemiştim.", "Bu haklı bir nokta, işe gidip gelme masrafını düşünmemiştim."]],
          ["On the contrary, our sales actually went up when everyone worked from home.", "Aksine, herkes evden çalışırken satışlarımız aslında arttı.", ["On the contrary, our sales actually rose when everyone worked from home."], ["Tam tersine herkes evden çalıştığında satışlarımız aslında yükseldi.", "Aksine herkes evden çalıştığında satışlarımız aslında arttı.", "Tam tersine, herkes evden çalışırken satışlarımız aslında arttı."]],
          ["Emma strongly disagreed and said she would object to any new rule.", "Emma kesinlikle katılmadı ve her yeni kurala itiraz edeceğini söyledi.", ["Emma strongly disagreed and said that she would object to any new rule."], ["Emma hiç katılmadı ve her yeni kurala itiraz edeceğini söyledi.", "Emma kesinlikle karşı çıktı ve her yeni kurala itiraz edeceğini söyledi.", "Emma kesinlikle aynı fikirde değildi ve her yeni kurala itiraz edeceğini söyledi."]],
          ["In the end, we reached a compromise of three office days a week.", "Sonunda haftada üç ofis günü konusunda uzlaştık.", ["In the end, we agreed on a compromise of three office days a week."], ["Sonunda haftada üç gün ofiste olmak üzere bir uzlaşmaya vardık.", "Sonunda haftada üç ofis gününde orta yolu bulduk.", "Nihayetinde haftada üç ofis günü üzerinde uzlaştık."]]
        ]
      },
      {
        title: "Ama, rağmen, oysa", icon: "🔀",
        words: [["however", "ancak, fakat", ""], ["although", "-e rağmen, -se de", ""], ["whereas", "oysa, -ken", ""], ["nevertheless", "yine de, buna rağmen", ""], ["even though", "-dığı halde", ""], ["despite", "-e rağmen", ""], ["in spite of", "-e rağmen", ""], ["on the other hand", "öte yandan", ""], ["while", "-ken, oysa", ""], ["yet", "yine de, ama", ""]],
        sentences: [
          ["Remote work saves a lot of time, however, it can feel lonely after a while.", "Uzaktan çalışma çok zaman kazandırır, ancak bir süre sonra yalnız hissettirebilir.", ["Remote work saves a lot of time. However, it can feel lonely after a while."], ["Uzaktan çalışmak çok zaman kazandırır, fakat bir süre sonra yalnızlık hissettirebilir.", "Uzaktan çalışma çok zaman kazandırıyor, ancak bir süre sonra insanı yalnız hissettirebilir."]],
          ["Although the office is noisy, I always get my best ideas there.", "Ofis gürültülü olsa da en iyi fikirlerim hep orada aklıma gelir.", ["Even though the office is noisy, I always get my best ideas there."], ["Ofis gürültülü olmasına rağmen en iyi fikirlerimi hep orada buluyorum.", "Ofis gürültülü olsa da en iyi fikirler hep orada aklıma geliyor.", "Ofis gürültülü olduğu halde en iyi fikirlerimi her zaman orada bulurum."]],
          ["Deniz loves working at home, whereas Emma prefers the buzz of the office.", "Deniz evde çalışmayı seviyor, Emma ise ofisin hareketliliğini tercih ediyor.", ["Deniz loves working from home, whereas Emma prefers the buzz of the office."], ["Deniz evde çalışmaya bayılıyor, oysa Emma ofisin canlılığını tercih ediyor.", "Deniz evden çalışmayı seviyor, Emma ise ofisin hareketini tercih ediyor."]],
          ["The plan has some serious risks, nevertheless, the board decided to try it.", "Planın bazı ciddi riskleri var, yine de yönetim kurulu denemeye karar verdi.", ["The plan has some serious risks. Nevertheless, the board decided to try it."], ["Planın bazı ciddi riskleri var, buna rağmen yönetim kurulu onu denemeye karar verdi.", "Planın ciddi riskleri var, yine de yönetim kurulu planı denemeye karar verdi."]],
          ["Despite the long commute, he has never arrived late to the Monday meeting.", "Uzun yola rağmen pazartesi toplantısına hiç geç kalmadı.", ["In spite of the long commute, he has never arrived late to the Monday meeting."], ["Yolu uzun olmasına rağmen pazartesi toplantısına bir kez bile geç kalmadı.", "Uzun yola rağmen pazartesi toplantısına asla geç kalmadı.", "İşe gidiş yolu uzun olmasına rağmen pazartesi toplantısına hiç geç kalmadı."]],
          ["She lives far away, yet she comes in every day in spite of the rain.", "Uzakta yaşıyor, yine de yağmura rağmen her gün işe geliyor.", ["She lives far away, yet she comes in every day despite the rain."], ["Uzakta oturuyor ama yine de yağmura rağmen her gün işe geliyor.", "Uzakta yaşamasına rağmen yağmura aldırmadan her gün işe geliyor.", "Uzakta yaşıyor, ama yağmura rağmen her gün ofise geliyor."]]
        ]
      },
      {
        title: "Üstelik ve bu yüzden", icon: "➕",
        words: [["moreover", "üstelik, dahası", ""], ["furthermore", "ayrıca, bunun yanı sıra", ""], ["in addition", "buna ek olarak", ""], ["therefore", "bu nedenle, dolayısıyla", ""], ["as a result", "sonuç olarak", ""], ["consequently", "sonuç olarak, bu yüzden", ""], ["besides", "hem zaten, ayrıca", ""], ["not only", "sadece... değil", ""], ["overall", "genel olarak", ""], ["in conclusion", "sonuç olarak, özetle", "🏁"]],
        sentences: [
          ["Remote work saves money. Moreover, it reduces traffic and pollution in the city.", "Uzaktan çalışma para kazandırır. Üstelik şehirdeki trafiği ve kirliliği azaltır.", ["Remote work saves money. Furthermore, it reduces traffic and pollution in the city."], ["Uzaktan çalışmak para kazandırıyor. Dahası şehirdeki trafiği ve kirliliği azaltıyor.", "Uzaktan çalışma para kazandırır. Ayrıca şehirdeki trafiği ve kirliliği azaltır."]],
          ["The office was half empty, therefore the company moved to a smaller building.", "Ofis yarı boştu, bu yüzden şirket daha küçük bir binaya taşındı.", ["The office was half empty, so the company moved to a smaller building."], ["Ofis yarı boştu, dolayısıyla şirket daha küçük bir binaya taşındı.", "Ofis yarı yarıya boştu, bu nedenle şirket daha küçük bir binaya geçti."]],
          ["Not only did sales improve, but fewer people also left the company.", "Satışlar artmakla kalmadı, şirketten ayrılan kişi sayısı da azaldı.", ["Not only did sales improve, but fewer people left the company too."], ["Sadece satışlar artmadı, aynı zamanda daha az kişi şirketten ayrıldı.", "Satışlar iyileşmekle kalmadı, şirketten daha az insan ayrıldı.", "Hem satışlar arttı hem de şirketten daha az kişi ayrıldı."]],
          ["Nobody read the report, and as a result, the same mistakes happened again.", "Kimse raporu okumadı ve sonuç olarak aynı hatalar yine yaşandı.", ["Nobody read the report, and consequently, the same mistakes happened again."], ["Kimse raporu okumadı ve bunun sonucunda aynı hatalar tekrar yaşandı.", "Raporu kimse okumadı, sonuç olarak aynı hatalar yeniden yapıldı.", "Kimse raporu okumadı, bu yüzden aynı hatalar yine oldu."]],
          ["Besides, a quiet home office is not something everyone can afford in London.", "Hem zaten Londra'da sessiz bir ev ofisini herkes karşılayamaz.", ["Besides, not everyone in London can afford a quiet home office."], ["Ayrıca sessiz bir ev ofisi Londra'da herkesin karşılayabileceği bir şey değil.", "Üstelik Londra'da herkes sessiz bir ev ofisine sahip olamaz.", "Zaten Londra'da sessiz bir ev ofisini herkes karşılayamaz."]],
          ["Overall, the survey shows that people want flexibility rather than total freedom.", "Genel olarak anket, insanların tam özgürlükten çok esneklik istediğini gösteriyor.", ["Overall, the survey shows people want flexibility rather than total freedom."], ["Genel olarak anket insanların tam özgürlük yerine esneklik istediğini gösteriyor.", "Genelde anket, insanların tam özgürlükten ziyade esneklik istediğini gösteriyor."]]
        ]
      },
      {
        title: "İkna etme sanatı", icon: "🎯",
        words: [["persuade", "ikna etmek", ""], ["convince", "inandırmak, ikna etmek", ""], ["argument", "argüman, gerekçe", ""], ["benefit", "fayda", "✅"], ["drawback", "sakınca, dezavantaj", "❌"], ["productivity", "verimlilik", "📈"], ["remote work", "uzaktan çalışma", "💻"], ["commute", "işe gidip gelme", "🚆"], ["flexible", "esnek", ""], ["trust", "güvenmek, güven", "🤝"]],
        sentences: [
          ["Deniz tried to persuade Mr. Walker with numbers instead of emotions.", "Deniz, Bay Walker'ı duygular yerine rakamlarla ikna etmeye çalıştı.", ["Deniz tried to persuade Mr. Walker with numbers rather than emotions."], ["Deniz Bay Walker'ı duygularla değil rakamlarla ikna etmeye çalıştı.", "Deniz, Bay Walker'ı duygu yerine sayılarla ikna etmeye çalıştı."]],
          ["The strongest argument for remote work is the time we save on our commute.", "Uzaktan çalışmanın lehine en güçlü argüman, yolda kazandığımız zaman.", ["The best argument for remote work is the time we save on our commute."], ["Uzaktan çalışma için en güçlü argüman yolda kazandığımız zamandır.", "Uzaktan çalışmanın en güçlü gerekçesi işe gidip gelirken kazandığımız zaman."]],
          ["Every plan has benefits and drawbacks, so let's look at both honestly.", "Her planın faydaları ve sakıncaları vardır, o yüzden ikisine de dürüstçe bakalım.", ["Every plan has benefits and drawbacks, so let's honestly look at both."], ["Her planın artıları ve eksileri var, bu yüzden ikisine de dürüstçe bakalım.", "Her planın faydaları ve dezavantajları vardır, o halde ikisine de dürüstçe bakalım."]],
          ["Our productivity data might convince even the most traditional manager.", "Verimlilik verilerimiz en geleneksel yöneticiyi bile ikna edebilir.", ["Our productivity figures might convince even the most traditional manager."], ["Verimlilik verilerimiz en tutucu yöneticiyi bile ikna edebilir.", "Verimlilik verilerimiz en geleneksel müdürü bile inandırabilir."]],
          ["A flexible schedule shows that the company really trusts its employees.", "Esnek bir program, şirketin çalışanlarına gerçekten güvendiğini gösterir.", ["A flexible schedule shows the company really trusts its employees."], ["Esnek bir çalışma saati şirketin çalışanlarına gerçekten güvendiğini gösterir.", "Esnek bir program şirketin çalışanlarına gerçekten güvendiğini gösteriyor."]],
          ["If you want to win the debate, start with facts, not feelings.", "Tartışmayı kazanmak istiyorsan duygularla değil gerçeklerle başla.", ["If you want to win the debate, begin with facts, not feelings."], ["Tartışmayı kazanmak istiyorsanız duygularla değil gerçeklerle başlayın.", "Münazarayı kazanmak istiyorsan duygularla değil gerçeklerle başla.", "Tartışmayı kazanmak istiyorsan hislerle değil gerçeklerle başla."]]
        ]
      }
    ]
  },
  // ───────────────────────── ÜNİTE 8 ─────────────────────────
  {
    title: "Kültürlerarası İletişim",
    desc: "Kültür farklarını konuşabilecek, İngiliz kibarlığını ve imaları çözebilecek, must have ve can't be ile tahmin yürütebileceksin.",
    cefr: "B2",
    guide: [
      { h: "İngiliz kibarlığı: dolaylı rica", p: "Türkçede 'Pencereyi kapat' demek arkadaş arasında normaldir, İngilizcede 'Close the window' ise kaba duyulur. Rica 'Would you mind + -ing' ile yumuşatılır. Dikkat, 'Would you mind?' sorusuna 'No' demek 'hayır, sakıncası yok' yani EVET demektir. 'I'm afraid' ise korku değil kibar bir 'maalesef'tir.", ex: [["Would you mind opening the door?", "Kapıyı açar mısınız?"], ["I'm afraid we're fully booked.", "Maalesef tamamen doluyuz."]] },
      { h: "İma ve understatement", p: "İngilizler çoğu zaman tam tersini ya da çok daha azını söyler. 'Not bad' genelde 'çok iyi', 'quite interesting' ise 'katılmıyorum' anlamına gelebilir. 'A bit of a problem' büyük bir felaket olabilir. Buna 'understatement' denir. Türkler doğrudan konuşmaya alışık olduğu için bu sinyalleri kaçırır, bu yüzden tona ve bağlama dikkat et.", ex: [["Not bad at all, Deniz.", "Hiç fena değil Deniz, yani çok iyi."], ["We have a bit of a problem.", "Ufak bir sorunumuz var, yani büyük bir sorun."]] },
      { h: "Şimdiki zaman için tahmin: must, might, can't", p: "Kanıta dayalı tahmin yaparken 'must be' (olmalı, eminim), 'might/could be' (olabilir) ve 'can't be' (olamaz) kullanılır. Türklerin tipik hatası olumsuz tahmin için 'mustn't be' demektir. 'Mustn't' yasak anlamı taşır. 'Olamaz' için doğru yapı 'can't be'dir.", ex: [["She must be tired after the flight.", "Uçuştan sonra yorgun olmalı."], ["That can't be true.", "Bu doğru olamaz."]] },
      { h: "Geçmiş için tahmin: must have, might have been", p: "Geçmişle ilgili tahminde modal + have + V3 kullanılır. 'He must have forgotten' (unutmuş olmalı), 'She can't have seen it' (görmüş olamaz), 'It might have been a joke' (şaka olabilirdi). Türkçedeki '-mış olmalı' ve '-mış olabilir' yapılarına birebir denk gelir. 'Must have' konuşmada 'must've' diye kısaltılır, 'must of' diye yazmak yanlıştır.", ex: [["They must have missed the train.", "Treni kaçırmış olmalılar."], ["He can't have meant it.", "Bunu kastetmiş olamaz."]] }
    ],
    story: {
      title: "'Not Bad' Ne Demek?", icon: "🇬🇧",
      lines: [
        ["Anlatıcı", "On Monday morning, Deniz presented his new app design to the whole team.", "Pazartesi sabahı Deniz yeni uygulama tasarımını tüm ekibe sundu."],
        ["Mr. Walker", "Hmm. Not bad, Deniz. Not bad at all.", "Hmm. Fena değil Deniz. Hiç fena değil."],
        ["Deniz", "Only 'not bad'? He must have hated it. My career is over.", "Sadece 'fena değil' mi? Kesin nefret etti. Kariyerim bitti."],
        ["Emma", "Relax. When a British manager says 'not bad', it usually means 'very good'.", "Sakin ol. İngiliz bir yönetici 'fena değil' diyorsa genelde 'çok iyi' demektir."],
        ["Deniz", "So what does 'quite interesting' mean? He said that to Tom last week.", "Peki 'oldukça ilginç' ne demek? Geçen hafta Tom'a öyle dedi."],
        ["Emma", "That means 'I disagree, and we will never speak of this again'.", "O, 'katılmıyorum ve bunu bir daha asla konuşmayacağız' demek."],
        ["Deniz", "And what about 'with all due respect'?", "Peki ya 'kusura bakmayın ama'?"],
        ["Emma", "That one means 'I think you're an idiot', but very politely.", "O da 'bence aptalın tekisin' demek, ama çok kibarca."],
        ["Anlatıcı", "That evening, Deniz called Can and explained British English like a real expert.", "O akşam Deniz Can'ı aradı ve İngiliz İngilizcesini gerçek bir uzman gibi anlattı."],
        ["Deniz", "Can, if a Brit says your food is 'not bad', you've basically won a Michelin star.", "Can, bir İngiliz yemeğine 'fena değil' derse, resmen Michelin yıldızı kazanmışsın demektir."],
        ["Can", "So they can't have liked my kebab photos when they called them 'quite interesting'.", "Demek ki kebap fotoğraflarıma 'oldukça ilginç' dediklerinde beğenmiş olamazlar."]
      ],
      questions: [
        { after: 2, q: "How did Deniz feel after Mr. Walker's comment?", options: ["Proud and happy", "Worried that his boss hated the design", "Bored and tired"], answer: 1 },
        { after: 3, q: "According to Emma, 'not bad' usually means...", options: ["very good", "terrible", "average"], answer: 0 },
        { after: 7, q: "What does 'with all due respect' often really mean?", options: ["I respect you deeply", "I agree completely", "I think you're wrong, but I'm being polite"], answer: 2 },
        { after: 10, q: "What did Can realise about his kebab photos?", options: ["People loved them", "People probably didn't like them", "People wanted to buy them"], answer: 1 }
      ]
    },
    extra: [
      ["not bad", "fena değil (çoğu zaman 'çok iyi')", "👌"], ["quite good", "fena değil, idare eder", ""], ["with all due respect", "kusura bakmayın ama", ""], ["I hear what you say", "ne dediğini anlıyorum (ama katılmıyorum)", ""], ["cheers", "sağ ol, şerefe", "🍻"],
      ["mate", "dostum, kanka", "🙋"], ["brilliant", "harika, muhteşem", "🌟"], ["fancy", "canı istemek", ""], ["bless you", "çok yaşa", "🤧"], ["eye contact", "göz teması", "👀"],
      ["handshake", "tokalaşma", "🤝"], ["personal space", "kişisel alan", ""], ["punctuality", "dakiklik", "⏰"], ["hierarchy", "hiyerarşi", ""], ["formal", "resmi", "👔"],
      ["informal", "samimi, gayriresmi", "👕"], ["body language", "beden dili", "🧍"], ["taboo", "tabu", "🤐"], ["humour", "mizah", "😂"], ["irony", "ironi", ""],
      ["accent", "aksan", "🗣️"], ["dialect", "lehçe, ağız", ""], ["expat", "yurt dışında yaşayan kişi, gurbetçi", "✈️"], ["homesick", "memleket hasreti çeken", "🏡"], ["culture shock", "kültür şoku", "😵"],
      ["hospitality", "misafirperverlik", "🫖"], ["superstition", "batıl inanç", "🧿"], ["bow", "eğilerek selamlamak", "🙇"], ["take offence", "alınmak, gücenmek", ""], ["fair enough", "makul, peki haklısın", ""]
    ],
    lessons: [
      {
        title: "Kültür farkları", icon: "🌍",
        words: [["culture", "kültür", "🌍"], ["custom", "adet, gelenek", ""], ["tradition", "gelenek", "🎎"], ["stereotype", "klişe, kalıp yargı", ""], ["norm", "norm, kural", ""], ["etiquette", "görgü kuralları, adap", "🍽️"], ["background", "geçmiş, köken", ""], ["diversity", "çeşitlilik", "🌈"], ["adapt", "uyum sağlamak", ""], ["misunderstanding", "yanlış anlama", ""]],
        sentences: [
          ["Every culture has its own unwritten rules about time, food and personal questions.", "Her kültürün zaman, yemek ve kişisel sorular hakkında yazılı olmayan kuralları vardır.", ["Every culture has its own unwritten rules about time, food, and personal questions."], ["Her kültürün zaman, yemek ve özel sorularla ilgili yazısız kuralları vardır.", "Her kültürün zaman, yemek ve kişisel sorular konusunda yazılı olmayan kuralları var."]],
          ["In Turkey, it is a custom to offer guests tea the moment they arrive.", "Türkiye'de misafirlere gelir gelmez çay ikram etmek bir gelenektir.", ["In Turkey, it is customary to offer guests tea the moment they arrive."], ["Türkiye'de misafirlere geldikleri anda çay ikram etmek bir adettir.", "Türkiye'de konuklara gelir gelmez çay ikram etmek bir gelenek.", "Türkiye'de misafire gelir gelmez çay ikram etmek adettir."]],
          ["Not every British person loves rain and tea, that is just a stereotype.", "Her İngiliz yağmuru ve çayı sevmez, bu sadece bir klişe.", ["Not all British people love rain and tea, that is just a stereotype."], ["Her İngiliz yağmuru ve çayı sevmez, bu sadece bir kalıp yargı.", "Her İngiliz yağmura ve çaya bayılmaz, bu sadece bir klişe.", "Her İngiliz yağmuru ve çayı sevmez, bu yalnızca bir klişedir."]],
          ["Moving abroad means you have to adapt to new norms very quickly.", "Yurt dışına taşınmak, yeni normlara çok hızlı uyum sağlamak demektir.", ["Moving abroad means you need to adapt to new norms very quickly."], ["Yurt dışına taşınınca yeni normlara çok çabuk uyum sağlaman gerekir.", "Yurt dışına taşınmak yeni kurallara çok hızlı uyum sağlamak zorunda olmak demek.", "Yurt dışına taşınırsan yeni normlara çok hızlı uyum sağlamak zorundasın."]],
          ["Our team is full of diversity, with people from eleven different backgrounds.", "Ekibimiz çok çeşitli, on bir farklı kökenden insan var.", ["Our team is very diverse, with people from eleven different backgrounds."], ["Ekibimizde büyük bir çeşitlilik var, on bir farklı kökenden insan var.", "Ekibimiz çeşitlilikle dolu, on bir farklı geçmişten insanlar var.", "Ekibimiz çok çeşitli, on bir farklı kökenden insanlardan oluşuyor."]],
          ["A small misunderstanding about table etiquette made the dinner rather awkward.", "Sofra adabıyla ilgili küçük bir yanlış anlama yemeği epey tuhaflaştırdı.", ["A small misunderstanding about table manners made the dinner rather awkward."], ["Sofra görgü kurallarıyla ilgili küçük bir yanlış anlaşılma yemeği oldukça garip yaptı.", "Sofra adabı konusundaki küçük bir yanlış anlama yemeği biraz tuhaf bir hale getirdi.", "Sofra adabıyla ilgili ufak bir yanlış anlama akşam yemeğini epey garipleştirdi."]]
        ]
      },
      {
        title: "Nezaket kuralları", icon: "🎩",
        words: [["polite", "kibar", "🎩"], ["rude", "kaba", "😤"], ["apologise", "özür dilemek", "🙏"], ["would you mind", "sakıncası var mı, -ir misiniz", ""], ["I'm afraid", "maalesef, korkarım", ""], ["small talk", "havadan sudan sohbet", "☁️"], ["queue", "sıra, kuyruk", "🧍"], ["awkward", "tuhaf, garip, rahatsız edici", "😬"], ["compliment", "iltifat", "💐"], ["modest", "alçakgönüllü, mütevazı", ""]],
        sentences: [
          ["Would you mind closing the window? It's getting a bit cold in here.", "Pencereyi kapatır mısın? Burası biraz soğumaya başladı.", ["Would you mind shutting the window? It's getting a bit cold in here."], ["Pencereyi kapatabilir misiniz? Burası biraz soğuyor.", "Pencereyi kapatır mısınız? Burası biraz soğumaya başladı.", "Pencereyi kapatmanın sakıncası var mı? Burası biraz soğudu."]],
          ["I'm afraid I can't come tonight, but thank you so much for asking.", "Maalesef bu akşam gelemiyorum ama sorduğun için çok teşekkürler.", ["I'm afraid I can't make it tonight, but thank you so much for asking."], ["Korkarım bu akşam gelemeyeceğim ama davet ettiğin için çok teşekkür ederim.", "Maalesef bu akşam gelemem ama sorduğunuz için çok teşekkürler.", "Ne yazık ki bu akşam gelemiyorum ama sorduğun için çok sağ ol."]],
          ["In Britain, jumping the queue is seen as extremely rude.", "İngiltere'de sırayı kaynatmak son derece kaba bir davranış olarak görülür.", ["In Britain, jumping the queue is considered extremely rude."], ["Britanya'da sıraya kaynak yapmak çok kaba kabul edilir.", "İngiltere'de sırayı atlamak son derece kaba sayılır.", "İngiltere'de sıra kaynatmak aşırı kabalık olarak görülür."]],
          ["British people apologise all the time, even when you step on their foot.", "İngilizler, sen onların ayağına bassan bile sürekli özür diler.", ["British people say sorry all the time, even when you step on their foot."], ["İngilizler siz ayaklarına bassanız bile sürekli özür diler.", "İngilizler sen onların ayağına bassan bile hep özür diliyor.", "İngilizler, ayaklarına bassan bile durmadan özür diler."]],
          ["Small talk about the weather helps people avoid awkward silences in the lift.", "Hava hakkında sohbet, insanların asansördeki garip sessizliklerden kaçınmasına yardım eder.", ["Small talk about the weather helps people avoid awkward silences in the elevator."], ["Hava durumu üzerine laflamak asansördeki tuhaf sessizlikleri önlemeye yardım eder.", "Havadan sudan sohbet insanların asansördeki garip sessizliklerden kaçınmasını sağlar."]],
          ["When Deniz paid her a compliment, Emma was modest and changed the subject.", "Deniz ona iltifat edince Emma alçakgönüllü davrandı ve konuyu değiştirdi.", ["When Deniz gave her a compliment, Emma was modest and changed the subject."], ["Deniz ona iltifat ettiğinde Emma mütevazı davranıp konuyu değiştirdi.", "Deniz ona iltifat edince Emma mütevazı davrandı ve konuyu değiştirdi."]]
        ]
      },
      {
        title: "Satır aralarını oku", icon: "🔍",
        words: [["imply", "ima etmek", ""], ["hint", "ipucu, ima", "💡"], ["indirect", "dolaylı", ""], ["direct", "doğrudan, direkt", "➡️"], ["sarcasm", "alaycılık, iğneleme", "🙃"], ["understatement", "hafife alarak söyleme", ""], ["read between the lines", "satır aralarını okumak", "📖"], ["subtle", "ince, belli belirsiz", ""], ["tone", "ton, üslup", "🎵"], ["literally", "kelimesi kelimesine, gerçekten", ""]],
        sentences: [
          ["When my manager says 'interesting idea', he usually implies that it is terrible.", "Müdürüm 'ilginç fikir' dediğinde genellikle berbat olduğunu ima ediyor.", ["When my manager says 'interesting idea', he usually implies it is terrible."], ["Müdürüm 'ilginç bir fikir' derse genelde berbat olduğunu ima eder.", "Yöneticim 'ilginç fikir' dediğinde çoğu zaman berbat olduğunu ima ediyor."]],
          ["Turks are often quite direct, while the British prefer a more indirect style.", "Türkler genellikle oldukça doğrudan konuşur, İngilizler ise daha dolaylı bir tarzı sever.", ["Turks are often quite direct, whereas the British prefer a more indirect style."], ["Türkler çoğu zaman oldukça direkt, İngilizler ise daha dolaylı bir üslubu tercih ediyor.", "Türkler genelde epey doğrudandır, İngilizler ise daha dolaylı bir tarzı tercih eder."]],
          ["You have to read between the lines to understand what she really means.", "Gerçekte ne demek istediğini anlamak için satır aralarını okuman gerekiyor.", ["To understand what she really means, you have to read between the lines."], ["Ne demek istediğini gerçekten anlamak için satır aralarını okumalısın.", "Gerçekte ne kastettiğini anlamak için satır aralarını okuman lazım.", "Aslında ne demek istediğini anlamak için satır aralarını okumanız gerekiyor."]],
          ["Calling a disaster 'a bit of a problem' is a classic British understatement.", "Bir felakete 'ufak bir sorun' demek klasik bir İngiliz hafife alma örneğidir.", ["Calling a disaster 'a bit of a problem' is a typical British understatement."], ["Bir felakete 'küçük bir sorun' demek tipik İngiliz usulü hafife almaktır.", "Bir felakete 'ufak bir sorun' demek klasik İngiliz tarzı hafife almadır."]],
          ["He dropped a subtle hint that he wanted us to leave the party.", "Partiden gitmemizi istediğine dair ince bir ipucu verdi.", ["He gave a subtle hint that he wanted us to leave the party."], ["Partiden gitmemizi istediğini üstü kapalı şekilde ima etti.", "Partiden ayrılmamızı istediğine dair belli belirsiz bir ima yaptı.", "Partiden gitmemizi istediğini ince bir şekilde ima etti."]],
          ["Her tone was so dry that I missed the sarcasm completely.", "Ses tonu o kadar kuruydu ki iğnelemeyi tamamen kaçırdım.", ["Her tone was so dry that I completely missed the sarcasm."], ["Tonu öyle kuruydu ki alaycılığı hiç fark etmedim.", "Ses tonu o kadar kuruydu ki alaycılığı tamamen kaçırdım.", "Sesi o kadar ifadesizdi ki iğnelemeyi hiç anlamadım."]]
        ]
      },
      {
        title: "Olmalı, olamaz", icon: "🕵️",
        words: [["must be", "olmalı", ""], ["can't be", "olamaz", "🙅"], ["might be", "olabilir", ""], ["could be", "olabilir", ""], ["probably", "muhtemelen", ""], ["obviously", "belli ki, açıkça", ""], ["certain", "emin, kesin", ""], ["assume", "varsaymak", ""], ["conclude", "sonucuna varmak", ""], ["clue", "ipucu", "🔎"]],
        sentences: [
          ["Emma hasn't replied all day, so she must be very busy.", "Emma bütün gün cevap vermedi, demek ki çok meşgul olmalı.", ["Emma has not replied all day, so she must be very busy."], ["Emma tüm gün yanıt vermedi, çok meşgul olmalı.", "Emma bütün gün cevap vermedi, o yüzden çok yoğun olmalı.", "Emma gün boyu cevap vermedi, kesin çok meşguldür."]],
          ["That can't be Mr. Walker, he would never wear a pink jumper.", "O Bay Walker olamaz, o asla pembe kazak giymez.", ["That can't be Mr. Walker, he'd never wear a pink jumper."], ["Bu Bay Walker olamaz, asla pembe kazak giymez.", "O Bay Walker olamaz, pembe kazak giyeceği hiç tutmaz.", "O kişi Bay Walker olamaz, o asla pembe bir kazak giymez."]],
          ["The guy at the door might be our new neighbour, or a delivery driver.", "Kapıdaki adam yeni komşumuz ya da bir kurye olabilir.", ["The man at the door might be our new neighbour, or a delivery driver."], ["Kapıdaki adam yeni komşumuz olabilir ya da bir kurye.", "Kapıdaki kişi yeni komşumuz veya bir kurye olabilir.", "Kapıdaki adam yeni komşumuz da olabilir, bir kurye de."]],
          ["If he says 'quite good', it could be praise, or it could be a warning.", "'Fena değil' derse bu bir övgü de olabilir, bir uyarı da.", ["If he says 'quite good', it could be praise or a warning."], ["'Oldukça iyi' derse bu övgü de olabilir uyarı da.", "'Fena değil' diyorsa bu bir övgü de olabilir, bir uyarı da."]],
          ["Don't assume that silence means agreement, it probably means confusion.", "Sessizliğin onay anlamına geldiğini varsayma, muhtemelen kafa karışıklığı demektir.", ["Do not assume that silence means agreement, it probably means confusion."], ["Sessizliği onay sanma, muhtemelen kafaları karışık demektir.", "Sessizliğin kabul anlamına geldiğini varsaymayın, muhtemelen kafa karışıklığı demek."]],
          ["Based on every clue, I can only conclude that Lina ate my cake.", "Tüm ipuçlarına bakınca, pastamı Lina'nın yediği sonucuna varıyorum.", ["Based on all the clues, I can only conclude that Lina ate my cake."], ["Bütün ipuçlarına bakarak tek varabileceğim sonuç, pastamı Lina'nın yediği.", "Her ipucuna bakınca pastamı Lina'nın yediği sonucuna varıyorum.", "Tüm ipuçlarına göre pastamı Lina'nın yediği sonucuna varabilirim ancak."]]
        ]
      },
      {
        title: "Olmuş olmalı", icon: "🧩",
        words: [["must have", "-mış olmalı", ""], ["can't have", "-mış olamaz", ""], ["might have been", "olmuş olabilir", ""], ["may have", "-mış olabilir", ""], ["offended", "gücenmiş, alınmış", "😠"], ["confused", "kafası karışık", "😕"], ["embarrassed", "utanmış, mahcup", "😳"], ["guess", "tahmin etmek, sanmak", ""], ["signal", "işaret, sinyal", "🚦"], ["gesture", "jest, el hareketi", "👋"]],
        sentences: [
          ["Lina must have offended the guests, because they left before dessert.", "Lina misafirleri kırmış olmalı, çünkü tatlıdan önce gittiler.", ["Lina must have offended the guests, as they left before dessert."], ["Lina misafirleri gücendirmiş olmalı çünkü tatlıdan önce ayrıldılar.", "Lina konukları kırmış olmalı, çünkü tatlıdan önce gittiler.", "Lina misafirleri alındırmış olmalı çünkü tatlıdan önce gittiler."]],
          ["He can't have meant it as an insult, he was smiling the whole time.", "Bunu hakaret olarak kastetmiş olamaz, bütün süre gülümsüyordu.", ["He can't have meant it as an insult, he was smiling all the time."], ["Bunu hakaret amacıyla söylemiş olamaz, baştan sona gülümsüyordu.", "Bunu hakaret olarak kastetmiş olamaz, hep gülümsüyordu.", "Hakaret etmek istemiş olamaz, bütün süre gülümsüyordu."]],
          ["It might have been a joke, but nobody in the room laughed.", "Bir şaka olmuş olabilir ama odadaki kimse gülmedi.", ["It may have been a joke, but nobody in the room laughed."], ["Şaka olabilirdi ama odada kimse gülmedi.", "Belki şakaydı ama odadaki hiç kimse gülmedi.", "Bir şaka olabilir ama odada kimse gülmedi."]],
          ["The thumbs-up gesture may have looked rude to some of our foreign clients.", "Başparmak işareti bazı yabancı müşterilerimize kaba görünmüş olabilir.", ["The thumbs-up gesture might have looked rude to some of our foreign clients."], ["Baş parmak hareketi bazı yabancı müşterilerimize kaba gelmiş olabilir.", "Başparmak yukarı işareti bazı yabancı müşterilerimize kaba görünmüş olabilir."]],
          ["I guess she was embarrassed, because her face went bright red.", "Sanırım utanmıştı, çünkü yüzü kıpkırmızı oldu.", ["I guess she was embarrassed, as her face went bright red."], ["Galiba utandı çünkü yüzü kıpkırmızı kesildi.", "Sanırım mahcup olmuştu, çünkü yüzü kıpkırmızı oldu.", "Bence utanmıştı çünkü yüzü kıpkırmızı oldu."]],
          ["Deniz looked confused, he must have missed some cultural signal.", "Deniz'in kafası karışmış görünüyordu, bir kültürel işareti kaçırmış olmalıydı.", ["Deniz looked confused, he must have missed a cultural signal."], ["Deniz şaşkın görünüyordu, bir kültürel sinyali kaçırmış olmalıydı.", "Deniz'in kafası karışık görünüyordu, kültürel bir işareti kaçırmış olmalı.", "Deniz'in kafası karışmıştı, bir kültürel işareti kaçırmış olmalı."]]
        ]
      }
    ]
  },
  // ───────────────────────── ÜNİTE 9 ─────────────────────────
  {
    title: "Deyimler I",
    desc: "En sık kullanılan İngilizce deyimleri anlayıp doğru yerde kullanabilecek, kelimesi kelimesine çeviri tuzağından kurtulacaksın.",
    cefr: "B2",
    guide: [
      { h: "Deyim nedir, neden çevrilmez?", p: "Deyimlerin anlamı kelimelerin toplamından çıkmaz. 'Piece of cake' bir dilim pasta değil, 'çocuk oyuncağı' demektir. Türkçede de 'etekleri zil çalmak' bir İngilize çok garip gelir. Deyimi gördüğünde kelimelere değil, bütün ifadeye ve bağlama bak. Bazılarının Türkçede neredeyse birebir karşılığı vardır, 'kill two birds with one stone' tam olarak 'bir taşla iki kuş vurmak'tır.", ex: [["The exam was a piece of cake.", "Sınav çocuk oyuncağıydı."], ["Let's kill two birds with one stone.", "Bir taşla iki kuş vuralım."]] },
      { h: "Deyimlerde fiil çekimi", p: "Deyimdeki fiil normal bir fiil gibi çekimlenir, zamana ve özneye göre değişir. 'Hit the sack' geçmişte 'I hit the sack at ten', 'break the ice' geçmişte 'he broke the ice' olur. Ama deyimin diğer kelimeleri değiştirilmez. 'Break the ices' ya da 'a piece of cakes' denmez.", ex: [["She broke the ice with a joke.", "Bir şakayla buzları kırdı."], ["I hit the sack early last night.", "Dün gece erkenden yattım."]] },
      { h: "Ne zaman kullanmalı?", p: "Deyimler çoğunlukla gündelik konuşmada kullanılır. İş e-postasında 'It costs an arm and a leg' yerine 'It is very expensive' daha uygundur. Ayrıca bir deyimi çok sık kullanmak yapay durur. Önce dinlerken tanımayı öğren, sonra emin olduklarını konuşmana yavaş yavaş kat.", ex: [["This laptop cost an arm and a leg.", "Bu laptop servet değerindeydi."], ["The laptop was very expensive.", "Laptop çok pahalıydı."]] }
    ],
    story: {
      title: "Can Londra'da", icon: "🐱",
      lines: [
        ["Anlatıcı", "Can finally visited London, and Deniz wanted to show him real British English.", "Can sonunda Londra'ya geldi ve Deniz ona gerçek İngiliz İngilizcesini göstermek istedi."],
        ["Deniz", "Lina, this is Can. Don't worry, talking to him is a piece of cake.", "Lina, bu Can. Merak etme, onunla konuşmak çocuk oyuncağı."],
        ["Can", "Why is everyone talking about cake? I haven't eaten anything since Istanbul.", "Neden herkes pastadan bahsediyor? İstanbul'dan beri hiçbir şey yemedim."],
        ["Lina", "Ha! I like him already. You two are in the same boat with idioms.", "Ha! Onu şimdiden sevdim. Deyimler konusunda ikiniz aynı gemidesiniz."],
        ["Anlatıcı", "Later that night, it started raining cats and dogs, and Can ran to the window.", "O gece daha sonra bardaktan boşanırcasına yağmur başladı ve Can pencereye koştu."],
        ["Can", "Deniz, where are all the cats? I can only see one angry pigeon.", "Deniz, bütün kediler nerede? Sadece sinirli bir güvercin görüyorum."],
        ["Deniz", "It just means it's raining very hard. Anyway, let's hit the sack, it's late.", "Sadece çok şiddetli yağmur yağıyor demek. Neyse, hadi yatalım, geç oldu."],
        ["Can", "I'm not hitting anything! I'm a peaceful man, Deniz.", "Hiçbir şeye vurmuyorum! Ben barışçıl bir adamım, Deniz."],
        ["Lina", "Don't worry, Can. Even Londoners get idioms wrong once in a blue moon.", "Merak etme Can. Londralılar bile kırk yılda bir deyimleri yanlış anlar."],
        ["Can", "A blue moon? Okay, now you're definitely pulling my leg.", "Mavi ay mı? Tamam, şimdi kesin benimle dalga geçiyorsunuz."]
      ],
      questions: [
        { after: 2, q: "Why was Can confused at first?", options: ["He thought they were talking about real cake", "He did not like Lina", "He had lost his bag"], answer: 0 },
        { after: 5, q: "What did Can actually see outside?", options: ["Lots of cats and dogs", "One angry pigeon", "A blue moon"], answer: 1 },
        { after: 7, q: "How did Can understand 'hit the sack'?", options: ["As going to the gym", "As eating a late dinner", "As hitting something"], answer: 2 },
        { after: 9, q: "What does Can think at the end?", options: ["That Lina is joking with him", "That London is boring", "That he should go home"], answer: 0 }
      ]
    },
    extra: [
      ["when pigs fly", "balık kavağa çıkınca", "🐷"], ["cry over spilt milk", "olmuşla ölmüşe çare yok, boşuna dövünmek", "🥛"], ["let off steam", "stres atmak, deşarj olmak", "♨️"], ["go the extra mile", "fazlasını yapmak, ekstra çaba göstermek", ""], ["get cold feet", "son anda cesaretini kaybetmek", "🥶"],
      ["cut to the chase", "sadede gelmek", ""], ["hang in there", "dayan, pes etme", "💪"], ["jump on the bandwagon", "akıma kapılmak, modaya uymak", ""], ["miss the boat", "fırsatı kaçırmak", "⛵"], ["on thin ice", "riskli durumda, pamuk ipliğine bağlı", "🧊"],
      ["out of the blue", "durduk yere, birdenbire", ""], ["sit on the fence", "taraf tutmamak, kararsız kalmak", ""], ["the tip of the iceberg", "buzdağının görünen kısmı", "🏔️"], ["take it with a pinch of salt", "ihtiyatla yaklaşmak, şüpheyle karşılamak", "🧂"], ["throw in the towel", "havlu atmak, pes etmek", "🏳️"],
      ["up in the air", "belirsiz, havada", ""], ["you can say that again", "aynen öyle, çok haklısın", ""], ["actions speak louder than words", "icraat sözden daha etkilidir", ""], ["add fuel to the fire", "yangına körükle gitmek", "🔥"], ["barking up the wrong tree", "yanlış kapı çalmak", "🌳"],
      ["cut someone some slack", "birine tolerans göstermek", ""], ["don't judge a book by its cover", "görünüşe aldanma", "📕"], ["easier said than done", "söylemesi kolay", ""], ["get out of hand", "kontrolden çıkmak", ""], ["keep an eye on", "göz kulak olmak", "👁️"],
      ["over the moon", "sevinçten uçmak, çok mutlu", "🌙"], ["speak of the devil", "iti an çomağı hazırla", "😈"], ["a storm in a teacup", "bir bardak suda fırtına", "🍵"], ["through thick and thin", "iyi günde kötü günde", ""], ["rule of thumb", "pratik kural, genel kural", "👍"]
    ],
    lessons: [
      {
        title: "Sosyal deyimler", icon: "🧊",
        words: [["break the ice", "buzları kırmak", "🧊"], ["hit it off", "hemen kaynaşmak, iyi anlaşmak", ""], ["see eye to eye", "aynı fikirde olmak", "👀"], ["give someone the cold shoulder", "birine soğuk davranmak", "🥶"], ["spill the beans", "ağzından kaçırmak, sırrı açmak", "🫘"], ["let the cat out of the bag", "baklayı ağzından çıkarmak", "🐈"], ["get on like a house on fire", "çok iyi anlaşmak", ""], ["in the same boat", "aynı gemide, aynı durumda", "🚣"], ["on the same page", "aynı düşüncede, mutabık", "📄"], ["the life of the party", "eğlencenin ruhu, ortamın neşesi", "🎉"]],
        sentences: [
          ["Can told a silly joke about his name to break the ice at the party.", "Can partide buzları kırmak için adıyla ilgili saçma bir şaka yaptı.", ["To break the ice at the party, Can told a silly joke about his name."], ["Can partide buzu kırmak için ismiyle ilgili aptalca bir espri yaptı.", "Can partide buzları kırmak için adı hakkında saçma bir şaka yaptı.", "Partide buzları kırmak için Can adıyla ilgili saçma bir espri yaptı."]],
          ["Can and Lina hit it off immediately and talked about food for hours.", "Can ve Lina hemen kaynaştılar ve saatlerce yemek hakkında konuştular.", ["Can and Lina hit it off right away and talked about food for hours."], ["Can ile Lina hemen anlaştılar ve saatlerce yemekten konuştular.", "Can ve Lina hemen kaynaşıp saatlerce yemek hakkında konuştu.", "Can ile Lina anında kaynaştı ve saatlerce yemek üzerine sohbet ettiler."]],
          ["Deniz and his boss rarely see eye to eye about deadlines.", "Deniz ve patronu teslim tarihleri konusunda nadiren aynı fikirde olur.", ["Deniz and his boss seldom see eye to eye about deadlines."], ["Deniz ile patronu teslim tarihleri konusunda nadiren anlaşır.", "Deniz ve patronu son tarihler konusunda nadiren aynı fikirdedir.", "Deniz ve patronu teslim tarihlerinde pek nadir aynı fikirde olur."]],
          ["Please don't spill the beans, the party is supposed to be a surprise.", "Lütfen ağzından kaçırma, parti sürpriz olacak.", ["Please don't spill the beans, the party should be a surprise."], ["Lütfen sırrı açığa vurma, partinin sürpriz olması gerekiyor.", "Lütfen ağzından bir şey kaçırma, partinin sürpriz olması lazım.", "Lütfen ağzından kaçırmayın, parti sürpriz olacak."]],
          ["When Lina said he let the cat out of the bag, Can looked for a cat.", "Lina baklayı ağzından çıkardığını söyleyince Can bir kedi aradı.", ["Can looked for a cat when Lina said he let the cat out of the bag."], ["Lina onun baklayı ağzından çıkardığını söyleyince Can kedi aramaya başladı.", "Lina sırrı ağzından kaçırdığını söylediğinde Can bir kedi aradı."]],
          ["We're all in the same boat, so let's stay on the same page.", "Hepimiz aynı gemideyiz, o yüzden aynı düşüncede kalalım.", ["We are all in the same boat, so let's stay on the same page."], ["Hepimiz aynı durumdayız, bu yüzden aynı çizgide kalalım.", "Hepimiz aynı gemideyiz, bu yüzden aynı fikirde kalalım.", "Hepimiz aynı gemideyiz, o halde aynı sayfada kalalım."]]
        ]
      },
      {
        title: "Kolay mı zor mu?", icon: "🍰",
        words: [["piece of cake", "çocuk oyuncağı, çok kolay", "🍰"], ["a walk in the park", "çok kolay iş", "🌳"], ["hit the nail on the head", "tam üstüne basmak, taşı gediğine koymak", "🔨"], ["bite off more than you can chew", "boyundan büyük işe kalkışmak", ""], ["the last straw", "bardağı taşıran son damla", "🥤"], ["back to square one", "başa dönmek, sıfıra dönmek", "🔄"], ["cut corners", "işi baştan savma yapmak", "✂️"], ["learn the ropes", "işin inceliklerini öğrenmek", "🪢"], ["a blessing in disguise", "görünüşte kötü ama hayırlı olan şey", ""], ["call it a day", "paydos etmek, bugünlük bırakmak", "🛑"]],
        sentences: [
          ["The driving test was a piece of cake, but parking was a different story.", "Ehliyet sınavı çocuk oyuncağıydı ama park etmek başka bir hikâyeydi.", ["The driving test was a piece of cake, but parking was another story."], ["Sürüş sınavı çok kolaydı ama park etmek ayrı bir meseleydi.", "Direksiyon sınavı çocuk oyuncağıydı ama park etmek bambaşka bir hikâyeydi.", "Ehliyet sınavı çok kolaydı ama park etmek başka bir hikâyeydi."]],
          ["You hit the nail on the head, the real problem is the budget.", "Tam üstüne bastın, asıl sorun bütçe.", ["You hit the nail on the head, the budget is the real problem."], ["Taşı gediğine koydun, asıl sorun bütçe.", "Tam isabet, asıl sorun bütçe.", "Tam üstüne bastınız, asıl sorun bütçedir."]],
          ["I think I bit off more than I could chew with three projects at once.", "Sanırım aynı anda üç projeyle boyumdan büyük işe kalkıştım.", ["With three projects at once, I think I bit off more than I could chew."], ["Galiba aynı anda üç projeyle boyumu aşan bir işe kalkıştım.", "Sanırım aynı anda üç proje alarak boyumdan büyük işe kalkıştım."]],
          ["The server crashed again, so we are back to square one.", "Sunucu yine çöktü, yani başa döndük.", ["The server has crashed again, so we are back to square one."], ["Sunucu tekrar çöktü, bu yüzden en başa döndük.", "Sunucu yine çöktü, sıfıra döndük.", "Sunucu yine çöktü, o yüzden başa döndük."]],
          ["Losing that job was a blessing in disguise, because I found a much better one.", "O işi kaybetmek hayırlı oldu, çünkü çok daha iyisini buldum.", ["Losing that job turned out to be a blessing in disguise, because I found a better one."], ["O işten çıkmam hayırlı oldu çünkü çok daha iyi bir iş buldum.", "O işi kaybetmek aslında iyi oldu, çünkü çok daha iyisini buldum.", "O işi kaybetmem hayra alamet oldu çünkü çok daha iyisini buldum."]],
          ["We've worked for ten hours without a break, so let's call it a day.", "On saattir aralıksız çalışıyoruz, o yüzden bugünlük paydos edelim.", ["We have worked for ten hours without a break, so let's call it a day."], ["On saattir mola vermeden çalışıyoruz, artık bugünlük bırakalım.", "On saattir hiç ara vermeden çalıştık, hadi paydos edelim.", "On saattir molasız çalışıyoruz, o yüzden bugünlük bu kadar yeter."]]
        ]
      },
      {
        title: "Uyku, sağlık, ruh hali", icon: "😴",
        words: [["hit the sack", "yatmak, kafayı vurup yatmak", "🛏️"], ["under the weather", "keyifsiz, biraz rahatsız", "🤒"], ["feel blue", "hüzünlü hissetmek, canı sıkkın olmak", "💙"], ["on cloud nine", "havalara uçmak, çok mutlu olmak", "☁️"], ["sleep like a log", "ölü gibi uyumak, deliksiz uyumak", "🪵"], ["as fit as a fiddle", "turp gibi, sapasağlam", "🎻"], ["burn the midnight oil", "gece geç saatlere kadar çalışmak", "🕯️"], ["on edge", "gergin, diken üstünde", ""], ["butterflies in my stomach", "heyecandan içim içime sığmıyor", "🦋"], ["get some shut-eye", "biraz kestirmek, biraz uyumak", "😴"]],
        sentences: [
          ["I'm exhausted after the long flight, so I'm going to hit the sack early.", "Uzun uçuştan sonra çok yorgunum, o yüzden erkenden yatacağım.", ["I am exhausted after the long flight, so I will hit the sack early."], ["Uzun uçuştan sonra bitkinim, bu yüzden erken yatacağım.", "Uzun uçuştan sonra çok yorgunum, erkenden yatıyorum.", "Uzun yolculuktan sonra çok yorgunum, o yüzden erken yatacağım."]],
          ["Can heard 'hit the sack' and asked Deniz why he wanted to punch a bag.", "Can 'hit the sack' ifadesini duyunca Deniz'e neden çuvala vurmak istediğini sordu.", ["When Can heard 'hit the sack', he asked Deniz why he wanted to punch a bag."], ["Can 'hit the sack' lafını duyunca Deniz'e neden çuvala yumruk atmak istediğini sordu.", "Can bu deyimi duyunca Deniz'e neden bir çuvala vurmak istediğini sordu."]],
          ["Emma is feeling a bit under the weather, so she's working from home today.", "Emma kendini biraz keyifsiz hissediyor, bu yüzden bugün evden çalışıyor.", ["Emma feels a bit under the weather, so she is working from home today."], ["Emma biraz rahatsız, o yüzden bugün evden çalışıyor.", "Emma kendini pek iyi hissetmiyor, bu yüzden bugün evden çalışıyor.", "Emma biraz hasta gibi, o yüzden bugün evden çalışıyor."]],
          ["After the long walk around London, Can slept like a log until noon.", "Londra'daki uzun yürüyüşten sonra Can öğlene kadar ölü gibi uyudu.", ["Can slept like a log until noon after the long walk around London."], ["Londra'yı uzun uzun gezdikten sonra Can öğlene kadar deliksiz uyudu.", "Londra'da uzun bir yürüyüşten sonra Can öğlene kadar mışıl mışıl uyudu.", "Londra'daki uzun yürüyüşün ardından Can öğlene kadar deliksiz uyudu."]],
          ["Deniz was on cloud nine after Emma agreed to have dinner with him.", "Emma onunla yemeğe çıkmayı kabul edince Deniz havalara uçtu.", ["After Emma agreed to have dinner with him, Deniz was on cloud nine."], ["Emma onunla akşam yemeğine çıkmayı kabul ettikten sonra Deniz havalara uçtu.", "Emma onunla yemek yemeyi kabul edince Deniz'in ayakları yere basmadı.", "Emma yemek davetini kabul edince Deniz çok mutlu oldu."]],
          ["Before every exam, I burn the midnight oil and feel totally on edge.", "Her sınavdan önce gece geç saatlere kadar çalışırım ve çok gergin olurum.", ["I burn the midnight oil before every exam and feel totally on edge."], ["Her sınavdan önce sabahlara kadar çalışırım ve tamamen diken üstünde olurum.", "Her sınav öncesi gece yarılarına kadar çalışıyorum ve çok geriliyorum.", "Her sınavdan önce geç saatlere kadar çalışır ve çok gerilirim."]]
        ]
      },
      {
        title: "Para deyimleri", icon: "💸",
        words: [["cost an arm and a leg", "çok pahalı olmak, servet değerinde olmak", "💸"], ["break the bank", "çok pahalıya patlamak, cebi yakmak", "🏦"], ["a rip-off", "kazık, fahiş fiyat", ""], ["tighten your belt", "kemer sıkmak", "🪢"], ["pay through the nose", "fahiş para ödemek, kazıklanmak", "👃"], ["make ends meet", "iki yakasını bir araya getirmek", ""], ["in the red", "eksiye düşmüş, borçta", "🔴"], ["bring home the bacon", "eve ekmek getirmek", "🥓"], ["money doesn't grow on trees", "para ağaçta yetişmiyor", "🌳"], ["splash out", "bol para harcamak, kendini şımartmak", "💦"]],
        sentences: [
          ["A cup of coffee in central London can cost an arm and a leg.", "Londra'nın merkezinde bir fincan kahve servet değerinde olabilir.", ["In central London, a cup of coffee can cost an arm and a leg."], ["Londra merkezinde bir kahve çok pahalı olabilir.", "Londra'nın merkezinde bir fincan kahve dudak uçuklatan bir fiyata olabilir.", "Londra merkezinde bir fincan kahve bir servete mal olabilir."]],
          ["Twelve pounds for a tiny sandwich? That's a total rip-off!", "Minicik bir sandviç için on iki sterlin mi? Bu tam bir kazık!", ["Twelve pounds for a small sandwich? That's a total rip-off!"], ["Küçücük bir sandviçe on iki sterlin mi? Bu resmen kazık!", "Ufacık bir sandviç için on iki pound mu? Bu tam bir kazık!"]],
          ["Since my bank account is in the red, I need to tighten my belt.", "Banka hesabım eksiye düştüğü için kemerimi sıkmam gerek.", ["My bank account is in the red, so I need to tighten my belt."], ["Hesabım eksiye düştüğü için kemer sıkmam lazım.", "Banka hesabım eksiyde olduğundan kemer sıkmam gerekiyor.", "Banka hesabım ekside olduğu için kemerleri sıkmam gerek."]],
          ["Many young people in London struggle to make ends meet every month.", "Londra'daki birçok genç her ay iki yakasını bir araya getirmekte zorlanıyor.", ["Every month, many young people in London struggle to make ends meet."], ["Londra'da pek çok genç her ay geçinmekte zorlanıyor.", "Londra'daki birçok genç her ay ay sonunu getirmekte zorlanıyor.", "Londra'daki pek çok genç her ay iki yakasını bir araya getirmekte zorlanır."]],
          ["Can paid through the nose for a taxi because he didn't understand the meter.", "Can taksimetreyi anlamadığı için taksiye fahiş para ödedi.", ["Can paid through the nose for a taxi because he did not understand the meter."], ["Can taksimetreyi anlamadığı için taksiciye kazıklandı.", "Can taksimetreyi anlamadığından taksi için çok fazla para ödedi.", "Can taksimetreyi çözemediği için taksiye fahiş bir ücret ödedi."]],
          ["One nice dinner won't break the bank, so let's splash out tonight.", "Güzel bir akşam yemeği bizi batırmaz, hadi bu akşam biraz savuralım.", ["One nice dinner will not break the bank, so let's splash out tonight."], ["Güzel bir yemek cebimizi yakmaz, bu akşam kendimizi şımartalım.", "Bir güzel akşam yemeği bizi batırmaz, hadi bu akşam bol harcayalım.", "Güzel bir akşam yemeği cebimizi yakmaz, bu gece kendimizi şımartalım."]]
        ]
      },
      {
        title: "Zaman ve şans deyimleri", icon: "🌙",
        words: [["once in a blue moon", "kırk yılda bir", "🌙"], ["in the nick of time", "son anda, tam zamanında", "⏱️"], ["at the drop of a hat", "hiç düşünmeden, hemen", "🎩"], ["beat around the bush", "lafı dolandırmak", "🌿"], ["kill two birds with one stone", "bir taşla iki kuş vurmak", "🐦"], ["the ball is in your court", "top sende, karar senin", "🎾"], ["pull someone's leg", "birini işletmek, şaka yapmak", "🦵"], ["raining cats and dogs", "bardaktan boşanırcasına yağmak", "🌧️"], ["better late than never", "geç olsun güç olmasın", "🐢"], ["every cloud has a silver lining", "her şerde bir hayır vardır", "🌥️"]],
        sentences: [
          ["I only eat fast food once in a blue moon, usually after midnight.", "Kırk yılda bir fast food yerim, genelde de gece yarısından sonra.", ["I eat fast food only once in a blue moon, usually after midnight."], ["Kırk yılda bir fast food yiyorum, o da genelde gece yarısından sonra.", "Fast foodu kırk yılda bir yerim, çoğunlukla gece yarısından sonra.", "Sadece kırk yılda bir hazır yemek yerim, genelde gece yarısından sonra."]],
          ["We reached the gate in the nick of time, just before it closed.", "Kapı kapanmadan hemen önce, son anda kapıya yetiştik.", ["We got to the gate in the nick of time, just before it closed."], ["Kapıya tam son anda, kapanmadan hemen önce yetiştik.", "Kapı kapanmadan hemen önce son anda kapıya vardık.", "Son anda, kapı kapanmadan hemen önce kapıya yetiştik."]],
          ["Stop beating around the bush and tell me what happened to my laptop.", "Lafı dolandırmayı bırak ve dizüstü bilgisayarıma ne olduğunu söyle.", ["Stop beating around the bush and tell me what happened to my laptop!"], ["Lafı dolandırmayı bırak da laptopuma ne olduğunu söyle.", "Lafı evirip çevirmeyi bırak ve bilgisayarıma ne olduğunu anlat.", "Lafı dolandırmayı bırakın ve dizüstü bilgisayarıma ne olduğunu söyleyin."]],
          ["By cycling to work, I kill two birds with one stone, exercise and savings.", "İşe bisikletle giderek bir taşla iki kuş vuruyorum, hem spor hem tasarruf.", ["I kill two birds with one stone by cycling to work, exercise and savings."], ["İşe bisikletle gidince bir taşla iki kuş vuruyorum, hem egzersiz hem tasarruf.", "Bisikletle işe giderek bir taşla iki kuş vuruyorum, hem spor hem de para."]],
          ["It's raining cats and dogs, and Can is checking the sky for animals.", "Bardaktan boşanırcasına yağmur yağıyor ve Can gökyüzünde hayvan arıyor.", ["It is raining cats and dogs, and Can is checking the sky for animals."], ["Yağmur bardaktan boşanırcasına yağıyor, Can da gökyüzünde hayvan arıyor.", "Şakır şakır yağmur yağıyor ve Can gökyüzünde hayvan arıyor.", "Bardaktan boşanırcasına yağıyor ve Can gökyüzünde hayvanlara bakıyor."]],
          ["Relax, I'm just pulling your leg, the meeting isn't cancelled.", "Rahatla, sadece seninle dalga geçiyorum, toplantı iptal edilmedi.", ["Relax, I am just pulling your leg, the meeting is not cancelled."], ["Sakin ol, sadece şaka yapıyorum, toplantı iptal olmadı.", "Rahat ol, sadece seni işletiyorum, toplantı iptal edilmedi.", "Rahatla, sadece şaka yapıyorum, toplantı iptal edilmedi."]]
        ]
      }
    ]
  }
];
