(window.LIBRARY = window.LIBRARY || []).push(
  { id: "lib7a", title: "Duygular ve Kişilik (İleri)", icon: "🎭", cefr: "C1", desc: "İnce duygu tonlarını ve karakter özelliklerini anlatan ileri seviye kelimeler",
    words: [
      ["smug", "kendini beğenmiş, halinden fazla memnun", "😏", "He gave me a smug smile after winning the argument.", "Tartışmayı kazandıktan sonra bana kendini beğenmiş bir gülümseme attı."],
      ["bashful", "utangaç, mahcup", "☺️", "She was too bashful to accept the compliment gracefully.", "İltifatı zarifçe kabul edemeyecek kadar utangaçtı."],
      ["vindictive", "kinci, intikamcı", "", "A vindictive manager can make the whole office miserable.", "Kinci bir yönetici bütün ofisi mutsuz edebilir."],
      ["compassionate", "şefkatli, merhametli", "🤲", "The nurse was compassionate and patient with every frightened patient.", "Hemşire korkmuş her hastaya karşı şefkatli ve sabırlıydı."],
      ["obstinate", "inatçı, dik kafalı", "", "My grandfather is too obstinate to admit he needs glasses.", "Dedem gözlüğe ihtiyacı olduğunu kabul edemeyecek kadar inatçı."],
      ["euphoric", "coşkulu, aşırı mutlu", "🥳", "The fans were euphoric when their team scored in the final minute.", "Takımları son dakikada gol atınca taraftarlar coşkudan kendinden geçti."],
      ["despondent", "umutsuz, morali bozuk", "", "After the third rejection, he felt completely despondent about his career.", "Üçüncü retten sonra kariyeri konusunda tamamen umutsuzluğa kapıldı."],
      ["disillusioned", "hayal kırıklığına uğramış, gözü açılmış", "", "Many young voters feel disillusioned with politics these days.", "Bugünlerde birçok genç seçmen siyasetten hayal kırıklığına uğramış hissediyor."],
      ["flustered", "telaşlanmış, şaşkına dönmüş", "😳", "She got flustered when the interviewer asked an unexpected question.", "Görüşmeci beklenmedik bir soru sorunca telaşlandı."],
      ["crestfallen", "yüzü düşmüş, hevesi kırılmış", "", "He looked crestfallen when he heard the trip was cancelled.", "Gezinin iptal edildiğini duyunca yüzü düştü."],
      ["jaded", "bıkkın, her şeyden bıkmış", "", "After ten years in sales, she had become jaded and tired.", "Satışta on yıl geçirdikten sonra bıkkın ve yorgun biri olmuştu."],
      ["sullen", "somurtkan, asık suratlı", "😒", "The teenager sat in sullen silence throughout the family dinner.", "Genç, aile yemeği boyunca somurtkan bir sessizlik içinde oturdu."],
      ["petulant", "huysuz, şımarık ve alıngan", "", "His petulant reaction to criticism surprised everyone in the meeting.", "Eleştiriye verdiği huysuz tepki toplantıdaki herkesi şaşırttı."],
      ["vain", "kibirli, kendine hayran", "🪞", "He is so vain that he checks his reflection in every window.", "O kadar kendine hayran ki her camda yansımasına bakıyor."],
      ["conceited", "kendini beğenmiş", "", "She is talented, but not conceited about her success.", "Yetenekli ama başarısı konusunda kendini beğenmiş değil."],
      ["self-righteous", "kendini haklı ve üstün gören", "", "I find his self-righteous tone really hard to listen to.", "Kendini haklı gören o tavrını dinlemek bana gerçekten zor geliyor."],
      ["sanctimonious", "ahlak hocası tavırlı, ukala", "", "Nobody enjoys a sanctimonious lecture about their eating habits.", "Kimse yeme alışkanlıkları hakkında ahlak hocası tavırlı bir nutuktan hoşlanmaz."],
      ["magnanimous", "yüce gönüllü, bağışlayıcı", "", "She was magnanimous in victory and praised her opponent warmly.", "Zaferde yüce gönüllü davrandı ve rakibini içtenlikle övdü."],
      ["benevolent", "iyiliksever, hayırsever", "😇", "The village was supported by a benevolent local businessman.", "Köy, iyiliksever yerel bir iş insanı tarafından destekleniyordu."],
      ["spiteful", "kötü niyetli, nispet yapan", "", "Leaving that comment on her photo was a spiteful thing to do.", "Fotoğrafına o yorumu bırakmak kötü niyetli bir davranıştı."],
      ["malicious", "kötü niyetli, zarar vermeye yönelik", "", "The rumour was malicious and completely untrue.", "Söylenti kötü niyetliydi ve tamamen asılsızdı."],
      ["amiable", "cana yakın, hoş sohbet", "🙂", "Our new neighbour seems like an amiable and helpful man.", "Yeni komşumuz cana yakın ve yardımsever birine benziyor."],
      ["affable", "sıcakkanlı, kolay konuşulan", "", "The affable receptionist made every guest feel welcome.", "Sıcakkanlı resepsiyonist her misafiri hoş karşılanmış hissettirdi."],
      ["gregarious", "sosyal, kalabalığı seven", "🎉", "She is gregarious and always the first to start a conversation.", "Çok sosyal biridir ve sohbeti başlatan hep ilk o olur."],
      ["reticent", "ketum, ağzı sıkı", "🤐", "He was reticent about his reasons for leaving the company.", "Şirketten ayrılma nedenleri konusunda ketum davrandı."],
      ["diffident", "kendine güvensiz, çekingen", "", "The diffident student rarely raised his hand in class.", "Çekingen öğrenci derste nadiren el kaldırırdı."],
      ["timid", "ürkek, çekingen", "🐭", "The timid puppy hid behind the sofa when guests arrived.", "Ürkek yavru köpek misafirler gelince kanepenin arkasına saklandı."],
      ["meek", "uysal, boyun eğen", "", "Don't be so meek, you have every right to complain.", "Bu kadar uysal olma, şikâyet etmeye her türlü hakkın var."],
      ["tenacious", "azimli, yılmaz", "💪", "She is tenacious and never gives up on a difficult problem.", "Azimlidir ve zor bir problemden asla vazgeçmez."],
      ["steadfast", "sarsılmaz, sadık, kararlı", "", "His parents remained steadfast in their support for his decision.", "Ailesi kararına verdikleri destekte sarsılmaz kaldı."],
      ["fickle", "dönek, hevesi çabuk değişen", "", "Fashion is fickle, and today's trend is tomorrow's joke.", "Moda dönektir ve bugünün trendi yarının şakasıdır."],
      ["erratic", "düzensiz, tutarsız", "", "His erratic behaviour worried his colleagues and friends.", "Tutarsız davranışları iş arkadaşlarını ve dostlarını endişelendirdi."],
      ["hot-headed", "aceleci, çabuk parlayan", "🔥", "A hot-headed driver started shouting at us at the traffic lights.", "Çabuk parlayan bir sürücü trafik ışıklarında bize bağırmaya başladı."],
      ["short-tempered", "sabırsız, çabuk sinirlenen", "", "I get short-tempered when I haven't slept enough.", "Yeterince uyumadığımda çabuk sinirlenirim."],
      ["even-tempered", "sakin mizaçlı, dengeli", "", "Our even-tempered coach never raises his voice at the players.", "Sakin mizaçlı koçumuz oyunculara asla sesini yükseltmez."],
      ["level-headed", "aklı başında, soğukkanlı", "🧠", "We need someone level-headed to handle this crisis.", "Bu krizi yönetmek için aklı başında birine ihtiyacımız var."],
      ["composed", "sakin, kendine hâkim", "", "She stayed composed even when the audience started booing.", "Seyirciler yuhalamaya başladığında bile sakinliğini korudu."],
      ["detached", "mesafeli, duygusal olarak kopuk", "", "He sounded strangely detached when he talked about his childhood.", "Çocukluğundan bahsederken tuhaf bir şekilde mesafeli konuşuyordu."],
      ["indifferent", "kayıtsız, umursamaz", "🤷", "She seemed indifferent to the result of the election.", "Seçim sonucuna kayıtsız görünüyordu."],
      ["apathetic", "ilgisiz, duyarsız", "", "It's hard to motivate an apathetic team before a deadline.", "Teslim tarihinden önce ilgisiz bir ekibi motive etmek zordur."],
      ["listless", "halsiz, isteksiz", "", "The heat made everyone feel listless and sleepy.", "Sıcak herkesi halsiz ve uykulu hissettirdi."],
      ["lethargic", "uyuşuk, bitkin", "🥱", "I always feel lethargic after a heavy lunch.", "Ağır bir öğle yemeğinden sonra hep uyuşuk hissederim."],
      ["perturbed", "huzursuz, tedirgin", "", "She was perturbed by the strange noises coming from the flat upstairs.", "Üst kattaki daireden gelen tuhaf seslerden tedirgin oldu."],
      ["unnerved", "sinirleri bozulmuş, ürkmüş", "", "The long silence on the phone unnerved me a little.", "Telefondaki uzun sessizlik beni biraz ürküttü."],
      ["rattled", "sarsılmış, paniğe kapılmış", "", "The goalkeeper looked rattled after the first mistake.", "Kaleci ilk hatadan sonra sarsılmış görünüyordu."],
      ["distraught", "perişan, kahrolmuş", "😭", "The distraught owner searched for his lost dog all night.", "Perişan haldeki sahibi kayıp köpeğini bütün gece aradı."],
      ["inconsolable", "teselli edilemez", "", "The little girl was inconsolable after her balloon flew away.", "Balonu uçup gidince küçük kız teselli edilemez hale geldi."],
      ["grief-stricken", "acıdan yıkılmış", "", "The grief-stricken family thanked everyone who attended the funeral.", "Acıdan yıkılmış aile cenazeye katılan herkese teşekkür etti."],
      ["forlorn", "kimsesiz ve üzgün, çaresiz", "", "A forlorn kitten was sitting alone in the rain.", "Kimsesiz bir yavru kedi yağmurda tek başına oturuyordu."],
      ["morose", "suratsız, karamsar", "", "He became morose and quiet after losing his job.", "İşini kaybettikten sonra karamsar ve sessiz biri oldu."],
      ["glum", "keyifsiz, asık yüzlü", "☹️", "Why do you look so glum on such a sunny day?", "Böyle güneşli bir günde neden bu kadar keyifsiz görünüyorsun?"],
      ["dejected", "morali bozuk, bezgin", "", "The players walked off the pitch looking dejected.", "Oyuncular sahadan morali bozuk bir şekilde çıktı."],
      ["buoyant", "neşeli, iyimser", "🎈", "She was in a buoyant mood after hearing the good news.", "İyi haberi duyduktan sonra neşeli bir ruh halindeydi."],
      ["upbeat", "iyimser, pozitif", "", "Despite the bad results, the manager remained upbeat about the future.", "Kötü sonuçlara rağmen müdür gelecek konusunda iyimser kaldı."],
      ["jubilant", "sevinçli, zafer coşkusu içinde", "🙌", "Jubilant crowds filled the streets after the announcement.", "Duyurudan sonra sevinçli kalabalıklar sokakları doldurdu."],
      ["exuberant", "coşkulu, enerji dolu", "", "The exuberant children ran straight into the sea.", "Coşkulu çocuklar doğrudan denize koştu."],
      ["ecstatic", "kendinden geçmiş, çok mutlu", "🤩", "My sister was ecstatic when she got into her dream university.", "Kız kardeşim hayalindeki üniversiteye girince havalara uçtu."],
      ["blissful", "mutluluk dolu, huzurlu", "", "We spent a blissful week by the lake with no phones.", "Göl kenarında telefonsuz, mutluluk dolu bir hafta geçirdik."],
      ["placid", "durgun, sakin", "", "She has a placid nature and rarely gets upset.", "Sakin bir yapısı var ve nadiren üzülür."],
      ["vindicated", "haklı çıkmış", "✅", "When the report came out, she felt completely vindicated.", "Rapor yayımlandığında kendini tamamen haklı çıkmış hissetti."],
      ["mortified", "utançtan yerin dibine girmiş", "🙈", "I was mortified when I called my teacher Mum by accident.", "Öğretmenime yanlışlıkla anne dediğimde utançtan yerin dibine girdim."],
      ["sheepish", "mahcup, utangaç", "", "He gave a sheepish grin when he admitted eating the last slice.", "Son dilimi yediğini itiraf ederken mahcup bir şekilde sırıttı."],
      ["contrite", "pişman, tövbekâr", "", "He sounded genuinely contrite when he apologised to the team.", "Ekipten özür dilerken gerçekten pişman görünüyordu."],
      ["remorseful", "vicdan azabı çeken", "", "The driver was remorseful and offered to pay for the damage.", "Sürücü vicdan azabı çekiyordu ve hasarı ödemeyi teklif etti."],
      ["guilt-ridden", "suçluluk duygusuyla dolu", "", "She felt guilt-ridden for forgetting her best friend's birthday.", "En iyi arkadaşının doğum gününü unuttuğu için suçluluk duygusuyla doluydu."],
      ["indignation", "öfke, haksızlığa karşı içerleme", "", "There was widespread indignation over the sudden price increase.", "Ani fiyat artışına karşı yaygın bir öfke vardı."],
      ["resentment", "içerleme, kırgınlık", "", "Years of unfair treatment had left him full of resentment.", "Yıllarca süren adaletsiz muamele onu kırgınlıkla doldurmuştu."],
      ["animosity", "düşmanlık, husumet", "", "There is no animosity between us, we just disagree.", "Aramızda düşmanlık yok, sadece aynı fikirde değiliz."],
      ["disdain", "küçümseme, hor görme", "", "She looked at the cheap souvenirs with obvious disdain.", "Ucuz hediyelik eşyalara açık bir küçümsemeyle baktı."],
      ["scorn", "aşağılama, hor görme", "", "His idea was met with scorn at first, but later it worked.", "Fikri ilk başta aşağılamayla karşılandı ama sonra işe yaradı."],
      ["apprehension", "kaygı, endişe", "", "I felt some apprehension before my first day at the new job.", "Yeni işteki ilk günümden önce biraz kaygı duydum."],
      ["trepidation", "korku, tedirginlik", "", "With some trepidation, she opened the envelope with her exam results.", "Biraz tedirginlikle sınav sonuçlarının olduğu zarfı açtı."],
      ["foreboding", "kötü bir şey olacağı hissi", "🌩️", "I had a sense of foreboding as soon as I entered the empty house.", "Boş eve girer girmez kötü bir şey olacakmış gibi hissettim."],
      ["misgiving", "kuşku, içe sinmeme", "", "I had serious misgivings about lending him my car.", "Ona arabamı ödünç verme konusunda ciddi kuşkularım vardı."],
      ["qualm", "vicdani tereddüt, çekince", "", "She had no qualms about asking for a higher salary.", "Daha yüksek maaş istemek konusunda hiçbir çekincesi yoktu."],
      ["elation", "büyük sevinç, coşku", "", "His elation at passing the driving test lasted all week.", "Ehliyet sınavını geçmenin verdiği büyük sevinç bütün hafta sürdü."],
      ["yearning", "derin özlem, hasret", "", "She felt a deep yearning for the quiet village where she grew up.", "Büyüdüğü sessiz köye karşı derin bir özlem duydu."],
      ["infatuation", "geçici tutku, sevda", "😍", "It wasn't real love, just a brief infatuation with a stranger.", "Gerçek aşk değildi, bir yabancıya karşı kısa süreli bir tutkuydu."],
      ["fondness", "düşkünlük, sevgi", "", "He has a great fondness for old black and white films.", "Eski siyah beyaz filmlere büyük bir düşkünlüğü var."],
      ["zeal", "şevk, heves", "", "She approached the new project with real zeal and energy.", "Yeni projeye gerçek bir şevk ve enerjiyle yaklaştı."],
      ["candid", "açık sözlü, samimi", "", "Thank you for being so candid about the problems in the team.", "Ekipteki sorunlar konusunda bu kadar açık sözlü olduğun için teşekkürler."],
      ["forthright", "dobra, dolaysız", "", "She is forthright and always tells you exactly what she thinks.", "Dobra biridir ve sana her zaman tam olarak ne düşündüğünü söyler."],
      ["devious", "sinsi, dolambaçlı", "🦊", "He found a devious way to avoid paying the full price.", "Tam fiyatı ödememek için sinsi bir yol buldu."],
      ["manipulative", "manipülatif, insanları kullanan", "", "A manipulative partner often makes you doubt your own memory.", "Manipülatif bir partner çoğu zaman kendi hafızandan şüphe etmeni sağlar."],
      ["deceitful", "hilekâr, aldatıcı", "", "It was deceitful of him to hide the real cost from us.", "Gerçek maliyeti bizden saklaması hilekârca bir davranıştı."],
      ["two-faced", "iki yüzlü", "", "I can't trust her because she is so two-faced.", "Ona güvenemem çünkü çok iki yüzlü."],
      ["hypocritical", "ikiyüzlü, riyakâr", "", "It's hypocritical to complain about plastic while buying bottled water every day.", "Her gün şişe su alırken plastikten şikâyet etmek ikiyüzlülüktür."],
      ["pompous", "kendini önemli sanan, şişirilmiş", "", "The speaker was pompous and used long words to sound clever.", "Konuşmacı kendini önemli sanıyordu ve zeki görünmek için uzun kelimeler kullandı."],
      ["condescending", "tepeden bakan, küçümseyen", "", "I hate it when he uses that condescending tone with waiters.", "Garsonlara o tepeden bakan tonu kullanmasından nefret ediyorum."],
      ["patronising", "üstten bakan, çocuk yerine koyan", "", "Explaining something so simple to an expert sounds a bit patronising.", "Bir uzmana bu kadar basit bir şeyi açıklamak biraz üstten bakmak gibi duruyor."],
      ["self-effacing", "kendini öne çıkarmayan, alçakgönüllü", "", "Despite her fame, she is quiet and self-effacing in interviews.", "Ünlü olmasına rağmen röportajlarda sessiz ve kendini öne çıkarmayan biridir."],
      ["unassuming", "gösterişsiz, mütevazı", "", "The best chef in town runs an unassuming little restaurant.", "Şehrin en iyi aşçısı gösterişsiz küçük bir restoran işletiyor."],
      ["altruistic", "özgeci, başkalarını düşünen", "", "She volunteers every weekend for purely altruistic reasons.", "Tamamen özgeci nedenlerle her hafta sonu gönüllü çalışıyor."],
      ["egotistical", "bencil, kendini beğenmiş", "", "An egotistical boss rarely gives credit to his team.", "Bencil bir patron ekibine nadiren hak ettiği takdiri verir."],
      ["inquisitive", "meraklı, soru soran", "🔍", "Inquisitive children ask hundreds of questions every day.", "Meraklı çocuklar her gün yüzlerce soru sorar."],
      ["perceptive", "anlayışlı, sezgisi güçlü", "", "She is perceptive enough to notice when someone is upset.", "Birinin üzgün olduğunu fark edecek kadar sezgisi güçlüdür."],
      ["astute", "zeki, durumu iyi kavrayan", "", "That was an astute decision to invest before prices went up.", "Fiyatlar yükselmeden önce yatırım yapmak zekice bir karardı."],
      ["shrewd", "kurnaz, açıkgöz", "", "He is a shrewd negotiator who always gets a good deal.", "Her zaman iyi bir anlaşma yapan açıkgöz bir müzakerecidir."],
      ["cynical", "kinik, her şeye şüpheyle bakan", "", "Some people are cynical about companies that claim to be green.", "Bazı insanlar çevreci olduğunu iddia eden şirketlere şüpheyle bakar."],
      ["stoic", "acıya sessizce katlanan, metin", "🗿", "He remained stoic throughout the long and painful treatment.", "Uzun ve acılı tedavi boyunca metanetini korudu."],
      ["fastidious", "titiz, kılı kırk yaran", "", "She is fastidious about keeping her desk perfectly organised.", "Masasını kusursuz düzenli tutma konusunda çok titizdir."],
      ["complacent", "rehavete kapılmış, fazla rahat", "", "We can't become complacent just because sales were good last year.", "Geçen yıl satışlar iyi gitti diye rehavete kapılamayız."],
      ["temperamental", "dengesiz, havadan havaya giren", "", "The singer is famously temperamental before a concert.", "Şarkıcı konserlerden önce havadan havaya girmesiyle bilinir."],
      ["eccentric", "eksantrik, tuhaf ve sıra dışı", "🎩", "My eccentric uncle collects old keys from all over the world.", "Eksantrik amcam dünyanın her yerinden eski anahtarlar biriktirir."],
      ["abrasive", "kaba, sert ve itici", "", "His abrasive style of management made many people quit.", "Kaba ve sert yönetim tarzı birçok kişinin istifa etmesine yol açtı."],
      ["overbearing", "baskıcı, her şeye karışan", "", "Her overbearing mother wants to plan every detail of the wedding.", "Baskıcı annesi düğünün her ayrıntısını planlamak istiyor."],
      ["cantankerous", "huysuz, geçimsiz", "👴", "The cantankerous old man complained about the noise every evening.", "Huysuz yaşlı adam her akşam gürültüden şikâyet ederdi."],
      ["self-conscious", "kendinden utanan, çekinen", "", "I feel self-conscious when I have to speak English in front of others.", "Başkalarının önünde İngilizce konuşmam gerektiğinde çekiniyorum."],
      ["bottle up", "duygularını içine atmak", "🍾", "It isn't healthy to bottle up your anger for years.", "Öfkeni yıllarca içine atman sağlıklı değil."],
      ["lash out", "birine aniden saldırmak, patlamak", "", "When he is stressed, he tends to lash out at the people closest to him.", "Stresli olduğunda en yakınındaki insanlara patlama eğilimindedir."]
    ] },
  { id: "lib7b", title: "İlişkiler ve Sosyal Hayat", icon: "💞", cefr: "B2", desc: "Aile, arkadaşlık, aşk ve sosyal ortamlarla ilgili kullanışlı kelime ve kalıplar",
    words: [
      ["tie the knot", "dünya evine girmek, evlenmek", "💍", "They finally decided to tie the knot after seven years together.", "Yedi yıl birlikte olduktan sonra sonunda dünya evine girmeye karar verdiler."],
      ["propose", "evlenme teklif etmek", "", "He plans to propose to her on the beach at sunset.", "Ona gün batımında sahilde evlenme teklif etmeyi planlıyor."],
      ["fiancé", "nişanlı", "", "Let me introduce you to my fiancé, Emre.", "Seni nişanlım Emre ile tanıştırayım."],
      ["newlyweds", "yeni evliler", "", "The newlyweds left for their trip the morning after the wedding.", "Yeni evliler düğünün ertesi sabahı yolculuklarına çıktı."],
      ["honeymoon", "balayı", "🏝️", "We are going to Greece for our honeymoon next month.", "Gelecek ay balayımız için Yunanistan'a gidiyoruz."],
      ["anniversary", "yıl dönümü", "🎂", "My parents are celebrating their thirtieth wedding anniversary this weekend.", "Annemle babam bu hafta sonu otuzuncu evlilik yıl dönümlerini kutluyor."],
      ["in-laws", "kayınpeder ve kayınvalide, eşin ailesi", "", "We spend every holiday with my in-laws in Izmir.", "Her bayramı eşimin ailesiyle İzmir'de geçiriyoruz."],
      ["mother-in-law", "kayınvalide", "", "My mother-in-law makes the best stuffed peppers I have ever eaten.", "Kayınvalidem hayatımda yediğim en güzel biber dolmasını yapar."],
      ["stepfather", "üvey baba", "", "My stepfather taught me how to ride a bike.", "Bana bisiklete binmeyi üvey babam öğretti."],
      ["half-brother", "üvey erkek kardeş, baba ya da anne bir kardeş", "", "I have a half-brother who lives in Germany with his mother.", "Annesiyle Almanya'da yaşayan baba bir erkek kardeşim var."],
      ["only child", "tek çocuk", "", "As an only child, I always wanted a big family.", "Tek çocuk olarak hep kalabalık bir aile istedim."],
      ["sibling rivalry", "kardeş rekabeti", "", "There was a lot of sibling rivalry between my brother and me.", "Ağabeyimle aramda çok fazla kardeş rekabeti vardı."],
      ["run in the family", "ailede olmak, soydan gelmek", "🧬", "Musical talent seems to run in the family.", "Müzik yeteneği ailede var gibi görünüyor."],
      ["close-knit", "birbirine sıkı sıkıya bağlı", "", "We grew up in a close-knit neighbourhood where everyone knew each other.", "Herkesin birbirini tanıdığı, birbirine sıkı sıkıya bağlı bir mahallede büyüdük."],
      ["extended family", "geniş aile", "", "My extended family gets together every summer at my grandmother's house.", "Geniş ailem her yaz büyükannemin evinde bir araya gelir."],
      ["family gathering", "aile toplantısı, aile buluşması", "👨‍👩‍👧‍👦", "Every family gathering ends with a long political argument.", "Her aile buluşması uzun bir siyasi tartışmayla biter."],
      ["keep in touch", "iletişimi sürdürmek", "📱", "Let's keep in touch after you move to London.", "Londra'ya taşındıktan sonra iletişimi koparmayalım."],
      ["lose touch", "bağlantıyı kaybetmek", "", "We lose touch with old friends without even noticing it.", "Eski arkadaşlarla fark etmeden bağımızı kaybederiz."],
      ["get in touch", "irtibata geçmek, ulaşmak", "", "Please get in touch if you need any help with the move.", "Taşınmada yardıma ihtiyacın olursa lütfen bana ulaş."],
      ["reach out", "birine ulaşmak, el uzatmak", "🤝", "Don't be afraid to reach out when you are feeling lonely.", "Yalnız hissettiğinde birine ulaşmaktan korkma."],
      ["pop round", "kısa bir ziyarete uğramak", "", "Why don't you pop round for a coffee after work?", "İşten sonra bir kahveye uğrasana."],
      ["housewarming", "yeni ev partisi", "🏠", "They're having a housewarming party on Saturday, are you coming?", "Cumartesi yeni ev partisi veriyorlar, geliyor musun?"],
      ["plus-one", "davete getirilen eşlikçi", "", "The invitation says I can bring a plus-one to the wedding.", "Davetiyede düğüne bir eşlikçi getirebileceğim yazıyor."],
      ["icebreaker", "buzları eritecek etkinlik ya da söz", "🧊", "The teacher started the course with a funny icebreaker game.", "Öğretmen kursa buzları eriten eğlenceli bir oyunla başladı."],
      ["socialise", "sosyalleşmek", "", "I don't have much time to socialise during the exam period.", "Sınav döneminde sosyalleşmeye pek vaktim olmuyor."],
      ["mingle", "kalabalığa karışıp sohbet etmek", "🥂", "At the party, try to mingle instead of standing in the corner.", "Partide köşede durmak yerine insanlarla kaynaşmaya çalış."],
      ["blind date", "görücü usulü buluşma, tanımadan buluşma", "🙈", "My friend set me up on a blind date with her cousin.", "Arkadaşım beni kuzeniyle tanımadan buluşmam için ayarladı."],
      ["dating app", "flört uygulaması", "📲", "They met on a dating app and got married two years later.", "Bir flört uygulamasında tanıştılar ve iki yıl sonra evlendiler."],
      ["ghost", "aniden haber vermeden ortadan kaybolmak", "👻", "After three dates, he decided to ghost me without any explanation.", "Üç buluşmadan sonra hiçbir açıklama yapmadan ortadan kaybolmaya karar verdi."],
      ["compatible", "uyumlu", "", "We love each other, but we're just not compatible as a couple.", "Birbirimizi seviyoruz ama çift olarak uyumlu değiliz."],
      ["long-distance relationship", "uzak mesafe ilişkisi", "✈️", "A long-distance relationship needs a lot of trust and patience.", "Uzak mesafe ilişkisi çok fazla güven ve sabır gerektirir."],
      ["commitment", "bağlılık, taahhüt", "", "He is afraid of commitment and avoids serious relationships.", "Bağlılıktan korkuyor ve ciddi ilişkilerden kaçıyor."],
      ["cheat on", "aldatmak", "", "She found out that her boyfriend used to cheat on her.", "Erkek arkadaşının onu aldattığını öğrendi."],
      ["heartbreak", "kalp kırıklığı", "💔", "It took her almost a year to recover from the heartbreak.", "Kalp kırıklığını atlatması neredeyse bir yıl sürdü."],
      ["split up", "ayrılmak", "", "My parents split up when I was twelve.", "Ben on iki yaşındayken annemle babam ayrıldı."],
      ["custody", "velayet", "⚖️", "After the divorce, the mother got custody of the children.", "Boşanmadan sonra çocukların velayeti anneye verildi."],
      ["ex", "eski sevgili ya da eski eş", "", "I ran into my ex at the supermarket yesterday.", "Dün süpermarkette eski sevgilime rastladım."],
      ["rebound", "ayrılık sonrası hızlı ilişki", "", "Be careful, this new relationship might just be a rebound.", "Dikkat et, bu yeni ilişki sadece ayrılık sonrası bir avuntu olabilir."],
      ["make amends", "telafi etmek, gönül almak", "", "He tried to make amends by cooking her favourite dinner.", "En sevdiği yemeği pişirerek gönlünü almaya çalıştı."],
      ["forgive", "affetmek", "🕊️", "It took me a long time to forgive him for what he said.", "Söylediği şey için onu affetmem uzun zaman aldı."],
      ["reconcile", "barışmak, uzlaşmak", "", "The two brothers managed to reconcile after years of silence.", "İki kardeş yıllarca süren küslükten sonra barışmayı başardı."],
      ["bicker", "didişmek, ufak şeyler için atışmak", "", "My grandparents bicker all day, but they adore each other.", "Büyükannemle büyükbabam bütün gün didişir ama birbirlerine bayılırlar."],
      ["nag", "dırdır etmek", "", "My mum used to nag me about cleaning my room.", "Annem odamı temizlemem için hep dırdır ederdi."],
      ["tease", "takılmak, alay etmek", "😜", "My friends love to tease me about my terrible singing.", "Arkadaşlarım berbat şarkı söylememle dalga geçmeye bayılır."],
      ["backstab", "arkadan vurmak", "🔪", "I never thought my best friend would backstab me like that.", "En iyi arkadaşımın beni böyle arkadan vuracağını hiç düşünmezdim."],
      ["peer pressure", "akran baskısı", "", "Many teenagers start smoking because of peer pressure.", "Birçok genç akran baskısı yüzünden sigaraya başlar."],
      ["fit in", "uyum sağlamak, aralarına katılmak", "🧩", "It took me months to fit in at my new school.", "Yeni okuluma uyum sağlamam aylar sürdü."],
      ["sense of belonging", "aidiyet duygusu", "", "Joining the choir gave her a strong sense of belonging.", "Koroya katılmak ona güçlü bir aidiyet duygusu verdi."],
      ["support network", "destek çevresi", "", "Having a good support network makes difficult times easier.", "İyi bir destek çevresine sahip olmak zor zamanları kolaylaştırır."],
      ["confide in", "birine sır vermek, içini dökmek", "", "I can always confide in my sister when something is wrong.", "Bir şeyler ters gittiğinde ablama her zaman içimi dökebilirim."],
      ["confidant", "sırdaş", "", "My grandmother was my closest confidant when I was a teenager.", "Ergenliğimde en yakın sırdaşım büyükannemdi."],
      ["rely on", "güvenmek, bel bağlamak", "", "You can rely on Deniz, she never forgets a promise.", "Deniz'e güvenebilirsin, verdiği sözü asla unutmaz."],
      ["stand by", "yanında durmak, desteklemek", "", "Real friends stand by you when things go wrong.", "Gerçek dostlar işler kötü gittiğinde yanında durur."],
      ["stick up for", "savunmak, arka çıkmak", "", "Thanks for trying to stick up for me in the meeting.", "Toplantıda bana arka çıkmaya çalıştığın için teşekkürler."],
      ["mutual friend", "ortak arkadaş", "", "We met through a mutual friend at a birthday party.", "Bir doğum günü partisinde ortak bir arkadaş aracılığıyla tanıştık."],
      ["set boundaries", "sınır koymak", "🚧", "It's important to set boundaries with people who drain your energy.", "Enerjini tüketen insanlarla sınır koymak önemlidir."],
      ["possessive", "sahiplenici, kıskanç", "", "He gets possessive when his girlfriend talks to other men.", "Kız arkadaşı başka erkeklerle konuşunca sahiplenici oluyor."],
      ["supportive", "destekleyici, destek olan", "", "My boss was very supportive when my father was ill.", "Babam hastayken patronum bana çok destek oldu."],
      ["role model", "rol model, örnek alınan kişi", "🌟", "My aunt has always been a role model for me.", "Teyzem benim için her zaman bir rol model oldu."],
      ["bond", "bağ, bağ kurmak", "", "There is a special bond between the twins.", "İkizler arasında özel bir bağ var."],
      ["bridesmaid", "nedime", "👗", "I was a bridesmaid at my cousin's wedding last summer.", "Geçen yaz kuzenimin düğününde nedimeydim."],
      ["wedding vows", "evlilik yeminleri", "", "He cried while reading his wedding vows in front of everyone.", "Herkesin önünde evlilik yeminlerini okurken ağladı."],
      ["guest list", "davetli listesi", "📝", "The guest list keeps getting longer every week.", "Davetli listesi her hafta daha da uzuyor."],
      ["get-together", "küçük buluşma, toplanma", "", "We're having a small get-together at my place on Friday night.", "Cuma akşamı bende küçük bir buluşma yapıyoruz."],
      ["potluck", "herkesin yemek getirdiği davet", "🍲", "Everyone brought a dish to the potluck dinner at the office.", "Ofisteki ortaklaşa akşam yemeğine herkes bir tabak yemek getirdi."],
      ["roommate", "oda arkadaşı, ev arkadaşı", "", "My roommate always leaves dirty dishes in the sink.", "Ev arkadaşım bulaşıkları hep lavaboda bırakıyor."],
      ["generation gap", "kuşak farkı", "", "The generation gap is obvious when we talk about technology.", "Teknoloji hakkında konuştuğumuzda kuşak farkı açıkça görülüyor."],
      ["babysit", "çocuğa bakmak", "🍼", "Could you babysit our son on Saturday evening?", "Cumartesi akşamı oğlumuza bakabilir misin?"],
      ["adopt", "evlat edinmek", "", "They decided to adopt a child after years of trying.", "Yıllarca denedikten sonra bir çocuk evlat edinmeye karar verdiler."],
      ["foster", "koruyucu aile olmak", "", "My neighbours foster children who can't live with their parents.", "Komşularım aileleriyle yaşayamayan çocuklara koruyucu aile oluyor."],
      ["expecting", "bebek bekleyen, hamile", "🤰", "Guess what, my sister is expecting her first baby in May.", "Bil bakalım ne oldu, ablam mayısta ilk bebeğini bekliyor."],
      ["maternity leave", "doğum izni", "", "She is on maternity leave until the end of the year.", "Yıl sonuna kadar doğum izninde."],
      ["condolences", "başsağlığı", "🕯️", "Please accept my deepest condolences for your loss.", "Kaybınız için lütfen en derin başsağlığı dileklerimi kabul edin."],
      ["mourn", "yas tutmak", "", "The whole town gathered to mourn the loss of the old teacher.", "Bütün kasaba yaşlı öğretmenin kaybının yasını tutmak için toplandı."],
      ["grieve", "acı çekmek, yasını tutmak", "", "Everyone needs time to grieve in their own way.", "Herkesin kendi yolunda yas tutmak için zamana ihtiyacı vardır."],
      ["drift apart", "zamanla uzaklaşmak", "", "We used to be best friends, but we started to drift apart after university.", "Eskiden en iyi arkadaştık ama üniversiteden sonra zamanla uzaklaşmaya başladık."],
      ["best man", "sağdıç", "🤵", "His brother will be the best man at the wedding.", "Düğünde sağdıç kardeşi olacak."],
      ["engagement ring", "nişan yüzüğü", "💍", "She showed everyone her engagement ring at lunch.", "Öğle yemeğinde herkese nişan yüzüğünü gösterdi."],
      ["get engaged", "nişanlanmak", "", "They want to get engaged before the end of the summer.", "Yaz bitmeden nişanlanmak istiyorlar."],
      ["walk down the aisle", "gelin olarak yürümek, evlenmek", "", "She will walk down the aisle in a dress her grandmother made.", "Büyükannesinin diktiği bir gelinlikle gelin yolunda yürüyecek."],
      ["get on your nerves", "sinirini bozmak", "😤", "Little habits can really get on your nerves when you live together.", "Birlikte yaşarken küçük alışkanlıklar gerçekten sinirini bozabilir."],
      ["on speaking terms", "konuşur durumda, küs olmayan", "", "The two neighbours are not on speaking terms after the parking argument.", "İki komşu park tartışmasından sonra birbirleriyle konuşmuyor."],
      ["falling-out", "araların bozulması, küslük", "", "They had a falling-out over money and never spoke again.", "Para yüzünden araları bozuldu ve bir daha hiç konuşmadılar."],
      ["move in together", "aynı eve taşınmak, birlikte yaşamaya başlamak", "📦", "After two years of dating, they decided to move in together.", "İki yıllık beraberliğin ardından aynı eve taşınmaya karar verdiler."],
      ["patch things up", "arayı düzeltmek", "🩹", "I called her to patch things up after our argument.", "Tartışmamızdan sonra arayı düzeltmek için onu aradım."],
      ["bury the hatchet", "küslüğe son vermek, barışmak", "", "It's time to bury the hatchet and move forward together.", "Küslüğe son verip birlikte ilerlemenin zamanı geldi."],
      ["clear the air", "havayı yumuşatmak, açık konuşup gerginliği gidermek", "", "We had a long talk to clear the air between us.", "Aramızdaki gerginliği gidermek için uzun uzun konuştuk."],
      ["make up for", "telafi etmek", "", "I bought her flowers to make up for forgetting our date.", "Buluşmamızı unuttuğum için telafi olsun diye ona çiçek aldım."],
      ["stand up for", "savunmak, hakkını aramak", "", "You should stand up for your friends when others criticise them.", "Başkaları arkadaşlarını eleştirdiğinde onları savunmalısın."],
      ["take sides", "taraf tutmak", "", "I don't want to take sides in my parents' argument.", "Annemle babamın tartışmasında taraf tutmak istemiyorum."],
      ["love at first sight", "ilk görüşte aşk", "😍", "Do you believe in love at first sight?", "İlk görüşte aşka inanır mısın?"],
      ["split the bill", "hesabı bölüşmek", "🧾", "Let's split the bill, it's fairer that way.", "Hesabı bölüşelim, böylesi daha adil."],
      ["pick up the tab", "hesabı ödemek", "", "The company will pick up the tab for tonight's dinner.", "Bu akşamki yemeğin hesabını şirket ödeyecek."],
      ["throw a party", "parti vermek", "🎉", "We want to throw a party for his fortieth birthday.", "Kırkıncı doğum günü için bir parti vermek istiyoruz."],
      ["social circle", "sosyal çevre", "", "Since moving to Ankara, my social circle has become much smaller.", "Ankara'ya taşındığımdan beri sosyal çevrem çok küçüldü."],
      ["childhood friend", "çocukluk arkadaşı", "", "My childhood friend and I still meet every New Year's Eve.", "Çocukluk arkadaşımla hâlâ her yılbaşı gecesi buluşuruz."],
      ["overshare", "fazla kişisel bilgi paylaşmak", "", "Some people overshare on social media about their private lives.", "Bazı insanlar özel hayatları hakkında sosyal medyada gereğinden fazla paylaşım yapar."],
      ["night out", "dışarıda eğlence gecesi", "🌃", "We're planning a girls' night out for Friday.", "Cuma için kızlar arasında bir eğlence gecesi planlıyoruz."],
      ["social butterfly", "çok sosyal, herkesle kaynaşan kişi", "🦋", "My sister is a real social butterfly at every party.", "Kız kardeşim her partide herkesle kaynaşan gerçek bir sosyal kelebektir."],
      ["third wheel", "çiftin yanındaki fazlalık kişi", "", "I felt like a third wheel on their romantic dinner.", "Onların romantik yemeğinde kendimi fazlalık gibi hissettim."],
      ["matchmaker", "çöpçatan", "", "My aunt loves playing matchmaker for all her single relatives.", "Teyzem bekâr akrabalarının hepsine çöpçatanlık yapmaya bayılır."],
      ["significant other", "hayat arkadaşı, partner", "", "You are welcome to bring your significant other to the dinner.", "Yemeğe hayat arkadaşını getirebilirsin."],
      ["lend an ear", "dinlemek, kulak vermek", "👂", "If you need to talk, I'm always happy to lend an ear.", "Konuşmaya ihtiyacın olursa seni dinlemekten her zaman mutluluk duyarım."],
      ["shoulder to cry on", "dertleşilecek kişi, omuz", "", "She was my shoulder to cry on during the divorce.", "Boşanma sürecinde dertleştiğim kişi oydu."],
      ["banter", "şakalaşma, laf atışması", "", "The friendly banter between the two hosts makes the show fun.", "İki sunucu arasındaki dostça şakalaşma programı eğlenceli kılıyor."],
      ["inside joke", "aramızdaki espri, iç şaka", "", "Sorry, it's an inside joke from our university days.", "Kusura bakma, üniversite günlerimizden kalma aramızdaki bir espri."],
      ["rapport", "uyum, iyi ilişki", "", "A good teacher quickly builds rapport with new students.", "İyi bir öğretmen yeni öğrencilerle hızla iyi bir ilişki kurar."],
      ["meddle", "burnunu sokmak, karışmak", "", "Please don't meddle in our relationship, we can handle it.", "Lütfen ilişkimize karışma, biz hallederiz."],
      ["breadwinner", "evin geçimini sağlayan kişi", "🍞", "After her husband lost his job, she became the main breadwinner.", "Kocası işini kaybettikten sonra evin geçimini sağlayan asıl kişi o oldu."],
      ["estranged", "küs, ilişkisi kopmuş", "", "He has been estranged from his father for over ten years.", "On yılı aşkın süredir babasıyla küs."]
    ] },
  { id: "lib7c", title: "Günlük Hayat ve Ev (Kalıplar)", icon: "🧺", cefr: "B2", desc: "Ev işleri ve günlük rutinler için doğal İngilizce kalıplar ve collocationlar",
    words: [
      ["run errands", "ufak tefek işleri halletmek", "🏃", "I usually run errands on Saturday morning before lunch.", "Ufak tefek işlerimi genellikle cumartesi sabahı öğle yemeğinden önce hallederim."],
      ["do the dishes", "bulaşık yıkamak", "🍽️", "If you cook, I'll do the dishes afterwards.", "Sen yemek yaparsan, sonra bulaşıkları ben yıkarım."],
      ["load the dishwasher", "bulaşık makinesini doldurmak", "", "Can you load the dishwasher before you go to bed?", "Yatmadan önce bulaşık makinesini doldurabilir misin?"],
      ["empty the dishwasher", "bulaşık makinesini boşaltmak", "", "The kids take turns to empty the dishwasher every morning.", "Çocuklar her sabah sırayla bulaşık makinesini boşaltır."],
      ["hang out the washing", "çamaşırları asmak", "👕", "It's sunny, so let's hang out the washing on the balcony.", "Hava güneşli, hadi çamaşırları balkona asalım."],
      ["fold the clothes", "kıyafetleri katlamak", "", "I usually fold the clothes while watching a series.", "Kıyafetleri genellikle dizi izlerken katlarım."],
      ["iron a shirt", "gömlek ütülemek", "👔", "I need to iron a shirt for tomorrow's interview.", "Yarınki mülakat için bir gömlek ütülemem lazım."],
      ["sort the laundry", "çamaşırları ayırmak", "", "Always sort the laundry into whites and colours first.", "Çamaşırları her zaman önce beyazlar ve renkliler olarak ayır."],
      ["do a load of laundry", "bir makine çamaşır yıkamak", "", "I'll do a load of laundry before we leave for the weekend.", "Hafta sonu için çıkmadan önce bir makine çamaşır yıkayacağım."],
      ["take out the trash", "çöpü dışarı çıkarmak", "🗑️", "Don't forget to take out the trash, it's starting to smell.", "Çöpü çıkarmayı unutma, kokmaya başladı."],
      ["take the bins out", "çöp kutularını dışarı çıkarmak", "", "It's my turn to take the bins out on Tuesday night.", "Salı akşamı çöp kutularını dışarı çıkarma sırası bende."],
      ["sweep the floor", "yeri süpürmek", "🧹", "Please sweep the floor after you finish cutting your hair.", "Saçını kestikten sonra lütfen yeri süpür."],
      ["mop the floor", "yeri paspaslamak", "", "I mop the floor in the kitchen twice a week.", "Mutfağın yerini haftada iki kez paspaslarım."],
      ["vacuum the carpet", "halıyı elektrikli süpürgeyle süpürmek", "", "We should vacuum the carpet before the guests arrive.", "Misafirler gelmeden halıyı süpürmeliyiz."],
      ["dust the shelves", "rafların tozunu almak", "", "I hate to dust the shelves because there are so many books.", "Rafların tozunu almaktan nefret ediyorum çünkü çok fazla kitap var."],
      ["wipe the counter", "tezgâhı silmek", "🧽", "Wipe the counter after you make your sandwich, please.", "Sandviçini yaptıktan sonra lütfen tezgâhı sil."],
      ["scrub the bathtub", "küveti ovarak temizlemek", "🛁", "It took me an hour to scrub the bathtub properly.", "Küveti düzgünce ovup temizlemem bir saatimi aldı."],
      ["declutter", "gereksiz eşyalardan arınmak", "📦", "We decided to declutter the house before moving.", "Taşınmadan önce evdeki gereksiz eşyalardan kurtulmaya karar verdik."],
      ["put away", "yerine kaldırmak", "", "Put away your toys before dinner, please.", "Lütfen yemekten önce oyuncaklarını yerine kaldır."],
      ["clear the table", "sofrayı toplamak", "", "The children help clear the table after every meal.", "Çocuklar her yemekten sonra sofrayı toplamaya yardım eder."],
      ["lay the table", "sofrayı kurmak", "🍴", "Could you lay the table while I finish the salad?", "Ben salatayı bitirirken sofrayı kurabilir misin?"],
      ["cook from scratch", "hazır malzeme kullanmadan sıfırdan pişirmek", "👩‍🍳", "I try to cook from scratch at least three times a week.", "Haftada en az üç kez sıfırdan yemek yapmaya çalışıyorum."],
      ["meal prep", "haftalık yemek hazırlığı", "🥡", "Sunday is my meal prep day for the whole week.", "Pazar günü bütün haftanın yemek hazırlığını yaptığım gün."],
      ["heat up", "ısıtmak", "", "Just heat up the soup in the microwave for two minutes.", "Çorbayı mikrodalgada iki dakika ısıtman yeterli."],
      ["defrost", "buzunu çözmek", "❄️", "Remember to defrost the chicken before you go to work.", "İşe gitmeden önce tavuğun buzunu çözmeyi unutma."],
      ["preheat the oven", "fırını önceden ısıtmak", "", "Preheat the oven to 180 degrees before you mix the ingredients.", "Malzemeleri karıştırmadan önce fırını 180 dereceye ısıt."],
      ["chop vegetables", "sebze doğramak", "🔪", "Can you chop vegetables for the salad while I make the sauce?", "Ben sosu yaparken salata için sebze doğrayabilir misin?"],
      ["peel potatoes", "patates soymak", "🥔", "My grandfather can peel potatoes faster than anyone I know.", "Dedem tanıdığım herkesten hızlı patates soyabilir."],
      ["pay the bills", "faturaları ödemek", "💳", "I always pay the bills online on the first of the month.", "Faturaları her zaman ayın birinde internetten öderim."],
      ["utility bills", "elektrik, su, doğalgaz faturaları", "", "Our utility bills went up a lot this winter.", "Bu kış faturalarımız çok arttı."],
      ["top up", "bakiye yüklemek, doldurmak", "", "I need to top up my travel card before I get on the bus.", "Otobüse binmeden önce ulaşım kartıma para yüklemem lazım."],
      ["set the alarm", "alarm kurmak", "⏰", "Did you set the alarm for six o'clock?", "Alarmı saat altıya kurdun mu?"],
      ["hit the snooze button", "alarmı ertelemek", "😴", "I hit the snooze button three times and missed my train.", "Alarmı üç kez erteledim ve trenimi kaçırdım."],
      ["take a shower", "duş almak", "🚿", "I usually take a shower as soon as I get home from the gym.", "Genellikle spor salonundan eve gelir gelmez duş alırım."],
      ["do your hair", "saçını yapmak", "💇", "Give me five minutes to do your hair before the party.", "Partiden önce saçını yapmam için bana beş dakika ver."],
      ["grab a bite", "bir şeyler atıştırmak", "🥪", "Let's grab a bite before the film starts.", "Film başlamadan bir şeyler atıştıralım."],
      ["skip breakfast", "kahvaltıyı atlamak", "", "I often skip breakfast when I'm in a hurry.", "Acelem olduğunda çoğu zaman kahvaltıyı atlarım."],
      ["stuck in traffic", "trafiğe takılmış", "🚗", "Sorry I'm late, I was stuck in traffic for an hour.", "Geç kaldığım için kusura bakma, bir saat trafiğe takıldım."],
      ["mow the lawn", "çimleri biçmek", "🌱", "My dad asked me to mow the lawn on Sunday.", "Babam pazar günü çimleri biçmemi istedi."],
      ["do the gardening", "bahçe işleriyle uğraşmak", "🌷", "My mother loves to do the gardening in spring.", "Annem baharda bahçe işleriyle uğraşmaya bayılır."],
      ["fix a leaky tap", "damlatan musluğu tamir etmek", "🚰", "I watched a video to learn how to fix a leaky tap.", "Damlatan musluğu nasıl tamir edeceğimi öğrenmek için bir video izledim."],
      ["unclog the drain", "tıkalı gideri açmak", "", "We had to unclog the drain because the shower was full of water.", "Duş suyla dolduğu için tıkalı gideri açmak zorunda kaldık."],
      ["change a light bulb", "ampul değiştirmek", "💡", "You need a ladder to change a light bulb in this room.", "Bu odada ampul değiştirmek için merdivene ihtiyacın var."],
      ["call a plumber", "tesisatçı çağırmak", "🔧", "The pipe burst, so we had to call a plumber at midnight.", "Boru patladı, o yüzden gece yarısı tesisatçı çağırmak zorunda kaldık."],
      ["assemble furniture", "mobilya kurmak", "🪛", "It took us all day to assemble furniture for the new bedroom.", "Yeni yatak odası için mobilya kurmak bütün günümüzü aldı."],
      ["hang a picture", "duvara resim asmak", "🖼️", "Can you help me hang a picture above the sofa?", "Kanepenin üstüne bir resim asmama yardım edebilir misin?"],
      ["redecorate", "evi yeniden dekore etmek", "🎨", "We want to redecorate the living room in lighter colours.", "Oturma odasını daha açık renklerle yeniden dekore etmek istiyoruz."],
      ["move house", "taşınmak", "🚚", "We have to move house again because the rent went up.", "Kira arttığı için yine taşınmak zorundayız."],
      ["unpack", "valizi ya da kolileri açıp yerleştirmek", "", "I still haven't had time to unpack all the boxes.", "Hâlâ bütün kolileri açıp yerleştirmeye vaktim olmadı."],
      ["sign a lease", "kira sözleşmesi imzalamak", "✍️", "We are going to sign a lease for a flat near the station.", "İstasyona yakın bir daire için kira sözleşmesi imzalayacağız."],
      ["household chores", "ev işleri", "", "We share the household chores equally in our family.", "Ailemizde ev işlerini eşit şekilde paylaşıyoruz."],
      ["split the chores", "ev işlerini bölüşmek", "", "My flatmates and I split the chores at the start of each month.", "Ev arkadaşlarımla her ayın başında ev işlerini bölüşürüz."],
      ["take turns", "sırayla yapmak", "🔄", "We take turns cooking dinner during the week.", "Hafta içi akşam yemeğini sırayla pişiriyoruz."],
      ["do the school run", "çocukları okula götürüp getirmek", "🏫", "My husband does the school run, and I pick them up.", "Çocukları okula kocam götürüyor, ben de alıyorum."],
      ["pick up the kids", "çocukları almak", "", "Can you pick up the kids from football practice today?", "Bugün çocukları futbol antrenmanından alabilir misin?"],
      ["drop off", "bırakmak", "", "I'll drop off the kids at school on my way to work.", "İşe giderken çocukları okula bırakırım."],
      ["put the kids to bed", "çocukları yatırmak", "🛏️", "After I put the kids to bed, I finally have some time for myself.", "Çocukları yatırdıktan sonra nihayet kendime biraz vaktim oluyor."],
      ["bedtime story", "uyku öncesi masalı", "📖", "My daughter won't sleep without a bedtime story.", "Kızım uyku öncesi masalı olmadan uyumuyor."],
      ["unwind", "gevşemek, kafa dağıtmak", "🧘", "I like to unwind with a hot bath after a long day.", "Uzun bir günün ardından sıcak bir banyoyla gevşemeyi severim."],
      ["put your feet up", "ayaklarını uzatıp dinlenmek", "🛋️", "You've worked hard all week, so put your feet up tonight.", "Bütün hafta çok çalıştın, bu akşam ayaklarını uzatıp dinlen."],
      ["turn in", "yatmaya gitmek", "", "I'm exhausted, so I think I'll turn in early tonight.", "Çok yorgunum, sanırım bu gece erken yatacağım."],
      ["spotless", "tertemiz, lekesiz", "✨", "Her kitchen is always spotless, even after a big dinner.", "Onun mutfağı büyük bir yemekten sonra bile hep tertemizdir."],
      ["clutter", "ev dağınıklığı, ıvır zıvır", "", "There is too much clutter on the kitchen table.", "Mutfak masasında çok fazla ıvır zıvır var."],
      ["laundry basket", "kirli sepeti", "🧺", "Please put your dirty socks in the laundry basket.", "Lütfen kirli çoraplarını kirli sepetine koy."],
      ["detergent", "deterjan", "", "We ran out of detergent, so I need to buy some more.", "Deterjanımız bitti, biraz daha almam lazım."],
      ["fabric softener", "yumuşatıcı", "", "This fabric softener makes the towels smell amazing.", "Bu yumuşatıcı havluların harika kokmasını sağlıyor."],
      ["stain", "leke", "", "I spilled coffee on my shirt and now there is a big stain.", "Gömleğime kahve döktüm ve şimdi büyük bir leke var."],
      ["tumble dryer", "kurutma makinesi", "", "Don't put wool sweaters in the tumble dryer.", "Yün kazakları kurutma makinesine koyma."],
      ["ironing board", "ütü masası", "", "The ironing board is folded behind the bedroom door.", "Ütü masası katlanmış halde yatak odası kapısının arkasında."],
      ["vacuum cleaner", "elektrikli süpürge", "", "Our old vacuum cleaner is so loud that it scares the cat.", "Eski elektrikli süpürgemiz o kadar gürültülü ki kediyi korkutuyor."],
      ["dustpan", "faraş", "", "Bring me the dustpan, I broke a glass in the kitchen.", "Bana faraşı getir, mutfakta bir bardak kırdım."],
      ["bin bag", "çöp poşeti", "", "We need a new roll of bin bags from the supermarket.", "Süpermarketten yeni bir rulo çöp poşeti almamız lazım."],
      ["lock the door", "kapıyı kilitlemek", "🔒", "Did you remember to lock the door when you left?", "Çıkarken kapıyı kilitlemeyi hatırladın mı?"],
      ["turn off the lights", "ışıkları kapatmak", "", "Please turn off the lights when you leave a room.", "Bir odadan çıkarken lütfen ışıkları kapat."],
      ["charge your phone", "telefonunu şarj etmek", "🔋", "You can charge your phone next to the bed.", "Telefonunu yatağın yanında şarj edebilirsin."],
      ["turn up the heating", "kaloriferi açmak, ısıyı artırmak", "🌡️", "It's freezing in here, can we turn up the heating a bit?", "Burası buz gibi, kaloriferi biraz açabilir miyiz?"],
      ["air out", "havalandırmak", "", "Open the windows to air out the room after cooking fish.", "Balık pişirdikten sonra odayı havalandırmak için pencereleri aç."],
      ["put the kettle on", "çaydanlığı ocağa koymak, su ısıtmak", "☕", "Come in and sit down, I'll put the kettle on.", "Gel otur, ben suyu ısıtayım."],
      ["order takeaway", "dışarıdan yemek sipariş etmek", "🥡", "We were too tired to cook, so we decided to order takeaway.", "Yemek yapamayacak kadar yorgunduk, o yüzden dışarıdan sipariş vermeye karar verdik."],
      ["eat in", "evde yemek", "", "Do you want to eat in tonight or go to a restaurant?", "Bu akşam evde mi yiyelim yoksa restorana mı gidelim?"],
      ["do the washing-up", "bulaşık yıkamak", "", "Whoever cooks doesn't have to do the washing-up.", "Yemeği kim yaparsa bulaşık yıkamak zorunda değil."],
      ["have people over", "eve misafir çağırmak", "", "We love to have people over for dinner on Saturdays.", "Cumartesileri akşam yemeğine eve misafir çağırmayı severiz."],
      ["run a bath", "küveti doldurup banyo hazırlamak", "", "I'll run a bath for you while you finish your tea.", "Sen çayını bitirirken ben sana küveti doldururum."],
      ["change the sheets", "çarşafları değiştirmek", "", "I change the sheets every Sunday morning.", "Çarşafları her pazar sabahı değiştiririm."],
      ["make an appointment", "randevu almak", "📅", "I need to make an appointment with the dentist this week.", "Bu hafta dişçiden randevu almam lazım."],
      ["book a table", "masa ayırtmak, rezervasyon yapmak", "", "Should I book a table for eight o'clock?", "Saat sekiz için masa ayırtayım mı?"],
      ["pick up a parcel", "paket teslim almak", "📦", "I have to pick up a parcel from the post office after work.", "İşten sonra postaneden bir paket almam gerekiyor."],
      ["make a mess", "ortalığı dağıtmak", "", "The kids always make a mess when they bake cookies.", "Çocuklar kurabiye yaparken hep ortalığı dağıtır."],
      ["clean up after", "birinin arkasını toplamak", "", "I'm tired of having to clean up after my brother.", "Kardeşimin arkasını toplamaktan bıktım."],
      ["do the ironing", "ütü yapmak", "", "I usually do the ironing on Sunday evening.", "Genellikle pazar akşamı ütü yaparım."],
      ["make a to-do list", "yapılacaklar listesi hazırlamak", "✅", "I make a to-do list every morning so I don't forget anything.", "Hiçbir şeyi unutmamak için her sabah yapılacaklar listesi hazırlarım."],
      ["do the cooking", "yemekleri yapmak", "", "In our house, my father does the cooking at weekends.", "Bizim evde hafta sonları yemekleri babam yapar."],
      ["spring clean", "baştan sona bahar temizliği yapmak", "🌸", "We spring clean the whole flat every April.", "Her nisan bütün daireyi baştan sona temizleriz."],
      ["deep clean", "detaylı temizlik", "", "The kitchen needs a deep clean before the inspection.", "Mutfağın denetimden önce detaylı bir temizliğe ihtiyacı var."],
      ["wash the car", "araba yıkamak", "🚙", "It always rains right after I wash the car.", "Arabayı yıkadıktan hemen sonra hep yağmur yağıyor."],
      ["soak the pan", "tavayı suda bekletmek", "🍳", "Soak the pan overnight and it will be easier to clean.", "Tavayı bir gece suda beklet, temizlemesi daha kolay olur."],
      ["sort the recycling", "geri dönüşümü ayırmak", "♻️", "Can you sort the recycling into paper and plastic?", "Geri dönüşümü kâğıt ve plastik olarak ayırabilir misin?"],
      ["shrink in the wash", "yıkamada çekmek", "", "Wool sweaters can shrink in the wash if the water is too hot.", "Su çok sıcaksa yün kazaklar yıkamada çekebilir."],
      ["direct debit", "otomatik ödeme talimatı", "🏦", "I pay my phone bill by direct debit every month.", "Telefon faturamı her ay otomatik ödeme talimatıyla öderim."],
      ["power cut", "elektrik kesintisi", "🔌", "There was a power cut last night, so we used candles.", "Dün gece elektrik kesintisi oldu, biz de mum kullandık."],
      ["fuse box", "sigorta kutusu", "", "When the lights go out, check the fuse box first.", "Işıklar söndüğünde önce sigorta kutusunu kontrol et."],
      ["make yourself at home", "kendi evin gibi rahat ol", "🏡", "Come in and make yourself at home, I'll bring some tea.", "Gel içeri, kendi evin gibi rahat ol, ben çay getiriyorum."],
      ["homebody", "evcimen kişi", "", "I'm a real homebody, I prefer staying in to going out.", "Tam bir evcimenim, dışarı çıkmaktansa evde kalmayı tercih ederim."],
      ["morning routine", "sabah rutini", "🌅", "My morning routine includes stretching and a big glass of water.", "Sabah rutinim esneme hareketlerini ve büyük bir bardak suyu içeriyor."],
      ["get ready", "hazırlanmak", "", "It takes me twenty minutes to get ready for work.", "İşe hazırlanmam yirmi dakikamı alıyor."],
      ["head home", "eve doğru yola çıkmak", "", "It's getting late, I think I'll head home now.", "Geç oluyor, sanırım artık eve doğru yola çıkacağım."],
      ["put the shopping away", "alışverişi yerleştirmek", "🛒", "Help me put the shopping away before the ice cream melts.", "Dondurma erimeden alışverişi yerleştirmeme yardım et."],
      ["potter around", "evde oyalanıp ufak işlerle uğraşmak", "", "On Sundays I just potter around the house and garden.", "Pazar günleri evde ve bahçede ufak işlerle oyalanırım."],
      ["doze off", "uyuklamak, içi geçmek", "💤", "I always doze off on the sofa while watching the news.", "Haberleri izlerken hep kanepede uyuklarım."],
      ["toss and turn", "yatakta dönüp durmak", "", "I often toss and turn when I'm worried about work.", "İşle ilgili endişelendiğimde çoğu zaman yatakta dönüp dururum."]
    ] }
);
