(window.LIBRARY = window.LIBRARY || []).push(
  { id: "lib2a", title: "Hukuk ve Devlet", icon: "⚖️", cefr: "C1", desc: "Mahkeme, yasa yapımı ve devlet kurumlarıyla ilgili ileri düzey kelimeler.",
    words: [
      ["constitution", "anayasa", "📜", "The new constitution guarantees equal treatment for every citizen of the country.", "Yeni anayasa ülkenin her vatandaşına eşit muamele güvencesi veriyor."],
      ["jurisdiction", "yargı yetkisi", "", "This court has no jurisdiction over crimes committed abroad.", "Bu mahkemenin yurt dışında işlenen suçlar üzerinde yargı yetkisi yok."],
      ["plaintiff", "davacı", "", "The plaintiff claims that the company ignored several safety warnings.", "Davacı, şirketin birkaç güvenlik uyarısını görmezden geldiğini iddia ediyor."],
      ["litigation", "dava süreci, yargılama", "", "Most small businesses cannot afford years of expensive litigation.", "Çoğu küçük işletme yıllarca sürecek pahalı bir yargılamayı karşılayamaz."],
      ["statute", "kanun, yasa maddesi", "", "The statute clearly defines what counts as a public building.", "Kanun neyin kamu binası sayıldığını açıkça tanımlıyor."],
      ["amendment", "değişiklik, yasa değişikliği", "", "Parliament approved an amendment that lowers the voting age to sixteen.", "Meclis oy kullanma yaşını on altıya düşüren bir değişikliği onayladı."],
      ["enforce", "uygulamak, yürürlüğe koymak", "", "The city has decided to enforce the parking rules more strictly.", "Şehir otopark kurallarını daha sıkı uygulamaya karar verdi."],
      ["compliance", "uyum, mevzuata uygunluk", "", "The bank hired ten new people to handle compliance with the regulations.", "Banka düzenlemelere uyumu yönetmek için on yeni kişi işe aldı."],
      ["legislature", "yasama organı", "", "The legislature will debate the proposal again next month.", "Yasama organı öneriyi gelecek ay yeniden tartışacak."],
      ["judiciary", "yargı", "", "An independent judiciary is essential for a healthy democracy.", "Bağımsız bir yargı sağlıklı bir demokrasi için vazgeçilmezdir."],
      ["separation of powers", "kuvvetler ayrılığı", "", "The separation of powers stops any single institution from becoming too strong.", "Kuvvetler ayrılığı tek bir kurumun aşırı güçlenmesini engeller."],
      ["rule of law", "hukukun üstünlüğü", "", "Investors prefer countries where the rule of law is respected.", "Yatırımcılar hukukun üstünlüğüne saygı duyulan ülkeleri tercih ediyor."],
      ["due process", "hukuki güvence, usulüne uygun yargılama", "", "Everyone has the right to due process, even people accused of serious crimes.", "Ağır suçlarla itham edilenler dahil herkesin usulüne uygun yargılanma hakkı vardır."],
      ["acquit", "beraat ettirmek, aklamak", "", "The jury decided to acquit him because the evidence was too weak.", "Jüri, deliller çok zayıf olduğu için onu beraat ettirmeye karar verdi."],
      ["convict", "mahkûm etmek", "", "The prosecutors failed to convict the manager of any wrongdoing.", "Savcılar müdürü herhangi bir suçtan mahkûm ettiremedi."],
      ["conviction", "mahkûmiyet", "", "His previous conviction made it hard for him to find a job.", "Önceki mahkûmiyeti iş bulmasını zorlaştırdı."],
      ["indictment", "iddianame", "", "The indictment lists twelve separate charges against the former mayor.", "İddianame eski belediye başkanına karşı on iki ayrı suçlama içeriyor."],
      ["prosecute", "kovuşturmak, yargılamak", "", "The state will prosecute anyone who sells fake medicine online.", "Devlet internette sahte ilaç satan herkesi yargılayacak."],
      ["prosecution", "kovuşturma, iddia makamı", "", "The prosecution called three experts to explain the financial records.", "İddia makamı mali kayıtları açıklamak için üç uzman çağırdı."],
      ["testimony", "tanık ifadesi", "", "Her testimony completely changed the direction of the trial.", "Onun tanık ifadesi davanın yönünü tamamen değiştirdi."],
      ["affidavit", "yeminli beyan", "", "He signed an affidavit confirming that he had never seen the documents.", "Belgeleri hiç görmediğini doğrulayan yeminli bir beyan imzaladı."],
      ["subpoena", "mahkeme celbi, celp etmek", "", "The committee issued a subpoena for all of the company's emails.", "Komisyon şirketin bütün e-postaları için bir celp çıkardı."],
      ["juror", "jüri üyesi", "", "One juror was dismissed after talking to a journalist about the case.", "Bir jüri üyesi dava hakkında bir gazeteciyle konuştuktan sonra görevden alındı."],
      ["parole", "şartlı tahliye", "", "He was released on parole after serving six years in prison.", "Cezaevinde altı yıl yattıktan sonra şartlı tahliye edildi."],
      ["custody", "gözaltı, velayet", "👨‍👧", "After the divorce, the mother was given full custody of the children.", "Boşanmadan sonra çocukların tam velayeti anneye verildi."],
      ["detain", "gözaltına almak, alıkoymak", "", "Police can detain a suspect for up to twenty four hours without charge.", "Polis bir şüpheliyi suçlama olmadan yirmi dört saate kadar gözaltında tutabilir."],
      ["warrant", "arama veya tutuklama emri", "", "The officers needed a warrant before they could search the apartment.", "Memurların daireyi arayabilmeleri için önce bir arama emrine ihtiyaçları vardı."],
      ["allegation", "iddia, suçlama", "", "The minister denied every allegation made in the newspaper report.", "Bakan gazete haberinde yer alan her iddiayı reddetti."],
      ["alleged", "iddia edilen, sözde", "", "The alleged victim refused to speak to reporters outside the court.", "İddia edilen mağdur mahkemenin önünde gazetecilerle konuşmayı reddetti."],
      ["liable", "sorumlu, yükümlü", "", "The landlord may be liable for any injuries caused by the broken stairs.", "Ev sahibi kırık merdivenlerin yol açtığı yaralanmalardan sorumlu tutulabilir."],
      ["liability", "yükümlülük, hukuki sorumluluk", "", "The company accepted liability and agreed to pay for the repairs.", "Şirket sorumluluğu kabul etti ve onarımların masrafını ödemeyi kabul etti."],
      ["negligence", "ihmal, dikkatsizlik", "", "The hospital was found guilty of negligence in the patient's death.", "Hastane hastanın ölümünde ihmalden suçlu bulundu."],
      ["damages", "tazminat", "💰", "The court ordered the newspaper to pay damages to the singer.", "Mahkeme gazetenin şarkıcıya tazminat ödemesine hükmetti."],
      ["settle out of court", "mahkeme dışında uzlaşmak", "🤝", "Both sides decided to settle out of court to avoid bad publicity.", "Her iki taraf da kötü bir imaj oluşmasın diye mahkeme dışında uzlaşmaya karar verdi."],
      ["precedent", "emsal, örnek karar", "", "This decision could set a precedent for thousands of similar cases.", "Bu karar binlerce benzer dava için emsal oluşturabilir."],
      ["ruling", "karar, hüküm", "", "The judge's ruling surprised both the lawyers and the public.", "Hâkimin kararı hem avukatları hem de kamuoyunu şaşırttı."],
      ["overturn", "bozmak, iptal etmek", "", "The higher court may overturn the decision if new evidence appears.", "Yeni deliller çıkarsa üst mahkeme kararı bozabilir."],
      ["uphold", "onamak, korumak", "", "The appeals court decided to uphold the original sentence.", "İstinaf mahkemesi ilk cezayı onamaya karar verdi."],
      ["dismiss", "reddetmek, düşürmek", "", "The judge may dismiss the case if the documents are not submitted on time.", "Belgeler zamanında sunulmazsa hâkim davayı düşürebilir."],
      ["file a complaint", "şikâyette bulunmak", "📝", "If the noise continues, you should file a complaint with the council.", "Gürültü devam ederse belediyeye şikâyette bulunmalısın."],
      ["breach of contract", "sözleşme ihlali", "", "The supplier was sued for breach of contract after missing three deadlines.", "Tedarikçi üç teslim tarihini kaçırınca sözleşme ihlali nedeniyle dava edildi."],
      ["provision", "hüküm, madde", "", "A special provision protects workers who report illegal activity.", "Özel bir hüküm yasa dışı faaliyetleri bildiren çalışanları koruyor."],
      ["void", "geçersiz, hükümsüz", "", "The agreement was declared void because one signature was forged.", "İmzalardan biri sahte olduğu için anlaşma geçersiz ilan edildi."],
      ["loophole", "kanun boşluğu", "", "Wealthy firms often use a legal loophole to pay less tax.", "Zengin şirketler daha az vergi ödemek için çoğu zaman bir kanun boşluğu kullanır."],
      ["legitimate", "meşru, yasal", "", "Asking for a refund after a delayed flight is a legitimate request.", "Rötar yapan bir uçuştan sonra para iadesi istemek meşru bir taleptir."],
      ["legitimacy", "meşruiyet", "", "The low turnout raised questions about the legitimacy of the result.", "Düşük katılım sonucun meşruiyetine dair soru işaretleri doğurdu."],
      ["legal aid", "adli yardım", "", "People on low incomes can apply for free legal aid.", "Düşük gelirli kişiler ücretsiz adli yardım için başvurabilir."],
      ["guardian", "vasi, veli", "", "Her uncle became her legal guardian after her parents passed away.", "Ebeveynleri vefat edince amcası onun yasal vasisi oldu."],
      ["attorney", "avukat", "👩‍⚖️", "You should not answer any questions until your attorney arrives.", "Avukatın gelene kadar hiçbir soruya cevap vermemelisin."],
      ["counsel", "hukuk danışmanı, avukat", "", "The defense counsel asked for more time to review the evidence.", "Savunma avukatı delilleri incelemek için ek süre istedi."],
      ["plead guilty", "suçunu kabul etmek", "", "He chose to plead guilty in exchange for a shorter sentence.", "Daha kısa bir ceza karşılığında suçunu kabul etmeyi seçti."],
      ["plea", "savunma, beyan", "", "Her plea of not guilty was recorded at the first hearing.", "Suçsuz olduğuna dair beyanı ilk duruşmada kayda geçti."],
      ["cross-examine", "çapraz sorgulamak", "", "The lawyer will cross-examine the witness after the lunch break.", "Avukat öğle arasından sonra tanığı çapraz sorgulayacak."],
      ["hearing", "duruşma", "", "The next hearing has been postponed until the end of March.", "Bir sonraki duruşma mart sonuna ertelendi."],
      ["courtroom", "duruşma salonu", "🏛️", "The courtroom fell silent when the judge entered.", "Hâkim içeri girince duruşma salonu sessizliğe büründü."],
      ["supreme court", "yüksek mahkeme, yargıtay", "", "The case finally reached the supreme court after eight years.", "Dava sekiz yılın sonunda nihayet yüksek mahkemeye ulaştı."],
      ["bureaucracy", "bürokrasi", "📂", "Starting a business here involves far too much bureaucracy.", "Burada iş kurmak çok fazla bürokrasi gerektiriyor."],
      ["bureaucrat", "bürokrat", "", "A senior bureaucrat explained the new rules to the press.", "Üst düzey bir bürokrat yeni kuralları basına açıkladı."],
      ["regulatory", "düzenleyici", "", "The drug still needs approval from the regulatory agency.", "İlacın hâlâ düzenleyici kurumdan onay alması gerekiyor."],
      ["authority", "yetki, makam, otorite", "", "Only the local authority can give permission for the new building.", "Yeni bina için yalnızca yerel yönetim izin verebilir."],
      ["decree", "kararname", "", "The president issued a decree closing all schools for a week.", "Cumhurbaşkanı tüm okulları bir hafta kapatan bir kararname çıkardı."],
      ["ordinance", "yönetmelik, belediye kararı", "", "A new ordinance bans loud music in the park after ten.", "Yeni bir yönetmelik saat ondan sonra parkta yüksek sesle müziği yasaklıyor."],
      ["municipality", "belediye", "", "The municipality plans to build three new libraries next year.", "Belediye gelecek yıl üç yeni kütüphane inşa etmeyi planlıyor."],
      ["public sector", "kamu sektörü", "", "Salaries in the public sector rose by five percent this year.", "Kamu sektöründe maaşlar bu yıl yüzde beş arttı."],
      ["state-owned", "devlete ait", "", "The state-owned railway company is finally being modernized.", "Devlete ait demiryolu şirketi nihayet modernleştiriliyor."],
      ["tax evasion", "vergi kaçakçılığı", "", "The businessman was arrested for tax evasion and false accounting.", "İş insanı vergi kaçakçılığı ve sahte muhasebe nedeniyle tutuklandı."],
      ["embezzlement", "zimmete para geçirme", "", "The accountant was charged with embezzlement after money went missing.", "Para kaybolunca muhasebeci zimmete para geçirmekle suçlandı."],
      ["money laundering", "kara para aklama", "", "Banks must report any transfers that suggest money laundering.", "Bankalar kara para aklamaya işaret eden her transferi bildirmek zorunda."],
      ["perjury", "yalan yere yemin", "", "Lying under oath is perjury and can lead to prison.", "Yeminli olarak yalan söylemek yalan yere yemindir ve hapse yol açabilir."],
      ["misdemeanor", "kabahat, hafif suç", "", "Crossing the road on a red light is only a misdemeanor here.", "Burada kırmızı ışıkta karşıya geçmek yalnızca bir kabahattir."],
      ["felony", "ağır suç", "", "Armed robbery is a felony that carries a long prison term.", "Silahlı soygun uzun hapis cezası gerektiren ağır bir suçtur."],
      ["offender", "suçlu, fail", "", "The program helps every young offender find work after leaving prison.", "Program her genç hükümlünün cezaevinden çıktıktan sonra iş bulmasına yardım ediyor."],
      ["penalty", "ceza, yaptırım", "", "The penalty for late tax returns has doubled since last year.", "Geç verilen vergi beyannameleri için ceza geçen yıldan bu yana iki katına çıktı."],
      ["impose", "dayatmak, uygulamaya koymak", "", "The government plans to impose stricter limits on air pollution.", "Hükümet hava kirliliğine daha sıkı sınırlar getirmeyi planlıyor."],
      ["abolish", "kaldırmak, ilga etmek", "", "Many countries decided to abolish the death penalty decades ago.", "Birçok ülke ölüm cezasını onlarca yıl önce kaldırmaya karar verdi."],
      ["enact", "yasalaştırmak", "", "Lawmakers hope to enact the new privacy rules before the summer.", "Milletvekilleri yeni gizlilik kurallarını yazdan önce yasalaştırmayı umuyor."],
      ["repeal", "yürürlükten kaldırmak", "", "Protesters are demanding that the government repeal the unpopular law.", "Protestocular hükümetin bu sevilmeyen yasayı yürürlükten kaldırmasını istiyor."],
      ["come into force", "yürürlüğe girmek", "", "The new traffic rules will come into force on the first of January.", "Yeni trafik kuralları bir ocakta yürürlüğe girecek."],
      ["jurisprudence", "hukuk bilimi, içtihat", "", "She is writing her thesis on European jurisprudence and human dignity.", "Tezini Avrupa içtihadı ve insan onuru üzerine yazıyor."],
      ["civil law", "medeni hukuk", "", "Disputes between neighbors are usually handled under civil law.", "Komşular arasındaki anlaşmazlıklar genellikle medeni hukuk kapsamında ele alınır."],
      ["criminal law", "ceza hukuku", "", "He specialized in criminal law because he wanted to defend ordinary people.", "Sıradan insanları savunmak istediği için ceza hukuku alanında uzmanlaştı."],
      ["copyright", "telif hakkı", "©️", "You cannot use these photos without permission because of copyright.", "Telif hakkı nedeniyle bu fotoğrafları izinsiz kullanamazsın."],
      ["power of attorney", "vekâletname", "", "She gave her brother power of attorney while she was working abroad.", "Yurt dışında çalışırken kardeşine vekâletname verdi."],
      ["inheritance", "miras", "", "The two sisters argued for years over their inheritance.", "İki kız kardeş miras yüzünden yıllarca tartıştı."],
      ["civil rights", "medeni haklar, yurttaşlık hakları", "", "The civil rights movement changed how people thought about equality.", "Medeni haklar hareketi insanların eşitlik hakkındaki düşüncesini değiştirdi."],
      ["confiscate", "el koymak, müsadere etmek", "", "Customs officers may confiscate any food you bring into the country.", "Gümrük memurları ülkeye getirdiğin her türlü yiyeceğe el koyabilir."],
      ["seize", "el koymak, ele geçirmek", "", "Police managed to seize two tons of illegal goods at the port.", "Polis limanda iki ton yasa dışı mala el koymayı başardı."],
      ["extradite", "suçluyu iade etmek", "", "The two countries agreed to extradite the suspect within a month.", "İki ülke şüpheliyi bir ay içinde iade etmeyi kabul etti."],
      ["extradition", "suçlu iadesi", "", "There is no extradition agreement between these two countries.", "Bu iki ülke arasında suçlu iadesi anlaşması yok."],
      ["amnesty", "af, genel af", "", "The government announced an amnesty for people with unpaid parking fines.", "Hükümet ödenmemiş otopark cezası olanlar için bir af ilan etti."],
      ["pardon", "affetmek, af", "", "The president refused to pardon the officials involved in the scandal.", "Cumhurbaşkanı skandala karışan yetkilileri affetmeyi reddetti."],
      ["impartial", "tarafsız", "", "A judge must remain impartial, whatever their personal opinions are.", "Bir hâkim kişisel görüşleri ne olursa olsun tarafsız kalmalıdır."],
      ["oversight", "denetim, gözetim", "👁️", "Parliament has oversight of how the security services spend their budget.", "Meclis güvenlik birimlerinin bütçelerini nasıl harcadığını denetler."],
      ["audit", "denetim, denetlemek", "", "An external audit revealed serious mistakes in the ministry's accounts.", "Dış denetim bakanlığın hesaplarında ciddi hatalar ortaya çıkardı."],
      ["constitutional", "anayasal", "", "Freedom of the press is a constitutional right in most democracies.", "Basın özgürlüğü çoğu demokraside anayasal bir haktır."],
      ["unconstitutional", "anayasaya aykırı", "", "The court ruled that the new curfew was unconstitutional.", "Mahkeme yeni sokağa çıkma yasağının anayasaya aykırı olduğuna hükmetti."],
      ["statute of limitations", "zamanaşımı", "⏳", "The statute of limitations for this kind of fraud is ten years.", "Bu tür bir dolandırıcılık için zamanaşımı on yıldır."],
      ["burden of proof", "ispat yükü", "", "In a criminal case, the burden of proof is on the prosecution.", "Ceza davasında ispat yükü iddia makamındadır."],
      ["beyond reasonable doubt", "makul şüphenin ötesinde", "", "Guilt must be proven beyond reasonable doubt before anyone is sent to prison.", "Biri hapse gönderilmeden önce suçun makul şüphenin ötesinde kanıtlanması gerekir."],
      ["presumption of innocence", "masumiyet karinesi", "", "Social media often ignores the presumption of innocence completely.", "Sosyal medya masumiyet karinesini çoğu zaman tamamen görmezden geliyor."],
      ["legal proceedings", "hukuki süreç, yasal işlemler", "", "The company has started legal proceedings against its former director.", "Şirket eski müdürüne karşı yasal işlem başlattı."],
      ["state of emergency", "olağanüstü hal", "🚨", "A state of emergency was declared after the floods destroyed several towns.", "Seller birkaç kasabayı yerle bir edince olağanüstü hal ilan edildi."],
      ["martial law", "sıkıyönetim", "", "Under martial law, the army controlled the streets of the capital.", "Sıkıyönetim altında başkentin sokaklarını ordu kontrol ediyordu."],
      ["injunction", "ihtiyati tedbir, mahkeme yasağı", "", "The residents won an injunction that stopped the construction for six months.", "Sakinler inşaatı altı ay durduran bir ihtiyati tedbir kararı aldı."],
      ["defamation", "iftira, hakaret", "", "The actor sued the magazine for defamation over the false story.", "Oyuncu yalan haber nedeniyle dergiye hakaret davası açtı."],
      ["arbitration", "tahkim", "", "The contract says that any dispute will be settled through arbitration.", "Sözleşmeye göre her türlü anlaşmazlık tahkim yoluyla çözülecek."],
      ["lawmaker", "yasa koyucu, milletvekili", "", "One lawmaker suggested a tax on sugary drinks to fight obesity.", "Bir milletvekili obeziteyle mücadele için şekerli içeceklere vergi önerdi."],
      ["law enforcement", "kolluk kuvvetleri", "👮", "Law enforcement agencies are sharing information to stop online scams.", "Kolluk kuvvetleri internet dolandırıcılığını durdurmak için bilgi paylaşıyor."],
      ["criminal record", "sabıka kaydı", "", "Applicants for this job must not have a criminal record.", "Bu işe başvuranların sabıka kaydı olmamalıdır."],
      ["civil liberties", "temel hak ve özgürlükler", "", "Critics say the new surveillance law threatens our civil liberties.", "Eleştirmenler yeni gözetim yasasının temel özgürlüklerimizi tehdit ettiğini söylüyor."]
    ] },
  { id: "lib2b", title: "Siyaset ve Uluslararası İlişkiler", icon: "🌍", cefr: "C1", desc: "Diplomasi, seçimler, çatışma ve küresel güç dengeleri için ileri düzey kelimeler.",
    words: [
      ["sovereignty", "egemenlik", "", "Both nations claim sovereignty over the small island.", "Her iki ülke de küçük ada üzerinde egemenlik iddia ediyor."],
      ["diplomacy", "diplomasi", "🕊️", "Quiet diplomacy achieved more than months of public threats.", "Sessiz diplomasi aylarca süren açık tehditlerden daha fazlasını başardı."],
      ["diplomat", "diplomat", "", "The diplomat was asked to leave the country within forty eight hours.", "Diplomattan kırk sekiz saat içinde ülkeyi terk etmesi istendi."],
      ["diplomatic", "diplomatik", "", "The two countries cut diplomatic ties after the incident.", "İki ülke olaydan sonra diplomatik ilişkilerini kesti."],
      ["treaty", "antlaşma", "📜", "The treaty was signed by twelve countries in a ceremony in Geneva.", "Antlaşma Cenevre'deki bir törenle on iki ülke tarafından imzalandı."],
      ["alliance", "ittifak", "", "The military alliance was formed to protect its members from attack.", "Askeri ittifak üyelerini saldırıya karşı korumak için kuruldu."],
      ["ally", "müttefik", "", "The country has always been a close ally of its western neighbors.", "Ülke her zaman batılı komşularının yakın bir müttefiki oldu."],
      ["embassy", "büyükelçilik", "🏢", "You need to visit the embassy to apply for a work visa.", "Çalışma vizesine başvurmak için büyükelçiliğe gitmen gerekiyor."],
      ["ambassador", "büyükelçi", "", "The new ambassador presented her credentials to the president this morning.", "Yeni büyükelçi bu sabah güven mektubunu cumhurbaşkanına sundu."],
      ["consulate", "konsolosluk", "", "The consulate helped him get a new passport after his was stolen.", "Pasaportu çalınınca konsolosluk yeni pasaport almasına yardım etti."],
      ["envoy", "özel temsilci, elçi", "", "A special envoy was sent to calm the situation in the region.", "Bölgedeki durumu yatıştırmak için özel bir temsilci gönderildi."],
      ["summit", "zirve", "", "World leaders will meet at a climate summit later this year.", "Dünya liderleri bu yılın ilerleyen dönemlerinde bir iklim zirvesinde buluşacak."],
      ["bilateral", "ikili, iki taraflı", "", "The two governments signed a bilateral trade agreement yesterday.", "İki hükümet dün ikili bir ticaret anlaşması imzaladı."],
      ["multilateral", "çok taraflı", "", "Climate change can only be solved through multilateral cooperation.", "İklim değişikliği ancak çok taraflı işbirliğiyle çözülebilir."],
      ["ratify", "onaylamak", "", "Parliament still has to ratify the agreement before it becomes law.", "Anlaşmanın yasalaşmadan önce meclis tarafından onaylanması gerekiyor."],
      ["foreign policy", "dış politika", "", "Energy security has become the center of the country's foreign policy.", "Enerji güvenliği ülkenin dış politikasının merkezine yerleşti."],
      ["superpower", "süper güç", "", "Some experts believe the world now has more than one superpower.", "Bazı uzmanlar dünyada artık birden fazla süper güç olduğuna inanıyor."],
      ["geopolitics", "jeopolitik", "", "You cannot understand energy prices without understanding geopolitics.", "Jeopolitiği anlamadan enerji fiyatlarını anlayamazsın."],
      ["territorial", "toprakla ilgili, bölgesel", "", "The two neighbors have had territorial disagreements for decades.", "İki komşunun onlarca yıldır toprak anlaşmazlıkları var."],
      ["border dispute", "sınır anlaşmazlığı", "", "The border dispute was finally resolved by an international court.", "Sınır anlaşmazlığı sonunda uluslararası bir mahkeme tarafından çözüldü."],
      ["annex", "ilhak etmek", "", "The decision to annex the region was condemned around the world.", "Bölgeyi ilhak etme kararı tüm dünyada kınandı."],
      ["occupation", "işgal", "", "The occupation lasted for almost ten years and left deep scars.", "İşgal neredeyse on yıl sürdü ve derin izler bıraktı."],
      ["invasion", "istila, işgal", "", "The invasion forced hundreds of thousands of people to leave their homes.", "İstila yüz binlerce insanı evlerini terk etmeye zorladı."],
      ["ceasefire", "ateşkes", "🏳️", "A ceasefire came into effect at midnight, but fighting continued in the north.", "Ateşkes gece yarısı yürürlüğe girdi ama kuzeyde çatışmalar sürdü."],
      ["truce", "geçici ateşkes, mütareke", "", "The rival groups agreed to a short truce during the holiday.", "Rakip gruplar bayram boyunca kısa bir ateşkes konusunda anlaştı."],
      ["peacekeeping", "barışı koruma", "", "The peacekeeping mission includes soldiers from fifteen countries.", "Barışı koruma misyonunda on beş ülkeden askerler bulunuyor."],
      ["peace talks", "barış görüşmeleri", "", "The peace talks collapsed after only two days.", "Barış görüşmeleri yalnızca iki gün sonra çöktü."],
      ["mediate", "arabuluculuk yapmak", "", "Norway offered to mediate between the government and the rebels.", "Norveç hükümet ile isyancılar arasında arabuluculuk yapmayı teklif etti."],
      ["mediator", "arabulucu", "", "A neutral mediator helped both sides find common ground.", "Tarafsız bir arabulucu iki tarafın ortak bir zemin bulmasına yardım etti."],
      ["escalate", "tırmanmak, tırmandırmak", "📈", "Experts fear the conflict could escalate into a regional war.", "Uzmanlar çatışmanın bölgesel bir savaşa dönüşecek şekilde tırmanmasından korkuyor."],
      ["de-escalate", "gerginliği azaltmak", "", "Both leaders made phone calls to de-escalate the situation.", "Her iki lider de gerginliği azaltmak için telefon görüşmeleri yaptı."],
      ["hostility", "düşmanlık", "", "Years of hostility made it hard for the two peoples to trust each other.", "Yıllarca süren düşmanlık iki halkın birbirine güvenmesini zorlaştırdı."],
      ["hostile", "düşmanca, hasmane", "", "The minister faced a hostile crowd when he visited the factory.", "Bakan fabrikayı ziyaret ettiğinde düşmanca bir kalabalıkla karşılaştı."],
      ["aggression", "saldırganlık", "", "The council condemned the act of aggression against a peaceful neighbor.", "Konsey barışçıl bir komşuya yönelik saldırganlığı kınadı."],
      ["deterrence", "caydırıcılık", "", "The policy of deterrence is based on making an attack too costly.", "Caydırıcılık politikası bir saldırıyı fazla maliyetli kılmaya dayanır."],
      ["arms race", "silahlanma yarışı", "", "Many feared the new missiles would start another arms race.", "Pek çok kişi yeni füzelerin yeni bir silahlanma yarışı başlatmasından korktu."],
      ["disarmament", "silahsızlanma", "", "The disarmament talks focused on reducing nuclear stockpiles.", "Silahsızlanma görüşmeleri nükleer stokların azaltılmasına odaklandı."],
      ["non-proliferation", "nükleer silahların yayılmasını önleme", "", "The non-proliferation agreement aims to stop the spread of nuclear weapons.", "Yayılmayı önleme anlaşması nükleer silahların yayılmasını durdurmayı amaçlıyor."],
      ["embargo", "ambargo", "🚫", "The oil embargo caused fuel prices to rise sharply across Europe.", "Petrol ambargosu Avrupa genelinde yakıt fiyatlarının hızla yükselmesine yol açtı."],
      ["trade war", "ticaret savaşı", "", "Consumers end up paying more when two countries start a trade war.", "İki ülke bir ticaret savaşı başlattığında sonunda tüketiciler daha fazla öder."],
      ["globalization", "küreselleşme", "🌐", "Globalization has created jobs in some places and destroyed them in others.", "Küreselleşme bazı yerlerde iş yarattı, bazı yerlerde ise işleri yok etti."],
      ["humanitarian", "insani", "", "The earthquake caused a humanitarian crisis in the mountain villages.", "Deprem dağ köylerinde insani bir krize yol açtı."],
      ["humanitarian aid", "insani yardım", "📦", "Trucks carrying humanitarian aid were finally allowed to cross the border.", "İnsani yardım taşıyan kamyonların nihayet sınırı geçmesine izin verildi."],
      ["asylum seeker", "sığınmacı", "", "Every asylum seeker has the right to have their case heard fairly.", "Her sığınmacının başvurusunun adil şekilde değerlendirilmesi hakkı vardır."],
      ["displaced", "yerinden edilmiş", "", "Thousands of displaced families are living in temporary camps.", "Yerinden edilmiş binlerce aile geçici kamplarda yaşıyor."],
      ["stateless", "vatansız", "", "Being stateless means having no passport and very few rights.", "Vatansız olmak pasaportunun olmaması ve çok az hakka sahip olmak demektir."],
      ["ruling party", "iktidar partisi", "", "The ruling party lost its majority in the last election.", "İktidar partisi son seçimde çoğunluğunu kaybetti."],
      ["incumbent", "görevdeki, makamdaki kişi", "", "The incumbent mayor is running for a third term.", "Görevdeki belediye başkanı üçüncü dönem için aday oluyor."],
      ["electorate", "seçmen kitlesi", "🗳️", "The electorate is clearly tired of broken promises.", "Seçmen kitlesi tutulmayan sözlerden açıkça bıkmış durumda."],
      ["mandate", "yetki, halkın verdiği görev", "", "The new government says it has a clear mandate for reform.", "Yeni hükümet reform için açık bir yetkisi olduğunu söylüyor."],
      ["polling station", "oy verme yeri, sandık", "", "Long queues formed outside every polling station in the city.", "Şehirdeki her sandık noktasının önünde uzun kuyruklar oluştu."],
      ["swing voter", "kararsız seçmen", "", "Both candidates are trying hard to win over the swing voter.", "Her iki aday da kararsız seçmeni kazanmak için çok uğraşıyor."],
      ["lobby", "lobi yapmak, lobi", "", "Environmental groups lobby the government to ban single use plastics.", "Çevre grupları tek kullanımlık plastikleri yasaklatmak için hükümet nezdinde lobi yapıyor."],
      ["lobbyist", "lobici", "", "A lobbyist for the tobacco industry met the minister twice last month.", "Tütün sektörünün bir lobicisi geçen ay bakanla iki kez görüştü."],
      ["grassroots", "tabandan gelen", "🌱", "The campaign started as a small grassroots movement in one village.", "Kampanya tek bir köyde küçük, tabandan gelen bir hareket olarak başladı."],
      ["populist", "popülist", "", "The populist leader promised to fight the corrupt elite.", "Popülist lider yozlaşmış seçkinlerle savaşacağına söz verdi."],
      ["partisan", "taraflı, partizan", "", "The debate became so partisan that no real solutions were discussed.", "Tartışma o kadar taraflı hâle geldi ki gerçek çözümler konuşulmadı."],
      ["bipartisan", "iki partinin desteklediği", "", "The infrastructure bill received rare bipartisan support in the senate.", "Altyapı yasa tasarısı senatoda nadir görülen bir iki parti desteği aldı."],
      ["polarization", "kutuplaşma", "", "Social media is often blamed for the growing political polarization.", "Artan siyasi kutuplaşma için çoğu zaman sosyal medya suçlanıyor."],
      ["left-wing", "sol görüşlü, solcu", "", "The left-wing parties want higher taxes on large companies.", "Sol partiler büyük şirketlere daha yüksek vergi istiyor."],
      ["right-wing", "sağ görüşlü, sağcı", "", "A right-wing newspaper criticized the plan as too expensive.", "Sağ görüşlü bir gazete planı fazla pahalı bulup eleştirdi."],
      ["conservative", "muhafazakâr", "", "Older voters in the region tend to be more conservative.", "Bölgedeki yaşlı seçmenler daha muhafazakâr olma eğiliminde."],
      ["liberal", "liberal, özgürlükçü", "", "The city is known for its liberal attitudes and lively nightlife.", "Şehir özgürlükçü tutumları ve hareketli gece hayatıyla bilinir."],
      ["moderate", "ılımlı", "", "She is seen as a moderate who can talk to both sides.", "Her iki tarafla da konuşabilen ılımlı biri olarak görülüyor."],
      ["radical", "radikal, köklü", "", "The party is calling for radical changes to the education system.", "Parti eğitim sisteminde köklü değişiklikler yapılması çağrısında bulunuyor."],
      ["extremism", "aşırıcılık", "", "Schools have a role to play in preventing extremism among young people.", "Okulların gençler arasında aşırıcılığı önlemede oynayacağı bir rol var."],
      ["propaganda", "propaganda", "📢", "During the war, the radio was full of propaganda.", "Savaş sırasında radyo propagandayla doluydu."],
      ["rhetoric", "söylem, hitabet", "", "His angry rhetoric made the negotiations even harder.", "Öfkeli söylemi müzakereleri daha da zorlaştırdı."],
      ["spin doctor", "algı yöneticisi", "", "The party's spin doctor tried to present the defeat as a success.", "Partinin algı yöneticisi yenilgiyi bir başarı gibi sunmaya çalıştı."],
      ["impeach", "görevden almak için yargılamak", "", "The opposition does not have enough votes to impeach the president.", "Muhalefetin cumhurbaşkanını azil sürecine sokacak kadar oyu yok."],
      ["veto", "veto etmek, veto", "", "The president threatened to veto any bill that raised taxes.", "Cumhurbaşkanı vergileri artıran her yasa tasarısını veto etmekle tehdit etti."],
      ["term limit", "görev süresi sınırı", "", "A two term limit prevents leaders from staying in power forever.", "İki dönemlik görev sınırı liderlerin sonsuza kadar iktidarda kalmasını engeller."],
      ["inauguration", "yemin töreni, göreve başlama", "", "Thousands of people gathered in the square for the inauguration.", "Binlerce kişi yemin töreni için meydanda toplandı."],
      ["sworn in", "yemin ederek göreve başlamak", "", "The new ministers were sworn in at the palace on Monday.", "Yeni bakanlar pazartesi günü sarayda yemin ederek göreve başladı."],
      ["cabinet", "kabine, bakanlar kurulu", "", "The prime minister reshuffled the cabinet after the scandal.", "Başbakan skandaldan sonra kabinede değişikliğe gitti."],
      ["head of state", "devlet başkanı", "", "In some countries, the king is the head of state but has little power.", "Bazı ülkelerde kral devlet başkanıdır ama çok az yetkisi vardır."],
      ["regime", "rejim, yönetim", "", "The regime has silenced almost every independent journalist.", "Rejim neredeyse her bağımsız gazeteciyi susturdu."],
      ["authoritarian", "otoriter", "", "Authoritarian governments often control the media and the courts.", "Otoriter hükümetler çoğu zaman medyayı ve mahkemeleri kontrol eder."],
      ["dictatorship", "diktatörlük", "", "The country became a democracy after forty years of dictatorship.", "Ülke kırk yıllık diktatörlüğün ardından demokrasiye geçti."],
      ["coup", "darbe", "", "The army seized power in a coup early on Sunday morning.", "Ordu pazar sabahı erken saatlerde bir darbeyle yönetimi ele geçirdi."],
      ["uprising", "ayaklanma", "", "The uprising began when food prices doubled in a single month.", "Ayaklanma, gıda fiyatları tek bir ayda iki katına çıkınca başladı."],
      ["revolt", "isyan etmek, isyan", "", "The farmers began to revolt against the new land taxes.", "Çiftçiler yeni arazi vergilerine karşı isyan etmeye başladı."],
      ["dissent", "muhalefet, karşı görüş", "", "The government shows little tolerance for dissent of any kind.", "Hükümet her türlü muhalefete çok az hoşgörü gösteriyor."],
      ["dissident", "muhalif", "", "The dissident writer has lived in exile for twenty years.", "Muhalif yazar yirmi yıldır sürgünde yaşıyor."],
      ["insurgency", "isyan hareketi, silahlı başkaldırı", "", "The insurgency in the mountains has lasted more than a decade.", "Dağlardaki silahlı başkaldırı on yıldan uzun süredir devam ediyor."],
      ["intelligence agency", "istihbarat teşkilatı", "🕵️", "The intelligence agency warned about a possible cyber attack.", "İstihbarat teşkilatı olası bir siber saldırı konusunda uyardı."],
      ["espionage", "casusluk", "", "Two engineers were arrested on charges of industrial espionage.", "İki mühendis endüstriyel casusluk suçlamasıyla tutuklandı."],
      ["national security", "ulusal güvenlik", "", "The documents were kept secret for reasons of national security.", "Belgeler ulusal güvenlik gerekçesiyle gizli tutuldu."],
      ["sovereign", "egemen, bağımsız", "", "Every sovereign state has the right to choose its own path.", "Her egemen devletin kendi yolunu seçme hakkı vardır."],
      ["self-determination", "kendi kaderini tayin hakkı", "", "The people of the island voted for self-determination.", "Adanın halkı kendi kaderini tayin hakkı için oy kullandı."],
      ["secede", "ayrılmak, bağımsızlık ilan etmek", "", "The northern province wants to secede and form its own country.", "Kuzeydeki eyalet ayrılıp kendi ülkesini kurmak istiyor."],
      ["separatist", "ayrılıkçı", "", "Separatist groups control parts of the eastern region.", "Ayrılıkçı gruplar doğu bölgesinin bazı kısımlarını kontrol ediyor."],
      ["nationalism", "milliyetçilik", "", "Rising nationalism has made cooperation between neighbors more difficult.", "Yükselen milliyetçilik komşular arasındaki işbirliğini zorlaştırdı."],
      ["patriotism", "vatanseverlik", "", "For him, patriotism means improving the country, not praising it blindly.", "Ona göre vatanseverlik ülkeyi körü körüne övmek değil, geliştirmektir."],
      ["colonialism", "sömürgecilik", "", "The effects of colonialism can still be seen in the region's borders.", "Sömürgeciliğin etkileri bölgenin sınırlarında hâlâ görülebiliyor."],
      ["hegemony", "hegemonya, üstünlük", "", "No single country can maintain global hegemony for very long.", "Hiçbir ülke küresel hegemonyasını çok uzun süre koruyamaz."],
      ["soft power", "yumuşak güç", "", "Films and music are an important part of a country's soft power.", "Filmler ve müzik bir ülkenin yumuşak gücünün önemli bir parçasıdır."],
      ["balance of power", "güç dengesi", "⚖️", "The new alliance could change the balance of power in the region.", "Yeni ittifak bölgedeki güç dengesini değiştirebilir."],
      ["foreign aid", "dış yardım", "", "The country receives foreign aid to rebuild its schools and hospitals.", "Ülke okullarını ve hastanelerini yeniden inşa etmek için dış yardım alıyor."],
      ["delegation", "heyet", "", "A trade delegation from Japan will visit Istanbul next week.", "Japonya'dan bir ticaret heyeti gelecek hafta İstanbul'u ziyaret edecek."],
      ["negotiation", "müzakere", "", "After a long negotiation, both sides accepted the final text.", "Uzun bir müzakerenin ardından iki taraf da nihai metni kabul etti."],
      ["accord", "uzlaşı, anlaşma", "", "The peace accord was signed after nine months of talks.", "Barış anlaşması dokuz aylık görüşmelerin ardından imzalandı."],
      ["pact", "pakt, antlaşma", "", "The neighbors signed a pact promising never to attack each other.", "Komşular birbirine asla saldırmayacaklarına dair bir pakt imzaladı."],
      ["statesman", "devlet adamı", "", "He is remembered as a statesman who put peace before politics.", "Barışı siyasetin önünde tutan bir devlet adamı olarak hatırlanıyor."],
      ["policymaker", "politika yapıcı", "", "Every policymaker should read this report on youth unemployment.", "Her politika yapıcı genç işsizliği hakkındaki bu raporu okumalı."],
      ["think tank", "düşünce kuruluşu", "💡", "A think tank in Brussels published a study on energy security.", "Brüksel'deki bir düşünce kuruluşu enerji güvenliği üzerine bir çalışma yayımladı."],
      ["sphere of influence", "nüfuz alanı", "", "The great powers competed to expand their sphere of influence.", "Büyük güçler nüfuz alanlarını genişletmek için yarıştı."],
      ["proxy war", "vekâlet savaşı", "", "Many analysts describe the conflict as a proxy war between two powers.", "Pek çok analist çatışmayı iki güç arasındaki bir vekâlet savaşı olarak tanımlıyor."],
      ["intervene", "müdahale etmek", "", "The international community was slow to intervene in the crisis.", "Uluslararası toplum krize müdahale etmekte yavaş kaldı."],
      ["intervention", "müdahale", "", "Military intervention should always be the very last option.", "Askeri müdahale her zaman en son seçenek olmalıdır."]
    ] },
  { id: "lib2c", title: "Toplum ve Sosyoloji", icon: "👥", cefr: "B2", desc: "Toplumsal sınıf, aile, kültür ve eşitlik üzerine konuşmak için kelimeler.",
    words: [
      ["social mobility", "toplumsal hareketlilik", "", "Good public schools are the key to social mobility.", "İyi devlet okulları toplumsal hareketliliğin anahtarıdır."],
      ["working class", "işçi sınıfı", "", "She grew up in a working class neighborhood near the docks.", "Limanın yakınındaki bir işçi sınıfı mahallesinde büyüdü."],
      ["middle class", "orta sınıf", "", "Rising rents are putting pressure on the middle class.", "Artan kiralar orta sınıf üzerinde baskı oluşturuyor."],
      ["upper class", "üst sınıf", "", "In the novel, he falls in love with a girl from the upper class.", "Romanda üst sınıftan bir kıza âşık oluyor."],
      ["elite", "seçkinler, elit", "", "Only a small elite could afford to study abroad at that time.", "O zamanlar yalnızca küçük bir seçkin kesim yurt dışında okuyabiliyordu."],
      ["privileged", "ayrıcalıklı", "", "I know I was privileged to have parents who supported my education.", "Eğitimimi destekleyen bir ailem olduğu için ayrıcalıklı olduğumu biliyorum."],
      ["underprivileged", "imkânları kısıtlı, yoksul", "", "The charity gives free laptops to underprivileged students every year.", "Hayır kurumu her yıl imkânları kısıtlı öğrencilere ücretsiz dizüstü bilgisayar veriyor."],
      ["marginalized", "dışlanmış, ötekileştirilmiş", "", "The project gives a voice to marginalized groups in the city.", "Proje şehirdeki ötekileştirilmiş gruplara ses veriyor."],
      ["social exclusion", "sosyal dışlanma", "", "Long term unemployment often leads to social exclusion.", "Uzun süreli işsizlik çoğu zaman sosyal dışlanmaya yol açar."],
      ["inclusion", "katılım, kapsayıcılık", "🤝", "The company has a new program to promote inclusion in the workplace.", "Şirketin işyerinde kapsayıcılığı teşvik eden yeni bir programı var."],
      ["ethnicity", "etnik köken", "", "The form asks about your age, gender and ethnicity.", "Form yaşınızı, cinsiyetinizi ve etnik kökeninizi soruyor."],
      ["sexism", "cinsiyetçilik", "", "She wrote a blog post about everyday sexism in the tech industry.", "Teknoloji sektöründeki gündelik cinsiyetçilik hakkında bir blog yazısı yazdı."],
      ["ageism", "yaş ayrımcılığı", "", "Many people over fifty experience ageism when looking for a job.", "Elli yaş üstü birçok kişi iş ararken yaş ayrımcılığıyla karşılaşıyor."],
      ["gender equality", "toplumsal cinsiyet eşitliği", "⚖️", "Gender equality starts with how we raise our children at home.", "Toplumsal cinsiyet eşitliği evde çocuklarımızı nasıl yetiştirdiğimizle başlar."],
      ["gender roles", "toplumsal cinsiyet rolleri", "", "Traditional gender roles are changing fast in big cities.", "Geleneksel toplumsal cinsiyet rolleri büyük şehirlerde hızla değişiyor."],
      ["patriarchy", "ataerkillik", "", "The book explores how patriarchy shaped family life in the village.", "Kitap ataerkilliğin köydeki aile hayatını nasıl şekillendirdiğini inceliyor."],
      ["feminism", "feminizm", "", "Her grandmother's stories were her first lesson in feminism.", "Büyükannesinin hikâyeleri onun feminizmdeki ilk dersiydi."],
      ["stigma", "damga, toplumsal leke", "", "There is still a stigma attached to asking for help with mental health.", "Ruh sağlığı için yardım istemeye hâlâ bir damga yapıştırılıyor."],
      ["stigmatize", "damgalamak", "", "We should not stigmatize people who have been in prison.", "Cezaevinde bulunmuş insanları damgalamamalıyız."],
      ["conformity", "uyum, toplumsal uyumculuk", "", "Teenagers often feel strong pressure towards conformity at school.", "Ergenler okulda çoğu zaman uyum sağlama yönünde güçlü bir baskı hisseder."],
      ["conform", "uymak, ayak uydurmak", "", "He refused to conform to his family's expectations and became an artist.", "Ailesinin beklentilerine uymayı reddetti ve sanatçı oldu."],
      ["peer pressure", "akran baskısı", "", "Many young people start smoking because of peer pressure.", "Pek çok genç akran baskısı yüzünden sigaraya başlıyor."],
      ["socialization", "sosyalleşme", "", "School plays a huge role in the socialization of children.", "Okul çocukların sosyalleşmesinde çok büyük bir rol oynar."],
      ["nuclear family", "çekirdek aile", "👨‍👩‍👧", "The nuclear family is now the most common household type here.", "Çekirdek aile artık burada en yaygın hane tipi."],
      ["extended family", "geniş aile", "", "We spend every holiday with our extended family in the village.", "Her bayramı köyde geniş ailemizle geçiriyoruz."],
      ["single parent", "yalnız ebeveyn", "", "Being a single parent with two jobs is incredibly tiring.", "İki işte çalışan yalnız bir ebeveyn olmak inanılmaz yorucu."],
      ["household", "hane, ev halkı", "🏠", "The average household now spends a third of its income on rent.", "Ortalama bir hane artık gelirinin üçte birini kiraya harcıyor."],
      ["breadwinner", "evin geçimini sağlayan kişi", "", "In many families today, the mother is the main breadwinner.", "Günümüzde birçok ailede evin asıl geçimini anne sağlıyor."],
      ["homemaker", "ev hanımı veya ev erkeği", "", "My father became a homemaker when my mother got promoted.", "Annem terfi alınca babam evle ilgilenmeye başladı."],
      ["kinship", "akrabalık", "", "In small villages, kinship ties are still extremely important.", "Küçük köylerde akrabalık bağları hâlâ son derece önemli."],
      ["ancestry", "soy, ata", "🧬", "DNA tests have made people curious about their ancestry.", "DNA testleri insanları soylarını merak eder hâle getirdi."],
      ["rite of passage", "geçiş ritüeli", "", "Getting a driving licence is a rite of passage for many teenagers.", "Ehliyet almak birçok genç için bir geçiş ritüelidir."],
      ["belief system", "inanç sistemi", "", "Every culture has its own belief system about life and death.", "Her kültürün yaşam ve ölüm hakkında kendi inanç sistemi vardır."],
      ["secular", "laik, dünyevi", "", "The country has a secular constitution but a religious population.", "Ülkenin laik bir anayasası ama dindar bir nüfusu var."],
      ["consumerism", "tüketim kültürü", "🛍️", "Black Friday is a perfect example of modern consumerism.", "Kara Cuma modern tüketim kültürünün mükemmel bir örneğidir."],
      ["materialism", "maddiyatçılık", "", "He moved to the countryside to escape the materialism of city life.", "Şehir hayatının maddiyatçılığından kaçmak için kırsala taşındı."],
      ["individualism", "bireycilik", "", "Western cultures are often said to value individualism.", "Batı kültürlerinin bireyciliğe değer verdiği sıkça söylenir."],
      ["collectivism", "toplulukçuluk, kolektivizm", "", "In cultures that value collectivism, family decisions come first.", "Toplulukçuluğa değer veren kültürlerde ailenin kararları önce gelir."],
      ["solidarity", "dayanışma", "✊", "After the earthquake, the solidarity between neighbors was amazing.", "Depremden sonra komşular arasındaki dayanışma muhteşemdi."],
      ["social cohesion", "toplumsal uyum, birlik", "", "Shared public spaces help build social cohesion in a neighborhood.", "Ortak kamusal alanlar bir mahallede toplumsal birlik oluşturmaya yardımcı olur."],
      ["urbanization", "kentleşme", "🏙️", "Rapid urbanization has created huge traffic problems in our city.", "Hızlı kentleşme şehrimizde büyük trafik sorunlarına yol açtı."],
      ["slum", "gecekondu bölgesi, varoş", "", "Nearly a million people live in the slum on the edge of the city.", "Şehrin kenarındaki gecekondu bölgesinde yaklaşık bir milyon kişi yaşıyor."],
      ["homelessness", "evsizlik", "", "Homelessness has increased since rents started rising so fast.", "Kiralar bu kadar hızlı artmaya başladığından beri evsizlik arttı."],
      ["wealth gap", "servet uçurumu", "", "The wealth gap between the richest and poorest keeps getting wider.", "En zenginler ile en yoksullar arasındaki servet uçurumu giderek açılıyor."],
      ["affluent", "varlıklı, zengin", "", "Affluent families can pay for private tutors and extra classes.", "Varlıklı aileler özel öğretmenlere ve ek derslere para verebilir."],
      ["deprived", "yoksun, mahrum", "", "The new clinic will serve one of the most deprived areas of the city.", "Yeni klinik şehrin en yoksun bölgelerinden birine hizmet verecek."],
      ["deprivation", "yoksunluk", "", "Sleep deprivation can affect your mood and your memory.", "Uykusuzluk ruh halini ve hafızanı etkileyebilir."],
      ["disadvantaged", "dezavantajlı", "", "The scholarship is for students from disadvantaged backgrounds.", "Burs dezavantajlı geçmişe sahip öğrenciler içindir."],
      ["social security", "sosyal güvenlik", "", "Part of your salary goes to social security every month.", "Maaşının bir kısmı her ay sosyal güvenliğe gidiyor."],
      ["life expectancy", "ortalama yaşam süresi", "", "Life expectancy has risen by ten years over the last half century.", "Ortalama yaşam süresi son yarım yüzyılda on yıl arttı."],
      ["birth rate", "doğum oranı", "👶", "The birth rate has fallen sharply in most European countries.", "Doğum oranı çoğu Avrupa ülkesinde keskin şekilde düştü."],
      ["aging population", "yaşlanan nüfus", "", "An aging population means more pressure on health services.", "Yaşlanan nüfus sağlık hizmetleri üzerinde daha fazla baskı demek."],
      ["demographic", "demografik, nüfus grubu", "", "Advertisers really want to reach the eighteen to thirty demographic.", "Reklamcılar özellikle on sekiz ile otuz yaş arası nüfus grubuna ulaşmak istiyor."],
      ["census", "nüfus sayımı", "📊", "According to the last census, the city has grown by twenty percent.", "Son nüfus sayımına göre şehir yüzde yirmi büyüdü."],
      ["migrant", "göçmen", "", "Migrant workers often do the hardest jobs for the lowest pay.", "Göçmen işçiler çoğu zaman en zor işleri en düşük ücretle yapar."],
      ["emigrant", "başka ülkeye göç eden kişi", "", "As an emigrant, she sends money home to her parents every month.", "Yurt dışına göç etmiş biri olarak her ay ailesine para gönderiyor."],
      ["assimilation", "asimilasyon", "", "Some immigrants fear that assimilation means losing their own language.", "Bazı göçmenler asimilasyonun kendi dillerini kaybetmek anlamına geldiğinden korkuyor."],
      ["assimilate", "asimile olmak, kaynaşmak", "", "Children usually assimilate into a new culture faster than adults.", "Çocuklar yeni bir kültüre genellikle yetişkinlerden daha hızlı uyum sağlar."],
      ["multiculturalism", "çokkültürlülük", "", "The city's food scene is a great example of multiculturalism.", "Şehrin yemek kültürü çokkültürlülüğün harika bir örneğidir."],
      ["tolerant", "hoşgörülü", "", "Young people today are generally more tolerant than older generations.", "Bugünün gençleri genel olarak eski kuşaklardan daha hoşgörülü."],
      ["coexist", "bir arada yaşamak", "", "Different religions have managed to coexist in this town for centuries.", "Farklı dinler bu kasabada yüzyıllardır bir arada yaşamayı başardı."],
      ["civic", "kentsel, yurttaşlıkla ilgili", "", "Voting in local elections is an important civic responsibility.", "Yerel seçimlerde oy kullanmak önemli bir yurttaşlık sorumluluğudur."],
      ["civic duty", "yurttaşlık görevi", "", "Many people see paying taxes as a civic duty.", "Birçok kişi vergi ödemeyi bir yurttaşlık görevi olarak görüyor."],
      ["nonprofit", "kâr amacı gütmeyen", "", "She left her bank job to work for a small nonprofit.", "Bankadaki işini bırakıp küçük, kâr amacı gütmeyen bir kuruluşta çalışmaya başladı."],
      ["activism", "aktivizm", "📣", "Online activism can spread a message to millions in a few hours.", "İnternet aktivizmi bir mesajı birkaç saat içinde milyonlara yayabilir."],
      ["advocacy", "savunuculuk", "", "The group does advocacy work for people with disabilities.", "Grup engelli bireyler için savunuculuk çalışması yapıyor."],
      ["advocate", "savunmak, savunucu", "", "Doctors advocate more exercise and less screen time for children.", "Doktorlar çocuklar için daha fazla egzersiz ve daha az ekran süresini savunuyor."],
      ["social norm", "toplumsal norm", "", "Shaking hands is a social norm in business meetings here.", "Burada iş toplantılarında tokalaşmak bir toplumsal normdur."],
      ["deviance", "sapkınlık, normdan sapma", "", "What counts as deviance changes from one society to another.", "Neyin normdan sapma sayıldığı bir toplumdan diğerine değişir."],
      ["peer", "akran", "", "Teenagers care a lot about what each peer in their class thinks.", "Ergenler sınıflarındaki akranlarının ne düşündüğünü çok önemser."],
      ["subculture", "alt kültür", "", "Skateboarding started as a small subculture in California.", "Kaykay Kaliforniya'da küçük bir alt kültür olarak başladı."],
      ["counterculture", "karşı kültür", "", "The counterculture of the sixties rejected war and consumerism.", "Altmışların karşı kültürü savaşı ve tüketim kültürünü reddetti."],
      ["status symbol", "statü sembolü", "⌚", "For many people, an expensive watch is a status symbol.", "Birçok kişi için pahalı bir saat bir statü sembolüdür."],
      ["prestige", "prestij, saygınlık", "", "Doctors and judges enjoy a lot of prestige in our society.", "Doktorlar ve hâkimler toplumumuzda büyük saygınlığa sahip."],
      ["caste", "kast", "", "The caste system once decided what job a person could do.", "Kast sistemi bir zamanlar bir kişinin hangi işi yapabileceğini belirlerdi."],
      ["social ladder", "toplumsal merdiven", "🪜", "Education helped her climb the social ladder quickly.", "Eğitim toplumsal merdiveni hızla tırmanmasına yardım etti."],
      ["meritocracy", "liyakat sistemi", "", "In a true meritocracy, talent matters more than family connections.", "Gerçek bir liyakat sisteminde yetenek aile bağlantılarından daha önemlidir."],
      ["literacy", "okuryazarlık", "📖", "The literacy rate in the region has risen to ninety percent.", "Bölgedeki okuryazarlık oranı yüzde doksana yükseldi."],
      ["illiteracy", "okuma yazma bilmeme", "", "Illiteracy is still a serious problem among older women in rural areas.", "Okuma yazma bilmemek kırsal bölgelerdeki yaşlı kadınlar arasında hâlâ ciddi bir sorun."],
      ["juvenile", "çocuk, reşit olmayan", "", "The juvenile court deals only with offenders under eighteen.", "Çocuk mahkemesi yalnızca on sekiz yaşından küçük suçlulara bakar."],
      ["delinquency", "suça yönelme, suçluluk", "", "Sports clubs can help reduce delinquency among teenagers.", "Spor kulüpleri ergenler arasında suça yönelmeyi azaltmaya yardımcı olabilir."],
      ["crime rate", "suç oranı", "", "The crime rate dropped after the new street lights were installed.", "Yeni sokak lambaları takıldıktan sonra suç oranı düştü."],
      ["alienation", "yabancılaşma", "", "Working from home all year gave him a feeling of alienation.", "Bütün yıl evden çalışmak onda bir yabancılaşma duygusu yarattı."],
      ["sense of belonging", "aidiyet duygusu", "", "Joining the choir gave her a strong sense of belonging.", "Koroya katılmak ona güçlü bir aidiyet duygusu verdi."],
      ["social worker", "sosyal hizmet uzmanı", "", "A social worker visits the family every two weeks.", "Bir sosyal hizmet uzmanı aileyi iki haftada bir ziyaret ediyor."],
      ["inequity", "adaletsizlik, hakkaniyetsizlik", "", "The report highlights the inequity in how schools are funded.", "Rapor okulların finansmanındaki adaletsizliğe dikkat çekiyor."],
      ["underclass", "en alt sınıf", "", "Some writers warn about a growing underclass without stable jobs.", "Bazı yazarlar düzenli işi olmayan, büyüyen bir alt sınıf konusunda uyarıyor."],
      ["food bank", "gıda bankası", "🥫", "More families than ever are relying on the local food bank.", "Her zamankinden fazla aile yerel gıda bankasına muhtaç."],
      ["outcast", "dışlanmış kişi", "", "At his new school, he felt like an outcast for months.", "Yeni okulunda aylarca kendini dışlanmış biri gibi hissetti."],
      ["generation gap", "kuşak çatışması", "", "Music is often where you notice the generation gap most clearly.", "Kuşak çatışmasını en net fark ettiğin yer çoğu zaman müziktir."],
      ["millennial", "Y kuşağı mensubu", "", "As a millennial, I have changed jobs four times in eight years.", "Y kuşağından biri olarak sekiz yılda dört kez iş değiştirdim."],
      ["sociology", "sosyoloji", "", "She studied sociology because she wanted to understand how society works.", "Toplumun nasıl işlediğini anlamak istediği için sosyoloji okudu."],
      ["poverty line", "yoksulluk sınırı", "", "Nearly one in five families live below the poverty line.", "Neredeyse her beş aileden biri yoksulluk sınırının altında yaşıyor."],
      ["living wage", "insanca yaşanacak ücret", "", "Workers are demanding a living wage that covers rent and food.", "İşçiler kirayı ve gıdayı karşılayacak insanca bir ücret talep ediyor."],
      ["gender gap", "cinsiyet uçurumu", "", "The gender gap in science careers is slowly getting smaller.", "Bilim kariyerlerindeki cinsiyet uçurumu yavaş yavaş kapanıyor."],
      ["glass ceiling", "cam tavan", "", "She was the first woman to break the glass ceiling at the bank.", "Bankada cam tavanı kıran ilk kadın oldu."],
      ["role model", "rol model, örnek alınan kişi", "🌟", "My older sister has always been my role model.", "Ablam her zaman benim rol modelim oldu."],
      ["social circle", "sosyal çevre", "", "After moving abroad, it took me a year to build a social circle.", "Yurt dışına taşındıktan sonra bir sosyal çevre oluşturmam bir yıl sürdü."],
      ["community center", "toplum merkezi, mahalle evi", "", "The community center offers free language classes every evening.", "Mahalle evi her akşam ücretsiz dil kursları veriyor."],
      ["divorce rate", "boşanma oranı", "", "The divorce rate has doubled in the past twenty years.", "Boşanma oranı son yirmi yılda iki katına çıktı."],
      ["foster care", "koruyucu aile bakımı", "", "He spent most of his childhood in foster care.", "Çocukluğunun büyük bölümünü koruyucu aile yanında geçirdi."],
      ["nursing home", "huzurevi", "", "My grandmother moved into a nursing home near our house.", "Büyükannem evimizin yakınındaki bir huzurevine taşındı."],
      ["caregiver", "bakım veren kişi, bakıcı", "", "Being the main caregiver for a sick parent can be exhausting.", "Hasta bir ebeveynin asıl bakımını üstlenmek çok yorucu olabilir."],
      ["segregation", "ayrımcılık, ayrıştırma", "", "School segregation by income is a hidden problem in many cities.", "Gelire göre okul ayrıştırması birçok şehirde gizli bir sorun."],
      ["xenophobia", "yabancı düşmanlığı", "", "The campaign aims to fight xenophobia through shared cooking events.", "Kampanya ortak yemek etkinlikleriyle yabancı düşmanlığıyla mücadele etmeyi amaçlıyor."],
      ["empower", "güçlendirmek, yetki vermek", "💪", "Microloans can empower women to start their own small businesses.", "Küçük krediler kadınları kendi küçük işlerini kurmaları için güçlendirebilir."],
      ["equal opportunity", "fırsat eşitliği", "", "We are an equal opportunity employer and welcome all applicants.", "Fırsat eşitliğine önem veren bir işvereniz ve tüm adaylara kapımız açık."],
      ["philanthropy", "hayırseverlik", "", "She spent the last years of her life devoted to philanthropy.", "Hayatının son yıllarını hayırseverliğe adadı."],
      ["herd mentality", "sürü psikolojisi", "🐑", "Herd mentality explains why everyone suddenly buys the same product.", "Sürü psikolojisi herkesin neden birden aynı ürünü satın aldığını açıklıyor."],
      ["status quo", "mevcut durum, statüko", "", "People who benefit from the status quo rarely want change.", "Mevcut düzenden fayda sağlayanlar nadiren değişim ister."]
    ] }
);
