(window.LIBRARY = window.LIBRARY || []).push(
  { id: "lib6a", title: "Medya, Gazetecilik ve İletişim", icon: "📰", cefr: "B2", desc: "Haber dünyasını, medya okuryazarlığını ve etkili iletişimi anlatan kelimeler.",
    words: [
      ["broadcaster", "yayıncı kuruluş", "📡", "The national broadcaster will show the debate live tonight.", "Ulusal yayıncı kuruluş tartışmayı bu akşam canlı yayınlayacak."],
      ["press office", "basın bürosu", "🏢", "Please send all questions about the event to our press office.", "Etkinlikle ilgili tüm sorularınızı basın büromuza gönderin."],
      ["correspondent", "muhabir, haberci", "🎙️", "Our correspondent in Berlin has the latest details for us.", "Berlin muhabirimiz bize en son ayrıntıları aktarıyor."],
      ["columnist", "köşe yazarı", "✍️", "She has been a columnist for the Sunday paper for ten years.", "On yıldır pazar gazetesinde köşe yazarlığı yapıyor."],
      ["circulation", "tiraj", "🗞️", "The magazine's circulation has dropped sharply since last year.", "Derginin tirajı geçen yıldan beri sert biçimde düştü."],
      ["citizen journalism", "yurttaş gazeteciliği", "📱", "Citizen journalism grew quickly once everyone had a camera in their pocket.", "Herkesin cebinde bir kamera olunca yurttaş gazeteciliği hızla büyüdü."],
      ["phone-in", "telefonla katılımlı program", "📻", "Listeners called the radio phone-in to complain about the traffic.", "Dinleyiciler trafikten şikâyet etmek için telefonla katılımlı radyo programını aradı."],
      ["broadsheet", "ciddi büyük boy gazete", "🗞️", "He prefers a serious broadsheet to the popular weekend papers.", "Popüler hafta sonu gazeteleri yerine ciddi bir büyük boy gazeteyi tercih ediyor."],
      ["media outlet", "medya kuruluşu", "", "Several media outlets reported the story within minutes.", "Birkaç medya kuruluşu haberi dakikalar içinde verdi."],
      ["anonymous source", "isimsiz kaynak", "🕵️", "The article relies heavily on an anonymous source inside the ministry.", "Makale büyük ölçüde bakanlık içindeki isimsiz bir kaynağa dayanıyor."],
      ["leak", "sızdırmak, sızıntı", "💧", "Someone decided to leak the documents to a local newspaper.", "Biri belgeleri yerel bir gazeteye sızdırmaya karar verdi."],
      ["whistleblower", "muhbir, usulsüzlüğü ifşa eden kişi", "📣", "The whistleblower lost her job after speaking to reporters.", "Usulsüzlüğü ifşa eden kadın, muhabirlerle konuştuktan sonra işini kaybetti."],
      ["investigative", "araştırmacı", "🔍", "Investigative journalism takes months of patient and careful work.", "Araştırmacı gazetecilik aylarca sabırlı ve dikkatli çalışma gerektirir."],
      ["misinformation", "yanlış bilgi", "⚠️", "Misinformation spreads quickly when people share posts without reading them.", "İnsanlar paylaşımları okumadan yaydığında yanlış bilgi hızla yayılır."],
      ["disinformation", "kasıtlı dezenformasyon", "🧨", "The campaign used disinformation to confuse voters before the election.", "Kampanya seçim öncesi seçmenlerin kafasını karıştırmak için kasıtlı dezenformasyon kullandı."],
      ["news cycle", "haber döngüsü", "🔄", "In today's fast news cycle, a scandal is forgotten within a week.", "Bugünün hızlı haber döngüsünde bir skandal bir hafta içinde unutuluyor."],
      ["biased", "taraflı, önyargılı", "⚖️", "Many viewers felt the interview was biased against the mayor.", "Pek çok izleyici röportajın belediye başkanına karşı taraflı olduğunu düşündü."],
      ["gatekeeper", "bilgi akışını kontrol eden kişi", "🚪", "Editors used to act as the gatekeeper of what the public could read.", "Editörler eskiden halkın neyi okuyabileceğinin bekçiliğini yapardı."],
      ["censor", "sansürlemek", "🚫", "The government tried to censor the film before its release.", "Hükümet filmi gösterime girmeden önce sansürlemeye çalıştı."],
      ["press freedom", "basın özgürlüğü", "🕊️", "Press freedom is essential for a healthy democracy.", "Basın özgürlüğü sağlıklı bir demokrasi için vazgeçilmezdir."],
      ["libel", "yazılı iftira", "", "The newspaper was sued for libel after printing false claims.", "Gazete yanlış iddialar bastıktan sonra iftira davasıyla karşılaştı."],
      ["slander", "sözlü iftira", "", "Calling him a thief in public could count as slander.", "Onu herkesin önünde hırsız diye çağırmak sözlü iftira sayılabilir."],
      ["speakerphone", "hoparlörlü telefon", "🔊", "Can I put you on speakerphone so my colleague can hear too?", "Meslektaşım da duyabilsin diye seni hoparlöre alabilir miyim?"],
      ["retraction", "düzeltme, geri çekme", "", "A short retraction appeared on page twelve the next morning.", "Ertesi sabah on ikinci sayfada kısa bir düzeltme yayımlandı."],
      ["editor-in-chief", "genel yayın yönetmeni", "👔", "The editor-in-chief decided to put the story on the front page.", "Genel yayın yönetmeni haberi ön sayfaya koymaya karar verdi."],
      ["allegedly", "iddiaya göre", "", "The manager allegedly hid the losses from the board for months.", "İddiaya göre müdür zararları aylarca yönetim kurulundan sakladı."],
      ["spokesperson", "sözcü", "🗣️", "A spokesperson for the hospital refused to comment on the case.", "Hastanenin sözcüsü dava hakkında yorum yapmayı reddetti."],
      ["news anchor", "haber sunucusu", "📺", "The news anchor calmly read the breaking story on live television.", "Haber sunucusu son dakika haberini canlı yayında sakin bir şekilde okudu."],
      ["newsroom", "haber merkezi", "🏢", "The newsroom was busy and noisy right before the deadline.", "Haber merkezi teslim saatinden hemen önce kalabalık ve gürültülüydü."],
      ["footage", "görüntü, kamera kaydı", "🎥", "Security camera footage showed the thief leaving through the back door.", "Güvenlik kamerası görüntüleri hırsızın arka kapıdan çıktığını gösterdi."],
      ["caption", "fotoğraf altyazısı", "🖼️", "The caption under the photo gave the wrong name.", "Fotoğrafın altındaki altyazı yanlış ismi veriyordu."],
      ["viewership", "izleyici sayısı", "📈", "The show's viewership doubled after the second season.", "Programın izleyici sayısı ikinci sezondan sonra iki katına çıktı."],
      ["ratings", "reyting", "📊", "The channel cancelled the series because of poor ratings.", "Kanal düşük reytingler yüzünden diziyi iptal etti."],
      ["prime time", "en çok izlenen saat dilimi", "🕗", "The final episode will air in prime time on Saturday.", "Final bölümü cumartesi günü en çok izlenen saat diliminde yayınlanacak."],
      ["advertisement", "reklam, ilan", "", "I saw an advertisement for the job in the local paper.", "İş ilanını yerel gazetede gördüm."],
      ["infographic", "bilgi grafiği", "📊", "A simple infographic explained the new tax rules better than any article.", "Basit bir bilgi grafiği yeni vergi kurallarını her makaleden daha iyi açıkladı."],
      ["echo chamber", "yankı odası", "🔁", "Social feeds can become an echo chamber where everyone agrees with you.", "Sosyal akışlar herkesin sizinle aynı fikirde olduğu bir yankı odasına dönüşebilir."],
      ["poll", "kamuoyu yoklaması", "🗳️", "A new poll shows the two candidates are almost level.", "Yeni bir kamuoyu yoklaması iki adayın neredeyse başa baş olduğunu gösteriyor."],
      ["media literacy", "medya okuryazarlığı", "🧠", "Schools should teach media literacy from an early age.", "Okullar medya okuryazarlığını erken yaşta öğretmeli."],
      ["credible", "güvenilir, inandırıcı", "✅", "We need a credible source before we publish this claim.", "Bu iddiayı yayımlamadan önce güvenilir bir kaynağa ihtiyacımız var."],
      ["verify", "doğrulamak", "✔️", "Always verify a story with a second source before sharing it.", "Bir haberi paylaşmadan önce her zaman ikinci bir kaynakla doğrula."],
      ["verification", "doğrulama", "", "The verification team checks every photo before it goes online.", "Doğrulama ekibi her fotoğrafı internete konmadan önce kontrol ediyor."],
      ["op-ed", "görüş yazısı", "📝", "The professor wrote an op-ed about rising rents in the city.", "Profesör şehirdeki artan kiralar hakkında bir görüş yazısı yazdı."],
      ["byline", "yazar adı satırı", "", "It was her first article with her own byline on it.", "Bu, üzerinde kendi imzasının olduğu ilk makalesiydi."],
      ["edition", "baskı, sayı", "", "The evening edition included an interview with the coach.", "Akşam baskısında teknik direktörle bir röportaj vardı."],
      ["newsstand", "gazete bayii", "🏪", "I still buy a paper every morning from the newsstand near the station.", "Hâlâ her sabah istasyonun yanındaki gazete bayiinden gazete alıyorum."],
      ["hoax", "asılsız haber, aldatmaca", "🎭", "The photo of a shark on the highway turned out to be a hoax.", "Otoyoldaki köpek balığı fotoğrafının bir aldatmaca olduğu ortaya çıktı."],
      ["sensational", "sansasyonel", "💥", "The tabloid used a sensational headline to sell more copies.", "Magazin gazetesi daha çok satmak için sansasyonel bir manşet kullandı."],
      ["sensationalism", "sansasyonculuk", "", "Critics accuse the channel of sensationalism and cheap drama.", "Eleştirmenler kanalı sansasyonculuk ve ucuz dramla suçluyor."],
      ["mainstream media", "ana akım medya", "📺", "Young people trust the mainstream media less than their parents do.", "Gençler ana akım medyaya ebeveynlerinden daha az güveniyor."],
      ["livestream", "canlı yayın yapmak, canlı yayın", "🔴", "The band will livestream the concert for fans around the world.", "Grup konseri dünyanın dört bir yanındaki hayranları için canlı yayınlayacak."],
      ["channel", "kanal", "📺", "Do you know which channel is showing the match tonight?", "Bu akşam maçı hangi kanalın verdiğini biliyor musun?"],
      ["wire service", "haber ajansı servisi", "", "The photo was sent around the world by a major wire service.", "Fotoğraf büyük bir haber ajansı servisi aracılığıyla dünyaya dağıtıldı."],
      ["miscommunication", "iletişim kopukluğu", "😕", "The delay was caused by a simple miscommunication between two teams.", "Gecikme iki ekip arasındaki basit bir iletişim kopukluğundan kaynaklandı."],
      ["talk show", "sohbet programı", "🛋️", "The actor talked about his childhood on a late-night talk show.", "Oyuncu gece geç saatteki bir sohbet programında çocukluğunu anlattı."],
      ["smear campaign", "karalama kampanyası", "", "The candidate says she is the victim of a smear campaign.", "Aday bir karalama kampanyasının kurbanı olduğunu söylüyor."],
      ["confirmation", "teyit, doğrulama", "", "We are still waiting for official confirmation of the results.", "Sonuçların resmi teyidini hâlâ bekliyoruz."],
      ["tip-off", "ihbar, gizli bilgi", "📞", "Police acted on a tip-off from a local shop owner.", "Polis yerel bir dükkân sahibinden gelen ihbar üzerine harekete geçti."],
      ["gag order", "yayın yasağı kararı", "🤐", "The judge issued a gag order, so reporters cannot discuss the trial.", "Hâkim yayın yasağı kararı verdi, bu yüzden muhabirler davayı konuşamıyor."],
      ["watchdog", "denetim kurumu, bekçi", "🐕", "The media watchdog received hundreds of complaints about the advert.", "Medya denetim kurumu reklam hakkında yüzlerce şikâyet aldı."],
      ["cover a story", "bir haberi takip etmek", "", "She was sent abroad to cover a story about the floods.", "Sellerle ilgili bir haberi takip etmesi için yurt dışına gönderildi."],
      ["break a story", "bir haberi ilk vermek", "⚡", "A student website was the first to break a story about the scandal.", "Skandalla ilgili haberi ilk veren bir öğrenci web sitesiydi."],
      ["eyewitness", "görgü tanığı", "👀", "One eyewitness said the car was driving far too fast.", "Bir görgü tanığı arabanın çok hızlı gittiğini söyledi."],
      ["on the record", "resmî olarak, kayıtlı", "🎙️", "The director finally agreed to speak on the record about the cuts.", "Müdür sonunda kesintiler hakkında resmî olarak konuşmayı kabul etti."],
      ["press pass", "basın kartı", "🪪", "You need a press pass to get into the stadium's media area.", "Stadyumun basın bölümüne girmek için basın kartı gerekiyor."],
      ["commentator", "yorumcu, spiker", "🎧", "The commentator could hardly believe what he was watching.", "Yorumcu izlediği şeye neredeyse inanamıyordu."],
      ["commentary", "yorum, anlatım", "", "The live commentary made the slow game much more fun.", "Canlı anlatım yavaş maçı çok daha eğlenceli hâle getirdi."],
      ["airtime", "yayın süresi", "⏱️", "Smaller parties complain that they get very little airtime.", "Küçük partiler çok az yayın süresi aldıklarından şikâyet ediyor."],
      ["on air", "yayında", "🔴", "Please switch off your phones when the red light says on air.", "Kırmızı ışık yayında olduğumuzu gösterdiğinde lütfen telefonlarınızı kapatın."],
      ["paywall", "ücretli erişim duvarı", "🔒", "I couldn't read the article because it was behind a paywall.", "Makale ücretli erişim duvarının arkasında olduğu için okuyamadım."],
      ["newsworthy", "haber değeri taşıyan", "", "Editors decide every day what is newsworthy and what is not.", "Editörler her gün neyin haber değeri taşıdığına karar verir."],
      ["obituary", "ölüm ilanı, anma yazısı", "🕯️", "The newspaper published a moving obituary of the old teacher.", "Gazete yaşlı öğretmen için dokunaklı bir anma yazısı yayımladı."],
      ["distort", "çarpıtmak", "🌀", "Short clips can easily distort what a politician really said.", "Kısa videolar bir politikacının gerçekte ne söylediğini kolayca çarpıtabilir."],
      ["newsflash", "son dakika duyurusu", "⚡", "A newsflash interrupted the film to report a strong earthquake.", "Güçlü bir depremi bildiren son dakika duyurusu filmi yarıda kesti."],
      ["fact-checker", "doğruluk kontrolcüsü", "🔎", "A fact-checker found three serious errors in the minister's speech.", "Bir doğruluk kontrolcüsü bakanın konuşmasında üç ciddi hata buldu."],
      ["conspiracy theory", "komplo teorisi", "🛸", "My uncle believes every conspiracy theory he reads on the internet.", "Amcam internette okuduğu her komplo teorisine inanıyor."],
      ["deepfake", "derin sahte video", "🤖", "The deepfake looked so real that thousands of people shared it.", "Derin sahte video o kadar gerçekçiydi ki binlerce kişi paylaştı."],
      ["media frenzy", "medya çılgınlığı", "📸", "The royal wedding caused a media frenzy across the country.", "Kraliyet düğünü ülke genelinde bir medya çılgınlığına yol açtı."],
      ["narrative", "anlatı, söylem", "", "Both sides are trying to control the narrative after the protest.", "Protestodan sonra iki taraf da anlatıyı kontrol etmeye çalışıyor."],
      ["talking points", "konuşma maddeleri", "📋", "The spokesman just repeated the same talking points again and again.", "Sözcü aynı konuşma maddelerini tekrar tekrar yineledi."],
      ["press briefing", "basın brifingi", "🎤", "The daily press briefing starts at eleven in the main hall.", "Günlük basın brifingi ana salonda saat on birde başlıyor."],
      ["jargon", "teknik dil, jargon", "", "Try to avoid legal jargon when you write for ordinary readers.", "Sıradan okurlar için yazarken hukuki jargondan kaçınmaya çalış."],
      ["public discourse", "kamusal tartışma", "🗣️", "Social media has changed the tone of public discourse in many countries.", "Sosyal medya pek çok ülkede kamusal tartışmanın üslubunu değiştirdi."],
      ["hang up", "telefonu kapatmak", "☎️", "Please don't hang up, I just need two more minutes.", "Lütfen telefonu kapatma, sadece iki dakikaya daha ihtiyacım var."],
      ["eavesdrop", "gizlice dinlemek", "👂", "I didn't mean to eavesdrop, but your conversation was quite loud.", "Gizlice dinlemek istemedim ama konuşmanız oldukça yüksek sesliydi."],
      ["megaphone", "megafon", "📢", "The organiser used a megaphone to speak to the crowd outside.", "Organizatör dışarıdaki kalabalığa seslenmek için megafon kullandı."],
      ["grapevine", "dedikodu ağı, kulaktan dolma", "🍇", "I heard through the grapevine that our manager is leaving.", "Müdürümüzün ayrılacağını kulaktan dolma duydum."],
      ["get the message across", "mesajı iletmek, derdini anlatmak", "", "The ad was short, but it managed to get the message across.", "Reklam kısaydı ama mesajı iletmeyi başardı."],
      ["reach out", "iletişime geçmek", "📲", "Feel free to reach out if you have any questions.", "Herhangi bir sorunuz olursa iletişime geçmekten çekinmeyin."],
      ["airwaves", "radyo ve televizyon yayınları", "📡", "Her new song is all over the airwaves this summer.", "Yeni şarkısı bu yaz bütün radyo ve televizyon yayınlarında çalıyor."],
      ["cartoonist", "karikatürist", "✏️", "The cartoonist drew the prime minister as a tiny nervous bird.", "Karikatürist başbakanı ufacık ve gergin bir kuş olarak çizdi."],
      ["voicemail", "sesli mesaj", "📞", "I left a voicemail, but she still hasn't called me back.", "Sesli mesaj bıraktım ama hâlâ beni geri aramadı."],
      ["correspondence", "yazışma", "✉️", "All correspondence with clients must be kept for five years.", "Müşterilerle tüm yazışmalar beş yıl boyunca saklanmalı."],
      ["broadband", "geniş bant internet", "🌐", "Many villages still don't have fast broadband connections.", "Pek çok köyde hâlâ hızlı geniş bant bağlantısı yok."],
      ["freelance", "serbest çalışan, serbest", "💻", "He works as a freelance photographer for several magazines.", "Birkaç dergi için serbest fotoğrafçı olarak çalışıyor."],
      ["freelancer", "serbest çalışan kişi", "", "As a freelancer, she chooses her own projects and hours.", "Serbest çalışan biri olarak kendi projelerini ve saatlerini seçiyor."],
      ["news agency", "haber ajansı", "🌍", "Most local papers buy their foreign news from a large news agency.", "Yerel gazetelerin çoğu dış haberlerini büyük bir haber ajansından alıyor."],
      ["mass media", "kitle iletişim araçları", "📻", "Mass media shaped public taste for most of the last century.", "Kitle iletişim araçları geçen yüzyılın büyük bölümünde halkın zevkini şekillendirdi."],
      ["interviewee", "röportaj yapılan kişi", "", "The interviewee asked to see the questions in advance.", "Röportaj yapılan kişi soruları önceden görmek istedi."],
      ["bulletin", "haber bülteni", "📻", "The radio station broadcasts a short news bulletin every hour.", "Radyo istasyonu her saat başı kısa bir haber bülteni yayınlıyor."],
      ["in-depth", "ayrıntılı, derinlemesine", "", "The magazine published an in-depth report on the housing crisis.", "Dergi konut krizi hakkında derinlemesine bir rapor yayımladı."],
      ["unbiased", "tarafsız", "", "It is hard to find truly unbiased news these days.", "Bu günlerde gerçekten tarafsız haber bulmak zor."],
      ["accuracy", "doğruluk", "🎯", "Speed matters in news, but accuracy matters even more.", "Haberde hız önemlidir ama doğruluk daha da önemlidir."],
      ["disclose", "açıklamak, ifşa etmek", "", "The company refused to disclose how much it paid the actor.", "Şirket oyuncuya ne kadar ödediğini açıklamayı reddetti."],
      ["disclosure", "açıklama, ifşa", "", "The disclosure of the emails caused a huge political storm.", "E-postaların ifşası büyük bir siyasi fırtınaya yol açtı."],
      ["public interest", "kamu yararı", "👥", "The editor argued that the story was clearly in the public interest.", "Editör haberin açıkça kamu yararına olduğunu savundu."],
      ["intrusive", "rahatsız edici, mahremiyete giren", "", "Some questions about her family felt intrusive and unfair.", "Ailesiyle ilgili bazı sorular mahremiyete giren ve haksız geldi."],
      ["go public", "kamuoyuna açıklamak", "", "The workers decided to go public with their complaints.", "İşçiler şikâyetlerini kamuoyuna açıklamaya karar verdi."],
      ["make headlines", "manşetlere çıkmak", "🗞️", "The young inventor started to make headlines all over Europe.", "Genç mucit tüm Avrupa'da manşetlere çıkmaya başladı."],
      ["hit the headlines", "gündeme oturmak", "", "The tiny town hit the headlines after the strange discovery.", "Küçük kasaba tuhaf keşiften sonra gündeme oturdu."]
    ] },
  { id: "lib6b", title: "Sanat, Edebiyat ve Sinema", icon: "🎨", cefr: "C1", desc: "Resim, edebiyat, tiyatro ve sinema üzerine incelikli konuşmak için ileri düzey kelimeler.",
    words: [
      ["sculptor", "heykeltıraş", "🗿", "The sculptor spent three years carving the figure from a single block of marble.", "Heykeltıraş figürü tek bir mermer bloğundan oymak için üç yıl harcadı."],
      ["portrait", "portre", "🖼️", "Her grandmother's portrait still hangs above the fireplace.", "Büyükannesinin portresi hâlâ şöminenin üstünde asılı duruyor."],
      ["contemporary", "çağdaş", "", "The museum focuses on contemporary artists from the Middle East.", "Müze Orta Doğulu çağdaş sanatçılara odaklanıyor."],
      ["palette", "renk paleti", "🎨", "The painter used a soft palette of greens and greys.", "Ressam yeşil ve grilerden oluşan yumuşak bir renk paleti kullandı."],
      ["mural", "duvar resmi", "🧱", "Local teenagers painted a huge mural on the side of the station.", "Yerel gençler istasyonun yan duvarına dev bir duvar resmi yaptı."],
      ["aesthetics", "estetik anlayışı", "", "The aesthetics of the film owe a lot to old Japanese prints.", "Filmin estetik anlayışı eski Japon baskılarına çok şey borçlu."],
      ["novelist", "romancı", "📖", "The novelist rarely gives interviews and prefers to stay out of the spotlight.", "Romancı nadiren röportaj veriyor ve ilgi odağından uzak durmayı tercih ediyor."],
      ["antagonist", "kötü karakter, karşı karakter", "😈", "The antagonist is more sympathetic than the hero in this story.", "Bu hikâyede karşı karakter kahramandan daha sempatik."],
      ["subplot", "yan hikâye", "", "A romantic subplot slows down the second half of the novel.", "Romantik bir yan hikâye romanın ikinci yarısını yavaşlatıyor."],
      ["plot twist", "beklenmedik olay dönüşü", "🌀", "Nobody in the cinema saw the final plot twist coming.", "Sinemadaki hiç kimse son beklenmedik dönüşü tahmin edemedi."],
      ["climax", "doruk noktası", "⛰️", "The climax of the play takes place during a violent storm.", "Oyunun doruk noktası şiddetli bir fırtına sırasında yaşanıyor."],
      ["foreshadowing", "önceden ima etme", "", "The author uses subtle foreshadowing to hint at the hero's fate.", "Yazar kahramanın kaderini sezdirmek için ince bir önceden ima tekniği kullanıyor."],
      ["simile", "benzetme", "", "Brave as a lion is a simple simile that children learn early.", "Aslan gibi cesur, çocukların erken öğrendiği basit bir benzetmedir."],
      ["imagery", "imgelem, imgeler", "", "The poem is full of dark imagery of winter and loss.", "Şiir kış ve kayba dair karanlık imgelerle dolu."],
      ["verse", "şiir dizesi, manzum", "", "The entire play is written in verse rather than prose.", "Oyunun tamamı düzyazı yerine manzum olarak yazılmış."],
      ["stanza", "kıta, bent", "", "The last stanza of the poem completely changes its meaning.", "Şiirin son kıtası anlamını tamamen değiştiriyor."],
      ["rhyme", "kafiye, uyak", "", "Modern poets often avoid rhyme and use free rhythm instead.", "Modern şairler çoğu zaman kafiyeden kaçınıp serbest ritim kullanır."],
      ["memoir", "anı kitabı", "📔", "Her memoir describes growing up in a small fishing village.", "Anı kitabı küçük bir balıkçı köyünde büyümesini anlatıyor."],
      ["autobiography", "otobiyografi", "", "In his autobiography, the actor is surprisingly honest about his failures.", "Oyuncu otobiyografisinde başarısızlıkları konusunda şaşırtıcı derecede dürüst."],
      ["prequel", "öncül film ya da kitap", "", "The prequel explains how the two brothers first became enemies.", "Öncül film iki kardeşin ilk kez nasıl düşman olduğunu açıklıyor."],
      ["screenplay", "senaryo", "📜", "She adapted the novel into a screenplay in only six weeks.", "Romanı yalnızca altı haftada senaryoya uyarladı."],
      ["screenwriter", "senarist", "", "The screenwriter added a new character who isn't in the book.", "Senarist kitapta olmayan yeni bir karakter ekledi."],
      ["cinematography", "görüntü yönetimi", "🎥", "The cinematography is breathtaking, especially in the desert scenes.", "Görüntü yönetimi özellikle çöl sahnelerinde nefes kesici."],
      ["cinematographer", "görüntü yönetmeni", "", "The cinematographer shot the whole film using natural light.", "Görüntü yönetmeni filmin tamamını doğal ışıkla çekti."],
      ["close-up", "yakın çekim", "🔎", "A long close-up of her eyes tells us everything without words.", "Gözlerine yapılan uzun bir yakın çekim bize her şeyi sözsüz anlatıyor."],
      ["casting", "oyuncu seçimi", "", "The casting was perfect, even for the smallest roles.", "Oyuncu seçimi en küçük roller için bile kusursuzdu."],
      ["leading role", "başrol", "⭐", "He landed his first leading role at the age of forty.", "İlk başrolünü kırk yaşında kaptı."],
      ["supporting role", "yardımcı rol", "", "She won an award for her supporting role as the hero's sister.", "Kahramanın kız kardeşi olarak oynadığı yardımcı rolle ödül kazandı."],
      ["cameo", "kısa konuk görünüm", "", "The director makes a brief cameo as a waiter in the café scene.", "Yönetmen kafe sahnesinde garson olarak kısa bir konuk görünüm yapıyor."],
      ["premiere", "gala gösterimi, prömiyer", "🎬", "The film's premiere was held in Istanbul last night.", "Filmin galası dün gece İstanbul'da yapıldı."],
      ["box office", "gişe", "🎟️", "The film was a surprise hit at the box office.", "Film gişede sürpriz bir başarı yakaladı."],
      ["blockbuster", "gişe rekortmeni film", "💰", "Every summer the studios release another expensive blockbuster.", "Her yaz stüdyolar pahalı bir gişe filmi daha vizyona sokuyor."],
      ["critically acclaimed", "eleştirmenlerce övülen", "🏅", "Her critically acclaimed debut novel was translated into twenty languages.", "Eleştirmenlerce övülen ilk romanı yirmi dile çevrildi."],
      ["acclaim", "beğeni, alkış", "", "The documentary won international acclaim for its honesty.", "Belgesel dürüstlüğüyle uluslararası beğeni topladı."],
      ["rave review", "övgü dolu eleştiri", "🌟", "The new musical received a rave review in the weekend paper.", "Yeni müzikal hafta sonu gazetesinde övgü dolu bir eleştiri aldı."],
      ["dubbed", "dublajlı", "🔊", "I prefer original films with subtitles to dubbed versions.", "Dublajlı versiyonlar yerine altyazılı orijinal filmleri tercih ederim."],
      ["special effects", "özel efektler", "✨", "The special effects look cheap compared with the brilliant acting.", "Özel efektler parlak oyunculuğun yanında ucuz görünüyor."],
      ["character arc", "karakter gelişimi", "📈", "The character arc of the shy accountant is the heart of the series.", "Utangaç muhasebecinin karakter gelişimi dizinin kalbini oluşturuyor."],
      ["monologue", "monolog", "🎭", "Her final monologue left the whole audience in tears.", "Son monoloğu tüm seyircileri gözyaşlarına boğdu."],
      ["playwright", "oyun yazarı", "✒️", "The young playwright based the comedy on her own family.", "Genç oyun yazarı komediyi kendi ailesine dayandırdı."],
      ["rehearsal", "prova", "", "The final rehearsal went badly, but the opening night was a triumph.", "Son prova kötü geçti ama açılış gecesi bir zaferdi."],
      ["audition", "seçmelere katılmak, seçme", "🎤", "Hundreds of actors came to audition for the role of the king.", "Yüzlerce oyuncu kral rolü için seçmelere katılmaya geldi."],
      ["understudy", "yedek oyuncu", "", "The understudy had to go on stage when the star fell ill.", "Yıldız oyuncu hastalanınca yedek oyuncu sahneye çıkmak zorunda kaldı."],
      ["encore", "bis", "👏", "The pianist came back for an encore after ten minutes of applause.", "Piyanist on dakikalık alkışın ardından bis için sahneye döndü."],
      ["intermission", "perde arası", "☕", "We bought ice cream and stretched our legs during the intermission.", "Perde arasında dondurma aldık ve biraz bacaklarımızı açtık."],
      ["matinee", "gündüz gösterimi", "🌞", "Tickets for the Sunday matinee are much cheaper.", "Pazar gündüz gösterimi biletleri çok daha ucuz."],
      ["choreographer", "koreograf", "💃", "The choreographer wanted the dancers to move like falling leaves.", "Koreograf dansçıların düşen yapraklar gibi hareket etmesini istedi."],
      ["choreography", "koreografi", "", "The choreography in the final scene is extremely complex.", "Son sahnedeki koreografi son derece karmaşık."],
      ["portray", "canlandırmak, tasvir etmek", "", "The film tries to portray the city as a character in its own right.", "Film şehri başlı başına bir karakter olarak tasvir etmeye çalışıyor."],
      ["portrayal", "canlandırma, tasvir", "", "His portrayal of a tired detective feels completely real.", "Yorgun bir dedektifi canlandırışı tamamen gerçek hissettiriyor."],
      ["evoke", "çağrıştırmak, uyandırmak", "", "The smell of old books can evoke strong childhood memories.", "Eski kitapların kokusu güçlü çocukluk anılarını uyandırabilir."],
      ["provoke", "kışkırtmak, tetiklemek", "", "The exhibition was designed to provoke debate about consumer culture.", "Sergi tüketim kültürü hakkında tartışmayı tetiklemek için tasarlandı."],
      ["craftsmanship", "ustalık, işçilik", "🛠️", "The craftsmanship of these old wooden doors is remarkable.", "Bu eski ahşap kapıların işçiliği dikkat çekici."],
      ["artisan", "zanaatkâr", "🧵", "A local artisan makes every lamp in the shop by hand.", "Dükkândaki her lambayı yerel bir zanaatkâr elle yapıyor."],
      ["calligraphy", "hat sanatı, kaligrafi", "🖋️", "She took up calligraphy to calm her mind after work.", "İşten sonra zihnini sakinleştirmek için hat sanatına başladı."],
      ["engraving", "gravür, oyma", "", "The old engraving shows the harbour as it looked in 1850.", "Eski gravür limanı 1850'deki hâliyle gösteriyor."],
      ["etching", "asitle yapılan baskı resim", "", "This small etching sold for more than a large oil painting.", "Bu küçük asitli baskı resim büyük bir yağlı boya tablodan daha pahalıya satıldı."],
      ["watercolour", "suluboya", "💧", "He paints a quick watercolour of every city he visits.", "Ziyaret ettiği her şehrin hızlıca bir suluboyasını yapıyor."],
      ["oil painting", "yağlı boya tablo", "🖌️", "An oil painting can take weeks to dry completely.", "Yağlı boya bir tablonun tamamen kuruması haftalar sürebilir."],
      ["fresco", "fresk", "⛪", "The fresco on the chapel ceiling was damaged by water.", "Şapel tavanındaki fresk sudan zarar gördü."],
      ["literary", "edebî", "📚", "The magazine publishes literary essays and short fiction.", "Dergi edebî denemeler ve kısa kurmaca yayımlıyor."],
      ["bestseller", "çok satan kitap", "🔥", "Her first novel, written in a tiny kitchen, became an unexpected bestseller.", "Küçücük bir mutfakta yazdığı ilk romanı beklenmedik bir çok satan kitap oldu."],
      ["publisher", "yayıncı, yayınevi", "🏛️", "Twelve publishers rejected the book before one finally accepted it.", "Kitabı sonunda biri kabul edene kadar on iki yayınevi reddetti."],
      ["literary agent", "edebî ajans, yazar menajeri", "🤝", "A good literary agent helps writers find the right publisher.", "İyi bir yazar menajeri yazarların doğru yayınevini bulmasına yardım eder."],
      ["royalties", "telif ücreti", "💵", "The author still earns royalties from a book she wrote decades ago.", "Yazar on yıllar önce yazdığı bir kitaptan hâlâ telif ücreti kazanıyor."],
      ["pen name", "takma ad, mahlas", "🎭", "She published her crime novels under a male pen name.", "Polisiye romanlarını erkek bir takma adla yayımladı."],
      ["ghostwriter", "hayalet yazar", "👻", "Many celebrity memoirs are actually written by a ghostwriter.", "Pek çok ünlü anı kitabı aslında bir hayalet yazar tarafından yazılıyor."],
      ["nuance", "ince ayrım, nüans", "", "Translation is difficult because every language has its own nuance.", "Çeviri zordur çünkü her dilin kendine özgü nüansları vardır."],
      ["motif", "motif, tekrar eden öğe", "", "Water is a recurring motif in all of her films.", "Su onun bütün filmlerinde tekrar eden bir motif."],
      ["canon", "edebî kanon, temel eserler", "", "Should modern graphic novels be part of the literary canon?", "Modern çizgi romanlar edebî kanonun bir parçası olmalı mı?"],
      ["unputdownable", "elden bırakılamayan", "📖", "I found the thriller completely unputdownable and finished it by dawn.", "Gerilim romanını hiç elimden bırakamadım ve şafakta bitirdim."],
      ["originality", "özgünlük", "💡", "Judges were impressed by the originality of her short film.", "Jüri kısa filminin özgünlüğünden etkilendi."],
      ["unconventional", "alışılmadık, sıra dışı", "", "The director chose an unconventional ending that divided the audience.", "Yönetmen seyirciyi ikiye bölen sıra dışı bir son seçti."],
      ["lyrical", "lirik, şiirsel", "", "His prose is so lyrical that it almost reads like poetry.", "Düzyazısı o kadar şiirsel ki neredeyse şiir gibi okunuyor."],
      ["haunting", "akıldan çıkmayan, ürpertici", "", "The film ends with a haunting image of an empty swing.", "Film boş bir salıncağın akıldan çıkmayan görüntüsüyle bitiyor."],
      ["melodrama", "melodram", "😭", "The series slowly turned from a clever drama into pure melodrama.", "Dizi yavaş yavaş zekice bir dramdan saf bir melodrama dönüştü."],
      ["sonnet", "sone", "", "Students had to write a sonnet about something they had lost.", "Öğrenciler kaybettikleri bir şey hakkında sone yazmak zorundaydı."],
      ["fable", "fabl", "🦊", "The old fable teaches that slow and steady wins the race.", "Eski fabl yavaş ama istikrarlı olanın yarışı kazandığını öğretir."],
      ["parable", "kıssa, ders veren hikâye", "", "The novel works as a modern parable about greed.", "Roman açgözlülük hakkında modern bir kıssa gibi işliyor."],
      ["novella", "uzun öykü, kısa roman", "", "The novella is barely a hundred pages but feels like an epic.", "Kısa roman ancak yüz sayfa ama bir destan gibi hissettiriyor."],
      ["flashback", "geriye dönüş sahnesi", "⏪", "A long flashback reveals what really happened on the night of the fire.", "Uzun bir geriye dönüş sahnesi yangın gecesi gerçekte ne olduğunu ortaya koyuyor."],
      ["cliffhanger", "merakta bırakan son", "🧗", "The season ended on a cliffhanger, so now we have to wait a year.", "Sezon merakta bırakan bir sonla bitti, şimdi bir yıl beklemek zorundayız."],
      ["subtext", "alt metin", "", "The subtext of the conversation is far more important than the words.", "Konuşmanın alt metni sözlerden çok daha önemli."],
      ["connotation", "yan anlam, çağrışım", "", "The word cheap often has a negative connotation in English.", "Cheap kelimesinin İngilizcede çoğu zaman olumsuz bir yan anlamı vardır."],
      ["allusion", "gönderme, ima", "", "The title is an allusion to an ancient Greek myth.", "Başlık eski bir Yunan mitine gönderme yapıyor."],
      ["pastiche", "taklit eser, pastiş", "", "The film is a playful pastiche of old detective movies.", "Film eski dedektif filmlerinin eğlenceli bir pastişi."],
      ["homage", "saygı duruşu, ithaf", "🙇", "The opening scene is a clear homage to the director's favourite silent film.", "Açılış sahnesi yönetmenin en sevdiği sessiz filme açık bir saygı duruşu."],
      ["tribute", "anma, saygı", "", "The concert was a tribute to the composer who died last spring.", "Konser geçen bahar ölen besteciyi anmak için düzenlendi."],
      ["parody", "parodi", "🤡", "The sketch is a clever parody of reality cooking shows.", "Skeç realite yemek programlarının zekice bir parodisi."],
      ["caricature", "karikatür", "", "The villain is so exaggerated that he becomes a caricature.", "Kötü karakter o kadar abartılı ki bir karikatüre dönüşüyor."],
      ["visionary", "vizyoner", "🔭", "The architect was a visionary who designed buildings far ahead of her time.", "Mimar, çağının çok ötesinde binalar tasarlayan vizyoner biriydi."],
      ["prolific", "üretken", "", "The prolific writer published at least one novel every year.", "Üretken yazar her yıl en az bir roman yayımladı."],
      ["renowned", "ünlü, tanınmış", "", "The festival invites renowned directors from all over the world.", "Festival dünyanın her yerinden tanınmış yönetmenleri davet ediyor."],
      ["art house", "sanat filmi", "", "This little cinema shows art house films that big chains ignore.", "Bu küçük sinema büyük zincirlerin görmezden geldiği sanat filmlerini gösteriyor."],
      ["indie film", "bağımsız film", "", "The indie film was shot in just eighteen days with a tiny budget.", "Bağımsız film çok küçük bir bütçeyle yalnızca on sekiz günde çekildi."],
      ["auteur", "kendine özgü üslubu olan yönetmen", "", "Critics treat him as an auteur whose films all share one vision.", "Eleştirmenler onu filmlerinin hepsi tek bir vizyonu paylaşan bir auteur olarak görüyor."],
      ["film festival", "film festivali", "🎞️", "Her short film was selected for a major film festival.", "Kısa filmi büyük bir film festivaline seçildi."],
      ["red carpet", "kırmızı halı", "", "Photographers lined the red carpet hours before the stars arrived.", "Fotoğrafçılar yıldızlar gelmeden saatler önce kırmızı halı boyunca dizildi."],
      ["screening", "gösterim", "📽️", "There will be a free screening of the documentary at the library.", "Kütüphanede belgeselin ücretsiz bir gösterimi olacak."],
      ["sneak preview", "ön gösterim", "👀", "Members got a sneak preview of the new exhibition last night.", "Üyeler dün gece yeni serginin ön gösterimini gördü."],
      ["director's cut", "yönetmenin kurgusu", "✂️", "The director's cut is forty minutes longer and much darker.", "Yönetmenin kurgusu kırk dakika daha uzun ve çok daha karanlık."],
      ["montage", "montaj sekansı", "", "A quick montage shows the boxer training through the winter.", "Hızlı bir montaj sekansı boksörün kış boyunca antrenman yaptığını gösteriyor."],
      ["voice-over", "dış ses", "🎙️", "The story is told through a calm voice-over by the older daughter.", "Hikâye büyük kızın sakin dış sesiyle anlatılıyor."],
      ["narrate", "anlatmak, seslendirmek", "", "A famous actor agreed to narrate the nature documentary.", "Ünlü bir oyuncu doğa belgeselini seslendirmeyi kabul etti."],
      ["depiction", "tasvir, betimleme", "", "The novel's depiction of village life is warm but never romantic.", "Romanın köy hayatı betimlemesi sıcak ama asla romantik değil."],
      ["rendition", "yorum, icra", "", "Her rendition of the old folk song gave everyone goosebumps.", "Eski halk şarkısını yorumlayışı herkesin tüylerini diken diken etti."],
      ["patron", "hami, sanat destekçisi", "", "A wealthy patron paid for the young painter to study in Paris.", "Varlıklı bir hami genç ressamın Paris'te eğitim almasının parasını ödedi."],
      ["auction", "müzayede", "🔨", "The painting sold at auction for twice the expected price.", "Tablo müzayedede beklenen fiyatın iki katına satıldı."],
      ["forgery", "sahte eser", "🕵️", "Experts discovered that the famous drawing was a clever forgery.", "Uzmanlar ünlü çizimin ustaca yapılmış bir sahte eser olduğunu keşfetti."],
      ["restoration", "restorasyon", "🧰", "The restoration of the old theatre took almost ten years.", "Eski tiyatronun restorasyonu yaklaşık on yıl sürdü."]
    ] },
  { id: "lib6c", title: "Müzik, Spor ve Eğlence", icon: "🎵", cefr: "B2", desc: "Konserlerden maçlara, boş zaman etkinliklerinden taraftar diline kadar eğlence dünyasının kelimeleri.",
    words: [
      ["melody", "melodi", "🎶", "I can remember the melody, but I've forgotten all the words.", "Melodiyi hatırlıyorum ama sözlerin hepsini unuttum."],
      ["harmony", "armoni, uyum", "", "The two sisters sing in perfect harmony on the last track.", "İki kız kardeş son parçada kusursuz bir armoniyle şarkı söylüyor."],
      ["rhythm", "ritim", "🥁", "Just follow the rhythm of the drums and you'll be fine.", "Sadece davulların ritmini takip et, sorun olmaz."],
      ["lyrics", "şarkı sözleri", "📝", "The lyrics of this song are much sadder than the music suggests.", "Bu şarkının sözleri müziğin düşündürdüğünden çok daha hüzünlü."],
      ["chorus", "nakarat", "🎤", "Everyone in the stadium sang the chorus together.", "Stadyumdaki herkes nakaratı hep birlikte söyledi."],
      ["tempo", "tempo", "", "The band suddenly increased the tempo and the crowd went wild.", "Grup aniden tempoyu artırdı ve kalabalık çılgına döndü."],
      ["beat", "ritim, vuruş", "", "This song has a great beat for running in the morning.", "Bu şarkının sabah koşusu için harika bir ritmi var."],
      ["tune", "ezgi, nağme", "", "He was whistling a cheerful tune while he cooked dinner.", "Akşam yemeğini pişirirken neşeli bir ezgi ıslıkla çalıyordu."],
      ["out of tune", "akortsuz, falsolu", "🙉", "The old piano in the hall is badly out of tune.", "Salondaki eski piyano fena hâlde akortsuz."],
      ["chord", "akor", "🎸", "I only know four chord shapes, but that's enough for most pop songs.", "Yalnızca dört akor biliyorum ama çoğu pop şarkısı için bu yeterli."],
      ["percussion", "vurmalı çalgılar", "🪘", "The percussion section added a Latin feel to the whole show.", "Vurmalı çalgılar bölümü bütün gösteriye Latin havası kattı."],
      ["drummer", "davulcu", "🥁", "The drummer broke a stick in the middle of the solo.", "Davulcu solonun ortasında bir baget kırdı."],
      ["guitarist", "gitarist", "🎸", "Their new guitarist used to play in a jazz trio.", "Yeni gitaristleri eskiden bir caz üçlüsünde çalıyordu."],
      ["vocalist", "vokalist, şarkıcı", "", "The band is looking for a vocalist with a strong, deep voice.", "Grup güçlü ve tok sesli bir vokalist arıyor."],
      ["lead singer", "solist", "🎙️", "The lead singer jumped into the crowd during the last song.", "Solist son şarkı sırasında kalabalığın içine atladı."],
      ["backing vocals", "arka vokal", "", "My cousin sings backing vocals for a well-known pop star.", "Kuzenim tanınmış bir pop yıldızı için arka vokal yapıyor."],
      ["orchestra", "orkestra", "🎻", "The city orchestra performs free concerts in the park every July.", "Şehir orkestrası her temmuzda parkta ücretsiz konserler veriyor."],
      ["conductor", "orkestra şefi", "🎼", "The conductor raised his hands and the hall went completely silent.", "Şef ellerini kaldırdı ve salon tamamen sessizleşti."],
      ["composer", "besteci", "", "The composer wrote the whole film score in just three weeks.", "Besteci bütün film müziğini yalnızca üç haftada yazdı."],
      ["compose", "bestelemek", "🎹", "She likes to compose music late at night when the house is quiet.", "Ev sessizken gece geç saatlerde müzik bestelemeyi seviyor."],
      ["symphony", "senfoni", "", "We listened to a symphony by candlelight in an old church.", "Eski bir kilisede mum ışığında bir senfoni dinledik."],
      ["album", "albüm", "💿", "Their second album sounds very different from the first one.", "İkinci albümleri ilkinden çok farklı geliyor."],
      ["record label", "plak şirketi", "🏷️", "A small record label signed the band after hearing one demo.", "Küçük bir plak şirketi tek bir demo dinledikten sonra grupla anlaştı."],
      ["cover version", "cover, yeniden yorum", "", "Her slow cover version is more popular than the original song.", "Onun yavaş cover versiyonu orijinal şarkıdan daha popüler."],
      ["remix", "remiks", "🎧", "A DJ made a dance remix of the old love song.", "Bir DJ eski aşk şarkısının dans remiksini yaptı."],
      ["playlist", "çalma listesi", "📱", "I made a playlist of calm songs for studying.", "Ders çalışmak için sakin şarkılardan bir çalma listesi hazırladım."],
      ["streaming", "dijital yayın, dinleme platformu", "🎧", "Most artists earn very little money from streaming services.", "Çoğu sanatçı dijital dinleme platformlarından çok az para kazanıyor."],
      ["venue", "mekân, etkinlik yeri", "🏟️", "The venue was too small for such a popular band.", "Mekân bu kadar popüler bir grup için fazla küçüktü."],
      ["on tour", "turnede", "🚌", "The band has been on tour in Europe since March.", "Grup martan beri Avrupa'da turnede."],
      ["sold out", "biletleri tükenmiş", "🎫", "Both concerts were sold out within twenty minutes.", "İki konserin biletleri de yirmi dakikada tükendi."],
      ["headliner", "festivalin ana sanatçısı", "⭐", "This year's headliner will play on the main stage on Saturday.", "Bu yılın ana sanatçısı cumartesi günü ana sahnede çalacak."],
      ["fan base", "hayran kitlesi", "❤️", "The singer has a huge fan base in South America.", "Şarkıcının Güney Amerika'da büyük bir hayran kitlesi var."],
      ["backstage", "sahne arkası", "🚪", "We were lucky enough to meet the band backstage after the show.", "Gösteriden sonra grupla sahne arkasında tanışacak kadar şanslıydık."],
      ["soundcheck", "ses kontrolü", "🔊", "The soundcheck took two hours because of a broken cable.", "Bozuk bir kablo yüzünden ses kontrolü iki saat sürdü."],
      ["jam session", "doğaçlama müzik buluşması", "🎷", "Every Thursday local musicians meet for a jam session at the bar.", "Her perşembe yerel müzisyenler barda doğaçlama müzik için buluşuyor."],
      ["improvise", "doğaçlama yapmak", "", "Jazz players learn to improvise when something goes wrong.", "Caz müzisyenleri bir şeyler ters gittiğinde doğaçlama yapmayı öğrenir."],
      ["acoustic", "akustik", "🎸", "They played an acoustic set with just two guitars and a violin.", "Sadece iki gitar ve bir kemanla akustik bir set çaldılar."],
      ["amplifier", "amfi, ses yükseltici", "🔌", "Turn the amplifier down a little, the neighbours are complaining.", "Amfiyi biraz kıs, komşular şikâyet ediyor."],
      ["catchy", "akılda kalıcı", "", "The song is so catchy that I've been singing it all day.", "Şarkı o kadar akılda kalıcı ki bütün gün onu söyleyip durdum."],
      ["upbeat", "neşeli, hareketli", "😄", "I need some upbeat music to get me through this report.", "Bu raporu bitirebilmek için biraz hareketli müziğe ihtiyacım var."],
      ["mellow", "yumuşak, sakin", "🌙", "The café plays mellow jazz in the evenings.", "Kafe akşamları sakin caz çalıyor."],
      ["earworm", "dile dolanan şarkı", "🐛", "That advert jingle is a terrible earworm, I can't stop humming it.", "O reklam müziği dile dolanan korkunç bir şarkı, mırıldanmayı bırakamıyorum."],
      ["hum", "mırıldanmak", "🎵", "If you don't know the words, just hum along.", "Sözleri bilmiyorsan sadece eşlik ederek mırıldan."],
      ["nightlife", "gece hayatı", "🌃", "The city is famous for its lively nightlife and late concerts.", "Şehir canlı gece hayatı ve geç saatlere uzanan konserleriyle ünlü."],
      ["entertaining", "eğlenceli, keyifli", "", "The match wasn't great, but the commentary was very entertaining.", "Maç pek iyi değildi ama anlatım çok eğlenceliydi."],
      ["amusement park", "lunapark", "🎡", "We spent the whole day at the amusement park with the kids.", "Bütün günü çocuklarla lunaparkta geçirdik."],
      ["roller coaster", "hız treni", "🎢", "I screamed the whole time I was on the roller coaster.", "Hız trenindeyken baştan sona çığlık attım."],
      ["board game", "kutu oyunu", "🎲", "On rainy weekends we usually play a board game with friends.", "Yağmurlu hafta sonlarında genelde arkadaşlarla kutu oyunu oynarız."],
      ["pastime", "eğlence, vakit geçirme uğraşı", "", "Fishing is his favourite pastime on quiet Sunday mornings.", "Balık tutmak, sakin pazar sabahlarında en sevdiği uğraş."],
      ["leisure", "boş zaman", "🏖️", "People today have less leisure time than they expected.", "Günümüzde insanların beklediğinden daha az boş zamanı var."],
      ["spectator", "seyirci", "👥", "Over fifty thousand spectators watched the final from the stands.", "Elli binden fazla seyirci finali tribünlerden izledi."],
      ["athlete", "sporcu, atlet", "🏃", "The young athlete trains six days a week before school.", "Genç sporcu haftada altı gün okuldan önce antrenman yapıyor."],
      ["tournament", "turnuva", "🏆", "Our office team reached the semi-finals of the local chess tournament.", "Ofis takımımız yerel satranç turnuvasında yarı finale kaldı."],
      ["championship", "şampiyona", "", "They need just one more win to secure the championship.", "Şampiyonayı garantilemek için sadece bir galibiyete daha ihtiyaçları var."],
      ["league", "lig", "", "The team finished third in the league last season.", "Takım geçen sezon ligi üçüncü bitirdi."],
      ["opponent", "rakip", "🤺", "She shook hands with her opponent before the match began.", "Maç başlamadan önce rakibiyle tokalaştı."],
      ["rival", "rakip, ezeli rakip", "", "Tonight they play their biggest rival from across the city.", "Bu akşam şehrin öbür yakasındaki en büyük rakipleriyle oynuyorlar."],
      ["rivalry", "rekabet, çekişme", "🔥", "The rivalry between the two clubs goes back more than a century.", "İki kulüp arasındaki rekabet yüz yıldan fazla geriye gidiyor."],
      ["referee", "hakem", "🧑‍⚖️", "The referee blew the whistle and the players stopped immediately.", "Hakem düdüğü çaldı ve oyuncular hemen durdu."],
      ["umpire", "hakem, tenis ve kriket hakemi", "🎾", "The tennis player argued with the umpire about the line call.", "Tenisçi çizgi kararı konusunda hakemle tartıştı."],
      ["squad", "kadro", "", "The coach named a young squad for the friendly match.", "Teknik direktör hazırlık maçı için genç bir kadro açıkladı."],
      ["line-up", "ilk on bir, sıralama", "📋", "There are three new names in tonight's starting line-up.", "Bu akşamki ilk on birde üç yeni isim var."],
      ["substitute", "yedek oyuncu, oyuna sonradan giren", "🔄", "The substitute scored just two minutes after coming on.", "Yedek oyuncu oyuna girdikten sadece iki dakika sonra gol attı."],
      ["captain", "kaptan", "🧢", "The captain lifted the trophy in front of the cheering fans.", "Kaptan kupayı tezahürat yapan taraftarların önünde kaldırdı."],
      ["equaliser", "beraberlik golü", "⚽", "They scored a late equaliser in the ninetieth minute.", "Doksanıncı dakikada geç bir beraberlik golü attılar."],
      ["goal difference", "averaj", "⚽", "The two teams have the same points, but we have a better goal difference.", "İki takımın puanı aynı ama bizim averajımız daha iyi."],
      ["foul", "faul", "🚩", "That was a clear foul, but the referee didn't see it.", "Bu açık bir fauldü ama hakem görmedi."],
      ["offside", "ofsayt", "", "The goal was ruled out because the striker was offside.", "Forvet ofsayt olduğu için gol iptal edildi."],
      ["red card", "kırmızı kart", "🟥", "He got a red card for kicking an opponent.", "Bir rakibe tekme attığı için kırmızı kart gördü."],
      ["injury time", "uzatma dakikaları", "⏱️", "They won the game with a header in injury time.", "Maçı uzatma dakikalarında bir kafa golüyle kazandılar."],
      ["extra time", "uzatma devresi", "", "The cup final went to extra time after a goalless ninety minutes.", "Kupa finali golsüz geçen doksan dakikanın ardından uzatmaya gitti."],
      ["half-time", "devre arası", "", "At half-time the coach changed the whole strategy.", "Devre arasında teknik direktör bütün stratejiyi değiştirdi."],
      ["victory", "zafer, galibiyet", "🏅", "Fans celebrated the victory in the streets until morning.", "Taraftarlar galibiyeti sabaha kadar sokaklarda kutladı."],
      ["defeat", "yenilgi", "", "It was their first defeat at home in two years.", "Bu, iki yıldır evlerindeki ilk yenilgileriydi."],
      ["underdog", "favori olmayan, az şansı olan taraf", "🐶", "Everyone loves to cheer for the underdog in a cup final.", "Herkes bir kupa finalinde şansı az olan tarafı desteklemeyi sever."],
      ["clinch", "kesinleştirmek, garantilemek", "", "A win on Sunday would clinch the title for the club.", "Pazar günkü bir galibiyet kulüp için şampiyonluğu garantileyecek."],
      ["qualify", "elemeleri geçmek, hak kazanmak", "", "Turkey needs to win both games to qualify for the tournament.", "Türkiye'nin turnuvaya katılma hakkı kazanması için iki maçı da kazanması gerekiyor."],
      ["knockout", "eleme usulü, nakavt", "🥊", "Only sixteen teams reach the knockout stage of the competition.", "Yarışmanın eleme aşamasına sadece on altı takım kalıyor."],
      ["semi-final", "yarı final", "", "We lost the semi-final on penalties, which was heartbreaking.", "Yarı finali penaltılarla kaybettik, bu çok yürek burkucuydu."],
      ["trophy", "kupa", "🏆", "The club hasn't won a major trophy in twenty years.", "Kulüp yirmi yıldır büyük bir kupa kazanamadı."],
      ["medal", "madalya", "🥇", "She won a silver medal at her very first Olympics.", "İlk olimpiyatında gümüş madalya kazandı."],
      ["podium", "kürsü, podyum", "", "All three runners on the podium came from the same small town.", "Kürsüdeki üç koşucunun hepsi aynı küçük kasabadan geliyordu."],
      ["record-breaking", "rekor kıran", "📈", "His record-breaking jump surprised even his own coach.", "Rekor kıran atlayışı kendi antrenörünü bile şaşırttı."],
      ["personal best", "kişisel rekor", "⏲️", "I finally ran a personal best in the city half marathon.", "Şehir yarı maratonunda sonunda kişisel rekorumu kırdım."],
      ["stamina", "dayanıklılık, kondisyon", "💪", "Swimming is a great way to build stamina without hurting your knees.", "Yüzme dizlerini incitmeden kondisyon kazanmanın harika bir yolu."],
      ["endurance", "dayanıklılık", "", "Cycling across the mountains is a real test of endurance.", "Dağları bisikletle aşmak gerçek bir dayanıklılık sınavı."],
      ["agility", "çeviklik", "🐈", "Good goalkeepers need agility just as much as physical strength.", "İyi kaleciler fiziksel güç kadar çevikliğe de ihtiyaç duyar."],
      ["training session", "antrenman", "🏋️", "The players had an extra training session on Sunday morning.", "Oyuncular pazar sabahı ekstra bir antrenman yaptı."],
      ["cool down", "soğuma hareketleri yapmak", "🧊", "Always cool down for five minutes after a hard run.", "Zorlu bir koşudan sonra her zaman beş dakika soğuma yap."],
      ["sprint", "depar atmak, kısa mesafe koşusu", "⚡", "I had to sprint to catch the last bus home.", "Eve giden son otobüse yetişmek için depar atmak zorunda kaldım."],
      ["relay", "bayrak yarışı", "🏃", "Our team dropped the baton in the final leg of the relay.", "Takımımız bayrak yarışının son ayağında bayrağı düşürdü."],
      ["lap", "tur", "🔁", "She ran one more lap of the track before going home.", "Eve gitmeden önce pistte bir tur daha koştu."],
      ["finish line", "bitiş çizgisi", "🏁", "He crossed the finish line with his arms in the air.", "Kolları havada bitiş çizgisini geçti."],
      ["gymnastics", "jimnastik", "🤸", "My daughter has been doing gymnastics since she was five.", "Kızım beş yaşından beri jimnastik yapıyor."],
      ["martial arts", "dövüş sanatları", "🥋", "Learning martial arts gave him more confidence and discipline.", "Dövüş sanatları öğrenmek ona daha fazla özgüven ve disiplin kazandırdı."],
      ["cheer on", "tezahüratla desteklemek", "📣", "Thousands of people came to cheer on the runners in the rain.", "Binlerce kişi yağmurda koşucuları desteklemek için geldi."],
      ["chant", "slogan atmak, tezahürat", "", "The fans began to chant the goalkeeper's name.", "Taraftarlar kalecinin adını tezahüratla haykırmaya başladı."],
      ["supporter", "taraftar", "🧣", "He has been a loyal supporter of the club for forty years.", "Kırk yıldır kulübün sadık bir taraftarı."],
      ["season ticket", "sezonluk bilet", "🎟️", "A season ticket is cheaper if you go to every home game.", "Her iç saha maçına gidiyorsan sezonluk bilet daha ucuz."],
      ["stadium", "stadyum", "🏟️", "The new stadium can hold sixty thousand people.", "Yeni stadyum altmış bin kişi alabiliyor."],
      ["arena", "kapalı salon, arena", "", "The basketball final will take place in the city arena.", "Basketbol finali şehirdeki kapalı salonda yapılacak."],
      ["hat-trick", "bir maçta üç gol", "⚽", "The young striker scored a hat-trick in his first match.", "Genç forvet ilk maçında üç gol attı."],
      ["make a comeback", "geri dönüş yapmak", "🔙", "After two years of injury, she hopes to make a comeback this summer.", "İki yıllık sakatlığın ardından bu yaz geri dönüş yapmayı umuyor."],
      ["sportsmanship", "sportmenlik", "🤝", "Helping his injured opponent up was a great act of sportsmanship.", "Sakatlanan rakibini ayağa kaldırması büyük bir sportmenlik örneğiydi."],
      ["fair play", "centilmenlik, adil oyun", "", "The team won a special award for fair play this season.", "Takım bu sezon centilmenlik için özel bir ödül kazandı."],
      ["doping", "doping", "💉", "The cyclist was banned for two years after a doping test.", "Bisikletçi doping testinden sonra iki yıl men edildi."],
      ["disqualify", "diskalifiye etmek", "🚫", "The judges may disqualify any swimmer who starts too early.", "Hakemler erken çıkış yapan her yüzücüyü diskalifiye edebilir."],
      ["tracklist", "şarkı listesi", "📃", "The band finally revealed the tracklist of their new album.", "Grup sonunda yeni albümlerinin şarkı listesini açıkladı."],
      ["mascot", "maskot", "🐻", "The team mascot danced with children during the break.", "Takım maskotu arada çocuklarla dans etti."],
      ["transfer window", "transfer dönemi", "📝", "The club signed three new players before the transfer window closed.", "Kulüp transfer dönemi kapanmadan önce üç yeni oyuncuyla anlaştı."]
    ] }
);
