(window.LIBRARY = window.LIBRARY || []).push(
  { id: "lib4a", title: "Psikoloji ve Davranış", icon: "🧠", cefr: "B2", desc: "Duyguları, alışkanlıkları ve insan davranışını anlatmak için gereken kelimeler.",
    words: [
      ["anxiety", "kaygı, endişe", "😰", "Her anxiety gets worse before every job interview she attends.", "Katıldığı her iş görüşmesinden önce kaygısı artıyor."],
      ["resilience", "dayanıklılık, toparlanma gücü", "💪", "Children often show surprising resilience after a difficult family change.", "Çocuklar zor bir aile değişikliğinden sonra çoğu zaman şaşırtıcı bir dayanıklılık gösterir."],
      ["mindset", "zihniyet, bakış açısı", "🧭", "A positive mindset will not solve everything, but it certainly helps.", "Olumlu bir zihniyet her şeyi çözmez ama kesinlikle yardımcı olur."],
      ["overthink", "fazla kafa yormak, kafasında büyütmek", "🌀", "Try not to overthink a simple text message from your boss.", "Patronundan gelen basit bir mesajı kafanda büyütmemeye çalış."],
      ["trauma", "travma", "🩹", "He still carries the trauma of the car accident he survived years ago.", "Yıllar önce atlattığı araba kazasının travmasını hâlâ taşıyor."],
      ["envy", "imrenme, haset", "💚", "She felt a little envy when her friend got the promotion.", "Arkadaşı terfi alınca biraz haset duydu."],
      ["frustration", "hayal kırıklığı, bıkkınlık", "😤", "I understand your frustration, but shouting will not fix the printer.", "Bıkkınlığını anlıyorum ama bağırmak yazıcıyı düzeltmeyecek."],
      ["temper", "öfke, huy", "🌋", "My uncle has a terrible temper when he is hungry.", "Amcam acıktığında çok kötü bir öfkeye kapılır."],
      ["phobia", "fobi", "🕷️", "Her phobia of spiders makes camping trips very stressful.", "Örümcek fobisi kamp gezilerini çok stresli hâle getiriyor."],
      ["depression", "depresyon", "🌧️", "Depression is a real illness and it deserves proper treatment.", "Depresyon gerçek bir hastalıktır ve düzgün bir tedaviyi hak eder."],
      ["cognitive", "bilişsel", "🧩", "Regular exercise can improve cognitive performance in older adults.", "Düzenli egzersiz yaşlı yetişkinlerde bilişsel performansı artırabilir."],
      ["behaviour", "davranış", "🚶", "The teacher praised his behaviour during the school trip.", "Öğretmen okul gezisi sırasındaki davranışını övdü."],
      ["trigger", "tetiklemek", "⚡", "Loud noises can trigger bad memories for some soldiers.", "Yüksek sesler bazı askerlerde kötü anıları tetikleyebilir."],
      ["conformity", "uyum gösterme, uyumculuk", "🐑", "Teenagers often feel strong pressure toward conformity at school.", "Gençler okulda çoğu zaman uyum göstermeye yönelik güçlü bir baskı hisseder."],
      ["self-control", "öz denetim", "🧘", "It takes a lot of self-control to ignore a plate of fresh cookies.", "Bir tabak taze kurabiyeyi görmezden gelmek büyük öz denetim gerektirir."],
      ["temptation", "ayartı, cazibe", "🍰", "I resisted the temptation to check my phone during dinner.", "Akşam yemeğinde telefonuma bakma cazibesine direndim."],
      ["punishment", "ceza", "⛔", "Experts say punishment alone rarely changes a child's behaviour.", "Uzmanlar tek başına cezanın bir çocuğun davranışını nadiren değiştirdiğini söylüyor."],
      ["reinforce", "pekiştirmek", "🔁", "Small rewards can reinforce good habits in the early weeks.", "Küçük ödüller ilk haftalarda iyi alışkanlıkları pekiştirebilir."],
      ["manipulate", "manipüle etmek, yönlendirmek", "🎭", "He tried to manipulate his friends into lending him money.", "Arkadaşlarını kendisine borç vermeleri için manipüle etmeye çalıştı."],
      ["denial", "inkâr, gerçeği kabul etmeme", "🙈", "She was in denial about how much the breakup had hurt her.", "Ayrılığın onu ne kadar incittiğini kabul etmiyordu."],
      ["rationalize", "kendine haklı gerekçe bulmak", "🤔", "People often rationalize bad decisions after they have already made them.", "İnsanlar çoğu zaman kötü kararları verdikten sonra kendilerine haklı gerekçe bulur."],
      ["resentment", "içerleme, kırgınlık", "😒", "Years of unfair treatment had filled him with resentment.", "Yıllarca süren adaletsiz muamele onu kırgınlıkla doldurmuştu."],
      ["isolated", "yalnız kalmış, yalıtılmış", "🏝️", "Working from home made him feel isolated from his colleagues.", "Evden çalışmak onu iş arkadaşlarından yalıtılmış hissettirdi."],
      ["bond", "bağ", "🤝", "The two sisters share a strong bond despite living far apart.", "İki kız kardeş birbirinden uzakta yaşasa da güçlü bir bağ paylaşıyor."],
      ["mindful", "bilinçli, farkında", "🍃", "Try to be mindful of how much time you spend on social media.", "Sosyal medyada ne kadar zaman geçirdiğinin farkında olmaya çalış."],
      ["wellbeing", "iyi oluş, esenlik", "🌿", "The company now offers free sessions to support employee wellbeing.", "Şirket artık çalışanların iyi oluşunu desteklemek için ücretsiz seanslar sunuyor."],
      ["validation", "onaylanma, takdir görme", "👍", "Many people look for validation through likes and comments online.", "Pek çok kişi internette beğeni ve yorumlarla onaylanma arıyor."],
      ["approval", "onay, beğeni", "✅", "He still seeks his father's approval for every big decision.", "Hâlâ her büyük karar için babasının onayını arıyor."],
      ["discourage", "cesaretini kırmak, caydırmak", "🚧", "Do not let one bad grade discourage you from studying science.", "Tek bir kötü notun seni fen okumaktan caydırmasına izin verme."],
      ["curiosity", "merak", "🔍", "Her curiosity about other cultures led her to travel alone.", "Diğer kültürlere duyduğu merak onu yalnız seyahat etmeye yöneltti."],
      ["boredom", "can sıkıntısı", "🥱", "Some studies suggest that boredom can actually boost creativity.", "Bazı araştırmalar can sıkıntısının aslında yaratıcılığı artırabileceğini öne sürüyor."],
      ["distracted", "dikkati dağılmış", "📱", "I get easily distracted when my phone is on the desk.", "Telefonum masadayken dikkatim kolayca dağılıyor."],
      ["recall", "hatırlamak, anımsamak", "💭", "I cannot recall the name of the restaurant we visited last summer.", "Geçen yaz gittiğimiz restoranın adını hatırlayamıyorum."],
      ["forgetful", "unutkan", "🗝️", "My grandmother has become a bit forgetful, so she writes everything down.", "Büyükannem biraz unutkan oldu, bu yüzden her şeyi not alıyor."],
      ["daydream", "hayal kurmak, dalıp gitmek", "☁️", "I often daydream about living in a small village by the sea.", "Sık sık deniz kenarındaki küçük bir köyde yaşamanın hayalini kuruyorum."],
      ["perceive", "algılamak", "👁️", "People perceive the same situation differently depending on their mood.", "İnsanlar aynı durumu ruh hâllerine göre farklı algılar."],
      ["misinterpret", "yanlış yorumlamak", "❓", "It is easy to misinterpret tone in a short written message.", "Kısa bir yazılı mesajdaki tonu yanlış yorumlamak kolaydır."],
      ["judgmental", "yargılayıcı", "☝️", "A good therapist listens carefully without being judgmental.", "İyi bir terapist yargılayıcı olmadan dikkatle dinler."],
      ["optimism", "iyimserlik", "🌅", "Her optimism kept the whole team going during the crisis.", "İyimserliği kriz sırasında bütün ekibi ayakta tuttu."],
      ["pessimist", "kötümser kişi", "🌑", "As a pessimist, he always expects the worst from every plan.", "Kötümser biri olarak her plandan hep en kötüsünü bekler."],
      ["cynical", "her şeye şüpheyle bakan, alaycı", "🙄", "Years in politics made him cynical about people's real motives.", "Siyasette geçen yıllar onu insanların gerçek niyetleri konusunda alaycı yaptı."],
      ["naive", "saf, toy", "🐣", "It was naive of me to believe the seller's promises.", "Satıcının vaatlerine inanmam saflıktı."],
      ["sociable", "girişken, sosyal", "🎉", "My new flatmate is very sociable and loves hosting dinners.", "Yeni ev arkadaşım çok sosyal ve yemek vermeye bayılıyor."],
      ["fulfilled", "tatmin olmuş, doyuma ulaşmış", "🌻", "She finally feels fulfilled since she started working as a nurse.", "Hemşire olarak çalışmaya başladığından beri sonunda kendini tatmin olmuş hissediyor."],
      ["hostile", "düşmanca", "😠", "The atmosphere in the meeting became hostile after the budget cuts.", "Bütçe kesintilerinden sonra toplantıdaki hava düşmanca bir hâl aldı."],
      ["sympathetic", "anlayışlı, halden anlayan", "🫂", "My manager was very sympathetic when my father was ill.", "Babam hastayken müdürüm çok anlayışlı davrandı."],
      ["ego", "ego, benlik", "🦚", "His ego would not let him admit that he was wrong.", "Egosu hatalı olduğunu kabul etmesine izin vermedi."],
      ["people-pleaser", "herkesi memnun etmeye çalışan kişi", "🙇", "As a people-pleaser, she finds it really hard to say no.", "Herkesi memnun etmeye çalışan biri olarak hayır demekte çok zorlanıyor."],
      ["procrastination", "erteleme alışkanlığı", "⏳", "Procrastination is often a way of avoiding uncomfortable feelings.", "Erteleme çoğu zaman rahatsız edici duygulardan kaçmanın bir yoludur."],
      ["impulse", "dürtü, ani istek", "⚡", "I bought the jacket on impulse and regretted it the next day.", "Ceketi ani bir istekle aldım ve ertesi gün pişman oldum."],
      ["urge", "güçlü istek, dürtü", "🔥", "I had a sudden urge to call my old school friend.", "Birden eski okul arkadaşımı arama isteği duydum."],
      ["crave", "çok istemek, canı çekmek", "🍫", "I always crave something sweet late in the evening.", "Akşamın geç saatlerinde canım hep tatlı bir şey çeker."],
      ["repress", "bastırmak", "🔒", "Some people repress painful memories for many years.", "Bazı insanlar acı verici anıları yıllarca bastırır."],
      ["suppress", "bastırmak, zapt etmek", "🤐", "He tried to suppress a laugh during the serious presentation.", "Ciddi sunum sırasında gülmesini bastırmaya çalıştı."],
      ["habitual", "alışkanlık hâline gelmiş", "🔄", "His habitual lateness finally cost him his job.", "Alışkanlık hâline gelen geç kalması sonunda ona işine mal oldu."],
      ["ruminate", "aynı şeyi zihninde evirip çevirmek", "🔂", "Try not to ruminate on mistakes you cannot change anymore.", "Artık değiştiremeyeceğin hatalar üzerinde durmadan düşünmemeye çalış."],
      ["tantrum", "öfke nöbeti, huysuzluk krizi", "🧒", "The little boy threw a tantrum in the middle of the supermarket.", "Küçük çocuk süpermarketin ortasında öfke nöbeti geçirdi."],
      ["obsessed", "takıntılı", "🔁", "He is completely obsessed with checking his step count.", "Adım sayısını kontrol etmeye tamamen takıntılı."],
      ["compulsive", "kontrol edilemeyen, saplantılı", "🛍️", "Compulsive shopping can quickly lead to serious debt.", "Kontrol edilemeyen alışveriş hızla ciddi borçlara yol açabilir."],
      ["subconscious", "bilinçaltı", "🌊", "Our subconscious often affects decisions we think are logical.", "Bilinçaltımız mantıklı sandığımız kararları çoğu zaman etkiler."],
      ["bottle up", "duygularını içine atmak", "🍾", "If you bottle up your anger, it will come out later.", "Öfkeni içine atarsan daha sonra dışarı çıkacaktır."],
      ["lash out", "birine öfkeyle saldırmak, patlamak", "💥", "When he is stressed, he tends to lash out at his family.", "Stresliyken ailesine patlama eğiliminde."],
      ["freak out", "panikleyip kendini kaybetmek", "😱", "Do not freak out, but I think I lost your car keys.", "Panik yapma ama sanırım arabanın anahtarlarını kaybettim."],
      ["calm down", "sakinleşmek", "😮‍💨", "Take a few deep breaths and try to calm down first.", "Birkaç derin nefes al ve önce sakinleşmeye çalış."],
      ["act out", "yaramazlık yapmak, sorunlu davranmak", "🎬", "Children sometimes act out when they feel ignored at home.", "Çocuklar evde görmezden gelindiklerini hissettiklerinde bazen sorunlu davranırlar."],
      ["snap at", "birine tersçe çıkışmak", "🐊", "I am sorry I snap at you when I am tired.", "Yorgunken sana tersçe çıkıştığım için özür dilerim."],
      ["come to terms with", "kabullenmek, barışmak", "🕊️", "It took her years to come to terms with her mother's death.", "Annesinin ölümünü kabullenmesi yıllar aldı."],
      ["peer pressure", "akran baskısı", "👥", "Many teenagers start smoking because of peer pressure.", "Pek çok genç akran baskısı yüzünden sigaraya başlar."],
      ["mood swings", "ani ruh hâli değişimleri", "🎢", "Lack of sleep can cause serious mood swings in adults too.", "Uykusuzluk yetişkinlerde de ciddi ruh hâli değişimlerine yol açabilir."],
      ["defence mechanism", "savunma mekanizması", "🛡️", "Humour is often a defence mechanism against painful feelings.", "Mizah çoğu zaman acı veren duygulara karşı bir savunma mekanizmasıdır."],
      ["coping mechanism", "başa çıkma yöntemi", "🧰", "Running became his main coping mechanism after the divorce.", "Boşanmadan sonra koşu onun ana başa çıkma yöntemi oldu."],
      ["attention span", "dikkat süresi", "⏱️", "Some people believe short videos are reducing our attention span.", "Bazı insanlar kısa videoların dikkat süremizi azalttığına inanıyor."],
      ["emotional intelligence", "duygusal zekâ", "💞", "Good leaders usually have a high level of emotional intelligence.", "İyi liderler genellikle yüksek düzeyde duygusal zekâya sahiptir."],
      ["inferiority complex", "aşağılık kompleksi", "📉", "He developed an inferiority complex after years of comparison with his brother.", "Yıllarca ağabeyiyle kıyaslandıktan sonra aşağılık kompleksi geliştirdi."],
      ["short-tempered", "çabuk sinirlenen", "🧨", "The new chef is talented but quite short-tempered in the kitchen.", "Yeni şef yetenekli ama mutfakta oldukça çabuk sinirleniyor."],
      ["level-headed", "aklı başında, soğukkanlı", "⚖️", "We need someone level-headed to handle the angry customers.", "Kızgın müşterilerle ilgilenecek soğukkanlı birine ihtiyacımız var."],
      ["thick-skinned", "eleştiriden etkilenmeyen, vurdumduymaz", "🦏", "You have to be thick-skinned to read online comments about your work.", "İşinle ilgili internet yorumlarını okumak için eleştiriden etkilenmeyen biri olmalısın."],
      ["self-conscious", "çekingen, kendinden utanan", "😳", "He feels self-conscious about his accent when he speaks English.", "İngilizce konuşurken aksanından utanıyor."],
      ["self-doubt", "kendinden şüphe etme", "🌫️", "Even successful artists struggle with self-doubt before a show.", "Başarılı sanatçılar bile bir gösteriden önce kendilerinden şüphe etmekle boğuşur."],
      ["self-pity", "kendine acıma", "🥀", "After a day of self-pity, she decided to look for a new job.", "Bir gün kendine acıdıktan sonra yeni bir iş aramaya karar verdi."],
      ["self-destructive", "kendine zarar veren", "💣", "Drinking every night is a self-destructive way to deal with stress.", "Her gece içmek stresle başa çıkmanın kendine zarar veren bir yoludur."],
      ["self-sabotage", "kendi başarısını baltalamak", "🪓", "Some people self-sabotage just before they reach an important goal.", "Bazı insanlar önemli bir hedefe ulaşmadan hemen önce kendi başarılarını baltalar."],
      ["insecurity", "güvensizlik", "🥺", "Her jealousy comes from a deep insecurity about the relationship.", "Kıskançlığı ilişkiyle ilgili derin bir güvensizlikten kaynaklanıyor."],
      ["vulnerability", "kırılganlık, savunmasızlık", "🫀", "Showing vulnerability can actually make a leader more trusted.", "Kırılganlık göstermek aslında bir lideri daha güvenilir kılabilir."],
      ["apathy", "ilgisizlik, umursamazlık", "😶", "Voter apathy was the biggest problem in the local elections.", "Yerel seçimlerdeki en büyük sorun seçmen ilgisizliğiydi."],
      ["indifferent", "kayıtsız, ilgisiz", "🤷", "He seemed completely indifferent to the news of his promotion.", "Terfi haberine tamamen kayıtsız görünüyordu."],
      ["despair", "umutsuzluk", "🕳️", "After losing the house, the family was in complete despair.", "Evi kaybettikten sonra aile tam bir umutsuzluk içindeydi."],
      ["grief", "derin keder, yas", "🖤", "Everyone experiences grief in their own way and at their own pace.", "Herkes yası kendi yolunda ve kendi hızında yaşar."],
      ["grieve", "yas tutmak", "🕯️", "Give yourself time to grieve before you make big decisions.", "Büyük kararlar vermeden önce yas tutmak için kendine zaman tanı."],
      ["euphoria", "aşırı sevinç, coşku", "🎆", "The euphoria of winning the match lasted for days.", "Maçı kazanmanın coşkusu günlerce sürdü."],
      ["composure", "soğukkanlılık, kendine hâkimiyet", "🧊", "She kept her composure even when the interviewer was rude.", "Görüşmeci kaba davrandığında bile soğukkanlılığını korudu."],
      ["cope", "başa çıkmak", "🌊", "Everyone needs healthy ways to cope with stress at work.", "Herkesin işteki stresle başa çıkmak için sağlıklı yollara ihtiyacı var."],
      ["deep-seated", "köklü, derinlere işlemiş", "🌳", "His fear of failure is deep-seated and goes back to childhood.", "Başarısızlık korkusu derinlere işlemiş ve çocukluğuna kadar uzanıyor."],
      ["ingrained", "kökleşmiş, iyice yerleşmiş", "🪨", "Some ingrained habits take months of effort to change.", "Bazı kökleşmiş alışkanlıkları değiştirmek aylarca çaba ister."],
      ["incentive", "teşvik, özendirici", "🎁", "A small bonus can be a strong incentive for the sales team.", "Küçük bir prim satış ekibi için güçlü bir teşvik olabilir."],
      ["susceptible", "yatkın, kolayca etkilenen", "🦠", "Tired people are more susceptible to clever advertising.", "Yorgun insanlar zekice yapılmış reklamlardan daha kolay etkilenir."],
      ["needy", "ilgiye muhtaç, sürekli ilgi bekleyen", "🥹", "He worried that calling her every day would seem needy.", "Onu her gün aramanın sürekli ilgi bekliyormuş gibi görüneceğinden endişelendi."],
      ["possessive", "sahiplenici, kıskanç", "🔐", "A possessive partner may try to control who you see.", "Sahiplenici bir partner kimlerle görüştüğünü kontrol etmeye çalışabilir."],
      ["overprotective", "aşırı korumacı", "🐥", "Overprotective parents sometimes stop children from learning independence.", "Aşırı korumacı ebeveynler bazen çocukların bağımsızlığı öğrenmesini engeller."],
      ["overreact", "aşırı tepki vermek", "📢", "I think you overreact every time someone criticizes your cooking.", "Bence biri yemeğini eleştirdiğinde her seferinde aşırı tepki veriyorsun."],
      ["overconfident", "kendine aşırı güvenen", "😎", "He was overconfident and did not prepare for the final exam.", "Kendine aşırı güveniyordu ve final sınavına hazırlanmadı."],
      ["wishful thinking", "hüsnükuruntu, boş umut", "🌠", "Expecting a pay rise this year is probably wishful thinking.", "Bu yıl maaş artışı beklemek muhtemelen boş bir umut."],
      ["cognitive dissonance", "bilişsel çelişki", "⚔️", "Smokers who know the risks often experience cognitive dissonance.", "Riskleri bilen sigara içiciler çoğu zaman bilişsel çelişki yaşar."],
      ["confirmation bias", "doğrulama yanlılığı", "🔎", "Confirmation bias makes us notice only the facts we already agree with.", "Doğrulama yanlılığı yalnızca zaten katıldığımız gerçekleri fark etmemize yol açar."],
      ["nervous breakdown", "sinir krizi, ruhsal çöküntü", "🧯", "Months of overwork nearly led him to a nervous breakdown.", "Aylarca aşırı çalışmak onu neredeyse ruhsal bir çöküntüye sürükledi."],
      ["psychological", "psikolojik", "🧠", "The psychological effects of the pandemic are still being studied.", "Salgının psikolojik etkileri hâlâ araştırılıyor."],
      ["psychiatrist", "psikiyatrist", "🩺", "Her doctor referred her to a psychiatrist for further support.", "Doktoru onu daha fazla destek için bir psikiyatriste yönlendirdi."],
      ["tendency", "eğilim", "📈", "She has a tendency to apologize even when it is not her fault.", "Suç onda olmasa bile özür dileme eğilimi var."],
      ["prone to", "yatkın, eğilimli", "⚠️", "People who sleep badly are more prone to anxiety and irritation.", "Kötü uyuyan insanlar kaygıya ve sinirliliğe daha yatkındır."],
      ["passive-aggressive", "pasif agresif", "📝", "Leaving passive-aggressive notes on the fridge will not solve the problem.", "Buzdolabına pasif agresif notlar bırakmak sorunu çözmeyecek."]
    ] },
  { id: "lib4b", title: "Eğitim ve Akademi", icon: "🎓", cefr: "C1", desc: "Üniversite hayatı, araştırma ve akademik çalışma için ileri düzey kelimeler.",
    words: [
      ["syllabus", "ders izlencesi, müfredat", "📋", "The professor added two new novels to the syllabus this term.", "Profesör bu dönem ders izlencesine iki yeni roman ekledi."],
      ["grant", "hibe, burs fonu", "💰", "Our team received a three-year grant to study coastal erosion.", "Ekibimiz kıyı erozyonunu incelemek için üç yıllık bir hibe aldı."],
      ["enrolment", "kayıt, kayıtlı öğrenci sayısı", "📝", "Enrolment in evening language classes has doubled since last year.", "Akşam dil kurslarına kayıt geçen yıldan bu yana iki katına çıktı."],
      ["qualitative", "nitel", "🗣️", "She used qualitative interviews to understand how nurses experience burnout.", "Hemşirelerin tükenmişliği nasıl yaşadığını anlamak için nitel görüşmeler kullandı."],
      ["quantitative", "nicel", "📊", "The study combines quantitative data with personal stories from participants.", "Çalışma nicel verileri katılımcıların kişisel hikâyeleriyle birleştiriyor."],
      ["publication", "yayın", "📰", "The publication of her first paper opened many doors in academia.", "İlk makalesinin yayımlanması ona akademide pek çok kapı açtı."],
      ["conference", "konferans, kongre", "🎤", "I am presenting my findings at an international conference in Lisbon.", "Bulgularımı Lizbon'daki uluslararası bir kongrede sunuyorum."],
      ["faculty", "fakülte, öğretim kadrosu", "🏛️", "The faculty voted to change the grading system next year.", "Öğretim kadrosu gelecek yıl not sistemini değiştirmek için oy kullandı."],
      ["module", "modül, ders birimi", "🧱", "This module covers the history of European economic thought.", "Bu modül Avrupa iktisadi düşüncesinin tarihini kapsıyor."],
      ["extension", "ek süre", "⏰", "I asked my tutor for an extension because I had been ill.", "Hasta olduğum için hocamdan ek süre istedim."],
      ["submission", "teslim, gönderim", "📤", "The deadline for submission is midnight on Friday.", "Teslim için son tarih cuma gece yarısı."],
      ["assessment", "değerlendirme, ölçme", "📏", "Final assessment for the course is based on a portfolio, not an exam.", "Dersin final değerlendirmesi sınava değil bir portfolyoya dayanıyor."],
      ["assess", "değerlendirmek, ölçmek", "🔬", "Teachers need better tools to assess speaking skills fairly.", "Öğretmenlerin konuşma becerilerini adil biçimde ölçmek için daha iyi araçlara ihtiyacı var."],
      ["evaluate", "değerlendirmek", "🧮", "Students must evaluate the reliability of every source they use.", "Öğrenciler kullandıkları her kaynağın güvenilirliğini değerlendirmeli."],
      ["transcript", "not dökümü, transkript", "📄", "Please attach an official transcript to your application form.", "Lütfen başvuru formunuza resmî bir not dökümü ekleyin."],
      ["diploma", "diploma", "📜", "He finally framed his diploma and hung it in his office.", "Sonunda diplomasını çerçeveletip ofisine astı."],
      ["doctorate", "doktora", "🎓", "She completed her doctorate while raising two small children.", "İki küçük çocuk büyütürken doktorasını tamamladı."],
      ["major", "ana dal, bölüm", "🎯", "My major is economics, but I take art classes for fun.", "Ana dalım ekonomi ama zevk için sanat dersleri alıyorum."],
      ["elective", "seçmeli ders", "🎨", "I chose photography as an elective in my second year.", "İkinci yılımda seçmeli ders olarak fotoğrafçılığı seçtim."],
      ["compulsory", "zorunlu", "📌", "Statistics is compulsory for all first-year psychology students.", "İstatistik tüm birinci sınıf psikoloji öğrencileri için zorunludur."],
      ["prerequisite", "ön koşul", "🔑", "Basic algebra is a prerequisite for this engineering course.", "Temel cebir bu mühendislik dersi için ön koşuldur."],
      ["memorize", "ezberlemek", "🧠", "Instead of trying to memorize dates, try to understand the causes.", "Tarihleri ezberlemeye çalışmak yerine nedenleri anlamaya çalış."],
      ["analytical", "analitik", "🔍", "The job requires strong analytical skills and attention to detail.", "İş güçlü analitik beceriler ve ayrıntıya dikkat gerektiriyor."],
      ["invigilator", "sınav gözetmeni", "👀", "The invigilator collected all phones before the exam began.", "Sınav gözetmeni sınav başlamadan önce bütün telefonları topladı."],
      ["retake", "tekrar girmek, yeniden almak", "🔁", "If you fail, you can retake the exam in September.", "Kalırsan sınava eylülde tekrar girebilirsin."],
      ["distinction", "derece, üstün başarı", "🏅", "She graduated with distinction from one of the top law schools.", "En iyi hukuk fakültelerinden birinden dereceyle mezun oldu."],
      ["alumni", "mezunlar", "👨‍🎓", "The university invited alumni to mentor current students.", "Üniversite mevcut öğrencilere mentorluk yapmaları için mezunları davet etti."],
      ["vocational", "mesleki", "🔧", "Vocational training can lead to well-paid jobs without a university degree.", "Mesleki eğitim üniversite diploması olmadan iyi ücretli işlere götürebilir."],
      ["apprenticeship", "çıraklık, meslek eğitimi programı", "🛠️", "He did a four-year apprenticeship with a local electrician.", "Yerel bir elektrikçinin yanında dört yıllık bir çıraklık yaptı."],
      ["literacy", "okuryazarlık", "📖", "Digital literacy is now as important as reading and writing.", "Dijital okuryazarlık artık okuma yazma kadar önemli."],
      ["numeracy", "temel matematik becerisi", "🔢", "Poor numeracy can make everyday tasks like budgeting very difficult.", "Zayıf matematik becerisi bütçe yapmak gibi günlük işleri çok zorlaştırabilir."],
      ["pedagogy", "pedagoji, öğretim bilimi", "🍎", "Modern pedagogy encourages students to ask questions rather than just listen.", "Modern pedagoji öğrencileri sadece dinlemek yerine soru sormaya teşvik eder."],
      ["admission", "kabul, giriş", "🚪", "Admission to the medical school is extremely competitive.", "Tıp fakültesine kabul son derece rekabetçidir."],
      ["tenure", "kadro, kalıcı akademik görev", "🔒", "After ten years of teaching, he was finally granted tenure.", "On yıllık öğretmenlikten sonra nihayet kalıcı kadro aldı."],
      ["funding", "fon, finansman", "🏦", "The project was cancelled because of a lack of funding.", "Proje finansman eksikliği nedeniyle iptal edildi."],
      ["fieldwork", "saha çalışması", "🗺️", "She spent six months doing fieldwork in remote mountain villages.", "Uzak dağ köylerinde altı ay saha çalışması yaptı."],
      ["replicate", "tekrarlamak, yinelemek", "🧪", "Other scientists were unable to replicate the surprising results.", "Diğer bilim insanları şaşırtıcı sonuçları tekrarlayamadı."],
      ["theoretical", "kuramsal, teorik", "📐", "The course is too theoretical and offers little practical training.", "Ders fazla kuramsal ve çok az pratik eğitim sunuyor."],
      ["discipline", "bilim dalı, disiplin", "🧬", "Linguistics is a discipline that overlaps with psychology and philosophy.", "Dilbilim psikoloji ve felsefeyle örtüşen bir bilim dalıdır."],
      ["interdisciplinary", "disiplinlerarası", "🔗", "Climate research is increasingly interdisciplinary and involves economists too.", "İklim araştırmaları giderek disiplinlerarası hâle geliyor ve ekonomistleri de kapsıyor."],
      ["scholar", "akademisyen, âlim", "🧑‍🏫", "She is a respected scholar of medieval Islamic art.", "Ortaçağ İslam sanatı alanında saygın bir akademisyendir."],
      ["academia", "akademi, akademik dünya", "🏫", "After his PhD, he left academia to work in industry.", "Doktorasından sonra sektörde çalışmak için akademik dünyadan ayrıldı."],
      ["erudite", "çok bilgili, engin bilgili", "🦉", "Our lecturer is erudite but explains things in simple language.", "Hocamız çok bilgili ama konuları sade bir dille anlatıyor."],
      ["well-read", "çok okumuş", "📚", "My grandfather was a well-read man who loved discussing history.", "Dedem tarih tartışmayı seven çok okumuş bir adamdı."],
      ["comprehension", "kavrama, anlama", "🧐", "The test checks reading comprehension rather than grammar knowledge.", "Test dilbilgisi bilgisinden çok okuduğunu anlamayı ölçüyor."],
      ["grasp", "kavramak", "✊", "It took me weeks to grasp the basic ideas of quantum physics.", "Kuantum fiziğinin temel fikirlerini kavramam haftalar aldı."],
      ["proficiency", "yeterlilik, ustalık", "🏆", "Applicants must prove their proficiency in English with a certificate.", "Adaylar İngilizce yeterliliklerini bir sertifikayla kanıtlamalı."],
      ["aptitude", "yetenek, kabiliyet", "🎹", "He showed an early aptitude for languages and music.", "Dillere ve müziğe erken yaşta yetenek gösterdi."],
      ["gifted", "üstün yetenekli", "🌟", "The school runs a special programme for gifted children.", "Okul üstün yetenekli çocuklar için özel bir program yürütüyor."],
      ["extracurricular", "ders dışı", "⚽", "Universities value extracurricular activities as much as good grades.", "Üniversiteler ders dışı etkinliklere iyi notlar kadar değer veriyor."],
      ["expel", "okuldan atmak", "🚫", "The school decided to expel two students for cheating.", "Okul kopya çektikleri için iki öğrenciyi okuldan atmaya karar verdi."],
      ["skim", "göz gezdirmek", "👓", "Skim the article first to get a general idea of the topic.", "Konu hakkında genel bir fikir edinmek için önce makaleye göz gezdir."],
      ["summarize", "özetlemek", "✂️", "Can you summarize the main argument in two sentences?", "Ana argümanı iki cümlede özetleyebilir misin?"],
      ["rubric", "puanlama ölçütü tablosu", "📑", "The rubric explains exactly how each essay will be marked.", "Puanlama tablosu her makalenin tam olarak nasıl notlanacağını açıklıyor."],
      ["criteria", "ölçütler", "☑️", "The selection criteria include academic results and an interview.", "Seçim ölçütleri akademik sonuçları ve bir mülakatı içeriyor."],
      ["benchmark", "ölçüt, kıyas noktası", "📍", "These test scores serve as a benchmark for future years.", "Bu sınav puanları gelecek yıllar için bir kıyas noktası işlevi görüyor."],
      ["scrutinize", "dikkatle incelemek", "🔎", "Reviewers will scrutinize every figure in your research paper.", "Hakemler araştırma makalendeki her rakamı dikkatle inceleyecek."],
      ["synthesize", "sentezlemek, birleştirmek", "🧷", "A good essay must synthesize ideas from several different sources.", "İyi bir makale birkaç farklı kaynaktan gelen fikirleri sentezlemelidir."],
      ["infer", "çıkarım yapmak", "💡", "From the data, we can infer that sleep affects exam results.", "Verilerden uykunun sınav sonuçlarını etkilediği çıkarımını yapabiliriz."],
      ["rigour", "titizlik, kesinlik", "⚙️", "The study was criticized for its lack of scientific rigour.", "Çalışma bilimsel titizlikten yoksun olduğu için eleştirildi."],
      ["tuition fee", "öğrenim ücreti, harç", "💳", "The tuition fee for international students rose again this year.", "Uluslararası öğrenciler için öğrenim ücreti bu yıl yine arttı."],
      ["gap year", "ara yıl", "🌍", "She took a gap year to volunteer before starting university.", "Üniversiteye başlamadan önce gönüllü çalışmak için bir ara yıl verdi."],
      ["freshman", "birinci sınıf öğrencisi", "🆕", "As a freshman, I got lost on campus almost every day.", "Birinci sınıf öğrencisiyken neredeyse her gün kampüste kayboluyordum."],
      ["lecture hall", "amfi, konferans salonu", "🏟️", "The lecture hall was so full that some students sat on the floor.", "Amfi o kadar doluydu ki bazı öğrenciler yere oturdu."],
      ["reading list", "okuma listesi", "📚", "The reading list for this course has over forty books.", "Bu dersin okuma listesinde kırktan fazla kitap var."],
      ["office hours", "hocanın görüşme saatleri", "🕑", "If you have questions, come to my office hours on Tuesday.", "Sorunuz varsa salı günkü görüşme saatlerime gelin."],
      ["study abroad", "yurt dışında okumak", "✈️", "Many students dream of the chance to study abroad for a semester.", "Pek çok öğrenci bir dönem yurt dışında okuma fırsatını hayal eder."],
      ["exchange student", "değişim öğrencisi", "🔄", "We hosted an exchange student from Brazil for a whole year.", "Brezilyalı bir değişim öğrencisini bütün bir yıl ağırladık."],
      ["boarding school", "yatılı okul", "🛏️", "He was sent to boarding school at the age of eleven.", "On bir yaşında yatılı okula gönderildi."],
      ["mature student", "ileri yaşta üniversiteye başlayan öğrenci", "🧑‍🦳", "As a mature student, she brought valuable work experience to class.", "İleri yaşta öğrenci olarak derse değerli bir iş deneyimi kattı."],
      ["distance learning", "uzaktan eğitim", "💻", "Distance learning allowed him to study while working full time.", "Uzaktan eğitim tam zamanlı çalışırken okumasını sağladı."],
      ["rote learning", "ezbercilik", "🦜", "Critics argue that rote learning kills curiosity in young students.", "Eleştirmenler ezberciliğin genç öğrencilerdeki merakı öldürdüğünü savunuyor."],
      ["hands-on", "uygulamalı", "🙌", "The workshop offers hands-on experience with real lab equipment.", "Atölye gerçek laboratuvar ekipmanıyla uygulamalı deneyim sunuyor."],
      ["trial and error", "deneme yanılma", "🎯", "I learned to code mostly through trial and error.", "Kod yazmayı çoğunlukla deneme yanılma yoluyla öğrendim."],
      ["fall behind", "geride kalmak", "🐢", "If you miss too many classes, you will fall behind quickly.", "Çok fazla derse girmezsen hızla geride kalırsın."],
      ["catch up on", "eksiğini kapatmak, telafi etmek", "🏃", "I spent the weekend trying to catch up on my reading.", "Hafta sonunu okuma eksiklerimi kapatmaya çalışarak geçirdim."],
      ["keep up with", "ayak uydurmak, yetişmek", "🚴", "It is hard to keep up with the latest research in this field.", "Bu alandaki en son araştırmalara yetişmek zor."],
      ["hit the books", "derslere gömülmek, sıkı çalışmak", "📘", "Exams start next week, so I really need to hit the books.", "Sınavlar gelecek hafta başlıyor, bu yüzden gerçekten derslere gömülmem lazım."],
      ["pass with flying colours", "parlak bir başarıyla geçmek", "🏳️‍🌈", "Everyone was nervous, but she managed to pass with flying colours.", "Herkes gergindi ama o parlak bir başarıyla geçmeyi başardı."],
      ["scrape through", "kıl payı geçmek", "😅", "I did not study much, but I managed to scrape through the test.", "Pek çalışmadım ama testi kıl payı geçmeyi başardım."],
      ["mock exam", "deneme sınavı", "📝", "The mock exam showed me which topics I still need to review.", "Deneme sınavı hâlâ hangi konuları tekrar etmem gerektiğini gösterdi."],
      ["open-book exam", "açık kitap sınavı", "📖", "An open-book exam tests understanding rather than memory.", "Açık kitap sınavı ezberi değil anlamayı ölçer."],
      ["case study", "vaka çalışması", "🗂️", "We analysed a case study of a company that failed after rapid growth.", "Hızlı büyümenin ardından batan bir şirketle ilgili bir vaka çalışmasını inceledik."],
      ["research paper", "araştırma makalesi", "📃", "His research paper on urban noise was cited by many experts.", "Kentsel gürültü üzerine yazdığı araştırma makalesine pek çok uzman atıf yaptı."],
      ["primary source", "birincil kaynak", "🗞️", "A diary from the war is a valuable primary source for historians.", "Savaştan kalma bir günlük tarihçiler için değerli bir birincil kaynaktır."],
      ["co-author", "ortak yazar", "✍️", "She was invited to co-author a chapter in a new textbook.", "Yeni bir ders kitabında bir bölümün ortak yazarı olmaya davet edildi."],
      ["manuscript", "el yazması, yayımlanmamış metin", "📜", "He sent the final manuscript to the publisher last week.", "Son metni geçen hafta yayınevine gönderdi."],
      ["accredited", "akredite, resmî olarak tanınmış", "✔️", "Make sure the online course is accredited before you pay.", "Ödeme yapmadan önce çevrim içi kursun akredite olduğundan emin ol."],
      ["dean", "dekan", "👔", "The dean announced new scholarships for students from low-income families.", "Dekan düşük gelirli ailelerden gelen öğrenciler için yeni burslar açıkladı."],
      ["teaching assistant", "asistan, ders yardımcısı", "🧑‍💼", "The teaching assistant marks our weekly problem sets.", "Ders asistanı haftalık problem setlerimizi notluyor."],
      ["fellowship", "araştırma bursu", "🔬", "He won a research fellowship to spend a year at a university abroad.", "Yurt dışındaki bir üniversitede bir yıl geçirmek için araştırma bursu kazandı."],
      ["bursary", "burs, öğrenim yardımı", "💷", "The college offers a small bursary to cover travel costs.", "Kolej ulaşım masraflarını karşılamak için küçük bir burs veriyor."],
      ["sabbatical", "akademik izin, araştırma izni", "🏖️", "The professor is on sabbatical this year, writing a new book.", "Profesör bu yıl araştırma iznine çıktı ve yeni bir kitap yazıyor."],
      ["symposium", "sempozyum", "🎙️", "The symposium brought together experts on artificial intelligence and law.", "Sempozyum yapay zekâ ve hukuk alanındaki uzmanları bir araya getirdi."],
      ["truancy", "okul kaçağı olma, devamsızlık", "🏃‍♂️", "The school introduced new measures to reduce truancy among teenagers.", "Okul gençler arasındaki devamsızlığı azaltmak için yeni önlemler aldı."],
      ["entrance exam", "giriş sınavı", "🚪", "Thousands of students take the university entrance exam every June.", "Her haziran binlerce öğrenci üniversite giriş sınavına giriyor."],
      ["eligible", "uygun, hak sahibi", "✅", "Only full-time students are eligible for this scholarship.", "Bu bursa yalnızca tam zamanlı öğrenciler başvurabilir."],
      ["cohort", "aynı dönemde okuyan grup, kohort", "👥", "Our cohort was the first to complete the new programme online.", "Bizim dönemimiz yeni programı çevrim içi tamamlayan ilk gruptu."],
      ["field of study", "çalışma alanı", "🌾", "Choosing a field of study at eighteen can feel overwhelming.", "On sekiz yaşında bir çalışma alanı seçmek bunaltıcı gelebilir."],
      ["specialize in", "uzmanlaşmak", "🎯", "She plans to specialize in child psychology after her degree.", "Diplomasından sonra çocuk psikolojisinde uzmanlaşmayı planlıyor."],
      ["academic year", "akademik yıl, öğretim yılı", "📅", "The academic year starts in late September in most countries.", "Çoğu ülkede akademik yıl eylül sonunda başlar."],
      ["critical thinking", "eleştirel düşünme", "🤔", "Good teachers encourage critical thinking instead of simple memorization.", "İyi öğretmenler basit ezber yerine eleştirel düşünmeyi teşvik eder."],
      ["lateral thinking", "yanal düşünme, alışılmadık çözüm yolu", "↪️", "This puzzle can only be solved with some lateral thinking.", "Bu bilmece ancak biraz yanal düşünmeyle çözülebilir."],
      ["study habits", "çalışma alışkanlıkları", "🗓️", "Good study habits matter more than long hours at the desk.", "İyi çalışma alışkanlıkları masa başında geçen uzun saatlerden daha önemlidir."],
      ["annotate", "not düşmek, açıklama eklemek", "🖊️", "I always annotate the margins when I read difficult texts.", "Zor metinleri okurken her zaman kenarlara not düşerim."],
      ["appendix", "ek, ekler bölümü", "📎", "The full questionnaire is included in the appendix of the thesis.", "Anketin tamamı tezin ekler bölümünde yer alıyor."],
      ["self-taught", "kendi kendini yetiştirmiş", "🧑‍💻", "He is a self-taught programmer who never went to university.", "Hiç üniversiteye gitmemiş, kendi kendini yetiştirmiş bir programcı."],
      ["mastery", "ustalık, tam hâkimiyet", "🥋", "True mastery of a language takes many years of practice.", "Bir dile gerçek anlamda hâkim olmak yıllarca pratik gerektirir."],
      ["competence", "yetkinlik", "🧰", "The course aims to build competence in basic data analysis.", "Kurs temel veri analizinde yetkinlik kazandırmayı amaçlıyor."],
      ["insightful", "derin görüşlü, ufuk açıcı", "💡", "Your comments on my draft were really insightful, thank you.", "Taslağıma yaptığın yorumlar gerçekten ufuk açıcıydı, teşekkürler."]
    ] },
  { id: "lib4c", title: "Felsefe, Etik ve İnanç", icon: "⚖️", cefr: "C1", desc: "Ahlak, inanç ve varoluş üzerine derin sohbetler için ileri düzey kelimeler.",
    words: [
      ["moral", "ahlaki", "🧭", "Doctors often face difficult moral questions about the end of life.", "Doktorlar yaşamın sonuyla ilgili zor ahlaki sorularla sık sık karşılaşır."],
      ["vice", "kötü huy, ahlaki zaaf", "🚬", "Gambling was his only vice, but it ruined his marriage.", "Kumar onun tek kötü huyuydu ama evliliğini mahvetti."],
      ["principle", "ilke", "📏", "I refuse to lie for anyone, it is a matter of principle.", "Kimse için yalan söylemem, bu bir ilke meselesi."],
      ["injustice", "adaletsizlik", "⛓️", "The film shows the injustice faced by workers in the factory.", "Film fabrikadaki işçilerin maruz kaldığı adaletsizliği gösteriyor."],
      ["fairness", "hakkaniyet, adil olma", "⚖️", "Children have a strong sense of fairness from a very young age.", "Çocuklar çok küçük yaştan itibaren güçlü bir adalet duygusuna sahiptir."],
      ["fate", "kader, yazgı", "🎲", "She believes it was fate that they met on that train.", "O trende tanışmalarının kader olduğuna inanıyor."],
      ["destiny", "alın yazısı, kader", "🌌", "He felt that becoming a teacher was his true destiny.", "Öğretmen olmanın gerçek kaderi olduğunu hissetti."],
      ["karma", "karma, ettiğini bulma", "☯️", "He cheated his partners and lost everything, some would call it karma.", "Ortaklarını dolandırdı ve her şeyini kaybetti, bazıları buna karma derdi."],
      ["existential", "varoluşsal", "🌀", "Turning forty gave him a kind of existential crisis.", "Kırk yaşına girmek ona bir tür varoluşsal kriz yaşattı."],
      ["spirituality", "maneviyat", "🕯️", "For her, spirituality is about inner growth rather than religion.", "Onun için maneviyat dinden çok içsel gelişimle ilgilidir."],
      ["faith", "inanç, iman", "🙏", "His faith gave him strength during the long illness.", "İnancı uzun hastalığı boyunca ona güç verdi."],
      ["atheist", "ateist", "🔭", "My brother is an atheist, but he enjoys visiting old churches.", "Ağabeyim ateist ama eski kiliseleri gezmekten hoşlanıyor."],
      ["agnostic", "agnostik, bilinemezci", "❔", "She describes herself as agnostic because nobody can prove either side.", "Kimse iki taraftan birini kanıtlayamadığı için kendini agnostik olarak tanımlıyor."],
      ["sacred", "kutsal", "⛰️", "The mountain is sacred to the people who live in the valley.", "Dağ vadide yaşayan insanlar için kutsaldır."],
      ["divine", "ilahi, tanrısal", "✨", "In many old stories, storms were seen as divine punishment.", "Pek çok eski hikâyede fırtınalar ilahi ceza olarak görülürdü."],
      ["worship", "ibadet etmek, tapmak", "🛐", "People of different faiths worship in the same old building.", "Farklı inançlardan insanlar aynı eski binada ibadet ediyor."],
      ["prayer", "dua", "📿", "My grandmother says a short prayer before every meal.", "Büyükannem her yemekten önce kısa bir dua okur."],
      ["pilgrimage", "hac, kutsal yolculuk", "🚶‍♀️", "Every year, millions of people make a pilgrimage to holy sites.", "Her yıl milyonlarca insan kutsal mekânlara hac yolculuğu yapar."],
      ["sin", "günah", "🍎", "In many traditions, lying is considered a sin.", "Pek çok gelenekte yalan söylemek günah sayılır."],
      ["salvation", "kurtuluş", "🛟", "The novel's hero searches for salvation after a life of crime.", "Romanın kahramanı suçla geçen bir hayatın ardından kurtuluş arıyor."],
      ["afterlife", "öteki dünya, ahiret", "🌈", "Ancient Egyptians buried their dead with objects for the afterlife.", "Eski Mısırlılar ölülerini öteki dünya için eşyalarla birlikte gömerdi."],
      ["eternity", "sonsuzluk, ebediyet", "♾️", "Waiting for the test results felt like an eternity.", "Test sonuçlarını beklemek sonsuzluk gibi geldi."],
      ["mortal", "ölümlü", "⏳", "Philosophers remind us that we are mortal and our time is limited.", "Filozoflar bize ölümlü olduğumuzu ve zamanımızın sınırlı olduğunu hatırlatır."],
      ["immortal", "ölümsüz", "🧛", "If you were immortal, would your life still feel meaningful?", "Ölümsüz olsaydın hayatın yine de anlamlı gelir miydi?"],
      ["reincarnation", "reenkarnasyon, ruh göçü", "🔄", "Some religions teach that reincarnation continues until the soul is free.", "Bazı dinler ruh özgürleşene kadar reenkarnasyonun sürdüğünü öğretir."],
      ["enlightenment", "aydınlanma", "💡", "The monk spent decades in search of enlightenment.", "Keşiş onlarca yılı aydınlanma arayışıyla geçirdi."],
      ["logic", "mantık", "🧮", "Your logic is clear, but I do not agree with your first assumption.", "Mantığın açık ama ilk varsayımına katılmıyorum."],
      ["rational", "akılcı, rasyonel", "🧠", "Humans like to think they are rational, but emotions often decide.", "İnsanlar akılcı olduklarını düşünmeyi sever ama çoğu zaman duygular karar verir."],
      ["irrational", "akıl dışı, mantıksız", "🌪️", "Her fear of flying is irrational, and she knows it.", "Uçma korkusu mantıksız ve o da bunu biliyor."],
      ["contradict", "çelişmek, yalanlamak", "↔️", "His actions contradict everything he says about honesty.", "Davranışları dürüstlük hakkında söylediği her şeyle çelişiyor."],
      ["absolute", "mutlak", "🔷", "Some thinkers argue that there is no absolute truth.", "Bazı düşünürler mutlak bir gerçeğin olmadığını savunur."],
      ["universal", "evrensel", "🌐", "Is kindness a universal value or does it depend on culture?", "İyilik evrensel bir değer mi yoksa kültüre mi bağlı?"],
      ["dogma", "dogma, sorgulanmaz inanç", "🧱", "Science should question dogma instead of simply accepting it.", "Bilim dogmayı basitçe kabul etmek yerine sorgulamalı."],
      ["doctrine", "öğreti, doktrin", "📖", "The church changed its doctrine on several issues over the centuries.", "Kilise yüzyıllar içinde birçok konudaki öğretisini değiştirdi."],
      ["ideology", "ideoloji", "🚩", "Political ideology should not decide which scientific facts we accept.", "Hangi bilimsel gerçekleri kabul edeceğimize siyasi ideoloji karar vermemeli."],
      ["sceptical", "kuşkucu, şüpheci", "🤨", "I am sceptical about any diet that promises quick results.", "Hızlı sonuç vaat eden her diyete şüpheyle yaklaşırım."],
      ["certainty", "kesinlik", "📌", "We can never know the future with complete certainty.", "Geleceği asla tam bir kesinlikle bilemeyiz."],
      ["empiricism", "deneycilik, ampirizm", "🔬", "Empiricism holds that knowledge comes mainly from experience.", "Deneycilik bilginin esas olarak deneyimden geldiğini savunur."],
      ["stoic", "metanetli, sabırlı, stoacı", "🗿", "He remained stoic throughout the trial and never showed emotion.", "Duruşma boyunca metanetini korudu ve hiç duygu göstermedi."],
      ["hedonism", "hazcılık, hedonizm", "🍷", "A life of pure hedonism rarely leads to lasting happiness.", "Saf hazcılıkla geçen bir hayat nadiren kalıcı mutluluğa götürür."],
      ["humanism", "hümanizm, insancılık", "🧑‍🤝‍🧑", "Humanism places human reason and dignity at the centre of ethics.", "Hümanizm insan aklını ve onurunu etiğin merkezine koyar."],
      ["secular", "laik, dünyevi", "🏛️", "The country has a secular constitution that separates religion and state.", "Ülkenin din ve devleti ayıran laik bir anayasası var."],
      ["tolerate", "hoş görmek, katlanmak", "🤲", "A healthy society must tolerate opinions it strongly dislikes.", "Sağlıklı bir toplum hiç hoşlanmadığı görüşlere de hoşgörü göstermelidir."],
      ["obligation", "yükümlülük", "📜", "Do rich countries have a moral obligation to help poorer ones?", "Zengin ülkelerin daha yoksul ülkelere yardım etme gibi ahlaki bir yükümlülüğü var mı?"],
      ["duty", "görev, ödev", "🎖️", "She felt it was her duty to report the dangerous working conditions.", "Tehlikeli çalışma koşullarını bildirmenin görevi olduğunu hissetti."],
      ["reflection", "derin düşünme, tefekkür", "🪞", "After much reflection, he decided to leave his well-paid job.", "Uzun uzun düşündükten sonra iyi maaşlı işinden ayrılmaya karar verdi."],
      ["euthanasia", "ötanazi", "🏥", "Euthanasia remains one of the most divisive ethical debates today.", "Ötanazi bugün hâlâ en çok bölen etik tartışmalardan biri."],
      ["hypocrite", "ikiyüzlü", "🎭", "He calls others lazy, which makes him a hypocrite.", "Başkalarına tembel diyor, bu da onu ikiyüzlü yapıyor."],
      ["deceive", "aldatmak, kandırmak", "🃏", "The company tried to deceive customers with misleading labels.", "Şirket yanıltıcı etiketlerle müşterileri kandırmaya çalıştı."],
      ["deception", "aldatma, hile", "🕸️", "The whole plan was built on deception from the very start.", "Bütün plan en başından beri hileye dayanıyordu."],
      ["betray", "ihanet etmek", "🗡️", "I would never betray a friend who trusted me with a secret.", "Bana bir sır emanet eden bir arkadaşa asla ihanet etmem."],
      ["loyalty", "sadakat, bağlılık", "🐕", "Is loyalty to your company more important than honesty?", "Şirketine sadakat dürüstlükten daha mı önemli?"],
      ["mercy", "merhamet", "🕊️", "The judge showed mercy because the young man was truly sorry.", "Genç adam gerçekten pişman olduğu için yargıç merhamet gösterdi."],
      ["forgiveness", "affetme, bağışlama", "💐", "Forgiveness does not mean forgetting what happened to you.", "Affetmek başına gelenleri unutmak anlamına gelmez."],
      ["redemption", "kefaret, günahtan arınma", "🌅", "The story is about a former thief and his long road to redemption.", "Hikâye eski bir hırsızı ve onun arınmaya giden uzun yolunu anlatıyor."],
      ["repent", "tövbe etmek, pişman olmak", "😔", "He began to repent for the harm he had caused his family.", "Ailesine verdiği zarar için tövbe etmeye başladı."],
      ["humility", "alçakgönüllülük", "🌾", "True wisdom often comes with a deep sense of humility.", "Gerçek bilgelik çoğu zaman derin bir alçakgönüllülükle gelir."],
      ["arrogance", "kibir", "👑", "His arrogance made it impossible for him to learn from others.", "Kibri başkalarından öğrenmesini imkânsız kıldı."],
      ["greed", "açgözlülük, hırs", "🤑", "Many believe greed was the main cause of the financial crisis.", "Pek çok kişi finansal krizin ana nedeninin açgözlülük olduğuna inanıyor."],
      ["superstitious", "batıl inançlı", "🐈‍⬛", "My aunt is so superstitious that she never opens umbrellas indoors.", "Teyzem o kadar batıl inançlı ki şemsiyeyi asla evin içinde açmaz."],
      ["miracle", "mucize", "🌟", "The doctors said his recovery was nothing short of a miracle.", "Doktorlar iyileşmesinin tam anlamıyla bir mucize olduğunu söyledi."],
      ["prophecy", "kehanet", "🔮", "According to the old prophecy, the city would fall in a single night.", "Eski kehanete göre şehir tek bir gecede düşecekti."],
      ["myth", "mit, efsane, yaygın yanlış inanış", "🐉", "It is a myth that we only use ten percent of our brains.", "Beynimizin yalnızca yüzde onunu kullandığımız yaygın bir yanlış inanıştır."],
      ["cult", "tarikat benzeri grup, kült", "🕯️", "She left the cult after realizing the leader was controlling her life.", "Liderin hayatını kontrol ettiğini fark edince kült gruptan ayrıldı."],
      ["convert", "din değiştirmek", "🔁", "He decided to convert after years of studying different religions.", "Yıllarca farklı dinleri inceledikten sonra din değiştirmeye karar verdi."],
      ["devout", "dindar, sofu", "📿", "Her parents are devout and never miss a religious holiday.", "Anne babası dindardır ve hiçbir dinî bayramı kaçırmaz."],
      ["fundamentalist", "köktendinci", "📕", "Fundamentalist groups often reject any modern reading of old texts.", "Köktendinci gruplar eski metinlerin modern yorumlarını çoğu zaman reddeder."],
      ["blessing", "nimet, lütuf", "🌤️", "Losing that job turned out to be a blessing in the end.", "O işi kaybetmek sonunda bir nimet çıktı."],
      ["curse", "lanet", "🧿", "Some villagers believed the old house was under a curse.", "Bazı köylüler eski evin lanetli olduğuna inanıyordu."],
      ["omen", "alamet, uğur ya da uğursuzluk işareti", "🦅", "A black cat crossing your path is seen as a bad omen in some cultures.", "Bazı kültürlerde yolunuzdan kara kedi geçmesi kötüye alamet sayılır."],
      ["transcendent", "aşkın, dünyevi olanı aşan", "🌠", "Many people describe hearing great music as a transcendent experience.", "Pek çok kişi harika bir müzik dinlemeyi dünyevi olanı aşan bir deneyim olarak tanımlar."],
      ["unethical", "etik dışı", "🚫", "Testing cosmetics on animals is considered unethical by many consumers.", "Kozmetikleri hayvanlar üzerinde test etmek pek çok tüketiciye göre etik dışıdır."],
      ["immoral", "ahlaksız, ahlaka aykırı", "⛔", "Is it immoral to break a promise to save someone's life?", "Birinin hayatını kurtarmak için bir sözü bozmak ahlaka aykırı mı?"],
      ["amoral", "ahlak dışı, ahlakla ilgisi olmayan", "🤖", "A machine is amoral, it simply follows the rules we give it.", "Bir makinenin ahlakla ilgisi yoktur, sadece ona verdiğimiz kuralları uygular."],
      ["righteous", "doğru, haklı, erdemli", "🛡️", "She felt a righteous anger when she saw the animals being mistreated.", "Hayvanlara kötü davranıldığını görünce haklı bir öfke duydu."],
      ["self-righteous", "kendini ahlakça üstün gören", "☝️", "Nobody enjoys listening to his self-righteous speeches about healthy eating.", "Kimse onun sağlıklı beslenme hakkındaki kendini beğenmiş nutuklarını dinlemekten hoşlanmıyor."],
      ["virtuous", "erdemli", "🌼", "In the old tale, the virtuous daughter is finally rewarded.", "Eski masalda erdemli kız sonunda ödüllendirilir."],
      ["wicked", "kötü, zalim", "🦹", "The wicked king in the story taxed the poor until they starved.", "Hikâyedeki zalim kral yoksulları açlıktan ölene kadar vergilendirdi."],
      ["benevolent", "iyiliksever, hayırsever", "😇", "The town was supported for years by a benevolent local businessman.", "Kasaba yıllarca hayırsever bir yerel iş insanı tarafından desteklendi."],
      ["malevolent", "kötü niyetli", "😈", "The film's malevolent computer slowly takes control of the ship.", "Filmdeki kötü niyetli bilgisayar yavaş yavaş geminin kontrolünü ele geçirir."],
      ["sincerity", "içtenlik, samimiyet", "💗", "Nobody in the room doubted the sincerity of her apology.", "Odadaki hiç kimse özrünün içtenliğinden şüphe etmedi."],
      ["authenticity", "sahicilik, özgünlük", "🪪", "Young voters say they value authenticity more than polished speeches.", "Genç seçmenler cilalı konuşmalardan çok sahiciliğe değer verdiklerini söylüyor."],
      ["utopia", "ütopya", "🏝️", "Every utopia looks perfect on paper but fails in real life.", "Her ütopya kâğıt üzerinde mükemmel görünür ama gerçek hayatta başarısız olur."],
      ["dystopia", "distopya", "🏚️", "The novel describes a dystopia where every thought is monitored.", "Roman her düşüncenin izlendiği bir distopyayı anlatıyor."],
      ["idealism", "idealizm, ülkücülük", "🌈", "His youthful idealism slowly faded after years in politics.", "Gençlik idealizmi siyasette geçen yıllardan sonra yavaş yavaş söndü."],
      ["pragmatic", "pragmatik, gerçekçi", "🔧", "We need a pragmatic solution, not a perfect one.", "Mükemmel değil pragmatik bir çözüme ihtiyacımız var."],
      ["cynicism", "kinizm, insanlara güvensizlik", "😏", "Public cynicism about politicians has grown in recent years.", "Son yıllarda kamuoyunun politikacılara duyduğu güvensizlik arttı."],
      ["materialism", "maddecilik, materyalizm", "🛒", "Critics say modern materialism leaves people feeling empty inside.", "Eleştirmenler modern maddeciliğin insanları içten içe boş hissettirdiğini söylüyor."],
      ["consumerism", "tüketim kültürü", "🛍️", "The documentary questions the consumerism that drives holiday shopping.", "Belgesel bayram alışverişini körükleyen tüketim kültürünü sorguluyor."],
      ["absurdity", "saçmalık, absürtlük", "🤡", "He laughed at the absurdity of filling in ten forms for one signature.", "Tek bir imza için on form doldurmanın saçmalığına güldü."],
      ["legacy", "miras, geride bırakılan iz", "🏺", "What kind of legacy do you want to leave for the next generation?", "Bir sonraki nesle nasıl bir iz bırakmak istersin?"],
      ["justification", "gerekçe, haklı çıkarma", "📝", "There is no moral justification for treating people this way.", "İnsanlara bu şekilde davranmanın hiçbir ahlaki gerekçesi yok."],
      ["ceremony", "tören", "🎊", "The wedding ceremony mixed traditions from both families' religions.", "Düğün töreni iki ailenin dinlerinden gelen gelenekleri harmanladı."],
      ["prophet", "peygamber", "📜", "Stories about the prophet are taught to children in many countries.", "Peygamberle ilgili hikâyeler pek çok ülkede çocuklara öğretilir."],
      ["holy", "kutsal, mukaddes", "🕍", "The city is considered holy by three major religions.", "Şehir üç büyük din tarafından kutsal kabul ediliyor."],
      ["heaven", "cennet", "☁️", "My little niece asked me if dogs go to heaven.", "Küçük yeğenim köpeklerin cennete gidip gitmediğini sordu."],
      ["eternal", "ebedî, sonsuz", "🔥", "Many myths tell of heroes who searched for eternal life.", "Pek çok mit sonsuz yaşamı arayan kahramanları anlatır."],
      ["believer", "inanan kişi, mümin", "🙌", "She is a firm believer in giving people a second chance.", "İnsanlara ikinci bir şans vermeye yürekten inanan biri."],
      ["sect", "mezhep, tarikat", "🔱", "The small sect broke away from the main church in the 1600s.", "Küçük mezhep 1600'lerde ana kiliseden ayrıldı."],
      ["play devil's advocate", "şeytanın avukatlığını yapmak", "😼", "Let me play devil's advocate and defend the opposite view for a moment.", "İzin ver bir anlığına şeytanın avukatlığını yapıp karşı görüşü savunayım."],
      ["the end justifies the means", "amaca giden her yol mubahtır", "🏁", "He truly believes that the end justifies the means in business.", "İş dünyasında amaca giden her yolun mubah olduğuna gerçekten inanıyor."],
      ["code of conduct", "davranış kuralları", "📘", "All employees must sign the company's code of conduct.", "Tüm çalışanlar şirketin davranış kurallarını imzalamak zorunda."],
      ["conscientious objector", "vicdani retçi", "✋", "He registered as a conscientious objector and refused to carry a weapon.", "Vicdani retçi olarak kayıt yaptırdı ve silah taşımayı reddetti."],
      ["whistleblower", "usulsüzlüğü ifşa eden kişi", "📣", "The whistleblower revealed that the factory was polluting the river.", "Usulsüzlüğü ifşa eden kişi fabrikanın nehri kirlettiğini ortaya çıkardı."],
      ["meaning of life", "hayatın anlamı", "🌌", "We stayed up all night talking about the meaning of life.", "Bütün gece uyumadan hayatın anlamı hakkında konuştuk."],
      ["inner peace", "iç huzur", "🧘", "She found inner peace only after she stopped comparing herself to others.", "Ancak kendini başkalarıyla kıyaslamayı bırakınca iç huzuru buldu."],
      ["good and evil", "iyi ve kötü", "☯️", "Most fairy tales are built around a clear battle between good and evil.", "Çoğu masal iyi ile kötü arasındaki net bir savaş üzerine kuruludur."],
      ["right and wrong", "doğru ile yanlış", "🧭", "Parents try to teach their children the difference between right and wrong.", "Ebeveynler çocuklarına doğru ile yanlış arasındaki farkı öğretmeye çalışır."],
      ["golden rule", "altın kural", "🥇", "The golden rule says you should treat others as you want to be treated.", "Altın kural başkalarına kendine nasıl davranılmasını istiyorsan öyle davranman gerektiğini söyler."],
      ["benefit of the doubt", "şüpheyi lehine yorumlama", "🤝", "He is new here, so let us give him the benefit of the doubt.", "O burada yeni, o yüzden şüpheyi onun lehine yorumlayalım."]
    ] }
);
