(window.LIBRARY = window.LIBRARY || []).push(
  { id: "lib3a", title: "Bilim ve Araştırma", icon: "🔬", cefr: "C1", desc: "Akademik makaleleri, deneyleri ve bilimsel tartışmaları rahatça takip etmek için ileri düzey kelimeler.",
    words: [
      ["replicate", "tekrarlamak, yinelemek", "🔁", "Other teams failed to replicate the results of the original study.", "Diğer ekipler özgün çalışmanın sonuçlarını tekrarlamayı başaramadı."],
      ["replication", "tekrarlama, yineleme", "", "Independent replication is the best way to test a surprising claim.", "Bağımsız tekrarlama, şaşırtıcı bir iddiayı sınamanın en iyi yoludur."],
      ["reproducible", "tekrarlanabilir", "", "Good science depends on results that are reproducible in other labs.", "İyi bilim, başka laboratuvarlarda tekrarlanabilen sonuçlara dayanır."],
      ["anomaly", "anormallik, sapma", "", "The researchers noticed a strange anomaly in the temperature readings.", "Araştırmacılar sıcaklık ölçümlerinde tuhaf bir anormallik fark etti."],
      ["calibrate", "ayarlamak, kalibre etmek", "", "You need to calibrate the scale before every new measurement.", "Her yeni ölçümden önce teraziyi kalibre etmen gerekiyor."],
      ["quantify", "sayısal olarak ifade etmek, ölçmek", "", "It is difficult to quantify the impact of stress on creativity.", "Stresin yaratıcılık üzerindeki etkisini sayısal olarak ölçmek zordur."],
      ["quantitative", "nicel", "", "The project combines quantitative data with in-depth interviews.", "Proje nicel verileri derinlemesine görüşmelerle birleştiriyor."],
      ["qualitative", "nitel", "", "Qualitative research helps us understand why people make certain choices.", "Nitel araştırma, insanların neden belirli seçimler yaptığını anlamamıza yardım eder."],
      ["infer", "çıkarım yapmak, sonuç çıkarmak", "", "From these patterns we can infer that the species migrates at night.", "Bu örüntülerden türün geceleri göç ettiği sonucunu çıkarabiliriz."],
      ["inference", "çıkarım", "", "That inference is reasonable, but it still needs more evidence.", "Bu çıkarım makul ama hâlâ daha fazla kanıta ihtiyaç duyuyor."],
      ["deduction", "tümdengelim, çıkarsama", "", "Her conclusion was based on careful deduction rather than guesswork.", "Vardığı sonuç tahmine değil dikkatli bir çıkarsamaya dayanıyordu."],
      ["postulate", "varsaymak, öne sürmek", "", "Some scientists postulate that life could exist beneath the ice.", "Bazı bilim insanları buzun altında yaşam olabileceğini öne sürüyor."],
      ["paradigm shift", "paradigma değişimi, köklü bakış değişimi", "", "The discovery caused a paradigm shift in how we think about memory.", "Bu keşif, belleği nasıl düşündüğümüz konusunda köklü bir paradigma değişimine yol açtı."],
      ["falsify", "yanlışlamak, tahrif etmek", "", "A good theory makes predictions that experiments could falsify.", "İyi bir teori, deneylerin yanlışlayabileceği tahminlerde bulunur."],
      ["validate", "doğrulamak, geçerliliğini kanıtlamak", "✅", "We used a second method to validate the initial measurements.", "İlk ölçümleri doğrulamak için ikinci bir yöntem kullandık."],
      ["validity", "geçerlilik", "", "Critics questioned the validity of the questionnaire used in the study.", "Eleştirmenler çalışmada kullanılan anketin geçerliliğini sorguladı."],
      ["reliability", "güvenilirlik", "", "The reliability of the test improved after we changed the questions.", "Soruları değiştirdikten sonra testin güvenilirliği arttı."],
      ["rigour", "titizlik, kesinlik", "", "The paper was praised for its rigour and clear writing style.", "Makale titizliği ve açık yazım tarzı nedeniyle övüldü."],
      ["systematic", "sistematik, düzenli", "", "They carried out a systematic review of more than two hundred papers.", "İki yüzden fazla makalenin sistematik bir incelemesini yaptılar."],
      ["longitudinal", "uzunlamasına, uzun süreli izlemeye dayalı", "", "This longitudinal study followed the same children for twenty years.", "Bu uzun süreli çalışma aynı çocukları yirmi yıl boyunca izledi."],
      ["cohort", "kohort, aynı özellikteki grup", "", "The first cohort of participants joined the programme in 2019.", "Katılımcıların ilk kohortu programa 2019'da katıldı."],
      ["control group", "kontrol grubu", "", "The control group received no treatment during the eight weeks.", "Kontrol grubu sekiz hafta boyunca hiçbir tedavi almadı."],
      ["placebo", "plasebo, etkisiz ilaç", "💊", "Half of the volunteers were given a placebo instead of the real drug.", "Gönüllülerin yarısına gerçek ilaç yerine plasebo verildi."],
      ["double-blind", "çift kör", "", "In a double-blind trial, neither patients nor doctors know who gets the drug.", "Çift kör bir denemede ne hastalar ne de doktorlar ilacı kimin aldığını bilir."],
      ["margin of error", "hata payı", "", "The poll has a margin of error of three percent.", "Anketin yüzde üçlük bir hata payı var."],
      ["statistically significant", "istatistiksel olarak anlamlı", "", "The difference between the two groups was not statistically significant.", "İki grup arasındaki fark istatistiksel olarak anlamlı değildi."],
      ["dataset", "veri kümesi", "", "The team made the entire dataset available to other researchers.", "Ekip tüm veri kümesini diğer araştırmacıların kullanımına açtı."],
      ["raw data", "ham veri", "", "Always keep a copy of the raw data before you start cleaning it.", "Temizlemeye başlamadan önce ham verinin bir kopyasını mutlaka sakla."],
      ["skewed", "çarpık, yanlı", "", "The results were skewed because most participants were university students.", "Katılımcıların çoğu üniversite öğrencisi olduğu için sonuçlar çarpıktı."],
      ["conjecture", "varsayım, tahmin", "", "Without solid evidence, his theory remains pure conjecture.", "Sağlam kanıt olmadan onun teorisi salt bir varsayım olarak kalıyor."],
      ["speculate", "tahminde bulunmak, spekülasyon yapmak", "", "It is too early to speculate about the cause of the decline.", "Düşüşün nedeni hakkında tahminde bulunmak için çok erken."],
      ["speculative", "spekülatif, varsayıma dayalı", "", "The final chapter of the book is more speculative than scientific.", "Kitabın son bölümü bilimsel olmaktan çok varsayıma dayalı."],
      ["implausible", "akla yatkın olmayan, inandırıcı olmayan", "", "The explanation sounded implausible to most experts in the field.", "Açıklama alandaki uzmanların çoğuna inandırıcı gelmedi."],
      ["corroborate", "doğrulamak, desteklemek", "", "Satellite images corroborate the reports of rapid ice loss.", "Uydu görüntüleri hızlı buz kaybı raporlarını doğruluyor."],
      ["refute", "çürütmek", "", "New measurements seem to refute the idea that the lake is shrinking.", "Yeni ölçümler gölün küçüldüğü fikrini çürütüyor gibi görünüyor."],
      ["debunk", "asılsız olduğunu göstermek, çürütmek", "", "Scientists worked hard to debunk the myth about vaccines and autism.", "Bilim insanları aşılar ve otizm hakkındaki efsanenin asılsızlığını göstermek için çok çalıştı."],
      ["disprove", "aksini kanıtlamak, çürütmek", "", "One well designed experiment can disprove a popular theory.", "İyi tasarlanmış tek bir deney popüler bir teoriyi çürütebilir."],
      ["contradict", "çelişmek, ters düşmek", "", "These findings contradict what we believed about sleep and memory.", "Bu bulgular uyku ve bellek hakkında inandıklarımızla çelişiyor."],
      ["scrutiny", "titiz inceleme, mercek altı", "🔍", "Every new claim in medicine should face careful scrutiny.", "Tıptaki her yeni iddia dikkatli bir incelemeden geçmelidir."],
      ["scrutinize", "titizlikle incelemek", "", "Reviewers will scrutinize every table and graph in your paper.", "Hakemler makalendeki her tabloyu ve grafiği titizlikle inceleyecek."],
      ["fieldwork", "saha çalışması", "🧭", "She spent six months doing fieldwork in remote mountain villages.", "Altı ayını ücra dağ köylerinde saha çalışması yaparak geçirdi."],
      ["specimen", "numune, örnek", "", "Each specimen was labelled and stored at a low temperature.", "Her numune etiketlendi ve düşük sıcaklıkta saklandı."],
      ["telescope", "teleskop", "🔭", "The new telescope can detect galaxies that formed billions of years ago.", "Yeni teleskop milyarlarca yıl önce oluşmuş galaksileri tespit edebiliyor."],
      ["molecule", "molekül", "", "A water molecule consists of two hydrogen atoms and one oxygen atom.", "Bir su molekülü iki hidrojen ve bir oksijen atomundan oluşur."],
      ["particle", "parçacık", "", "Physicists are searching for a particle that could explain dark matter.", "Fizikçiler karanlık maddeyi açıklayabilecek bir parçacığı arıyor."],
      ["genome", "genom", "🧬", "Reading the entire human genome once took more than a decade.", "Tüm insan genomunu okumak bir zamanlar on yıldan fazla sürüyordu."],
      ["mutation", "mutasyon", "", "A single mutation can change how a protein behaves in the body.", "Tek bir mutasyon bir proteinin vücuttaki davranışını değiştirebilir."],
      ["organism", "organizma", "", "This tiny organism can survive in boiling water and freezing ice.", "Bu küçücük organizma kaynar suda da donmuş buzda da hayatta kalabiliyor."],
      ["evolve", "evrimleşmek, gelişmek", "", "Bacteria can evolve resistance to a drug in just a few years.", "Bakteriler yalnızca birkaç yılda bir ilaca karşı direnç geliştirebilir."],
      ["phenomena", "olgular, fenomenler", "", "The northern lights are among the most beautiful natural phenomena.", "Kuzey ışıkları en güzel doğal olgular arasında yer alır."],
      ["parameter", "parametre, değişken ölçüt", "", "We changed one parameter at a time to see its effect.", "Etkisini görmek için her seferinde tek bir parametreyi değiştirdik."],
      ["threshold", "eşik", "", "Pain becomes noticeable once the signal passes a certain threshold.", "Sinyal belirli bir eşiği geçtiğinde ağrı fark edilir hâle gelir."],
      ["magnitude", "büyüklük, şiddet", "", "Nobody expected an earthquake of that magnitude in the region.", "Kimse bölgede o büyüklükte bir deprem beklemiyordu."],
      ["trajectory", "yörünge, gidişat", "", "Engineers calculated the exact trajectory of the falling satellite.", "Mühendisler düşen uydunun tam yörüngesini hesapladı."],
      ["simulation", "simülasyon, benzetim", "💻", "The computer simulation showed how the virus might spread in a city.", "Bilgisayar simülasyonu virüsün bir şehirde nasıl yayılabileceğini gösterdi."],
      ["pilot study", "ön çalışma, pilot çalışma", "", "A small pilot study helped us fix problems before the main experiment.", "Küçük bir pilot çalışma, asıl deneyden önce sorunları gidermemize yardım etti."],
      ["preliminary", "ön, başlangıç niteliğinde", "", "The preliminary results look promising, but we need more data.", "Ön sonuçlar umut verici görünüyor ama daha fazla veriye ihtiyacımız var."],
      ["tentative", "geçici, kesinleşmemiş", "", "The authors offer only a tentative explanation for the effect.", "Yazarlar bu etki için yalnızca geçici bir açıklama sunuyor."],
      ["interim", "ara, geçici", "", "An interim report will be published halfway through the project.", "Projenin yarısında bir ara rapor yayımlanacak."],
      ["conclusive", "kesin, kesin sonuç veren", "", "There is still no conclusive proof that the drug works.", "İlacın işe yaradığına dair hâlâ kesin bir kanıt yok."],
      ["inconclusive", "sonuçsuz, kesin sonuca varmayan", "", "The first round of tests was inconclusive, so we repeated them.", "İlk test turu kesin sonuç vermedi, bu yüzden testleri tekrarladık."],
      ["yield", "sonuç vermek, ortaya koymak", "", "The new method may yield more accurate estimates of population size.", "Yeni yöntem nüfus büyüklüğü için daha doğru tahminler ortaya koyabilir."],
      ["derive", "türetmek, elde etmek", "", "Many modern medicines derive from compounds found in plants.", "Birçok modern ilaç bitkilerde bulunan bileşiklerden türetilir."],
      ["attribute to", "bir şeye bağlamak, atfetmek", "", "Researchers attribute the rise in allergies to changes in diet.", "Araştırmacılar alerjilerdeki artışı beslenmedeki değişikliklere bağlıyor."],
      ["account for", "açıklamak, oluşturmak", "", "Genetics may account for about half of the differences in height.", "Boydaki farklılıkların yaklaşık yarısını genetik açıklayabilir."],
      ["shed light on", "aydınlatmak, ışık tutmak", "💡", "This discovery could shed light on how early humans communicated.", "Bu keşif ilk insanların nasıl iletişim kurduğuna ışık tutabilir."],
      ["carry out", "yürütmek, gerçekleştirmek", "", "The students will carry out the experiment under supervision.", "Öğrenciler deneyi gözetim altında gerçekleştirecek."],
      ["break new ground", "çığır açmak, yeni bir alana girmek", "", "Her work on bird navigation continues to break new ground.", "Kuşların yön bulması üzerine yaptığı çalışmalar çığır açmaya devam ediyor."],
      ["state-of-the-art", "son teknoloji, en ileri", "", "The university opened a state-of-the-art laboratory last spring.", "Üniversite geçen bahar son teknoloji bir laboratuvar açtı."],
      ["pioneering", "öncü, çığır açan", "", "He is known for his pioneering research on the deep ocean.", "Derin okyanus üzerine yaptığı öncü araştırmalarla tanınıyor."],
      ["fabricate", "uydurmak, sahte veri üretmek", "", "The scientist lost his job after he was found to fabricate data.", "Bilim insanı veri uydurduğu ortaya çıkınca işini kaybetti."],
      ["retract", "geri çekmek", "", "The journal had to retract the article because of serious errors.", "Dergi ciddi hatalar nedeniyle makaleyi geri çekmek zorunda kaldı."],
      ["ethics committee", "etik kurul", "", "The ethics committee must approve every study involving human participants.", "Etik kurul, insan katılımcı içeren her çalışmayı onaylamak zorundadır."],
      ["informed consent", "bilgilendirilmiş onam", "", "All participants gave informed consent before the interviews began.", "Tüm katılımcılar görüşmeler başlamadan önce bilgilendirilmiş onam verdi."],
      ["funding", "fon, finansman", "💰", "The lab may close next year unless it finds new funding.", "Laboratuvar yeni finansman bulamazsa gelecek yıl kapanabilir."],
      ["grant", "hibe, burs", "", "She received a generous grant to study coral reefs in the Pacific.", "Pasifik'teki mercan resiflerini incelemek için cömert bir hibe aldı."],
      ["academia", "akademi dünyası", "🎓", "After ten years in academia, he moved to a private research company.", "Akademi dünyasında on yıl geçirdikten sonra özel bir araştırma şirketine geçti."],
      ["scholarly", "akademik, bilimsel", "", "The library gives students access to thousands of scholarly articles.", "Kütüphane öğrencilere binlerce akademik makaleye erişim sağlıyor."],
      ["discipline", "disiplin, bilim dalı", "", "Psychology is a young discipline compared to physics or chemistry.", "Psikoloji fizik ya da kimyaya kıyasla genç bir bilim dalıdır."],
      ["interdisciplinary", "disiplinlerarası", "", "Climate research requires an interdisciplinary approach with many different experts.", "İklim araştırması birçok farklı uzmanın yer aldığı disiplinlerarası bir yaklaşım gerektirir."],
      ["investigation", "inceleme, araştırma, soruşturma", "", "An independent investigation found several problems with the original data.", "Bağımsız bir inceleme, özgün verilerde birkaç sorun buldu."],
      ["assess", "değerlendirmek", "", "We need better tools to assess the long-term effects of the policy.", "Politikanın uzun vadeli etkilerini değerlendirmek için daha iyi araçlara ihtiyacımız var."],
      ["benchmark", "ölçüt, karşılaştırma noktası", "", "These scores will serve as a benchmark for future studies.", "Bu puanlar gelecekteki çalışmalar için bir karşılaştırma ölçütü olacak."],
      ["metric", "ölçüt, ölçüm değeri", "📏", "Citation count is a common but imperfect metric of research quality.", "Atıf sayısı araştırma kalitesinin yaygın ama kusurlu bir ölçütüdür."],
      ["indicator", "gösterge", "", "Heart rate is a useful indicator of how stressed a person feels.", "Kalp atış hızı bir kişinin ne kadar stresli hissettiğinin yararlı bir göstergesidir."],
      ["proportion", "oran, pay", "", "A large proportion of the samples contained tiny pieces of plastic.", "Numunelerin büyük bir kısmı küçük plastik parçaları içeriyordu."],
      ["ratio", "oran", "", "The ratio of men to women in the study was roughly equal.", "Çalışmadaki erkeklerin kadınlara oranı aşağı yukarı eşitti."],
      ["median", "ortanca, medyan", "", "The median age of the volunteers was thirty-four years.", "Gönüllülerin ortanca yaşı otuz dörttü."],
      ["approximation", "yaklaşık değer, yaklaşım", "", "This figure is only an approximation, so treat it with caution.", "Bu rakam sadece yaklaşık bir değer, o yüzden temkinli yaklaş."],
      ["probability", "olasılık", "🎲", "The probability of finding life on that planet is extremely low.", "O gezegende yaşam bulma olasılığı son derece düşük."],
      ["likelihood", "olasılık, ihtimal", "", "Regular exercise reduces the likelihood of developing heart disease.", "Düzenli egzersiz kalp hastalığı geliştirme ihtimalini azaltır."],
      ["variance", "varyans, değişkenlik", "", "There was a high variance in the scores of the younger group.", "Genç grubun puanlarında yüksek bir değişkenlik vardı."],
      ["deviation", "sapma", "", "Any deviation from the original plan must be reported to the supervisor.", "Özgün plandan her türlü sapma danışmana bildirilmelidir."],
      ["discrepancy", "tutarsızlık, uyuşmazlık", "", "We found a discrepancy between the two sets of figures.", "İki veri grubu arasında bir tutarsızlık bulduk."],
      ["underlying", "altta yatan, temel", "", "Scientists still do not fully understand the underlying cause of the disease.", "Bilim insanları hastalığın altta yatan nedenini hâlâ tam olarak anlamıyor."],
      ["mechanism", "mekanizma, işleyiş", "⚙️", "The study explains the mechanism that allows birds to sense magnetic fields.", "Çalışma, kuşların manyetik alanları algılamasını sağlayan mekanizmayı açıklıyor."],
      ["catalyst", "katalizör, tetikleyici", "", "Heat acts as a catalyst and speeds up the chemical reaction.", "Isı bir katalizör gibi davranarak kimyasal tepkimeyi hızlandırır."],
      ["compound", "bileşik", "🧪", "This compound is found naturally in green tea and dark chocolate.", "Bu bileşik doğal olarak yeşil çayda ve bitter çikolatada bulunur."],
      ["substance", "madde", "", "The lab tested every unknown substance found at the site.", "Laboratuvar alanda bulunan her bilinmeyen maddeyi test etti."],
      ["radiation", "radyasyon, ışınım", "☢️", "Astronauts are exposed to higher levels of radiation in space.", "Astronotlar uzayda daha yüksek düzeyde radyasyona maruz kalır."],
      ["velocity", "hız, sürat", "", "The velocity of the water increases as the river gets narrower.", "Nehir daraldıkça suyun hızı artar."],
      ["friction", "sürtünme", "", "Friction between the tyres and the road helps the car stop.", "Lastiklerle yol arasındaki sürtünme arabanın durmasına yardım eder."],
      ["erosion", "erozyon, aşınma", "", "Coastal erosion has destroyed several houses along the cliffs.", "Kıyı erozyonu yamaçlar boyunca birkaç evi yok etti."],
      ["sediment", "tortu, çökelti", "", "Layers of sediment at the bottom of the lake record past climates.", "Gölün dibindeki tortu katmanları geçmiş iklimleri kayıt altına alır."],
      ["fossil", "fosil", "🦴", "The children found a fossil of a small fish on the beach.", "Çocuklar sahilde küçük bir balığın fosilini buldu."],
      ["observatory", "gözlemevi", "", "The observatory sits on a mountain far from city lights.", "Gözlemevi şehir ışıklarından uzak bir dağın üzerinde duruyor."],
      ["astronomer", "gökbilimci, astronom", "", "An amateur astronomer spotted the comet before the professionals did.", "Amatör bir gökbilimci kuyruklu yıldızı profesyonellerden önce fark etti."],
      ["physicist", "fizikçi", "", "The physicist explained black holes in a way everyone could understand.", "Fizikçi kara delikleri herkesin anlayabileceği bir şekilde anlattı."],
      ["trial and error", "deneme yanılma", "", "They found the right formula through years of trial and error.", "Doğru formülü yıllarca süren deneme yanılma yoluyla buldular."],
      ["proof of concept", "kavram kanıtı, fikrin uygulanabilirlik kanıtı", "", "The small prototype served as a proof of concept for investors.", "Küçük prototip yatırımcılar için bir kavram kanıtı işlevi gördü."]
    ] },
  { id: "lib3b", title: "Teknoloji ve Yazılım", icon: "💻", cefr: "B2", desc: "İş yerinde, yazılım ekiplerinde ve günlük teknoloji kullanımında sık geçen kelime ve ifadeler.",
    words: [
      ["open source", "açık kaynak", "", "Most of the tools we use at work are open source and free.", "İş yerinde kullandığımız araçların çoğu açık kaynak ve ücretsiz."],
      ["repository", "depo, kod deposu", "📦", "Please clone the repository and run the tests on your machine.", "Lütfen depoyu klonla ve testleri kendi bilgisayarında çalıştır."],
      ["merge", "birleştirmek", "", "Don't merge your changes until someone has reviewed them.", "Biri incelemeden değişikliklerini birleştirme."],
      ["branch", "dal, kod dalı", "🌿", "I created a new branch to work on the login feature.", "Giriş özelliği üzerinde çalışmak için yeni bir dal oluşturdum."],
      ["pull request", "birleştirme isteği", "", "She opened a pull request and asked the team for feedback.", "Bir birleştirme isteği açtı ve ekipten geri bildirim istedi."],
      ["version control", "sürüm kontrolü", "", "Version control lets you go back to any earlier state of the project.", "Sürüm kontrolü projenin önceki herhangi bir hâline dönmeni sağlar."],
      ["deploy", "yayına almak, canlıya almak", "🚀", "We usually deploy new code on Tuesday mornings, never on Fridays.", "Yeni kodu genelde salı sabahları yayına alırız, asla cuma günleri değil."],
      ["deployment", "yayına alma, dağıtım", "", "The deployment failed because a password was missing from the server.", "Sunucuda bir şifre eksik olduğu için yayına alma başarısız oldu."],
      ["release", "sürüm, yayımlamak", "", "The next release will include a dark mode and faster search.", "Bir sonraki sürüm karanlık mod ve daha hızlı arama içerecek."],
      ["rollback", "geri alma, önceki sürüme dönüş", "", "After the crash, the team decided to do a quick rollback.", "Çöküşten sonra ekip hızlıca önceki sürüme dönmeye karar verdi."],
      ["roll out", "kademeli olarak sunmak, kullanıma sunmak", "", "The company will roll out the new app to all users next month.", "Şirket yeni uygulamayı gelecek ay tüm kullanıcılara sunacak."],
      ["patch", "yama", "🩹", "Install the latest security patch as soon as possible.", "En son güvenlik yamasını mümkün olan en kısa sürede yükle."],
      ["hotfix", "acil düzeltme", "", "The developers pushed a hotfix late at night to stop the errors.", "Geliştiriciler hataları durdurmak için gece geç saatte acil bir düzeltme yayımladı."],
      ["debug", "hata ayıklamak", "🐞", "It took me three hours to debug a problem caused by one comma.", "Tek bir virgülün yol açtığı bir sorunu ayıklamak üç saatimi aldı."],
      ["troubleshoot", "sorun gidermek", "", "The IT team will troubleshoot your laptop this afternoon.", "BT ekibi bu öğleden sonra dizüstü bilgisayarının sorununu giderecek."],
      ["workaround", "geçici çözüm, dolambaçlı çözüm", "", "There is no real fix yet, but here is a simple workaround.", "Henüz gerçek bir çözüm yok ama işte basit bir geçici çözüm."],
      ["bug fix", "hata düzeltmesi", "", "This update is just a small bug fix, so it won't take long.", "Bu güncelleme sadece küçük bir hata düzeltmesi, o yüzden uzun sürmez."],
      ["bug report", "hata raporu", "", "Please write a clear bug report with the steps to repeat the problem.", "Lütfen sorunu tekrar oluşturma adımlarını içeren net bir hata raporu yaz."],
      ["crash report", "çökme raporu", "", "The app sends a crash report automatically when something goes wrong.", "Bir şeyler ters gittiğinde uygulama otomatik olarak çökme raporu gönderir."],
      ["buggy", "hatalı, sorunlu", "", "The first version of the game was so buggy that many people quit.", "Oyunun ilk sürümü o kadar hatalıydı ki birçok kişi bıraktı."],
      ["glitchy", "aksayan, takılan", "", "My video call was glitchy, so I missed half of the meeting.", "Görüntülü aramam aksıyordu, bu yüzden toplantının yarısını kaçırdım."],
      ["lag", "gecikme, takılma", "", "There is a lot of lag when I play online in the evening.", "Akşamları çevrim içi oynarken çok fazla gecikme oluyor."],
      ["latency", "gecikme süresi", "", "Low latency is essential for video calls and online games.", "Düşük gecikme süresi görüntülü aramalar ve çevrim içi oyunlar için şarttır."],
      ["load time", "yüklenme süresi", "⏱️", "We cut the page load time from five seconds to one.", "Sayfanın yüklenme süresini beş saniyeden bir saniyeye indirdik."],
      ["authentication", "kimlik doğrulama", "🔐", "The bank added an extra authentication step for large payments.", "Banka yüksek tutarlı ödemeler için ek bir kimlik doğrulama adımı ekledi."],
      ["authorize", "yetkilendirmek, onaylamak", "", "You need to authorize the app before it can read your calendar.", "Uygulamanın takvimini okuyabilmesi için önce onu yetkilendirmen gerekiyor."],
      ["permission", "izin", "", "The app asks for permission to use your camera and microphone.", "Uygulama kameranı ve mikrofonunu kullanmak için izin istiyor."],
      ["admin", "yönetici", "", "Only the admin can add new users to the system.", "Sisteme yeni kullanıcı yalnızca yönetici ekleyebilir."],
      ["user account", "kullanıcı hesabı", "👤", "Each employee gets a separate user account with its own password.", "Her çalışan kendi şifresi olan ayrı bir kullanıcı hesabı alır."],
      ["user experience", "kullanıcı deneyimi", "", "Small details can make a huge difference to the user experience.", "Küçük ayrıntılar kullanıcı deneyiminde büyük bir fark yaratabilir."],
      ["user interface", "kullanıcı arayüzü", "", "The new user interface is cleaner and much easier to understand.", "Yeni kullanıcı arayüzü daha sade ve anlaşılması çok daha kolay."],
      ["layout", "düzen, yerleşim", "", "I like the layout of this website because everything is easy to find.", "Bu web sitesinin düzenini seviyorum çünkü her şeyi bulmak kolay."],
      ["dashboard", "gösterge paneli, kontrol paneli", "📊", "The sales dashboard shows today's numbers in real time.", "Satış paneli bugünün rakamlarını anlık olarak gösteriyor."],
      ["default", "varsayılan", "", "The default language is English, but you can change it in settings.", "Varsayılan dil İngilizce ama ayarlardan değiştirebilirsin."],
      ["customize", "kişiselleştirmek, özelleştirmek", "", "You can customize the home screen with your favourite apps.", "Ana ekranı en sevdiğin uygulamalarla kişiselleştirebilirsin."],
      ["configure", "yapılandırmak, ayarlamak", "", "It took us a whole day to configure the new printer.", "Yeni yazıcıyı yapılandırmak bütün günümüzü aldı."],
      ["preferences", "tercihler", "", "You can change your notification preferences at any time.", "Bildirim tercihlerini istediğin zaman değiştirebilirsin."],
      ["pop-up", "açılır pencere", "", "A pop-up keeps appearing every time I open this page.", "Bu sayfayı her açtığımda bir açılır pencere çıkıp duruyor."],
      ["drop-down menu", "açılır menü", "", "Choose your country from the drop-down menu at the top.", "Üstteki açılır menüden ülkeni seç."],
      ["toolbar", "araç çubuğu", "", "The save button is on the toolbar at the top of the screen.", "Kaydet düğmesi ekranın üstündeki araç çubuğunda."],
      ["keyboard shortcut", "klavye kısayolu", "⌨️", "Learning one keyboard shortcut a day will save you hours.", "Her gün bir klavye kısayolu öğrenmek sana saatler kazandırır."],
      ["cursor", "imleç", "", "Move the cursor to the end of the line and press enter.", "İmleci satırın sonuna götür ve entera bas."],
      ["double-click", "çift tıklamak", "🖱️", "Double-click the icon on your desktop to open the program.", "Programı açmak için masaüstündeki simgeye çift tıkla."],
      ["drag and drop", "sürükleyip bırakmak", "", "Just drag and drop the photos into this box to upload them.", "Fotoğrafları yüklemek için onları bu kutuya sürükleyip bırakman yeterli."],
      ["swipe", "kaydırmak", "👆", "Swipe left to delete a message or right to archive it.", "Bir mesajı silmek için sola, arşivlemek için sağa kaydır."],
      ["tap", "dokunmak", "", "Tap the screen twice to like a photo.", "Bir fotoğrafı beğenmek için ekrana iki kez dokun."],
      ["zoom in", "yakınlaştırmak", "🔎", "Zoom in on the map so we can see the street names.", "Sokak adlarını görebilmemiz için haritayı yakınlaştır."],
      ["tab", "sekme", "", "I always have about thirty tabs open in my browser.", "Tarayıcımda hep otuz kadar sekme açık olur."],
      ["directory", "dizin, klasör", "📁", "Save the file in the main project directory, not on the desktop.", "Dosyayı masaüstüne değil, ana proje dizinine kaydet."],
      ["file format", "dosya biçimi", "", "Which file format should I use, PDF or Word?", "Hangi dosya biçimini kullanmalıyım, PDF mi Word mü?"],
      ["compress", "sıkıştırmak", "🗜️", "Compress the videos before you send them by email.", "Videoları e-postayla göndermeden önce sıkıştır."],
      ["extract", "çıkarmak, açmak", "", "Extract the files from the zip folder before you install the program.", "Programı kurmadan önce dosyaları zip klasöründen çıkar."],
      ["sync", "eşitlemek, senkronize etmek", "🔄", "My phone and laptop sync my notes automatically.", "Telefonum ve dizüstü bilgisayarım notlarımı otomatik olarak eşitliyor."],
      ["server", "sunucu", "🖥️", "The website went down because the server was overloaded.", "Sunucu aşırı yüklendiği için web sitesi çöktü."],
      ["hosting", "barındırma, hosting", "", "We pay a small monthly fee for website hosting.", "Web sitesi barındırma hizmeti için aylık küçük bir ücret ödüyoruz."],
      ["domain", "alan adı", "🌐", "We bought a short domain that is easy to remember.", "Akılda kalması kolay kısa bir alan adı satın aldık."],
      ["bandwidth", "bant genişliği", "", "Streaming in high quality uses a lot of bandwidth.", "Yüksek kalitede yayın izlemek çok fazla bant genişliği kullanır."],
      ["wi-fi", "kablosuz internet", "📶", "The hotel wi-fi is free but quite slow in the rooms.", "Otelin kablosuz interneti ücretsiz ama odalarda oldukça yavaş."],
      ["hotspot", "erişim noktası, mobil bağlantı paylaşımı", "", "I used my phone as a hotspot when the office internet stopped working.", "Ofisin interneti çalışmayı bırakınca telefonumu erişim noktası olarak kullandım."],
      ["bluetooth", "bluetooth", "", "Turn on bluetooth so your headphones can connect.", "Kulaklığının bağlanabilmesi için bluetooth'u aç."],
      ["pair", "eşleştirmek", "🎧", "You need to pair the speaker with your phone the first time.", "Hoparlörü ilk seferde telefonunla eşleştirmen gerekiyor."],
      ["battery life", "pil ömrü", "🔋", "The battery life of this laptop is about twelve hours.", "Bu dizüstü bilgisayarın pil ömrü yaklaşık on iki saat."],
      ["processor", "işlemci", "", "A faster processor makes video editing much smoother.", "Daha hızlı bir işlemci video düzenlemeyi çok daha akıcı hâle getirir."],
      ["ram", "RAM, çalışma belleği", "", "My computer slows down because it only has four gigabytes of RAM.", "Bilgisayarım yalnızca dört gigabayt RAM'i olduğu için yavaşlıyor."],
      ["storage space", "depolama alanı", "", "My phone keeps telling me that I'm running out of storage space.", "Telefonum sürekli depolama alanımın tükenmek üzere olduğunu söylüyor."],
      ["hard drive", "sabit disk", "💽", "I keep an external hard drive with copies of all my photos.", "Tüm fotoğraflarımın kopyalarının olduğu harici bir sabit diskim var."],
      ["operating system", "işletim sistemi", "", "The app works on every major operating system, including Linux.", "Uygulama Linux dâhil tüm büyük işletim sistemlerinde çalışıyor."],
      ["firmware", "donanım yazılımı", "", "Update the router firmware to fix the security problem.", "Güvenlik sorununu gidermek için modemin donanım yazılımını güncelle."],
      ["compatible", "uyumlu", "", "Is this charger compatible with my new phone?", "Bu şarj aleti yeni telefonumla uyumlu mu?"],
      ["compatibility", "uyumluluk", "", "Check compatibility with your system before you buy the software.", "Yazılımı satın almadan önce sisteminle uyumluluğunu kontrol et."],
      ["plugin", "eklenti", "🧩", "This plugin adds a spell checker to your browser.", "Bu eklenti tarayıcına bir yazım denetleyicisi ekliyor."],
      ["extension", "uzantı, eklenti", "", "I installed an extension that blocks annoying ads.", "Can sıkıcı reklamları engelleyen bir uzantı yükledim."],
      ["backend", "arka uç", "", "He works on the backend, so users never see his code directly.", "Arka uçta çalışıyor, bu yüzden kullanıcılar onun kodunu hiçbir zaman doğrudan görmüyor."],
      ["front end", "ön yüz, ön uç", "", "Our front end team designs everything the user sees on the screen.", "Ön yüz ekibimiz kullanıcının ekranda gördüğü her şeyi tasarlıyor."],
      ["full-stack", "hem ön hem arka uçta çalışan", "", "We are looking for a full-stack developer who can work remotely.", "Uzaktan çalışabilecek, hem ön hem arka uçta çalışan bir geliştirici arıyoruz."],
      ["developer", "geliştirici", "👩‍💻", "She worked as a developer for five years before becoming a manager.", "Yönetici olmadan önce beş yıl geliştirici olarak çalıştı."],
      ["programmer", "programcı", "", "A good programmer writes code that other people can easily read.", "İyi bir programcı başkalarının kolayca okuyabileceği kod yazar."],
      ["programming language", "programlama dili", "", "Python is often the first programming language people learn.", "Python genellikle insanların öğrendiği ilk programlama dilidir."],
      ["script", "betik, komut dosyası", "📜", "I wrote a short script that renames hundreds of files in seconds.", "Yüzlerce dosyayı saniyeler içinde yeniden adlandıran kısa bir betik yazdım."],
      ["function", "fonksiyon, işlev", "", "This function checks whether the email address is valid.", "Bu fonksiyon e-posta adresinin geçerli olup olmadığını kontrol ediyor."],
      ["loop", "döngü", "➰", "The program got stuck in a loop and never finished.", "Program bir döngüye takıldı ve hiç bitmedi."],
      ["syntax", "sözdizimi", "", "A missing bracket caused a syntax error in my code.", "Eksik bir parantez kodumda sözdizimi hatasına yol açtı."],
      ["compile", "derlemek", "", "It takes about ten minutes to compile the whole project.", "Projenin tamamını derlemek yaklaşık on dakika sürüyor."],
      ["execute", "çalıştırmak, yürütmek", "", "The computer will execute these commands one after another.", "Bilgisayar bu komutları birbiri ardına çalıştıracak."],
      ["input", "girdi", "", "The form rejects any input that is longer than fifty characters.", "Form elli karakterden uzun her girdiyi reddediyor."],
      ["output", "çıktı", "", "Compare the output of the program with the expected result.", "Programın çıktısını beklenen sonuçla karşılaştır."],
      ["query", "sorgu", "", "This database query returns all customers from Istanbul.", "Bu veritabanı sorgusu İstanbul'daki tüm müşterileri getiriyor."],
      ["pixel", "piksel", "", "Every pixel on this screen is sharp and bright.", "Bu ekrandaki her piksel net ve parlak."],
      ["render", "işlemek, oluşturmak", "", "It took the computer two hours to render the short animation.", "Bilgisayarın kısa animasyonu işlemesi iki saat sürdü."],
      ["graphics", "grafikler, grafik", "🎮", "The game has amazing graphics, but it needs a powerful computer.", "Oyunun grafikleri harika ama güçlü bir bilgisayar gerektiriyor."],
      ["malware", "kötü amaçlı yazılım", "🦠", "Never open attachments from strangers because they may contain malware.", "Yabancılardan gelen ekleri asla açma çünkü kötü amaçlı yazılım içerebilirler."],
      ["phishing", "oltalama, kimlik avı", "🎣", "The email looked real, but it was a phishing attempt.", "E-posta gerçek görünüyordu ama bir oltalama girişimiydi."],
      ["firewall", "güvenlik duvarı", "🧱", "The company firewall blocks many social media websites.", "Şirketin güvenlik duvarı birçok sosyal medya sitesini engelliyor."],
      ["antivirus", "virüsten koruma programı", "", "Run an antivirus scan if your computer starts acting strangely.", "Bilgisayarın tuhaf davranmaya başlarsa bir virüs taraması yap."],
      ["vulnerability", "güvenlik açığı", "", "Experts discovered a serious vulnerability in the popular messaging app.", "Uzmanlar popüler mesajlaşma uygulamasında ciddi bir güvenlik açığı keşfetti."],
      ["data breach", "veri ihlali", "", "Millions of passwords were stolen in the latest data breach.", "Son veri ihlalinde milyonlarca şifre çalındı."],
      ["encryption", "şifreleme", "🔒", "End-to-end encryption means only you and the receiver can read messages.", "Uçtan uca şifreleme, mesajları yalnızca senin ve alıcının okuyabileceği anlamına gelir."],
      ["privacy settings", "gizlilik ayarları", "", "Check your privacy settings so strangers cannot see your photos.", "Yabancıların fotoğraflarını görememesi için gizlilik ayarlarını kontrol et."],
      ["cookie", "çerez", "🍪", "The website uses a cookie to remember your language choice.", "Web sitesi dil seçimini hatırlamak için bir çerez kullanıyor."],
      ["terms of service", "hizmet şartları", "", "Almost nobody reads the terms of service before clicking accept.", "Neredeyse hiç kimse kabul et'e tıklamadan önce hizmet şartlarını okumaz."],
      ["free trial", "ücretsiz deneme", "", "The free trial lasts thirty days, and then you have to pay.", "Ücretsiz deneme otuz gün sürüyor, sonra ödeme yapman gerekiyor."],
      ["license", "lisans", "", "Each license allows you to install the software on two computers.", "Her lisans yazılımı iki bilgisayara kurmana izin veriyor."],
      ["beta", "beta, deneme sürümü", "", "I joined the beta to test new features before everyone else.", "Yeni özellikleri herkesten önce denemek için beta sürümüne katıldım."],
      ["help desk", "yardım masası, destek birimi", "🛠️", "If you forget your password, call the help desk.", "Şifreni unutursan yardım masasını ara."],
      ["factory reset", "fabrika ayarlarına sıfırlama", "", "A factory reset will delete everything on the phone, so back it up first.", "Fabrika ayarlarına sıfırlama telefondaki her şeyi siler, o yüzden önce yedek al."],
      ["reboot", "yeniden başlatmak", "", "Try to reboot the router before you call customer service.", "Müşteri hizmetlerini aramadan önce modemi yeniden başlatmayı dene."],
      ["boot up", "açılmak, başlatmak", "", "My old laptop takes almost five minutes to boot up.", "Eski dizüstü bilgisayarımın açılması neredeyse beş dakika sürüyor."],
      ["intuitive", "sezgisel, kolay anlaşılır", "", "The app is so intuitive that my grandmother learned it in a day.", "Uygulama o kadar kolay anlaşılır ki büyükannem bir günde öğrendi."],
      ["seamless", "kesintisiz, sorunsuz", "", "Moving my files to the new phone was quick and seamless.", "Dosyalarımı yeni telefona taşımak hızlı ve sorunsuzdu."],
      ["clear cache", "önbelleği temizlemek", "", "If the page looks broken, clear cache and reload it.", "Sayfa bozuk görünüyorsa önbelleği temizle ve yeniden yükle."]
    ] },
  { id: "lib3c", title: "Tıp ve Sağlık", icon: "🩺", cefr: "B2", desc: "Doktorda, hastanede ve eczanede derdini anlatmak, sağlık haberlerini anlamak için gerekli kelimeler.",
    words: [
      ["diagnose", "teşhis koymak", "", "It took the doctors weeks to diagnose the rare condition.", "Doktorların bu nadir rahatsızlığa teşhis koyması haftalar sürdü."],
      ["diagnosis", "teşhis, tanı", "", "Early diagnosis makes many diseases much easier to treat.", "Erken teşhis birçok hastalığın tedavisini çok daha kolaylaştırır."],
      ["misdiagnosis", "yanlış teşhis", "", "A misdiagnosis meant she took the wrong medicine for months.", "Yanlış teşhis yüzünden aylarca yanlış ilacı kullandı."],
      ["prognosis", "hastalığın seyri, prognoz", "", "The prognosis is good if the patient follows the treatment plan.", "Hasta tedavi planına uyarsa hastalığın seyri iyi görünüyor."],
      ["treat", "tedavi etmek", "", "Doctors usually treat this infection with a short course of medicine.", "Doktorlar bu enfeksiyonu genelde kısa bir ilaç kürüyle tedavi eder."],
      ["treatment", "tedavi", "", "The new treatment has fewer side effects than the old one.", "Yeni tedavinin eskisine göre daha az yan etkisi var."],
      ["cure", "tedavi, çare, iyileştirmek", "", "There is still no cure for the common cold.", "Soğuk algınlığının hâlâ bir çaresi yok."],
      ["remedy", "çare, ilaç", "🍯", "My grandmother's remedy for a cough is honey with warm milk.", "Büyükannemin öksürük için çaresi ılık süte bal katmaktır."],
      ["dosage", "doz, dozaj", "", "Check the dosage carefully before you give medicine to children.", "Çocuklara ilaç vermeden önce dozu dikkatlice kontrol et."],
      ["dose", "doz", "", "Take one dose in the morning and another before bed.", "Bir dozu sabah, diğerini yatmadan önce al."],
      ["overdose", "aşırı doz", "", "Taking too many painkillers at once can lead to an overdose.", "Aynı anda çok fazla ağrı kesici almak aşırı doza yol açabilir."],
      ["antibiotic", "antibiyotik", "💊", "An antibiotic will not help you if you have a virus.", "Virüs kaptıysan antibiyotik sana yardım etmez."],
      ["over-the-counter", "reçetesiz", "", "You can buy this medicine over-the-counter at any pharmacy.", "Bu ilacı herhangi bir eczaneden reçetesiz alabilirsin."],
      ["prescribe", "reçete etmek, yazmak", "📝", "The doctor will prescribe something stronger if the pain continues.", "Ağrı devam ederse doktor daha güçlü bir şey yazacak."],
      ["ointment", "merhem", "", "Put a little ointment on the burn and cover it.", "Yanığa biraz merhem sür ve üstünü ört."],
      ["syrup", "şurup", "", "This cough syrup tastes awful, but it really works.", "Bu öksürük şurubunun tadı berbat ama gerçekten işe yarıyor."],
      ["inhaler", "inhaler, astım spreyi", "", "He always carries his inhaler when he goes running.", "Koşuya çıkarken inhalerini hep yanında taşır."],
      ["jab", "aşı, iğne", "💉", "I had my flu jab last week, and my arm still hurts.", "Grip aşımı geçen hafta oldum, kolum hâlâ ağrıyor."],
      ["booster", "hatırlatma dozu, takviye aşı", "", "Adults need a tetanus booster every ten years.", "Yetişkinlerin her on yılda bir tetanoz hatırlatma dozuna ihtiyacı var."],
      ["immunity", "bağışıklık", "", "Good sleep and a healthy diet can strengthen your immunity.", "İyi uyku ve sağlıklı beslenme bağışıklığını güçlendirebilir."],
      ["immune system", "bağışıklık sistemi", "🛡️", "Stress can weaken your immune system over time.", "Stres zamanla bağışıklık sistemini zayıflatabilir."],
      ["infectious", "bulaşıcı", "", "Measles is one of the most infectious diseases in the world.", "Kızamık dünyadaki en bulaşıcı hastalıklardan biridir."],
      ["contagious", "bulaşıcı", "", "Stay at home for a few days because you are still contagious.", "Birkaç gün evde kal çünkü hâlâ bulaşıcısın."],
      ["outbreak", "salgın, baş gösterme", "", "Health officials are trying to control an outbreak of food poisoning.", "Sağlık yetkilileri bir gıda zehirlenmesi salgınını kontrol altına almaya çalışıyor."],
      ["epidemic", "salgın", "", "Some experts call loneliness a silent epidemic in big cities.", "Bazı uzmanlar yalnızlığı büyük şehirlerde sessiz bir salgın olarak adlandırıyor."],
      ["pandemic", "pandemi, küresel salgın", "🌍", "The pandemic changed the way many people work and shop.", "Pandemi birçok insanın çalışma ve alışveriş biçimini değiştirdi."],
      ["quarantine", "karantina", "", "Travellers had to stay in quarantine for two weeks.", "Yolcular iki hafta boyunca karantinada kalmak zorundaydı."],
      ["transmit", "bulaştırmak, iletmek", "", "Mosquitoes can transmit several serious diseases to humans.", "Sivrisinekler insanlara birkaç ciddi hastalık bulaştırabilir."],
      ["transmission", "bulaşma, iletim", "", "Washing your hands reduces the transmission of many illnesses.", "Ellerini yıkamak birçok hastalığın bulaşmasını azaltır."],
      ["bacteria", "bakteriler", "🦠", "Some bacteria in your stomach are actually good for your health.", "Midendeki bazı bakteriler aslında sağlığın için iyidir."],
      ["germs", "mikroplar", "", "Children pick up germs very easily at school.", "Çocuklar okulda çok kolay mikrop kapar."],
      ["inflammation", "iltihap, iltihaplanma", "", "Ice can reduce inflammation after a sports injury.", "Buz, spor yaralanmasından sonra iltihaplanmayı azaltabilir."],
      ["swelling", "şişlik", "", "The swelling in my knee went down after a few days.", "Dizimdeki şişlik birkaç gün sonra indi."],
      ["swollen", "şişmiş, şiş", "", "My ankle was so swollen that I couldn't wear my shoe.", "Ayak bileğim o kadar şişmişti ki ayakkabımı giyemedim."],
      ["itchy", "kaşıntılı", "", "My eyes get red and itchy every spring.", "Her ilkbahar gözlerim kızarıp kaşınıyor."],
      ["blocked nose", "tıkalı burun", "🤧", "I can't sleep well with a blocked nose.", "Burnum tıkalıyken iyi uyuyamıyorum."],
      ["dizziness", "baş dönmesi", "😵", "Tell the doctor if the dizziness gets worse when you stand up.", "Ayağa kalktığında baş dönmesi kötüleşirse doktora söyle."],
      ["nausea", "mide bulantısı", "", "Nausea is a common side effect of this medicine.", "Mide bulantısı bu ilacın yaygın bir yan etkisidir."],
      ["vomit", "kusmak", "", "If the child starts to vomit, take him to the hospital.", "Çocuk kusmaya başlarsa onu hastaneye götür."],
      ["fatigue", "yorgunluk, bitkinlik", "", "Constant fatigue can be a sign of a deeper health problem.", "Sürekli bitkinlik daha derin bir sağlık sorununun belirtisi olabilir."],
      ["migraine", "migren", "", "When I have a migraine, I need a dark and quiet room.", "Migrenim olduğunda karanlık ve sessiz bir odaya ihtiyacım olur."],
      ["cramp", "kramp", "", "I got a terrible cramp in my leg while swimming.", "Yüzerken bacağıma korkunç bir kramp girdi."],
      ["sprained ankle", "burkulmuş ayak bileği", "", "She missed the final match because of a sprained ankle.", "Burkulmuş ayak bileği yüzünden final maçını kaçırdı."],
      ["fracture", "kırık, kırılmak", "🦴", "The X-ray showed a small fracture in his wrist.", "Röntgen bileğinde küçük bir kırık olduğunu gösterdi."],
      ["bruised", "morarmış, berelenmiş", "", "He wasn't badly hurt, just a little bruised after the fall.", "Kötü yaralanmadı, düştükten sonra sadece biraz morardı."],
      ["bleeding", "kanama", "🩸", "Press firmly on the cut to stop the bleeding.", "Kanamayı durdurmak için kesiğin üzerine sıkıca bastır."],
      ["wound", "yara", "", "Clean the wound with water before you put a plaster on it.", "Üzerine yara bandı yapıştırmadan önce yarayı suyla temizle."],
      ["scar", "yara izi", "", "The operation left a small scar on her stomach.", "Ameliyat karnında küçük bir yara izi bıraktı."],
      ["stitches", "dikiş", "🧵", "The cut was deep, so he needed six stitches.", "Kesik derindi, bu yüzden altı dikiş atılması gerekti."],
      ["crutches", "koltuk değneği", "🩼", "I had to walk on crutches for a month after the accident.", "Kazadan sonra bir ay koltuk değnekleriyle yürümek zorunda kaldım."],
      ["wheelchair", "tekerlekli sandalye", "♿", "The building has a ramp for people in a wheelchair.", "Binada tekerlekli sandalye kullananlar için bir rampa var."],
      ["first aid", "ilk yardım", "⛑️", "Everyone in the office took a basic first aid course.", "Ofisteki herkes temel bir ilk yardım kursu aldı."],
      ["emergency room", "acil servis", "🚑", "We waited four hours in the emergency room last night.", "Dün gece acil serviste dört saat bekledik."],
      ["paramedic", "sağlık görevlisi, paramedik", "", "The paramedic checked his breathing before putting him in the ambulance.", "Sağlık görevlisi onu ambulansa koymadan önce solunumunu kontrol etti."],
      ["intensive care", "yoğun bakım", "", "She spent three days in intensive care after the surgery.", "Ameliyattan sonra üç gün yoğun bakımda kaldı."],
      ["discharge", "taburcu etmek", "", "The hospital will discharge him tomorrow if his fever stays down.", "Ateşi düşük kalırsa hastane onu yarın taburcu edecek."],
      ["general practitioner", "aile hekimi, pratisyen hekim", "", "Your general practitioner can refer you to a specialist.", "Aile hekimin seni bir uzmana sevk edebilir."],
      ["specialist", "uzman doktor", "", "I've been waiting two months to see a skin specialist.", "Bir cildiye uzmanına görünmek için iki aydır bekliyorum."],
      ["physician", "hekim, doktor", "", "Always ask your physician before you stop taking any medicine.", "Herhangi bir ilacı bırakmadan önce mutlaka hekimine danış."],
      ["physiotherapist", "fizyoterapist", "", "My physiotherapist gave me exercises to strengthen my back.", "Fizyoterapistim sırtımı güçlendirmem için bana egzersizler verdi."],
      ["psychiatrist", "psikiyatrist", "", "A psychiatrist can prescribe medication, but a psychologist usually cannot.", "Bir psikiyatrist ilaç yazabilir ama bir psikolog genellikle yazamaz."],
      ["counselling", "danışmanlık, psikolojik destek", "", "The company offers free counselling to employees who feel overwhelmed.", "Şirket bunalmış hisseden çalışanlara ücretsiz psikolojik destek sunuyor."],
      ["blood test", "kan tahlili", "", "The blood test showed that I was low in iron.", "Kan tahlili demir seviyemin düşük olduğunu gösterdi."],
      ["x-ray", "röntgen", "", "They took an X-ray to make sure nothing was broken.", "Kırık bir şey olmadığından emin olmak için röntgen çektiler."],
      ["scan", "tarama, görüntüleme", "", "The scan showed that the baby is healthy and growing well.", "Tarama bebeğin sağlıklı olduğunu ve iyi büyüdüğünü gösterdi."],
      ["ultrasound", "ultrason", "", "The doctor used an ultrasound to look at her kidneys.", "Doktor böbreklerine bakmak için ultrason kullandı."],
      ["operation", "ameliyat", "", "The operation was successful, and he is already walking again.", "Ameliyat başarılı geçti ve şimdiden yeniden yürüyor."],
      ["undergo", "geçirmek, maruz kalmak", "", "She will undergo knee surgery at the end of the month.", "Ay sonunda diz ameliyatı geçirecek."],
      ["anaesthetic", "anestezi, uyuşturucu ilaç", "", "You won't feel anything because of the local anaesthetic.", "Lokal anestezi sayesinde hiçbir şey hissetmeyeceksin."],
      ["recovery", "iyileşme", "", "Full recovery from this kind of injury can take six months.", "Bu tür bir yaralanmadan tamamen iyileşmek altı ay sürebilir."],
      ["relapse", "nüks, hastalığın tekrarlaması", "", "Stopping the treatment too early increases the risk of a relapse.", "Tedaviyi çok erken bırakmak hastalığın tekrarlama riskini artırır."],
      ["chronic", "kronik, süreğen", "", "Millions of people live with chronic back pain.", "Milyonlarca insan kronik sırt ağrısıyla yaşıyor."],
      ["acute", "akut, şiddetli ve ani", "", "He was taken to hospital with acute stomach pain.", "Akut karın ağrısıyla hastaneye kaldırıldı."],
      ["benign", "iyi huylu", "", "Luckily, the lump turned out to be benign.", "Neyse ki yumru iyi huylu çıktı."],
      ["malignant", "kötü huylu", "", "Doctors removed the malignant cells before they could spread.", "Doktorlar kötü huylu hücreleri yayılmadan önce aldı."],
      ["tumour", "tümör", "", "The scan revealed a small tumour that needed further tests.", "Tarama, ek testler gerektiren küçük bir tümörü ortaya çıkardı."],
      ["cancer", "kanser", "🎗️", "Not smoking is one of the best ways to prevent lung cancer.", "Sigara içmemek akciğer kanserini önlemenin en iyi yollarından biridir."],
      ["diabetes", "diyabet, şeker hastalığı", "", "People with diabetes need to check their blood sugar regularly.", "Diyabet hastalarının kan şekerlerini düzenli olarak kontrol etmeleri gerekir."],
      ["asthma", "astım", "", "Cold air can trigger an asthma attack in some people.", "Soğuk hava bazı insanlarda astım krizini tetikleyebilir."],
      ["allergy", "alerji", "", "I have an allergy to nuts, so I always read the labels.", "Kuruyemişe alerjim var, bu yüzden etiketleri hep okurum."],
      ["hay fever", "saman nezlesi, polen alerjisi", "🌼", "Hay fever makes my spring holidays quite unpleasant.", "Saman nezlesi bahar tatillerimi oldukça tatsızlaştırıyor."],
      ["high blood pressure", "yüksek tansiyon", "", "Eating too much salt can lead to high blood pressure.", "Çok fazla tuz yemek yüksek tansiyona yol açabilir."],
      ["heart attack", "kalp krizi", "", "Chest pain and shortness of breath can be signs of a heart attack.", "Göğüs ağrısı ve nefes darlığı kalp krizi belirtisi olabilir."],
      ["stroke", "felç, inme", "", "Quick treatment after a stroke can prevent permanent damage.", "İnmeden sonraki hızlı tedavi kalıcı hasarı önleyebilir."],
      ["cholesterol", "kolesterol", "", "My doctor told me to eat less fried food to lower my cholesterol.", "Doktorum kolesterolümü düşürmek için daha az kızartma yememi söyledi."],
      ["obesity", "obezite", "", "Childhood obesity has become a serious problem in many countries.", "Çocukluk çağı obezitesi birçok ülkede ciddi bir sorun hâline geldi."],
      ["nutrition", "beslenme", "🥗", "Good nutrition is especially important for women during pregnancy.", "İyi beslenme özellikle hamilelik döneminde kadınlar için önemlidir."],
      ["supplement", "takviye, besin desteği", "", "My doctor suggested a vitamin D supplement during the winter.", "Doktorum kış boyunca D vitamini takviyesi önerdi."],
      ["balanced diet", "dengeli beslenme", "", "A balanced diet includes vegetables, protein and whole grains.", "Dengeli beslenme sebze, protein ve tam tahılları içerir."],
      ["dehydrated", "susuz kalmış", "💧", "Drink plenty of water so you don't get dehydrated in the heat.", "Sıcakta susuz kalmamak için bol su iç."],
      ["sedentary", "hareketsiz, oturarak geçen", "", "A sedentary lifestyle increases the risk of many health problems.", "Hareketsiz bir yaşam tarzı birçok sağlık sorununun riskini artırır."],
      ["hygiene", "hijyen, temizlik", "🧼", "Good hygiene in the kitchen helps prevent food poisoning.", "Mutfakta iyi hijyen gıda zehirlenmesini önlemeye yardım eder."],
      ["disinfect", "dezenfekte etmek", "", "The nurses disinfect all the equipment after every patient.", "Hemşireler her hastadan sonra tüm ekipmanı dezenfekte eder."],
      ["pulse", "nabız", "", "The nurse checked my pulse and wrote it on the chart.", "Hemşire nabzımı ölçtü ve çizelgeye yazdı."],
      ["heartbeat", "kalp atışı", "❤️", "We heard the baby's heartbeat for the first time today.", "Bugün bebeğin kalp atışını ilk kez duyduk."],
      ["breathless", "nefes nefese, soluksuz", "", "I feel breathless after climbing just two flights of stairs.", "Sadece iki kat merdiven çıktıktan sonra nefes nefese kalıyorum."],
      ["short of breath", "nefesi daralmış", "", "Call a doctor if you suddenly feel short of breath.", "Aniden nefesin daralırsa bir doktor çağır."],
      ["kidney", "böbrek", "", "Drinking enough water every day helps prevent kidney stones.", "Her gün yeterince su içmek böbrek taşlarını önlemeye yardım eder."],
      ["liver", "karaciğer", "", "Too much alcohol can seriously damage your liver.", "Fazla alkol karaciğerine ciddi zarar verebilir."],
      ["lung", "akciğer", "🫁", "The doctor listened to each lung with her stethoscope.", "Doktor steteskopuyla her bir akciğeri dinledi."],
      ["spine", "omurga", "", "Sitting badly for hours can put pressure on your spine.", "Saatlerce kötü oturmak omurgana baskı yapabilir."],
      ["metabolism", "metabolizma", "", "Your metabolism slows down a little as you get older.", "Yaşlandıkça metabolizman biraz yavaşlar."],
      ["hormone", "hormon", "", "Stress causes the body to release a hormone called cortisol.", "Stres vücudun kortizol adlı bir hormon salgılamasına neden olur."],
      ["hereditary", "kalıtsal", "🧬", "Some types of heart disease are hereditary, so check your family history.", "Bazı kalp hastalıkları kalıtsaldır, bu yüzden aile geçmişini kontrol et."],
      ["medical history", "tıbbi geçmiş, sağlık geçmişi", "📋", "The doctor asked about my medical history before the operation.", "Doktor ameliyattan önce sağlık geçmişimi sordu."],
      ["health insurance", "sağlık sigortası", "", "My new job comes with private health insurance.", "Yeni işim özel sağlık sigortasıyla birlikte geliyor."],
      ["organ donor", "organ bağışçısı", "", "I registered as an organ donor when I got my driving licence.", "Ehliyetimi aldığımda organ bağışçısı olarak kaydoldum."],
      ["midwife", "ebe", "👶", "The midwife stayed with her for the whole night.", "Ebe bütün gece onunla birlikte kaldı."],
      ["life expectancy", "ortalama yaşam süresi", "", "Life expectancy has increased a lot over the last century.", "Ortalama yaşam süresi geçen yüzyılda çok arttı."],
      ["asymptomatic", "belirtisiz, semptomsuz", "", "Many people with the virus were asymptomatic and felt completely fine.", "Virüsü taşıyan birçok kişi belirtisizdi ve kendini tamamen iyi hissediyordu."]
    ] }
);
