(window.LIBRARY = window.LIBRARY || []).push(
  { id: "lib5a", title: "Çevre, Enerji ve İklim", icon: "🌍", cefr: "B2", desc: "İklim krizi, enerji kaynakları ve çevre korumayı konuşmak için gereken kelimeler.",
    words: [
      ["biodiversity", "biyolojik çeşitlilik", "🌿", "Protecting biodiversity means protecting the plants and animals we all depend on.", "Biyolojik çeşitliliği korumak, hepimizin bağlı olduğu bitki ve hayvanları korumak demektir."],
      ["conservation", "koruma, doğa koruma", "🛡️", "She works for a conservation group that protects old forests in the north.", "Kuzeydeki yaşlı ormanları koruyan bir doğa koruma grubunda çalışıyor."],
      ["contaminate", "kirletmek, bulaştırmak", "☣️", "Chemicals from the factory could contaminate the river for many years.", "Fabrikadan gelen kimyasallar nehri yıllarca kirletebilir."],
      ["contamination", "kirlenme, bulaşma", "🧪", "Tests showed serious contamination in the soil near the old factory.", "Testler eski fabrikanın yakınındaki toprakta ciddi bir kirlenme olduğunu gösterdi."],
      ["hydroelectric", "hidroelektrik", "💧", "The new hydroelectric dam produces enough power for three nearby towns.", "Yeni hidroelektrik baraj yakındaki üç kasabaya yetecek kadar enerji üretiyor."],
      ["nuclear power", "nükleer enerji", "⚛️", "People still disagree about whether nuclear power is safe enough for the future.", "İnsanlar nükleer enerjinin gelecek için yeterince güvenli olup olmadığı konusunda hâlâ anlaşamıyor."],
      ["power plant", "elektrik santrali", "🏭", "The old power plant will close next year and become a museum.", "Eski elektrik santrali gelecek yıl kapanacak ve bir müzeye dönüşecek."],
      ["power grid", "elektrik şebekesi", "🔌", "The heatwave put huge pressure on the national power grid last summer.", "Geçen yaz sıcak hava dalgası ulusal elektrik şebekesine büyük bir yük bindirdi."],
      ["polar", "kutupla ilgili, kutup", "🐻‍❄️", "Polar regions are warming faster than any other part of the planet.", "Kutup bölgeleri gezegenin diğer tüm bölgelerinden daha hızlı ısınıyor."],
      ["blackout", "genel elektrik kesintisi, karartma", "🌑", "The storm caused a blackout across the whole city for six hours.", "Fırtına bütün şehirde altı saat süren bir elektrik kesintisine yol açtı."],
      ["energy-efficient", "enerji tasarruflu, verimli", "💡", "We replaced our old fridge with a more energy-efficient model.", "Eski buzdolabımızı daha enerji tasarruflu bir modelle değiştirdik."],
      ["ice cap", "buzul örtüsü", "🧊", "Scientists measure how fast the polar ice cap is shrinking every year.", "Bilim insanları kutup buzul örtüsünün her yıl ne kadar hızlı küçüldüğünü ölçüyor."],
      ["extreme weather", "aşırı hava olayları", "🌪️", "Extreme weather is becoming more common in many parts of the world.", "Aşırı hava olayları dünyanın birçok yerinde daha sık görülmeye başladı."],
      ["rainfall", "yağış miktarı", "🌧️", "The region had very little rainfall this year, and farmers are worried.", "Bölge bu yıl çok az yağış aldı ve çiftçiler endişeli."],
      ["humidity", "nem", "💦", "The heat is bearable, but the humidity makes it hard to breathe.", "Sıcağa katlanılabiliyor ama nem nefes almayı zorlaştırıyor."],
      ["carbon dioxide", "karbondioksit", "🌫️", "Trees absorb carbon dioxide and release oxygen into the air.", "Ağaçlar karbondioksiti emer ve havaya oksijen bırakır."],
      ["methane", "metan", "🐄", "Cows produce a surprising amount of methane, which warms the planet.", "İnekler gezegeni ısıtan şaşırtıcı miktarda metan üretir."],
      ["offset", "dengelemek, telafi etmek", "⚖️", "The company plants trees to offset the pollution from its flights.", "Şirket uçuşlarından kaynaklanan kirliliği dengelemek için ağaç dikiyor."],
      ["net zero", "net sıfır emisyon", "🎯", "The government promised to reach net zero by the middle of the century.", "Hükümet yüzyılın ortasına kadar net sıfıra ulaşma sözü verdi."],
      ["reusable", "tekrar kullanılabilir", "♻️", "I always carry a reusable bottle instead of buying water.", "Su satın almak yerine her zaman tekrar kullanılabilir bir şişe taşırım."],
      ["disposable", "tek kullanımlık", "🥤", "Many cafés no longer give out disposable cups to their customers.", "Birçok kafe artık müşterilerine tek kullanımlık bardak vermiyor."],
      ["hazardous", "tehlikeli, zararlı", "⚠️", "Old batteries are hazardous and should never go in the normal bin.", "Eski piller tehlikelidir ve asla normal çöp kutusuna atılmamalıdır."],
      ["pesticide", "tarım ilacı, böcek ilacı", "🧴", "Some farmers have stopped using pesticide because it harms the bees.", "Bazı çiftçiler arılara zarar verdiği için tarım ilacı kullanmayı bıraktı."],
      ["fertilizer", "gübre", "🌱", "Too much fertilizer can wash into rivers and kill the fish.", "Fazla gübre nehirlere karışıp balıkları öldürebilir."],
      ["organic farming", "organik tarım", "🥕", "Organic farming takes more effort, but the soil stays healthier.", "Organik tarım daha fazla emek ister ama toprak daha sağlıklı kalır."],
      ["sewage", "kanalizasyon atığı, lağım", "🚽", "The beach was closed after sewage leaked into the sea.", "Lağım suyu denize sızdıktan sonra plaj kapatıldı."],
      ["drinking water", "içme suyu", "🚰", "Millions of people still do not have access to clean drinking water.", "Milyonlarca insanın hâlâ temiz içme suyuna erişimi yok."],
      ["water shortage", "su sıkıntısı", "🏜️", "The city introduced strict rules because of the water shortage.", "Şehir su sıkıntısı nedeniyle katı kurallar getirdi."],
      ["scarcity", "kıtlık, azlık", "📉", "The scarcity of fresh water could lead to conflict between countries.", "Tatlı suyun azlığı ülkeler arasında çatışmaya yol açabilir."],
      ["deplete", "tüketmek, azaltmak", "🪫", "If we keep fishing like this, we will deplete the oceans.", "Böyle avlanmaya devam edersek okyanusları tüketeceğiz."],
      ["dispose of", "elden çıkarmak, atmak", "🗑️", "Please dispose of your old phone at a proper recycling point.", "Lütfen eski telefonunu uygun bir geri dönüşüm noktasında elden çıkar."],
      ["solar farm", "güneş enerjisi santrali", "🌞", "A huge solar farm now covers the dry fields outside the village.", "Köyün dışındaki kuru tarlaları artık dev bir güneş enerjisi santrali kaplıyor."],
      ["preserve", "korumak, muhafaza etmek", "🏞️", "We must preserve these wetlands for future generations.", "Bu sulak alanları gelecek nesiller için korumalıyız."],
      ["restore", "eski hâline getirmek, onarmak", "🔧", "Volunteers are working hard to restore the damaged coastline.", "Gönüllüler hasar görmüş kıyı şeridini eski hâline getirmek için çok çalışıyor."],
      ["reforestation", "yeniden ağaçlandırma", "🌳", "The reforestation project has planted over a million trees so far.", "Yeniden ağaçlandırma projesi şimdiye kadar bir milyondan fazla ağaç dikti."],
      ["extinction", "nesli tükenme", "🦤", "Many frogs are facing extinction because of disease and habitat loss.", "Birçok kurbağa türü hastalık ve yaşam alanı kaybı yüzünden yok olma tehlikesiyle karşı karşıya."],
      ["ban", "yasaklamak, yasak", "🚫", "Several cities decided to ban diesel cars from the centre.", "Birkaç şehir dizel arabaları merkezden yasaklamaya karar verdi."],
      ["off-grid", "şebekeden bağımsız", "🏕️", "They live completely off-grid in a cabin with solar panels.", "Güneş panelli bir kulübede tamamen şebekeden bağımsız yaşıyorlar."],
      ["wind farm", "rüzgâr enerjisi santrali", "🌬️", "The new wind farm stands on the hills above the coast.", "Yeni rüzgâr santrali kıyının üstündeki tepelerde duruyor."],
      ["emit", "salmak, yaymak", "💨", "Older cars emit far more harmful gases than modern ones.", "Eski arabalar modern olanlardan çok daha fazla zararlı gaz salar."],
      ["absorb", "emmek, soğurmak", "🧽", "The oceans absorb a large part of the extra heat on Earth.", "Okyanuslar Dünya'daki fazla ısının büyük bir kısmını emer."],
      ["generate", "üretmek", "⚡", "These wind turbines generate electricity for about five thousand homes.", "Bu rüzgâr türbinleri yaklaşık beş bin ev için elektrik üretiyor."],
      ["consumption", "tüketim", "📊", "Our energy consumption drops a lot when we turn off the heating.", "Isıtmayı kapattığımızda enerji tüketimimiz çok düşüyor."],
      ["pollutant", "kirletici madde", "🧪", "Lead was once a common pollutant in the air of big cities.", "Kurşun bir zamanlar büyük şehirlerin havasında yaygın bir kirletici maddeydi."],
      ["appliance", "ev aleti", "🔌", "The washing machine is the appliance that uses the most energy in our flat.", "Çamaşır makinesi dairemizde en çok enerji harcayan ev aleti."],
      ["thermostat", "termostat", "🌡️", "Turning the thermostat down by one degree can save a lot of money.", "Termostatı bir derece düşürmek çok para tasarrufu sağlayabilir."],
      ["utility bill", "fatura, su elektrik gaz faturası", "🧾", "Our utility bill doubled this winter because of the cold weather.", "Soğuk hava yüzünden bu kış faturamız iki katına çıktı."],
      ["meter", "sayaç", "🔢", "A technician came to read the gas meter this morning.", "Bu sabah gaz sayacını okumak için bir teknisyen geldi."],
      ["rechargeable", "şarj edilebilir", "🔋", "Rechargeable batteries cost more at first but save money later.", "Şarj edilebilir piller başta daha pahalıdır ama sonradan para kazandırır."],
      ["electric vehicle", "elektrikli araç", "🚗", "He sold his old car and bought an electric vehicle last month.", "Eski arabasını sattı ve geçen ay elektrikli bir araç aldı."],
      ["charging station", "şarj istasyonu", "🔌", "There is a charging station in the car park behind the supermarket.", "Süpermarketin arkasındaki otoparkta bir şarj istasyonu var."],
      ["fuel efficiency", "yakıt verimliliği", "⛽", "Good tyres and slow driving can improve your fuel efficiency.", "İyi lastikler ve yavaş sürüş yakıt verimliliğini artırabilir."],
      ["petrol", "benzin", "⛽", "The price of petrol has gone up again this week.", "Benzinin fiyatı bu hafta yine arttı."],
      ["diesel", "dizel, mazot", "🛢️", "Most of the trucks on this road still run on diesel.", "Bu yoldaki kamyonların çoğu hâlâ dizelle çalışıyor."],
      ["coal", "kömür", "⚫", "The town grew rich from coal, but the mines closed decades ago.", "Kasaba kömür sayesinde zenginleşti ama madenler onlarca yıl önce kapandı."],
      ["crude oil", "ham petrol", "🛢️", "The price of crude oil affects almost everything we buy.", "Ham petrolün fiyatı aldığımız neredeyse her şeyi etkiler."],
      ["natural gas", "doğal gaz", "🔥", "Most homes in our city are heated with natural gas.", "Şehrimizdeki evlerin çoğu doğal gazla ısıtılıyor."],
      ["pipeline", "boru hattı", "🚇", "The new pipeline will carry gas across three different countries.", "Yeni boru hattı gazı üç farklı ülkeden geçirerek taşıyacak."],
      ["drilling", "sondaj", "🛠️", "Local people protested against offshore drilling near their beaches.", "Yerel halk plajlarının yakınındaki açık deniz sondajını protesto etti."],
      ["mining", "madencilik", "⛏️", "Mining has left deep scars on the hills around the village.", "Madencilik köyün etrafındaki tepelerde derin izler bıraktı."],
      ["refinery", "rafineri", "🏭", "The refinery turns crude oil into petrol and other fuels.", "Rafineri ham petrolü benzine ve diğer yakıtlara dönüştürür."],
      ["oil spill", "petrol sızıntısı", "🐧", "The oil spill killed thousands of seabirds along the coast.", "Petrol sızıntısı kıyı boyunca binlerce deniz kuşunu öldürdü."],
      ["ecological", "ekolojik", "🌿", "Building the airport here would be an ecological disaster for the birds.", "Havalimanını buraya inşa etmek kuşlar için ekolojik bir felaket olur."],
      ["geothermal", "jeotermal", "♨️", "Iceland uses geothermal energy to heat most of its homes.", "İzlanda evlerinin çoğunu ısıtmak için jeotermal enerji kullanıyor."],
      ["biomass", "biyokütle", "🪵", "The plant burns biomass such as wood chips and farm waste.", "Santral odun yongası ve tarım atığı gibi biyokütle yakıyor."],
      ["biofuel", "biyoyakıt", "🌽", "Some airlines are testing biofuel made from used cooking oil.", "Bazı havayolları kullanılmış yemeklik yağdan yapılan biyoyakıtı test ediyor."],
      ["tidal energy", "gelgit enerjisi", "🌊", "Tidal energy is reliable because the sea moves in and out every day.", "Gelgit enerjisi güvenilirdir çünkü deniz her gün yükselip alçalır."],
      ["famine", "kıtlık, açlık felaketi", "🌾", "Years of drought led to a terrible famine in the region.", "Yıllarca süren kuraklık bölgede korkunç bir kıtlığa yol açtı."],
      ["crop failure", "ürün kaybı, rekolte kaybı", "🥀", "A single crop failure can ruin a small farmer completely.", "Tek bir ürün kaybı küçük bir çiftçiyi tamamen mahvedebilir."],
      ["flash flood", "ani sel", "🌊", "The flash flood swept several cars down the narrow street.", "Ani sel birkaç arabayı dar sokak boyunca sürükledi."],
      ["storm surge", "fırtına kabarması", "🌀", "The storm surge pushed seawater deep into the coastal town.", "Fırtına kabarması deniz suyunu kıyı kasabasının içlerine kadar itti."],
      ["monsoon", "muson yağmuru", "☔", "During the monsoon, some roads become rivers for several weeks.", "Muson döneminde bazı yollar birkaç hafta boyunca nehre dönüşür."],
      ["environmentalist", "çevreci", "🧑‍🌾", "The environmentalist spoke at the meeting about saving the local forest.", "Çevreci, toplantıda yerel ormanı kurtarmak hakkında konuştu."],
      ["desertification", "çölleşme", "🏜️", "Desertification is turning fertile land into dry, empty dust.", "Çölleşme verimli toprakları kuru, boş bir toza dönüştürüyor."],
      ["thaw", "çözülmek, erimek", "🌡️", "When the frozen ground starts to thaw, it releases old gases.", "Donmuş toprak çözülmeye başladığında eski gazları serbest bırakır."],
      ["threat", "tehdit", "⚠️", "Rising sea levels are a real threat to many island nations.", "Yükselen deniz seviyeleri birçok ada ülkesi için gerçek bir tehdit."],
      ["devastating", "yıkıcı", "💥", "The fires had a devastating effect on the local wildlife.", "Yangınların yerel yaban hayatı üzerinde yıkıcı bir etkisi oldu."],
      ["catastrophic", "felaket boyutunda", "🔥", "Scientists warn that further warming could have catastrophic results.", "Bilim insanları daha fazla ısınmanın felaket boyutunda sonuçları olabileceği konusunda uyarıyor."],
      ["clean-up", "temizlik çalışması", "🧤", "Hundreds of volunteers joined the beach clean-up on Sunday morning.", "Pazar sabahı yüzlerce gönüllü plaj temizliğine katıldı."],
      ["self-sufficient", "kendi kendine yeten", "🥬", "The farm is almost self-sufficient in both food and energy.", "Çiftlik hem yiyecek hem enerji açısından neredeyse kendi kendine yetiyor."],
      ["short-sighted", "ileriyi göremeyen, kısa vadeli düşünen", "🙈", "Cutting the climate budget would be a short-sighted decision.", "İklim bütçesini kısmak ileriyi göremeyen bir karar olur."],
      ["raise awareness", "farkındalık yaratmak", "📢", "The students made a short film to raise awareness about plastic waste.", "Öğrenciler plastik atık konusunda farkındalık yaratmak için kısa bir film çekti."],
      ["green energy", "yeşil enerji", "🍃", "Our electricity provider offers a cheaper plan for green energy.", "Elektrik sağlayıcımız yeşil enerji için daha ucuz bir tarife sunuyor."],
      ["environmentally friendly", "çevre dostu", "🌎", "They chose an environmentally friendly way to heat their new house.", "Yeni evlerini ısıtmak için çevre dostu bir yöntem seçtiler."],
      ["upcycle", "ileri dönüştürmek", "🪑", "She likes to upcycle old furniture and sell it online.", "Eski mobilyaları ileri dönüştürüp internetten satmayı seviyor."],
      ["microplastic", "mikroplastik", "🔬", "Researchers found microplastic in the stomachs of many small fish.", "Araştırmacılar birçok küçük balığın midesinde mikroplastik buldu."],
      ["overfishing", "aşırı avlanma", "🎣", "Overfishing has emptied large parts of the sea in just a few decades.", "Aşırı avlanma sadece birkaç on yılda denizin büyük kısımlarını boşalttı."],
      ["overpopulation", "aşırı nüfus", "👥", "Some experts believe overpopulation puts too much pressure on resources.", "Bazı uzmanlar aşırı nüfusun kaynaklar üzerinde çok fazla baskı yarattığına inanıyor."],
      ["habitat loss", "yaşam alanı kaybı", "🏚️", "Habitat loss is the main reason many birds are disappearing.", "Yaşam alanı kaybı birçok kuşun ortadan kaybolmasının ana nedeni."],
      ["climate crisis", "iklim krizi", "🆘", "Young people are demanding stronger action on the climate crisis.", "Gençler iklim krizi konusunda daha güçlü adımlar atılmasını talep ediyor."],
      ["carbon tax", "karbon vergisi", "💰", "A carbon tax makes companies pay for the pollution they create.", "Karbon vergisi şirketlerin yarattıkları kirliliğin bedelini ödemesini sağlar."],
      ["finite", "sınırlı, tükenebilir", "⏳", "Oil and gas are finite resources that will not last forever.", "Petrol ve gaz sonsuza kadar sürmeyecek tükenebilir kaynaklardır."],
      ["abundant", "bol, bereketli", "☀️", "Sunlight is abundant here, so solar power makes a lot of sense.", "Burada güneş ışığı bol, bu yüzden güneş enerjisi çok mantıklı."],
      ["scarce", "kıt, az bulunan", "🫗", "Water becomes scarce in the summer months, so we use it carefully.", "Yaz aylarında su kıtlaşır, bu yüzden onu dikkatli kullanırız."],
      ["sustainability", "sürdürülebilirlik", "🔄", "The company hired a manager to focus only on sustainability.", "Şirket yalnızca sürdürülebilirliğe odaklanacak bir yönetici işe aldı."],
      ["switch off", "kapatmak", "🔦", "Please switch off the lights when you leave the meeting room.", "Lütfen toplantı odasından çıkarken ışıkları kapat."],
      ["standby", "bekleme modu", "📺", "Leaving the TV on standby still uses a small amount of power.", "Televizyonu bekleme modunda bırakmak yine de az miktarda elektrik harcar."],
      ["solar energy", "güneş enerjisi", "🌞", "The school now gets half of its power from solar energy.", "Okul artık elektriğinin yarısını güneş enerjisinden alıyor."],
      ["kilowatt", "kilovat", "⚡", "Our bill shows how many kilowatt hours we used each day.", "Faturamız her gün kaç kilovatsaat harcadığımızı gösteriyor."],
      ["voltage", "voltaj, gerilim", "🔋", "Check the voltage before you plug in a device from abroad.", "Yurt dışından gelen bir cihazı takmadan önce voltajı kontrol et."],
      ["generator", "jeneratör", "🔊", "The hospital switched to its own generator during the blackout.", "Hastane elektrik kesintisi sırasında kendi jeneratörüne geçti."],
      ["greenwashing", "yeşil aklama, sahte çevrecilik", "🎭", "Calling a plastic bottle natural is a classic example of greenwashing.", "Plastik bir şişeye doğal demek klasik bir yeşil aklama örneğidir."],
      ["carbon capture", "karbon yakalama", "🏗️", "Carbon capture technology traps gases before they reach the air.", "Karbon yakalama teknolojisi gazları havaya ulaşmadan önce hapseder."],
      ["climate summit", "iklim zirvesi", "🤝", "World leaders met at the climate summit but agreed on very little.", "Dünya liderleri iklim zirvesinde bir araya geldi ama çok az konuda anlaştı."],
      ["permafrost", "donmuş toprak tabakası", "❄️", "Roads in the far north are cracking as the permafrost melts.", "Donmuş toprak tabakası eridikçe uzak kuzeydeki yollar çatlıyor."],
      ["acid rain", "asit yağmuru", "🌧️", "Acid rain damaged the stone statues in the old town square.", "Asit yağmuru eski kent meydanındaki taş heykellere zarar verdi."],
      ["waste management", "atık yönetimi", "🚛", "Good waste management keeps the streets clean and the air healthy.", "İyi bir atık yönetimi sokakları temiz, havayı sağlıklı tutar."],
      ["e-waste", "elektronik atık", "📱", "Old phones and laptops create tons of e-waste every year.", "Eski telefonlar ve dizüstü bilgisayarlar her yıl tonlarca elektronik atık oluşturuyor."],
      ["water supply", "su şebekesi, su kaynağı", "🚿", "The earthquake damaged the water supply for the entire district.", "Deprem bütün ilçenin su şebekesine zarar verdi."],
      ["wastewater", "atık su", "🚰", "The factory must clean its wastewater before it goes into the river.", "Fabrika atık suyunu nehre gitmeden önce arıtmak zorunda."]
    ] },
  { id: "lib5b", title: "Doğa, Coğrafya ve Hayvanlar", icon: "🦊", cefr: "B2", desc: "Yer şekilleri, doğa olayları ve hayvanlar dünyasını anlatmak için gereken kelimeler.",
    words: [
      ["continent", "kıta", "🗺️", "Africa is the second largest continent in the world.", "Afrika dünyanın en büyük ikinci kıtasıdır."],
      ["peninsula", "yarımada", "🏝️", "We rented a small house at the tip of the peninsula.", "Yarımadanın ucunda küçük bir ev kiraladık."],
      ["archipelago", "takımada", "🏝️", "The archipelago has more than a hundred islands, but few are inhabited.", "Takımadada yüzden fazla ada var ama pek azında insan yaşıyor."],
      ["equator", "ekvator", "🌐", "Countries near the equator have warm weather all year round.", "Ekvatora yakın ülkelerde yıl boyu sıcak hava olur."],
      ["hemisphere", "yarıküre", "🌏", "When it is summer in the northern hemisphere, it is winter in Australia.", "Kuzey yarıkürede yaz olduğunda Avustralya'da kış olur."],
      ["latitude", "enlem", "📐", "The two cities are at the same latitude but have very different climates.", "İki şehir aynı enlemde ama iklimleri çok farklı."],
      ["longitude", "boylam", "🧭", "Sailors once found it very hard to calculate their longitude at sea.", "Denizciler bir zamanlar denizde boylamlarını hesaplamakta çok zorlanırdı."],
      ["altitude", "rakım, yükseklik", "⛰️", "At this altitude, even a short walk makes you breathe heavily.", "Bu rakımda kısa bir yürüyüş bile nefes nefese kalmana neden olur."],
      ["terrain", "arazi", "🥾", "The terrain was so rocky that we had to leave the car behind.", "Arazi o kadar kayalıktı ki arabayı geride bırakmak zorunda kaldık."],
      ["plateau", "yayla, plato", "🏔️", "Shepherds take their animals up to the plateau every summer.", "Çobanlar her yaz hayvanlarını yaylaya çıkarır."],
      ["canyon", "kanyon", "🏜️", "We hiked down to the bottom of the canyon and camped by the river.", "Kanyonun dibine kadar yürüyüp nehrin kenarında kamp kurduk."],
      ["gorge", "boğaz, dar vadi", "🪨", "A narrow wooden bridge crosses the gorge high above the water.", "Dar bir tahta köprü boğazın üzerinden suyun çok yukarısında geçiyor."],
      ["ridge", "sırt, bayır", "🏔️", "We walked along the ridge and could see two valleys at once.", "Sırt boyunca yürüdük ve aynı anda iki vadiyi görebildik."],
      ["peak", "zirve, doruk", "🗻", "The peak was covered in snow even in the middle of July.", "Zirve temmuz ortasında bile karla kaplıydı."],
      ["foothills", "dağ eteği", "⛰️", "Our village lies in the foothills, about an hour from the mountains.", "Köyümüz dağ eteklerinde, dağlara yaklaşık bir saat uzaklıkta."],
      ["slope", "yamaç, eğim", "⛷️", "Their house sits on a steep slope covered in olive trees.", "Evleri zeytin ağaçlarıyla kaplı dik bir yamaçta duruyor."],
      ["cliff", "uçurum, yalıyar", "🧗", "Do not walk too close to the edge of the cliff.", "Uçurumun kenarına çok yakın yürüme."],
      ["cave", "mağara", "🦇", "Thousands of bats live in the dark cave behind the waterfall.", "Şelalenin arkasındaki karanlık mağarada binlerce yarasa yaşıyor."],
      ["waterfall", "şelale", "🏞️", "You can hear the waterfall long before you actually see it.", "Şelaleyi görmeden çok önce sesini duyabilirsin."],
      ["stream", "dere", "💧", "The children built a small dam across the stream behind the farm.", "Çocuklar çiftliğin arkasındaki derenin üzerine küçük bir set yaptı."],
      ["riverbank", "nehir kıyısı", "🎣", "My grandfather spent every Sunday fishing on the riverbank.", "Dedem her pazarı nehir kıyısında balık tutarak geçirirdi."],
      ["estuary", "haliç, nehir ağzı", "🦢", "Many birds feed in the estuary where the river meets the sea.", "Birçok kuş nehrin denizle buluştuğu halicte beslenir."],
      ["delta", "delta", "🔺", "The river splits into dozens of channels as it forms a delta.", "Nehir bir delta oluştururken düzinelerce kola ayrılır."],
      ["tributary", "kol, ana nehre dökülen akarsu", "〰️", "This small river is a tributary of the much larger one in the south.", "Bu küçük nehir güneydeki çok daha büyük nehrin bir koludur."],
      ["swamp", "bataklık", "🐊", "Alligators hide in the swamp and wait quietly for their prey.", "Timsahlar bataklıkta saklanıp avlarını sessizce bekler."],
      ["marsh", "sazlık, bataklık", "🌾", "The marsh is full of tall grass and noisy frogs at night.", "Sazlık gece uzun otlar ve gürültücü kurbağalarla dolu."],
      ["wetland", "sulak alan", "🦩", "The wetland is home to flamingos for part of the year.", "Sulak alan yılın bir bölümünde flamingolara ev sahipliği yapıyor."],
      ["meadow", "çayır", "🌼", "We had a picnic in a meadow full of wild flowers.", "Kır çiçekleriyle dolu bir çayırda piknik yaptık."],
      ["grassland", "otlak, bozkır", "🐃", "Huge herds of animals move across the grassland in search of water.", "Büyük hayvan sürüleri su aramak için otlakta yer değiştirir."],
      ["savanna", "savan", "🦒", "Giraffes and zebras share the open savanna with many other animals.", "Zürafalar ve zebralar açık savanı birçok başka hayvanla paylaşır."],
      ["tundra", "tundra", "🦌", "Very few trees can survive in the cold, windy tundra.", "Soğuk ve rüzgârlı tundrada çok az ağaç yaşayabilir."],
      ["jungle", "orman, cengel", "🐒", "The guide used a large knife to cut a path through the jungle.", "Rehber ormanda bir yol açmak için büyük bir bıçak kullandı."],
      ["oasis", "vaha", "🌴", "After two days in the desert, the oasis looked like paradise.", "Çölde geçen iki günün ardından vaha cennet gibi göründü."],
      ["sand dune", "kum tepesi", "🏜️", "We watched the sunset from the top of a huge sand dune.", "Gün batımını devasa bir kum tepesinin üstünden izledik."],
      ["bay", "koy, körfez", "⛵", "The boats stay in the quiet bay when the sea gets rough.", "Deniz dalgalandığında tekneler sakin koyda kalır."],
      ["gulf", "körfez", "🌊", "Oil tankers cross the gulf every day on their way to Asia.", "Petrol tankerleri her gün Asya'ya giderken körfezi geçiyor."],
      ["strait", "boğaz", "🚢", "Huge ships pass through the narrow strait between the two continents.", "Dev gemiler iki kıta arasındaki dar boğazdan geçer."],
      ["shoreline", "kıyı çizgisi", "🏖️", "We walked along the shoreline collecting shells and smooth stones.", "Kıyı boyunca deniz kabukları ve pürüzsüz taşlar toplayarak yürüdük."],
      ["tide", "gelgit", "🌊", "At low tide, you can walk across the sand to the small island.", "Alçak gelgitte kumların üzerinden küçük adaya yürüyebilirsin."],
      ["current", "akıntı", "🏊", "The current was too strong, so the lifeguards closed the beach.", "Akıntı çok güçlüydü, bu yüzden cankurtaranlar plajı kapattı."],
      ["coral reef", "mercan resifi", "🐠", "Divers come from all over the world to see the coral reef.", "Dalgıçlar mercan resifini görmek için dünyanın her yerinden geliyor."],
      ["lagoon", "lagün, deniz gölü", "🏝️", "The water in the lagoon is warm, calm and incredibly clear.", "Lagündeki su ılık, sakin ve inanılmaz derecede berrak."],
      ["iceberg", "buzdağı", "🧊", "Only a small part of an iceberg can be seen above the water.", "Bir buzdağının sadece küçük bir kısmı suyun üstünde görülebilir."],
      ["geyser", "gayzer, kaynaç", "♨️", "The geyser shoots hot water into the air every forty minutes.", "Gayzer her kırk dakikada bir havaya sıcak su fışkırtıyor."],
      ["hot spring", "kaplıca, sıcak su kaynağı", "♨️", "After the long hike, we relaxed in a natural hot spring.", "Uzun yürüyüşten sonra doğal bir kaplıcada dinlendik."],
      ["volcano", "yanardağ", "🌋", "The volcano has been quiet for a hundred years, but it is not dead.", "Yanardağ yüz yıldır sessiz ama sönmüş değil."],
      ["eruption", "patlama, püskürme", "🌋", "The eruption covered nearby villages in a thick layer of ash.", "Püskürme yakındaki köyleri kalın bir kül tabakasıyla kapladı."],
      ["lava", "lav", "🔥", "Red lava flowed slowly down the side of the mountain.", "Kırmızı lav dağın yamacından yavaşça aşağı aktı."],
      ["earthquake", "deprem", "🏚️", "Every family should have an emergency bag ready in case of an earthquake.", "Her ailenin deprem ihtimaline karşı hazır bir acil durum çantası olmalı."],
      ["tremor", "sarsıntı", "📳", "We felt a small tremor in the night, but nothing was damaged.", "Gece küçük bir sarsıntı hissettik ama hiçbir şey zarar görmedi."],
      ["avalanche", "çığ", "🏔️", "The ski resort closed two slopes because of the avalanche risk.", "Kayak merkezi çığ riski nedeniyle iki pisti kapattı."],
      ["tsunami", "tsunami, dev dalga", "🌊", "Sirens warn people to move to higher ground if a tsunami is coming.", "Siren sesleri tsunami geliyorsa insanları daha yüksek yerlere çıkmaları için uyarır."],
      ["mammal", "memeli", "🐋", "The whale is a mammal, so it has to come up to breathe.", "Balina bir memelidir, bu yüzden nefes almak için yüzeye çıkmak zorundadır."],
      ["reptile", "sürüngen", "🦎", "A reptile cannot control its body temperature, so it lies in the sun.", "Bir sürüngen vücut ısısını kontrol edemez, bu yüzden güneşte yatar."],
      ["amphibian", "amfibi, iki yaşamlı", "🐸", "An amphibian can live both in water and on land.", "Bir amfibi hem suda hem karada yaşayabilir."],
      ["predator", "yırtıcı hayvan, avcı", "🐆", "The lion is the top predator in this part of Africa.", "Aslan Afrika'nın bu bölgesindeki en üst avcıdır."],
      ["prey", "av", "🐇", "Rabbits are easy prey for foxes and large birds.", "Tavşanlar tilkiler ve büyük kuşlar için kolay avdır."],
      ["herd", "sürü", "🐘", "A herd of elephants walked slowly towards the river.", "Bir fil sürüsü yavaşça nehre doğru yürüdü."],
      ["flock", "kuş veya koyun sürüsü", "🐑", "A flock of sheep blocked the road for almost ten minutes.", "Bir koyun sürüsü yolu neredeyse on dakika boyunca kapattı."],
      ["swarm", "oğul, böcek sürüsü", "🐝", "A swarm of bees landed on the tree in our garden.", "Bahçemizdeki ağaca bir arı oğulu kondu."],
      ["nest", "yuva", "🪺", "A pair of birds built a nest above our front door.", "Bir çift kuş ön kapımızın üstüne yuva yaptı."],
      ["burrow", "oyuk, yuva, kazmak", "🕳️", "The rabbit disappeared into its burrow as soon as it saw us.", "Tavşan bizi görür görmez yuvasına girip kayboldu."],
      ["den", "in", "🐺", "The wolves return to their den to protect their young.", "Kurtlar yavrularını korumak için inlerine döner."],
      ["hive", "arı kovanı", "🍯", "My uncle keeps three hives and sells the honey at the market.", "Amcam üç kovan besliyor ve balı pazarda satıyor."],
      ["hibernate", "kış uykusuna yatmak", "😴", "Bears eat as much as possible before they hibernate for the winter.", "Ayılar kış uykusuna yatmadan önce olabildiğince çok yer."],
      ["migration", "göç", "🦅", "The autumn migration of storks is an amazing sight from the hills.", "Leyleklerin sonbahar göçü tepelerden muhteşem bir manzaradır."],
      ["camouflage", "kamuflaj", "🦎", "The lizard uses camouflage to look exactly like the rock.", "Kertenkele tam olarak kaya gibi görünmek için kamuflaj kullanır."],
      ["breed", "üremek, cins", "🐕", "Many animals breed in the spring when food is easy to find.", "Birçok hayvan yiyecek bulmanın kolay olduğu ilkbaharda ürer."],
      ["offspring", "yavru, döl", "🐣", "Some fish produce thousands of offspring, but only a few survive.", "Bazı balıklar binlerce yavru üretir ama sadece birkaçı hayatta kalır."],
      ["cub", "yavru, aslan veya ayı yavrusu", "🐻", "The bear stayed close to her cub the whole time.", "Ayı yavrusunun yanından hiç ayrılmadı."],
      ["fur", "kürk, post", "🐈", "Thick fur keeps the animal warm in freezing temperatures.", "Kalın kürk, hayvanı dondurucu soğukta sıcak tutar."],
      ["feather", "tüy", "🪶", "My daughter found a long blue feather in the park.", "Kızım parkta uzun mavi bir tüy buldu."],
      ["beak", "gaga", "🐦", "The bird used its sharp beak to break open the seed.", "Kuş tohumu kırıp açmak için sivri gagasını kullandı."],
      ["claw", "pençe, tırnak", "🦀", "The crab raised one claw as a warning to the curious child.", "Yengeç meraklı çocuğa uyarı olarak bir kıskacını kaldırdı."],
      ["paw", "pati", "🐾", "The dog left muddy paw prints all over the kitchen floor.", "Köpek mutfağın her yerine çamurlu pati izleri bıraktı."],
      ["fin", "yüzgeç", "🦈", "Swimmers panicked when they saw a fin above the water.", "Yüzücüler suyun üstünde bir yüzgeç görünce paniğe kapıldı."],
      ["horn", "boynuz", "🦏", "The rhino uses its horn to defend itself and its young.", "Gergedan kendini ve yavrusunu korumak için boynuzunu kullanır."],
      ["tusk", "fildişi, uzun diş", "🐘", "An elephant uses its tusk to dig for water and roots.", "Fil su ve kök bulmak için kazarken uzun dişini kullanır."],
      ["hoof", "toynak", "🐎", "The horse hurt its hoof on a sharp stone in the field.", "At, tarladaki sivri bir taşa basıp toynağını yaraladı."],
      ["venom", "zehir, hayvan zehri", "🐍", "Doctors used the snake's venom to make a new medicine.", "Doktorlar yılanın zehrini yeni bir ilaç yapmak için kullandı."],
      ["venomous", "zehirli, sokan veya ısıran", "🦂", "This spider looks harmless, but it is actually very venomous.", "Bu örümcek zararsız görünüyor ama aslında çok zehirli."],
      ["poisonous", "zehirli, yenince zehirleyen", "🍄", "Some of these mushrooms are poisonous, so never eat them raw.", "Bu mantarların bazıları zehirlidir, bu yüzden onları asla çiğ yeme."],
      ["carnivore", "etobur", "🥩", "As a carnivore, the tiger needs a lot of meat every week.", "Bir etobur olarak kaplanın her hafta çok fazla ete ihtiyacı vardır."],
      ["herbivore", "otobur", "🥬", "The cow is a herbivore and spends most of the day eating grass.", "İnek bir otoburdur ve günün çoğunu ot yiyerek geçirir."],
      ["omnivore", "hepçil", "🍽️", "A bear is an omnivore, so it eats berries, fish and insects.", "Ayı bir hepçildir, bu yüzden meyve, balık ve böcek yer."],
      ["scavenger", "leşçil", "🦅", "Vultures are scavengers that clean up after other animals.", "Akbabalar diğer hayvanların artıklarını temizleyen leşçillerdir."],
      ["poaching", "kaçak avcılık", "🚔", "Poaching has nearly wiped out the rhinos in this region.", "Kaçak avcılık bu bölgedeki gergedanları neredeyse yok etti."],
      ["captivity", "esaret, kafeste yaşam", "🔒", "Animals born in captivity often cannot survive in the wild.", "Esaret altında doğan hayvanlar çoğu zaman vahşi doğada hayatta kalamaz."],
      ["in the wild", "vahşi doğada", "🌲", "Wolves usually live about eight years in the wild.", "Kurtlar vahşi doğada genellikle yaklaşık sekiz yıl yaşar."],
      ["wildlife reserve", "yaban hayatı koruma alanı", "🦓", "Hunting is strictly forbidden inside the wildlife reserve.", "Yaban hayatı koruma alanının içinde avlanmak kesinlikle yasaktır."],
      ["sanctuary", "barınak, koruma alanı", "🐴", "The donkey sanctuary takes care of old and injured animals.", "Eşek barınağı yaşlı ve yaralı hayvanlara bakıyor."],
      ["food chain", "besin zinciri", "🔗", "Losing one small insect can affect the whole food chain.", "Küçük bir böceğin yok olması bütün besin zincirini etkileyebilir."],
      ["wolf", "kurt", "🐺", "We heard a wolf howling somewhere in the forest at night.", "Gece ormanın bir yerinde uluyan bir kurt duyduk."],
      ["eagle", "kartal", "🦅", "An eagle circled high above the valley looking for food.", "Bir kartal yiyecek arayarak vadinin çok yukarısında daireler çizdi."],
      ["whale", "balina", "🐋", "We took a boat trip and saw a whale jump out of the water.", "Tekne turuna çıktık ve bir balinanın sudan sıçradığını gördük."],
      ["dolphin", "yunus", "🐬", "A dolphin swam next to our boat for several minutes.", "Bir yunus birkaç dakika boyunca teknemizin yanında yüzdü."],
      ["shark", "köpek balığı", "🦈", "Most kinds of shark are not dangerous to people at all.", "Köpek balığı türlerinin çoğu insanlar için hiç tehlikeli değildir."],
      ["octopus", "ahtapot", "🐙", "The octopus can change colour in less than a second.", "Ahtapot bir saniyeden kısa sürede renk değiştirebilir."],
      ["jellyfish", "denizanası", "🪼", "I got stung by a jellyfish on the first day of our holiday.", "Tatilimizin ilk gününde beni bir denizanası soktu."],
      ["tortoise", "kara kaplumbağası", "🐢", "Our neighbour's tortoise is older than my grandmother.", "Komşumuzun kaplumbağası babaannemden daha yaşlı."],
      ["turtle", "deniz kaplumbağası", "🐢", "Volunteers protect the beach where the turtle lays its eggs.", "Gönüllüler kaplumbağanın yumurtalarını bıraktığı plajı koruyor."],
      ["lizard", "kertenkele", "🦎", "A tiny lizard ran across the warm wall and disappeared.", "Minik bir kertenkele sıcak duvarın üzerinden koşup gözden kayboldu."],
      ["snake", "yılan", "🐍", "Wear boots when you walk here because there might be a snake in the grass.", "Burada yürürken bot giy çünkü otların arasında yılan olabilir."],
      ["spider", "örümcek", "🕷️", "There is a huge spider in the bathroom and I refuse to go in.", "Banyoda kocaman bir örümcek var ve içeri girmeyi reddediyorum."],
      ["mosquito", "sivrisinek", "🦟", "A single mosquito kept me awake for half the night.", "Tek bir sivrisinek gecenin yarısı boyunca beni uyutmadı."],
      ["crow", "karga", "🐦‍⬛", "That crow is clever enough to open our rubbish bin.", "O karga çöp kutumuzu açacak kadar zeki."],
      ["pigeon", "güvercin", "🕊️", "Tourists love feeding the pigeon flocks in the main square.", "Turistler ana meydandaki güvercin sürülerini beslemeyi çok seviyor."],
      ["bear", "ayı", "🐻", "Keep your food in the car, because a bear can smell it from far away.", "Yiyeceğini arabada tut, çünkü bir ayı onun kokusunu çok uzaktan alabilir."],
      ["goat", "keçi", "🐐", "The goat climbed onto the roof of the old shed.", "Keçi eski barakanın çatısına tırmandı."],
      ["donkey", "eşek", "🫏", "In the village, people still use a donkey to carry heavy loads.", "Köyde insanlar ağır yükleri taşımak için hâlâ eşek kullanıyor."]
    ] },
  { id: "lib5c", title: "Şehir, Mimari ve Ulaşım", icon: "🏙️", cefr: "B2", desc: "Şehir hayatı, binalar ve ulaşım hakkında rahatça konuşmak için gereken kelimeler.",
    words: [
      ["urban sprawl", "plansız kentsel yayılma", "🏘️", "Urban sprawl has swallowed the farms that once surrounded the city.", "Plansız kentsel yayılma bir zamanlar şehri çevreleyen çiftlikleri yuttu."],
      ["outskirts", "şehrin dış mahalleleri, kenar", "🛣️", "They moved to the outskirts because rents there are much lower.", "Kiralar çok daha düşük olduğu için şehrin dış mahallelerine taşındılar."],
      ["inner city", "şehrin eski merkezi, iç kesimleri", "🏙️", "The inner city has changed a lot in the last twenty years.", "Şehrin iç kesimleri son yirmi yılda çok değişti."],
      ["borough", "belediye bölgesi, ilçe", "🗺️", "Each borough of the city has its own library and sports centre.", "Şehrin her ilçesinin kendi kütüphanesi ve spor merkezi var."],
      ["residential area", "yerleşim bölgesi", "🏡", "Trucks are not allowed to drive through this residential area at night.", "Kamyonların gece bu yerleşim bölgesinden geçmesine izin verilmiyor."],
      ["industrial zone", "sanayi bölgesi", "🏭", "Most of the factories are in the industrial zone outside the town.", "Fabrikaların çoğu kasabanın dışındaki sanayi bölgesinde."],
      ["city council", "belediye meclisi", "🏛️", "The city council voted to build a new park by the river.", "Belediye meclisi nehrin kenarına yeni bir park yapılması yönünde oy kullandı."],
      ["underpass", "alt geçit", "🚇", "Use the underpass to cross the main road safely.", "Ana yolu güvenle geçmek için alt geçidi kullan."],
      ["infrastructure", "altyapı", "🚧", "The city needs to invest more in roads, pipes and other infrastructure.", "Şehrin yollara, borulara ve diğer altyapıya daha fazla yatırım yapması gerekiyor."],
      ["urban planning", "şehir planlaması", "📐", "Good urban planning makes it easy to live without a car.", "İyi bir şehir planlaması arabasız yaşamayı kolaylaştırır."],
      ["zoning", "imar düzenlemesi", "📋", "Zoning rules say no one can build higher than five floors here.", "İmar kuralları burada kimsenin beş kattan yüksek bina yapamayacağını söylüyor."],
      ["shanty town", "gecekondu mahallesi", "🏚️", "The shanty town grew quickly as people arrived from the countryside.", "Gecekondu mahallesi insanlar kırsaldan geldikçe hızla büyüdü."],
      ["housing estate", "toplu konut sitesi", "🏘️", "She grew up on a large housing estate with hundreds of identical flats.", "Yüzlerce birbirinin aynısı dairenin olduğu büyük bir toplu konut sitesinde büyüdü."],
      ["high-rise", "yüksek bina, çok katlı", "🏢", "They live on the twentieth floor of a high-rise near the station.", "İstasyonun yakınındaki yüksek bir binanın yirminci katında oturuyorlar."],
      ["detached house", "müstakil ev", "🏠", "Their dream is to buy a detached house with a big garden.", "Hayalleri büyük bahçeli müstakil bir ev almak."],
      ["terraced house", "sıra ev, bitişik nizam ev", "🏘️", "We live in a narrow terraced house, so we can hear our neighbours.", "Dar bir sıra evde yaşıyoruz, bu yüzden komşularımızı duyabiliyoruz."],
      ["cottage", "kır evi, küçük köy evi", "🏡", "We rented a stone cottage in the countryside for the weekend.", "Hafta sonu için kırsalda taştan bir kır evi kiraladık."],
      ["mansion", "konak, malikâne", "🏰", "The old mansion on the hill is now a luxury hotel.", "Tepedeki eski konak artık lüks bir otel."],
      ["monument", "anıt", "🗽", "The monument in the main square remembers the soldiers of the war.", "Ana meydandaki anıt savaşın askerlerini anıyor."],
      ["cathedral", "katedral", "⛪", "It took almost two hundred years to finish building the cathedral.", "Katedralin inşasını bitirmek neredeyse iki yüz yıl sürdü."],
      ["dome", "kubbe", "🕌", "The golden dome of the building shines in the afternoon sun.", "Binanın altın kubbesi öğleden sonra güneşinde parlıyor."],
      ["arch", "kemer", "🌉", "We walked under a stone arch into a quiet little square.", "Taş bir kemerin altından geçerek sessiz, küçük bir meydana girdik."],
      ["facade", "bina cephesi", "🏛️", "The facade of the old bank is covered in beautiful carvings.", "Eski bankanın cephesi güzel oymalarla kaplı."],
      ["terrace", "teras", "☕", "We had breakfast on the terrace with a view of the sea.", "Kahvaltıyı deniz manzaralı terasta yaptık."],
      ["courtyard", "avlu", "⛲", "The rooms of the old inn open onto a shady courtyard.", "Eski hanın odaları gölgeli bir avluya açılıyor."],
      ["staircase", "merdiven, merdiven boşluğu", "🪜", "The building has a beautiful spiral staircase made of marble.", "Binada mermerden yapılmış güzel bir döner merdiven var."],
      ["elevator", "asansör", "🛗", "The elevator was broken, so we carried the sofa up six floors.", "Asansör bozuktu, bu yüzden kanepeyi altı kat yukarı taşıdık."],
      ["basement", "bodrum katı", "🔦", "We keep our bikes and old boxes in the basement.", "Bisikletlerimizi ve eski kutularımızı bodrum katında tutuyoruz."],
      ["attic", "çatı katı, tavan arası", "📦", "I found my grandmother's old letters in a box in the attic.", "Tavan arasındaki bir kutuda babaannemin eski mektuplarını buldum."],
      ["rooftop", "çatı, çatı üstü", "🌇", "There is a rooftop bar with an amazing view of the whole city.", "Bütün şehrin muhteşem manzarasına sahip bir çatı barı var."],
      ["blueprint", "mimari plan, taslak", "📘", "The architect showed us the blueprint for the new library.", "Mimar bize yeni kütüphanenin planını gösterdi."],
      ["construction site", "şantiye", "🏗️", "You must wear a helmet when you enter the construction site.", "Şantiyeye girerken kask takmak zorundasın."],
      ["scaffolding", "iskele, yapı iskelesi", "🧱", "The church has been covered in scaffolding for almost three years.", "Kilise neredeyse üç yıldır iskeleyle kaplı."],
      ["crane", "vinç", "🏗️", "A giant crane lifted the steel beams to the top of the tower.", "Dev bir vinç çelik kirişleri kulenin tepesine kaldırdı."],
      ["historic", "tarihi", "🏯", "We stayed in a small hotel in the historic part of the city.", "Şehrin tarihi bölümündeki küçük bir otelde kaldık."],
      ["cobblestone", "parke taşı, arnavut kaldırımı", "🪨", "Walking on cobblestone streets in high heels is almost impossible.", "Arnavut kaldırımlı sokaklarda topuklu ayakkabıyla yürümek neredeyse imkânsız."],
      ["sidewalk", "kaldırım", "🚶", "People were sitting on the sidewalk outside the café.", "İnsanlar kafenin önündeki kaldırımda oturuyordu."],
      ["curb", "kaldırım kenarı, bordür", "🛑", "He parked so close to the curb that he scratched his tyre.", "Kaldırım kenarına o kadar yakın park etti ki lastiğini çizdi."],
      ["crosswalk", "yaya geçidi", "🚸", "Cars must stop when someone is waiting at the crosswalk.", "Biri yaya geçidinde bekliyorsa arabalar durmak zorunda."],
      ["intersection", "kavşak", "🚦", "There was an accident at the intersection near my office.", "Ofisimin yakınındaki kavşakta bir kaza oldu."],
      ["junction", "kavşak, yol ayrımı", "🔀", "Turn left at the next junction and you will see the hospital.", "Bir sonraki kavşaktan sola dönersen hastaneyi göreceksin."],
      ["lane", "şerit", "🛣️", "Trucks must stay in the right lane on the motorway.", "Kamyonlar otoyolda sağ şeritte kalmak zorunda."],
      ["one-way street", "tek yönlü sokak", "⬆️", "You cannot turn here because it is a one-way street.", "Burada dönemezsin çünkü burası tek yönlü bir sokak."],
      ["dead end", "çıkmaz sokak", "⛔", "The map told us to go left, but it was a dead end.", "Harita sola gitmemizi söyledi ama orası çıkmaz sokaktı."],
      ["detour", "dolambaçlı yol, sapma", "↪️", "We took a detour to avoid the traffic on the bridge.", "Köprüdeki trafikten kaçınmak için başka bir yoldan dolaştık."],
      ["diversion", "trafik yönlendirmesi, alternatif güzergâh", "🚧", "There is a diversion because the main road is closed for repairs.", "Ana yol onarım için kapalı olduğu için alternatif güzergâh var."],
      ["speed bump", "hız tümseği", "〰️", "Slow down, there is a speed bump right in front of the school.", "Yavaşla, okulun tam önünde bir hız tümseği var."],
      ["speed limit", "hız sınırı", "🔢", "The speed limit in the city centre is thirty kilometres an hour.", "Şehir merkezinde hız sınırı saatte otuz kilometre."],
      ["toll road", "paralı yol", "💳", "We took the toll road because it saves almost an hour.", "Neredeyse bir saat kazandırdığı için paralı yolu kullandık."],
      ["highway", "otoyol, ana yol", "🛣️", "The highway was empty because everyone had left the day before.", "Herkes bir gün önce yola çıktığı için otoyol boştu."],
      ["motorway", "otoyol", "🚙", "It is about two hours by motorway to the coast.", "Sahile otoyoldan yaklaşık iki saat sürüyor."],
      ["ring road", "çevre yolu", "⭕", "Take the ring road if you want to avoid driving through the centre.", "Merkezden geçmek istemiyorsan çevre yolunu kullan."],
      ["overpass", "üst geçit", "🌉", "A huge banner was hanging from the overpass above the motorway.", "Otoyolun üstündeki üst geçitten büyük bir pankart sarkıyordu."],
      ["tunnel", "tünel", "🚇", "My phone always loses signal when the train goes into the tunnel.", "Tren tünele girdiğinde telefonum hep çekmez oluyor."],
      ["parking lot", "otopark", "🅿️", "The parking lot at the mall is always full on Saturdays.", "Alışveriş merkezinin otoparkı cumartesileri hep dolu oluyor."],
      ["parking fine", "park cezası", "🎫", "I got a parking fine because I stayed ten minutes too long.", "On dakika fazla kaldığım için park cezası yedim."],
      ["tow away", "çekiciyle çekmek", "🚛", "If you park here, they will tow away your car in minutes.", "Buraya park edersen arabanı dakikalar içinde çekerler."],
      ["congestion", "trafik sıkışıklığı, yoğunluk", "🚗", "The new tram line has reduced congestion in the city centre.", "Yeni tramvay hattı şehir merkezindeki trafik sıkışıklığını azalttı."],
      ["gridlock", "trafik kilidi, tam tıkanıklık", "🚥", "One accident on the bridge caused gridlock across half the city.", "Köprüdeki tek bir kaza şehrin yarısında trafiği tamamen kilitledi."],
      ["commuter", "işe gidip gelen kişi", "🧑‍💼", "Every morning, thousands of commuters squeeze onto the same train.", "Her sabah binlerce kişi işe gitmek için aynı trene sıkışıyor."],
      ["carpool", "araç paylaşımı, ortak araçla gitmek", "🚘", "Four of us carpool to work, so we share the petrol costs.", "Dördümüz işe aynı arabayla gidiyoruz, böylece benzin masrafını paylaşıyoruz."],
      ["ride-sharing", "araç paylaşım hizmeti", "📲", "Ride-sharing apps have made taxis much less popular in some cities.", "Araç paylaşım uygulamaları bazı şehirlerde taksileri çok daha az popüler hâle getirdi."],
      ["route", "güzergâh, rota", "🗺️", "This bus takes a longer route, but it is never crowded.", "Bu otobüs daha uzun bir güzergâh izliyor ama hiç kalabalık olmuyor."],
      ["depot", "garaj, depo", "🚌", "The last bus goes back to the depot just after midnight.", "Son otobüs gece yarısından hemen sonra garaja dönüyor."],
      ["metro", "metro", "🚇", "The metro is the fastest way to get across the city.", "Metro şehrin bir ucundan öbür ucuna gitmenin en hızlı yolu."],
      ["tram", "tramvay", "🚋", "We took the old tram along the seafront to the museum.", "Sahil boyunca eski tramvaya binip müzeye gittik."],
      ["cable car", "teleferik", "🚡", "A cable car takes visitors to the top of the hill in five minutes.", "Teleferik ziyaretçileri beş dakikada tepenin zirvesine çıkarıyor."],
      ["shuttle", "servis aracı, ring", "🚐", "A free shuttle runs between the airport and the city hotels.", "Havalimanı ile şehirdeki oteller arasında ücretsiz bir servis çalışıyor."],
      ["carriage", "vagon", "🚃", "The first carriage of the train is usually the least crowded.", "Trenin ilk vagonu genellikle en az kalabalık olanıdır."],
      ["ticket inspector", "bilet kontrolörü", "🎫", "The ticket inspector fined a young man who had no ticket.", "Bilet kontrolörü bileti olmayan genç bir adama ceza kesti."],
      ["off-peak", "yoğun olmayan saatlerde, indirimli saat", "🕙", "Off-peak tickets are cheaper if you travel after ten in the morning.", "Sabah ondan sonra yolculuk yaparsan yoğun olmayan saat biletleri daha ucuz."],
      ["travel card", "ulaşım kartı", "💳", "Do not forget to top up your travel card before Monday.", "Pazartesiden önce ulaşım kartına para yüklemeyi unutma."],
      ["fare", "bilet ücreti, yol parası", "💵", "The bus fare went up again at the beginning of the year.", "Otobüs bilet ücreti yılbaşında yine arttı."],
      ["turnstile", "turnike", "🚧", "My card did not work, so I got stuck at the turnstile.", "Kartım çalışmadı, bu yüzden turnikede takılıp kaldım."],
      ["night bus", "gece otobüsü", "🌙", "I missed the last train, so I had to take the night bus home.", "Son treni kaçırdım, bu yüzden eve gece otobüsüyle dönmek zorunda kaldım."],
      ["hop on", "atlamak, binivermek", "🚌", "Just hop on the next bus and get off at the third stop.", "Bir sonraki otobüse atla ve üçüncü durakta in."],
      ["pull over", "kenara çekmek", "🚓", "The police officer asked the driver to pull over.", "Polis memuru sürücüden kenara çekmesini istedi."],
      ["give way", "yol vermek", "🔺", "You must give way to buses when they leave a stop.", "Otobüsler duraktan çıkarken onlara yol vermelisin."],
      ["overtake", "sollamak", "🏎️", "It is dangerous to overtake a truck on a narrow road.", "Dar bir yolda kamyonu sollamak tehlikelidir."],
      ["honk", "korna çalmak", "📯", "Drivers started to honk when the light turned green.", "Işık yeşile döndüğünde sürücüler korna çalmaya başladı."],
      ["scooter", "scooter, elektrikli scooter", "🛴", "Many students use an electric scooter to get to class.", "Birçok öğrenci derse gitmek için elektrikli scooter kullanıyor."],
      ["bike lane", "bisiklet şeridi", "🚲", "The city painted a new bike lane along the main avenue.", "Belediye ana cadde boyunca yeni bir bisiklet şeridi çizdi."],
      ["cycle path", "bisiklet yolu", "🚴", "There is a lovely cycle path that follows the river for miles.", "Kilometrelerce nehri takip eden güzel bir bisiklet yolu var."],
      ["pedestrian zone", "yaya bölgesi", "🚶‍♀️", "The old market street is now a pedestrian zone with no cars.", "Eski çarşı sokağı artık arabaların girmediği bir yaya bölgesi."],
      ["street vendor", "seyyar satıcı", "🌭", "We bought roasted corn from a street vendor near the harbour.", "Limanın yakınındaki bir seyyar satıcıdan közlenmiş mısır aldık."],
      ["avenue", "cadde, bulvar", "🌳", "The avenue is lined with tall trees and expensive shops.", "Cadde uzun ağaçlar ve pahalı mağazalarla çevrili."],
      ["boulevard", "bulvar", "🛣️", "We walked down the wide boulevard towards the old palace.", "Geniş bulvar boyunca eski saraya doğru yürüdük."],
      ["plaza", "meydan, alışveriş meydanı", "🏬", "Street musicians often play in the plaza on summer evenings.", "Sokak müzisyenleri yaz akşamları sık sık meydanda çalıyor."],
      ["fountain", "çeşme, fıskiye", "⛲", "Children were splashing in the fountain to cool down.", "Çocuklar serinlemek için fıskiyede su sıçratıyordu."],
      ["lamppost", "sokak lambası direği", "🏮", "Someone had tied a lost cat poster to every lamppost on the street.", "Biri sokaktaki her lamba direğine kayıp kedi ilanı asmıştı."],
      ["skyline", "şehir silueti", "🌆", "The city skyline looks magical when the lights come on at night.", "Şehir silueti geceleri ışıklar yanınca büyülü görünüyor."],
      ["roadworks", "yol çalışması", "👷", "Roadworks on the main street will continue until the end of the month.", "Ana caddedeki yol çalışması ay sonuna kadar sürecek."],
      ["traffic warden", "trafik ve park görevlisi", "👮", "The traffic warden was writing a ticket when I ran back to my car.", "Arabama koşarak döndüğümde park görevlisi ceza yazıyordu."],
      ["real estate", "emlak, gayrimenkul", "🏢", "Real estate prices in the city centre have doubled in five years.", "Şehir merkezindeki emlak fiyatları beş yılda iki katına çıktı."],
      ["property", "mülk, taşınmaz", "🔑", "They bought a small property near the sea as an investment.", "Yatırım olarak denize yakın küçük bir mülk satın aldılar."],
      ["stained glass", "vitray", "🌈", "Light poured through the stained glass windows of the old church.", "Işık eski kilisenin vitray pencerelerinden içeri doluyordu."],
      ["spire", "kule külahı, sivri kule", "⛪", "You can see the spire of the church from every part of town.", "Kilisenin sivri kulesini kasabanın her yerinden görebilirsin."],
      ["tower block", "çok katlı apartman", "🏢", "The old tower block will be replaced by smaller, greener homes.", "Eski çok katlı apartmanın yerine daha küçük, daha yeşil evler yapılacak."],
      ["storey", "kat", "🏬", "The new hotel will be a forty storey building made of glass.", "Yeni otel camdan yapılmış kırk katlı bir bina olacak."],
      ["floor plan", "kat planı", "📏", "I like this flat because the floor plan is open and bright.", "Bu daireyi seviyorum çünkü kat planı açık ve aydınlık."],
      ["concrete", "beton", "🧱", "The city is full of grey concrete buildings from the seventies.", "Şehir yetmişlerden kalma gri beton binalarla dolu."],
      ["brick", "tuğla", "🧱", "The old factory was built entirely of red brick.", "Eski fabrika tamamen kırmızı tuğladan inşa edilmişti."],
      ["foundation", "temel", "🏗️", "Cracks in the foundation can make the whole building unsafe.", "Temeldeki çatlaklar bütün binayı güvensiz hâle getirebilir."],
      ["corridor", "koridor", "🚪", "My office is at the end of the long corridor on the left.", "Ofisim uzun koridorun sonunda, solda."],
      ["hallway", "hol, koridor", "🚪", "Please leave your wet shoes in the hallway by the door.", "Lütfen ıslak ayakkabılarını kapının yanındaki holde bırak."],
      ["suburban", "banliyöye ait", "🏡", "They live a quiet suburban life with a garden and two dogs.", "Bahçeli ve iki köpekli sakin bir banliyö hayatı sürüyorlar."],
      ["metropolitan", "büyükşehir, metropol", "🌃", "The metropolitan area is home to more than fifteen million people.", "Büyükşehir bölgesi on beş milyondan fazla insana ev sahipliği yapıyor."],
      ["densely populated", "yoğun nüfuslu", "👥", "This is one of the most densely populated neighbourhoods in Europe.", "Burası Avrupa'nın en yoğun nüfuslu mahallelerinden biri."],
      ["bustling", "hareketli, cıvıl cıvıl", "🛍️", "We spent the afternoon exploring the bustling markets of the old city.", "Öğleden sonrayı eski şehrin hareketli pazarlarını gezerek geçirdik."],
      ["derelict", "harap, terk edilmiş", "🏚️", "Artists turned the derelict warehouse into a popular gallery.", "Sanatçılar terk edilmiş depoyu popüler bir galeriye dönüştürdü."]
    ] }
);
