(window.LIBRARY = window.LIBRARY || []).push(
  { id: "lib1a", title: "İş Dünyası ve Yönetim", icon: "💼", cefr: "B2", desc: "Şirket yapısı, toplantılar, ekip yönetimi ve iş süreçleri için gereken temel kelimeler.",
    words: [
      ["subsidiary", "yan kuruluş, bağlı şirket", "🏢", "The company opened a new subsidiary in Germany last spring.", "Şirket geçen bahar Almanya'da yeni bir yan kuruluş açtı."],
      ["workforce", "işgücü, çalışan kadrosu", "👷", "Almost half of our workforce now works from home twice a week.", "İşgücümüzün neredeyse yarısı artık haftada iki gün evden çalışıyor."],
      ["redundancy", "kadro fazlası nedeniyle işten çıkarılma", "📉", "Thirty employees faced redundancy after the factory closed.", "Fabrika kapandıktan sonra otuz çalışan işten çıkarılmayla karşı karşıya kaldı."],
      ["outsource", "dış kaynağa vermek", "🔄", "Many small firms outsource their accounting to save time and money.", "Birçok küçük firma zaman ve para kazanmak için muhasebesini dış kaynağa veriyor."],
      ["in-house", "şirket içi", "🏠", "We have an in-house design team, so we rarely hire agencies.", "Şirket içi bir tasarım ekibimiz var, bu yüzden nadiren ajans tutuyoruz."],
      ["logistics", "lojistik", "🚚", "She manages the logistics of shipping products to twelve countries.", "On iki ülkeye ürün gönderiminin lojistiğini o yönetiyor."],
      ["procurement", "satın alma, tedarik", "🧾", "All requests for new laptops must go through the procurement department.", "Yeni dizüstü bilgisayar talepleri satın alma departmanından geçmek zorunda."],
      ["vendor", "satıcı firma, tedarikçi", "🤝", "We switched to a cheaper vendor for our office supplies.", "Ofis malzemelerimiz için daha ucuz bir satıcı firmaya geçtik."],
      ["supplier", "tedarikçi", "📦", "Our main supplier delivered the raw materials two days late.", "Ana tedarikçimiz ham maddeleri iki gün geç teslim etti."],
      ["contractor", "yüklenici, sözleşmeli çalışan", "🔧", "The building work was done by an independent contractor.", "İnşaat işi bağımsız bir yüklenici tarafından yapıldı."],
      ["benchmark", "kıyaslama ölçütü", "📏", "We use last year's sales as a benchmark for this year.", "Bu yıl için geçen yılın satışlarını kıyaslama ölçütü olarak kullanıyoruz."],
      ["action plan", "eylem planı", "📝", "After the meeting, each team had to prepare a clear action plan.", "Toplantıdan sonra her ekip net bir eylem planı hazırlamak zorundaydı."],
      ["roll out", "kullanıma sunmak, yaygınlaştırmak", "🚀", "The bank will roll out the new app to all customers next month.", "Banka yeni uygulamayı gelecek ay tüm müşterilere kullanıma sunacak."],
      ["implement", "uygulamaya koymak", "⚙️", "It took us six months to implement the new software.", "Yeni yazılımı uygulamaya koymamız altı ay sürdü."],
      ["oversee", "denetlemek, gözetmek", "👀", "She was hired to oversee the opening of the new store.", "Yeni mağazanın açılışını denetlemek için işe alındı."],
      ["supervise", "nezaret etmek, yönetmek", "🧑‍🏫", "He supervises a team of eight engineers in the Ankara office.", "Ankara ofisinde sekiz mühendisten oluşan bir ekibi yönetiyor."],
      ["line manager", "doğrudan bağlı olunan yönetici", "👔", "You should ask your line manager before booking any time off.", "İzin almadan önce doğrudan bağlı olduğun yöneticiye sormalısın."],
      ["chain of command", "emir komuta zinciri", "🔗", "Complaints should follow the chain of command, starting with your supervisor.", "Şikâyetler, amirinden başlayarak emir komuta zincirini izlemeli."],
      ["report to", "birine bağlı çalışmak, rapor vermek", "📋", "In this role, you will report to the head of marketing.", "Bu pozisyonda pazarlama müdürüne bağlı çalışacaksınız."],
      ["take responsibility", "sorumluluk almak", "🙋", "A good leader is willing to take responsibility when things go wrong.", "İyi bir lider işler ters gittiğinde sorumluluk almaya isteklidir."],
      ["initiative", "inisiyatif, girişim", "💡", "She showed real initiative by fixing the problem without being asked.", "Kimse istemeden sorunu çözerek gerçek bir inisiyatif gösterdi."],
      ["carry out", "yürütmek, gerçekleştirmek", "✅", "The team will carry out a customer survey before the launch.", "Ekip lansmandan önce bir müşteri anketi gerçekleştirecek."],
      ["streamline", "sadeleştirmek, verimli hâle getirmek", "🌊", "We need to streamline the approval process so projects move faster.", "Projelerin daha hızlı ilerlemesi için onay sürecini sadeleştirmemiz gerekiyor."],
      ["efficiency", "verimlilik", "⚡", "The new machines have greatly improved the efficiency of the factory.", "Yeni makineler fabrikanın verimliliğini büyük ölçüde artırdı."],
      ["prioritize", "önceliklendirmek", "🔝", "When everything feels urgent, you have to prioritize the most important tasks.", "Her şey acil görünüyorsa en önemli işleri önceliklendirmen gerekir."],
      ["fall behind", "geride kalmak, gecikmek", "🐢", "If we fall behind this week, we will miss the launch date.", "Bu hafta geride kalırsak lansman tarihini kaçıracağız."],
      ["on track", "planlandığı gibi ilerleyen", "🛤️", "Don't worry, the project is still on track for a June release.", "Merak etme, proje hâlâ haziran çıkışı için planlandığı gibi ilerliyor."],
      ["behind schedule", "programın gerisinde", "⏰", "The new bridge is already three months behind schedule.", "Yeni köprü şimdiden programın üç ay gerisinde."],
      ["time frame", "zaman çizelgesi, süre", "🗓️", "What is a realistic time frame for finishing the website?", "Web sitesini bitirmek için gerçekçi bir süre nedir?"],
      ["feasible", "uygulanabilir, yapılabilir", "🧩", "Is it feasible to open two new branches in one year?", "Bir yılda iki yeni şube açmak uygulanabilir mi?"],
      ["draw up", "hazırlamak, taslağını çıkarmak", "✍️", "Our lawyer will draw up the contract by Friday.", "Avukatımız sözleşmeyi cumaya kadar hazırlayacak."],
      ["sign off", "son onayı vermek", "🖊️", "The director has to sign off on the budget before we start.", "Başlamadan önce müdürün bütçeye son onayı vermesi gerekiyor."],
      ["authorize", "yetkilendirmek, izin vermek", "🔑", "Only the finance manager can authorize payments over ten thousand lira.", "On bin liranın üzerindeki ödemelere yalnızca finans müdürü izin verebilir."],
      ["bring forward", "öne almak", "⏩", "Can we bring forward the meeting to Tuesday morning?", "Toplantıyı salı sabahına öne alabilir miyiz?"],
      ["restructure", "yeniden yapılandırmak", "🏗️", "The company plans to restructure its sales teams next year.", "Şirket gelecek yıl satış ekiplerini yeniden yapılandırmayı planlıyor."],
      ["downsize", "küçülmek, kadro azaltmak", "📦", "After losing two big clients, the agency had to downsize.", "İki büyük müşteriyi kaybettikten sonra ajans küçülmek zorunda kaldı."],
      ["expansion", "büyüme, genişleme", "🌍", "The expansion into Asian markets has been a huge success.", "Asya pazarlarına doğru genişleme büyük bir başarı oldu."],
      ["competitive advantage", "rekabet avantajı", "🏆", "Fast delivery gives us a real competitive advantage over larger stores.", "Hızlı teslimat bize büyük mağazalara karşı gerçek bir rekabet avantajı sağlıyor."],
      ["best practice", "en iyi uygulama", "⭐", "Backing up files every day is considered best practice in IT.", "Dosyaları her gün yedeklemek bilişimde en iyi uygulama kabul edilir."],
      ["compliance", "mevzuata uyum", "📜", "The legal team checks our compliance with data protection laws.", "Hukuk ekibi veri koruma yasalarına uyumumuzu kontrol ediyor."],
      ["guideline", "yönerge, kılavuz ilke", "🧭", "Please read the new guideline on using company cars.", "Lütfen şirket araçlarının kullanımına dair yeni yönergeyi okuyun."],
      ["code of conduct", "davranış kuralları", "📘", "Every new employee must sign the company code of conduct.", "Her yeni çalışan şirketin davranış kurallarını imzalamak zorunda."],
      ["conflict of interest", "çıkar çatışması", "⚖️", "Hiring your own brother could create a conflict of interest.", "Kendi kardeşini işe almak bir çıkar çatışması yaratabilir."],
      ["joint venture", "ortak girişim", "🤜", "The two car makers formed a joint venture to build electric engines.", "İki otomobil üreticisi elektrikli motor üretmek için ortak bir girişim kurdu."],
      ["liaise", "irtibat kurmak, koordineli çalışmak", "📞", "You will liaise with suppliers and make sure orders arrive on time.", "Tedarikçilerle irtibat kurup siparişlerin zamanında gelmesini sağlayacaksın."],
      ["coordinate", "koordine etmek", "🎛️", "Who is going to coordinate the trip for the sales conference?", "Satış konferansı için yolculuğu kim koordine edecek?"],
      ["cross-functional", "farklı departmanlardan oluşan", "🔀", "A cross-functional team of designers and engineers built the prototype.", "Tasarımcılar ve mühendislerden oluşan karma bir ekip prototipi yaptı."],
      ["morale", "moral, çalışan motivasyonu", "😊", "Staff morale improved a lot after the new manager arrived.", "Yeni yönetici geldikten sonra çalışanların morali çok yükseldi."],
      ["incentive", "teşvik, özendirici", "🎁", "The company offers a cash incentive for every new client you bring in.", "Şirket getirdiğin her yeni müşteri için nakit teşvik veriyor."],
      ["performance review", "performans değerlendirmesi", "📊", "My performance review is next week, and I'm a bit nervous.", "Performans değerlendirmem gelecek hafta ve biraz gerginim."],
      ["appraisal", "değerlendirme, takdir görüşmesi", "📈", "During the annual appraisal, we discussed my goals for next year.", "Yıllık değerlendirme sırasında gelecek yılki hedeflerimi konuştuk."],
      ["onboarding", "işe alıştırma süreci", "🧳", "Our onboarding program helps new staff settle in during their first month.", "İşe alıştırma programımız yeni çalışanların ilk ayında uyum sağlamasına yardım ediyor."],
      ["recruitment", "işe alım", "🔍", "Recruitment has become harder because skilled workers are in high demand.", "Nitelikli çalışanlara talep yüksek olduğu için işe alım zorlaştı."],
      ["job description", "iş tanımı", "📄", "The job description says the role requires fluent English.", "İş tanımı bu pozisyonun akıcı İngilizce gerektirdiğini söylüyor."],
      ["turnover", "çalışan devir hızı, ciro", "🔁", "High staff turnover is costing the restaurant a lot of money.", "Yüksek çalışan devir hızı restorana çok paraya mal oluyor."],
      ["maternity leave", "doğum izni", "👶", "She is on maternity leave until the end of March.", "Mart sonuna kadar doğum izninde."],
      ["human resources", "insan kaynakları", "🧑‍💼", "Please send your sick note to human resources as soon as possible.", "Lütfen rapor belgeni en kısa sürede insan kaynaklarına gönder."],
      ["middle management", "orta kademe yönetim", "🪜", "Most decisions are made by middle management, not by the CEO.", "Kararların çoğu genel müdür değil, orta kademe yönetim tarafından alınıyor."],
      ["self-employed", "serbest çalışan, kendi işinin sahibi", "🧑‍💻", "Since becoming self-employed, I choose my own working hours.", "Serbest çalışmaya başladığımdan beri çalışma saatlerimi kendim seçiyorum."],
      ["close a deal", "anlaşmayı sonuçlandırmak", "✍️", "We hope to close a deal with the Italian buyers this week.", "Bu hafta İtalyan alıcılarla anlaşmayı sonuçlandırmayı umuyoruz."],
      ["strike a deal", "anlaşmaya varmak", "🤝", "After long talks, the union and management finally managed to strike a deal.", "Uzun görüşmelerden sonra sendika ve yönetim sonunda anlaşmaya varmayı başardı."],
      ["risk assessment", "risk değerlendirmesi", "⚠️", "We must complete a risk assessment before starting any building work.", "Herhangi bir inşaat işine başlamadan önce risk değerlendirmesi yapmalıyız."],
      ["contingency plan", "acil durum planı, B planı", "🛟", "We have a contingency plan in case the main server fails.", "Ana sunucu çökerse diye bir acil durum planımız var."],
      ["crisis management", "kriz yönetimi", "🚨", "Good crisis management saved the brand after the product recall.", "İyi kriz yönetimi ürün geri çağırmasından sonra markayı kurtardı."],
      ["deliverable", "teslim edilecek çıktı", "📬", "The first deliverable is a full report on customer habits.", "İlk teslim edilecek çıktı müşteri alışkanlıkları üzerine kapsamlı bir rapor."],
      ["constructive", "yapıcı", "🛠️", "Thanks for the constructive comments, they really helped me improve the plan.", "Yapıcı yorumların için teşekkürler, planı geliştirmeme gerçekten yardım etti."],
      ["mission statement", "misyon bildirgesi", "🎯", "Our mission statement focuses on quality and honesty.", "Misyon bildirgemiz kalite ve dürüstlüğe odaklanıyor."],
      ["scope", "kapsam", "🔭", "Adding a mobile app is outside the scope of this project.", "Mobil uygulama eklemek bu projenin kapsamı dışında."],
      ["workflow", "iş akışı", "🔃", "The new tool has made our daily workflow much smoother.", "Yeni araç günlük iş akışımızı çok daha akıcı hâle getirdi."],
      ["delegation", "yetki devri, görev dağıtımı", "📤", "Effective delegation means trusting your team with important tasks.", "Etkili görev dağıtımı ekibine önemli işlerde güvenmek demektir."],
      ["empower", "yetkilendirmek, güçlendirmek", "💪", "We want to empower staff to make decisions without waiting for approval.", "Çalışanları onay beklemeden karar verebilecek şekilde güçlendirmek istiyoruz."],
      ["decision-maker", "karar verici", "🧠", "Make sure you speak directly to the decision-maker, not an assistant.", "Bir asistanla değil, doğrudan karar vericiyle konuştuğundan emin ol."],
      ["executive summary", "yönetici özeti", "📑", "Busy directors usually read only the executive summary of a report.", "Yoğun yöneticiler genellikle bir raporun yalnızca yönetici özetini okur."],
      ["annual report", "faaliyet raporu, yıllık rapor", "📚", "The annual report shows that profits rose by twelve percent.", "Yıllık rapor kârın yüzde on iki arttığını gösteriyor."],
      ["board meeting", "yönetim kurulu toplantısı", "🪑", "The plan will be presented at next month's board meeting.", "Plan gelecek ayki yönetim kurulu toplantısında sunulacak."],
      ["chairperson", "başkan, toplantı başkanı", "🎙️", "The chairperson opened the meeting with a short welcome speech.", "Başkan toplantıyı kısa bir hoş geldiniz konuşmasıyla açtı."],
      ["managing director", "genel müdür", "👩‍💼", "The managing director visits every branch at least once a year.", "Genel müdür her şubeyi yılda en az bir kez ziyaret ediyor."],
      ["operations", "operasyonlar, işletme faaliyetleri", "🏭", "He is responsible for daily operations at the warehouse.", "Depodaki günlük operasyonlardan o sorumlu."],
      ["resource allocation", "kaynak dağılımı", "🧮", "Poor resource allocation left some teams with too much work.", "Kötü kaynak dağılımı bazı ekiplerin fazla işle kalmasına yol açtı."],
      ["allocate", "tahsis etmek, ayırmak", "📌", "We decided to allocate more money to staff training this year.", "Bu yıl çalışan eğitimine daha fazla para ayırmaya karar verdik."],
      ["understaffed", "personel eksiği olan", "🙇", "The hospital is badly understaffed during the summer holidays.", "Hastanede yaz tatillerinde ciddi personel eksikliği oluyor."],
      ["at short notice", "kısa süre önce haber vererek", "⏱️", "Sorry to call you at short notice, but can you come in today?", "Kısa süre önce haber verdiğim için kusura bakma ama bugün gelebilir misin?"],
      ["hand over", "devretmek, teslim etmek", "🫴", "Before you leave, please hand over your projects to Selin.", "Ayrılmadan önce lütfen projelerini Selin'e devret."],
      ["escalate", "üst kademeye taşımak", "⬆️", "If the customer is still unhappy, escalate the issue to your manager.", "Müşteri hâlâ memnun değilse sorunu yöneticine taşı."],
      ["troubleshoot", "sorun gidermek", "🧰", "Our IT team can troubleshoot most problems remotely.", "Bilgi işlem ekibimiz çoğu sorunu uzaktan giderebiliyor."],
      ["set targets", "hedef belirlemek", "🎯", "Managers should set targets that are challenging but realistic.", "Yöneticiler zorlayıcı ama gerçekçi hedefler belirlemeli."],
      ["meet a target", "hedefi tutturmak", "🥅", "If we meet a target three months in a row, we all get a bonus.", "Üç ay üst üste hedefi tutturursak hepimiz prim alıyoruz."],
      ["exceed expectations", "beklentileri aşmak", "🌟", "The new intern continues to exceed expectations in every task.", "Yeni stajyer her görevde beklentileri aşmaya devam ediyor."],
      ["underperform", "beklenenin altında performans göstermek", "📉", "Stores that underperform for two years may be closed.", "İki yıl boyunca beklenenin altında kalan mağazalar kapatılabilir."],
      ["core competency", "temel yetkinlik", "🧱", "Customer service is our core competency, so we never outsource it.", "Müşteri hizmetleri temel yetkinliğimiz, bu yüzden onu asla dışarıya vermiyoruz."],
      ["company culture", "şirket kültürü", "🎨", "The company culture here is relaxed but very hardworking.", "Buradaki şirket kültürü rahat ama çok çalışkan."],
      ["organizational chart", "organizasyon şeması", "🗂️", "Look at the organizational chart to see who is in each department.", "Her departmanda kimin olduğunu görmek için organizasyon şemasına bak."],
      ["job security", "iş güvencesi", "🔒", "Many young people value job security more than a high salary.", "Birçok genç iş güvencesine yüksek maaştan daha çok değer veriyor."],
      ["probation period", "deneme süresi", "⏳", "New staff have a three-month probation period before the contract becomes permanent.", "Yeni çalışanların sözleşme kalıcı olmadan önce üç aylık bir deneme süresi var."],
      ["fixed-term contract", "belirli süreli sözleşme", "📃", "I'm on a fixed-term contract that ends in December.", "Aralıkta biten belirli süreli bir sözleşmeyle çalışıyorum."],
      ["perk", "yan hak, ekstra imkân", "🎟️", "Free lunch is my favourite perk of working here.", "Ücretsiz öğle yemeği burada çalışmanın en sevdiğim yan hakkı."],
      ["business trip", "iş seyahati", "✈️", "He is away on a business trip to Dubai until Thursday.", "Perşembeye kadar Dubai'ye bir iş seyahatinde."],
      ["run a meeting", "toplantı yönetmek", "🗣️", "It takes skill to run a meeting that finishes on time.", "Zamanında biten bir toplantıyı yönetmek beceri ister."],
      ["go over", "gözden geçirmek", "🔎", "Let's go over the figures once more before we send them.", "Göndermeden önce rakamları bir kez daha gözden geçirelim."],
      ["draw on", "yararlanmak, başvurmak", "🧠", "In this new role, you can draw on your years of sales experience.", "Bu yeni pozisyonda yılların satış deneyiminden yararlanabilirsin."],
      ["phase out", "aşamalı olarak kaldırmak", "🌅", "The firm will phase out paper forms by the end of next year.", "Firma kâğıt formları gelecek yılın sonuna kadar aşamalı olarak kaldıracak."],
      ["corporate", "kurumsal", "🏙️", "After ten years in a corporate job, she opened her own café.", "Kurumsal bir işte on yıl çalıştıktan sonra kendi kafesini açtı."],
      ["enterprise", "işletme, teşebbüs", "🏪", "The government offers cheap loans to small and medium enterprise owners.", "Hükûmet küçük ve orta ölçekli işletme sahiplerine ucuz kredi veriyor."],
      ["multinational", "çok uluslu", "🌐", "She works for a multinational company with offices in forty countries.", "Kırk ülkede ofisi olan çok uluslu bir şirkette çalışıyor."],
      ["franchise", "bayilik, franchise", "🍔", "He bought a coffee shop franchise instead of starting his own brand.", "Kendi markasını kurmak yerine bir kahve dükkânı bayiliği satın aldı."],
      ["memo", "iç yazışma notu", "🗒️", "The manager sent a memo about the new holiday rules.", "Müdür yeni tatil kurallarıyla ilgili bir iç not gönderdi."],
      ["governance", "yönetişim, kurumsal yönetim", "🏛️", "Investors care about good governance as much as profit.", "Yatırımcılar iyi kurumsal yönetimi kâr kadar önemsiyor."],
      ["professionalism", "profesyonellik", "🎩", "Her professionalism impressed the clients from the very first meeting.", "Profesyonelliği daha ilk toplantıdan müşterileri etkiledi."],
      ["consultancy", "danışmanlık firması", "🧑‍⚖️", "They hired a consultancy to help them cut costs.", "Maliyetleri düşürmelerine yardım etmesi için bir danışmanlık firması tuttular."],
      ["expertise", "uzmanlık", "🎓", "We need someone with expertise in cyber security.", "Siber güvenlik alanında uzmanlığı olan birine ihtiyacımız var."]
    ] },
  { id: "lib1b", title: "Pazarlama ve Satış", icon: "📣", cefr: "B2", desc: "Marka, reklam, dijital pazarlama, perakende ve satış görüşmeleri için kullanışlı kelimeler.",
    words: [
      ["target audience", "hedef kitle", "🎯", "Our target audience is young parents who shop online.", "Hedef kitlemiz internetten alışveriş yapan genç ebeveynler."],
      ["target market", "hedef pazar", "🗺️", "The target market for this watch is wealthy business travellers.", "Bu saatin hedef pazarı varlıklı iş seyahatçileri."],
      ["market research", "pazar araştırması", "🔬", "Market research showed that customers wanted smaller packs.", "Pazar araştırması müşterilerin daha küçük paketler istediğini gösterdi."],
      ["focus group", "odak grubu", "👥", "We tested the new flavour with a focus group of ten students.", "Yeni tadı on öğrenciden oluşan bir odak grubuyla test ettik."],
      ["consumer behaviour", "tüketici davranışı", "🛍️", "The pandemic changed consumer behaviour in many surprising ways.", "Salgın tüketici davranışını birçok şaşırtıcı şekilde değiştirdi."],
      ["buyer persona", "alıcı profili", "🧍", "Our main buyer persona is a busy office worker in her thirties.", "Ana alıcı profilimiz otuzlu yaşlarında yoğun bir ofis çalışanı."],
      ["brand loyalty", "marka sadakati", "❤️", "Strong brand loyalty means customers keep coming back even when prices rise.", "Güçlü marka sadakati, fiyatlar artsa bile müşterilerin geri gelmesi demektir."],
      ["brand identity", "marka kimliği", "🎨", "Colours and fonts are an important part of brand identity.", "Renkler ve yazı tipleri marka kimliğinin önemli bir parçasıdır."],
      ["rebrand", "markayı yenilemek", "🔄", "The old bakery decided to rebrand with a modern logo and name.", "Eski fırın modern bir logo ve isimle markasını yenilemeye karar verdi."],
      ["positioning", "konumlandırma", "📍", "Their positioning as a luxury brand allows them to charge high prices.", "Lüks marka olarak konumlandırmaları yüksek fiyat almalarına imkân veriyor."],
      ["slogan", "slogan", "📢", "Everyone in the country remembers that catchy slogan from the nineties.", "Ülkedeki herkes doksanlardan kalan o akılda kalıcı sloganı hatırlıyor."],
      ["tagline", "marka sloganı, kısa tanıtım cümlesi", "🏷️", "We need a short tagline to put under the logo.", "Logonun altına koymak için kısa bir tanıtım cümlesine ihtiyacımız var."],
      ["billboard", "reklam panosu", "🪧", "They put up a huge billboard next to the motorway.", "Otoyolun yanına devasa bir reklam panosu diktiler."],
      ["endorsement", "ünlü desteği, tavsiye", "🌟", "The sports drink sold out after a famous footballer's endorsement.", "Spor içeceği ünlü bir futbolcunun desteğinden sonra tükendi."],
      ["endorse", "desteklemek, reklam yüzü olmak", "👍", "Many athletes endorse products they never actually use.", "Birçok sporcu aslında hiç kullanmadığı ürünlerin reklam yüzü oluyor."],
      ["sponsor", "sponsor olmak", "🏟️", "A local bank agreed to sponsor the city marathon.", "Yerel bir banka şehir maratonuna sponsor olmayı kabul etti."],
      ["sponsorship", "sponsorluk", "🤝", "The club lost its main sponsorship deal after a bad season.", "Kulüp kötü bir sezonun ardından ana sponsorluk anlaşmasını kaybetti."],
      ["word of mouth", "kulaktan kulağa yayılma", "🗣️", "Our restaurant grew mainly through word of mouth, not advertising.", "Restoranımız reklamla değil, esas olarak kulaktan kulağa büyüdü."],
      ["engagement", "etkileşim", "💬", "Short videos get much higher engagement than long text posts.", "Kısa videolar uzun yazılı paylaşımlardan çok daha yüksek etkileşim alıyor."],
      ["reach", "erişim, ulaşılan kişi sayısı", "📡", "The post had a reach of over fifty thousand people.", "Paylaşım elli binden fazla kişiye erişti."],
      ["click-through rate", "tıklanma oranı", "🖱️", "Changing the button colour increased our click-through rate by two percent.", "Düğme rengini değiştirmek tıklanma oranımızı yüzde iki artırdı."],
      ["conversion rate", "dönüşüm oranı", "🔁", "Lots of people visit the site, but the conversion rate is very low.", "Siteyi çok kişi ziyaret ediyor ama dönüşüm oranı çok düşük."],
      ["landing page", "açılış sayfası", "🖥️", "The ad sends users to a simple landing page with a sign-up form.", "Reklam kullanıcıları kayıt formu olan basit bir açılış sayfasına yönlendiriyor."],
      ["newsletter", "bülten", "📰", "Sign up for our newsletter to hear about new products first.", "Yeni ürünleri ilk sen duymak için bültenimize kaydol."],
      ["mailing list", "e-posta listesi", "📧", "Our mailing list has grown to twenty thousand subscribers.", "E-posta listemiz yirmi bin aboneye ulaştı."],
      ["subscriber", "abone", "🔔", "Every new subscriber gets a ten percent discount code.", "Her yeni abone yüzde on indirim kodu alıyor."],
      ["unsubscribe", "abonelikten çıkmak", "🚫", "If you send too many emails, people will simply unsubscribe.", "Çok fazla e-posta gönderirsen insanlar abonelikten çıkıp gider."],
      ["opt in", "onay vererek katılmak", "✅", "Customers must opt in before we can send them marketing messages.", "Pazarlama mesajı gönderebilmemiz için müşterilerin önce onay vermesi gerekir."],
      ["cold call", "tanımadığı birini satış için aramak", "☎️", "I hate it when salespeople cold call me during dinner.", "Satıcıların akşam yemeği sırasında beni habersizce araması çok sinirime dokunuyor."],
      ["lead", "potansiyel müşteri", "🧲", "The trade fair gave us more than two hundred new sales leads.", "Ticaret fuarı bize iki yüzden fazla yeni potansiyel müşteri kazandırdı."],
      ["sales pitch", "satış konuşması", "🎤", "He practised his sales pitch in front of the mirror all night.", "Bütün gece aynanın karşısında satış konuşmasını çalıştı."],
      ["prospect", "olası müşteri", "🔭", "Spend more time on prospects who have already shown interest.", "Zaten ilgi göstermiş olası müşterilere daha fazla zaman ayır."],
      ["upsell", "daha pahalı ürün satmak", "⬆️", "The waiter tried to upsell us a bottle of expensive wine.", "Garson bize pahalı bir şişe şarap satmaya çalıştı."],
      ["cross-sell", "tamamlayıcı ürün satmak", "↔️", "Phone shops often cross-sell cases and screen protectors.", "Telefon dükkânları genellikle yanında kılıf ve ekran koruyucu da satar."],
      ["bulk discount", "toplu alım indirimi", "📦", "If you order more than a hundred units, we offer a bulk discount.", "Yüzden fazla adet sipariş ederseniz toplu alım indirimi sunuyoruz."],
      ["special offer", "özel teklif, kampanya", "🎉", "This special offer is only valid until Sunday.", "Bu özel kampanya yalnızca pazara kadar geçerli."],
      ["limited edition", "sınırlı sayıda üretim", "💎", "The limited edition sneakers sold out within ten minutes.", "Sınırlı sayıda üretilen spor ayakkabılar on dakikada tükendi."],
      ["free trial", "ücretsiz deneme", "🆓", "The app offers a thirty-day free trial before you have to pay.", "Uygulama ödeme yapmadan önce otuz günlük ücretsiz deneme sunuyor."],
      ["money-back guarantee", "para iade garantisi", "💵", "Every course comes with a money-back guarantee if you are not satisfied.", "Memnun kalmazsanız her kursta para iade garantisi var."],
      ["loyalty program", "sadakat programı", "🎫", "With the loyalty program, every tenth coffee is free.", "Sadakat programıyla her onuncu kahve bedava."],
      ["clearance sale", "stok eritme indirimi", "🏷️", "The shop is having a clearance sale before it moves to a new street.", "Dükkân yeni bir sokağa taşınmadan önce stok eritme indirimi yapıyor."],
      ["retail", "perakende", "🛒", "She has worked in retail for years, mostly in clothing stores.", "Yıllardır perakendede, çoğunlukla giyim mağazalarında çalıştı."],
      ["retailer", "perakendeci", "🏬", "The biggest online retailer in the country now sells groceries too.", "Ülkenin en büyük çevrim içi perakendecisi artık market ürünleri de satıyor."],
      ["wholesale", "toptan", "🚛", "Most restaurants usually buy their vegetables at wholesale prices.", "Çoğu restoran sebzelerini genellikle toptan fiyatlarla alır."],
      ["wholesaler", "toptancı", "🏭", "We buy our fabric from a wholesaler in Bursa.", "Kumaşımızı Bursa'daki bir toptancıdan alıyoruz."],
      ["distributor", "distribütör, dağıtıcı", "🚚", "We are looking for a distributor to sell our tea in Europe.", "Çayımızı Avrupa'da satmak için bir distribütör arıyoruz."],
      ["distribution channel", "dağıtım kanalı", "🔀", "Social media has become our most important distribution channel.", "Sosyal medya en önemli dağıtım kanalımız hâline geldi."],
      ["point of sale", "satış noktası", "💳", "Small snacks are placed at the point of sale to tempt shoppers.", "Alışverişçileri cezbetmek için küçük atıştırmalıklar satış noktasına konuyor."],
      ["shopping cart", "alışveriş sepeti", "🛒", "Many users leave items in their shopping cart and never pay.", "Birçok kullanıcı ürünleri alışveriş sepetinde bırakıp hiç ödeme yapmıyor."],
      ["e-commerce", "e-ticaret", "🌐", "E-commerce has made it easy for small producers to reach the whole country.", "E-ticaret küçük üreticilerin tüm ülkeye ulaşmasını kolaylaştırdı."],
      ["brick-and-mortar", "fiziksel mağaza", "🧱", "Some online brands are now opening brick-and-mortar stores.", "Bazı çevrim içi markalar artık fiziksel mağazalar açıyor."],
      ["foot traffic", "yaya trafiği, mağazaya gelen kişi sayısı", "🚶", "The shop gets heavy foot traffic because it is near the metro.", "Dükkân metroya yakın olduğu için çok yoğun yaya trafiği alıyor."],
      ["window display", "vitrin düzeni", "🪟", "A creative window display can make people stop and walk in.", "Yaratıcı bir vitrin düzeni insanları durdurup içeri girmeye ikna edebilir."],
      ["merchandise", "satılık mallar, ürünler", "👕", "The band makes more money from merchandise than from music.", "Grup müzikten çok satılan ürünlerden para kazanıyor."],
      ["shelf life", "raf ömrü", "🥫", "This yoghurt has a shelf life of only ten days.", "Bu yoğurdun raf ömrü sadece on gün."],
      ["restock", "stoğu yenilemek", "🔄", "We restock the shelves every night after closing time.", "Rafları her gece kapanıştan sonra yeniden dolduruyoruz."],
      ["pricing strategy", "fiyatlandırma stratejisi", "💲", "Our pricing strategy is to stay slightly cheaper than the big brands.", "Fiyatlandırma stratejimiz büyük markalardan biraz daha ucuz kalmak."],
      ["mark up", "fiyatı yükseltmek, kâr eklemek", "➕", "Airports mark up the price of water by almost three hundred percent.", "Havalimanları suyun fiyatını neredeyse yüzde üç yüz artırıyor."],
      ["markdown", "fiyat indirimi", "🔻", "There is a fifty percent markdown on all winter coats.", "Tüm kışlık montlarda yüzde elli indirim var."],
      ["best-seller", "en çok satan ürün", "🥇", "This blue backpack has been our best-seller for three years.", "Bu mavi sırt çantası üç yıldır en çok satan ürünümüz."],
      ["niche market", "niş pazar", "🔍", "They found a niche market selling vegan food for dogs.", "Köpekler için vegan mama satarak niş bir pazar buldular."],
      ["mass market", "kitlesel pazar", "🌎", "The company wants to move from luxury goods into the mass market.", "Şirket lüks ürünlerden kitlesel pazara geçmek istiyor."],
      ["supply and demand", "arz ve talep", "⚖️", "Prices change all the time because of supply and demand.", "Fiyatlar arz ve talep yüzünden sürekli değişiyor."],
      ["customer base", "müşteri tabanı", "👪", "Our customer base is mostly women between twenty and forty.", "Müşteri tabanımız çoğunlukla yirmi ile kırk yaş arası kadınlar."],
      ["customer satisfaction", "müşteri memnuniyeti", "😃", "Customer satisfaction has gone up since we added live chat.", "Canlı sohbeti eklediğimizden beri müşteri memnuniyeti arttı."],
      ["after-sales service", "satış sonrası hizmet", "🔧", "Good after-sales service is the reason I always buy this brand.", "Bu markayı hep almamın nedeni iyi satış sonrası hizmet."],
      ["testimonial", "müşteri yorumu, referans", "💬", "We added customer testimonials to the homepage to build trust.", "Güven oluşturmak için ana sayfaya müşteri yorumları ekledik."],
      ["unique selling point", "eşsiz satış özelliği", "💡", "The unique selling point of this phone is its two-day battery.", "Bu telefonun eşsiz satış özelliği iki gün dayanan bataryası."],
      ["value proposition", "değer önerisi", "🎁", "Our value proposition is simple, good food delivered in twenty minutes.", "Değer önerimiz basit, yirmi dakikada teslim edilen iyi yemek."],
      ["outsell", "daha çok satmak", "📈", "Electric cars may soon outsell petrol cars in some countries.", "Elektrikli arabalar bazı ülkelerde yakında benzinlilerden daha çok satabilir."],
      ["sell out", "tükenmek", "🈵", "Tickets for the concert are expected to sell out in an hour.", "Konser biletlerinin bir saatte tükenmesi bekleniyor."],
      ["product launch", "ürün lansmanı", "🚀", "The product launch will take place online next Monday.", "Ürün lansmanı önümüzdeki pazartesi çevrim içi yapılacak."],
      ["trade show", "ticaret fuarı", "🎪", "We met our biggest customer at a trade show in Istanbul.", "En büyük müşterimizle İstanbul'daki bir ticaret fuarında tanıştık."],
      ["booth", "stant", "⛺", "Visit our booth at the fair to try the product for free.", "Ürünü ücretsiz denemek için fuardaki standımızı ziyaret edin."],
      ["free sample", "ücretsiz numune", "🧴", "The store was giving away a free sample of perfume to every customer.", "Mağaza her müşteriye ücretsiz parfüm numunesi dağıtıyordu."],
      ["giveaway", "hediye çekilişi, bedava dağıtım", "🎁", "We are running a giveaway on Instagram to celebrate our birthday.", "Doğum günümüzü kutlamak için Instagram'da bir hediye çekilişi yapıyoruz."],
      ["flyer", "el ilanı", "📄", "Students were handing out flyers for the new pizza place.", "Öğrenciler yeni pizzacının el ilanlarını dağıtıyordu."],
      ["leaflet", "broşür, tanıtım kâğıdı", "📃", "There is a leaflet in the box with all the safety information.", "Kutunun içinde tüm güvenlik bilgilerini içeren bir broşür var."],
      ["catalogue", "katalog", "📒", "You can order anything from the catalogue by phone.", "Katalogdaki her şeyi telefonla sipariş edebilirsin."],
      ["press release", "basın bülteni", "📰", "The company issued a press release about its new chief executive.", "Şirket yeni genel müdürü hakkında bir basın bülteni yayımladı."],
      ["public relations", "halkla ilişkiler", "🎙️", "She studied public relations and now works for a hotel chain.", "Halkla ilişkiler okudu ve şimdi bir otel zincirinde çalışıyor."],
      ["hype", "abartılı ilgi, şişirme", "🎈", "The film didn't live up to all the hype.", "Film tüm o abartılı ilgiyi hak etmedi."],
      ["buzz", "heyecan, dedikodu, gündem", "🐝", "There is a lot of buzz online about the new game.", "İnternette yeni oyun hakkında çok fazla konuşuluyor."],
      ["trendsetter", "moda belirleyen kişi", "😎", "She was a real trendsetter, wearing those boots years before anyone else.", "Gerçek bir moda öncüsüydü, o botları herkesten yıllar önce giydi."],
      ["market leader", "pazar lideri", "👑", "They became the market leader in coffee machines within five years.", "Beş yıl içinde kahve makinelerinde pazar lideri oldular."],
      ["sales figures", "satış rakamları", "🔢", "The latest sales figures are better than we expected.", "Son satış rakamları beklediğimizden daha iyi."],
      ["sales target", "satış hedefi", "🎯", "Our team reached its sales target two weeks early.", "Ekibimiz satış hedefine iki hafta erken ulaştı."],
      ["quota", "kota", "📊", "Each rep has a monthly quota of forty new contracts.", "Her temsilcinin aylık kırk yeni sözleşmelik bir kotası var."],
      ["commission", "komisyon, prim", "💰", "Estate agents earn a commission on every house they sell.", "Emlakçılar sattıkları her evden komisyon alır."],
      ["sales representative", "satış temsilcisi", "🧑‍💼", "A sales representative will call you to arrange a demo.", "Bir satış temsilcisi tanıtım ayarlamak için sizi arayacak."],
      ["account manager", "müşteri temsilcisi", "📇", "Your account manager will help you with any problems.", "Müşteri temsilciniz her türlü sorunda size yardım edecek."],
      ["clientele", "müşteri kitlesi", "🥂", "The hotel's clientele is mostly business travellers and diplomats.", "Otelin müşteri kitlesi çoğunlukla iş seyahatçileri ve diplomatlar."],
      ["consumerism", "tüketim kültürü", "🛍️", "Black Friday is often criticized as a symbol of consumerism.", "Kara Cuma sık sık tüketim kültürünün bir sembolü olarak eleştiriliyor."],
      ["demographic", "demografik grup", "📊", "The app is popular with an older demographic than we expected.", "Uygulama beklediğimizden daha yaşlı bir demografik grupta popüler."],
      ["segment", "segment, pazar dilimi", "🍰", "Students are the fastest-growing segment of our customers.", "Öğrenciler müşterilerimizin en hızlı büyüyen segmenti."],
      ["analytics", "analitik veriler", "📈", "Website analytics show that most visitors leave after ten seconds.", "Web sitesi analitikleri ziyaretçilerin çoğunun on saniye sonra ayrıldığını gösteriyor."],
      ["social media marketing", "sosyal medya pazarlaması", "📱", "Social media marketing is cheaper than television ads for small brands.", "Küçük markalar için sosyal medya pazarlaması televizyon reklamlarından daha ucuz."],
      ["content marketing", "içerik pazarlaması", "✍️", "Through content marketing, the company shares free recipes to attract buyers.", "Şirket içerik pazarlamasıyla alıcı çekmek için ücretsiz tarifler paylaşıyor."],
      ["pop-up", "geçici mağaza, açılır pencere", "🎪", "The brand opened a pop-up shop in the mall for just one week.", "Marka alışveriş merkezinde sadece bir haftalığına geçici bir mağaza açtı."],
      ["banner", "afiş, internet reklam bandı", "🏳️", "Most people ignore the banner ads at the top of websites.", "Çoğu insan web sitelerinin üstündeki afiş reklamlarını görmezden geliyor."],
      ["sponsored post", "sponsorlu paylaşım", "📌", "That travel blogger was paid for every sponsored post she shared.", "O seyahat blogçusuna paylaştığı her sponsorlu gönderi için ödeme yapıldı."],
      ["outreach", "erişim çalışması, tanıtım faaliyeti", "📣", "Our outreach to local schools brought in many new customers.", "Yerel okullara yönelik tanıtım çalışmamız birçok yeni müşteri getirdi."],
      ["cold email", "tanımadığı birine gönderilen satış e-postası", "✉️", "I sent a cold email to the manager, and she actually replied.", "Müdüre tanışmadan bir e-posta gönderdim ve gerçekten cevap verdi."],
      ["rapport", "yakınlık, iyi ilişki", "🤗", "Good salespeople build rapport before they talk about prices.", "İyi satıcılar fiyatlardan söz etmeden önce yakınlık kurar."],
      ["repeat customer", "sürekli müşteri", "🔁", "A repeat customer is worth much more than a one-time buyer.", "Sürekli bir müşteri tek seferlik bir alıcıdan çok daha değerlidir."],
      ["customer retention", "müşteriyi elde tutma", "🧲", "Customer retention is cheaper than finding new buyers.", "Müşteriyi elde tutmak yeni alıcı bulmaktan daha ucuz."],
      ["churn", "müşteri kaybı, abonelik iptal oranı", "🌪️", "The streaming service is trying to reduce churn by adding more films.", "Yayın servisi daha fazla film ekleyerek müşteri kaybını azaltmaya çalışıyor."],
      ["pain point", "müşterinin sorunu, can sıkan nokta", "🩹", "Long waiting times are the biggest pain point for our customers.", "Uzun bekleme süreleri müşterilerimizin en büyük sorunu."],
      ["loss leader", "zararına satılan çekici ürün", "🧲", "The supermarket sells cheap bread as a loss leader to bring people in.", "Süpermarket insanları içeri çekmek için ekmeği zararına ucuz satıyor."],
      ["price war", "fiyat savaşı", "⚔️", "A price war between the two airlines made flights incredibly cheap.", "İki havayolu arasındaki fiyat savaşı uçuşları inanılmaz ucuzlattı."]
    ] },
  { id: "lib1c", title: "Finans ve Yatırım", icon: "📈", cefr: "C1", desc: "Borsa, muhasebe, kredi, vergi ve kişisel yatırım konularında ileri düzey finans kelimeleri.",
    words: [
      ["asset", "varlık", "🏠", "Her most valuable asset is the apartment she inherited from her grandmother.", "En değerli varlığı büyükannesinden miras kalan daire."],
      ["liability", "yükümlülük, borç", "⛓️", "Each loan is recorded as a liability on the company's balance sheet.", "Her kredi şirketin bilançosunda bir yükümlülük olarak kaydedilir."],
      ["diversification", "çeşitlendirme", "🧺", "Diversification reduces the risk of losing everything in a single crash.", "Çeşitlendirme tek bir çöküşte her şeyi kaybetme riskini azaltır."],
      ["stock exchange", "borsa", "🏛️", "The firm hopes to be listed on the stock exchange within two years.", "Firma iki yıl içinde borsaya kote olmayı umuyor."],
      ["share price", "hisse fiyatı", "💹", "The share price fell sharply after the disappointing results were published.", "Hayal kırıklığı yaratan sonuçlar yayımlandıktan sonra hisse fiyatı sert düştü."],
      ["bond", "tahvil", "📜", "Government bonds are usually seen as a safer investment than shares.", "Devlet tahvilleri genellikle hisselerden daha güvenli bir yatırım olarak görülür."],
      ["yield", "getiri", "🌾", "The yield on these bonds has risen to nearly six percent.", "Bu tahvillerin getirisi yüzde altıya yaklaştı."],
      ["compound interest", "bileşik faiz", "🌱", "Thanks to compound interest, small monthly savings can grow surprisingly large.", "Bileşik faiz sayesinde küçük aylık birikimler şaşırtıcı derecede büyüyebilir."],
      ["boom", "patlama, hızlı büyüme dönemi", "💥", "The housing boom made property owners rich almost overnight.", "Konut patlaması mülk sahiplerini neredeyse bir gecede zengin etti."],
      ["volatility", "oynaklık, dalgalanma", "🎢", "Cryptocurrencies are well known for their extreme price volatility.", "Kripto paralar aşırı fiyat oynaklıklarıyla iyi bilinir."],
      ["liquidity", "likidite, nakde çevrilebilirlik", "💧", "Property offers good returns but very little liquidity.", "Gayrimenkul iyi getiri sağlar ama likiditesi çok düşüktür."],
      ["capital", "sermaye", "💰", "They raised enough capital to open three more factories.", "Üç fabrika daha açmaya yetecek kadar sermaye topladılar."],
      ["venture capital", "girişim sermayesi", "🦄", "The app was funded almost entirely by venture capital.", "Uygulama neredeyse tamamen girişim sermayesiyle finanse edildi."],
      ["initial public offering", "halka arz", "🔔", "The initial public offering raised far more money than analysts expected.", "Halka arz analistlerin beklediğinden çok daha fazla para topladı."],
      ["market capitalization", "piyasa değeri", "🏦", "Its market capitalization is now larger than that of many national economies.", "Piyasa değeri artık birçok ulusal ekonomiden daha büyük."],
      ["net profit", "net kâr", "➕", "After taxes and salaries, our net profit was surprisingly small.", "Vergiler ve maaşlardan sonra net kârımız şaşırtıcı derecede küçüktü."],
      ["gross profit", "brüt kâr", "📊", "Gross profit doesn't tell you much if your running costs are huge.", "İşletme maliyetlerin çok büyükse brüt kâr sana pek bir şey anlatmaz."],
      ["balance sheet", "bilanço", "📋", "A quick look at the balance sheet shows that the company is heavily in debt.", "Bilançoya kısa bir bakış şirketin ağır borç içinde olduğunu gösteriyor."],
      ["overheads", "genel giderler", "💡", "Working from home helped us cut our overheads by almost a third.", "Evden çalışmak genel giderlerimizi neredeyse üçte bir azaltmamıza yardım etti."],
      ["fixed costs", "sabit maliyetler", "🧱", "Rent and insurance are fixed costs that we pay regardless of sales.", "Kira ve sigorta, satışlardan bağımsız ödediğimiz sabit maliyetlerdir."],
      ["variable costs", "değişken maliyetler", "📦", "As production increases, our variable costs rise as well.", "Üretim arttıkça değişken maliyetlerimiz de yükseliyor."],
      ["return on investment", "yatırımın getirisi", "🔁", "The marketing campaign delivered an impressive return on investment.", "Pazarlama kampanyası etkileyici bir yatırım getirisi sağladı."],
      ["depreciation", "amortisman, değer kaybı", "📉", "A new car suffers heavy depreciation in its first year.", "Yeni bir araba ilk yılında ciddi değer kaybına uğrar."],
      ["write off", "zarar yazmak, silmek", "🗑️", "The bank had to write off millions in loans that would never be repaid.", "Banka asla geri ödenmeyecek milyonlarca liralık krediyi zarar yazmak zorunda kaldı."],
      ["bad debt", "tahsil edilemeyen alacak", "🚫", "Several unpaid invoices were finally recorded as bad debt.", "Ödenmeyen birkaç fatura sonunda tahsil edilemeyen alacak olarak kaydedildi."],
      ["default", "borcunu ödeyememek, temerrüde düşmek", "⚠️", "If the country defaults on its loans, its currency could collapse.", "Ülke borçlarını ödeyemezse para birimi çökebilir."],
      ["go bankrupt", "iflas etmek", "💸", "Without a new investor, the airline will go bankrupt by winter.", "Yeni bir yatırımcı olmazsa havayolu kışa kadar iflas edecek."],
      ["insolvent", "ödeme güçlüğü içinde, aciz hâlde", "🕳️", "The court declared the construction company insolvent last week.", "Mahkeme geçen hafta inşaat şirketinin aciz hâlde olduğunu ilan etti."],
      ["creditor", "alacaklı", "📬", "The company's creditors met to decide whether to accept the offer.", "Şirketin alacaklıları teklifi kabul edip etmeyeceklerine karar vermek için toplandı."],
      ["embezzlement", "zimmete para geçirme", "🕵️", "The accountant was arrested for embezzlement after funds went missing.", "Fonlar kaybolduktan sonra muhasebeci zimmete para geçirmekten tutuklandı."],
      ["collateral", "teminat", "🔐", "He used his house as collateral to get the business loan.", "İşletme kredisini almak için evini teminat olarak gösterdi."],
      ["lender", "borç veren, kredi veren kurum", "🏦", "Most lenders want to see three years of tax records.", "Kredi veren kurumların çoğu üç yıllık vergi kayıtlarını görmek ister."],
      ["borrower", "borç alan", "🙏", "Borrowers with a poor history usually pay much higher interest.", "Geçmişi kötü olan borçlular genellikle çok daha yüksek faiz öder."],
      ["credit rating", "kredi notu", "⭐", "The agency lowered the country's credit rating after the election.", "Kuruluş seçimden sonra ülkenin kredi notunu düşürdü."],
      ["down payment", "peşinat", "🔑", "We spent four years saving for the down payment on our flat.", "Dairemizin peşinatı için dört yıl para biriktirdik."],
      ["tax return", "vergi beyannamesi", "🧾", "Freelancers must submit their tax return before the end of March.", "Serbest çalışanlar vergi beyannamelerini mart sonundan önce vermek zorunda."],
      ["tax evasion", "vergi kaçırma", "🚔", "The businessman was sentenced to prison for tax evasion.", "İş insanı vergi kaçırmaktan hapis cezasına çarptırıldı."],
      ["tax avoidance", "yasal yollarla vergiden kaçınma", "🧮", "Tax avoidance is legal, but many people consider it unethical.", "Yasal yollarla vergiden kaçınma yasaldır ama birçok kişi bunu ahlaka aykırı bulur."],
      ["deductible", "vergiden düşülebilir", "✂️", "Some work expenses, like training courses, are tax deductible.", "Eğitim kursları gibi bazı iş giderleri vergiden düşülebilir."],
      ["audit", "denetim", "🔍", "The annual audit revealed several errors in the accounts.", "Yıllık denetim hesaplarda birkaç hata ortaya çıkardı."],
      ["auditor", "denetçi", "🧑‍💼", "An independent auditor checks the bank's records every year.", "Bağımsız bir denetçi her yıl bankanın kayıtlarını kontrol ediyor."],
      ["fiscal year", "mali yıl", "📅", "In many companies, the fiscal year does not start in January.", "Birçok şirkette mali yıl ocak ayında başlamaz."],
      ["fiscal policy", "maliye politikası", "🏛️", "The new government promised a stricter fiscal policy to control spending.", "Yeni hükûmet harcamaları kontrol etmek için daha sıkı bir maliye politikası sözü verdi."],
      ["monetary policy", "para politikası", "🪙", "Changes in monetary policy can affect the price of everything you buy.", "Para politikasındaki değişiklikler aldığın her şeyin fiyatını etkileyebilir."],
      ["hedge", "riskten korunmak", "🛡️", "Many investors buy gold to hedge against rising prices.", "Birçok yatırımcı artan fiyatlara karşı korunmak için altın alıyor."],
      ["hedge fund", "serbest yatırım fonu", "🎩", "He left banking to work for a hedge fund in London.", "Londra'da bir serbest yatırım fonunda çalışmak için bankacılığı bıraktı."],
      ["mutual fund", "yatırım fonu", "🧺", "A mutual fund lets small investors own a share of many companies.", "Yatırım fonu küçük yatırımcıların birçok şirketten pay sahibi olmasını sağlar."],
      ["index fund", "endeks fonu", "📈", "Index funds are popular because their fees are very low.", "Endeks fonları ücretleri çok düşük olduğu için popüler."],
      ["speculation", "spekülasyon", "🎲", "Rising rents in the city are partly driven by speculation.", "Şehirdeki artan kiralar kısmen spekülasyondan kaynaklanıyor."],
      ["speculate", "spekülasyon yapmak", "🔮", "It is risky to speculate on currencies with borrowed money.", "Borç parayla döviz üzerine spekülasyon yapmak risklidir."],
      ["short-selling", "açığa satış", "⬇️", "Short-selling allows traders to profit when a share price falls.", "Açığa satış, hisse fiyatı düştüğünde yatırımcıların kâr etmesini sağlar."],
      ["broker", "aracı kurum, komisyoncu", "📞", "My broker advised me not to sell my shares yet.", "Aracım hisselerimi henüz satmamamı tavsiye etti."],
      ["brokerage", "aracı kurum, komisyon ücreti", "🏢", "Online brokerage apps have made investing much easier for young people.", "Çevrim içi aracı kurum uygulamaları gençler için yatırımı çok kolaylaştırdı."],
      ["day trading", "gün içi alım satım", "⏱️", "He quit his job for day trading and lost most of his savings.", "Gün içi alım satım yapmak için işini bıraktı ve birikimlerinin çoğunu kaybetti."],
      ["risk tolerance", "risk toleransı", "🧗", "Young investors often have a higher risk tolerance than retirees.", "Genç yatırımcıların risk toleransı genellikle emeklilerden daha yüksektir."],
      ["risk-averse", "riskten kaçınan", "🐢", "My parents are very risk-averse, so they keep their money in the bank.", "Annemle babam riskten çok kaçınır, bu yüzden paralarını bankada tutarlar."],
      ["nest egg", "kenarda tutulan birikim", "🪺", "They built up a nice nest egg by saving a little every month.", "Her ay biraz biriktirerek güzel bir birikim yaptılar."],
      ["pension fund", "emeklilik fonu", "👴", "The pension fund invests workers' money in property and shares.", "Emeklilik fonu çalışanların parasını gayrimenkul ve hisselere yatırıyor."],
      ["surplus", "fazla, bütçe fazlası", "➕", "For the first time in years, the city budget showed a surplus.", "Yıllardır ilk kez şehir bütçesi fazla verdi."],
      ["national debt", "kamu borcu, ulusal borç", "🏦", "The national debt has doubled over the past decade.", "Ulusal borç son on yılda iki katına çıktı."],
      ["stimulus", "teşvik paketi", "💉", "The government announced a stimulus package to support small businesses.", "Hükûmet küçük işletmeleri desteklemek için bir teşvik paketi açıkladı."],
      ["takeover", "devralma, şirket satın alımı", "🦈", "Staff were worried about losing their jobs after the takeover.", "Çalışanlar devralmadan sonra işlerini kaybetmekten endişeliydi."],
      ["wealth management", "varlık yönetimi", "💎", "The bank offers wealth management services to its richest clients.", "Banka en zengin müşterilerine varlık yönetimi hizmeti sunuyor."],
      ["financial advisor", "mali danışman", "🧑‍🏫", "A good financial advisor will explain every fee clearly.", "İyi bir mali danışman her ücreti açıkça anlatır."],
      ["net worth", "net servet", "📊", "His net worth increased dramatically after the company went public.", "Şirket halka açıldıktan sonra net serveti büyük ölçüde arttı."],
      ["income stream", "gelir kaynağı", "🌊", "Renting out her spare room gave her a second income stream.", "Boş odasını kiraya vermek ona ikinci bir gelir kaynağı sağladı."],
      ["passive income", "pasif gelir", "😴", "Many people dream of earning passive income from online courses.", "Birçok kişi çevrim içi kurslardan pasif gelir elde etmeyi hayal ediyor."],
      ["capital gains", "sermaye kazancı", "📈", "You may have to pay tax on capital gains when you sell the house.", "Evi sattığında sermaye kazancı üzerinden vergi ödemen gerekebilir."],
      ["appreciate", "değer kazanmak", "⬆️", "Land in this area is likely to appreciate once the new metro opens.", "Yeni metro açıldığında bu bölgedeki arsaların değer kazanması muhtemel."],
      ["depreciate", "değer kaybetmek", "⬇️", "The lira continued to depreciate against the dollar last month.", "Lira geçen ay dolar karşısında değer kaybetmeye devam etti."],
      ["financial statement", "mali tablo", "📑", "Investors studied the financial statement carefully before buying shares.", "Yatırımcılar hisse almadan önce mali tabloyu dikkatle incelediler."],
      ["projection", "öngörü, tahmin", "🔭", "Our sales projection for next year looks quite optimistic.", "Gelecek yıl için satış öngörümüz oldukça iyimser görünüyor."],
      ["earnings", "kazanç", "💵", "The company will report its quarterly earnings on Thursday.", "Şirket çeyrek dönem kazançlarını perşembe açıklayacak."],
      ["accrue", "birikmek, tahakkuk etmek", "⏳", "Interest will accrue on the loan from the first day.", "Kredide faiz ilk günden itibaren işlemeye başlayacak."],
      ["outstanding", "ödenmemiş, vadesi gelmiş", "📌", "You still have an outstanding balance of two thousand lira.", "Hâlâ iki bin liralık ödenmemiş bir bakiyeniz var."],
      ["accounts payable", "borç hesapları, ödenecek hesaplar", "📤", "Our accounts payable team pays suppliers every second Friday.", "Ödenecek hesaplar ekibimiz tedarikçilere iki haftada bir cuma ödeme yapıyor."],
      ["accounts receivable", "alacak hesapları", "📥", "Accounts receivable keeps growing because clients are paying late.", "Müşteriler geç ödediği için alacak hesapları büyümeye devam ediyor."],
      ["ledger", "muhasebe defteri", "📒", "Every transaction is recorded in the general ledger.", "Her işlem genel muhasebe defterine kaydedilir."],
      ["bookkeeping", "defter tutma", "✏️", "She does the bookkeeping for several small shops in the neighbourhood.", "Mahalledeki birkaç küçük dükkânın defterini o tutuyor."],
      ["solvency", "ödeme gücü", "🧱", "Regulators are worried about the solvency of some smaller banks.", "Düzenleyiciler bazı küçük bankaların ödeme gücünden endişeli."],
      ["margin call", "teminat tamamlama çağrısı", "📲", "When the market fell, he received a margin call he couldn't pay.", "Piyasa düşünce ödeyemeyeceği bir teminat tamamlama çağrısı aldı."],
      ["bubble", "balon, spekülatif şişkinlik", "🫧", "Many experts believe the housing market is a bubble about to burst.", "Birçok uzman konut piyasasının patlamak üzere olan bir balon olduğuna inanıyor."],
      ["market crash", "piyasa çöküşü", "💥", "She lost half her savings in the market crash of that year.", "O yılki piyasa çöküşünde birikimlerinin yarısını kaybetti."],
      ["rally", "toparlanma, yükseliş", "🚀", "Shares staged a strong rally after the interest rate cut.", "Faiz indiriminden sonra hisseler güçlü bir yükseliş gösterdi."],
      ["skyrocket", "fırlamak, hızla yükselmek", "🚀", "Rents have skyrocketed since the university opened nearby.", "Yakına üniversite açıldığından beri kiralar fırladı."],
      ["fluctuate", "dalgalanmak", "〰️", "Fuel prices fluctuate depending on the season and global events.", "Yakıt fiyatları mevsime ve küresel olaylara göre dalgalanıyor."],
      ["rebound", "yeniden toparlanmak", "🏀", "Tourism is expected to rebound strongly next summer.", "Turizmin gelecek yaz güçlü bir şekilde toparlanması bekleniyor."],
      ["recovery", "iyileşme, toparlanma", "🌤️", "The economic recovery has been slower than many had hoped.", "Ekonomik toparlanma birçok kişinin umduğundan daha yavaş oldu."],
      ["underwrite", "güvence altına almak, sigortalamak", "✒️", "Three major banks agreed to underwrite the share sale.", "Üç büyük banka hisse satışını güvence altına almayı kabul etti."],
      ["insurance premium", "sigorta primi", "🛡️", "My insurance premium went up after I had a small accident.", "Küçük bir kaza yaptıktan sonra sigorta primim arttı."],
      ["policyholder", "poliçe sahibi", "📄", "Every policyholder will receive a letter explaining the new terms.", "Her poliçe sahibi yeni koşulları açıklayan bir mektup alacak."],
      ["asset management", "portföy yönetimi, varlık yönetimi", "🗂️", "She has worked in asset management for over fifteen years.", "On beş yılı aşkın süredir portföy yönetiminde çalışıyor."],
      ["risk management", "risk yönetimi", "🧯", "Poor risk management led to huge losses at the bank.", "Kötü risk yönetimi bankada büyük kayıplara yol açtı."],
      ["windfall", "beklenmedik kazanç", "🍀", "The family used the windfall from the lottery to pay off their debts.", "Aile piyangodan gelen beklenmedik kazançla borçlarını kapattı."],
      ["interest-free", "faizsiz", "🆓", "The store offers interest-free payments over twelve months.", "Mağaza on iki aya yayılan faizsiz ödeme imkânı sunuyor."],
      ["lump sum", "toplu para, bir defada ödenen tutar", "💼", "When he retired, he received a lump sum instead of monthly payments.", "Emekli olduğunda aylık ödemeler yerine toplu bir para aldı."],
      ["wire transfer", "havale, elektronik para transferi", "🔌", "The payment was sent by wire transfer from a bank in Zurich.", "Ödeme Zürih'teki bir bankadan havale yoluyla gönderildi."],
      ["creditworthy", "kredi verilebilir, kredibilitesi yüksek", "✅", "Banks only lend to customers they consider creditworthy.", "Bankalar yalnızca kredibilitesi yüksek gördükleri müşterilere borç verir."],
      ["in the black", "kârda, artıda", "⚫", "After three difficult years, the restaurant is finally in the black.", "Üç zor yılın ardından restoran sonunda kâra geçti."],
      ["cash cow", "sürekli para getiren iş, nakit ineği", "🐄", "The old printer business remains the company's cash cow.", "Eski yazıcı işi şirketin sürekli para getiren kolu olmaya devam ediyor."],
      ["blue-chip", "köklü ve güvenilir şirket", "🔵", "Conservative investors prefer blue-chip companies with steady dividends.", "Temkinli yatırımcılar düzenli kâr payı dağıtan köklü şirketleri tercih eder."],
      ["insider trading", "içeriden öğrenenlerin ticareti", "🤫", "The director was fined for insider trading before the merger was announced.", "Müdür birleşme açıklanmadan önce içeriden bilgiyle işlem yaptığı için ceza aldı."],
      ["annuity", "yıllık gelir, rant", "🗓️", "She bought an annuity that pays her a fixed amount every month.", "Ona her ay sabit bir tutar ödeyen bir yıllık gelir planı satın aldı."],
      ["principal", "anapara", "💲", "So far, I've only paid interest and none of the principal.", "Şu ana kadar sadece faiz ödedim, anaparadan hiç ödemedim."],
      ["liquidate", "tasfiye etmek, nakde çevirmek", "🔥", "The owners decided to liquidate the business and sell its assets.", "Sahipler işletmeyi tasfiye edip varlıklarını satmaya karar verdi."],
      ["refinance", "yeniden finanse etmek, krediyi yapılandırmak", "🔄", "We plan to refinance our mortgage now that rates have fallen.", "Faizler düştüğüne göre konut kredimizi yeniden yapılandırmayı planlıyoruz."],
      ["money laundering", "kara para aklama", "🧼", "Police discovered that the car wash was used for money laundering.", "Polis oto yıkamanın kara para aklamak için kullanıldığını ortaya çıkardı."],
      ["shortfall", "açık, eksiklik", "🕳️", "The hospital faces a funding shortfall of nearly two million lira.", "Hastane yaklaşık iki milyon liralık bir finansman açığıyla karşı karşıya."],
      ["lucrative", "kazançlı, kârlı", "🤑", "Selling software to banks turned out to be a very lucrative business.", "Bankalara yazılım satmak çok kazançlı bir iş çıktı."],
      ["cost-cutting", "maliyet düşürme", "✂️", "The new boss introduced strict cost-cutting measures across the company.", "Yeni patron şirket genelinde katı maliyet düşürme önlemleri getirdi."]
    ] }
);
