(window.LIBRARY = window.LIBRARY || []).push(
  { id: "lib8a", title: "Phrasal Verbs II", icon: "🔗", cefr: "B2", desc: "Günlük hayatta ve iş yerinde sık kullanılan ileri düzey phrasal verb'ler.",
    words: [
      ["account for", "açıklamak, -in payını oluşturmak", "📊", "Young customers account for nearly half of our online sales.", "Genç müşteriler çevrim içi satışlarımızın neredeyse yarısını oluşturuyor."],
      ["act up", "huysuzlanmak, düzgün çalışmamak", "💻", "My laptop always starts to act up right before an important meeting.", "Dizüstü bilgisayarım hep önemli bir toplantıdan hemen önce sorun çıkarmaya başlıyor."],
      ["add up", "mantıklı gelmek, toplamı tutmak", "🧮", "His story about the missing money just doesn't add up.", "Kayıp parayla ilgili hikâyesi hiç mantıklı gelmiyor."],
      ["back down", "geri adım atmak", "🤚", "The manager refused to back down even after the team complained.", "Ekip şikâyet ettikten sonra bile müdür geri adım atmayı reddetti."],
      ["back up", "desteklemek, yedeklemek", "💾", "Remember to back up your files before you install the update.", "Güncellemeyi kurmadan önce dosyalarını yedeklemeyi unutma."],
      ["bank on", "-e güvenmek, bel bağlamak", "🏦", "Don't bank on getting a bonus this year, the company is struggling.", "Bu yıl prim almaya bel bağlama, şirket zor durumda."],
      ["bear with", "sabretmek, biraz beklemek", "⏳", "Please bear with me while I find your booking in the system.", "Rezervasyonunuzu sistemde bulurken lütfen biraz sabredin."],
      ["blow over", "geçip gitmek, yatışmak", "🌬️", "Don't worry about the argument, it will blow over in a few days.", "Tartışmayı dert etme, birkaç gün içinde geçip gider."],
      ["boil down to", "-e indirgenmek, özünde ... olmak", "🍲", "In the end, the whole problem seems to boil down to poor communication.", "Sonuçta bütün sorun özünde kötü iletişime dayanıyor gibi görünüyor."],
      ["bounce back", "toparlanmak, eski hâline dönmek", "🏀", "After losing her job, she managed to bounce back within a few months.", "İşini kaybettikten sonra birkaç ay içinde toparlanmayı başardı."],
      ["break into", "zorla girmek, bir alana girmek", "🚪", "It is very hard to break into the film industry without contacts.", "Tanıdık olmadan film sektörüne girmek çok zor."],
      ["break out", "patlak vermek, baş göstermek", "🔥", "Doctors fear that a serious flu epidemic could break out this winter.", "Doktorlar bu kış ciddi bir grip salgınının patlak verebileceğinden korkuyor."],
      ["bring about", "-e yol açmak, gerçekleştirmek", "⚙️", "The new director hopes to bring about real change in the company.", "Yeni direktör şirkette gerçek bir değişim yaratmayı umuyor."],
      ["bring forward", "öne almak", "📅", "Can we bring forward the meeting to Tuesday morning?", "Toplantıyı salı sabahına öne alabilir miyiz?"],
      ["bring in", "getirmek, uygulamaya koymak", "📜", "The government plans to bring in stricter rules for online shopping.", "Hükümet çevrim içi alışveriş için daha sıkı kurallar getirmeyi planlıyor."],
      ["brush off", "geçiştirmek, önemsememek", "🧹", "She tried to brush off the criticism, but it clearly hurt her.", "Eleştiriyi geçiştirmeye çalıştı ama onu açıkça üzmüştü."],
      ["build up", "biriktirmek, geliştirmek", "🧱", "It takes years to build up a loyal group of customers.", "Sadık bir müşteri kitlesi oluşturmak yıllar alır."],
      ["burn out", "tükenmek, mesleki tükenmişlik yaşamak", "🕯️", "If you work every weekend, you will burn out sooner or later.", "Her hafta sonu çalışırsan er ya da geç tükenirsin."],
      ["call for", "gerektirmek, talep etmek", "📣", "This kind of situation calls for a calm and careful response.", "Bu tür bir durum sakin ve dikkatli bir tepki gerektirir."],
      ["calm down", "sakinleşmek", "😮‍💨", "Take a deep breath and calm down before you reply to that email.", "O e-postaya cevap vermeden önce derin bir nefes al ve sakinleş."],
      ["carry out", "yürütmek, gerçekleştirmek", "🔬", "The team will carry out a detailed survey of customer habits.", "Ekip müşteri alışkanlıklarıyla ilgili ayrıntılı bir anket yürütecek."],
      ["cash in on", "-den kâr sağlamak, fırsata çevirmek", "💰", "Many shops tried to cash in on the sudden interest in home fitness.", "Pek çok mağaza evde spora olan ani ilgiden kâr sağlamaya çalıştı."],
      ["catch on", "tutmak, yaygınlaşmak, anlamak", "📈", "The idea was strange at first, but it started to catch on quickly.", "Fikir önce tuhaftı ama hızla tutmaya başladı."],
      ["chicken out", "korkup vazgeçmek", "🐔", "I planned to ask for a raise, but I chickened out at the last minute.", "Zam istemeyi planlamıştım ama son anda korkup vazgeçtim."],
      ["clear up", "açıklığa kavuşturmak, toparlamak", "🌤️", "I would like to clear up a few points before we sign the contract.", "Sözleşmeyi imzalamadan önce birkaç noktayı netleştirmek istiyorum."],
      ["close down", "kapanmak, kapatmak", "🔒", "The old cinema in our neighbourhood had to close down last year.", "Mahallemizdeki eski sinema geçen yıl kapanmak zorunda kaldı."],
      ["come along", "gelişmek, ilerlemek, eşlik etmek", "🚶", "Things are starting to come along nicely with the new project.", "Yeni projede işler güzelce ilerlemeye başlıyor."],
      ["come around", "fikrini değiştirip ikna olmak", "🔄", "My father hated the plan, but he will come around eventually.", "Babam plandan nefret etti ama sonunda ikna olacaktır."],
      ["come forward", "ortaya çıkıp bilgi vermek", "🙋", "The police asked anyone who saw the accident to come forward.", "Polis kazayı gören herkesin ortaya çıkıp bilgi vermesini istedi."],
      ["come through", "sözünü tutmak, atlatmak", "✅", "Don't worry, I know my colleagues will come through for me.", "Merak etme, meslektaşlarımın sözlerini tutup yanımda olacağını biliyorum."],
      ["crack down on", "-e sıkı önlem almak", "🚔", "The city has decided to crack down on illegal parking.", "Şehir yönetimi kaçak park etmeye karşı sıkı önlem almaya karar verdi."],
      ["cut off", "kesmek, bağlantıyı koparmak", "✂️", "Our internet was cut off because we forgot to pay the bill.", "Faturayı ödemeyi unuttuğumuz için internetimiz kesildi."],
      ["deal with", "ilgilenmek, başa çıkmak", "🤝", "I need to deal with these customer complaints before lunch.", "Öğle yemeğinden önce bu müşteri şikâyetleriyle ilgilenmem gerekiyor."],
      ["die down", "azalmak, dinmek", "🌪️", "We waited inside until the wind began to die down.", "Rüzgâr dinmeye başlayana kadar içeride bekledik."],
      ["do without", "-sız idare etmek", "🚫", "I could easily do without a car if public transport were better.", "Toplu taşıma daha iyi olsa arabasız rahatça idare edebilirdim."],
      ["drag on", "uzayıp gitmek", "🐌", "The meeting seemed to drag on for hours without any decision.", "Toplantı hiçbir karar alınmadan saatlerce uzayıp gitti sanki."],
      ["draw up", "hazırlamak, taslağını çıkarmak", "📝", "Our lawyer will draw up a new contract by Friday.", "Avukatımız cuma gününe kadar yeni bir sözleşme hazırlayacak."],
      ["dress up", "şık giyinmek, kostüm giymek", "👔", "You don't need to dress up, it is just a casual dinner.", "Şık giyinmene gerek yok, sadece rahat bir akşam yemeği."],
      ["drift apart", "zamanla birbirinden uzaklaşmak", "🛶", "We were best friends at school, but we started to drift apart after university.", "Okulda en yakın arkadaştık ama üniversiteden sonra birbirimizden uzaklaşmaya başladık."],
      ["drop off", "bırakmak, uyuyakalmak", "🚗", "I can drop off the kids at school on my way to work.", "İşe giderken çocukları okula bırakabilirim."],
      ["ease off", "hafiflemek, yavaşlamak", "🪶", "The pain should ease off after you take the medicine.", "İlacı aldıktan sonra ağrı hafiflemeli."],
      ["eat out", "dışarıda yemek yemek", "🍽️", "We usually eat out on Fridays because nobody wants to cook.", "Kimse yemek yapmak istemediği için cumaları genelde dışarıda yeriz."],
      ["fall behind", "geride kalmak, gecikmek", "🏃", "If you miss too many classes, you will fall behind the others.", "Çok fazla derse girmezsen diğerlerinin gerisinde kalırsın."],
      ["fall through", "suya düşmek, gerçekleşmemek", "🕳️", "The deal could fall through if we don't agree on the price soon.", "Fiyatta yakında anlaşamazsak anlaşma suya düşebilir."],
      ["fend off", "savuşturmak, uzak tutmak", "🛡️", "The small company managed to fend off its larger competitors.", "Küçük şirket daha büyük rakiplerini savuşturmayı başardı."],
      ["fill out", "doldurmak", "🖊️", "Please fill out this form and hand it to the receptionist.", "Lütfen bu formu doldurup resepsiyon görevlisine verin."],
      ["fit in", "uyum sağlamak, kaynaşmak", "🧩", "It took me a while to fit in at my new workplace.", "Yeni iş yerime uyum sağlamam biraz zaman aldı."],
      ["fizzle out", "sönüp gitmek, etkisini yitirmek", "🎆", "The protest started strong but began to fizzle out after a week.", "Protesto güçlü başladı ama bir hafta sonra sönmeye başladı."],
      ["follow through", "sonuna kadar götürmek", "🎯", "Making plans is easy, but you also need to follow through on them.", "Plan yapmak kolay ama onları sonuna kadar götürmen de gerekiyor."],
      ["freak out", "çok panik olmak, çıldırmak", "😱", "Don't freak out, but I think I scratched your car a little.", "Panik yapma ama sanırım arabanı biraz çizdim."],
      ["get across", "anlatmak, iletmek", "📢", "She used simple examples to get across a very complex idea.", "Çok karmaşık bir fikri anlatmak için basit örnekler kullandı."],
      ["get around to", "-e nihayet vakit bulmak", "🕰️", "I keep meaning to clean the garage, but I never get around to it.", "Garajı temizlemeyi hep düşünüyorum ama bir türlü vakit bulamıyorum."],
      ["get down to", "-e ciddi şekilde başlamak", "💼", "Let's stop chatting and get down to business.", "Sohbeti bırakıp işe ciddi şekilde başlayalım."],
      ["get through", "atlatmak, bitirmek, ulaşmak", "📞", "I tried calling the bank all morning but couldn't get through.", "Bütün sabah bankayı aradım ama ulaşamadım."],
      ["give away", "bedavaya vermek, ele vermek", "🎁", "We decided to give away our old furniture instead of selling it.", "Eski mobilyalarımızı satmak yerine bağışlamaya karar verdik."],
      ["go along with", "kabul etmek, uymak", "👍", "I didn't love the idea, but I decided to go along with it.", "Fikri pek sevmedim ama kabul etmeye karar verdim."],
      ["go over", "gözden geçirmek", "🔍", "Let's go over the presentation one more time before the client arrives.", "Müşteri gelmeden önce sunumu bir kez daha gözden geçirelim."],
      ["go without", "-sız kalmak, yoksun kalmak", "🥖", "Many families had to go without basic things during the crisis.", "Kriz sırasında birçok aile temel ihtiyaçlardan yoksun kalmak zorunda kaldı."],
      ["hand out", "dağıtmak", "📄", "The teacher will hand out the exam papers in five minutes.", "Öğretmen sınav kâğıtlarını beş dakika içinde dağıtacak."],
      ["hand over", "teslim etmek, devretmek", "🔑", "Before leaving the company, he had to hand over all his projects.", "Şirketten ayrılmadan önce bütün projelerini devretmek zorundaydı."],
      ["head off", "yola çıkmak, önlemek", "🧳", "We should head off early to avoid the traffic.", "Trafiğe yakalanmamak için erkenden yola çıkmalıyız."],
      ["hold up", "geciktirmek, dayanmak", "🚧", "Sorry, I didn't mean to hold up the meeting with my questions.", "Kusura bakmayın, sorularımla toplantıyı geciktirmek istemezdim."],
      ["jump at", "fırsatı hemen kapmak", "🦘", "Most people would jump at the chance to work in Lisbon for a year.", "Çoğu insan bir yıl Lizbon'da çalışma fırsatını hemen kapardı."],
      ["keep up with", "-e ayak uydurmak", "🏃‍♀️", "It is hard to keep up with all the changes in technology.", "Teknolojideki bütün değişikliklere ayak uydurmak zor."],
      ["lay out", "düzenlemek, ayrıntılı açıklamak", "🗺️", "In the meeting, she will lay out her plan for the next year.", "Toplantıda gelecek yıl için planını ayrıntılı olarak açıklayacak."],
      ["live up to", "beklentiyi karşılamak", "🌟", "The new restaurant did not live up to all the hype.", "Yeni restoran yapılan bütün reklamın hakkını veremedi."],
      ["make up for", "telafi etmek", "🩹", "I bought her flowers to make up for forgetting her birthday.", "Doğum gününü unuttuğumu telafi etmek için ona çiçek aldım."],
      ["mess up", "berbat etmek, karıştırmak", "🙈", "I don't want to mess up this interview, it is my dream job.", "Bu mülakatı berbat etmek istemiyorum, hayalimdeki iş."],
      ["nod off", "uyuklamak, içi geçmek", "😴", "The film was so slow that I started to nod off halfway through.", "Film o kadar yavaştı ki yarısında uyuklamaya başladım."],
      ["own up", "itiraf etmek, kabullenmek", "🙇", "Nobody wanted to own up to breaking the coffee machine.", "Kimse kahve makinesini bozduğunu itiraf etmek istemedi."],
      ["pass up", "fırsatı kaçırmak, geri çevirmek", "🙅", "You should never pass up a chance to learn something new.", "Yeni bir şey öğrenme fırsatını asla kaçırmamalısın."],
      ["pay off", "karşılığını vermek, borcu kapatmak", "🏆", "All those hours of practice finally started to pay off.", "Bütün o saatlerce çalışma sonunda karşılığını vermeye başladı."],
      ["phase out", "aşamalı olarak kaldırmak", "📉", "The company will phase out paper invoices by the end of the year.", "Şirket yıl sonuna kadar kâğıt faturaları aşamalı olarak kaldıracak."],
      ["pick on", "-e sataşmak, uğraşmak", "👊", "Older kids used to pick on him because he was small.", "Küçük olduğu için büyük çocuklar ona sataşırdı."],
      ["pile up", "birikmek, yığılmak", "📚", "If I take a day off, the emails just pile up in my inbox.", "Bir gün izin alsam e-postalar gelen kutumda birikiyor."],
      ["play down", "önemsiz göstermek", "🤏", "The minister tried to play down the seriousness of the problem.", "Bakan sorunun ciddiyetini önemsiz göstermeye çalıştı."],
      ["pop up", "aniden ortaya çıkmak", "💬", "New coffee shops seem to pop up on every corner these days.", "Bugünlerde her köşede yeni kahve dükkânları türüyor sanki."],
      ["pull off", "başarmak, üstesinden gelmek", "🎩", "Nobody believed we could pull off such a big event in two weeks.", "Kimse iki haftada böyle büyük bir etkinliği başarabileceğimize inanmadı."],
      ["pull out", "çekilmek, vazgeçmek", "🏳️", "The investor decided to pull out of the deal at the last moment.", "Yatırımcı son anda anlaşmadan çekilmeye karar verdi."],
      ["push back", "ertelemek, karşı çıkmak", "⏩", "We had to push back the launch date because of technical problems.", "Teknik sorunlar yüzünden lansman tarihini ertelemek zorunda kaldık."],
      ["put across", "anlatmak, ifade etmek", "🗣️", "He is clever but struggles to put across his ideas in meetings.", "Zeki ama toplantılarda fikirlerini ifade etmekte zorlanıyor."],
      ["put forward", "öne sürmek, önermek", "💡", "Several people put forward interesting suggestions during the workshop.", "Atölye sırasında birkaç kişi ilginç öneriler sundu."],
      ["put together", "bir araya getirmek, hazırlamak", "🛠️", "Could you put together a short report on last month's sales?", "Geçen ayın satışlarıyla ilgili kısa bir rapor hazırlayabilir misin?"],
      ["sell out", "tükenmek, satılıp bitmek", "🎟️", "Tickets for her concerts always sell out within an hour.", "Onun konserlerinin biletleri hep bir saat içinde tükenir."],
      ["set back", "geciktirmek, geri bırakmak", "⏮️", "The heavy rain will set back the construction work by weeks.", "Şiddetli yağmur inşaat çalışmalarını haftalarca geciktirecek."],
      ["set off", "yola çıkmak, tetiklemek", "🚀", "We need to set off at dawn to reach the mountain before noon.", "Öğleden önce dağa varmak için şafakta yola çıkmamız gerekiyor."],
      ["shake up", "köklü değişiklik yapmak", "🌀", "The new CEO wants to shake up the whole sales department.", "Yeni CEO bütün satış departmanında köklü değişiklik yapmak istiyor."],
      ["single out", "seçip ayırmak, özellikle belirtmek", "☝️", "It is unfair to single out one person when the whole team made mistakes.", "Bütün ekip hata yapmışken tek bir kişiyi seçip suçlamak haksızlık."],
      ["sink in", "kafasına dank etmek, idrak etmek", "💭", "It took a few days for the good news to really sink in.", "İyi haberin gerçekten idrak edilmesi birkaç gün sürdü."],
      ["slow down", "yavaşlamak", "🐢", "Doctors told him to slow down and take better care of himself.", "Doktorlar ona yavaşlamasını ve kendine daha iyi bakmasını söyledi."],
      ["speak up", "sesini yükseltmek, fikrini söylemek", "🎤", "If you disagree with the decision, you should speak up now.", "Karara katılmıyorsan şimdi fikrini söylemelisin."],
      ["spell out", "açık açık anlatmak", "🔤", "Do I really need to spell out why this plan won't work?", "Bu planın neden işe yaramayacağını gerçekten tek tek anlatmam mı gerekiyor?"],
      ["stand by", "arkasında durmak, hazır beklemek", "🫂", "I stand by what I said yesterday, even if it was unpopular.", "Popüler olmasa da dün söylediklerimin arkasındayım."],
      ["stand up for", "savunmak, arka çıkmak", "✊", "You have to stand up for yourself when people treat you unfairly.", "İnsanlar sana haksızlık ettiğinde kendini savunmalısın."],
      ["step up", "artırmak, sorumluluk almak", "🪜", "When our manager got sick, Elif decided to step up and lead the team.", "Müdürümüz hastalanınca Elif sorumluluk alıp ekibi yönetmeye karar verdi."],
      ["stick to", "-e bağlı kalmak", "📌", "Let's stick to the plan and not change anything at the last minute.", "Plana bağlı kalalım ve son anda hiçbir şeyi değiştirmeyelim."],
      ["talk into", "ikna etmek", "🗨️", "My friend tried to talk me into running a half marathon with him.", "Arkadaşım beni onunla yarı maraton koşmaya ikna etmeye çalıştı."],
      ["tear down", "yıkmak", "🏚️", "They plan to tear down the old factory and build apartments.", "Eski fabrikayı yıkıp yerine daire yapmayı planlıyorlar."],
      ["track down", "izini bulmak, bulup çıkarmak", "🕵️", "It took me weeks to track down a copy of that old record.", "O eski plağın bir kopyasını bulmam haftalarımı aldı."],
      ["tune in", "kanala ya da yayına bağlanmak", "📻", "Millions of people tune in every Sunday to watch the show.", "Milyonlarca kişi her pazar programı izlemek için yayına bağlanıyor."],
      ["turn around", "durumu düzeltmek, tersine çevirmek", "↩️", "The new manager managed to turn around the failing business.", "Yeni müdür batmakta olan işletmeyi toparlamayı başardı."],
      ["wear off", "etkisi geçmek", "☕", "The effect of the coffee started to wear off by mid-afternoon.", "Kahvenin etkisi öğleden sonra geçmeye başladı."],
      ["wear out", "yıpranmak, yormak", "👟", "These shoes will wear out quickly if you run on rough roads.", "Bozuk yollarda koşarsan bu ayakkabılar çabuk yıpranır."],
      ["wipe out", "yok etmek, silip süpürmek", "🌊", "The storm managed to wipe out most of the crops in the region.", "Fırtına bölgedeki ekinlerin çoğunu yok etti."],
      ["write off", "gözden çıkarmak, zarar yazmak", "🗑️", "Don't write off the team yet, they still have three games to play.", "Takımı henüz gözden çıkarma, daha oynayacakları üç maç var."],
      ["weigh in", "fikrini belirtmek, tartışmaya katılmak", "⚖️", "Several experts were invited to weigh in on the new housing plan.", "Yeni konut planı hakkında görüş bildirmeleri için birkaç uzman davet edildi."],
      ["look over", "göz gezdirmek, kontrol etmek", "👀", "Could you look over my CV before I send it to the company?", "Şirkete göndermeden önce CV'me bir göz atabilir misin?"],
      ["turn up", "gelmek, ortaya çıkmak, sesini açmak", "🔊", "I hope more people turn up to the meeting this time.", "Umarım bu sefer toplantıya daha fazla kişi gelir."],
      ["run through", "hızlıca gözden geçirmek, prova etmek", "🎬", "Let's run through the main points one last time before the presentation.", "Sunumdan önce ana noktaların üzerinden son bir kez hızlıca geçelim."],
      ["hold off", "ertelemek, beklemek", "✋", "We decided to hold off on buying a house until prices fall.", "Fiyatlar düşene kadar ev almayı ertelemeye karar verdik."]
    ] },
  { id: "lib8b", title: "Deyimler III", icon: "🎭", cefr: "C1", desc: "Ana dili İngilizce olanların sohbette ve iş hayatında sık kullandığı deyimler ve anlamları.",
    words: [
      ["a drop in the ocean", "devede kulak", "💧", "Our donation was just a drop in the ocean compared to what they need.", "Bağışımız onların ihtiyacının yanında devede kulak kaldı."],
      ["a far cry from", "-den çok farklı, -in çok uzağında", "📏", "This tiny flat is a far cry from the house I grew up in.", "Bu minicik daire büyüdüğüm evden çok farklı."],
      ["a penny for your thoughts", "ne düşünüyorsun bakalım", "🪙", "You look miles away, a penny for your thoughts?", "Çok dalgın görünüyorsun, ne düşünüyorsun bakalım?"],
      ["against the clock", "zamana karşı yarışarak", "⏱️", "The engineers worked against the clock to fix the system before Monday.", "Mühendisler sistemi pazartesiden önce düzeltmek için zamanla yarıştı."],
      ["all ears", "kulak kesilmek, can kulağıyla dinlemek", "👂", "If you have a better idea, I'm all ears.", "Daha iyi bir fikrin varsa can kulağıyla dinliyorum."],
      ["an uphill battle", "çok zorlu bir mücadele", "⛰️", "Getting the new law approved will be an uphill battle.", "Yeni yasayı onaylatmak çok zorlu bir mücadele olacak."],
      ["at the end of the day", "sonuçta, nihayetinde", "🌇", "At the end of the day, it's your money and your decision.", "Sonuçta senin paran ve senin kararın."],
      ["beat the odds", "tüm olasılıklara rağmen başarmak", "🎲", "The small startup managed to beat the odds and survive its first year.", "Küçük girişim her şeye rağmen ilk yılını atlatmayı başardı."],
      ["behind closed doors", "kapalı kapılar ardında, gizlice", "🚪", "The final decision was made behind closed doors without asking the staff.", "Nihai karar çalışanlara sorulmadan kapalı kapılar ardında alındı."],
      ["bend over backwards", "çırpınmak, elinden gelenin fazlasını yapmak", "🤸", "The hotel staff always bend over backwards to make their guests feel welcome.", "Otel çalışanları misafirlerini rahat ettirmek için hep çırpınır."],
      ["the best of both worlds", "iki tarafın da avantajı", "🌍", "Working from home twice a week gives me the best of both worlds.", "Haftada iki gün evden çalışmak bana iki tarafın da avantajını veriyor."],
      ["between a rock and a hard place", "iki ateş arasında", "🪨", "I'm between a rock and a hard place, both options will upset someone.", "İki ateş arasındayım, iki seçenek de birini üzecek."],
      ["bite your tongue", "dilini tutmak", "👅", "I wanted to argue, but I decided to bite my tongue and stay calm.", "Tartışmak istedim ama dilimi tutup sakin kalmaya karar verdim."],
      ["by the book", "kurallara harfiyen uyarak", "📘", "Our new accountant does everything strictly by the book.", "Yeni muhasebecimiz her şeyi kurallara harfiyen uyarak yapıyor."],
      ["by the skin of your teeth", "kıl payı", "😬", "I passed the driving test by the skin of my teeth.", "Ehliyet sınavını kıl payı geçtim."],
      ["call the shots", "sözü geçen kişi olmak, kararları vermek", "🎬", "She may be young, but she is the one who calls the shots here.", "Genç olabilir ama burada kararları veren o."],
      ["come rain or shine", "ne olursa olsun, her koşulda", "🌦️", "He goes for a run every morning, come rain or shine.", "Ne olursa olsun her sabah koşuya çıkıyor."],
      ["down to earth", "mütevazı, ayakları yere basan", "🌱", "Despite her success, she is very down to earth and friendly.", "Başarısına rağmen çok mütevazı ve samimi biri."],
      ["draw the line", "sınır koymak", "🚧", "I don't mind working late, but I draw the line at working on Sundays.", "Geç saate kadar çalışmaya itirazım yok ama pazar çalışmaya sınır koyarım."],
      ["face the music", "yaptığının sonucuna katlanmak", "🎼", "He broke the rules, and now he has to face the music.", "Kuralları çiğnedi ve şimdi sonuçlarına katlanmak zorunda."],
      ["fly off the handle", "birden parlamak, öfkeden kudurmak", "🌋", "There is no need to fly off the handle over a small mistake.", "Küçük bir hata yüzünden birden parlamana gerek yok."],
      ["get a word in edgeways", "araya bir kelime bile sokamamak", "🗣️", "She talked so much that I couldn't get a word in edgeways.", "O kadar çok konuştu ki araya tek kelime bile sokamadım."],
      ["get the hang of", "-e alışmak, işi kapmak", "🎸", "The software looks confusing, but you will get the hang of it quickly.", "Program karmaşık görünüyor ama çabucak alışırsın."],
      ["give the benefit of the doubt", "şüpheden yararlandırmak, iyi niyetle yaklaşmak", "⚖️", "He has been late twice, but let's give him the benefit of the doubt.", "İki kez geç kaldı ama ona iyi niyetle yaklaşalım."],
      ["go with the flow", "akışına bırakmak", "🌊", "I don't make detailed plans on holiday, I just go with the flow.", "Tatilde ayrıntılı plan yapmam, akışına bırakırım."],
      ["have a chip on your shoulder", "içinde bir ukde ya da kırgınlık taşımak", "🪵", "He seems to have a chip on his shoulder about not going to university.", "Üniversiteye gitmemiş olmakla ilgili içinde bir ukde var gibi görünüyor."],
      ["have second thoughts", "tereddüt etmek, ikinci kez düşünmek", "🤔", "I'm starting to have second thoughts about moving abroad.", "Yurt dışına taşınma konusunda tereddüt etmeye başlıyorum."],
      ["head over heels", "sırılsıklam aşık", "💘", "They met in Rome and fell head over heels in love.", "Roma'da tanıştılar ve birbirlerine sırılsıklam aşık oldular."],
      ["hit the roof", "tepesi atmak, küplere binmek", "🤯", "My dad will hit the roof when he sees the phone bill.", "Babam telefon faturasını görünce küplere binecek."],
      ["hold your horses", "acele etme, bir dakika dur", "🐎", "Hold your horses, we haven't even signed the contract yet.", "Acele etme, daha sözleşmeyi bile imzalamadık."],
      ["in hot water", "başı belada", "♨️", "He is in hot water for sharing confidential files with a friend.", "Gizli dosyaları bir arkadaşıyla paylaştığı için başı belada."],
      ["in the bag", "cepte, garantide", "👜", "With two goals ahead and five minutes left, the win is in the bag.", "İki gol önde ve beş dakika kalmışken galibiyet cepte."],
      ["in the dark", "habersiz, karanlıkta", "🌑", "The employees were kept in the dark about the merger until the last day.", "Çalışanlar birleşmeden son güne kadar habersiz bırakıldı."],
      ["in the loop", "haberdar, bilgi akışının içinde", "🔁", "Please keep me in the loop about any changes to the schedule.", "Lütfen programdaki her değişiklikten beni haberdar et."],
      ["it's not rocket science", "o kadar da zor değil", "🚀", "Just follow the instructions, it's not rocket science.", "Talimatları takip et yeter, o kadar da zor değil."],
      ["jump the gun", "aceleci davranmak, erken davranmak", "🔫", "Let's not jump the gun, we don't know the results yet.", "Aceleci davranmayalım, sonuçları henüz bilmiyoruz."],
      ["keep your chin up", "moralini bozma", "🙂", "Keep your chin up, you'll find an even better job soon.", "Moralini bozma, yakında çok daha iyi bir iş bulacaksın."],
      ["leave no stone unturned", "taş üstünde taş bırakmamak, her yolu denemek", "🔎", "The detectives promised to leave no stone unturned in their search.", "Dedektifler aramalarında her yolu deneyeceklerine söz verdi."],
      ["let sleeping dogs lie", "eski defterleri açmamak", "🐕", "I wanted to ask about their divorce, but I decided to let sleeping dogs lie.", "Boşanmalarını sormak istedim ama eski defterleri açmamaya karar verdim."],
      ["lose your touch", "eski ustalığını kaybetmek", "🎯", "Many great players lose their touch as they get older.", "Birçok büyük oyuncu yaşlandıkça eski ustalığını kaybeder."],
      ["make a mountain out of a molehill", "pireyi deve yapmak", "🐜", "It's only a small scratch, don't make a mountain out of a molehill.", "Sadece küçük bir çizik, pireyi deve yapma."],
      ["make waves", "ortalığı karıştırmak, ses getirmek", "🌊", "The new manager is careful not to make waves in her first month.", "Yeni müdür ilk ayında ortalığı karıştırmamaya özen gösteriyor."],
      ["no strings attached", "hiçbir şart olmadan, karşılıksız", "🎈", "They offered us a free trial with no strings attached.", "Bize hiçbir şart olmadan ücretsiz deneme sundular."],
      ["not my cup of tea", "pek bana göre değil", "🍵", "Horror films are not my cup of tea, I prefer comedies.", "Korku filmleri pek bana göre değil, komedileri tercih ederim."],
      ["off the record", "kayıt dışı, aramızda kalsın", "🎙️", "Off the record, the director is planning to resign next month.", "Aramızda kalsın, müdür gelecek ay istifa etmeyi planlıyor."],
      ["off the top of my head", "aklıma ilk gelen, düşünmeden söylersem", "🧠", "Off the top of my head, I'd say the trip will cost about two thousand.", "Düşünmeden söylersem yolculuk iki bin civarı tutar derim."],
      ["on the ball", "uyanık, işini bilen", "⚽", "Our new assistant is really on the ball, she never misses a deadline.", "Yeni asistanımız gerçekten çok uyanık, hiçbir teslim tarihini kaçırmıyor."],
      ["on the dot", "tam vaktinde, dakikası dakikasına", "🕘", "The train left at nine o'clock on the dot.", "Tren tam saat dokuzda kalktı."],
      ["on the mend", "iyileşmekte", "🩹", "Grandma had a bad flu, but she's on the mend now.", "Büyükannem kötü bir grip geçirdi ama şimdi iyileşiyor."],
      ["out of the woods", "tehlikeyi atlatmış", "🌲", "The company is doing better, but it's not out of the woods yet.", "Şirket daha iyi durumda ama henüz tehlikeyi atlatmış değil."],
      ["pass the buck", "sorumluluğu başkasına atmak", "🫳", "Every department tried to pass the buck when the project failed.", "Proje başarısız olunca her departman sorumluluğu başkasına atmaya çalıştı."],
      ["play devil's advocate", "şeytanın avukatlığını yapmak", "😈", "Let me play devil's advocate for a moment and question this plan.", "İzin verin bir an şeytanın avukatlığını yapıp bu planı sorgulayayım."],
      ["put all your eggs in one basket", "bütün yumurtaları aynı sepete koymak", "🧺", "Don't put all your eggs in one basket, invest in different areas.", "Bütün yumurtaları aynı sepete koyma, farklı alanlara yatırım yap."],
      ["put your foot down", "kesin tavır koymak", "🦶", "When the kids wanted a third dog, I had to put my foot down.", "Çocuklar üçüncü bir köpek isteyince kesin tavır koymak zorunda kaldım."],
      ["put your foot in your mouth", "pot kırmak, çam devirmek", "🙊", "I really put my foot in my mouth when I asked about her ex.", "Eski sevgilisini sorduğumda resmen çam devirdim."],
      ["take a rain check", "başka bir zamana ertelemek", "☔", "I'm exhausted tonight, can I take a rain check on dinner?", "Bu akşam çok yorgunum, yemeği başka bir zamana erteleyebilir miyiz?"],
      ["ring a bell", "tanıdık gelmek", "🔔", "His name rings a bell, but I can't remember where we met.", "Adı tanıdık geliyor ama nerede tanıştığımızı hatırlayamıyorum."],
      ["rock the boat", "huzuru bozmak, düzeni sarsmak", "🚣", "Everyone was happy with the plan, so I didn't want to rock the boat.", "Herkes plandan memnundu, bu yüzden huzuru bozmak istemedim."],
      ["rub salt in the wound", "yaraya tuz basmak", "🧂", "Losing was bad enough, so please don't rub salt in the wound.", "Kaybetmek yeterince kötüydü, lütfen yaraya tuz basma."],
      ["run in the family", "ailede olmak, soydan gelmek", "👪", "Musical talent seems to run in the family, they all play something.", "Müzik yeteneği ailede var gibi, hepsi bir şey çalıyor."],
      ["save face", "itibarını korumak, yüzünü kurtarmak", "🎭", "The company offered a refund to save face after the scandal.", "Şirket skandalın ardından itibarını korumak için para iadesi teklif etti."],
      ["second nature", "alışkanlık hâline gelmiş, ikinci doğa", "🔄", "After years of practice, typing without looking became second nature.", "Yıllarca çalıştıktan sonra bakmadan yazmak ikinci doğam oldu."],
      ["see the bigger picture", "resmin bütününü görmek", "🖼️", "Try to see the bigger picture instead of focusing on small problems.", "Küçük sorunlara takılmak yerine resmin bütününü görmeye çalış."],
      ["shoot yourself in the foot", "kendi ayağına sıkmak", "🦶", "By lying to the client, you would only shoot yourself in the foot.", "Müşteriye yalan söyleyerek sadece kendi ayağına sıkmış olursun."],
      ["sleep on it", "bir gece düşünmek", "🛏️", "It's a big decision, so sleep on it and tell me tomorrow.", "Büyük bir karar, bir gece düşün ve yarın bana söyle."],
      ["smell a rat", "bir terslik sezmek, işkillenmek", "🐀", "When he refused to show the receipts, I started to smell a rat.", "Fişleri göstermeyi reddedince bir terslik sezmeye başladım."],
      ["stab in the back", "sırtından bıçaklamak", "🔪", "I trusted him completely, so I never expected him to stab me in the back.", "Ona tamamen güveniyordum, sırtımdan bıçaklayacağını hiç beklemiyordum."],
      ["start from scratch", "sıfırdan başlamak", "✏️", "The file was deleted, so we had to start from scratch.", "Dosya silindi, bu yüzden sıfırdan başlamak zorunda kaldık."],
      ["stick to your guns", "fikrinden dönmemek, inadından vazgeçmemek", "💪", "Everyone disagreed, but she decided to stick to her guns.", "Herkes karşı çıktı ama o fikrinden dönmemeye karar verdi."],
      ["take a back seat", "geri planda kalmak", "💺", "After retiring, he decided to take a back seat and let his daughter run the shop.", "Emekli olduktan sonra geri plana çekilip dükkânı kızının yönetmesine izin verdi."],
      ["the best thing since sliced bread", "dünyanın en harika icadı", "🍞", "My brother thinks his new phone is the best thing since sliced bread.", "Kardeşim yeni telefonunun dünyanın en harika icadı olduğunu düşünüyor."],
      ["the devil is in the details", "asıl zorluk ayrıntılarda gizli", "🔍", "The plan sounds simple, but the devil is in the details.", "Plan basit görünüyor ama asıl zorluk ayrıntılarda gizli."],
      ["the icing on the cake", "üstüne üstlük, işin en güzel kısmı", "🎂", "The job pays well, and the free gym is the icing on the cake.", "İş iyi para veriyor, ücretsiz spor salonu da cabası."],
      ["throw caution to the wind", "temkini elden bırakmak, gözünü karartmak", "🌬️", "For once, I decided to throw caution to the wind and book the trip.", "Bir kerelik gözümü karartıp yolculuğu ayarlamaya karar verdim."],
      ["tie the knot", "dünya evine girmek, evlenmek", "💍", "After ten years together, they finally decided to tie the knot.", "On yıllık birlikteliğin ardından sonunda evlenmeye karar verdiler."],
      ["to cut a long story short", "uzun lafın kısası", "✂️", "To cut a long story short, we missed the flight and stayed another night.", "Uzun lafın kısası, uçağı kaçırdık ve bir gece daha kaldık."],
      ["under the radar", "dikkat çekmeden, göze batmadan", "📡", "The small change went under the radar until customers complained.", "Küçük değişiklik müşteriler şikâyet edene kadar kimsenin dikkatini çekmedi."],
      ["up to scratch", "beklenen düzeyde, yeterli", "📋", "If your work isn't up to scratch, you'll have to do it again.", "İşin beklenen düzeyde değilse yeniden yapman gerekecek."],
      ["wear your heart on your sleeve", "duygularını saklamamak", "❤️", "He wears his heart on his sleeve, so you always know how he feels.", "Duygularını hiç saklamaz, bu yüzden ne hissettiğini her zaman bilirsin."],
      ["when it rains it pours", "aksilikler hep üst üste gelir", "⛈️", "First my car broke down, then I lost my keys, when it rains it pours.", "Önce arabam bozuldu, sonra anahtarlarımı kaybettim, aksilikler hep üst üste gelir."],
      ["with flying colours", "parlak bir başarıyla", "🎓", "She passed all her final exams with flying colours.", "Bütün final sınavlarını parlak bir başarıyla geçti."],
      ["word of mouth", "kulaktan kulağa, ağızdan ağıza", "👄", "Our café never advertised, all our customers came through word of mouth.", "Kafemiz hiç reklam vermedi, bütün müşterilerimiz kulaktan kulağa duyup geldi."],
      ["a hot potato", "kimsenin dokunmak istemediği tartışmalı konu", "🥔", "Pension reform has become a hot potato for every government.", "Emeklilik reformu her hükümet için kimsenin dokunmak istemediği bir konu hâline geldi."],
      ["bite the hand that feeds you", "nimet verene nankörlük etmek", "🍽️", "Criticising your biggest client in public is like trying to bite the hand that feeds you.", "En büyük müşterini herkesin önünde eleştirmek, ekmek yediğin kaba pislemek gibidir."],
      ["burn the candle at both ends", "kendini aşırı yıpratmak", "🕯️", "If you burn the candle at both ends, you'll end up getting sick.", "Kendini bu kadar yıpratırsan sonunda hastalanırsın."],
      ["cry wolf", "yalandan alarm vermek, çoban yalanı söylemek", "🐺", "If you cry wolf too often, nobody will believe you when it's serious.", "Çok sık yalandan alarm verirsen iş ciddiye bindiğinde kimse sana inanmaz."],
      ["get up on the wrong side of the bed", "ters tarafından kalkmak", "🛌", "Did you get up on the wrong side of the bed? You've been grumpy all day.", "Ters tarafından mı kalktın? Bütün gün huysuzsun."],
      ["give the green light", "yeşil ışık yakmak, onay vermek", "🟢", "The board will probably give the green light to the project next week.", "Yönetim kurulu muhtemelen gelecek hafta projeye onay verecek."],
      ["go cold turkey", "bir alışkanlığı birden bırakmak", "🦃", "He decided to go cold turkey and quit smoking overnight.", "Sigarayı bir gecede birden bırakmaya karar verdi."],
      ["have your hands full", "başı kalabalık olmak, çok meşgul olmak", "🙌", "I'd love to help, but I have my hands full with the new baby.", "Yardım etmeyi çok isterdim ama yeni bebekle başım kalabalık."],
      ["keep your cards close to your chest", "niyetini belli etmemek", "🃏", "The negotiator likes to keep his cards close to his chest until the end.", "Müzakereci sonuna kadar niyetini belli etmemeyi sever."],
      ["let your hair down", "kendini salıvermek, rahatlamak", "💃", "After the exams, the students finally let their hair down at a party.", "Sınavlardan sonra öğrenciler nihayet bir partide kendilerini salıverdi."],
      ["make a killing", "köşeyi dönmek, büyük para kazanmak", "💸", "Some investors hope to make a killing when the share price rises.", "Bazı yatırımcılar hisse fiyatı yükselince köşeyi dönmeyi umuyor."],
      ["miss the mark", "hedefi tutturamamak, beklentiyi karşılamamak", "🎯", "The advert was expensive, but it completely missed the mark with young people.", "Reklam pahalıydı ama gençlerde tamamen hedefi ıskaladı."],
      ["on the same wavelength", "aynı frekansta olmak, kafa dengi olmak", "📶", "My new colleague and I are on the same wavelength about almost everything.", "Yeni meslektaşımla neredeyse her konuda aynı frekanstayız."],
      ["out of your depth", "boyunu aşan bir işte olmak", "🏊", "In my first week as a manager, I felt completely out of my depth.", "Müdür olarak ilk haftamda boyumu aşan bir işte olduğumu hissettim."],
      ["paint the town red", "kurtlarını dökmek, sabaha kadar eğlenmek", "🎨", "After the promotion, we went out to paint the town red.", "Terfiden sonra sabaha kadar eğlenmeye çıktık."],
      ["read the room", "ortamı okumak, havayı sezmek", "👥", "He told a joke at the funeral, he clearly can't read the room.", "Cenazede şaka yaptı, belli ki ortamı okuyamıyor."],
      ["scratch the surface", "konunun sadece yüzeyine değinmek", "🪶", "This short course will only scratch the surface of the subject.", "Bu kısa kurs konunun sadece yüzeyine değinecek."],
      ["spread yourself too thin", "kendini çok fazla işe bölmek", "🧈", "Don't spread yourself too thin by joining every project.", "Her projeye katılıp kendini çok fazla işe bölme."],
      ["steal someone's thunder", "birinin parlayacağı anı elinden almak", "⚡", "She announced her engagement at my party and managed to steal my thunder.", "Benim partimde nişanını ilan etti ve parlayacağım anı elimden aldı."],
      ["take the bull by the horns", "zorluğun üstüne cesurca gitmek", "🐂", "Instead of waiting, she decided to take the bull by the horns and call the CEO herself.", "Beklemek yerine zorluğun üstüne gidip CEO'yu kendisi aramaya karar verdi."],
      ["a taste of your own medicine", "kendi silahıyla vurulmak, aynı şekilde karşılık görmek", "💊", "He always interrupts others, so now he's getting a taste of his own medicine.", "Hep başkalarının sözünü keser, şimdi de aynı şekilde karşılık görüyor."],
      ["bury the hatchet", "küslüğü bitirmek, barışmak", "🪓", "After years of silence, the two brothers finally decided to bury the hatchet.", "Yıllarca konuşmadıktan sonra iki kardeş sonunda barışmaya karar verdi."],
      ["down the drain", "boşa gitmek, heba olmak", "🚰", "All our hard work went down the drain when the project was cancelled.", "Proje iptal edilince bütün emeğimiz boşa gitti."],
      ["keep a low profile", "göze batmamak, sessiz kalmak", "🤫", "After the argument, he decided to keep a low profile at the office.", "Tartışmadan sonra ofiste göze batmamaya karar verdi."],
      ["the writing is on the wall", "sonun geldiği belli olmak", "🧱", "Sales have fallen for two years, the writing is on the wall for the shop.", "Satışlar iki yıldır düşüyor, dükkânın sonunun geldiği belli."],
      ["sit tight", "yerinde kalıp beklemek, sabretmek", "🪑", "Just sit tight, the technician will be here in ten minutes.", "Sen yerinde bekle, teknisyen on dakikaya burada olur."],
      ["a long shot", "zayıf ihtimal", "🏹", "It's a long shot, but maybe the shop still has one in stock.", "Zayıf bir ihtimal ama belki mağazada hâlâ bir tane vardır."],
      ["get your act together", "kendine çeki düzen vermek", "🧹", "If you want to pass, you need to get your act together now.", "Geçmek istiyorsan hemen kendine çeki düzen vermen gerek."]
    ] },
  { id: "lib8c", title: "Akademik Kelimeler ve Bağlaçlar", icon: "🎓", cefr: "C1", desc: "Makale, rapor ve tezlerde sık geçen genel akademik kelimeler ile bağlaçlar.",
    words: [
      ["nonetheless", "yine de, buna rağmen", "↪️", "The sample was small, nonetheless the results were quite convincing.", "Örneklem küçüktü, yine de sonuçlar oldukça ikna ediciydi."],
      ["whereby", "ki bu sayede, -diği", "🔗", "The study proposes a system whereby patients can book tests online.", "Çalışma, hastaların testleri çevrim içi ayarlayabileceği bir sistem öneriyor."],
      ["likewise", "aynı şekilde", "🟰", "Prices rose sharply in the cities, and likewise in rural areas.", "Fiyatlar şehirlerde keskin biçimde arttı, kırsal bölgelerde de aynı şekilde."],
      ["accordingly", "buna göre, bu doğrultuda", "🧭", "The guidelines changed last year, and we updated our methods accordingly.", "Yönergeler geçen yıl değişti ve yöntemlerimizi buna göre güncelledik."],
      ["subsequently", "daha sonra, ardından", "⏭️", "The drug was tested on mice and subsequently approved for human trials.", "İlaç farelerde test edildi ve ardından insan deneyleri için onaylandı."],
      ["by contrast", "buna karşılık", "⚖️", "Northern regions grew quickly, by contrast the south remained stable.", "Kuzey bölgeleri hızla büyüdü, buna karşılık güney sabit kaldı."],
      ["on the whole", "genel olarak, bütününde", "🌐", "On the whole, participants found the new interface easier to use.", "Genel olarak katılımcılar yeni arayüzü daha kolay kullanılır buldu."],
      ["as such", "bu nedenle, bu haliyle", "📌", "The data is incomplete and, as such, should be treated with caution.", "Veriler eksik ve bu nedenle dikkatle ele alınmalı."],
      ["that is to say", "yani, başka bir deyişle", "💬", "The effect was temporary, that is to say it disappeared within a week.", "Etki geçiciydi, yani bir hafta içinde ortadan kalktı."],
      ["namely", "yani, şöyle ki, isim vermek gerekirse", "🏷️", "Two factors were studied, namely age and income.", "İki etken incelendi, yani yaş ve gelir."],
      ["in particular", "özellikle", "🔦", "The report focuses on young workers, in particular those under twenty five.", "Rapor genç çalışanlara, özellikle yirmi beş yaşın altındakilere odaklanıyor."],
      ["with respect to", "-e ilişkin, bakımından", "📐", "The two groups differed significantly with respect to sleep quality.", "İki grup uyku kalitesi bakımından önemli ölçüde farklıydı."],
      ["in terms of", "bakımından, açısından", "📊", "In terms of cost, the second option is clearly more efficient.", "Maliyet açısından ikinci seçenek açıkça daha verimli."],
      ["owing to", "-den dolayı, yüzünden", "🌧️", "The survey was delayed owing to a lack of funding.", "Anket fon eksikliğinden dolayı ertelendi."],
      ["given that", "göz önüne alındığında, -diği düşünülürse", "🤲", "Given that the sample was small, the findings should be treated carefully.", "Örneklemin küçük olduğu düşünülürse bulgulara dikkatle yaklaşılmalı."],
      ["so as to", "-mek amacıyla, -mek için", "🎯", "Names were removed so as to protect the privacy of participants.", "Katılımcıların gizliliğini korumak amacıyla isimler çıkarıldı."],
      ["similarly", "benzer şekilde", "🪞", "Similarly, the second experiment showed a clear rise in attention.", "Benzer şekilde ikinci deney de dikkatte belirgin bir artış gösterdi."],
      ["alternatively", "alternatif olarak, ya da", "🔀", "Alternatively, the data could be collected through short interviews.", "Alternatif olarak veriler kısa görüşmelerle toplanabilir."],
      ["admittedly", "kabul etmek gerekir ki", "🙋", "Admittedly, the study has some limitations that future research should address.", "Kabul etmek gerekir ki çalışmanın gelecekteki araştırmaların ele alması gereken bazı sınırlılıkları var."],
      ["in summary", "özetle", "📝", "In summary, the evidence suggests that regular exercise improves memory.", "Özetle kanıtlar düzenli egzersizin hafızayı geliştirdiğini gösteriyor."],
      ["regardless of", "-e bakılmaksızın", "🌈", "All applicants are treated equally, regardless of their background.", "Tüm başvuru sahiplerine geçmişlerine bakılmaksızın eşit davranılır."],
      ["on the basis of", "-e dayanarak, temelinde", "🧱", "Students were selected on the basis of their exam results.", "Öğrenciler sınav sonuçlarına dayanarak seçildi."],
      ["as opposed to", "-in aksine, -e karşın", "↔️", "The focus is on long term effects, as opposed to short term gains.", "Odak, kısa vadeli kazançların aksine uzun vadeli etkiler üzerinde."],
      ["in accordance with", "-e uygun olarak, uyarınca", "📜", "All data was stored in accordance with university regulations.", "Tüm veriler üniversite yönetmeliklerine uygun olarak saklandı."],
      ["thereafter", "ondan sonra, bundan böyle", "🔜", "Participants were tested once in March and monthly thereafter.", "Katılımcılar mart ayında bir kez ve ondan sonra her ay test edildi."],
      ["predominantly", "ağırlıklı olarak, büyük ölçüde", "🥇", "The town's population is predominantly made up of young families.", "Kasabanın nüfusu ağırlıklı olarak genç ailelerden oluşuyor."],
      ["primarily", "esas olarak, öncelikle", "1️⃣", "This chapter is primarily concerned with economic factors.", "Bu bölüm esas olarak ekonomik etkenlerle ilgileniyor."],
      ["essentially", "özünde, temelde", "💎", "The two theories are essentially saying the same thing in different words.", "İki kuram özünde aynı şeyi farklı sözcüklerle söylüyor."],
      ["ultimately", "nihayetinde, en sonunda", "🏁", "Ultimately, the success of any policy depends on public support.", "Nihayetinde herhangi bir politikanın başarısı kamuoyu desteğine bağlıdır."],
      ["respectively", "sırasıyla", "🔢", "The two groups scored sixty and seventy five percent respectively.", "İki grup sırasıyla yüzde altmış ve yüzde yetmiş beş puan aldı."],
      ["approximately", "yaklaşık olarak", "≈", "Approximately one third of respondents said they rarely read the news.", "Katılımcıların yaklaşık üçte biri haberleri nadiren okuduğunu söyledi."],
      ["implicitly", "örtük olarak, dolaylı biçimde", "🌫️", "The article implicitly suggests that the policy has failed.", "Makale, politikanın başarısız olduğunu dolaylı biçimde ima ediyor."],
      ["inherently", "doğası gereği, özünde", "🧬", "No method is inherently better, each depends on the research question.", "Hiçbir yöntem doğası gereği daha iyi değildir, her biri araştırma sorusuna bağlıdır."],
      ["largely", "büyük ölçüde", "🐘", "The project's success was largely due to strong local support.", "Projenin başarısı büyük ölçüde güçlü yerel destekten kaynaklandı."],
      ["relatively", "görece, nispeten", "📏", "The procedure is relatively simple and can be done in one day.", "İşlem nispeten basittir ve bir günde yapılabilir."],
      ["solely", "yalnızca, sadece", "☝️", "The decision should not be based solely on financial considerations.", "Karar yalnızca mali kaygılara dayandırılmamalı."],
      ["merely", "sadece, salt", "🪶", "These figures are merely estimates and may change after further analysis.", "Bu rakamlar sadece tahmindir ve daha fazla analizden sonra değişebilir."],
      ["virtually", "neredeyse, hemen hemen", "💯", "Virtually all participants completed the survey within ten minutes.", "Katılımcıların neredeyse tamamı anketi on dakika içinde tamamladı."],
      ["specifically", "özellikle, açıkça", "🎯", "The program was designed specifically for first year students.", "Program özellikle birinci sınıf öğrencileri için tasarlandı."],
      ["typically", "genellikle, tipik olarak", "📋", "Such studies typically last between six months and two years.", "Bu tür çalışmalar genellikle altı ay ile iki yıl arasında sürer."],
      ["considerably", "önemli ölçüde, epeyce", "📈", "Housing costs have risen considerably over the last decade.", "Konut maliyetleri son on yılda önemli ölçüde arttı."],
      ["significantly", "anlamlı ölçüde, kayda değer biçimde", "📉", "Stress levels decreased significantly after the eight week program.", "Stres düzeyleri sekiz haftalık programdan sonra kayda değer biçimde azaldı."],
      ["discrepancy", "tutarsızlık, fark", "❗", "There is a clear discrepancy between the two sets of data.", "İki veri seti arasında açık bir tutarsızlık var."],
      ["inference", "çıkarım", "🧠", "The inference drawn from these results may not apply to other countries.", "Bu sonuçlardan çıkarılan çıkarım başka ülkelere uymayabilir."],
      ["rationale", "gerekçe, mantık", "💡", "The authors explain the rationale behind their choice of method.", "Yazarlar yöntem seçimlerinin ardındaki gerekçeyi açıklıyor."],
      ["scope", "kapsam", "🔭", "A detailed cost analysis is beyond the scope of this paper.", "Ayrıntılı bir maliyet analizi bu makalenin kapsamı dışındadır."],
      ["synthesis", "sentez, bir araya getirme", "⚗️", "The review offers a useful synthesis of recent research on sleep.", "İnceleme, uyku üzerine son araştırmaların yararlı bir sentezini sunuyor."],
      ["validity", "geçerlilik", "✅", "Some experts have questioned the validity of the questionnaire.", "Bazı uzmanlar anketin geçerliliğini sorguladı."],
      ["constraint", "kısıt, sınırlama", "⛓️", "Time constraint was the main reason the study was kept small.", "Zaman kısıtı çalışmanın küçük tutulmasının ana nedeniydi."],
      ["dimension", "boyut", "🧊", "Culture adds an important dimension to the debate on education.", "Kültür, eğitim tartışmasına önemli bir boyut katıyor."],
      ["entity", "varlık, kurum, tüzel kişi", "🏢", "Each branch operates as a separate legal entity.", "Her şube ayrı bir tüzel kişi olarak faaliyet gösteriyor."],
      ["parameter", "parametre, sınır, ölçüt", "🎛️", "The researchers set clear parameters for what counted as success.", "Araştırmacılar neyin başarı sayılacağına dair net ölçütler belirledi."],
      ["proportion", "oran, pay", "🥧", "A large proportion of graduates find work within six months.", "Mezunların büyük bir kısmı altı ay içinde iş buluyor."],
      ["anomaly", "anormallik, sapma", "🔺", "One anomaly in the results was the unusually high score in March.", "Sonuçlardaki bir sapma mart ayındaki alışılmadık derecede yüksek puandı."],
      ["caveat", "uyarı, çekince", "⚠️", "One important caveat is that the data comes from a single city.", "Önemli bir çekince, verilerin tek bir şehirden gelmesidir."],
      ["feasible", "uygulanabilir, yapılabilir", "🛠️", "It is not feasible to interview every employee in the company.", "Şirketteki her çalışanla görüşmek uygulanabilir değil."],
      ["comprehensive", "kapsamlı", "📚", "The book provides a comprehensive overview of modern economics.", "Kitap modern ekonomiye kapsamlı bir genel bakış sunuyor."],
      ["crucial", "çok önemli, kritik", "🔑", "Early diagnosis is crucial for successful treatment.", "Başarılı tedavi için erken teşhis kritik önemdedir."],
      ["distinct", "belirgin, ayrı", "🔷", "The survey revealed three distinct groups of customers.", "Anket üç ayrı müşteri grubunu ortaya çıkardı."],
      ["explicit", "açık, net", "📣", "The contract makes no explicit reference to remote work.", "Sözleşme uzaktan çalışmaya açıkça değinmiyor."],
      ["marginal", "marjinal, çok küçük", "🤏", "The new method led to only a marginal improvement in accuracy.", "Yeni yöntem doğrulukta yalnızca çok küçük bir iyileşme sağladı."],
      ["preliminary", "ön, hazırlık niteliğinde", "🧪", "Preliminary results suggest the treatment may be effective.", "Ön sonuçlar tedavinin etkili olabileceğini gösteriyor."],
      ["robust", "sağlam, güvenilir", "🏗️", "We need more robust evidence before changing the policy.", "Politikayı değiştirmeden önce daha sağlam kanıtlara ihtiyacımız var."],
      ["subsequent", "sonraki, ardından gelen", "➡️", "These findings were confirmed in subsequent studies.", "Bu bulgular sonraki çalışmalarda doğrulandı."],
      ["theoretical", "kuramsal, teorik", "📖", "The first chapter presents the theoretical background of the study.", "Birinci bölüm çalışmanın kuramsal arka planını sunuyor."],
      ["arbitrary", "keyfi, gelişigüzel", "🎲", "The cut off age of forty seems rather arbitrary.", "Kırk yaş sınırı oldukça keyfi görünüyor."],
      ["analogous", "benzer, örnek alınabilir", "🪞", "The situation is analogous to what happened in the music industry.", "Durum müzik sektöründe yaşananlara benziyor."],
      ["contradictory", "çelişkili", "🔄", "The witnesses gave contradictory accounts of the event.", "Tanıklar olayla ilgili çelişkili anlatımlar sundu."],
      ["compatible", "uyumlu, bağdaşır", "🧩", "These findings are compatible with earlier research on memory.", "Bu bulgular hafıza üzerine daha önceki araştırmalarla uyumlu."],
      ["prevalent", "yaygın", "🌍", "Back pain is particularly prevalent among office workers.", "Bel ağrısı özellikle ofis çalışanları arasında yaygındır."],
      ["salient", "en dikkat çekici, göze çarpan", "✨", "The most salient feature of the data is the sudden rise in 2020.", "Verilerin en dikkat çekici özelliği 2020'deki ani artış."],
      ["qualitative", "nitel", "🗨️", "We used qualitative interviews to understand how people felt.", "İnsanların nasıl hissettiğini anlamak için nitel görüşmeler kullandık."],
      ["quantitative", "nicel", "🔢", "Quantitative data was collected through an online questionnaire.", "Nicel veriler çevrim içi bir anketle toplandı."],
      ["aforementioned", "yukarıda adı geçen, söz konusu", "👆", "The aforementioned study was carried out in three countries.", "Yukarıda adı geçen çalışma üç ülkede yürütüldü."],
      ["negligible", "önemsiz, ihmal edilebilir", "🫧", "The difference between the two groups was negligible.", "İki grup arasındaki fark ihmal edilebilir düzeydeydi."],
      ["tentative", "geçici, kesinleşmemiş, temkinli", "✏️", "These conclusions are tentative and need further testing.", "Bu sonuçlar kesinleşmemiştir ve daha fazla test gerektirir."],
      ["conducive", "elverişli, -e yardımcı", "🌱", "A quiet room is more conducive to deep concentration.", "Sessiz bir oda derin konsantrasyona daha elverişlidir."],
      ["pertinent", "ilgili, konuyla bağlantılı", "📎", "Please include only information that is pertinent to the question.", "Lütfen yalnızca soruyla ilgili bilgileri ekleyin."],
      ["allocate", "ayırmak, tahsis etmek", "💰", "The university will allocate more funds to mental health services.", "Üniversite ruh sağlığı hizmetlerine daha fazla fon ayıracak."],
      ["ascertain", "kesin olarak belirlemek", "🔍", "It was difficult to ascertain the exact cause of the error.", "Hatanın kesin nedenini belirlemek zordu."],
      ["attribute", "-e bağlamak, atfetmek", "🏷️", "Researchers attribute the decline to changes in diet.", "Araştırmacılar düşüşü beslenmedeki değişikliklere bağlıyor."],
      ["constitute", "oluşturmak, teşkil etmek", "🧱", "Women constitute nearly sixty percent of the workforce in this sector.", "Kadınlar bu sektördeki iş gücünün yaklaşık yüzde altmışını oluşturuyor."],
      ["corroborate", "doğrulamak, teyit etmek", "🤝", "Other studies corroborate the link between sleep and mood.", "Başka çalışmalar uyku ile ruh hâli arasındaki bağlantıyı doğruluyor."],
      ["derive", "elde etmek, türetmek", "🌿", "Most of the data derive from official government sources.", "Verilerin çoğu resmî devlet kaynaklarından elde ediliyor."],
      ["elicit", "ortaya çıkarmak, almak", "🎣", "The questions were designed to elicit honest answers from students.", "Sorular öğrencilerden dürüst cevaplar almak için tasarlandı."],
      ["encompass", "kapsamak", "🫧", "The term wellbeing can encompass both physical and mental health.", "İyi oluş terimi hem fiziksel hem ruhsal sağlığı kapsayabilir."],
      ["facilitate", "kolaylaştırmak", "🛤️", "Online tools can facilitate communication between distant teams.", "Çevrim içi araçlar uzak ekipler arasındaki iletişimi kolaylaştırabilir."],
      ["formulate", "formüle etmek, oluşturmak", "🧮", "It took us weeks to formulate a clear research question.", "Net bir araştırma sorusu oluşturmamız haftalar sürdü."],
      ["illustrate", "örneklerle göstermek", "🖍️", "The graph below will illustrate the rise in online shopping.", "Aşağıdaki grafik çevrim içi alışverişteki artışı gösterecek."],
      ["infer", "sonuç çıkarmak", "🕵️", "From these results, we can infer that price matters more than design.", "Bu sonuçlardan fiyatın tasarımdan daha önemli olduğu sonucunu çıkarabiliriz."],
      ["manifest", "kendini göstermek, ortaya koymak", "🌡️", "Stress can manifest itself in many physical symptoms.", "Stres pek çok fiziksel belirtiyle kendini gösterebilir."],
      ["mitigate", "hafifletmek, azaltmak", "🛡️", "Planting trees can help mitigate the effects of extreme heat.", "Ağaç dikmek aşırı sıcağın etkilerini hafifletmeye yardımcı olabilir."],
      ["refute", "çürütmek", "❌", "The new evidence seems to refute the original theory.", "Yeni kanıtlar ilk kuramı çürütüyor gibi görünüyor."],
      ["scrutinise", "titizlikle incelemek", "🔬", "Reviewers will scrutinise every part of the proposal.", "Hakemler önerinin her bölümünü titizlikle inceleyecek."],
      ["underpin", "temelini oluşturmak, desteklemek", "🏛️", "Strong data should underpin every policy decision.", "Her politika kararının temelinde sağlam veriler olmalı."],
      ["validate", "doğrulamak, geçerli kılmak", "✔️", "The team used a second survey to validate their first findings.", "Ekip ilk bulgularını doğrulamak için ikinci bir anket kullandı."],
      ["warrant", "gerektirmek, haklı çıkarmak", "📜", "These early results warrant further investigation.", "Bu ilk sonuçlar daha ileri bir araştırmayı gerektiriyor."],
      ["yield", "sonuç vermek, sağlamak", "🌾", "The new approach did not yield any significant results.", "Yeni yaklaşım anlamlı bir sonuç vermedi."],
      ["assess", "değerlendirmek", "📝", "Teachers use short quizzes to assess student progress.", "Öğretmenler öğrencinin ilerlemesini değerlendirmek için kısa sınavlar kullanır."],
      ["advocate", "savunmak, desteklemek", "📢", "Many experts advocate a shorter working week.", "Pek çok uzman daha kısa bir çalışma haftasını savunuyor."],
      ["assert", "ileri sürmek, iddia etmek", "🗣️", "The authors assert that social media harms concentration.", "Yazarlar sosyal medyanın konsantrasyona zarar verdiğini ileri sürüyor."],
      ["discern", "ayırt etmek, fark etmek", "👁️", "It is hard to discern any clear pattern in the data.", "Verilerde net bir örüntü ayırt etmek zor."],
      ["interpret", "yorumlamak", "🧐", "We must interpret these figures with great care.", "Bu rakamları büyük bir dikkatle yorumlamalıyız."],
      ["quantify", "sayısal olarak ölçmek", "📏", "It is difficult to quantify the value of a happy workplace.", "Mutlu bir iş yerinin değerini sayısal olarak ölçmek zor."],
      ["replicate", "tekrarlamak, aynısını elde etmek", "🔁", "Other scientists failed to replicate the results of the experiment.", "Başka bilim insanları deneyin sonuçlarını tekrarlayamadı."],
      ["reiterate", "yinelemek, tekrar vurgulamak", "🔂", "I would like to reiterate the main point of this essay.", "Bu denemenin ana fikrini yinelemek istiyorum."],
      ["outline", "ana hatlarıyla anlatmak", "🗒️", "In this section, I will outline the structure of the thesis.", "Bu bölümde tezin yapısını ana hatlarıyla anlatacağım."],
      ["differentiate", "ayırt etmek, ayırmak", "🔀", "Students must learn to differentiate between facts and opinions.", "Öğrenciler gerçeklerle görüşleri ayırt etmeyi öğrenmeli."],
      ["evaluate", "değerlendirmek", "⭐", "The aim of this study is to evaluate the new teaching method.", "Bu çalışmanın amacı yeni öğretim yöntemini değerlendirmektir."],
      ["categorise", "sınıflandırmak", "🗂️", "We decided to categorise the responses into four main groups.", "Cevapları dört ana gruba ayırmaya karar verdik."]
    ] }
);
