(window.PODCASTS = window.PODCASTS || []).push(
  { id: "p1", title: "Yeni işte ilk gün", cefr: "A2", icon: "💼", desc: "Maya ve Tom, yeni bir işe başlarken yaşanan heyecanı ve küçük hataları konuşuyor.",
    lines: [
      ["Maya", "Hi everyone, and welcome to ASİ Dil Radio! I'm Maya.", "Herkese merhaba, ASİ Dil Radyo'ya hoş geldiniz! Ben Maya."],
      ["Tom", "And I'm Tom. Today we're talking about the first day at a new job.", "Ben de Tom. Bugün yeni bir işteki ilk günü konuşuyoruz."],
      ["Maya", "Oh, I love this topic. Tom, do you remember your first day at work?", "Ah, bu konuya bayılıyorum. Tom, işteki ilk gününü hatırlıyor musun?"],
      ["Tom", "Sadly, yes. I wore a suit and everyone else wore jeans.", "Ne yazık ki evet. Ben takım elbise giydim, herkes kot giymişti."],
      ["Maya", "No way! That's so funny. Did you feel silly?", "Olamaz! Çok komik. Kendini aptal gibi hissettin mi?"],
      ["Tom", "A little. But my new boss said I looked very smart. I think she was being kind.", "Biraz. Ama yeni patronum çok şık göründüğümü söyledi. Sanırım nazik davranıyordu."],
      ["Maya", "My first day was in a small café in Toronto. I was so nervous.", "Benim ilk günüm Toronto'da küçük bir kafedeydi. Çok gergindim."],
      ["Tom", "What happened?", "Ne oldu?"],
      ["Maya", "Well, I forgot everyone's name in about five minutes.", "Şey, beş dakika içinde herkesin adını unuttum."],
      ["Tom", "That's normal, I think. There are so many new people on the first day.", "Bence bu normal. İlk gün o kadar çok yeni insan var ki."],
      ["Maya", "Right. So now I have a tip. Write the names in a small notebook.", "Doğru. O yüzden artık bir tavsiyem var. İsimleri küçük bir deftere yazın."],
      ["Tom", "Good idea. My tip is simple. Ask questions. Nobody expects you to know everything.", "İyi fikir. Benim tavsiyem basit. Soru sorun. Kimse her şeyi bilmenizi beklemiyor."],
      ["Maya", "Yes! And smile. A smile is free, you know.", "Evet! Ve gülümseyin. Gülümsemek bedava, biliyorsunuz."],
      ["Tom", "Unless you're British. Then you just nod politely.", "İngiliz değilseniz tabii. O zaman sadece kibarca başınızı sallarsınız."],
      ["Maya", "Ha! Oh, and bring your own lunch. On my first day I didn't have any money.", "Ha! Bir de kendi öğle yemeğinizi getirin. İlk günümde hiç param yoktu."],
      ["Tom", "So what did you eat?", "Peki ne yedin?"],
      ["Maya", "A free cookie from the café. Only one cookie!", "Kafeden bedava bir kurabiye. Sadece bir kurabiye!"],
      ["Tom", "A great start to your career. Thanks for listening, everyone. See you next time!", "Kariyerine harika bir başlangıç. Dinlediğiniz için teşekkürler. Bir dahaki sefere görüşürüz!"]
    ],
    questions: [
      { after: 5, q: "Tom ilk iş gününde neden kendini biraz garip hissetti?", options: ["Geç kaldığı için", "Herkes kot giyerken o takım elbise giydiği için", "Patronunun adını unuttuğu için"], answer: 1 },
      { after: 10, q: "Maya'nın isimleri hatırlamak için tavsiyesi ne?", options: ["İsimleri küçük bir deftere yazmak", "Herkese iki kez sormak", "İsimleri telefona kaydetmek"], answer: 0 },
      { after: 16, q: "Maya ilk gününde öğle yemeğinde ne yedi?", options: ["Bir sandviç", "Hiçbir şey", "Sadece bir kurabiye"], answer: 2 }
    ] },

  { id: "p2", title: "Yurt dışında market alışverişi", cefr: "A2", icon: "🛒", desc: "Konuk Deniz, Londra'da markette yaşadığı küçük şaşkınlıkları anlatıyor.",
    lines: [
      ["Maya", "Welcome back to ASİ Dil Radio! Today we have a guest. Hi, Deniz!", "ASİ Dil Radyo'ya tekrar hoş geldiniz! Bugün bir konuğumuz var. Merhaba Deniz!"],
      ["Deniz", "Hi Maya, hi Tom. Thanks for having me.", "Merhaba Maya, merhaba Tom. Beni davet ettiğiniz için teşekkürler."],
      ["Tom", "Deniz moved from Izmir to London last year. Deniz, what was hard at first?", "Deniz geçen yıl İzmir'den Londra'ya taşındı. Deniz, başta ne zordu?"],
      ["Deniz", "Honestly? The supermarket. I couldn't find anything.", "Dürüst olmak gerekirse mi? Market. Hiçbir şey bulamıyordum."],
      ["Maya", "Really? What were you looking for?", "Gerçekten mi? Ne arıyordun?"],
      ["Deniz", "White cheese for breakfast. I looked everywhere. In the end I bought feta from Greece.", "Kahvaltı için beyaz peynir. Her yere baktım. Sonunda Yunanistan'dan feta aldım."],
      ["Tom", "That's a very British solution. Close enough.", "Bu çok İngiliz bir çözüm. Yeterince yakın."],
      ["Deniz", "And the bread! In Turkey I buy fresh bread every morning. Here it's in plastic bags.", "Bir de ekmek! Türkiye'de her sabah taze ekmek alırım. Burada plastik poşetlerde."],
      ["Maya", "In Canada it's the same. But there are some good bakeries, you know.", "Kanada'da da aynısı. Ama bazı iyi fırınlar da var, biliyorsun."],
      ["Deniz", "Yes, I found one near my flat. It's a bit expensive but I go there on Sundays.", "Evet, evimin yakınında bir tane buldum. Biraz pahalı ama pazar günleri oraya gidiyorum."],
      ["Tom", "What about the checkout? Was that easy?", "Peki ya kasa? Kolay mıydı?"],
      ["Deniz", "No! There was a machine and it kept saying unexpected item in the bagging area.", "Hayır! Bir makine vardı ve sürekli torbalama alanında beklenmeyen ürün deyip duruyordu."],
      ["Maya", "Oh, I hate that machine. Everybody hates that machine.", "Ah, o makineden nefret ediyorum. Herkes o makineden nefret ediyor."],
      ["Tom", "It's our national enemy. We talk to it like an old friend.", "O bizim ulusal düşmanımız. Onunla eski bir arkadaş gibi konuşuruz."],
      ["Maya", "So, Deniz, what's your advice for new people in a new country?", "Peki Deniz, yeni bir ülkedeki yeni insanlara tavsiyen ne?"],
      ["Deniz", "Be patient and try new food. Now I really like British crumpets.", "Sabırlı olun ve yeni yemekler deneyin. Artık İngiliz crumpet'larını gerçekten seviyorum."],
      ["Tom", "See? London changes everyone. Thanks, Deniz!", "Gördünüz mü? Londra herkesi değiştirir. Teşekkürler Deniz!"]
    ],
    questions: [
      { after: 5, q: "Deniz kahvaltı için ne aradı?", options: ["Zeytin", "Beyaz peynir", "Simit"], answer: 1 },
      { after: 9, q: "Deniz pazar günleri nereye gidiyor?", options: ["Evinin yakınındaki bir fırına", "Büyük bir markete", "Bir Türk restoranına"], answer: 0 },
      { after: 13, q: "Kasadaki makine Deniz için neden sorun oldu?", options: ["Kartını kabul etmedi", "Çok yavaştı", "Sürekli beklenmeyen ürün uyarısı verdi"], answer: 2 },
      { after: 15, q: "Deniz'in tavsiyesi ne?", options: ["Sabırlı olmak ve yeni yemekler denemek", "Türkiye'den yiyecek getirmek", "Sadece büyük marketlere gitmek"], answer: 0 }
    ] },

  { id: "p3", title: "Telefon bağımlılığı", cefr: "B1", icon: "📱", desc: "Maya bir hafta boyunca telefon kullanımını azaltmayı deniyor, Tom ise şüpheli.",
    lines: [
      ["Tom", "Hello and welcome to ASİ Dil Radio. Maya, you look tired. Is everything okay?", "Merhaba, ASİ Dil Radyo'ya hoş geldiniz. Maya, yorgun görünüyorsun. Her şey yolunda mı?"],
      ["Maya", "I'm fine! Well, kind of. I tried a little experiment last week. No phone after eight p.m.", "İyiyim! Yani, sayılır. Geçen hafta küçük bir deney yaptım. Akşam sekizden sonra telefon yok."],
      ["Tom", "Wow. How did that go?", "Vay. Nasıl geçti?"],
      ["Maya", "The first night was awful. I kept reaching for my pocket, you know, like a reflex.", "İlk gece berbattı. Sürekli cebime uzanıp duruyordum, bilirsin, refleks gibi."],
      ["Tom", "I do that too. Sometimes I pick up my phone and then forget why.", "Ben de yapıyorum. Bazen telefonu elime alıyorum, sonra neden aldığımı unutuyorum."],
      ["Maya", "Exactly! So I put it in a drawer in the kitchen. Out of sight, out of mind.", "Aynen! Ben de onu mutfakta bir çekmeceye koydum. Gözden ırak, gönülden ırak."],
      ["Tom", "And what did you do instead? Stare at the wall?", "Peki onun yerine ne yaptın? Duvara mı baktın?"],
      ["Maya", "Ha ha. No, I actually read a whole book. And I called my grandma. On the landline!", "Ha ha. Hayır, aslında koca bir kitap okudum. Bir de büyükannemi aradım. Sabit hattan!"],
      ["Tom", "A landline? I thought those only existed in museums.", "Sabit hat mı? Onların sadece müzelerde olduğunu sanıyordum."],
      ["Maya", "My grandma still has one. She was so happy. We talked for an hour.", "Büyükannemde hâlâ var. Çok mutlu oldu. Bir saat konuştuk."],
      ["Tom", "Okay, that's actually lovely. But why do you look tired then?", "Tamam, bu gerçekten çok güzel. Ama o zaman neden yorgun görünüyorsun?"],
      ["Maya", "Because I used my phone as an alarm clock. And it was in the drawer. So I woke up late twice.", "Çünkü telefonumu çalar saat olarak kullanıyordum. Ve o çekmecedeydi. Yani iki kere geç uyandım."],
      ["Tom", "Ah, the classic mistake. You need an old-fashioned alarm clock.", "Ah, klasik hata. Eski usul bir çalar saate ihtiyacın var."],
      ["Maya", "I ordered one yesterday. Anyway, I feel calmer in the evenings now. I sleep better too.", "Dün bir tane sipariş ettim. Neyse, artık akşamları daha sakin hissediyorum. Daha iyi de uyuyorum."],
      ["Tom", "So would you recommend it to our listeners?", "Peki bunu dinleyicilerimize tavsiye eder misin?"],
      ["Maya", "Definitely. Start small. Maybe one hour without your phone before bed.", "Kesinlikle. Küçük başlayın. Belki yatmadan önce telefonsuz bir saat."],
      ["Tom", "I'll give it a go. But if I miss an important message, I'm blaming you.", "Bir deneyeceğim. Ama önemli bir mesajı kaçırırsam seni suçlayacağım."],
      ["Maya", "Deal! Thanks for listening, everybody.", "Anlaştık! Dinlediğiniz için teşekkürler, herkes."]
    ],
    questions: [
      { after: 5, q: "Where did Maya put her phone in the evenings?", options: ["Under her pillow", "In a kitchen drawer", "In her car"], answer: 1 },
      { after: 9, q: "What did Maya do instead of using her phone?", options: ["She watched TV all night", "She went to the gym", "She read a book and called her grandma"], answer: 2 },
      { after: 11, q: "Why did Maya wake up late?", options: ["Her alarm was on the phone in the drawer", "She went to bed very late", "Her grandma called her at night"], answer: 0 },
      { after: 15, q: "What does Maya recommend?", options: ["Throwing your phone away", "Starting with one phone-free hour before bed", "Using a landline every day"], answer: 1 }
    ] },

  { id: "p4", title: "Para biriktirmenin küçük sırları", cefr: "B1", icon: "💰", desc: "Maya ve Tom, maaş gününden önce paranın neden hep bittiğini ve nasıl birikim yapılacağını konuşuyor.",
    lines: [
      ["Maya", "Hey everyone, it's Maya and Tom. Today's topic is money. Specifically, saving it.", "Herkese selam, ben Maya, yanımda Tom. Bugünün konusu para. Daha doğrusu, para biriktirmek."],
      ["Tom", "Which is something I'm terrible at. My money disappears around the twentieth of every month.", "Ki bu konuda berbatım. Param her ayın yirmisi civarında yok oluyor."],
      ["Maya", "Where does it go?", "Nereye gidiyor?"],
      ["Tom", "Mostly coffee, I think. And takeaways. And books I never read.", "Sanırım çoğu kahveye. Bir de paket yemeklere. Bir de hiç okumadığım kitaplara."],
      ["Maya", "Okay, so here's a trick I learned from my dad. Pay yourself first.", "Tamam, babamdan öğrendiğim bir numara var. Önce kendine öde."],
      ["Tom", "Pay myself? I'm not sure I understand.", "Kendime mi ödeyeyim? Anladığımdan emin değilim."],
      ["Maya", "When you get your salary, you move some money into a savings account straight away. Before you spend anything.", "Maaşını aldığında hemen bir miktarı birikim hesabına aktarıyorsun. Hiçbir şey harcamadan önce."],
      ["Tom", "Ah, so I can't spend what I can't see.", "Ah, yani göremediğimi harcayamam."],
      ["Maya", "Exactly. Even ten percent makes a big difference after a year.", "Aynen. Yüzde on bile bir yıl sonra büyük fark yaratır."],
      ["Tom", "Fine. But what about the coffee? I can't give up coffee. I'm British. We run on tea and coffee.", "Peki. Ama kahve ne olacak? Kahveden vazgeçemem. Ben İngilizim. Biz çay ve kahveyle çalışırız."],
      ["Maya", "You don't have to give it up. Just make it at home a few days a week.", "Vazgeçmek zorunda değilsin. Sadece haftada birkaç gün evde yap."],
      ["Tom", "Hmm, that sounds reasonable. What else?", "Hmm, makul görünüyor. Başka?"],
      ["Maya", "Write down everything you spend for one month. Every single thing.", "Bir ay boyunca harcadığın her şeyi yaz. Her bir şeyi."],
      ["Tom", "That sounds a bit scary, to be honest. I might not like what I find.", "Açıkçası bu biraz korkutucu geliyor. Bulduklarımı beğenmeyebilirim."],
      ["Maya", "That's the point! When I did it, I found three apps I was paying for and never using.", "Mesele de bu! Ben yaptığımda, para ödediğim ama hiç kullanmadığım üç uygulama buldum."],
      ["Tom", "Subscriptions. The silent killers of the bank account.", "Abonelikler. Banka hesabının sessiz katilleri."],
      ["Maya", "So, listeners, check your subscriptions this week. You might save more than you think.", "Yani dinleyiciler, bu hafta aboneliklerinizi kontrol edin. Düşündüğünüzden fazla tasarruf edebilirsiniz."],
      ["Tom", "And if you find any money, feel free to send it to me. For coffee.", "Ve eğer biraz para bulursanız, bana göndermekten çekinmeyin. Kahve için."]
    ],
    questions: [
      { after: 3, q: "What does Tom spend most of his money on?", options: ["Rent and bills", "Coffee, takeaways and books", "Travel and clothes"], answer: 1 },
      { after: 8, q: "What does pay yourself first mean in this episode?", options: ["Saving money as soon as you get your salary", "Buying yourself a present every month", "Asking your boss for more money"], answer: 0 },
      { after: 14, q: "What did Maya find when she wrote down her spending?", options: ["She spent too much on coffee", "She had a lot of money in the bank", "She was paying for apps she never used"], answer: 2 }
    ] },

  { id: "p5", title: "Aksanlar ve yanlış anlamalar", cefr: "B1", icon: "🗣️", desc: "Kanadalı Maya ile İngiliz Tom, aynı kelimeleri neden farklı söylediklerini ve başlarına gelen komik karışıklıkları anlatıyor.",
    lines: [
      ["Tom", "Welcome to ASİ Dil Radio. Today we're talking about accents. And Maya says I have a funny one.", "ASİ Dil Radyo'ya hoş geldiniz. Bugün aksanları konuşuyoruz. Ve Maya benim komik bir aksanım olduğunu söylüyor."],
      ["Maya", "I said it was charming! Well, charming and a little bit funny.", "Çekici dedim! Yani, çekici ve biraz komik."],
      ["Tom", "From where I'm standing, you're the one with the accent.", "Benim baktığım yerden, aksanı olan sensin."],
      ["Maya", "Ha! Okay, here's a real example. When I first came to London, I asked for water in a café.", "Ha! Tamam, işte gerçek bir örnek. Londra'ya ilk geldiğimde bir kafede su istedim."],
      ["Tom", "Let me guess. They didn't understand you.", "Tahmin edeyim. Seni anlamadılar."],
      ["Maya", "Not at all! I said wadder, with a soft d sound. The waiter looked completely lost.", "Hiç anlamadılar! Yumuşak bir d sesiyle vadır dedim. Garson tamamen kaybolmuş gibi baktı."],
      ["Tom", "Because we say waw-tuh. Very clearly. With the t. Well, sometimes.", "Çünkü biz vo-tı deriz. Çok net. T ile. Yani, bazen."],
      ["Maya", "And sometimes you don't say the t at all! You say wa-uh.", "Bazen de t'yi hiç söylemiyorsunuz! Va-ı diyorsunuz."],
      ["Tom", "Guilty. That's more of a London thing. My grandmother would be horrified.", "Suçluyum. Bu daha çok Londra'ya özgü. Büyükannem dehşete düşerdi."],
      ["Maya", "But you know what? It's not just the sound. Some words are totally different.", "Ama biliyor musun? Mesele sadece ses değil. Bazı kelimeler tamamen farklı."],
      ["Tom", "Like pants. In Britain, pants are underwear. In Canada, they're trousers.", "Pants gibi. Britanya'da pants iç çamaşırı demek. Kanada'da pantolon."],
      ["Maya", "Oh no. I once told my British colleague that I liked her pants.", "Eyvah. Bir keresinde İngiliz bir iş arkadaşıma pantolonunu beğendiğimi söylemiştim."],
      ["Tom", "And how did she react?", "Peki nasıl tepki verdi?"],
      ["Maya", "She turned red and said thank you very quietly. I only understood a week later!", "Kızardı ve çok sessizce teşekkür ederim dedi. Ben ancak bir hafta sonra anladım!"],
      ["Tom", "That's brilliant. So, listeners, don't worry about your accent too much.", "Harika. Yani dinleyiciler, aksanınız için çok endişelenmeyin."],
      ["Maya", "Right. Everyone has an accent. The important thing is that people understand you.", "Doğru. Herkesin bir aksanı var. Önemli olan insanların sizi anlaması."],
      ["Tom", "And maybe check the meaning of pants before you compliment anyone.", "Ve belki birine iltifat etmeden önce pants kelimesinin anlamını kontrol edin."],
      ["Maya", "Good advice. See you next week!", "İyi tavsiye. Haftaya görüşürüz!"]
    ],
    questions: [
      { after: 5, q: "What did Maya ask for in the London café?", options: ["Coffee", "Water", "Tea"], answer: 1 },
      { after: 8, q: "According to Tom, where is dropping the t sound typical?", options: ["In London", "In Canada", "In his grandmother's town"], answer: 0 },
      { after: 13, q: "Why did Maya's colleague turn red?", options: ["She was angry about her work", "She felt sick", "In British English pants means underwear"], answer: 2 },
      { after: 15, q: "What is the main message about accents?", options: ["You should copy a British accent", "Being understood matters more than your accent", "Canadian accents are easier"], answer: 1 }
    ] },

  { id: "p6", title: "Uzaktan çalışmanın iki yüzü", cefr: "B2", icon: "🏠", desc: "Konuk yazılımcı Selin, evden çalışmanın özgürlüğünü ve yalnızlığını Maya ve Tom'la tartışıyor.",
    lines: [
      ["Maya", "Hi, everyone! Today we're diving into remote work, and we've got a guest who's been doing it for four years. Welcome, Selin!", "Herkese merhaba! Bugün uzaktan çalışmaya dalıyoruz ve dört yıldır bunu yapan bir konuğumuz var. Hoş geldin Selin!"],
      ["Selin", "Thanks, it's great to be here. And I'm wearing proper trousers today, just for you.", "Teşekkürler, burada olmak harika. Bugün sırf sizin için düzgün bir pantolon giydim."],
      ["Tom", "We're honoured. So, Selin, be honest. Is working from home as good as people make it out to be?", "Onur duyduk. Peki Selin, dürüst ol. Evden çalışmak insanların anlattığı kadar iyi mi?"],
      ["Selin", "Well, it depends. The first year, I absolutely loved it. No commute, no noisy open-plan office.", "Şey, duruma bağlı. İlk yıl kesinlikle bayıldım. İşe gidip gelme yok, gürültülü açık ofis yok."],
      ["Maya", "I can imagine. My commute used to eat up almost two hours a day.", "Tahmin edebiliyorum. Benim işe gidip gelişim eskiden günde neredeyse iki saatimi yiyordu."],
      ["Selin", "Exactly. But then, around the second winter, it started to wear me down. I realised I hadn't spoken to anyone face to face for days.", "Aynen. Ama sonra, ikinci kış civarında, beni yıpratmaya başladı. Günlerdir kimseyle yüz yüze konuşmadığımı fark ettim."],
      ["Tom", "That sounds lonely. I mean, I talk to my cat, but he's not much of a conversationalist.", "Kulağa yalnız geliyor. Yani, ben kedimle konuşuyorum ama o pek sohbet ehli değil."],
      ["Selin", "Ha, mine either. The other problem was that work and life blurred together. My laptop was always on the kitchen table, so I never really switched off.", "Ha, benimki de değil. Diğer sorun da iş ile hayatın birbirine karışmasıydı. Dizüstü bilgisayarım hep mutfak masasındaydı, o yüzden asla gerçekten kafamı kapatamıyordum."],
      ["Maya", "So how did you deal with that?", "Peki bununla nasıl başa çıktın?"],
      ["Selin", "A few things. I set strict working hours and I stuck to them. And I started going to a co-working space twice a week.", "Birkaç şeyle. Katı çalışma saatleri belirledim ve onlara sadık kaldım. Bir de haftada iki gün ortak çalışma alanına gitmeye başladım."],
      ["Tom", "Doesn't that defeat the purpose? Paying to sit in an office?", "Bu amacı boşa çıkarmıyor mu? Bir ofiste oturmak için para ödemek?"],
      ["Selin", "You'd think so, but it's different when it's your choice. Plus I've met some fascinating people there, including my current business partner.", "Öyle düşünürsün ama senin seçimin olunca farklı. Üstelik orada çok ilginç insanlarla tanıştım, şu anki iş ortağım da dahil."],
      ["Maya", "Oh, that's a great outcome! What about the end of the day? How do you mark it?", "Ah, bu harika bir sonuç! Peki ya günün sonu? Onu nasıl belirliyorsun?"],
      ["Selin", "I go for a short walk around the block. It's like a fake commute. It tells my brain the workday is over.", "Mahallede kısa bir yürüyüşe çıkıyorum. Sahte bir işe gidip gelme gibi. Beynime iş gününün bittiğini söylüyor."],
      ["Tom", "A fake commute. That's genius. I might steal that.", "Sahte bir işe gidip gelme. Bu dâhice. Bunu çalabilirim."],
      ["Maya", "So, Selin, would you ever go back to the office full-time?", "Peki Selin, bir gün tam zamanlı ofise geri döner misin?"],
      ["Selin", "Probably not. But I've learned that freedom needs a bit of structure, otherwise it turns into chaos.", "Muhtemelen hayır. Ama özgürlüğün biraz düzene ihtiyacı olduğunu öğrendim, yoksa kaosa dönüşüyor."],
      ["Tom", "Wise words. And on that note, I'm off for my fake commute to the fridge.", "Bilgece sözler. Ve bu notla, buzdolabına sahte işe gidiş yolculuğuma çıkıyorum."]
    ],
    questions: [
      { after: 5, q: "When did Selin start to find remote work difficult?", options: ["In her first month", "Around her second winter", "After she changed jobs"], answer: 1 },
      { after: 7, q: "What was one problem Selin had at home?", options: ["Her internet was too slow", "Her neighbours were noisy", "She could never really switch off from work"], answer: 2 },
      { after: 11, q: "What unexpected benefit came from the co-working space?", options: ["She met her current business partner", "It was cheaper than her flat", "She got a free laptop"], answer: 0 },
      { after: 13, q: "What is the purpose of Selin's daily walk?", options: ["To lose weight", "To signal to her brain that work is over", "To meet her neighbours"], answer: 1 }
    ] },

  { id: "p7", title: "Uzak mesafe ilişkileri", cefr: "B2", icon: "💌", desc: "Maya ve Tom, farklı ülkelerde yaşayan çiftlerin ilişkiyi nasıl ayakta tuttuğunu dinleyici mesajları üzerinden konuşuyor.",
    lines: [
      ["Tom", "Good evening and welcome to ASİ Dil Radio. Tonight's topic was chosen by you, our listeners. Long-distance relationships.", "İyi akşamlar, ASİ Dil Radyo'ya hoş geldiniz. Bu akşamın konusunu siz dinleyicilerimiz seçtiniz. Uzak mesafe ilişkileri."],
      ["Maya", "We got so many messages about this. Clearly a lot of you are going through it right now.", "Bu konuda o kadar çok mesaj aldık ki. Belli ki birçoğunuz şu anda bunu yaşıyor."],
      ["Tom", "Here's one from Emre. He's in Ankara and his girlfriend has just moved to Berlin for a master's degree. He asks, is it worth it, or are we just putting off the inevitable?", "İşte Emre'den bir tane. Kendisi Ankara'da, kız arkadaşı da yüksek lisans için Berlin'e yeni taşınmış. Soruyor, buna değer mi, yoksa sadece kaçınılmaz olanı erteliyor muyuz?"],
      ["Maya", "Oh, Emre. I've been there. My partner and I spent a year and a half on different continents.", "Ah, Emre. Ben de yaşadım. Partnerimle bir buçuk yıl farklı kıtalarda geçirdik."],
      ["Tom", "I didn't know that. How did you make it work?", "Bunu bilmiyordum. Nasıl yürüttünüz?"],
      ["Maya", "Honestly, the key thing was having an end date. We knew that after eighteen months one of us would move. That gave us something to look forward to.", "Dürüst olmak gerekirse en önemli şey bir bitiş tarihimizin olmasıydı. On sekiz ay sonra birimizin taşınacağını biliyorduk. Bu bize sabırsızlıkla bekleyeceğimiz bir şey verdi."],
      ["Tom", "That makes sense. Without a plan, it can feel like you're just drifting.", "Mantıklı. Bir plan olmadan sadece sürükleniyormuşsunuz gibi hissedebilir."],
      ["Maya", "Exactly. The second thing was not trying to talk all the time. At first we were on video calls for three hours every night, and we ran out of things to say.", "Aynen. İkinci şey de sürekli konuşmaya çalışmamaktı. Başta her gece üç saat görüntülü konuşuyorduk ve söyleyecek şeyimiz kalmıyordu."],
      ["Tom", "So quality over quantity.", "Yani nicelik değil nitelik."],
      ["Maya", "Right. We started doing things together instead. Watching the same film at the same time, cooking the same recipe. Silly things, but they made us feel close.", "Doğru. Onun yerine birlikte bir şeyler yapmaya başladık. Aynı anda aynı filmi izlemek, aynı tarifi pişirmek. Saçma şeyler ama bizi yakın hissettirdi."],
      ["Tom", "I like that. Here's another message, from Ayşe. She says the time difference is killing her. She's in Istanbul and he's in Vancouver.", "Bunu sevdim. İşte bir mesaj daha, Ayşe'den. Saat farkının onu bitirdiğini söylüyor. Kendisi İstanbul'da, sevgilisi Vancouver'da."],
      ["Maya", "Ooh, that's ten or eleven hours. That's tough. When one of you is waking up, the other is falling asleep.", "Ooh, bu on ya da on bir saat. Bu zor. Biriniz uyanırken diğeri uykuya dalıyor."],
      ["Tom", "My advice, for what it's worth, would be to agree on one fixed time slot that works for both of you, and protect it. Treat it like an important meeting.", "Benim tavsiyem, ne kadar değerliyse artık, ikinize de uyan sabit bir zaman dilimi üzerinde anlaşmak ve onu korumak olurdu. Önemli bir toplantı gibi davranın."],
      ["Maya", "And send voice messages! They're so much warmer than texts. You can hear the other person's mood.", "Bir de sesli mesaj gönderin! Yazılı mesajlardan çok daha sıcaklar. Karşı tarafın ruh halini duyabiliyorsunuz."],
      ["Tom", "True. Although my voice messages tend to be seven minutes long and mostly about the weather.", "Doğru. Gerçi benim sesli mesajlarım genelde yedi dakika sürüyor ve çoğunlukla hava durumu hakkında oluyor."],
      ["Maya", "That's the most British thing you've ever said. Anyway, to Emre and Ayşe, distance doesn't ruin a strong relationship. It just tests it.", "Bu söylediğin en İngiliz şey. Neyse, Emre ve Ayşe'ye, mesafe güçlü bir ilişkiyi mahvetmez. Sadece onu sınar."],
      ["Tom", "Beautifully put. Keep the messages coming, everyone.", "Çok güzel söyledin. Mesajlarınızı göndermeye devam edin, herkes."]
    ],
    questions: [
      { after: 2, q: "Why is Emre's girlfriend in Berlin?", options: ["She got a new job there", "She is doing a master's degree", "Her family lives there"], answer: 1 },
      { after: 5, q: "According to Maya, what helped her relationship most?", options: ["Having a clear end date for the distance", "Talking for hours every night", "Visiting each other every month"], answer: 0 },
      { after: 9, q: "What did Maya and her partner start doing instead of long calls?", options: ["Writing letters", "Playing online games with friends", "Doing the same activities at the same time"], answer: 2 },
      { after: 12, q: "What does Tom suggest for couples with a big time difference?", options: ["Moving to the same city immediately", "Agreeing on a fixed time slot and protecting it", "Only talking at weekends"], answer: 1 }
    ] },

  { id: "p8", title: "Uyku, en ucuz süper güç", cefr: "B2", icon: "😴", desc: "Konuk uyku araştırmacısı Dr. Kerem Aydın, iyi uykunun neden hafife alındığını ve küçük alışkanlıkların etkisini anlatıyor.",
    lines: [
      ["Maya", "Welcome back! Today's episode is about something we all do, but most of us don't do very well. Sleep.", "Tekrar hoş geldiniz! Bugünkü bölüm hepimizin yaptığı ama çoğumuzun pek iyi yapmadığı bir şey hakkında. Uyku."],
      ["Tom", "And joining us is Dr Kerem Aydın, who studies sleep for a living. Which sounds like the dream job, to be honest.", "Ve bize uykuyu meslek olarak inceleyen Dr. Kerem Aydın katılıyor. Açıkçası rüya gibi bir iş gibi geliyor."],
      ["Kerem", "Everyone says that! Unfortunately, I mostly watch other people sleep while I stay awake.", "Herkes bunu söylüyor! Ne yazık ki çoğunlukla ben uyanıkken başkalarının uyumasını izliyorum."],
      ["Maya", "So, Kerem, let's start with the big question. How much sleep do adults actually need?", "Peki Kerem, büyük soruyla başlayalım. Yetişkinlerin gerçekte ne kadar uykuya ihtiyacı var?"],
      ["Kerem", "For most adults, somewhere between seven and nine hours. There are a few people who genuinely manage on less, but they're far rarer than people think.", "Çoğu yetişkin için yedi ile dokuz saat arası. Gerçekten daha azıyla idare edebilen birkaç kişi var ama insanların sandığından çok daha nadirler."],
      ["Tom", "So when my old boss bragged about sleeping four hours a night, was he lying?", "Yani eski patronum gecede dört saat uyumakla övündüğünde yalan mı söylüyordu?"],
      ["Kerem", "He was probably running on empty and didn't realise it. Sleep deprivation sneaks up on you. You get used to feeling slightly worse, and you think it's normal.", "Muhtemelen boş depoyla gidiyordu ve farkında değildi. Uykusuzluk sinsice gelir. Biraz daha kötü hissetmeye alışırsınız ve bunun normal olduğunu düşünürsünüz."],
      ["Maya", "That's a bit scary. What are the most common mistakes people make?", "Bu biraz korkutucu. İnsanların en sık yaptığı hatalar neler?"],
      ["Kerem", "The big one is an irregular schedule. Going to bed at midnight on weekdays and three a.m. at weekends confuses your body clock. It's like giving yourself jet lag every Monday.", "En büyüğü düzensiz bir program. Hafta içi gece yarısı, hafta sonu sabah üçte yatmak vücut saatinizin kafasını karıştırır. Her pazartesi kendinize jet lag yaşatmak gibi."],
      ["Tom", "Social jet lag. I think I've had that since university.", "Sosyal jet lag. Sanırım üniversiteden beri bende var."],
      ["Kerem", "You're not alone. The other big one is caffeine. Coffee can stay in your system for up to ten hours, so an afternoon espresso might be what's keeping you awake at night.", "Yalnız değilsin. Diğer büyük hata kafein. Kahve vücudunuzda on saate kadar kalabilir, yani öğleden sonraki bir espresso sizi gece uyanık tutan şey olabilir."],
      ["Maya", "Okay, I'm feeling personally attacked. I have a coffee at four every day.", "Tamam, kişisel olarak saldırıya uğramış hissediyorum. Her gün saat dörtte kahve içiyorum."],
      ["Kerem", "Try cutting it off after lunch for two weeks and see what happens. Most people notice a difference surprisingly quickly.", "İki hafta boyunca öğle yemeğinden sonra kesmeyi deneyin ve ne olacağını görün. Çoğu insan farkı şaşırtıcı derecede çabuk fark eder."],
      ["Tom", "What about people who just lie there and can't switch their brain off?", "Peki ya orada öylece yatan ve beynini kapatamayan insanlar?"],
      ["Kerem", "That's very common. One simple technique is to keep a notebook by the bed and write down whatever is on your mind. Getting it out of your head and onto paper really helps.", "Bu çok yaygın. Basit bir teknik, yatağın yanında bir defter tutmak ve aklınızda ne varsa yazmak. Onu kafanızdan çıkarıp kâğıda dökmek gerçekten işe yarıyor."],
      ["Maya", "And if you still can't sleep after, say, twenty minutes?", "Peki ya diyelim yirmi dakika sonra hâlâ uyuyamıyorsanız?"],
      ["Kerem", "Get up, go to another room and do something boring in dim light. Don't stay in bed tossing and turning. Your brain starts to link the bed with frustration.", "Kalkın, başka bir odaya gidin ve loş ışıkta sıkıcı bir şey yapın. Yatakta dönüp durmayın. Beyniniz yatağı hayal kırıklığıyla ilişkilendirmeye başlar."],
      ["Tom", "Something boring. I could listen to my own voice messages.", "Sıkıcı bir şey. Kendi sesli mesajlarımı dinleyebilirim."],
      ["Maya", "Perfect cure. Thank you so much, Kerem. Sleep well, everyone!", "Mükemmel çare. Çok teşekkürler Kerem. Herkese iyi uykular!"]
    ],
    questions: [
      { after: 4, q: "How much sleep do most adults need, according to Kerem?", options: ["Five to six hours", "Seven to nine hours", "Ten hours or more"], answer: 1 },
      { after: 8, q: "What does Kerem compare an irregular sleep schedule to?", options: ["Giving yourself jet lag every week", "Drinking too much coffee", "Working the night shift"], answer: 0 },
      { after: 12, q: "What does Kerem suggest Maya should try?", options: ["Switching to tea at four o'clock", "Drinking coffee only at weekends", "Stopping coffee after lunch for two weeks"], answer: 2 },
      { after: 16, q: "What should you do if you can't sleep after about twenty minutes?", options: ["Stay in bed and keep trying", "Get up and do something boring in dim light", "Check your phone until you feel tired"], answer: 1 }
    ] },

  { id: "p9", title: "Yapay zekâ işimi elimden alır mı?", cefr: "B2", icon: "🤖", desc: "Maya ve Tom, yapay zekânın iş dünyasını nasıl değiştirdiğini ve bundan korkmak yerine nasıl uyum sağlanabileceğini tartışıyor.",
    lines: [
      ["Tom", "Hello, and welcome to ASİ Dil Radio. Today's topic is one that keeps a lot of people up at night. Will artificial intelligence take my job?", "Merhaba, ASİ Dil Radyo'ya hoş geldiniz. Bugünün konusu birçok insanı geceleri uyutmayan bir konu. Yapay zekâ işimi elimden alacak mı?"],
      ["Maya", "And before anyone asks, no, Tom and I have not been replaced by robots. Yet.", "Ve kimse sormadan söyleyelim, hayır, Tom ve ben robotlarla değiştirilmedik. Henüz."],
      ["Tom", "Although a robot would probably laugh at my jokes more convincingly than you do.", "Gerçi bir robot muhtemelen benim esprilerime senden daha inandırıcı gülerdi."],
      ["Maya", "Ha ha. Seriously though, I think the fear is understandable. A friend of mine is a translator, and she says her workload has changed completely in two years.", "Ha ha. Ciddi olarak ise, bence korku anlaşılır. Bir arkadaşım çevirmen ve iş yükünün iki yılda tamamen değiştiğini söylüyor."],
      ["Tom", "Changed how? Has she lost clients?", "Nasıl değişti? Müşteri mi kaybetti?"],
      ["Maya", "Some, yes. But what's interesting is that a lot of her work now is checking and polishing machine translations. The simple stuff is automated, but clients still want a human to make it sound natural.", "Bazılarını, evet. Ama ilginç olan şu, işinin büyük kısmı artık makine çevirilerini kontrol etmek ve parlatmak. Basit işler otomatik ama müşteriler hâlâ metnin doğal duyulmasını sağlayacak bir insan istiyor."],
      ["Tom", "So the job hasn't disappeared, it's shifted.", "Yani iş ortadan kalkmadı, yer değiştirdi."],
      ["Maya", "Exactly. And I think that's the pattern in a lot of industries. The tasks change before the jobs do.", "Aynen. Ve bence birçok sektörde durum böyle. İşlerden önce görevler değişiyor."],
      ["Tom", "I'd push back a little, though. For some people, the shift is brutal. If you've spent twenty years doing one thing, being told to just adapt isn't very comforting.", "Gerçi biraz itiraz edeceğim. Bazı insanlar için bu değişim acımasız. Yirmi yılını tek bir şeyi yaparak geçirdiysen, sadece uyum sağla denmesi pek teselli edici değil."],
      ["Maya", "That's fair. It's easy to say from the outside. Companies and governments need to invest in retraining, not just leave people to figure it out alone.", "Haklısın. Dışarıdan söylemesi kolay. Şirketlerin ve hükümetlerin yeniden eğitime yatırım yapması gerekiyor, insanları bunu tek başlarına çözmeye bırakmamaları lazım."],
      ["Tom", "Agreed. So what can an individual listener actually do?", "Katılıyorum. Peki tek bir dinleyici gerçekte ne yapabilir?"],
      ["Maya", "I'd say get curious rather than scared. Try the tools. Find out what they're good at and, more importantly, what they're bad at.", "Korkmak yerine merak edin derim. Araçları deneyin. Neyde iyi olduklarını ve daha da önemlisi neyde kötü olduklarını öğrenin."],
      ["Tom", "Because they're surprisingly bad at some things. I asked one to write a joke about British weather and it was dreadful.", "Çünkü bazı şeylerde şaşırtıcı derecede kötüler. Birinden İngiliz havası hakkında bir espri yazmasını istedim ve berbattı."],
      ["Maya", "To be fair, so are yours.", "Açıkçası seninkiler de öyle."],
      ["Tom", "Touché. But here's my serious point. Skills like empathy, judgement and dealing with messy, unpredictable people are still very hard to automate.", "Touché. Ama ciddi noktam şu. Empati, sağduyu ve dağınık, öngörülemez insanlarla başa çıkmak gibi beceriler hâlâ otomatikleştirilmesi çok zor şeyler."],
      ["Maya", "And communication! Which brings us back to learning languages. Speaking to a real person in their own language builds trust in a way a machine can't.", "Ve iletişim! Bu da bizi dil öğrenmeye geri getiriyor. Gerçek bir insanla kendi dilinde konuşmak, bir makinenin kuramayacağı şekilde güven inşa eder."],
      ["Tom", "A shameless plug, but a true one. Keep learning, everyone. See you next time.", "Utanmazca bir reklam ama doğru bir reklam. Öğrenmeye devam edin, herkes. Bir dahaki sefere görüşürüz."]
    ],
    questions: [
      { after: 5, q: "How has the work of Maya's translator friend changed?", options: ["She now mostly checks and improves machine translations", "She has stopped translating completely", "She only works with books now"], answer: 0 },
      { after: 9, q: "What is Tom's concern about telling people to adapt?", options: ["It is too expensive for companies", "It ignores how hard the change can be for some workers", "Most people don't want to learn new skills"], answer: 1 },
      { after: 11, q: "What does Maya advise listeners to do?", options: ["Avoid AI tools completely", "Change careers immediately", "Experiment with the tools and learn their limits"], answer: 2 },
      { after: 14, q: "Which skills does Tom think are hard to automate?", options: ["Typing and data entry", "Empathy, judgement and handling people", "Translation and writing jokes"], answer: 1 }
    ] },

  { id: "p10", title: "Dolaylı konuşma sanatı", cefr: "C1", icon: "🫖", desc: "Maya ve Tom, İngilizlerin ima yoluyla konuşma alışkanlığını, Kanadalı nezaketini ve Türk misafirperverliğini karşılaştırıyor.",
    lines: [
      ["Maya", "Welcome to ASİ Dil Radio. Today we're tackling something that trips up even very advanced learners. What people say versus what they actually mean.", "ASİ Dil Radyo'ya hoş geldiniz. Bugün çok ileri seviyedeki öğrencileri bile tökezleten bir konuyu ele alıyoruz. İnsanların söyledikleri ile gerçekte kastettikleri."],
      ["Tom", "In other words, an entire episode about my people. The British are, I'll admit, world champions at saying one thing and meaning something else entirely.", "Başka bir deyişle, tamamen benim halkım hakkında bir bölüm. İngilizler, itiraf edeyim, bir şey söyleyip bambaşka bir şey kastetmekte dünya şampiyonudur."],
      ["Maya", "Give us a classic example.", "Bize klasik bir örnek ver."],
      ["Tom", "Right. If a British colleague reads your proposal and says, that's an interesting idea, you should be slightly worried. What they often mean is, I have serious doubts, but I'm far too polite to say so.", "Peki. Eğer İngiliz bir iş arkadaşınız teklifinizi okuyup bu ilginç bir fikir derse, biraz endişelenmelisiniz. Çoğu zaman kastettikleri şudur, ciddi şüphelerim var ama bunu söyleyemeyecek kadar kibarım."],
      ["Maya", "See, that drives me up the wall. As a Canadian, I'm polite too, but if I say something's interesting, I genuinely find it interesting.", "İşte bu beni çileden çıkarıyor. Bir Kanadalı olarak ben de kibarım ama bir şeyin ilginç olduğunu söylersem, gerçekten ilginç buluyorumdur."],
      ["Tom", "Which makes you dangerously easy to read. Another one is with the greatest respect. That roughly translates as, I'm about to tell you you're completely wrong.", "Bu da seni tehlikeli derecede kolay okunur yapıyor. Bir diğeri de with the greatest respect, yani en büyük saygıyla. Kabaca şu anlama gelir, tamamen yanıldığını söylemek üzereyim."],
      ["Maya", "And the thing is, this isn't really about vocabulary. A learner can know every single word and still completely misread the situation.", "Ve mesele şu ki bu aslında kelime bilgisiyle ilgili değil. Bir öğrenci her kelimeyi bilip yine de durumu tamamen yanlış okuyabilir."],
      ["Tom", "Quite. It's about reading between the lines. And I suspect Turkish listeners are actually rather well equipped for this.", "Kesinlikle. Mesele satır aralarını okumak. Ve Türk dinleyicilerin aslında buna oldukça hazırlıklı olduğundan şüpheleniyorum."],
      ["Maya", "Oh, totally. My Turkish friend explained that if you visit someone and they offer you tea, you're supposed to decline once or twice before accepting.", "Ah, kesinlikle. Türk bir arkadaşım, birini ziyaret ettiğinizde size çay ikram ederlerse kabul etmeden önce bir iki kez geri çevirmeniz gerektiğini anlatmıştı."],
      ["Tom", "And the host is supposed to insist. It's a little ritual both sides understand perfectly, even though nobody spells it out.", "Ve ev sahibinin de ısrar etmesi gerekiyor. Kimse açıkça söylemese de iki tarafın da gayet iyi anladığı küçük bir ritüel."],
      ["Maya", "Whereas in Canada, if you say no thanks, we'll take you at your word and you'll go home thirsty.", "Oysa Kanada'da hayır teşekkürler derseniz, sözünüze güveniriz ve eve susuz dönersiniz."],
      ["Tom", "Brutal. So the skill transfers, but the codes are different. You have to learn a new set of signals for each culture.", "Acımasız. Yani beceri aktarılabiliyor ama kodlar farklı. Her kültür için yeni bir işaretler dizisi öğrenmeniz gerekiyor."],
      ["Maya", "So what's the practical advice for someone moving to the UK for work?", "Peki iş için Birleşik Krallık'a taşınan biri için pratik tavsiye ne?"],
      ["Tom", "Pay attention to tone and to what's left unsaid. If feedback seems oddly vague, it's perfectly acceptable to ask a clarifying question. Something like, just so I'm clear, would you like me to rework this section?", "Tona ve söylenmeyenlere dikkat edin. Eğer geri bildirim tuhaf biçimde belirsiz görünüyorsa, açıklayıcı bir soru sormak tamamen kabul edilebilir. Şöyle bir şey, net anlamak için soruyorum, bu bölümü yeniden düzenlememi ister misiniz?"],
      ["Maya", "That's clever, because it gives the other person a polite way to be direct.", "Bu zekice, çünkü karşı tarafa doğrudan olmanın kibar bir yolunu sunuyor."],
      ["Tom", "Precisely. You're essentially doing the translation for them.", "Kesinlikle. Esasen çeviriyi onlar için sen yapıyorsun."],
      ["Maya", "And on the flip side, if you're naturally quite direct, it's worth softening things a bit. Adding I wonder if or perhaps we could goes a long way.", "Öte yandan, eğer doğal olarak oldukça doğrudansanız, işleri biraz yumuşatmaya değer. I wonder if ya da perhaps we could gibi ifadeler eklemek çok işe yarar."],
      ["Tom", "With the greatest respect, Maya, that's an interesting idea.", "En büyük saygıyla Maya, bu ilginç bir fikir."],
      ["Maya", "I'm choosing to take that as a compliment. Thanks for listening, everyone!", "Bunu iltifat olarak almayı seçiyorum. Dinlediğiniz için teşekkürler, herkes!"]
    ],
    questions: [
      { after: 3, q: "When a British colleague calls a proposal interesting, what might they actually mean?", options: ["They want to discuss it over lunch", "They have serious reservations about it", "They intend to approve it immediately"], answer: 1 },
      { after: 6, q: "What point does Maya make about advanced learners?", options: ["Knowing the vocabulary doesn't guarantee understanding the intended meaning", "They usually understand British humour perfectly", "They should avoid polite phrases altogether"], answer: 0 },
      { after: 10, q: "How does the tea ritual illustrate cultural differences?", options: ["Canadians always insist on offering tea twice", "Turkish hosts never offer tea to strangers", "In Turkey declining is part of a shared ritual, while in Canada a refusal is taken literally"], answer: 2 },
      { after: 15, q: "Why does Maya think a clarifying question is useful?", options: ["It shows that you are more senior", "It allows the other person to be direct without seeming rude", "It avoids the need for any further feedback"], answer: 1 }
    ] },

  { id: "p11", title: "Tükenmişlik ve hırsın bedeli", cefr: "C1", icon: "🔥", desc: "Konuk eski yönetim danışmanı Leyla, tükenmişliği nasıl fark etmediğini ve kariyerini yeniden nasıl kurduğunu anlatıyor.",
    lines: [
      ["Tom", "Welcome to ASİ Dil Radio. Today's conversation is a bit more serious than usual. We're talking about burnout, and we're joined by Leyla, who spent eight years in management consulting before, in her words, hitting a wall.", "ASİ Dil Radyo'ya hoş geldiniz. Bugünkü sohbet her zamankinden biraz daha ciddi. Tükenmişliği konuşuyoruz ve bize, kendi deyişiyle duvara toslamadan önce sekiz yıl yönetim danışmanlığında çalışan Leyla katılıyor."],
      ["Leyla", "Thanks for having me. And yes, hitting a wall is the polite version. The less polite version involves crying in a hotel bathroom in Frankfurt.", "Davetiniz için teşekkürler. Ve evet, duvara toslamak kibar versiyonu. Daha az kibar versiyonunda Frankfurt'ta bir otel banyosunda ağlamak var."],
      ["Maya", "Oh, Leyla. Can you take us back to before that point? Were there warning signs?", "Ah, Leyla. Bizi o noktadan öncesine götürebilir misin? Uyarı işaretleri var mıydı?"],
      ["Leyla", "Plenty, in hindsight. I was constantly exhausted, but I put it down to jet lag. I'd stopped enjoying things I used to love, and I'd become incredibly cynical about my clients. But I was so caught up in the next deadline that I never joined the dots.", "Geriye dönüp bakınca, bolca. Sürekli bitkindim ama bunu jet lag'e bağlıyordum. Eskiden sevdiğim şeylerden keyif almayı bırakmıştım ve müşterilerime karşı inanılmaz derecede alaycı olmuştum. Ama bir sonraki teslim tarihine o kadar kapılmıştım ki noktaları hiç birleştirmedim."],
      ["Tom", "That cynicism part is interesting. I think people assume burnout just means being tired.", "O alaycılık kısmı ilginç. Bence insanlar tükenmişliğin sadece yorgun olmak anlamına geldiğini sanıyor."],
      ["Leyla", "Right, and that's a misconception. Tiredness goes away after a good holiday. Burnout doesn't. It's more of a slow erosion of your sense that what you're doing matters.", "Doğru, bu bir yanılgı. Yorgunluk iyi bir tatilden sonra geçer. Tükenmişlik geçmez. Daha çok, yaptığın şeyin önemli olduğu duygusunun yavaş yavaş aşınması gibi."],
      ["Maya", "Why do you think you didn't step back sooner?", "Sence neden daha erken geri çekilmedin?"],
      ["Leyla", "Partly ego, if I'm honest. My whole identity was built around being the one who could handle anything. Admitting I was struggling felt like admitting I'd failed.", "Dürüst olmam gerekirse kısmen ego. Bütün kimliğim her şeyin üstesinden gelebilen kişi olmak üzerine kuruluydu. Zorlandığımı kabul etmek başarısız olduğumu kabul etmek gibi geliyordu."],
      ["Tom", "I suspect a lot of high achievers listening will recognise that. Achievement becomes who you are rather than what you do.", "Dinleyen pek çok başarı odaklı kişinin bunu tanıyacağından şüpheleniyorum. Başarı, yaptığın şey olmaktan çıkıp kim olduğun haline geliyor."],
      ["Leyla", "Exactly that. And the workplace culture reinforced it. Long hours were worn like a badge of honour. Nobody ever said slow down, because everybody was in the same boat.", "Tam olarak bu. Ve işyeri kültürü bunu pekiştiriyordu. Uzun çalışma saatleri bir onur nişanı gibi taşınıyordu. Kimse yavaşla demiyordu çünkü herkes aynı gemideydi."],
      ["Maya", "So what happened after Frankfurt?", "Peki Frankfurt'tan sonra ne oldu?"],
      ["Leyla", "I took three months off, which at the time felt like career suicide. I saw a therapist, I slept a lot, and slowly I started to untangle what I actually valued from what I'd been told to value.", "Üç ay izin aldım, o zamanlar bu kariyer intiharı gibi geliyordu. Bir terapiste gittim, çok uyudum ve yavaş yavaş gerçekten değer verdiğim şeyleri bana değer vermem söylenen şeylerden ayırmaya başladım."],
      ["Tom", "And did you go back to consulting?", "Peki danışmanlığa geri döndün mü?"],
      ["Leyla", "Not in the same way. I now run a small practice advising nonprofits, three and a half days a week. I earn considerably less, but I sleep at night and I actually like the people I work with.", "Aynı şekilde değil. Şimdi haftada üç buçuk gün kâr amacı gütmeyen kuruluşlara danışmanlık yapan küçük bir ofisim var. Belirgin şekilde daha az kazanıyorum ama geceleri uyuyorum ve birlikte çalıştığım insanları gerçekten seviyorum."],
      ["Maya", "That's a trade-off a lot of people would envy. What would you say to someone who's listening and thinks, this sounds uncomfortably familiar?", "Bu birçok insanın imreneceği bir takas. Dinleyen ve bu rahatsız edici derecede tanıdık geliyor diye düşünen birine ne söylerdin?"],
      ["Leyla", "I'd say don't wait for the hotel bathroom moment. Talk to someone you trust now, and take the early signs seriously. Rest isn't a reward you earn once everything is done, because everything is never done.", "Otel banyosu anını beklemeyin derdim. Güvendiğiniz biriyle şimdi konuşun ve erken işaretleri ciddiye alın. Dinlenmek her şey bittiğinde kazandığınız bir ödül değil, çünkü her şey asla bitmez."],
      ["Tom", "That last line is going on my fridge. Thank you, Leyla, for being so candid.", "O son cümle buzdolabıma gidiyor. Bu kadar içten olduğun için teşekkürler Leyla."],
      ["Maya", "And to our listeners, look after yourselves. We'll be back next week.", "Ve dinleyicilerimize, kendinize iyi bakın. Haftaya döneceğiz."]
    ],
    questions: [
      { after: 3, q: "How did Leyla initially explain her constant exhaustion?", options: ["She blamed it on jet lag", "She thought she had a medical condition", "She assumed it was a lack of exercise"], answer: 0 },
      { after: 5, q: "According to Leyla, how does burnout differ from ordinary tiredness?", options: ["It only affects people in senior roles", "It is not resolved by a holiday and erodes your sense of purpose", "It mainly causes physical rather than emotional symptoms"], answer: 1 },
      { after: 9, q: "What role did workplace culture play?", options: ["It encouraged employees to take regular breaks", "It had no real influence on her situation", "It celebrated long hours, so nobody urged her to slow down"], answer: 2 },
      { after: 15, q: "What is Leyla's key message to listeners?", options: ["Rest should come only after all your work is finished", "Act on the early signs instead of waiting for a crisis", "Leave your job immediately if you feel tired"], answer: 1 }
    ] },

  { id: "p12", title: "Eve dönüş şoku", cefr: "C1", icon: "✈️", desc: "Yıllarca yurt dışında yaşadıktan sonra memleketine dönen Can, ters kültür şokunu ve iki dünya arasında kalmayı anlatıyor.",
    lines: [
      ["Maya", "Hello and welcome to ASİ Dil Radio. We've talked a lot about moving abroad on this show, but today we're looking at something people rarely warn you about. Moving back home.", "Merhaba, ASİ Dil Radyo'ya hoş geldiniz. Bu programda yurt dışına taşınmayı çok konuştuk ama bugün insanların sizi nadiren uyardığı bir şeye bakıyoruz. Eve geri taşınmak."],
      ["Tom", "Our guest is Can, who spent eleven years in Melbourne and moved back to Eskişehir last spring. Welcome, Can.", "Konuğumuz, on bir yıl Melbourne'de yaşayıp geçen bahar Eskişehir'e geri dönen Can. Hoş geldin Can."],
      ["Can", "Cheers, mate. Sorry, eleven years of Australian English. It's proving rather hard to shake off.", "Sağ ol dostum. Pardon, on bir yıllık Avustralya İngilizcesi. Ondan kurtulmak epey zor oluyor."],
      ["Tom", "Don't apologise. It's a welcome change from Maya's relentless Canadian enthusiasm.", "Özür dileme. Maya'nın bitmek bilmeyen Kanadalı coşkusundan sonra hoş bir değişiklik."],
      ["Maya", "Rude! Anyway, Can, I'm guessing you expected moving home to be the easy part.", "Kaba! Neyse Can, tahminimce eve dönmenin işin kolay kısmı olacağını sanıyordun."],
      ["Can", "Absolutely. I'd spent years feeling like an outsider in Australia, so I assumed coming back would feel like slipping into an old pair of shoes. Instead, it felt like the shoes had shrunk.", "Kesinlikle. Yıllarca Avustralya'da kendimi yabancı gibi hissetmiştim, bu yüzden geri dönmenin eski bir ayakkabıyı giymek gibi olacağını sandım. Onun yerine ayakkabılar küçülmüş gibi geldi."],
      ["Tom", "That's a vivid way of putting it. What exactly felt off?", "Bunu çok canlı bir şekilde ifade ettin. Tam olarak ne tuhaf geldi?"],
      ["Can", "Small things at first. I'd queue patiently and people would just walk past me. I'd say sorry constantly, and my friends would tease me for being too formal. And then bigger things. Everyone's lives had moved on without me.", "Önce küçük şeyler. Sabırla sıraya giriyordum ve insanlar yanımdan geçip gidiyordu. Sürekli özür diliyordum ve arkadaşlarım fazla resmî olduğum için benimle dalga geçiyordu. Sonra daha büyük şeyler. Herkesin hayatı bensiz devam etmişti."],
      ["Maya", "That must have been quite isolating, especially when you'd expected the opposite.", "Bu oldukça yalnızlaştırıcı olmuş olmalı, özellikle tam tersini beklerken."],
      ["Can", "It was. And the hardest part was that nobody really wanted to hear about it. If you complain about living abroad, people sympathise. If you complain about coming home, they look at you as if you're being ungrateful.", "Öyleydi. Ve en zor kısmı, kimsenin bunu gerçekten duymak istememesiydi. Yurt dışında yaşamaktan şikâyet edersen insanlar anlayış gösterir. Eve dönmekten şikâyet edersen sana nankörlük ediyormuşsun gibi bakarlar."],
      ["Tom", "There's an assumption that home is a fixed place waiting for you. But you've changed, and so has it.", "Evin seni bekleyen sabit bir yer olduğu varsayımı var. Ama sen değiştin, o da değişti."],
      ["Can", "Exactly. I think I'd romanticised it, too. In Melbourne, I'd remember the long breakfasts and the family gatherings, and conveniently forget the traffic and the bureaucracy.", "Aynen. Sanırım onu romantikleştirmiştim de. Melbourne'deyken uzun kahvaltıları ve aile toplantılarını hatırlıyor, trafiği ve bürokrasiyi işime geldiği gibi unutuyordum."],
      ["Maya", "Nostalgia is a very selective editor.", "Nostalji çok seçici bir editördür."],
      ["Can", "Ruthlessly selective. But I don't want to sound negative, because it's got much better. About six months in, something shifted.", "Acımasızca seçici. Ama olumsuz görünmek istemem, çünkü çok daha iyi oldu. Altıncı ay civarında bir şey değişti."],
      ["Tom", "What changed?", "Ne değişti?"],
      ["Can", "I stopped trying to be the person I was before I left. I accepted that I'm a bit of both now. I still have tea and toast some mornings, and I've joined a group of other returnees who meet once a month.", "Gitmeden önceki kişi olmaya çalışmayı bıraktım. Artık biraz ikisinden de olduğumu kabul ettim. Bazı sabahlar hâlâ çay ve kızarmış ekmek yiyorum ve ayda bir buluşan, geri dönmüş insanlardan oluşan bir gruba katıldım."],
      ["Maya", "I love that. A support group for people caught between two worlds.", "Buna bayıldım. İki dünya arasında kalmış insanlar için bir destek grubu."],
      ["Can", "We mostly just complain about the lack of decent flat whites, but yes, it helps enormously to know you're not alone.", "Çoğunlukla düzgün flat white yokluğundan şikâyet ediyoruz ama evet, yalnız olmadığını bilmek muazzam ölçüde yardımcı oluyor."],
      ["Tom", "Any final advice for listeners planning to move back home?", "Eve dönmeyi planlayan dinleyiciler için son bir tavsiye var mı?"],
      ["Can", "Give yourself the same patience you gave yourself when you first moved abroad. You're adjusting to a new place, even if it has a familiar name.", "İlk yurt dışına taşındığınızda kendinize gösterdiğiniz sabrın aynısını kendinize gösterin. Tanıdık bir adı olsa bile yeni bir yere uyum sağlıyorsunuz."],
      ["Maya", "What a perfect note to end on. Thank you so much, Can.", "Bitirmek için ne mükemmel bir not. Çok teşekkürler Can."],
      ["Tom", "And thank you all for listening. Wherever home is for you right now.", "Ve dinlediğiniz için hepinize teşekkürler. Şu anda eviniz neresiyse."]
    ],
    questions: [
      { after: 5, q: "What does Can mean by saying the shoes had shrunk?", options: ["Home no longer fitted him the way he had expected", "He had gained weight in Australia", "His old belongings had been thrown away"], answer: 0 },
      { after: 9, q: "Why was it hard for Can to talk about his difficulties?", options: ["His friends had all moved abroad", "People saw complaints about returning home as ungrateful", "He had forgotten much of his Turkish"], answer: 1 },
      { after: 12, q: "What does Maya mean by calling nostalgia a very selective editor?", options: ["People tend to forget their happiest memories", "Nostalgia makes people want to travel more", "Memory keeps the pleasant parts of a place and cuts out the negative ones"], answer: 2 },
      { after: 15, q: "What turned things around for Can after about six months?", options: ["He accepted his mixed identity and found a community of returnees", "He decided to move back to Melbourne", "He found a job with an Australian company"], answer: 0 }
    ] }
);
