(window.READINGS = window.READINGS || []).push(
  { id: "r11", title: "The Four-Day Week Nobody Expected to Work", trTitle: "Kimsenin İşe Yarayacağını Düşünmediği Dört Günlük Hafta", cefr: "B2", icon: "🗓️", kind: "Haber",
    paragraphs: [
      ["When Northgate Freight, a mid-sized logistics company with around two hundred employees, announced that it would trial a four-day working week, many of its own managers assumed the experiment would quietly collapse within a month. Logistics, after all, is an industry built on tight deadlines, early mornings and the constant pressure of trucks that need to leave on time. Yet a year later, the company has not only kept the shorter week but has also reported fewer sick days and a noticeable drop in staff turnover.", "Yaklaşık iki yüz çalışanı olan orta ölçekli bir lojistik şirketi olan Northgate Freight, dört günlük çalışma haftasını deneyeceğini duyurduğunda, kendi yöneticilerinin çoğu deneyin bir ay içinde sessizce çökeceğini varsaydı. Ne de olsa lojistik, sıkı teslim tarihleri, sabahın erken saatleri ve zamanında yola çıkması gereken kamyonların sürekli baskısı üzerine kurulu bir sektör. Ama bir yıl sonra şirket kısa haftayı korumakla kalmadı, daha az hastalık izni ve personel devir oranında belirgin bir düşüş de bildirdi."],
      ["The rules of the trial were simple, at least on paper. Employees would work thirty-two hours instead of forty, with no reduction in pay, as long as productivity stayed at roughly the same level. Teams were allowed to decide for themselves which day they would take off, provided that someone was always available to deal with customers. The company hired an independent researcher to measure output, wellbeing and customer satisfaction before, during and after the trial.", "Deneyin kuralları en azından kâğıt üzerinde basitti. Verimlilik aşağı yukarı aynı seviyede kaldığı sürece çalışanlar maaşlarında hiçbir kesinti olmadan kırk yerine otuz iki saat çalışacaktı. Müşterilerle ilgilenmek için her zaman birinin hazır bulunması şartıyla, ekiplerin hangi gün izin yapacaklarına kendilerinin karar vermesine izin verildi. Şirket, deneyden önce, deney sırasında ve sonrasında üretimi, çalışan refahını ve müşteri memnuniyetini ölçmesi için bağımsız bir araştırmacı tuttu."],
      ["The first few weeks were, by most accounts, chaotic. Meetings that had previously dragged on for an hour suddenly had to be squeezed into twenty minutes, and several team leaders admitted that they had underestimated how much time was being wasted on unnecessary emails. 'We realised that a lot of our busyness was just noise,' said one warehouse supervisor. 'Once we cut that out, the actual work fitted into four days surprisingly well.'", "Çoğu kişiye göre ilk birkaç hafta kaotikti. Daha önce bir saat boyunca uzayıp giden toplantıların birden yirmi dakikaya sıkıştırılması gerekti ve birkaç ekip lideri gereksiz e-postalara ne kadar zaman harcandığını hafife aldıklarını itiraf etti. Bir depo sorumlusu 'Meşguliyetimizin büyük kısmının sadece gürültü olduğunu fark ettik' dedi. 'Onu ayıkladığımızda asıl iş şaşırtıcı derecede rahat bir şekilde dört güne sığdı.'"],
      ["Not everyone was convinced, however. Some employees complained that their four working days had become so intense that they spent the fifth day simply recovering. Others worried that the arrangement might be reversed if profits fell, which made it difficult to fully relax. The researcher noted that the benefits were unevenly distributed, with office staff generally gaining more than drivers, whose schedules depended heavily on external factors such as traffic and weather.", "Ancak herkes ikna olmuş değildi. Bazı çalışanlar dört iş gününün o kadar yoğunlaştığından şikâyet etti ki beşinci günü sadece toparlanarak geçiriyorlardı. Diğerleri, kârlar düşerse düzenlemenin geri alınabileceğinden endişe ediyordu ve bu da tamamen rahatlamayı zorlaştırıyordu. Araştırmacı, faydaların eşit dağılmadığını, ofis çalışanlarının genellikle programları trafik ve hava durumu gibi dış etkenlere büyük ölçüde bağlı olan şoförlerden daha fazla kazançlı çıktığını belirtti."],
      ["Despite these concerns, the overall results were hard to ignore. Output remained stable, customer complaints did not increase, and the number of people leaving the company fell by almost a third. Perhaps more importantly, the firm found it much easier to attract new applicants, which in a sector facing serious labour shortages is a considerable advantage. Several competitors have since contacted Northgate to ask how the transition was managed.", "Bu endişelere rağmen genel sonuçları görmezden gelmek zordu. Üretim sabit kaldı, müşteri şikâyetleri artmadı ve şirketten ayrılan kişi sayısı neredeyse üçte bir oranında azaldı. Belki daha da önemlisi, firma yeni başvuru sahiplerini çekmeyi çok daha kolay buldu ki bu, ciddi iş gücü sıkıntısı yaşayan bir sektörde kayda değer bir avantaj. O zamandan beri birkaç rakip firma, geçişin nasıl yönetildiğini sormak için Northgate ile iletişime geçti."],
      ["Experts caution that a single success story does not prove that the four-day week will work everywhere. Industries that rely on constant physical presence, such as healthcare or hospitality, face very different challenges. Still, the Northgate case suggests that the length of the working week may be less fixed than we tend to assume. As one manager put it, the real question is not whether people can work less, but whether organisations are willing to rethink how they work at all.", "Uzmanlar, tek bir başarı hikâyesinin dört günlük haftanın her yerde işe yarayacağını kanıtlamadığı konusunda uyarıyor. Sağlık hizmetleri veya konaklama sektörü gibi sürekli fiziksel varlığa dayanan sektörler çok farklı zorluklarla karşı karşıya. Yine de Northgate örneği, çalışma haftasının uzunluğunun sandığımız kadar sabit olmayabileceğini gösteriyor. Bir yöneticinin dediği gibi, asıl soru insanların daha az çalışıp çalışamayacağı değil, kurumların nasıl çalıştıklarını yeniden düşünmeye gerçekten istekli olup olmadığı."]
    ],
    glossary: [["trial", "denemek, deneme"], ["collapse", "çökmek"], ["turnover", "personel devir oranı"], ["reduction", "azalma, kesinti"], ["provided that", "şartıyla"], ["squeezed", "sıkıştırılmış"], ["underestimated", "hafife almış"], ["unevenly distributed", "eşit dağılmamış"], ["labour shortages", "iş gücü sıkıntısı"], ["caution", "uyarmak"], ["transition", "geçiş"]],
    questions: [
      { q: "Why did many managers expect the trial to fail?", options: ["Because employees did not want it", "Because logistics depends on tight deadlines and early starts", "Because the company was losing money"], answer: 1 },
      { q: "What was a condition of the trial?", options: ["Pay would be reduced slightly", "All teams had to take Friday off", "Productivity had to stay at roughly the same level"], answer: 2 },
      { q: "According to the researcher, who benefited less from the shorter week?", options: ["Drivers", "Office staff", "Team leaders"], answer: 0 },
      { q: "What is the main message of the final paragraph?", options: ["The four-day week will soon become law", "Organisations should be open to rethinking how they work", "Healthcare should adopt the four-day week immediately"], answer: 1 }
    ] },

  { id: "r12", title: "The Recipe Notebook", trTitle: "Tarif Defteri", cefr: "B2", icon: "📓", kind: "Hikâye",
    paragraphs: [
      ["Selin had only gone to the Sunday flea market to buy a lamp. She left an hour later without a lamp but with a battered notebook that had cost her less than a cup of coffee. The seller, a bored teenager minding his uncle's stall, had no idea where it had come from. It was bound in faded green cloth, its corners soft with age, and when she opened it, a faint smell of cinnamon seemed to rise from the pages.", "Selin pazar günkü bit pazarına sadece bir lamba almak için gitmişti. Bir saat sonra lambasız ama ona bir fincan kahveden daha ucuza mal olmuş yıpranmış bir defterle ayrıldı. Amcasının tezgâhına bakan canı sıkkın bir genç olan satıcının defterin nereden geldiği hakkında hiçbir fikri yoktu. Defter solmuş yeşil bir kumaşla ciltlenmişti, köşeleri yıllardan yumuşamıştı ve Selin onu açtığında sayfalardan hafif bir tarçın kokusu yükseliyor gibiydi."],
      ["Inside, written in neat blue handwriting, were recipes. Dozens of them, each one dated, some with small drawings of the finished dish in the margins. The earliest entry was more than forty years old, and the handwriting changed subtly over the decades, becoming larger and shakier towards the end. On the inside cover, someone had written a name, Miriam Okafor, and the name of a street Selin vaguely recognised, on the other side of the city.", "İçinde, düzgün mavi bir el yazısıyla yazılmış tarifler vardı. Düzinelercesi, her biri tarihli, bazılarının kenar boşluklarında yemeğin bitmiş hâlinin küçük çizimleri vardı. En eski kayıt kırk yıldan daha eskiydi ve el yazısı on yıllar boyunca belli belirsiz değişmiş, sona doğru daha büyük ve daha titrek bir hâl almıştı. İç kapağa biri bir isim, Miriam Okafor, ve Selin'in belli belirsiz tanıdığı, şehrin öbür ucundaki bir sokağın adını yazmıştı."],
      ["What caught her attention, though, were the notes beneath each recipe. 'Too much sugar, Mum would have laughed at me.' 'Made this for Daniel's birthday, he asked for seconds.' 'Tried it again without her, it was not the same.' Selin read the whole notebook that evening, sitting on her kitchen floor. She had the uncomfortable feeling of reading someone's diary, and yet she could not stop. Each recipe seemed to carry a small piece of somebody's life.", "Ama dikkatini asıl çeken, her tarifin altındaki notlardı. 'Şeker fazla oldu, annem görse bana gülerdi.' 'Daniel'ın doğum günü için yaptım, bir tabak daha istedi.' 'Onsuz bir kez daha denedim, aynı olmadı.' Selin o akşam mutfağının zemininde oturarak defterin tamamını okudu. Birinin günlüğünü okuyormuş gibi rahatsız edici bir his vardı içinde, yine de duramıyordu. Her tarif, birinin hayatından küçük bir parça taşıyor gibiydi."],
      ["The next weekend, feeling slightly ridiculous, she took the bus to the street on the inside cover. She had no house number, so she asked in a small bakery on the corner whether anyone knew the name. The woman behind the counter went very still. Then she called towards the kitchen, and a man in his fifties came out, wiping flour from his hands. His name, it turned out, was Daniel.", "Ertesi hafta sonu, kendini biraz gülünç hissederek iç kapakta yazan sokağa otobüsle gitti. Kapı numarası yoktu, bu yüzden köşedeki küçük bir fırına girip bu ismi bilen olup olmadığını sordu. Tezgâhın arkasındaki kadın donup kaldı. Sonra mutfağa doğru seslendi ve ellerindeki unu silerek ellili yaşlarında bir adam dışarı çıktı. Adının Daniel olduğu ortaya çıktı."],
      ["Miriam had been his mother. She had died two years earlier, and during the chaos of clearing her flat, a box of old books had been given away by mistake. Daniel had searched every charity shop in the neighbourhood for the notebook and had eventually given up. He turned the pages slowly, without speaking, and Selin pretended to study the bread on the shelves so that he would not feel watched.", "Miriam onun annesiydi. İki yıl önce ölmüştü ve dairesini boşaltmanın karmaşası sırasında bir kutu eski kitap yanlışlıkla başkasına verilmişti. Daniel defteri bulmak için mahalledeki bütün yardım mağazalarını aramış ve sonunda pes etmişti. Hiç konuşmadan sayfaları yavaşça çevirdi, Selin de izlendiğini hissetmesin diye raflardaki ekmekleri inceliyormuş gibi yaptı."],
      ["He refused to let her leave without a paper bag of small biscuits, made, he said, from the recipe on page thirty-seven. For weeks afterwards, Selin kept thinking about that afternoon. What she remembered most was the taste of the biscuit, sweet and slightly spicy, and something Daniel had said almost to himself, that recipes are just instructions until someone you love makes them. That same night, she called her own grandmother and asked her to teach her how to cook something.", "Otuz yedinci sayfadaki tariften yapıldığını söylediği küçük kurabiyelerle dolu bir kese kâğıdı almadan gitmesine izin vermedi. Sonraki haftalar boyunca Selin o öğleden sonrayı düşünüp durdu. En çok hatırladığı şey, kurabiyenin tatlı ve hafif baharatlı tadı ve Daniel'ın neredeyse kendi kendine söylediği bir sözdü. Tarifler, sevdiğin biri onları yapana kadar sadece talimattır. Selin aynı gece kendi büyükannesini aradı ve ondan bir şey pişirmeyi öğretmesini istedi."]
    ],
    glossary: [["flea market", "bit pazarı"], ["battered", "yıpranmış"], ["minding", "göz kulak olan, bakan"], ["faded", "solmuş"], ["subtly", "belli belirsiz, ince bir şekilde"], ["shakier", "daha titrek"], ["vaguely", "belli belirsiz"], ["ridiculous", "gülünç"], ["went very still", "donup kaldı"], ["charity shop", "yardım mağazası"], ["flour", "un"]],
    questions: [
      { q: "Why did Selin go to the flea market?", options: ["To buy a lamp", "To sell old books", "To meet her grandmother"], answer: 0 },
      { q: "What did Selin find on the inside cover of the notebook?", options: ["A phone number", "A name and a street", "A photograph"], answer: 1 },
      { q: "How had the notebook ended up at the market?", options: ["Daniel had sold it for money", "Miriam had given it to the seller", "It was given away by mistake after Miriam died"], answer: 2 },
      { q: "What did Selin do at the end of the story?", options: ["She opened her own bakery", "She asked her grandmother to teach her to cook", "She bought another notebook"], answer: 1 }
    ] },

  { id: "r13", title: "Bees on the Rooftop", trTitle: "Çatıdaki Arılar", cefr: "B2", icon: "🐝", kind: "Röportaj",
    paragraphs: [
      ["Defne Arslan spent ten years working as an accountant before she swapped spreadsheets for beehives. Today she looks after twelve colonies on the rooftops of office buildings across the city, and she runs workshops for people who want to start keeping bees themselves. We met her on a windy roof, surrounded by the low hum of thousands of insects, to ask how she ended up here.", "Defne Arslan, elektronik tabloları arı kovanlarıyla değiştirmeden önce on yıl muhasebeci olarak çalıştı. Bugün şehrin dört bir yanındaki ofis binalarının çatılarında on iki arı kolonisine bakıyor ve kendi arısını beslemeye başlamak isteyenler için atölyeler düzenliyor. Onunla binlerce böceğin alçak vızıltısıyla çevrili rüzgârlı bir çatıda buluştuk ve buraya nasıl geldiğini sorduk."],
      ["So how does an accountant become a beekeeper? 'Slowly, and then all at once,' she laughs. 'I took a weekend course just for fun, because I was burnt out and needed something that had nothing to do with numbers. By the end of the second day, I was hooked. I kept my job for another two years, but every lunch break I was reading about bees. Eventually I realised I was living two lives, and only one of them made me happy.'", "Peki bir muhasebeci nasıl arıcı olur? 'Önce yavaş yavaş, sonra bir anda' diye gülüyor. 'Sırf eğlence olsun diye bir hafta sonu kursuna katıldım, çünkü tükenmiştim ve sayılarla hiç ilgisi olmayan bir şeye ihtiyacım vardı. İkinci günün sonunda bağımlı olmuştum. İşimi iki yıl daha sürdürdüm ama her öğle arasında arılar hakkında okuyordum. Sonunda iki hayat yaşadığımı ve bunlardan sadece birinin beni mutlu ettiğini fark ettim.'"],
      ["Isn't the city a strange place to keep bees? 'People assume so, but urban bees often do surprisingly well,' she explains. 'Cities have parks, gardens, balconies and trees along the streets, and many of them use fewer pesticides than intensive farms. The variety of flowers can actually be greater than in the countryside. The challenge is not food, it's space, and convincing building managers that a box full of bees on the roof is not a disaster waiting to happen.'", "Şehir arı beslemek için tuhaf bir yer değil mi? 'İnsanlar öyle sanıyor ama şehir arıları çoğu zaman şaşırtıcı derecede iyi durumda' diye açıklıyor. 'Şehirlerde parklar, bahçeler, balkonlar ve sokak boyunca ağaçlar var ve birçoğu yoğun tarım yapılan çiftliklerden daha az böcek ilacı kullanıyor. Çiçek çeşitliliği aslında kırsaldakinden bile fazla olabiliyor. Zorluk yiyecek değil, alan ve bina yöneticilerini çatıdaki arı dolu bir kutunun gerçekleşmeyi bekleyen bir felaket olmadığına ikna etmek.'"],
      ["How do the people working in these buildings react? 'At first, there's usually some nervousness,' Defne admits. 'Someone always asks what happens if the bees escape into the office. But honeybees are not aggressive unless they feel threatened, and they are far more interested in flowers than in people. After a few months, the attitude changes completely. Staff start asking when the honey will be ready, and some of them even volunteer to help during the harvest.'", "Bu binalarda çalışan insanlar nasıl tepki veriyor? 'İlk başta genellikle biraz tedirginlik oluyor' diye kabul ediyor Defne. 'Mutlaka biri arılar ofise kaçarsa ne olacağını soruyor. Ama bal arıları tehdit altında hissetmedikçe saldırgan değildir ve çiçeklerle insanlardan çok daha fazla ilgilenirler. Birkaç ay sonra tavır tamamen değişiyor. Çalışanlar balın ne zaman hazır olacağını sormaya başlıyor, hatta bazıları hasat sırasında yardım etmek için gönüllü oluyor.'"],
      ["Is urban beekeeping actually good for the environment? Here she becomes more careful. 'It depends. Honeybees are only one species among hundreds of wild bees, and if too many hives are placed in one area, they can compete with wild pollinators for food. That's why I always tell people that planting flowers is more important than keeping bees. A beehive on a roof with nothing growing nearby is not helping anyone.'", "Şehir arıcılığı çevre için gerçekten iyi mi? Burada daha dikkatli konuşuyor. 'Duruma göre değişir. Bal arıları yüzlerce yabani arı türü arasında sadece bir tür ve bir bölgeye çok fazla kovan yerleştirilirse yiyecek için yabani tozlayıcılarla rekabet edebilirler. Bu yüzden insanlara her zaman çiçek dikmenin arı beslemekten daha önemli olduğunu söylüyorum. Yakınında hiçbir şey yetişmeyen bir çatıdaki arı kovanı kimseye yardım etmiyor.'"],
      ["What advice would you give someone thinking of starting? 'Take a proper course, find a mentor and be patient,' she says without hesitation. 'Your first year will probably be a mess. You will get stung, you might lose a colony, and you will definitely make mistakes. But you will also learn to pay attention in a way you never have before, to the weather, the seasons, the smell of the air. For me, that has been the real gift.'", "Başlamayı düşünen birine ne tavsiye edersiniz? 'Düzgün bir kursa katılın, bir akıl hocası bulun ve sabırlı olun' diyor hiç tereddüt etmeden. 'İlk yılınız muhtemelen karmakarışık geçecek. Sokulacaksınız, belki bir koloni kaybedeceksiniz ve kesinlikle hatalar yapacaksınız. Ama aynı zamanda daha önce hiç yapmadığınız bir şekilde dikkat etmeyi öğreneceksiniz. Havaya, mevsimlere, havanın kokusuna. Benim için asıl hediye bu oldu.'"]
    ],
    glossary: [["swapped", "değiştirdi, takas etti"], ["colonies", "koloniler"], ["hum", "vızıltı, uğultu"], ["burnt out", "tükenmiş"], ["hooked", "bağımlı, kapılmış"], ["pesticides", "böcek ilaçları"], ["intensive", "yoğun"], ["threatened", "tehdit altında"], ["volunteer", "gönüllü olmak"], ["harvest", "hasat"], ["pollinators", "tozlayıcılar"], ["without hesitation", "tereddüt etmeden"]],
    questions: [
      { q: "Why did Defne first take a beekeeping course?", options: ["She wanted to change careers immediately", "She was exhausted and wanted a break from numbers", "Her company paid for it"], answer: 1 },
      { q: "According to Defne, what is the main challenge of keeping bees in the city?", options: ["Finding space and persuading building managers", "Finding enough food for the bees", "Dealing with air pollution"], answer: 0 },
      { q: "Why does she say planting flowers is more important than keeping bees?", options: ["Because flowers are easier to sell", "Because honeybees are dangerous to people", "Because too many hives can compete with wild bees for food"], answer: 2 },
      { q: "What does she consider the real gift of beekeeping?", options: ["Earning money from honey", "Learning to pay close attention to the natural world", "Becoming well known in the city"], answer: 1 }
    ] },

  { id: "r14", title: "Why I Stopped Saying I'm Busy", trTitle: "Neden Meşgulüm Demeyi Bıraktım", cefr: "B2", icon: "⏳", kind: "Blog",
    paragraphs: [
      ["For years, my answer to the question 'How are you?' was always the same. 'Busy,' I would say, often with a tired smile that was meant to suggest I was coping heroically with an impossible workload. It took me an embarrassingly long time to notice that everyone around me was saying exactly the same thing, and that none of us seemed particularly happy about it.", "Yıllarca 'Nasılsın?' sorusuna cevabım hep aynıydı. 'Meşgulüm' derdim, çoğu zaman imkânsız bir iş yüküyle kahramanca başa çıktığımı ima etmesi gereken yorgun bir gülümsemeyle. Etrafımdaki herkesin tam olarak aynı şeyi söylediğini ve hiçbirimizin bundan pek mutlu görünmediğini fark etmem utanç verici derecede uzun sürdü."],
      ["At some point, busyness stopped being a description and became a kind of status symbol. Saying you are busy implies that you are needed, important and in demand. Admitting that you had a relaxed week, on the other hand, can sound almost lazy, as if you are not trying hard enough. I realised that I was sometimes exaggerating how busy I was, simply because I did not want to seem less committed than my colleagues.", "Bir noktada meşguliyet bir tanım olmaktan çıktı ve bir tür statü sembolüne dönüştü. Meşgul olduğunu söylemek, sana ihtiyaç duyulduğunu, önemli ve aranan biri olduğunu ima eder. Öte yandan rahat bir hafta geçirdiğini itiraf etmek neredeyse tembellik gibi, yeterince çabalamıyormuşsun gibi gelebilir. Bazen sırf meslektaşlarımdan daha az kendini işine adamış görünmek istemediğim için ne kadar meşgul olduğumu abarttığımı fark ettim."],
      ["The problem is that words shape the way we think. The more often I described my life as busy, the more I experienced it that way. Even on calm days, I felt a vague sense of pressure, as though I ought to be doing something more productive. My weekends were packed with plans I had not really wanted to make, and I almost never allowed myself to simply sit and do nothing without feeling guilty.", "Sorun şu ki kelimeler düşünme biçimimizi şekillendirir. Hayatımı ne kadar sık meşgul olarak tanımladıysam, onu o kadar öyle yaşadım. Sakin günlerde bile, daha üretken bir şey yapmam gerekiyormuş gibi belirsiz bir baskı hissediyordum. Hafta sonlarım aslında yapmak istemediğim planlarla doluydu ve kendime suçluluk duymadan oturup hiçbir şey yapmama neredeyse hiç izin vermiyordum."],
      ["So, about six months ago, I made a small decision. I would stop using the word busy, at least out loud. When people asked how I was, I had to come up with an honest answer instead. Sometimes it was 'tired but fine', sometimes 'quite happy, actually', and occasionally 'overwhelmed, to be honest'. It was surprisingly difficult at first. The word kept slipping out automatically, like a reflex I had trained for years.", "Bu yüzden yaklaşık altı ay önce küçük bir karar verdim. Meşgul kelimesini en azından yüksek sesle kullanmayı bırakacaktım. İnsanlar nasıl olduğumu sorduğunda onun yerine dürüst bir cevap bulmam gerekiyordu. Bazen 'yorgun ama iyiyim', bazen 'aslında oldukça mutluyum', ara sıra da 'açıkçası bunalmış durumdayım' oldu. İlk başta şaşırtıcı derecede zordu. Kelime, yıllarca çalıştırdığım bir refleks gibi otomatik olarak ağzımdan kaçıp duruyordu."],
      ["What changed? More than I expected. Conversations became more genuine, because a real answer tends to invite a real response. A colleague I had barely spoken to admitted that she was struggling with her workload, and we ended up helping each other. I also started to notice which of my commitments genuinely mattered to me and which ones I had accepted out of habit or fear of saying no.", "Ne değişti? Beklediğimden fazlası. Sohbetler daha samimi hâle geldi, çünkü gerçek bir cevap genellikle gerçek bir karşılığı davet eder. Neredeyse hiç konuşmadığım bir meslektaşım iş yüküyle zorlandığını itiraf etti ve sonunda birbirimize yardım ettik. Ayrıca hangi taahhütlerimin benim için gerçekten önemli olduğunu, hangilerini alışkanlıktan ya da hayır deme korkusundan kabul ettiğimi fark etmeye başladım."],
      ["I am not claiming that dropping one word has transformed my life. I still have deadlines, and some weeks are genuinely exhausting. But I no longer wear my exhaustion like a badge. If you try this experiment yourself, I suspect you will find, as I did, that being busy and being fulfilled are not the same thing, and that the gap between them is worth paying attention to.", "Tek bir kelimeyi bırakmanın hayatımı değiştirdiğini iddia etmiyorum. Hâlâ teslim tarihlerim var ve bazı haftalar gerçekten yorucu. Ama artık yorgunluğumu bir rozet gibi taşımıyorum. Bu deneyi siz de denerseniz, sanırım benim gibi meşgul olmakla tatmin olmuş olmanın aynı şey olmadığını ve aralarındaki farkın dikkat etmeye değer olduğunu göreceksiniz."]
    ],
    glossary: [["coping", "başa çıkmak"], ["workload", "iş yükü"], ["embarrassingly", "utanç verici derecede"], ["status symbol", "statü sembolü"], ["exaggerating", "abartmak"], ["committed", "kendini adamış"], ["vague", "belirsiz"], ["guilty", "suçlu"], ["overwhelmed", "bunalmış"], ["reflex", "refleks"], ["genuine", "samimi, gerçek"], ["badge", "rozet"]],
    questions: [
      { q: "Why does the writer think people say they are busy?", options: ["Because it makes them sound important and committed", "Because they are always genuinely overworked", "Because their managers ask them to"], answer: 0 },
      { q: "How did using the word busy affect the writer?", options: ["It made the writer more productive", "It made the writer feel pressured even on calm days", "It helped the writer plan better weekends"], answer: 1 },
      { q: "What happened when the writer gave more honest answers?", options: ["People stopped talking to the writer", "The writer lost a job", "Conversations became more genuine"], answer: 2 },
      { q: "Which statement best matches the writer's conclusion?", options: ["Being busy and being fulfilled are different things", "Everyone should work fewer hours", "Deadlines are no longer a problem for the writer"], answer: 0 }
    ] },

  { id: "r15", title: "Why Dreams Slip Away", trTitle: "Rüyalar Neden Elimizden Kayıp Gider", cefr: "B2", icon: "🌙", kind: "Makale",
    paragraphs: [
      ["Most of us have had the experience of waking up from a vivid dream, certain that we will remember every detail, only to find that it has vanished completely by the time we have brushed our teeth. This frustrating phenomenon is so common that many people assume they simply do not dream very much. In reality, researchers believe that almost everyone dreams several times a night. The question is not why we dream, but why we forget so quickly.", "Çoğumuz canlı bir rüyadan uyanıp her ayrıntısını hatırlayacağımızdan emin olduğumuz, ama dişlerimizi fırçaladığımızda rüyanın tamamen kaybolduğunu fark ettiğimiz bir deneyim yaşamışızdır. Bu sinir bozucu olgu o kadar yaygındır ki birçok insan pek rüya görmediğini varsayar. Gerçekte araştırmacılar, neredeyse herkesin gecede birkaç kez rüya gördüğüne inanıyor. Soru neden rüya gördüğümüz değil, neden bu kadar çabuk unuttuğumuz."],
      ["One explanation involves the chemistry of the sleeping brain. During the stage of sleep in which the most vivid dreams tend to occur, levels of certain chemicals that help the brain store new memories are thought to be unusually low. In other words, the brain is busy creating experiences, but it is not fully recording them. It is a little like watching a film while the camera that should be filming it has been switched off.", "Açıklamalardan biri uyuyan beynin kimyasıyla ilgili. En canlı rüyaların görülme eğiliminde olduğu uyku evresinde, beynin yeni anıları depolamasına yardımcı olan bazı kimyasalların seviyelerinin alışılmadık derecede düşük olduğu düşünülüyor. Başka bir deyişle beyin deneyimler yaratmakla meşgul ama onları tam olarak kaydetmiyor. Bu biraz, onu kaydetmesi gereken kamera kapalıyken bir film izlemeye benziyor."],
      ["Another factor is attention. Dreams are often illogical, jumping from one scene to another without any clear story. Our memories work best when information is organised and connected to things we already know, so a random sequence of strange events is naturally harder to hold on to. On top of that, the moment we wake up, our attention is usually pulled towards the day ahead, whether it is an alarm, a message or the need for coffee.", "Bir diğer etken dikkat. Rüyalar çoğu zaman mantıksızdır, net bir hikâye olmadan bir sahneden diğerine atlar. Hafızamız en iyi, bilgi düzenli olduğunda ve zaten bildiğimiz şeylere bağlandığında çalışır, bu yüzden tuhaf olayların rastgele bir dizisini akılda tutmak doğal olarak daha zordur. Üstelik uyandığımız anda dikkatimiz genellikle önümüzdeki güne çekilir, ister bir alarm, ister bir mesaj, ister kahve ihtiyacı olsun."],
      ["Interestingly, people who wake up frequently during the night tend to remember more of their dreams. Some scientists suggest that this is because brief periods of wakefulness give the brain a chance to transfer fragments of a dream into longer-term memory. This may help explain why light sleepers often report more dreams than those who sleep deeply through the night, even if both groups actually dream about the same amount.", "İlginçtir ki gece sık sık uyanan insanlar rüyalarının daha fazlasını hatırlama eğiliminde. Bazı bilim insanları bunun, kısa uyanıklık dönemlerinin beyne bir rüyanın parçalarını uzun süreli belleğe aktarma fırsatı vermesinden kaynaklandığını öne sürüyor. Bu, her iki grup da aslında yaklaşık aynı miktarda rüya görse bile, hafif uyuyanların neden gece boyunca derin uyuyanlardan daha fazla rüya bildirdiğini açıklamaya yardımcı olabilir."],
      ["If you would like to remember your dreams more often, there are a few simple techniques worth trying. Keep a notebook next to your bed and write down anything you can recall as soon as you wake up, before checking your phone. Try to stay still for a minute with your eyes closed, since moving can disrupt fragile memories. Over time, many people find that simply paying attention to their dreams makes them easier to remember.", "Rüyalarınızı daha sık hatırlamak istiyorsanız denemeye değer birkaç basit teknik var. Yatağınızın yanında bir defter bulundurun ve uyanır uyanmaz, telefonunuza bakmadan önce hatırlayabildiğiniz her şeyi yazın. Gözleriniz kapalı bir dakika kıpırdamadan durmaya çalışın, çünkü hareket etmek kırılgan anıları bozabilir. Zamanla birçok insan, rüyalarına sadece dikkat etmenin onları hatırlamayı kolaylaştırdığını fark ediyor."],
      ["Whether remembering dreams is actually useful remains an open question. Some people find that their dreams offer creative ideas or help them process emotions, while others are perfectly happy to forget them. Either way, the fact that our nightly adventures disappear so easily is not a sign that something is wrong. It is simply one more reminder of how much of our mental life takes place beyond the reach of our conscious awareness.", "Rüyaları hatırlamanın gerçekten yararlı olup olmadığı hâlâ açık bir soru. Bazı insanlar rüyalarının yaratıcı fikirler sunduğunu ya da duygularını işlemelerine yardım ettiğini düşünürken, diğerleri onları unutmaktan gayet memnun. Her iki durumda da gece maceralarımızın bu kadar kolay kaybolması bir şeylerin yanlış gittiğinin işareti değil. Bu sadece zihinsel hayatımızın ne kadar büyük bir kısmının bilinçli farkındalığımızın erişiminin ötesinde gerçekleştiğinin bir hatırlatıcısı daha."]
    ],
    glossary: [["vivid", "canlı"], ["vanished", "kaybolmuş"], ["phenomenon", "olgu, fenomen"], ["illogical", "mantıksız"], ["sequence", "dizi, sıra"], ["wakefulness", "uyanıklık"], ["fragments", "parçalar"], ["recall", "hatırlamak"], ["disrupt", "bozmak"], ["fragile", "kırılgan"], ["conscious awareness", "bilinçli farkındalık"]],
    questions: [
      { q: "What do researchers believe about how often people dream?", options: ["Only a few people dream every night", "Almost everyone dreams several times a night", "Most people dream once a week"], answer: 1 },
      { q: "What comparison does the article use to explain the brain's chemistry during dreams?", options: ["A camera that is switched off while a film plays", "A computer that has crashed", "A library with no books"], answer: 0 },
      { q: "Why might light sleepers remember more dreams?", options: ["They dream much more than deep sleepers", "They eat less before going to bed", "Brief periods of waking help move dream fragments into memory"], answer: 2 },
      { q: "Which technique is NOT mentioned in the article?", options: ["Keeping a notebook by the bed", "Staying still with your eyes closed", "Taking a sleeping pill"], answer: 2 }
    ] },

  { id: "r16", title: "The Wood Wide Web, Revisited", trTitle: "Orman Ağı Efsanesine Yeniden Bakış", cefr: "C1", icon: "🍄", kind: "Makale",
    paragraphs: [
      ["Few scientific ideas have captured the public imagination quite as thoroughly as the notion that trees talk to one another. According to the popular version of the story, forests are interconnected by vast underground networks of fungi, through which mature trees nourish their offspring, warn their neighbours of approaching insects and even sacrifice themselves for the common good. It is an irresistibly poetic picture, one that has inspired documentaries, bestselling books and countless conversations on woodland walks. The trouble, as a growing number of researchers are pointing out, is that the evidence for much of it is considerably thinner than its popularity would suggest.", "Çok az bilimsel fikir, ağaçların birbiriyle konuştuğu düşüncesi kadar kamuoyunun hayal gücünü derinden yakalamıştır. Hikâyenin popüler versiyonuna göre ormanlar, devasa yeraltı mantar ağlarıyla birbirine bağlıdır. Olgun ağaçlar bu ağlar aracılığıyla yavrularını besler, komşularını yaklaşan böceklere karşı uyarır, hatta ortak iyilik için kendilerini feda eder. Bu karşı konulmaz derecede şiirsel bir tablo ve belgesellere, çok satan kitaplara ve orman yürüyüşlerinde yapılan sayısız sohbete ilham vermiş durumda. Sorun ise, giderek artan sayıda araştırmacının belirttiği gibi, bu hikâyenin büyük kısmına ilişkin kanıtların popülerliğinin düşündürdüğünden çok daha zayıf olması."],
      ["What is not in dispute is that fungi and plant roots form intimate partnerships. The fine threads of certain fungi wrap around or even penetrate the roots of trees, supplying them with water and minerals scavenged from the soil in exchange for sugars that the trees produce through photosynthesis. This arrangement is ancient, remarkably widespread and, by any reasonable measure, essential to the health of many ecosystems. Without it, a great many plants would struggle to survive on the nutrient-poor soils they currently colonise.", "Tartışma konusu olmayan şey, mantarların ve bitki köklerinin yakın ortaklıklar kurduğudur. Bazı mantarların ince iplikleri ağaç köklerinin etrafına sarılır, hatta köklerin içine girer ve ağaçların fotosentezle ürettiği şekerler karşılığında onlara topraktan toplanmış su ve mineraller sağlar. Bu düzen çok eskidir, dikkat çekici derecede yaygındır ve makul her ölçüye göre birçok ekosistemin sağlığı için vazgeçilmezdir. O olmasaydı, pek çok bitki şu anda yerleştiği besin açısından fakir topraklarda hayatta kalmakta zorlanırdı."],
      ["The leap from this well-established relationship to the image of a cooperative forest internet, however, involves several assumptions that have proved difficult to verify. For a network to function as a channel between trees, the same fungal individual must be connected to multiple trees simultaneously, and resources must demonstrably travel from one tree to another through it rather than through the soil. Demonstrating this in the field, where roots are tangled, fungi are microscopic and conditions vary from one square metre to the next, is extraordinarily challenging.", "Ne var ki bu sağlam biçimde kanıtlanmış ilişkiden işbirlikçi bir orman internetine sıçramak, doğrulanması zor olduğu ortaya çıkmış birkaç varsayım içeriyor. Bir ağın ağaçlar arasında bir kanal işlevi görebilmesi için aynı mantar bireyinin aynı anda birden fazla ağaca bağlı olması ve kaynakların topraktan değil, bu mantar üzerinden bir ağaçtan diğerine gittiğinin kanıtlanabilmesi gerekir. Köklerin birbirine dolandığı, mantarların mikroskobik olduğu ve koşulların bir metrekareden diğerine değiştiği arazide bunu göstermek olağanüstü derecede zordur."],
      ["Several of the most frequently cited experiments, critics argue, were conducted on a small scale, under artificial conditions, or with methods that cannot entirely rule out alternative explanations. In some cases, a modest transfer of carbon between seedlings has been interpreted as evidence of deliberate sharing, when it might equally reflect the fungus serving its own interests. A fungus, after all, is not a neutral cable but a living organism with its own needs, and it would be surprising if it distributed resources purely for the benefit of the trees it happens to be attached to.", "Eleştirmenlere göre en sık atıfta bulunulan deneylerin birçoğu küçük ölçekte, yapay koşullar altında ya da alternatif açıklamaları tamamen dışlayamayan yöntemlerle yapıldı. Bazı durumlarda fideler arasındaki mütevazı bir karbon aktarımı bilinçli bir paylaşımın kanıtı olarak yorumlandı, oysa bu aynı ölçüde mantarın kendi çıkarına hizmet etmesini de yansıtıyor olabilir. Ne de olsa mantar tarafsız bir kablo değil, kendi ihtiyaçları olan canlı bir organizmadır ve kaynakları yalnızca tesadüfen bağlı olduğu ağaçların yararına dağıtsaydı bu şaşırtıcı olurdu."],
      ["None of this means that the original researchers were acting in bad faith, nor that underground networks are irrelevant. Rather, the controversy illustrates how a nuanced and provisional finding can harden into accepted fact once it escapes the laboratory. Popular science thrives on compelling narratives, and the image of a nurturing mother tree is far more memorable than a carefully hedged statement about statistically significant isotope ratios. Over time, the caveats tend to fall away, and what remains is a story that feels true precisely because it has been repeated so often.", "Bunların hiçbiri ilk araştırmacıların kötü niyetle hareket ettiği ya da yeraltı ağlarının önemsiz olduğu anlamına gelmiyor. Daha çok bu tartışma, incelikli ve geçici bir bulgunun laboratuvardan çıktıktan sonra nasıl kabul görmüş bir gerçeğe dönüşerek katılaşabildiğini gösteriyor. Popüler bilim etkileyici anlatılarla beslenir ve besleyip büyüten bir anne ağaç imgesi, istatistiksel olarak anlamlı izotop oranları hakkında dikkatle sınırlandırılmış bir ifadeden çok daha akılda kalıcıdır. Zamanla çekinceler düşüp gider ve geriye tam da bu kadar sık tekrarlandığı için doğru gibi gelen bir hikâye kalır."],
      ["There is also a subtler concern. Framing forests as harmonious communities of altruistic individuals risks projecting human values onto processes that are, in many respects, indifferent to them. Competition, after all, is as much a feature of a forest as cooperation, and trees routinely shade out, outgrow and starve their neighbours. A more accurate picture might be messier and less comforting, but it would arguably be more fascinating, revealing ecosystems as dynamic arenas of negotiation rather than idealised families.", "Daha ince bir kaygı da var. Ormanları özgeci bireylerden oluşan uyumlu topluluklar olarak çerçevelemek, birçok açıdan insani değerlere kayıtsız olan süreçlere bu değerleri yansıtma riski taşıyor. Ne de olsa rekabet de işbirliği kadar ormanın bir özelliğidir ve ağaçlar komşularını rutin olarak gölgede bırakır, onlardan hızlı büyür ve onları besinsiz bırakır. Daha doğru bir tablo daha karmaşık ve daha az teselli edici olabilir, ama ekosistemleri idealize edilmiş aileler yerine dinamik pazarlık alanları olarak ortaya koyarak tartışmasız daha büyüleyici olurdu."],
      ["Ultimately, the debate is a useful reminder that science advances not by accumulating pleasing stories but by subjecting them to relentless scrutiny. The fungal networks beneath our feet are undeniably real and undeniably important. Whether they amount to a forest-wide system of communication remains, for now, an open question, and perhaps that uncertainty is itself worth celebrating. It leaves room for future research to surprise us, which is, in the end, what good science is supposed to do.", "Sonuçta bu tartışma, bilimin hoşa giden hikâyeler biriktirerek değil, onları amansız bir incelemeye tabi tutarak ilerlediğini gösteren faydalı bir hatırlatma. Ayaklarımızın altındaki mantar ağları inkâr edilemez biçimde gerçek ve inkâr edilemez biçimde önemli. Bunların orman çapında bir iletişim sistemi oluşturup oluşturmadığı ise şimdilik açık bir soru ve belki de bu belirsizliğin kendisi kutlanmaya değer. Gelecekteki araştırmaların bizi şaşırtmasına alan bırakıyor ki sonuçta iyi bilimin yapması gereken de budur."]
    ],
    glossary: [["nourish", "beslemek"], ["irresistibly", "karşı konulmaz biçimde"], ["scavenged", "toplanmış, arayıp bulunmuş"], ["verify", "doğrulamak"], ["simultaneously", "aynı anda"], ["rule out", "olasılık dışı bırakmak"], ["in bad faith", "kötü niyetle"], ["nuanced", "incelikli, nüanslı"], ["provisional", "geçici"], ["caveats", "çekinceler"], ["altruistic", "özgeci, diğerkâm"], ["relentless scrutiny", "amansız inceleme"]],
    questions: [
      { q: "What does the writer accept as well established?", options: ["Trees deliberately warn each other of danger", "Fungi and tree roots form mutually beneficial partnerships", "Mother trees feed their offspring through the soil"], answer: 1 },
      { q: "Why is it difficult to prove the existence of a forest network in the field?", options: ["Researchers lack funding for long-term studies", "Fungi can only grow in laboratories", "Roots are tangled, fungi are microscopic and conditions vary greatly"], answer: 2 },
      { q: "What point does the writer make about fungi in the fourth paragraph?", options: ["They have their own interests and may not act purely for the trees", "They are neutral channels that simply pass resources along", "They are harmful to young seedlings"], answer: 0 },
      { q: "What is the writer's attitude towards the remaining uncertainty?", options: ["Frustrated, because it undermines ecology", "Dismissive, because the idea has been disproved", "Positive, because it leaves room for future discoveries"], answer: 2 }
    ] },

  { id: "r17", title: "In Praise of Doing Things Badly", trTitle: "Bir Şeyi Kötü Yapmanın Övgüsü", cefr: "C1", icon: "🎨", kind: "Blog",
    paragraphs: [
      ["Somewhere along the way, we seem to have collectively forgotten that it is perfectly acceptable to be mediocre at things. I was reminded of this recently when a friend confessed, with a degree of embarrassment usually reserved for far graver admissions, that she had abandoned the piano after only three months. She had not given up because she disliked playing. She had given up because she was not improving quickly enough to justify, in her own eyes, the hours she was putting in.", "Yol boyunca bir yerde, bir şeylerde vasat olmanın gayet kabul edilebilir olduğunu topluca unutmuş gibiyiz. Bunu yakın zamanda bir arkadaşım, genellikle çok daha ciddi itiraflara özgü bir mahcubiyetle, sadece üç ay sonra piyanoyu bıraktığını itiraf ettiğinde hatırladım. Çalmayı sevmediği için bırakmamıştı. Kendi gözünde harcadığı saatleri haklı çıkaracak kadar hızlı gelişmediği için bırakmıştı."],
      ["Her reasoning struck me as both entirely understandable and deeply symptomatic of the age we live in. We are surrounded, to an unprecedented degree, by evidence of other people's excellence. A few minutes of scrolling will reveal teenagers performing flawless concertos, amateur bakers producing cakes of architectural complexity and weekend runners casually completing ultramarathons. Against such a backdrop, the ordinary experience of being a clumsy beginner can feel not merely humbling but faintly humiliating, as though one's struggles were a public failure rather than a private process.", "Onun mantığı bana hem tamamen anlaşılır hem de içinde yaşadığımız çağın derin bir belirtisi gibi geldi. Eşi görülmemiş ölçüde başkalarının mükemmelliğinin kanıtlarıyla çevriliyiz. Birkaç dakika ekranı kaydırmak, kusursuz konçertolar çalan gençleri, mimari karmaşıklıkta pastalar yapan amatör pastacıları ve ultramaratonları kolayca bitiren hafta sonu koşucularını gözler önüne serer. Böyle bir arka plan karşısında beceriksiz bir acemi olmanın sıradan deneyimi sadece alçakgönüllü kılıcı değil, hafiften aşağılayıcı da gelebilir, sanki insanın çabaları özel bir süreç değil de herkesin önünde yaşanan bir başarısızlıkmış gibi."],
      ["Compounding this is the relentless pressure to monetise or optimise our leisure. Hobbies, once valued precisely because they served no particular purpose, are increasingly framed as opportunities for self-improvement, personal branding or, failing that, a modest side income. Knitting becomes a potential online shop, sourdough a potential following, jogging a stream of data to be tracked, analysed and compared. Under these conditions, an activity pursued purely for its own sake begins to look almost indulgent, and an activity pursued badly looks like a waste of time.", "Bunu daha da kötüleştiren, boş zamanımızı paraya çevirme ya da optimize etme yönündeki amansız baskı. Bir zamanlar tam da belirli bir amaca hizmet etmedikleri için değer verilen hobiler, giderek kişisel gelişim, kişisel marka oluşturma ya da bu olmazsa mütevazı bir yan gelir fırsatı olarak çerçeveleniyor. Örgü potansiyel bir internet mağazasına, ekşi mayalı ekmek potansiyel bir takipçi kitlesine, koşu da takip edilecek, analiz edilecek ve karşılaştırılacak bir veri akışına dönüşüyor. Bu koşullar altında sırf kendisi için yapılan bir etkinlik neredeyse keyfine düşkünlük gibi, kötü yapılan bir etkinlik ise zaman kaybı gibi görünmeye başlıyor."],
      ["Yet there is something profoundly liberating about doing a thing for no reason other than that one enjoys it, and doing it without any expectation of mastery. When I took up painting a few years ago, my early efforts were, to put it charitably, unremarkable. They remain so. But the hours I spend at the easel are among the few in my week when I am not measuring myself against anyone, including my own former self. The point is not the painting. The point is the absorption, the rare and restorative sensation of losing track of time.", "Yine de bir şeyi sadece hoşa gittiği için ve hiçbir ustalık beklentisi olmadan yapmanın derinden özgürleştirici bir yanı var. Birkaç yıl önce resim yapmaya başladığımda ilk denemelerim, kibar bir ifadeyle, sıradandı. Hâlâ da öyleler. Ama şövalenin başında geçirdiğim saatler, haftamda kendimi kimseyle, eski hâlim de dâhil, kıyaslamadığım nadir anlar arasında. Mesele resim değil. Mesele kendini kaptırmak, zamanın nasıl geçtiğini unutmanın o nadir ve onarıcı hissi."],
      ["I am not suggesting that striving for excellence is misguided, nor that we should abandon discipline altogether. Mastery brings its own deep satisfactions, and those who pursue it deserve admiration. My argument is rather that not every activity needs to be a ladder. Some can simply be a garden, a place to wander around in, tend a little and enjoy without any ambition to reach the top of anything. The danger lies in treating every corner of life as an arena for performance, so that even our rest becomes another form of work.", "Mükemmellik için çabalamanın yanlış olduğunu ya da disiplini tamamen bırakmamız gerektiğini söylemiyorum. Ustalığın kendine özgü derin tatminleri vardır ve onun peşinden gidenler hayranlığı hak eder. Benim savım daha çok, her etkinliğin bir merdiven olmak zorunda olmadığı. Bazıları sadece bir bahçe olabilir, içinde dolaşılacak, biraz bakım yapılacak ve hiçbir şeyin zirvesine ulaşma hırsı olmadan tadı çıkarılacak bir yer. Tehlike, hayatın her köşesini bir performans alanı gibi görmekte yatıyor, öyle ki dinlenmemiz bile başka bir iş biçimine dönüşüyor."],
      ["There is also, I suspect, a quieter benefit to tolerating our own incompetence. Being bad at something, and continuing anyway, is an exercise in humility that few other experiences can offer adults. It reminds us what it feels like to be a learner, which in turn makes us more patient with others who are struggling. It loosens the grip of perfectionism, a trait that is often mistaken for a virtue but which, in its more extreme forms, can quietly corrode both creativity and wellbeing.", "Sanırım kendi beceriksizliğimize katlanmanın daha sessiz bir faydası da var. Bir şeyde kötü olup yine de devam etmek, yetişkinlere başka pek az deneyimin sunabileceği bir alçakgönüllülük alıştırmasıdır. Bize öğrenci olmanın nasıl bir his olduğunu hatırlatır, bu da zorlanan başkalarına karşı daha sabırlı olmamızı sağlar. Mükemmeliyetçiliğin pençesini gevşetir. Bu özellik çoğu zaman bir erdem sanılır ama uç biçimlerinde hem yaratıcılığı hem de iyi oluşu sessizce aşındırabilir."],
      ["So, to my friend and to anyone else wrestling with a similar dilemma, I would offer a modest proposal. Return to the piano, or whatever it may be, and give yourself explicit permission to be terrible at it. Play the same clumsy melody a hundred times if it pleases you. Nobody is keeping score, and if they are, they are not worth listening to. The world has more than enough experts. What it could use, perhaps, is a few more cheerful amateurs.", "Bu yüzden arkadaşıma ve benzer bir ikilemle boğuşan herkese mütevazı bir öneride bulunmak isterim. Piyanoya ya da her ne ise ona geri dönün ve kendinize onda berbat olma konusunda açık bir izin verin. Hoşunuza gidiyorsa aynı beceriksiz melodiyi yüz kez çalın. Kimse puan tutmuyor, tutan varsa da dinlenmeye değmez. Dünyada fazlasıyla uzman var. Belki de dünyanın ihtiyaç duyduğu şey, birkaç neşeli amatör daha."]
    ],
    glossary: [["mediocre", "vasat"], ["graver", "daha ciddi"], ["symptomatic", "belirtisi olan"], ["unprecedented", "eşi görülmemiş"], ["flawless", "kusursuz"], ["humbling", "alçakgönüllü kılan"], ["monetise", "paraya çevirmek"], ["indulgent", "keyfine düşkün, şımarıkça"], ["charitably", "kibarca, hoşgörüyle"], ["absorption", "kendini kaptırma"], ["incompetence", "beceriksizlik"], ["corrode", "aşındırmak"]],
    questions: [
      { q: "Why did the writer's friend give up the piano?", options: ["She did not enjoy playing it", "She felt she was not improving fast enough to justify the time", "She could not afford lessons any more"], answer: 1 },
      { q: "According to the writer, how does constant exposure to other people's excellence affect beginners?", options: ["It can make being a clumsy beginner feel humiliating", "It provides them with free lessons", "It encourages them to try more hobbies"], answer: 0 },
      { q: "What does the writer mean by saying that not every activity needs to be a ladder?", options: ["Hobbies should be done outdoors", "People should avoid competition at work", "Some activities can be enjoyed without aiming for mastery"], answer: 2 },
      { q: "Which benefit of being bad at something does the writer mention?", options: ["It makes us more patient with other learners", "It helps us earn extra money", "It improves our long-term memory"], answer: 0 }
    ] },

  { id: "r18", title: "The Shifting Coast", trTitle: "Kayan Kıyı", cefr: "C1", icon: "🗺️", kind: "Hikâye",
    paragraphs: [
      ["For forty-one years, Aurelio Brandt had drawn the same stretch of coastline, and for forty-one years it had refused to stay still. Each spring he would walk the cliffs with his notebook and his battered measuring wheel, recording where the land had crumbled into the sea over the winter, and each summer he would sit at the long table by his window and produce a new map, meticulously updated, that nobody had commissioned and almost nobody would ever see.", "Aurelio Brandt kırk bir yıl boyunca aynı kıyı şeridini çizmişti ve kırk bir yıl boyunca kıyı yerinde durmayı reddetmişti. Her bahar defteri ve hırpalanmış ölçüm tekerleğiyle yalıyarları yürür, kış boyunca karanın denize nerelerde ufalanıp döküldüğünü kaydederdi. Her yaz da penceresinin yanındaki uzun masaya oturur, titizlikle güncellenmiş, kimsenin sipariş etmediği ve neredeyse kimsenin göremeyeceği yeni bir harita çıkarırdı."],
      ["His daughter, Ilse, had long regarded this ritual with a mixture of affection and exasperation. She had grown up among his rolled-up charts, had learned to read contour lines before she could reliably read sentences, and had left the village at eighteen with the fierce conviction that she would never again live anywhere that smelled so persistently of salt and damp paper. Now, at forty-three, she found herself driving back along the coast road, summoned by a neighbour's carefully worded phone call suggesting that her father was not managing as well as he claimed.", "Kızı Ilse uzun zamandır bu ritüele sevgi ile bıkkınlık karışımı bir duyguyla bakıyordu. Babasının rulo hâlindeki haritaları arasında büyümüş, cümleleri doğru dürüst okuyamadan eş yükselti eğrilerini okumayı öğrenmiş ve on sekiz yaşında, bir daha asla bu kadar ısrarla tuz ve nemli kâğıt kokan bir yerde yaşamayacağına dair şiddetli bir inançla köyden ayrılmıştı. Şimdi kırk üç yaşında, bir komşunun babasının iddia ettiği kadar iyi idare edemediğini ima eden özenle seçilmiş sözcüklerle yaptığı bir telefon üzerine çağrılmış olarak kendini kıyı yolunda geri dönerken buldu."],
      ["He met her at the door looking smaller than she remembered, though no less stubborn. Over dinner he spoke of the erosion with the animated precision of a man describing a rival he had come to respect. The headland near the old chapel had lost almost three metres since the previous year, he informed her, and the footpath the council had rerouted only a decade earlier was already perilously close to the edge again. She listened, nodding, and tried not to notice the unopened letters piling up on the dresser or the faint tremor in his hand as he poured the tea.", "Onu kapıda karşıladığında hatırladığından daha küçük görünüyordu, ama inatçılığından hiçbir şey kaybetmemişti. Akşam yemeğinde erozyondan, saygı duymaya başladığı bir rakibi anlatan bir adamın coşkulu kesinliğiyle söz etti. Eski şapelin yanındaki burun bir önceki yıldan bu yana neredeyse üç metre kaybetmişti, belediyenin daha on yıl önce güzergâhını değiştirdiği patika da şimdiden yine tehlikeli biçimde kenara yaklaşmıştı. Ilse başını sallayarak dinledi ve büfenin üstünde biriken açılmamış mektupları ya da babası çayı dökerken elindeki hafif titremeyi fark etmemeye çalıştı."],
      ["The following morning she accompanied him on his survey, partly to keep an eye on him and partly, she admitted to herself, out of a curiosity she had spent years pretending not to feel. The wind was ferocious, and twice she had to steady him as he leaned too far over the crumbling rim to take a reading. Yet there was an unmistakable grace in the way he moved across the landscape, pausing, measuring, murmuring figures under his breath, as though the coast were a manuscript he was patiently annotating.", "Ertesi sabah ölçüm turunda ona eşlik etti, kısmen ona göz kulak olmak için, kısmen de kendine itiraf ettiği gibi yıllarca hissetmiyormuş gibi yaptığı bir merakla. Rüzgâr çok sertti ve babası ölçüm almak için ufalanan kenardan fazla eğildiğinde iki kez onu tutup dengelemesi gerekti. Yine de manzara boyunca hareket edişinde, durup ölçüp rakamları mırıldanışında, sanki kıyı sabırla notlar düştüğü bir el yazmasıymış gibi, apaçık bir zarafet vardı."],
      ["That evening, he unrolled the maps for her, all forty-one of them, weighing down the corners with mugs and stones. Laid side by side, they formed something she had never anticipated. What she had always dismissed as an eccentric obsession turned out to be an extraordinarily detailed record of a landscape in retreat, a slow-motion portrait of loss rendered in ink. Fields that had appeared on the earliest maps had simply vanished. A cottage she half remembered from childhood was there in one year and gone the next, reduced to a neat dotted line and a date.", "O akşam haritaların kırk birini de onun için açtı, köşelerine kupalar ve taşlar koydu. Yan yana dizildiklerinde hiç beklemediği bir şey oluşturdular. Her zaman tuhaf bir saplantı diye küçümsediği şey, geri çekilen bir manzaranın olağanüstü ayrıntılı bir kaydı, mürekkeple çizilmiş ağır çekim bir kayıp portresi çıktı. İlk haritalarda görünen tarlalar basbayağı yok olmuştu. Çocukluğundan yarım yamalak hatırladığı bir kulübe bir yıl oradaydı, ertesi yıl gitmişti, düzgün bir noktalı çizgiye ve bir tarihe indirgenmişti."],
      ["'Why do you keep doing it?' she asked eventually, and for a long moment he did not reply. 'Because someone ought to remember where things were,' he said at last. 'The sea doesn't care. The council only cares when a road falls in. But the land had a shape, and the shape mattered, and if I don't write it down, it will be as if it never existed.' He looked at her then, with an expression she could not quite interpret. 'I had hoped,' he added quietly, 'that someone might carry on after me.'", "'Neden yapmaya devam ediyorsun?' diye sordu sonunda ve babası uzun bir süre cevap vermedi. 'Çünkü birinin şeylerin nerede olduğunu hatırlaması gerek' dedi en sonunda. 'Denizin umurunda değil. Belediye de ancak bir yol çökünce umursuyor. Ama toprağın bir şekli vardı ve o şekil önemliydi, ben yazmazsam hiç var olmamış gibi olacak.' Sonra ona tam olarak yorumlayamadığı bir ifadeyle baktı. 'Umuyordum ki' diye ekledi sessizce, 'benden sonra biri devam eder.'"],
      ["Ilse did not answer him that night. But in the spring, when the weather finally softened, it was she who walked the cliffs with the notebook and the battered wheel, while her father followed a few paces behind, pointing out landmarks and correcting her figures with barely concealed delight.", "Ilse o gece ona cevap vermedi. Ama baharda, hava nihayet yumuşadığında, yalıyarları defter ve hırpalanmış tekerlekle yürüyen oydu. Babası ise birkaç adım geriden onu izliyor, önemli noktaları gösteriyor ve zar zor gizlediği bir sevinçle rakamlarını düzeltiyordu."]
    ],
    glossary: [["battered", "hırpalanmış"], ["meticulously", "titizlikle"], ["commissioned", "sipariş edilmiş, ısmarlanmış"], ["exasperation", "bıkkınlık, sinir"], ["conviction", "inanç, kanaat"], ["summoned", "çağrılmış"], ["perilously", "tehlikeli biçimde"], ["tremor", "titreme"], ["ferocious", "sert, vahşi"], ["annotating", "not düşmek"], ["eccentric", "tuhaf, alışılmadık"], ["barely concealed", "zar zor gizlenmiş"]],
    questions: [
      { q: "Why did Ilse return to the village?", options: ["Her father asked her to help with his maps", "A neighbour suggested her father was struggling", "She wanted to buy a house there"], answer: 1 },
      { q: "How does the narrator describe Aurelio's attitude to the erosion?", options: ["He treats it almost like a respected rival", "He is terrified of it", "He refuses to talk about it"], answer: 0 },
      { q: "What did Ilse realise when she saw all the maps together?", options: ["They were full of careless mistakes", "They could be sold for a lot of money", "They formed a detailed record of a disappearing landscape"], answer: 2 },
      { q: "What does the ending of the story suggest?", options: ["Ilse sold the maps to the council", "Ilse has decided to continue her father's work", "Aurelio finally stopped making maps"], answer: 1 }
    ] },

  { id: "r19", title: "The Art of Disappointing People Gracefully", trTitle: "İnsanları Zarafetle Hayal Kırıklığına Uğratma Sanatı", cefr: "C1", icon: "📚", kind: "Röportaj",
    paragraphs: [
      ["Elif Morgan has spent the past two decades translating contemporary Turkish fiction into English, a profession she describes, only half jokingly, as the art of disappointing people gracefully. Raised in Istanbul by a Turkish mother and a Welsh father, she grew up moving between two languages long before she understood that doing so could be a career. We spoke to her about untranslatable words, invisible labour and why a good translation should sometimes feel slightly foreign.", "Elif Morgan son yirmi yılını çağdaş Türk edebiyatını İngilizceye çevirerek geçirdi ve bu mesleği yarı şaka yollu, insanları zarafetle hayal kırıklığına uğratma sanatı olarak tanımlıyor. Türk bir anne ve Galli bir babanın kızı olarak İstanbul'da büyüyen Morgan, bunun bir meslek olabileceğini anlamadan çok önce iki dil arasında gidip gelerek büyüdü. Onunla çevrilemez kelimeleri, görünmez emeği ve iyi bir çevirinin neden bazen biraz yabancı hissettirmesi gerektiğini konuştuk."],
      ["You often say translation is about loss. What do you mean by that? 'Every translator knows that something will be lost, and the real skill lies in deciding what you can afford to sacrifice,' she says. 'Turkish, for instance, can convey an enormous amount through a single verb with a string of suffixes attached, nuances of doubt, hearsay, obligation and politeness all compressed into one word. English simply doesn't work like that. So you're constantly weighing whether to preserve the rhythm of a sentence, its precise meaning or its emotional temperature, because you rarely get to keep all three.'", "Sık sık çevirinin kayıpla ilgili olduğunu söylüyorsunuz. Bununla neyi kastediyorsunuz? 'Her çevirmen bir şeylerin kaybolacağını bilir ve asıl beceri neyi feda etmeyi göze alabileceğine karar vermekte yatar' diyor. 'Örneğin Türkçe, arka arkaya eklenmiş bir dizi ekle tek bir fiil aracılığıyla muazzam miktarda şey aktarabilir. Şüphe, duyuma dayalı bilgi, zorunluluk ve nezaket nüansları tek bir kelimeye sıkıştırılmıştır. İngilizce düpedüz böyle işlemez. Bu yüzden sürekli olarak bir cümlenin ritmini mi, tam anlamını mı yoksa duygusal sıcaklığını mı koruyacağınızı tartıyorsunuz, çünkü üçünü birden korumak nadiren mümkün olur.'"],
      ["Are there words you consider genuinely untranslatable? 'I'm wary of that term, because it tends to exoticise languages,' she replies. 'Any concept can be explained in any language, given enough words. The problem is economy. Take the Turkish word for the particular kind of reflection moonlight makes on water. English can describe it perfectly well, but it needs a whole phrase, and a phrase carries a different weight in a sentence than a single, elegant word. So the challenge isn't meaning, it's proportion. You have to find a way to make the reader feel what a Turkish reader feels, without burying the moment under explanation.'", "Gerçekten çevrilemez olduğunu düşündüğünüz kelimeler var mı? 'Bu terime karşı temkinliyim, çünkü dilleri egzotikleştirme eğiliminde' diye cevap veriyor. 'Yeterince kelime verilirse her kavram her dilde açıklanabilir. Sorun ekonomi. Ay ışığının suda yaptığı o özel yansımayı anlatan Türkçe kelimeyi düşünün. İngilizce bunu gayet iyi tarif edebilir ama bütün bir ifadeye ihtiyaç duyar ve bir ifade cümlede tek, zarif bir kelimeden farklı bir ağırlık taşır. Yani zorluk anlam değil, orantı. Okura, o anı açıklamaların altına gömmeden, bir Türk okurun hissettiğini hissettirmenin bir yolunu bulmanız gerekir.'"],
      ["Many readers barely notice the translator's name on the cover. Does that bother you? She laughs. 'Less than it used to. There's a long tradition of thinking that the best translation is an invisible one, that the reader should forget they're reading a translation at all. I've come to disagree with that, at least partly. If a novel set in a small Anatolian town reads exactly like it was written in suburban London, something has gone wrong. I'd rather the reader occasionally feel a gentle strangeness, a reminder that this world has its own textures and assumptions.'", "Birçok okur kapaktaki çevirmen adını neredeyse hiç fark etmiyor. Bu sizi rahatsız ediyor mu? Gülüyor. 'Eskisi kadar değil. En iyi çevirinin görünmez olanı olduğunu, okurun bir çeviri okuduğunu tamamen unutması gerektiğini düşünen köklü bir gelenek var. Ben buna en azından kısmen katılmamaya başladım. Küçük bir Anadolu kasabasında geçen bir roman, sanki Londra'nın bir banliyösünde yazılmış gibi okunuyorsa bir şeyler ters gitmiştir. Okurun ara sıra hafif bir yabancılık hissetmesini tercih ederim, bu dünyanın kendine özgü dokuları ve varsayımları olduğunu hatırlatan bir his.'"],
      ["How has technology changed your work? 'Machine translation has become remarkably competent at producing serviceable text, and I'd be foolish to pretend otherwise,' she acknowledges. 'For instruction manuals or routine correspondence, it's often perfectly adequate. Literature is a different matter, because so much of what makes a novel work lies in what is implied rather than stated, in irony, in the weight of a pause. That said, I do worry about the economics. If publishers come to believe that a machine draft plus a quick edit is good enough, the craft could gradually be hollowed out, not because it's unnecessary, but because it's underpaid.'", "Teknoloji işinizi nasıl değiştirdi? 'Makine çevirisi iş görür metinler üretmekte dikkat çekici derecede yetkin hâle geldi ve aksini iddia etmek aptallık olur' diye kabul ediyor. 'Kullanım kılavuzları ya da rutin yazışmalar için çoğu zaman gayet yeterli. Edebiyat ise farklı bir konu, çünkü bir romanı işler kılan şeyin büyük kısmı söylenende değil ima edilende, ironide, bir duraklamanın ağırlığında yatar. Yine de ekonomi konusunda gerçekten endişeliyim. Yayıncılar bir makine taslağı artı hızlı bir düzeltmenin yeterli olduğuna inanmaya başlarsa, bu zanaat gereksiz olduğu için değil, düşük ücretli olduğu için yavaş yavaş içi boşaltılabilir.'"],
      ["What advice would you give aspiring translators? 'Read voraciously in both languages, and not only literature. Read recipes, legal documents, sports commentary, anything that shows you how real people use language in specific contexts,' she says. 'And cultivate a thick skin. You will never produce a translation that satisfies everyone, and that's fine. A translation is ultimately an interpretation, one reader's deeply attentive response to a text. If you've been faithful to the spirit of the original and generous to your readers, you've done your job, even if some reviewer complains about a single word on page two hundred.'", "Çevirmen olmak isteyenlere ne tavsiye edersiniz? 'Her iki dilde de doymak bilmeden okuyun, sadece edebiyat da değil. Tarifler, hukuki belgeler, spor yorumları, gerçek insanların dili belirli bağlamlarda nasıl kullandığını gösteren her şeyi okuyun' diyor. 'Ve kalın bir deri geliştirin. Asla herkesi memnun eden bir çeviri üretemeyeceksiniz ve bu sorun değil. Çeviri nihayetinde bir yorumdur, bir okurun bir metne gösterdiği derin ve dikkatli bir karşılıktır. Özgün metnin ruhuna sadık ve okurlarınıza karşı cömert davrandıysanız, bir eleştirmen iki yüzüncü sayfadaki tek bir kelimeden şikâyet etse bile işinizi yapmışsınızdır.'"]
    ],
    glossary: [["half jokingly", "yarı şaka yollu"], ["sacrifice", "feda etmek"], ["suffixes", "ekler"], ["hearsay", "duyuma dayalı bilgi"], ["wary", "temkinli"], ["exoticise", "egzotikleştirmek"], ["proportion", "orantı"], ["serviceable", "iş görür"], ["implied", "ima edilen"], ["hollowed out", "içi boşaltılmış"], ["voraciously", "doymak bilmeden"], ["thick skin", "kalın deri, eleştiriye dayanıklılık"]],
    questions: [
      { q: "According to Elif, what is the real skill of a translator?", options: ["Translating every word literally", "Deciding what can be sacrificed", "Working as quickly as possible"], answer: 1 },
      { q: "Why is she wary of the term untranslatable?", options: ["It tends to make languages seem exotic", "It confuses ordinary readers", "It only applies to poetry"], answer: 0 },
      { q: "What is her view on invisible translations?", options: ["Readers should never notice they are reading a translation", "Translators should add explanations on every page", "A gentle sense of strangeness can be valuable"], answer: 2 },
      { q: "What concerns her most about machine translation?", options: ["It produces completely unreadable text", "Economic pressure could gradually undermine the craft", "It will soon replace novelists"], answer: 1 }
    ] },

  { id: "r20", title: "The Quiet Return of Repair", trTitle: "Tamirin Sessiz Dönüşü", cefr: "C1", icon: "🔧", kind: "Makale",
    paragraphs: [
      ["For much of the twentieth century, repairing things was simply what people did. Shoes were resoled, radios rewired, jumpers darned and furniture reupholstered, often by the very people who owned them. Somewhere in the latter decades of the century, however, that habit began to erode. As manufacturing costs fell and products became more complex, replacing a broken item increasingly made more economic sense than fixing it, and an entire culture of maintenance quietly receded into nostalgia.", "Yirminci yüzyılın büyük bölümünde bir şeyleri tamir etmek insanların doğal olarak yaptığı bir şeydi. Ayakkabılara pençe vurulur, radyoların kabloları yenilenir, kazaklar örülerek yamanır ve mobilyalar yeniden döşenirdi, çoğu zaman da bunları bizzat sahipleri yapardı. Ancak yüzyılın son on yıllarında bir yerde bu alışkanlık aşınmaya başladı. Üretim maliyetleri düştükçe ve ürünler karmaşıklaştıkça bozuk bir eşyayı değiştirmek onu tamir etmekten giderek daha mantıklı hâle geldi ve koca bir bakım kültürü sessizce nostaljiye çekildi."],
      ["Today, there are signs that the pendulum may be swinging back. In towns and cities across many countries, volunteer-run repair cafés have sprung up, offering residents the chance to bring in a faulty toaster, a torn coat or a temperamental laptop and fix it alongside someone with the relevant expertise. Online, tutorials demonstrating how to replace a cracked phone screen or revive a dead vacuum cleaner attract enormous audiences. Repair, it seems, is undergoing something of a cultural rehabilitation.", "Bugün sarkacın geri dönüyor olabileceğine dair işaretler var. Birçok ülkenin kasaba ve şehirlerinde gönüllülerin işlettiği tamir kafeleri ortaya çıktı. Bu kafeler sakinlere arızalı bir ekmek kızartma makinesini, yırtık bir montu ya da huysuz bir dizüstü bilgisayarı getirip ilgili uzmanlığa sahip biriyle birlikte tamir etme fırsatı sunuyor. İnternette çatlak bir telefon ekranının nasıl değiştirileceğini ya da çalışmayan bir elektrikli süpürgenin nasıl canlandırılacağını gösteren eğitim videoları muazzam izleyici kitlelerine ulaşıyor. Görünen o ki tamir bir tür kültürel itibar kazanma sürecinden geçiyor."],
      ["The motivations behind this revival are varied. For some participants, the appeal is primarily environmental. The production of electronic devices in particular consumes significant quantities of energy and raw materials, many of which are extracted under environmentally damaging conditions, and extending a product's lifespan by even a few years can substantially reduce its overall footprint. For others, the motivation is financial, sharpened by rising living costs. And for a sizeable number, it is something harder to quantify, a desire to understand and exert some control over the objects that populate their daily lives.", "Bu canlanmanın ardındaki motivasyonlar çeşitli. Bazı katılımcılar için çekicilik öncelikle çevresel. Özellikle elektronik cihazların üretimi önemli miktarda enerji ve hammadde tüketiyor, bunların birçoğu çevreye zarar veren koşullarda çıkarılıyor ve bir ürünün ömrünü birkaç yıl bile uzatmak toplam ayak izini önemli ölçüde azaltabiliyor. Diğerleri için motivasyon maddi ve artan yaşam maliyetleriyle keskinleşmiş durumda. Hatırı sayılır bir kesim için ise ölçülmesi daha zor bir şey, gündelik hayatlarını dolduran nesneleri anlama ve onlar üzerinde bir miktar kontrol kurma arzusu."],
      ["That last motivation points to a deeper tension. Many contemporary products are, whether by accident or by design, remarkably hostile to repair. Components are glued rather than screwed together, specialised tools are required to open casings, and spare parts and diagnostic software are often available only to authorised technicians. Manufacturers typically justify these practices on grounds of safety, quality control or the protection of intellectual property. Critics counter that they serve chiefly to channel consumers towards costly official services or, more often, towards buying a replacement.", "Bu son motivasyon daha derin bir gerilime işaret ediyor. Günümüz ürünlerinin birçoğu, ister kazara ister bilerek, tamire karşı dikkat çekici derecede düşmanca. Parçalar vidalanmak yerine yapıştırılıyor, kasaları açmak için özel aletler gerekiyor, yedek parçalar ve arıza tespit yazılımları çoğu zaman sadece yetkili teknisyenlere sunuluyor. Üreticiler bu uygulamaları genellikle güvenlik, kalite kontrolü ya da fikrî mülkiyetin korunması gerekçesiyle savunuyor. Eleştirmenler ise bunların esas olarak tüketicileri pahalı resmî servislere ya da daha sık olarak yenisini satın almaya yönlendirmeye yaradığını öne sürüyor."],
      ["This dispute has increasingly migrated from workshops to legislatures. Campaigners advocating a so-called right to repair argue that people who have paid for a product should be entitled to fix it, or to have it fixed by whomever they choose, without being obstructed by artificial barriers. In several jurisdictions, regulations have begun to require that certain appliances be designed for easier disassembly and that spare parts remain available for a minimum number of years. The precise impact of such measures remains to be seen, but they signal a notable shift in how policymakers conceive of ownership.", "Bu anlaşmazlık giderek atölyelerden yasama meclislerine taşındı. Tamir hakkı denen şeyi savunan kampanyacılar, bir ürün için para ödemiş insanların, yapay engellerle karşılaşmadan onu tamir etme ya da istedikleri kişiye tamir ettirme hakkına sahip olması gerektiğini savunuyor. Bazı yargı bölgelerinde düzenlemeler, belirli ev aletlerinin daha kolay sökülecek şekilde tasarlanmasını ve yedek parçaların asgari bir yıl sayısı boyunca bulunabilir olmasını şart koşmaya başladı. Bu tedbirlerin tam etkisi henüz belli değil, ama politika yapıcıların mülkiyeti nasıl algıladığında kayda değer bir değişime işaret ediyorlar."],
      ["It would be naive, however, to imagine that repair cafés and new regulations will by themselves reverse decades of throwaway consumption. Repairing an item still requires time, skill and, frequently, patience that many people can ill afford. Moreover, for some products, particularly those that are inexpensive to begin with, the economics of repair remain stubbornly unfavourable. A broader transformation would arguably require changes not only in law and design, but in the attitudes that lead us to regard newness as inherently desirable.", "Ancak tamir kafelerinin ve yeni düzenlemelerin tek başına on yıllardır süren kullan at tüketimini tersine çevireceğini düşünmek saflık olur. Bir eşyayı tamir etmek hâlâ zaman, beceri ve çoğu zaman birçok insanın ayıramayacağı bir sabır gerektiriyor. Üstelik bazı ürünler için, özellikle zaten ucuz olanlar için, tamirin ekonomisi inatla elverişsiz olmaya devam ediyor. Daha kapsamlı bir dönüşüm muhtemelen sadece yasada ve tasarımda değil, yeniliği doğası gereği arzu edilir görmemize yol açan tutumlarda da değişiklik gerektirir."],
      ["Perhaps that is where the most significant change is taking place. Those who have mended something with their own hands often describe a curious sense of attachment to it afterwards, as though the act of repair had transformed a disposable commodity into a possession with a history. A visibly patched jacket or a lovingly restored chair carries a kind of quiet dignity. In a culture long accustomed to discarding the imperfect, learning to value what has been mended may prove to be a small but genuinely radical act.", "Belki de en önemli değişim tam orada yaşanıyor. Bir şeyi kendi elleriyle onaran insanlar, sonrasında ona karşı tuhaf bir bağlılık hissettiklerini sık sık anlatıyor, sanki onarma eylemi kullanılıp atılacak bir metayı geçmişi olan bir eşyaya dönüştürmüş gibi. Yaması belli olan bir ceket ya da sevgiyle restore edilmiş bir sandalye bir tür sessiz onur taşır. Kusurlu olanı atmaya uzun zamandır alışmış bir kültürde, onarılmış olana değer vermeyi öğrenmek küçük ama gerçekten radikal bir eylem olabilir."]
    ],
    glossary: [["darned", "örülerek yamanmış"], ["erode", "aşınmak"], ["receded", "geri çekildi"], ["pendulum", "sarkaç"], ["temperamental", "huysuz, ne yapacağı belli olmayan"], ["rehabilitation", "itibarın iadesi, rehabilitasyon"], ["footprint", "ayak izi"], ["hostile to", "-e düşmanca, karşı"], ["legislatures", "yasama meclisleri"], ["jurisdictions", "yargı bölgeleri"], ["disassembly", "sökme, parçalarına ayırma"], ["commodity", "meta, mal"]],
    questions: [
      { q: "Why did repair become less common in the late twentieth century?", options: ["People lost interest in technology", "Replacing items became more economical than fixing them", "Repair shops were banned"], answer: 1 },
      { q: "Which motivation for repair is described as hardest to measure?", options: ["Saving money", "Protecting the environment", "Wanting to understand and control everyday objects"], answer: 2 },
      { q: "How do critics view manufacturers' restrictions on repair?", options: ["As a way to push consumers towards expensive services or replacements", "As necessary for customer safety", "As the result of new legislation"], answer: 0 },
      { q: "What does the writer suggest in the final paragraph?", options: ["Repair cafés will soon replace shops", "Learning to value mended objects could be a meaningful cultural change", "Only expensive products are worth repairing"], answer: 1 }
    ] }
);
