(window.READINGS = window.READINGS || []).push(
  { id: "r1", title: "The Wrong Umbrella", trTitle: "Yanlış Şemsiye", cefr: "A2", icon: "🌂", kind: "Hikâye",
    paragraphs: [
      ["It was a rainy Tuesday in October. Selin left her office at six and went into a small café near the station. She ordered a hot chocolate and sat by the window. Her black umbrella was wet, so she put it in the stand by the door. Then she opened her laptop and answered some emails from work.", "Ekim ayında yağmurlu bir salı günüydü. Selin altıda ofisinden çıktı ve istasyonun yakınındaki küçük bir kafeye girdi. Bir sıcak çikolata sipariş etti ve pencerenin yanına oturdu. Siyah şemsiyesi ıslaktı, bu yüzden onu kapının yanındaki şemsiyeliğe koydu. Sonra dizüstü bilgisayarını açtı ve işten gelen birkaç e-postayı yanıtladı."],
      ["Half an hour later, she was late for her train. She grabbed a black umbrella from the stand and ran outside. On the train, she opened it a little and saw something strange. There was a small yellow note inside it.", "Yarım saat sonra trenine geç kalmıştı. Şemsiyelikten siyah bir şemsiye kaptı ve dışarı koştu. Trende onu biraz açtı ve tuhaf bir şey gördü. İçinde küçük sarı bir not vardı."],
      ["The note said, If you find this umbrella, please call Emre. It was my grandfather's. Then there was a phone number. Selin felt terrible. This was not her umbrella. Somebody else probably had hers now. She decided to call the number as soon as she got home.", "Notta şöyle yazıyordu, Bu şemsiyeyi bulursanız lütfen Emre'yi arayın. Dedemindi. Ardından bir telefon numarası vardı. Selin kendini çok kötü hissetti. Bu onun şemsiyesi değildi. Muhtemelen şimdi onunki başka birindeydi. Eve varır varmaz numarayı aramaya karar verdi."],
      ["She called the number that evening. A young man answered. He was very happy and a little surprised. He said, I have your umbrella, I think. It is cheap and has a broken handle. They both laughed. Emre explained that the umbrella was very special to him because his grandfather used it for fifty years.", "O akşam numarayı aradı. Genç bir adam cevap verdi. Çok mutluydu ve biraz şaşırmıştı. Şöyle dedi, Sanırım sizin şemsiyeniz bende. Ucuz ve sapı kırık. İkisi de güldü. Emre şemsiyenin onun için çok özel olduğunu, çünkü dedesinin onu elli yıl kullandığını açıkladı."],
      ["The next day, they met at the same café and changed umbrellas. Emre bought her a hot chocolate to say thank you. Now they meet there every Tuesday, and they always check their umbrellas twice.", "Ertesi gün aynı kafede buluştular ve şemsiyeleri değiştirdiler. Emre teşekkür etmek için ona bir sıcak çikolata ısmarladı. Artık her salı orada buluşuyorlar ve şemsiyelerini her zaman iki kez kontrol ediyorlar."]
    ],
    glossary: [["rainy", "yağmurlu"], ["ordered", "sipariş etti"], ["stand", "şemsiyelik, askılık"], ["grabbed", "kaptı"], ["strange", "tuhaf"], ["note", "not"], ["terrible", "berbat, çok kötü"], ["probably", "muhtemelen"], ["surprised", "şaşırmış"], ["handle", "sap"], ["twice", "iki kez"]],
    questions: [
      { q: "Selin şemsiyeyi neden şemsiyeliğe koydu?", options: ["Çünkü şemsiye kırıktı", "Çünkü şemsiye ıslaktı", "Çünkü garson istedi"], answer: 1 },
      { q: "Şemsiyenin içinde ne vardı?", options: ["Sarı bir not", "Bir tren bileti", "Biraz para"], answer: 0 },
      { q: "Selin'in kendi şemsiyesi nasıldı?", options: ["Pahalı ve yeni", "Kırmızı ve büyük", "Ucuz ve sapı kırık"], answer: 2 },
      { q: "Selin ve Emre artık ne yapıyor?", options: ["Birlikte trenle işe gidiyorlar", "Her salı kafede buluşuyorlar", "Şemsiye dükkânı açtılar"], answer: 1 }
    ] },

  { id: "r2", title: "My Month Without Social Media", trTitle: "Sosyal Medyasız Bir Ayım", cefr: "A2", icon: "📵", kind: "Blog",
    paragraphs: [
      ["Hi everyone! Last month, I did a small experiment. I deleted all my social media apps from my phone for thirty days. Before that, I spent about four hours a day on my phone. That is a lot of time, right? I wanted to see how my life changes without it.", "Herkese merhaba! Geçen ay küçük bir deney yaptım. Otuz gün boyunca telefonumdaki bütün sosyal medya uygulamalarını sildim. Bundan önce günde yaklaşık dört saatimi telefonda geçiriyordum. Bu çok fazla zaman, değil mi? Onsuz hayatımın nasıl değiştiğini görmek istedim."],
      ["The first week was really hard. I picked up my phone again and again without a reason. I felt bored on the bus and in queues. I also worried that I was missing important news from my friends. Every evening, I wanted to download the apps again, but I did not.", "İlk hafta gerçekten zordu. Sebepsiz yere telefonumu tekrar tekrar elime aldım. Otobüste ve kuyruklarda sıkıldım. Arkadaşlarımdan önemli haberleri kaçırdığım için de endişelendim. Her akşam uygulamaları yeniden indirmek istedim ama indirmedim."],
      ["In the second week, things started to change. I read two books on the bus. I called my mother more often, and we had long conversations. I also started to cook dinner instead of watching videos while I ate.", "İkinci haftada işler değişmeye başladı. Otobüste iki kitap okudum. Annemi daha sık aradım ve uzun sohbetler ettik. Ayrıca yemek yerken video izlemek yerine akşam yemeği pişirmeye başladım."],
      ["The biggest surprise was my sleep. Before, I looked at my phone in bed until midnight. Without it, I fell asleep earlier and woke up with more energy. My friends said I looked more relaxed. I also had more time for a walk in the park after work.", "En büyük sürpriz uykum oldu. Önceden gece yarısına kadar yatakta telefonuma bakıyordum. O olmadan daha erken uyudum ve daha enerjik uyandım. Arkadaşlarım daha rahat göründüğümü söyledi. İşten sonra parkta yürüyüş yapmak için de daha çok vaktim oldu."],
      ["So, did I go back? Yes, but only a little. Now I use social media for twenty minutes a day, and never in the bedroom. My advice is simple. Try it for one week. You may be surprised too!", "Peki, geri döndüm mü? Evet, ama sadece biraz. Artık sosyal medyayı günde yirmi dakika kullanıyorum ve asla yatak odasında kullanmıyorum. Tavsiyem basit. Bir hafta deneyin. Siz de şaşırabilirsiniz!"]
    ],
    glossary: [["experiment", "deney"], ["deleted", "sildi"], ["without a reason", "sebepsiz yere"], ["bored", "sıkılmış"], ["queues", "kuyruklar"], ["worried", "endişelendi"], ["missing", "kaçırmak"], ["more often", "daha sık"], ["instead of", "yerine"], ["relaxed", "rahat, gevşemiş"], ["advice", "tavsiye"]],
    questions: [
      { q: "Yazar deneyden önce günde kaç saat telefonda geçiriyordu?", options: ["İki saat", "Dört saat", "Altı saat"], answer: 1 },
      { q: "İlk hafta yazar ne hissetti?", options: ["Sıkıldı ve endişelendi", "Çok mutlu oldu", "Hiçbir şey hissetmedi"], answer: 0 },
      { q: "Yazar için en büyük sürpriz neydi?", options: ["Kilo vermesi", "Yeni arkadaşlar edinmesi", "Uykusunun daha iyi olması"], answer: 2 },
      { q: "Yazar şimdi sosyal medyayı nasıl kullanıyor?", options: ["Hiç kullanmıyor", "Günde yirmi dakika, yatak odası dışında", "Sadece hafta sonları"], answer: 1 }
    ] },

  { id: "r3", title: "Welcome to the Team", trTitle: "Ekibe Hoş Geldin", cefr: "A2", icon: "📧", kind: "E-posta",
    paragraphs: [
      ["Dear Deniz, welcome to Brightline Design! We are all very happy that you are joining our team. I am writing to give you some information about your first day next Monday.", "Sevgili Deniz, Brightline Design'a hoş geldin! Ekibimize katıldığın için hepimiz çok mutluyuz. Gelecek pazartesi ilk günün hakkında sana biraz bilgi vermek için yazıyorum."],
      ["Please come to the office at half past nine. Our building is on Park Street, next to the big supermarket. When you arrive, go to the third floor and ask for Ayla at the reception desk. She will give you your ID card and your laptop.", "Lütfen ofise dokuz buçukta gel. Binamız Park Caddesi'nde, büyük süpermarketin yanında. Geldiğinde üçüncü kata çık ve resepsiyonda Ayla'yı sor. Sana kimlik kartını ve dizüstü bilgisayarını verecek."],
      ["In the morning, you will meet the other designers and see our current projects. Do not worry, you do not need to do any real work on the first day! At one o'clock, the whole team is going to have lunch together at an Italian restaurant nearby.", "Sabah diğer tasarımcılarla tanışacak ve mevcut projelerimizi göreceksin. Merak etme, ilk gün hiçbir gerçek iş yapman gerekmiyor! Saat birde bütün ekip yakındaki bir İtalyan restoranında birlikte öğle yemeği yiyecek."],
      ["In the afternoon, Mert from the IT team will help you set up your email and other programs. This usually takes about an hour, so please be patient. After that, you can explore the office and ask questions. There is a small kitchen on every floor with free tea, coffee and fruit.", "Öğleden sonra IT ekibinden Mert e-postanı ve diğer programları kurmana yardım edecek. Bu genellikle yaklaşık bir saat sürer, bu yüzden lütfen sabırlı ol. Ondan sonra ofisi keşfedebilir ve soru sorabilirsin. Her katta ücretsiz çay, kahve ve meyve bulunan küçük bir mutfak var."],
      ["Our dress code is casual, so jeans are fine. Please bring a copy of your passport for the contract. If you have any questions before Monday, you can call me or send me an email. See you soon! Best wishes, Kerem Aydın, Team Manager", "Kıyafet kuralımız rahat, yani kot pantolon olur. Lütfen sözleşme için pasaportunun bir kopyasını getir. Pazartesiden önce herhangi bir sorun olursa beni arayabilir veya bana e-posta gönderebilirsin. Yakında görüşürüz! En iyi dileklerimle, Kerem Aydın, Ekip Müdürü"]
    ],
    glossary: [["joining", "katılmak"], ["arrive", "varmak, gelmek"], ["reception desk", "resepsiyon masası"], ["ID card", "kimlik kartı"], ["current", "mevcut, şu anki"], ["nearby", "yakında, yakındaki"], ["set up", "kurmak"], ["explore", "keşfetmek"], ["dress code", "kıyafet kuralı"], ["casual", "rahat, günlük"], ["contract", "sözleşme"]],
    questions: [
      { q: "Deniz pazartesi ofise saat kaçta gelmeli?", options: ["Dokuzda", "Onda", "Dokuz buçukta"], answer: 2 },
      { q: "Deniz'e kimlik kartını kim verecek?", options: ["Ayla", "Mert", "Kerem"], answer: 0 },
      { q: "Ekip öğle yemeğini nerede yiyecek?", options: ["Ofisteki mutfakta", "Yakındaki bir İtalyan restoranında", "Süpermarketin kafesinde"], answer: 1 },
      { q: "Deniz ofise ne getirmeli?", options: ["Kendi dizüstü bilgisayarını", "Takım elbise", "Pasaportunun bir kopyasını"], answer: 2 }
    ] },

  { id: "r4", title: "Cat Takes the Bus to the Seaside", trTitle: "Kedi Otobüsle Sahile Gitti", cefr: "A2", icon: "🐈", kind: "Haber",
    paragraphs: [
      ["A ginger cat called Biscuit surprised everyone in the small town of Hollowfield last week. The cat got on a bus in the town centre and travelled forty kilometres to the seaside town of Marlow Bay.", "Biscuit adlı turuncu bir kedi geçen hafta küçük Hollowfield kasabasında herkesi şaşırttı. Kedi kasaba merkezinde bir otobüse bindi ve kırk kilometre yol gidip sahil kasabası Marlow Bay'e ulaştı."],
      ["The bus driver, Paul Hendry, did not see the cat at first. Biscuit was sleeping under a seat at the back of the bus. A passenger noticed him after about thirty minutes and told the driver. Many passengers took photos of him and shared them online.", "Otobüs şoförü Paul Hendry kediyi ilk başta görmedi. Biscuit otobüsün arkasında bir koltuğun altında uyuyordu. Bir yolcu yaklaşık otuz dakika sonra onu fark etti ve şoföre söyledi. Birçok yolcu onun fotoğraflarını çekip internette paylaştı."],
      ["He was very calm, said Mr Hendry. He did not want to get off. When we arrived at Marlow Bay, he walked to the front and looked at the sea through the window. I think he enjoyed the trip more than the people!", "Çok sakindi, dedi Bay Hendry. İnmek istemedi. Marlow Bay'e vardığımızda öne yürüdü ve pencereden denize baktı. Bence yolculuktan insanlardan daha çok keyif aldı!"],
      ["The driver took Biscuit to a local vet. The vet found a microchip under his skin with his owner's phone number. His owner, a teacher named Laura Pike, was very worried because Biscuit was missing for two days. She put posters on every street in Hollowfield, but nobody saw him.", "Şoför Biscuit'i yerel bir veterinere götürdü. Veteriner derisinin altında sahibinin telefon numarasının olduğu bir mikroçip buldu. Sahibi, Laura Pike adında bir öğretmen, çok endişeliydi çünkü Biscuit iki gündür kayıptı. Hollowfield'daki her sokağa afiş astı ama kimse onu görmedi."],
      ["Ms Pike drove to Marlow Bay that evening to bring her cat home. The bus company later gave Biscuit a funny gift, a free bus pass with his photo on it. Ms Pike says she will keep him inside for a while.", "Bayan Pike o akşam kedisini eve getirmek için arabayla Marlow Bay'e gitti. Otobüs şirketi daha sonra Biscuit'e komik bir hediye verdi, üzerinde fotoğrafı olan ücretsiz bir otobüs kartı. Bayan Pike bir süre onu evde tutacağını söylüyor."]
    ],
    glossary: [["ginger", "turuncu, kızıl"], ["seaside", "sahil, deniz kenarı"], ["at first", "ilk başta"], ["passenger", "yolcu"], ["noticed", "fark etti"], ["calm", "sakin"], ["get off", "inmek"], ["vet", "veteriner"], ["skin", "deri"], ["owner", "sahip"], ["missing", "kayıp"], ["for a while", "bir süre"]],
    questions: [
      { q: "Kedi otobüste ne yapıyordu?", options: ["Koltuğun altında uyuyordu", "Şoförün yanında oturuyordu", "Yolculardan yemek istiyordu"], answer: 0 },
      { q: "Kediyi ilk kim fark etti?", options: ["Şoför", "Bir yolcu", "Veteriner"], answer: 1 },
      { q: "Veteriner sahibini nasıl buldu?", options: ["Gazeteye ilan vererek", "Kedinin tasmasındaki adres sayesinde", "Mikroçipteki telefon numarası sayesinde"], answer: 2 },
      { q: "Otobüs şirketi Biscuit'e ne verdi?", options: ["Bir kutu mama", "Ücretsiz bir otobüs kartı", "Yeni bir tasma"], answer: 1 }
    ] },

  { id: "r5", title: "Working While the City Sleeps", trTitle: "Şehir Uyurken Çalışmak", cefr: "A2", icon: "🥖", kind: "Röportaj",
    paragraphs: [
      ["Most people are asleep at three in the morning, but Hasan Kaya is already at work. He is a baker in a small neighbourhood bakery. He has done this job for fifteen years. We asked him about his unusual daily routine.", "Çoğu insan sabahın üçünde uyurken Hasan Kaya çoktan iştedir. Küçük bir mahalle fırınında fırıncı. On beş yıldır bu işi yapıyor. Ona alışılmadık günlük rutinini sorduk."],
      ["What time do you wake up? I wake up at half past two every night. I drink a strong coffee and walk to the bakery. The streets are completely empty and quiet. Sometimes I only see a few cats and a street cleaner.", "Kaçta uyanıyorsunuz? Her gece iki buçukta uyanıyorum. Sert bir kahve içip fırına yürüyorum. Sokaklar tamamen boş ve sessiz. Bazen sadece birkaç kedi ve bir sokak temizlikçisi görüyorum."],
      ["What do you do first? First, I prepare the dough for the bread. Then I make simit and pastries. By six o'clock, we need about five hundred pieces. The first customers come at half past six, usually workers on their way to the factory.", "İlk önce ne yapıyorsunuz? Önce ekmek için hamuru hazırlıyorum. Sonra simit ve hamur işleri yapıyorum. Saat altıya kadar yaklaşık beş yüz parçaya ihtiyacımız var. İlk müşteriler altı buçukta geliyor, genellikle fabrikaya giden işçiler."],
      ["Is it difficult? Yes, sometimes. I go to bed at seven in the evening, so I miss weddings and birthday parties. My friends joke that I live in a different time zone. But I love the smell of fresh bread in the morning.", "Zor mu? Evet, bazen. Akşam yedide yatıyorum, bu yüzden düğünleri ve doğum günü partilerini kaçırıyorum. Arkadaşlarım farklı bir saat diliminde yaşadığımı söyleyip şaka yapıyor. Ama sabah taze ekmek kokusunu çok seviyorum."],
      ["What is the best part of your job? The best part is the people. An old man comes every day and buys one simit for himself and one for the birds. Small moments like that make me happy. I would not change this job for an office job, even for more money.", "İşinizin en güzel yanı ne? En güzel yanı insanlar. Yaşlı bir adam her gün gelip bir simit kendisi için, bir simit de kuşlar için alıyor. Bunun gibi küçük anlar beni mutlu ediyor. Daha fazla para için bile bu işi bir ofis işiyle değiştirmem."]
    ],
    glossary: [["asleep", "uykuda"], ["neighbourhood", "mahalle"], ["unusual", "alışılmadık"], ["daily routine", "günlük rutin"], ["completely", "tamamen"], ["prepare", "hazırlamak"], ["dough", "hamur"], ["pastries", "hamur işleri"], ["customers", "müşteriler"], ["miss", "kaçırmak"], ["time zone", "saat dilimi"], ["smell", "koku"]],
    questions: [
      { q: "Hasan her gece kaçta uyanıyor?", options: ["İki buçukta", "Üçte", "Altıda"], answer: 0 },
      { q: "İlk müşteriler genellikle kimler?", options: ["Öğrenciler", "Turistler", "Fabrikaya giden işçiler"], answer: 2 },
      { q: "Hasan'ın işinin zor yanı nedir?", options: ["Maaşı düşük", "Düğünleri ve partileri kaçırıyor", "Fırın evinden çok uzak"], answer: 1 },
      { q: "Yaşlı adam ikinci simidi kimin için alıyor?", options: ["Torunu için", "Kuşlar için", "Komşusu için"], answer: 1 }
    ] },

  { id: "r6", title: "The Last Train", trTitle: "Son Tren", cefr: "B1", icon: "🚉", kind: "Hikâye",
    paragraphs: [
      ["Ozan had never missed a train in his life, so he could not believe it when he saw the red lights of the last train disappearing into the dark. It was eleven at night, he was in a small town he did not know, and his phone battery was at three percent.", "Ozan hayatında hiç tren kaçırmamıştı, bu yüzden son trenin kırmızı ışıklarının karanlıkta kaybolduğunu gördüğünde inanamadı. Saat gece on birdi, bilmediği küçük bir kasabadaydı ve telefonunun şarjı yüzde üçteydi."],
      ["The station was empty except for an old woman sitting on a bench with a large basket. She looked at him and smiled as if she had expected this. Missed it, did you? she asked. The next one is at six in the morning. You can stay here and freeze, or you can help me carry this basket home.", "İstasyon, büyük bir sepetle bankta oturan yaşlı bir kadın dışında boştu. Kadın ona baktı ve sanki bunu bekliyormuş gibi gülümsedi. Kaçırdın, değil mi? diye sordu. Bir sonraki sabah altıda. Burada kalıp donabilirsin ya da bu sepeti eve taşımama yardım edebilirsin."],
      ["Ozan hesitated. He had grown up in a big city where you did not follow strangers home. But the wind was getting colder, and the woman did not look dangerous. She looked tired. He picked up the basket, which was surprisingly heavy, and followed her up a narrow street.", "Ozan tereddüt etti. Yabancıların peşinden eve gidilmeyen büyük bir şehirde büyümüştü. Ama rüzgâr giderek soğuyordu ve kadın tehlikeli görünmüyordu. Yorgun görünüyordu. Şaşırtıcı derecede ağır olan sepeti aldı ve dar bir sokaktan yukarı onu takip etti."],
      ["Her house was small and warm, and it smelled of oranges. The basket turned out to be full of jars of homemade jam, which she sold at the market every week. She made him tea, gave him a charger for his phone, and told him stories about the town while the clock ticked towards midnight.", "Evi küçük ve sıcaktı, portakal kokuyordu. Sepetin, her hafta pazarda sattığı ev yapımı reçel kavanozlarıyla dolu olduğu ortaya çıktı. Ona çay yaptı, telefonu için bir şarj aleti verdi ve saat gece yarısına doğru ilerlerken ona kasaba hakkında hikâyeler anlattı."],
      ["She said that forty years ago she had also missed the last train in this town. A kind family had let her stay, and she had never left. Ozan laughed and said that he had a job interview in the city the next afternoon, so he was definitely leaving. She just shrugged and said, We will see.", "Kırk yıl önce kendisinin de bu kasabada son treni kaçırdığını söyledi. Nazik bir aile kalmasına izin vermişti ve o bir daha hiç ayrılmamıştı. Ozan güldü ve ertesi öğleden sonra şehirde bir iş görüşmesi olduğunu, bu yüzden kesinlikle gideceğini söyledi. Kadın sadece omuz silkti ve Göreceğiz, dedi."],
      ["At six the next morning, Ozan caught the first train. He got the job, but every few months he takes the train back to that little town. He always arrives with an empty basket and leaves with a heavy one, and he never checks the timetable for the last train home.", "Ertesi sabah altıda Ozan ilk treni yakaladı. İşi aldı, ama birkaç ayda bir trenle o küçük kasabaya geri dönüyor. Her zaman boş bir sepetle geliyor ve dolu bir sepetle ayrılıyor, ve eve dönen son trenin saatine asla bakmıyor."]
    ],
    glossary: [["disappearing", "kaybolmak"], ["except for", "dışında, hariç"], ["bench", "bank"], ["freeze", "donmak"], ["hesitated", "tereddüt etti"], ["strangers", "yabancılar"], ["narrow", "dar"], ["turned out", "ortaya çıktı"], ["jars", "kavanozlar"], ["homemade", "ev yapımı"], ["shrugged", "omuz silkti"], ["timetable", "sefer tarifesi"]],
    questions: [
      { q: "Why was Ozan's situation especially difficult at the station?", options: ["He had lost his wallet", "His phone was almost dead and he did not know the town", "It was raining very heavily"], answer: 1 },
      { q: "What was inside the old woman's basket?", options: ["Oranges from her garden", "Bread for the market", "Jars of homemade jam"], answer: 2 },
      { q: "What happened to the woman forty years earlier?", options: ["She missed the last train and stayed in the town", "She worked at the train station", "She moved to the big city for a job"], answer: 0 },
      { q: "What does Ozan do now?", options: ["He lives in the small town", "He visits the town regularly", "He sells jam at the market"], answer: 1 }
    ] },

  { id: "r7", title: "What Three Countries Taught Me About Remote Work", trTitle: "Üç Ülkenin Bana Uzaktan Çalışma Hakkında Öğrettikleri", cefr: "B1", icon: "💻", kind: "Blog",
    paragraphs: [
      ["Two years ago, my company told us that we could work from anywhere. I was excited and a little scared. Since then, I have lived in Lisbon, Tbilisi and Chiang Mai, and I have learned more about work in these two years than in the previous five. Here are my three biggest lessons.", "İki yıl önce şirketim bize her yerden çalışabileceğimizi söyledi. Heyecanlıydım ve biraz da korkmuştum. O zamandan beri Lizbon, Tiflis ve Chiang Mai'de yaşadım ve bu iki yılda iş hakkında önceki beş yıldan daha fazlasını öğrendim. İşte en büyük üç dersim."],
      ["Lesson one, a beautiful view does not make you productive. In Lisbon, I rented a flat with a stunning view of the river. I spent the first month staring out of the window and finishing nothing. In the end, I moved my desk to face a plain white wall, and my work improved immediately.", "Birinci ders, güzel bir manzara sizi üretken yapmaz. Lizbon'da nehre bakan muhteşem manzaralı bir daire kiraladım. İlk ayı pencereden dışarı bakarak ve hiçbir şeyi bitirmeden geçirdim. Sonunda masamı düz beyaz bir duvara bakacak şekilde taşıdım ve işim hemen iyileşti."],
      ["Lesson two, time zones are harder than they look. In Tbilisi, I was three hours ahead of my team, which seemed fine at first. But meetings often started late in my afternoon and ran into the evening. I learned to protect my mornings for deep work and to say no to meetings without a clear purpose.", "İkinci ders, saat dilimleri göründüğünden daha zor. Tiflis'te ekibimden üç saat ilerideydim, bu ilk başta sorun değil gibi görünüyordu. Ama toplantılar genellikle öğleden sonramın geç saatlerinde başlıyor ve akşama sarkıyordu. Sabahlarımı derin çalışma için korumayı ve net bir amacı olmayan toplantılara hayır demeyi öğrendim."],
      ["Lesson three, loneliness is the real challenge. Nobody warns you about this. In Chiang Mai, the weather was perfect and the food was amazing, but some weeks I spoke to nobody except my laptop. Joining a coworking space changed everything. I found people to have lunch with and even a running group.", "Üçüncü ders, asıl zorluk yalnızlık. Kimse sizi bu konuda uyarmıyor. Chiang Mai'de hava mükemmeldi ve yemekler harikaydı, ama bazı haftalar dizüstü bilgisayarım dışında kimseyle konuşmadım. Bir ortak çalışma alanına katılmak her şeyi değiştirdi. Öğle yemeği yiyecek insanlar ve hatta bir koşu grubu buldum."],
      ["Would I recommend this lifestyle? Yes, but not for everyone. You need to be organised and comfortable with uncertainty. You also need a reliable internet connection, which is not always easy to find. I once had to join an important call from a hotel lobby because the power was cut in my building.", "Bu yaşam tarzını tavsiye eder miyim? Evet, ama herkese değil. Düzenli olmanız ve belirsizlikle barışık olmanız gerekiyor. Ayrıca güvenilir bir internet bağlantısına ihtiyacınız var, ki bunu bulmak her zaman kolay değil. Bir keresinde binamda elektrik kesildiği için önemli bir görüşmeye bir otel lobisinden katılmak zorunda kaldım."],
      ["Next month I am going home for a while. I miss my family, my own bed and, honestly, a kitchen where I know where everything is. But I am sure I will pack my bag again soon. If you have questions about any of these cities, leave a comment below.", "Gelecek ay bir süreliğine eve dönüyorum. Ailemi, kendi yatağımı ve açıkçası her şeyin nerede olduğunu bildiğim bir mutfağı özledim. Ama eminim yakında yine çantamı toplayacağım. Bu şehirlerden herhangi biri hakkında sorunuz varsa aşağıya yorum bırakın."]
    ],
    glossary: [["previous", "önceki"], ["productive", "üretken"], ["stunning", "muhteşem, çarpıcı"], ["staring", "dik dik bakmak"], ["plain", "sade, düz"], ["ahead of", "ilerisinde, önünde"], ["purpose", "amaç"], ["loneliness", "yalnızlık"], ["coworking space", "ortak çalışma alanı"], ["organised", "düzenli"], ["uncertainty", "belirsizlik"], ["reliable", "güvenilir"]],
    questions: [
      { q: "What helped the writer work better in Lisbon?", options: ["Moving the desk to face a wall", "Working in a café", "Taking more breaks by the river"], answer: 0 },
      { q: "What problem did the writer have in Tbilisi?", options: ["The internet was too slow", "Meetings continued into the evening", "The flat was too noisy"], answer: 1 },
      { q: "According to the writer, what is the real challenge of remote work?", options: ["Bad weather", "Expensive food", "Loneliness"], answer: 2 },
      { q: "Why did the writer once join a call from a hotel lobby?", options: ["The power was cut in the building", "The hotel had a better view", "The writer was meeting a client there"], answer: 0 }
    ] },

  { id: "r8", title: "Town Turns Car Parks Into Gardens", trTitle: "Kasaba Otoparkları Bahçeye Dönüştürüyor", cefr: "B1", icon: "🌱", kind: "Haber",
    paragraphs: [
      ["The town of Eastbridge has decided to replace more than two hundred parking spaces in its centre with small public gardens. The plan, which was approved by the town council on Thursday, is one of the boldest of its kind in the region and has caused a lively debate among residents.", "Eastbridge kasabası, merkezindeki iki yüzden fazla park yerini küçük halka açık bahçelerle değiştirmeye karar verdi. Belediye meclisi tarafından perşembe günü onaylanan plan, bölgedeki türünün en cesur örneklerinden biri ve sakinler arasında hararetli bir tartışmaya yol açtı."],
      ["According to the council, the new gardens will include trees, flower beds, benches and spaces where local schools can grow vegetables. The work will begin in the spring and should be finished within eighteen months. The project will cost around two million pounds, mostly paid for by a national environmental fund.", "Belediyeye göre yeni bahçelerde ağaçlar, çiçek tarhları, banklar ve yerel okulların sebze yetiştirebileceği alanlar olacak. Çalışmalar baharda başlayacak ve on sekiz ay içinde bitmesi bekleniyor. Projenin maliyeti, büyük kısmı ulusal bir çevre fonu tarafından karşılanmak üzere yaklaşık iki milyon sterlin olacak."],
      ["Supporters say the change will make the centre cleaner, quieter and more attractive. Councillor Megan Price, who led the project, explained that summers in the town are getting hotter every year. Trees can lower the temperature of a street by several degrees, she said. We want people to enjoy the centre, not just drive through it.", "Destekçiler değişikliğin merkezi daha temiz, daha sessiz ve daha çekici hale getireceğini söylüyor. Projeyi yöneten meclis üyesi Megan Price, kasabada yazların her yıl daha da ısındığını açıkladı. Ağaçlar bir sokağın sıcaklığını birkaç derece düşürebilir, dedi. İnsanların merkezden sadece arabayla geçmesini değil, merkezin tadını çıkarmasını istiyoruz."],
      ["However, not everyone is happy. Some shop owners are worried that fewer parking spaces will mean fewer customers. Tom Becker, who runs a hardware shop on the main street, said that many of his customers are older people who cannot carry heavy things on the bus. If they cannot park, they will shop online instead, he warned.", "Ancak herkes memnun değil. Bazı dükkân sahipleri daha az park yerinin daha az müşteri anlamına geleceğinden endişeli. Ana caddede bir hırdavat dükkânı işleten Tom Becker, müşterilerinin çoğunun otobüste ağır şeyler taşıyamayan yaşlı insanlar olduğunu söyledi. Park edemezlerse onun yerine internetten alışveriş yaparlar, diye uyardı."],
      ["To answer these concerns, the council has promised to build a new car park on the edge of town and to run a free electric bus to the centre every ten minutes. Disabled drivers will still be able to park on several streets close to the shops.", "Bu endişelere yanıt olarak belediye, kasabanın kenarında yeni bir otopark inşa etmeye ve merkeze her on dakikada bir ücretsiz elektrikli otobüs çalıştırmaya söz verdi. Engelli sürücüler dükkânlara yakın birkaç sokakta park etmeye devam edebilecek."],
      ["Similar projects in other European towns have had mixed results. In some places, shops actually saw more visitors after the change, while in others business fell for the first year. Eastbridge plans to study the effects carefully and publish a report after two years.", "Diğer Avrupa kasabalarındaki benzer projelerin sonuçları karışık oldu. Bazı yerlerde dükkânlar değişiklikten sonra aslında daha fazla ziyaretçi gördü, bazılarında ise işler ilk yıl düştü. Eastbridge etkileri dikkatle incelemeyi ve iki yıl sonra bir rapor yayımlamayı planlıyor."]
    ],
    glossary: [["replace", "yerini almak, değiştirmek"], ["approved", "onaylandı"], ["council", "belediye meclisi"], ["boldest", "en cesur"], ["residents", "sakinler"], ["flower beds", "çiçek tarhları"], ["fund", "fon"], ["temperature", "sıcaklık"], ["hardware shop", "hırdavatçı"], ["concerns", "endişeler"], ["disabled", "engelli"], ["mixed results", "karışık sonuçlar"]],
    questions: [
      { q: "Who will pay for most of the project?", options: ["Local shop owners", "A national environmental fund", "The residents through higher taxes"], answer: 1 },
      { q: "Why does Megan Price support the gardens?", options: ["Trees can make streets cooler", "Gardens are cheaper than car parks", "Schools asked for more space"], answer: 0 },
      { q: "What is Tom Becker worried about?", options: ["Noise from the building work", "The cost of the electric bus", "Losing customers who need to park"], answer: 2 },
      { q: "What have other European towns experienced?", options: ["Only positive results", "Mixed results", "Only negative results"], answer: 1 }
    ] },

  { id: "r9", title: "A Complaint About My Stay", trTitle: "Konaklamam Hakkında Bir Şikâyet", cefr: "B1", icon: "🏨", kind: "E-posta",
    paragraphs: [
      ["Dear Sir or Madam, I am writing to complain about my recent stay at the Harbour View Hotel from the 12th to the 15th of September. I booked a double room with a sea view for my wedding anniversary, and I paid the full price in advance. Unfortunately, the experience was very disappointing.", "Sayın Yetkili, 12-15 Eylül tarihleri arasında Harbour View Otel'deki son konaklamamla ilgili şikâyette bulunmak için yazıyorum. Evlilik yıldönümüm için deniz manzaralı bir çift kişilik oda ayırttım ve tüm ücreti peşin ödedim. Ne yazık ki deneyim son derece hayal kırıklığı yaratıcıydı."],
      ["When we arrived, the receptionist told us that our room was not ready. We waited in the lobby for almost two hours. Then we were given a room on the first floor that faced the car park, not the sea. When I showed my booking confirmation, the staff apologised but said that no other rooms were available.", "Vardığımızda resepsiyon görevlisi odamızın hazır olmadığını söyledi. Lobide yaklaşık iki saat bekledik. Sonra bize denize değil otoparka bakan birinci katta bir oda verildi. Rezervasyon onayımı gösterdiğimde personel özür diledi ama başka uygun oda olmadığını söyledi."],
      ["The room itself also had several problems. The air conditioning was extremely noisy, so we could hardly sleep. There was no hot water on the second morning, and the bathroom had not been cleaned properly. I reported these issues twice at reception, but nobody came to fix them. On our last night, we decided to sleep with the air conditioning off, even though the room was very hot.", "Odanın kendisinde de birkaç sorun vardı. Klima son derece gürültülüydü, bu yüzden neredeyse hiç uyuyamadık. İkinci sabah sıcak su yoktu ve banyo düzgün temizlenmemişti. Bu sorunları resepsiyona iki kez bildirdim ama kimse onları düzeltmeye gelmedi. Son gecemizde oda çok sıcak olmasına rağmen klimayı kapatarak uyumaya karar verdik."],
      ["I would like to say that some of your staff were very kind. In particular, a waiter named Can at the breakfast restaurant was helpful and friendly, and he even brought us a small cake when he heard it was our anniversary. However, one kind person cannot make up for so many problems.", "Personelinizden bazılarının çok nazik olduğunu belirtmek isterim. Özellikle kahvaltı restoranında Can adında bir garson yardımsever ve güler yüzlüydü, hatta yıldönümümüz olduğunu duyunca bize küçük bir pasta getirdi. Ancak tek bir nazik kişi bu kadar çok sorunu telafi edemez."],
      ["I paid extra for a sea view that we never had, and our special weekend was spoiled. I would therefore like a refund of the difference between the sea view room and the standard room. I also believe that some compensation for the noise and the lack of hot water would be fair.", "Hiç sahip olmadığımız bir deniz manzarası için ekstra ödeme yaptım ve özel hafta sonumuz mahvoldu. Bu nedenle deniz manzaralı oda ile standart oda arasındaki farkın iadesini istiyorum. Ayrıca gürültü ve sıcak su eksikliği için bir miktar tazminatın adil olacağını düşünüyorum."],
      ["I have attached a copy of my booking confirmation and some photos of the bathroom. I hope that you will take my complaint seriously and improve your service for future guests. I look forward to your reply within fourteen days. Yours faithfully, Elif Demir", "Rezervasyon onayımın bir kopyasını ve banyonun bazı fotoğraflarını ekte gönderiyorum. Şikâyetimi ciddiye alacağınızı ve gelecekteki misafirler için hizmetinizi iyileştireceğinizi umuyorum. On dört gün içinde yanıtınızı bekliyorum. Saygılarımla, Elif Demir"]
    ],
    glossary: [["complain", "şikâyet etmek"], ["in advance", "önceden, peşin"], ["disappointing", "hayal kırıklığı yaratan"], ["booking confirmation", "rezervasyon onayı"], ["apologised", "özür diledi"], ["hardly", "neredeyse hiç"], ["properly", "düzgün bir şekilde"], ["make up for", "telafi etmek"], ["spoiled", "mahvoldu"], ["refund", "geri ödeme, iade"], ["compensation", "tazminat"], ["attached", "ekledi, ekte"]],
    questions: [
      { q: "Why did Elif choose this hotel?", options: ["It was close to her office", "To celebrate her wedding anniversary", "It was the cheapest hotel in town"], answer: 1 },
      { q: "What was wrong with the room they were given?", options: ["It faced the car park instead of the sea", "It was on the top floor", "It had only one bed"], answer: 0 },
      { q: "What does Elif say about the waiter Can?", options: ["He was rude at breakfast", "He forgot their order", "He was kind and brought a cake"], answer: 2 },
      { q: "What does Elif ask the hotel for?", options: ["A free night next year", "A refund of the price difference and some compensation", "A letter of apology from the manager only"], answer: 1 }
    ] },

  { id: "r10", title: "Why We Put Things Off", trTitle: "İşleri Neden Erteliyoruz", cefr: "B1", icon: "🧠", kind: "Röportaj",
    paragraphs: [
      ["Almost everyone puts off important tasks, from answering emails to starting a diet. We spoke to Dr Leyla Arslan, a psychologist who studies everyday habits, about why we procrastinate and what we can do about it. Her answers may surprise you.", "Neredeyse herkes e-postalara cevap vermekten diyete başlamaya kadar önemli işleri erteler. Gündelik alışkanlıkları inceleyen psikolog Dr. Leyla Arslan ile neden ertelediğimizi ve bu konuda ne yapabileceğimizi konuştuk. Cevapları sizi şaşırtabilir."],
      ["Dr Arslan, is procrastination just laziness? Not at all. Lazy people do not want to do anything. Procrastinators often want to do the task, but they feel uncomfortable when they think about it. The task might be boring, difficult or scary, so we look for something that makes us feel better right now, like checking our phones.", "Dr. Arslan, erteleme sadece tembellik mi? Hiç değil. Tembel insanlar hiçbir şey yapmak istemez. Erteleyenler ise çoğu zaman işi yapmak ister ama onu düşündüklerinde rahatsız hissederler. İş sıkıcı, zor ya da korkutucu olabilir, bu yüzden şu an kendimizi daha iyi hissettiren bir şey ararız, telefonumuza bakmak gibi."],
      ["So it is about emotions, not time management? Exactly. Many people buy planners and productivity apps, but these do not solve the real problem. If you are afraid that your report will not be good enough, a beautiful calendar will not help. You need to deal with the feeling first. Ask yourself what exactly you are avoiding and why.", "Yani mesele zaman yönetimi değil, duygular mı? Kesinlikle. Birçok insan ajandalar ve verimlilik uygulamaları satın alıyor ama bunlar asıl sorunu çözmüyor. Raporunuzun yeterince iyi olmayacağından korkuyorsanız güzel bir takvim işe yaramaz. Önce o duyguyla başa çıkmanız gerekir. Kendinize tam olarak neyden kaçındığınızı ve nedenini sorun."],
      ["What practical advice can you give? My favourite trick is the five minute rule. Tell yourself that you will work on the task for only five minutes, and then you can stop. Starting is usually the hardest part. Once you begin, the task often feels less frightening, and most people continue much longer than five minutes.", "Hangi pratik tavsiyeleri verebilirsiniz? En sevdiğim yöntem beş dakika kuralı. Kendinize işin üzerinde sadece beş dakika çalışacağınızı, sonra bırakabileceğinizi söyleyin. Başlamak genellikle en zor kısımdır. Bir kez başladığınızda iş çoğu zaman daha az korkutucu gelir ve çoğu insan beş dakikadan çok daha uzun devam eder."],
      ["Anything else? Be kind to yourself. Research suggests that people who forgive themselves for procrastinating in the past are less likely to do it again. Feeling guilty only adds more negative emotions, and that makes us want to escape even more. It is also helpful to remove distractions, for example by leaving your phone in another room.", "Başka bir şey var mı? Kendinize karşı nazik olun. Araştırmalar, geçmişte erteledikleri için kendilerini affeden insanların bunu tekrar yapma olasılığının daha düşük olduğunu gösteriyor. Suçluluk duymak sadece daha fazla olumsuz duygu ekler ve bu da kaçma isteğimizi daha da artırır. Dikkat dağıtıcı şeyleri ortadan kaldırmak da faydalıdır, örneğin telefonunuzu başka bir odada bırakarak."],
      ["Do you ever procrastinate yourself? Of course! I put off writing this interview answer for two days. In the end, I used my own five minute rule, and here we are. Nobody is perfect, and that is completely normal. The important thing is to notice the pattern and try again tomorrow.", "Siz de hiç erteler misiniz? Tabii ki! Bu röportajın cevaplarını yazmayı iki gün erteledim. Sonunda kendi beş dakika kuralımı kullandım ve işte buradayız. Kimse mükemmel değildir ve bu tamamen normal. Önemli olan bu kalıbı fark etmek ve yarın yeniden denemektir."]
    ],
    glossary: [["put off", "ertelemek"], ["procrastinate", "ertelemek, oyalanmak"], ["laziness", "tembellik"], ["uncomfortable", "rahatsız"], ["emotions", "duygular"], ["planners", "ajandalar"], ["deal with", "başa çıkmak"], ["frightening", "korkutucu"], ["forgive", "affetmek"], ["guilty", "suçlu"], ["escape", "kaçmak"], ["distractions", "dikkat dağıtıcı şeyler"]],
    questions: [
      { q: "According to Dr Arslan, what is the main cause of procrastination?", options: ["Laziness", "Bad time management", "Uncomfortable feelings about a task"], answer: 2 },
      { q: "Why do planners and apps often not help?", options: ["They do not solve the emotional problem", "They are too expensive", "They are difficult to use"], answer: 0 },
      { q: "What is the five minute rule?", options: ["Take a five minute break every hour", "Start a task by working on it for only five minutes", "Check your phone for five minutes before work"], answer: 1 },
      { q: "What does research say about forgiving yourself?", options: ["It makes people lazier", "It has no effect", "It makes people less likely to procrastinate again"], answer: 2 }
    ] }
);
