(window.ROLEPLAYS = window.ROLEPLAYS || []).push(
  { id: "s1", title: "Kafede sipariş", cefr: "A1", icon: "☕", situation: "Bir kafedesin. Baristadan bir içecek ve bir atıştırmalık isteyeceksin, sonra ödemeyi yapacaksın.",
    partner: "Barista",
    turns: [
      { them: "Hi! What can I get you?", themTr: "Merhaba! Ne alırsınız?", hint: "Bir latte iste, boyutunu söyle.",
        answers: ["Can I have a large latte, please?", "I'd like a large latte, please."], keywords: ["latte", "large"] },
      { them: "Sure. Do you want milk or oat milk?", themTr: "Tabii. Normal süt mü, yulaf sütü mü istersiniz?", hint: "Yulaf sütü istediğini söyle.",
        answers: ["Oat milk, please.", "I'd like oat milk, please."], keywords: ["oat", "milk"] },
      { them: "Anything to eat?", themTr: "Yiyecek bir şey ister misiniz?", hint: "Bir kruvasan iste.",
        answers: ["Yes, a croissant, please.", "Can I have a croissant too?"], keywords: ["croissant"] },
      { them: "For here or to go?", themTr: "Burada mı, götürmek için mi?", hint: "Burada içeceğini söyle.",
        answers: ["For here, please.", "I'll have it here, thanks."], keywords: ["here"] },
      { them: "That's seven pounds fifty.", themTr: "Yedi pound elli peni tutuyor.", hint: "Kartla ödeyip ödeyemeyeceğini sor.",
        answers: ["Can I pay by card?", "Is it okay to pay by card?"], keywords: ["pay", "card"] },
      { them: "Of course. Here you go. Have a nice day!", themTr: "Elbette. Buyurun. İyi günler!", hint: "Teşekkür et ve iyi günler dile.",
        answers: ["Thank you! You too.", "Thanks a lot, have a nice day!"], keywords: ["thank"] }
    ] },

  { id: "s2", title: "Otelde check-in", cefr: "A1", icon: "🏨", situation: "Bir otele vardın. Resepsiyondaki görevliyle konuşup rezervasyonunla giriş yapacaksın.",
    partner: "Resepsiyon görevlisi",
    turns: [
      { them: "Good evening! Welcome to the Green Hotel.", themTr: "İyi akşamlar! Green Otel'e hoş geldiniz.", hint: "Rezervasyonun olduğunu söyle.",
        answers: ["Good evening. I have a reservation.", "Hello, I have a booking for tonight."], keywords: ["reservation", "booking"] },
      { them: "Great. What is your name, please?", themTr: "Harika. Adınız nedir lütfen?", hint: "Adını ve soyadını söyle.",
        answers: ["My name is Deniz Kaya.", "It's Deniz Kaya."], keywords: ["name", "kaya"] },
      { them: "Yes, a single room for three nights. Can I see your passport?", themTr: "Evet, üç gece için tek kişilik oda. Pasaportunuzu görebilir miyim?", hint: "Pasaportunu ver ve buyurun de.",
        answers: ["Yes, here is my passport.", "Sure, here you are."], keywords: ["here", "passport"] },
      { them: "Thank you. Your room is on the fourth floor.", themTr: "Teşekkürler. Odanız dördüncü katta.", hint: "Kahvaltının saat kaçta olduğunu sor.",
        answers: ["What time is breakfast?", "When is breakfast, please?"], keywords: ["breakfast", "time"] },
      { them: "Breakfast is from seven to ten.", themTr: "Kahvaltı yediden ona kadar.", hint: "Odada Wi-Fi olup olmadığını sor.",
        answers: ["Is there Wi-Fi in the room?", "Do you have free Wi-Fi?"], keywords: ["wi-fi"] },
      { them: "Yes, it's free. Here is your key. Enjoy your stay!", themTr: "Evet, ücretsiz. İşte anahtarınız. İyi konaklamalar!", hint: "Teşekkür et.",
        answers: ["Thank you very much!", "Thanks, good night!"], keywords: ["thank"] }
    ] },

  { id: "s3", title: "Yol sormak", cefr: "A1", icon: "🗺️", situation: "Yeni bir şehirdesin ve tren istasyonunu arıyorsun. Sokakta birinden yardım isteyeceksin.",
    partner: "Yoldan geçen biri",
    turns: [
      { them: "Hi, are you okay? You look lost.", themTr: "Merhaba, iyi misiniz? Kaybolmuş gibisiniz.", hint: "Kibarca seslen ve istasyonun nerede olduğunu sor.",
        answers: ["Excuse me, where is the train station?", "Hi, can you help me? Where is the station?"], keywords: ["where", "station"] },
      { them: "It's not far. Go straight and turn left at the bank.", themTr: "Uzak değil. Düz gidin ve bankadan sola dönün.", hint: "Bankadan sola mı diye tekrar ederek kontrol et.",
        answers: ["Turn left at the bank?", "So I turn left at the bank, right?"], keywords: ["left", "bank"] },
      { them: "Yes, that's right. Then it's on your right.", themTr: "Evet, doğru. Sonra sağınızda.", hint: "Yürüyerek ne kadar sürdüğünü sor.",
        answers: ["How long does it take on foot?", "Is it far to walk?"], keywords: ["walk", "foot", "long"] },
      { them: "About five minutes.", themTr: "Yaklaşık beş dakika.", hint: "Yakında bir kafe olup olmadığını da sor.",
        answers: ["Is there a cafe near the station?", "Is there a cafe near here?"], keywords: ["cafe", "near"] },
      { them: "Yes, there is a small cafe next to the station.", themTr: "Evet, istasyonun yanında küçük bir kafe var.", hint: "Teşekkür et.",
        answers: ["Thank you so much!", "Great, thanks for your help."], keywords: ["thank"] }
    ] },

  { id: "s4", title: "Markette alışveriş", cefr: "A1", icon: "🛒", situation: "Bir markettesin. Görevliden bazı ürünleri soracak, fiyat öğrenecek ve ödeme yapacaksın.",
    partner: "Market görevlisi",
    turns: [
      { them: "Hello, can I help you?", themTr: "Merhaba, yardımcı olabilir miyim?", hint: "Süt aradığını söyle.",
        answers: ["Yes, I'm looking for milk.", "Hi, where is the milk, please?"], keywords: ["milk"] },
      { them: "The milk is in aisle three, next to the cheese.", themTr: "Süt üçüncü reyonda, peynirin yanında.", hint: "Ekmeğin de nerede olduğunu sor.",
        answers: ["And where is the bread?", "Thanks. Where can I find bread?"], keywords: ["bread"] },
      { them: "The bread is at the front, near the door.", themTr: "Ekmek önde, kapının yanında.", hint: "Elmaların kilosunun ne kadar olduğunu sor.",
        answers: ["How much are the apples?", "How much is a kilo of apples?"], keywords: ["how much", "apples"] },
      { them: "They are two euros a kilo.", themTr: "Kilosu iki euro.", hint: "Bir kilo istediğini söyle.",
        answers: ["One kilo, please.", "I'd like one kilo, please."], keywords: ["kilo"] },
      { them: "Do you need a bag?", themTr: "Poşet ister misiniz?", hint: "Hayır de, kendi çantan olduğunu söyle.",
        answers: ["No, thanks. I have a bag.", "No, I have my own bag."], keywords: ["no", "bag"] },
      { them: "Okay. That's nine euros in total.", themTr: "Tamam. Toplam dokuz euro.", hint: "Nakit ödeyeceğini söyle.",
        answers: ["Here you are. I'll pay in cash.", "I'll pay cash. Here you go."], keywords: ["cash"] }
    ] },

  { id: "s5", title: "Doktora derdini anlatmak", cefr: "A2", icon: "🩺", situation: "Birkaç gündür hastasın ve doktora gittin. Belirtilerini anlatacak ve tavsiye alacaksın.",
    partner: "Doktor",
    turns: [
      { them: "Hello, please sit down. What seems to be the problem?", themTr: "Merhaba, lütfen oturun. Sorun nedir?", hint: "Başının ağrıdığını ve ateşin olduğunu söyle.",
        answers: ["I have a headache and a fever.", "I've had a bad headache and a fever."], keywords: ["headache", "fever"] },
      { them: "How long have you felt like this?", themTr: "Ne zamandır böyle hissediyorsunuz?", hint: "Üç gündür olduğunu söyle.",
        answers: ["For three days.", "Since Monday, so about three days."], keywords: ["three", "days"] },
      { them: "Do you have a sore throat or a cough?", themTr: "Boğaz ağrınız ya da öksürüğünüz var mı?", hint: "Boğazının ağrıdığını ama öksürüğün olmadığını söyle.",
        answers: ["My throat hurts, but I don't have a cough.", "Yes, a sore throat, but no cough."], keywords: ["throat", "cough"] },
      { them: "Are you taking any medicine at the moment?", themTr: "Şu an herhangi bir ilaç kullanıyor musunuz?", hint: "Sadece ağrı kesici aldığını söyle.",
        answers: ["Only a painkiller.", "I took some painkillers yesterday."], keywords: ["painkiller"] },
      { them: "I think it's the flu. Rest, drink a lot of water and take this twice a day.", themTr: "Bence grip. Dinlenin, bol su için ve bunu günde iki kez alın.", hint: "İşe gidip gidemeyeceğini sor.",
        answers: ["Can I go to work tomorrow?", "Should I stay at home or can I work?"], keywords: ["work"] },
      { them: "Stay at home for two or three days. Come back if you feel worse.", themTr: "İki üç gün evde kalın. Kötüleşirseniz tekrar gelin.", hint: "Teşekkür et ve anladığını söyle.",
        answers: ["Okay, I understand. Thank you, doctor.", "Thanks a lot, I will rest."], keywords: ["thank"] }
    ] },

  { id: "s6", title: "Telefonla restoran rezervasyonu", cefr: "A2", icon: "🍽️", situation: "Cumartesi akşamı arkadaşların için bir restoranda masa ayırtmak istiyorsun. Restoranı arıyorsun.",
    partner: "Restoran çalışanı",
    turns: [
      { them: "Good afternoon, Bella Cucina. How can I help?", themTr: "İyi günler, Bella Cucina. Nasıl yardımcı olabilirim?", hint: "Cumartesi için masa ayırtmak istediğini söyle.",
        answers: ["Hi, I'd like to book a table for Saturday.", "Hello, can I reserve a table for Saturday evening?"], keywords: ["table", "saturday"] },
      { them: "Of course. For how many people?", themTr: "Tabii. Kaç kişilik?", hint: "Dört kişi olduğunuzu söyle.",
        answers: ["For four people, please.", "There will be four of us."], keywords: ["four"] },
      { them: "And what time would you like?", themTr: "Saat kaçı istersiniz?", hint: "Saat sekizi iste.",
        answers: ["At eight o'clock, please.", "Is eight o'clock possible?"], keywords: ["eight"] },
      { them: "Sorry, eight is full. We have a table at half past eight.", themTr: "Üzgünüm, sekiz dolu. Sekiz buçukta bir masamız var.", hint: "Sekiz buçuğun uygun olduğunu söyle.",
        answers: ["Half past eight is fine.", "That's okay, half past eight is perfect."], keywords: ["fine", "half past", "okay"] },
      { them: "Lovely. Can I have your name and phone number?", themTr: "Güzel. Adınızı ve telefon numaranızı alabilir miyim?", hint: "Adını söyle ve numaranı vereceğini belirt.",
        answers: ["My name is Elif, and my number is 0555 123 4567.", "It's Elif Demir. My number is 0555 123 4567."], keywords: ["name", "number"] },
      { them: "Thank you. Anything else?", themTr: "Teşekkürler. Başka bir şey var mı?", hint: "Pencere kenarında bir masa isteyip isteyemeyeceğini sor.",
        answers: ["Can we have a table by the window?", "Is it possible to sit near the window?"], keywords: ["window"] }
    ] },

  { id: "s7", title: "Kayıp bagaj", cefr: "A2", icon: "🧳", situation: "Uçaktan indin ama bavulun gelmedi. Havalimanındaki bagaj ofisinde durumu anlatıyorsun.",
    partner: "Havalimanı görevlisi",
    turns: [
      { them: "Hello, how can I help you?", themTr: "Merhaba, size nasıl yardımcı olabilirim?", hint: "Bavulunun gelmediğini söyle.",
        answers: ["My suitcase didn't arrive.", "Hi, I can't find my luggage."], keywords: ["suitcase", "luggage"] },
      { them: "I'm sorry to hear that. Which flight were you on?", themTr: "Bunu duyduğuma üzüldüm. Hangi uçuştaydınız?", hint: "İstanbul'dan gelen uçuşta olduğunu söyle.",
        answers: ["I was on the flight from Istanbul.", "The flight from Istanbul, TK 1979."], keywords: ["flight", "istanbul"] },
      { them: "Can you describe your suitcase?", themTr: "Bavulunuzu tarif edebilir misiniz?", hint: "Büyük, mavi ve tekerlekli olduğunu söyle.",
        answers: ["It's a big blue suitcase with wheels.", "It's large and blue, and it has wheels."], keywords: ["blue", "big", "large"] },
      { them: "Is there anything special on it?", themTr: "Üzerinde özel bir şey var mı?", hint: "Üzerinde sarı bir kurdele olduğunu söyle.",
        answers: ["Yes, there's a yellow ribbon on the handle.", "It has a yellow ribbon on it."], keywords: ["yellow", "ribbon"] },
      { them: "Okay. Where are you staying?", themTr: "Tamam. Nerede kalıyorsunuz?", hint: "Şehir merkezindeki bir otelde kaldığını söyle.",
        answers: ["I'm staying at a hotel in the city centre.", "At the Park Hotel in the centre."], keywords: ["hotel", "centre", "center"] },
      { them: "We will send it to your hotel when we find it.", themTr: "Bulduğumuzda otelinize göndereceğiz.", hint: "Ne kadar süreceğini sor.",
        answers: ["How long will it take?", "When do you think it will arrive?"], keywords: ["how long", "when"] }
    ] },

  { id: "s8", title: "Kiralık daire görmek", cefr: "A2", icon: "🏠", situation: "Kiralık bir daireye bakmaya geldin. Emlakçıya daire hakkında sorular soruyorsun.",
    partner: "Emlakçı",
    turns: [
      { them: "Hi, come in! This is the living room.", themTr: "Merhaba, buyurun! Burası oturma odası.", hint: "Odanın güzel ve aydınlık olduğunu söyle.",
        answers: ["Wow, it's nice and bright.", "It's a lovely, bright room."], keywords: ["bright", "nice", "lovely"] },
      { them: "Yes, it gets a lot of sun. There are two bedrooms.", themTr: "Evet, çok güneş alıyor. İki yatak odası var.", hint: "Kiranın ne kadar olduğunu sor.",
        answers: ["How much is the rent?", "What is the monthly rent?"], keywords: ["rent"] },
      { them: "It's nine hundred a month.", themTr: "Aylık dokuz yüz.", hint: "Faturaların dahil olup olmadığını sor.",
        answers: ["Are the bills included?", "Does that include the bills?"], keywords: ["bills", "include"] },
      { them: "Water is included, but electricity and gas are not.", themTr: "Su dahil ama elektrik ve doğalgaz değil.", hint: "Evcil hayvana izin olup olmadığını sor. Bir kedin var.",
        answers: ["Are pets allowed? I have a cat.", "Can I have a cat here?"], keywords: ["cat", "pets"] },
      { them: "A cat is fine, but no dogs.", themTr: "Kedi olur ama köpek olmaz.", hint: "Ne zaman taşınabileceğini sor.",
        answers: ["When can I move in?", "Is it available next month?"], keywords: ["move", "available"] },
      { them: "It's free from the first of next month.", themTr: "Gelecek ayın birinden itibaren boş.", hint: "Düşünüp yarın arayacağını söyle.",
        answers: ["Great. I'll think about it and call you tomorrow.", "Thanks, I'll call you tomorrow."], keywords: ["call", "tomorrow"] }
    ] },

  { id: "s9", title: "Kibarca şikâyet", cefr: "B1", icon: "😤", situation: "Bir otelde kalıyorsun ve odandaki klima çalışmıyor, üstelik gürültülü bir odaya verilmişsin. Resepsiyona kibarca şikâyet ediyorsun.",
    partner: "Otel müdürü",
    turns: [
      { them: "Good morning. Is everything all right with your stay?", themTr: "Günaydın. Konaklamanızla ilgili her şey yolunda mı?", hint: "Kibarca bir sorun olduğunu söyle, klimanın çalışmadığını belirt.",
        answers: ["I'm afraid there's a problem. The air conditioning in my room isn't working.", "Not really, I'm sorry to say. The air conditioning doesn't work."], keywords: ["air conditioning", "working", "work"] },
      { them: "Oh, I'm very sorry about that. When did you notice it?", themTr: "Ah, bunun için çok üzgünüm. Ne zaman fark ettiniz?", hint: "Dün geceden beri olduğunu ve uyuyamadığını söyle.",
        answers: ["Since last night. It was so hot that I couldn't sleep.", "Last night, and I hardly slept because of the heat."], keywords: ["last night", "sleep"] },
      { them: "I'll send someone from maintenance right away.", themTr: "Hemen teknik servisten birini göndereceğim.", hint: "Teşekkür et ama odanın ayrıca çok gürültülü olduğunu ekle.",
        answers: ["Thank you. Also, the room is very noisy because it's above the bar.", "I appreciate that. The room is also really noisy at night."], keywords: ["noisy", "noise"] },
      { them: "I see. That's not the experience we want for our guests.", themTr: "Anlıyorum. Misafirlerimiz için istediğimiz deneyim bu değil.", hint: "Daha sessiz bir odaya geçip geçemeyeceğini sor.",
        answers: ["Would it be possible to move to a quieter room?", "Could I possibly change to a quieter room?"], keywords: ["quieter", "room", "move"] },
      { them: "We have a quiet room on the top floor. I can move you this afternoon.", themTr: "En üst katta sessiz bir odamız var. Sizi bu öğleden sonra taşıyabilirim.", hint: "Memnun olduğunu söyle ve bir indirim ya da telafi isteyip isteyemeyeceğini kibarca sor.",
        answers: ["That would be great. Is there anything you can do about last night, maybe a discount?", "Perfect, thank you. I was also wondering if you could offer a small discount."], keywords: ["discount"] },
      { them: "Of course. We'll take ten percent off your bill and breakfast is on us tomorrow.", themTr: "Elbette. Faturanızdan yüzde on düşeceğiz, yarınki kahvaltı da bizden.", hint: "Teşekkür et ve anlayışlarını takdir ettiğini söyle.",
        answers: ["That's very kind of you. Thank you for understanding.", "Thank you, I really appreciate your help."], keywords: ["thank", "appreciate", "kind"] }
    ] },

  { id: "s10", title: "İş mülakatı", cefr: "B1", icon: "💼", situation: "Bir yazılım şirketinde müşteri destek uzmanı pozisyonu için mülakata girdin. İnsan kaynakları yöneticisinin sorularını cevaplıyorsun.",
    partner: "İK yöneticisi",
    turns: [
      { them: "Thanks for coming in. Could you tell me a little about yourself?", themTr: "Geldiğiniz için teşekkürler. Bana biraz kendinizden bahseder misiniz?", hint: "Kim olduğunu ve iki yıllık müşteri hizmetleri deneyimin olduğunu söyle.",
        answers: ["Sure. I'm Can, and I have two years of experience in customer service.", "Of course. I've worked in customer service for two years at a telecom company."], keywords: ["experience", "customer", "years"] },
      { them: "Why do you want to work for us?", themTr: "Neden bizimle çalışmak istiyorsunuz?", hint: "Şirketin ürünlerini sevdiğini ve teknolojide gelişmek istediğini söyle.",
        answers: ["I really like your products, and I want to grow in the tech industry.", "Because I believe in your product and I want to learn more about technology."], keywords: ["product", "grow", "learn"] },
      { them: "What would you say is your biggest strength?", themTr: "En büyük güçlü yönünüz nedir?", hint: "Sabırlı ve iyi bir dinleyici olduğunu söyle.",
        answers: ["I'm very patient, and I'm a good listener.", "My biggest strength is patience. I listen carefully to customers."], keywords: ["patient", "listen", "patience"] },
      { them: "Tell me about a time you dealt with an angry customer.", themTr: "Kızgın bir müşteriyle uğraştığınız bir zamanı anlatın.", hint: "Bir müşterinin faturası yüzünden kızdığını, sakin kalıp sorunu çözdüğünü anlat.",
        answers: ["Once a customer was angry about a wrong bill. I stayed calm, checked the details and fixed the problem.", "A customer shouted at me about his bill, but I stayed calm and solved it the same day."], keywords: ["calm", "customer", "solved", "fixed"] },
      { them: "Where do you see yourself in five years?", themTr: "Beş yıl sonra kendinizi nerede görüyorsunuz?", hint: "Bir ekibe liderlik etmek istediğini söyle.",
        answers: ["I'd like to be leading a small support team.", "I hope to become a team leader in five years."], keywords: ["team", "lead", "leader", "leading"] },
      { them: "Do you have any questions for us?", themTr: "Bize sormak istediğiniz bir şey var mı?", hint: "Eğitim imkânlarını ve sonraki adımı sor.",
        answers: ["Yes. What kind of training do you offer, and what is the next step?", "Could you tell me about training opportunities and the next steps?"], keywords: ["training", "next"] }
    ] },

  { id: "s11", title: "İnternet arızasını bildirmek", cefr: "B1", icon: "📞", situation: "Evdeki internetin iki gündür çalışmıyor ve evden çalışıyorsun. İnternet sağlayıcının müşteri hizmetlerini arıyorsun.",
    partner: "Müşteri temsilcisi",
    turns: [
      { them: "Thank you for calling. How can I help you today?", themTr: "Aradığınız için teşekkürler. Bugün size nasıl yardımcı olabilirim?", hint: "İnternetinin iki gündür çalışmadığını söyle.",
        answers: ["Hi, my internet hasn't been working for two days.", "Hello, I've had no internet connection since Tuesday."], keywords: ["internet", "working", "connection"] },
      { them: "I'm sorry about that. Have you tried restarting the router?", themTr: "Bunun için üzgünüm. Modemi yeniden başlatmayı denediniz mi?", hint: "Birkaç kez denediğini ama işe yaramadığını söyle.",
        answers: ["Yes, I've restarted it several times, but it didn't help.", "I have, three times actually, but nothing changed."], keywords: ["restarted", "times"] },
      { them: "What lights can you see on the router?", themTr: "Modemde hangi ışıkları görüyorsunuz?", hint: "Kırmızı bir ışığın yanıp söndüğünü söyle.",
        answers: ["There's a red light that keeps flashing.", "One light is red and it's flashing."], keywords: ["red", "light", "flashing"] },
      { them: "That means there's a problem on the line. I'll need to send a technician.", themTr: "Bu, hatta bir sorun olduğu anlamına geliyor. Bir teknisyen göndermem gerekecek.", hint: "Evden çalıştığını ve acil olduğunu söyle, ne zaman gelebileceklerini sor.",
        answers: ["I work from home, so it's urgent. When can they come?", "It's quite urgent because I work from home. How soon can someone come?"], keywords: ["urgent", "when", "soon"] },
      { them: "The earliest appointment is Thursday morning.", themTr: "En erken randevu perşembe sabahı.", hint: "Perşembenin uygun olduğunu söyle ama çalışmayan günler için ücret iadesi olup olmayacağını sor.",
        answers: ["Thursday is fine. Will I get a refund for the days without internet?", "Okay, Thursday works. Can I get some money back for these days?"], keywords: ["thursday", "refund", "money"] },
      { them: "Yes, we'll add a credit to your next bill.", themTr: "Evet, bir sonraki faturanıza indirim yansıtacağız.", hint: "Teşekkür et ve bir referans numarası iste.",
        answers: ["Thank you. Could I have a reference number, please?", "Great, thanks. Can you give me a reference number?"], keywords: ["reference", "number"] }
    ] },

  { id: "s12", title: "Mağazada ürün iadesi", cefr: "B1", icon: "🧾", situation: "Geçen hafta aldığın kulaklığın bir tarafı ses vermiyor. Mağazaya gidip iade etmek ya da değiştirmek istiyorsun.",
    partner: "Mağaza çalışanı",
    turns: [
      { them: "Hi there, how can I help?", themTr: "Merhaba, nasıl yardımcı olabilirim?", hint: "Geçen hafta bu kulaklığı aldığını ve bir sorun olduğunu söyle.",
        answers: ["Hi, I bought these headphones last week, but there's a problem with them.", "Hello, I'd like to return these headphones. I bought them last week."], keywords: ["headphones", "last week", "return"] },
      { them: "What's wrong with them?", themTr: "Nesi var?", hint: "Sol taraftan hiç ses gelmediğini söyle.",
        answers: ["There's no sound from the left side.", "The left side doesn't work at all."], keywords: ["left", "sound", "work"] },
      { them: "Do you have the receipt?", themTr: "Fişiniz var mı?", hint: "Fişin olduğunu söyle ve ver.",
        answers: ["Yes, here's the receipt.", "I do, here you are."], keywords: ["receipt", "here"] },
      { them: "Would you like a refund or an exchange?", themTr: "Para iadesi mi istersiniz, değişim mi?", hint: "Aynı modelden yenisini istediğini söyle.",
        answers: ["I'd prefer an exchange for the same model.", "Could I just exchange them for a new pair?"], keywords: ["exchange", "same", "new"] },
      { them: "I'm afraid that model is out of stock at the moment.", themTr: "Maalesef o model şu an stokta yok.", hint: "O zaman para iadesi istediğini söyle.",
        answers: ["In that case, I'd like a refund, please.", "Then I'll take a refund instead."], keywords: ["refund"] },
      { them: "No problem. The money will be back on your card in three to five days.", themTr: "Sorun değil. Para üç ila beş gün içinde kartınıza geri yatar.", hint: "Teşekkür et ve anladığını söyle.",
        answers: ["Perfect, thanks for your help.", "Great, thank you very much."], keywords: ["thank"] }
    ] },

  { id: "s13", title: "Maaş pazarlığı", cefr: "B2", icon: "💰", situation: "Bir pazarlama şirketinden iş teklifi aldın ama önerilen maaş beklentinin altında. İK müdürüyle kibar ama kararlı bir şekilde pazarlık yapıyorsun.",
    partner: "İK müdürü",
    turns: [
      { them: "We're delighted to offer you the position. The starting salary is forty-five thousand a year. What do you think?", themTr: "Size pozisyonu teklif etmekten mutluluk duyuyoruz. Başlangıç maaşı yıllık kırk beş bin. Ne düşünüyorsunuz?", hint: "Teklif için teşekkür et, heyecanlı olduğunu ama rakamın beklentinin altında kaldığını söyle.",
        answers: ["Thank you, I'm really excited about the role. However, the salary is a bit lower than I expected.", "I appreciate the offer and I'm keen to join, but to be honest, I was expecting a higher figure."], keywords: ["salary", "expected", "expecting", "lower"] },
      { them: "I see. What figure did you have in mind?", themTr: "Anlıyorum. Aklınızda nasıl bir rakam vardı?", hint: "Piyasa araştırmasına ve deneyimine dayanarak elli iki bin iste.",
        answers: ["Based on my research and experience, I was thinking of around fifty-two thousand.", "Considering the market rate for this role and my five years of experience, fifty-two thousand would be fair."], keywords: ["fifty-two", "experience", "market", "research"] },
      { them: "That's quite a jump. Our budget for this role is fairly fixed.", themTr: "Bu oldukça büyük bir fark. Bu pozisyon için bütçemiz epey sabit.", hint: "Anlayışla karşıladığını söyle ama şirkete katacağın değeri vurgula.",
        answers: ["I understand, but I'm confident I can bring real value, especially with my experience in digital campaigns.", "I appreciate that budgets are tight, but I believe my skills will pay off quickly for the team."], keywords: ["value", "experience", "skills", "understand"] },
      { them: "The best we could do is forty-eight thousand.", themTr: "Yapabileceğimizin en iyisi kırk sekiz bin.", hint: "Maaş artmıyorsa başka haklar konusunda esneklik olup olmadığını sor, örneğin uzaktan çalışma ya da ek izin.",
        answers: ["If the salary is fixed, is there any flexibility on other benefits, like remote work or extra holiday?", "Could we look at the overall package then? For example, two days of remote work or a few more days off."], keywords: ["remote", "holiday", "benefits", "package"] },
      { them: "We could offer two remote days a week and a performance review after six months.", themTr: "Haftada iki gün uzaktan çalışma ve altı ay sonra bir performans değerlendirmesi önerebiliriz.", hint: "Altı ay sonraki değerlendirmede maaşın yeniden ele alınacağının yazılı olarak belirtilmesini iste.",
        answers: ["That sounds reasonable. Could we put in writing that the salary will be reviewed after six months?", "That works for me, as long as the six-month salary review is included in the contract."], keywords: ["writing", "contract", "review"] },
      { them: "Yes, I can add that to the contract.", themTr: "Evet, bunu sözleşmeye ekleyebilirim.", hint: "Teklifi kabul ettiğini söyle ve başlamak için sabırsızlandığını belirt.",
        answers: ["In that case, I'm happy to accept. I'm looking forward to starting.", "Great, then we have a deal. I can't wait to get started."], keywords: ["accept", "deal", "forward", "start"] }
    ] },

  { id: "s14", title: "Toplantıda itiraz etmek", cefr: "B2", icon: "🗣️", situation: "Ekip toplantısında müdürün yeni ürünü iki hafta içinde piyasaya sürmeyi öneriyor. Sen bunun riskli olduğunu düşünüyorsun ve saygılı bir şekilde itiraz ediyorsun.",
    partner: "Ekip müdürü",
    turns: [
      { them: "So, I'd like us to launch the new app in two weeks. Any thoughts?", themTr: "Evet, yeni uygulamayı iki hafta içinde piyasaya sürmemizi istiyorum. Fikri olan var mı?", hint: "Hedefi anladığını söyle ama bazı endişelerin olduğunu belirt.",
        answers: ["I see why we want to move fast, but I have some concerns about the timeline.", "I understand the goal, but I'm not sure two weeks is realistic."], keywords: ["concerns", "timeline", "realistic"] },
      { them: "Go on. What's worrying you?", themTr: "Devam et. Seni endişelendiren ne?", hint: "Testlerin bitmediğini ve hâlâ ciddi hatalar olduğunu söyle.",
        answers: ["Testing isn't finished yet, and we still have some serious bugs in the payment system.", "We haven't completed testing, and there are a few critical bugs we need to fix first."], keywords: ["testing", "bugs"] },
      { them: "But our competitors are launching something similar next month. We can't afford to wait.", themTr: "Ama rakiplerimiz gelecek ay benzer bir şey çıkarıyor. Beklemeyi göze alamayız.", hint: "Haklı olduğunu kabul et ama hatalı bir lansmanın itibarımıza daha çok zarar vereceğini savun.",
        answers: ["That's a fair point. Still, a buggy launch could damage our reputation more than a short delay.", "I agree timing matters, but if users have a bad first experience, we might lose them for good."], keywords: ["reputation", "delay", "users", "lose"] },
      { them: "So what do you suggest?", themTr: "Peki ne öneriyorsun?", hint: "Bir orta yol öner, önce küçük bir kullanıcı grubuyla beta sürümü yayınlayalım.",
        answers: ["How about a beta release for a small group of users first, and a full launch in four weeks?", "What if we did a limited beta in two weeks and the official launch two weeks later?"], keywords: ["beta", "users", "launch"] },
      { them: "Hmm, that could work. But who would handle the feedback?", themTr: "Hmm, bu işe yarayabilir. Ama geri bildirimlerle kim ilgilenecek?", hint: "Bu işi senin üstlenebileceğini söyle.",
        answers: ["I'd be happy to take that on and report back every week.", "I can take responsibility for collecting the feedback and sharing it with the team."], keywords: ["feedback", "take", "responsibility"] },
      { them: "All right, let's try it your way. Can you send me a plan by Friday?", themTr: "Tamam, senin dediğin gibi deneyelim. Cumaya kadar bana bir plan gönderebilir misin?", hint: "Kabul et ve dinlediği için teşekkür et.",
        answers: ["Absolutely, I'll have it ready by Friday. Thanks for hearing me out.", "Sure, you'll have it by Friday. I appreciate you being open to this."], keywords: ["friday", "thanks", "appreciate"] }
    ] },

  { id: "s15", title: "Ev sahibiyle tartışma", cefr: "B2", icon: "🔑", situation: "Ev sahibin kirayı yüzde otuz artırmak istiyor ve aylardır bildirdiğin nem sorununu hâlâ çözmedi. Onunla telefonda konuşuyorsun.",
    partner: "Ev sahibi",
    turns: [
      { them: "Hi, I'm calling about the rent. From next month, it'll go up by thirty percent.", themTr: "Merhaba, kira için arıyorum. Gelecek aydan itibaren yüzde otuz artacak.", hint: "Şaşırdığını ve bu artışın çok yüksek olduğunu söyle.",
        answers: ["Thirty percent? That's a huge increase. I wasn't expecting that at all.", "Honestly, that's far too much. Thirty percent is a lot more than the usual rise."], keywords: ["thirty", "increase", "too much"] },
      { them: "Well, prices have gone up everywhere. I have bills to pay too.", themTr: "Ama her yerde fiyatlar arttı. Benim de ödemem gereken faturalar var.", hint: "Bunu anladığını ama nem sorununun aylardır çözülmediğini hatırlat.",
        answers: ["I understand that, but I reported the damp in the bedroom months ago and nothing has been done.", "I get that, but the damp problem I told you about in March still hasn't been fixed."], keywords: ["damp", "fixed", "months", "reported"] },
      { them: "I've been busy. It's not that serious, is it?", themTr: "Meşguldüm. O kadar ciddi değil, değil mi?", hint: "Duvarlarda küf olduğunu ve sağlığını etkilediğini söyle.",
        answers: ["Actually, it is. There's mould on the walls and it's affecting my health.", "It's quite serious. The mould is spreading and I've been coughing a lot."], keywords: ["mould", "mold", "health"] },
      { them: "Okay, okay. I'll send someone to look at it.", themTr: "Tamam, tamam. Bakması için birini göndereceğim.", hint: "Net bir tarih iste ve artışı ancak sorun çözülünce konuşabileceğinizi söyle.",
        answers: ["I'd appreciate a specific date. And I think we should discuss the rent only after the repair is done.", "Could we agree on a date? I'd rather talk about any increase once the problem is solved."], keywords: ["date", "repair", "solved", "rent"] },
      { them: "Fine. But I still need some kind of increase.", themTr: "Peki. Ama yine de bir miktar artışa ihtiyacım var.", hint: "Yasal sınırı hatırlatarak yüzde on gibi makul bir artış öner.",
        answers: ["I'm willing to accept a reasonable increase, maybe ten percent, which is closer to the legal limit.", "I could agree to ten percent. That seems fair and it's within the legal limit."], keywords: ["ten percent", "reasonable", "legal", "fair"] },
      { them: "Let's say fifteen and I'll fix the damp next week.", themTr: "On beş diyelim, nemi de gelecek hafta hallederim.", hint: "Kabul ettiğini ama anlaşmayı yazılı olarak istediğini söyle.",
        answers: ["All right, fifteen percent, as long as the repair is done next week. Could you send me that in writing?", "Okay, deal. But please confirm it by email so we both have a record."], keywords: ["writing", "email", "confirm"] }
    ] },

  { id: "s16", title: "Networking etkinliği", cefr: "B2", icon: "🤝", situation: "Bir teknoloji konferansının networking bölümündesin. Tanımadığın bir yöneticiyle sohbet başlatıp bağlantı kurmak istiyorsun.",
    partner: "Konferans katılımcısı",
    turns: [
      { them: "Hi, are you enjoying the conference so far?", themTr: "Merhaba, konferans şimdiye kadar hoşunuza gidiyor mu?", hint: "Olumlu cevap ver, sabahki yapay zekâ konuşmasını beğendiğini söyle ve kendini tanıt.",
        answers: ["Yes, very much. The talk on AI this morning was brilliant. I'm Selin, by the way.", "Definitely. I really enjoyed the AI session this morning. I'm Selin, nice to meet you."], keywords: ["talk", "session", "enjoy", "meet"] },
      { them: "Nice to meet you, Selin. I'm Mark. What do you do?", themTr: "Tanıştığımıza memnun oldum Selin. Ben Mark. Ne iş yapıyorsun?", hint: "Bir fintech girişiminde ürün tasarımcısı olduğunu söyle.",
        answers: ["I'm a product designer at a fintech start-up in Istanbul.", "I work as a product designer for a small fintech company."], keywords: ["designer", "fintech"] },
      { them: "Interesting! We're actually looking at fintech partnerships at the moment.", themTr: "İlginç! Aslında şu sıralar fintech ortaklıklarına bakıyoruz.", hint: "Merakını göster ve ne tür ortaklıklar aradıklarını sor.",
        answers: ["Oh, really? What kind of partnerships are you looking for?", "That's a coincidence. What sort of partners do you have in mind?"], keywords: ["partnerships", "partners", "kind", "sort"] },
      { them: "Mostly companies that can help us make payments simpler for small businesses.", themTr: "Çoğunlukla küçük işletmeler için ödemeleri kolaylaştırmamıza yardım edebilecek şirketler.", hint: "Tam olarak bunun üzerinde çalıştığınızı söyle ve kısa bir örnek ver.",
        answers: ["That's exactly what we focus on. Our app lets small shops get paid in one tap.", "Funny you should say that, we've just built a simple payment tool for small businesses."], keywords: ["small", "payment", "paid", "businesses"] },
      { them: "I'd love to hear more, but I have to run to another session.", themTr: "Daha fazlasını duymayı çok isterdim ama başka bir oturuma yetişmem gerek.", hint: "İletişim bilgisi alışverişi yapmayı ve sonra görüşmeyi öner.",
        answers: ["No problem. Shall we swap contact details and set up a call next week?", "Of course. Can I connect with you on LinkedIn and send you a short email?"], keywords: ["contact", "call", "connect", "email"] },
      { them: "Absolutely, here's my card. Drop me a line on Monday.", themTr: "Kesinlikle, işte kartım. Pazartesi bana bir mesaj at.", hint: "Teşekkür et ve pazartesi yazacağını söyle.",
        answers: ["Thanks, Mark. I'll email you on Monday. Enjoy the rest of the conference!", "Great, I'll be in touch on Monday. It was a pleasure meeting you."], keywords: ["monday", "touch", "email"] }
    ] },

  { id: "s17", title: "Yatırımcıya sunum", cefr: "C1", icon: "📈", situation: "Yemek israfını azaltan bir uygulamanın kurucususun. Bir melek yatırımcıya kısa bir sunum yapıyor ve zor sorularını yanıtlıyorsun.",
    partner: "Yatırımcı",
    turns: [
      { them: "You've got five minutes. What problem are you solving?", themTr: "Beş dakikan var. Hangi sorunu çözüyorsun?", hint: "Restoranların her gün büyük miktarda yemeği çöpe attığını ve uygulamanızın bunu indirimli satışa dönüştürdüğünü söyle.",
        answers: ["Restaurants throw away tonnes of perfectly good food every day. Our app lets them sell that surplus at a discount instead of binning it.", "Food waste costs restaurants a fortune. We turn their unsold meals into revenue by connecting them with nearby customers."], keywords: ["food", "waste", "restaurants", "surplus"] },
      { them: "There are already a few apps doing that. What sets you apart?", themTr: "Bunu yapan birkaç uygulama zaten var. Sizi farklı kılan ne?", hint: "Satışları tahmin eden kendi algoritmanızı ve restoranların atığı önceden azaltabildiğini vurgula.",
        answers: ["Unlike our competitors, we predict surplus before it happens, so restaurants can actually cut waste at the source rather than just discount it.", "Our edge is the forecasting engine. It tells kitchens how much to cook, which tackles the root cause, not just the symptom."], keywords: ["predict", "forecasting", "competitors", "waste"] },
      { them: "Interesting. What kind of traction do you have?", themTr: "İlginç. Ne kadar ivme yakaladınız?", hint: "Somut rakamlar ver, üç yüz restoran, aylık yüzde yirmi büyüme ve düşük kayıp oranı.",
        answers: ["We've signed up three hundred restaurants in eight months, we're growing twenty percent month on month, and churn is under three percent.", "Three hundred partner restaurants so far, twenty percent monthly growth and very low churn, which tells us the product sticks."], keywords: ["restaurants", "growth", "growing", "churn"] },
      { them: "Your margins look thin, though. How do you plan to become profitable?", themTr: "Ama kâr marjlarınız düşük görünüyor. Kârlı hâle gelmeyi nasıl planlıyorsunuz?", hint: "Endişeyi kabul et, abonelik modeline geçtiğinizi ve veri analitiğini ek gelir kaynağı olarak sunacağınızı açıkla.",
        answers: ["That's a fair concern. We're moving restaurants onto a monthly subscription and adding premium analytics, which should push us into profit within eighteen months.", "You're right that commission alone won't get us there. The subscription tier and our analytics package are what will make the unit economics work."], keywords: ["subscription", "analytics", "profit", "concern"] },
      { them: "How much are you raising, and what will you use it for?", themTr: "Ne kadar yatırım arıyorsunuz ve bunu ne için kullanacaksınız?", hint: "Bir buçuk milyon istediğini, çoğunu üç yeni şehre açılmak ve mühendis almak için kullanacağını söyle.",
        answers: ["We're raising one and a half million. Most of it will go towards expanding into three new cities and hiring two senior engineers.", "One point five million, primarily to fund expansion into three cities and to strengthen the engineering team."], keywords: ["million", "expand", "expanding", "expansion", "engineers", "engineering"] },
      { them: "I like what I'm hearing, but I'd want to see your financials in more detail.", themTr: "Duyduklarım hoşuma gidiyor ama mali tablolarınızı daha ayrıntılı görmek isterim.", hint: "Memnuniyetle göndereceğini söyle ve bir sonraki görüşme için tarih öner.",
        answers: ["Of course. I'll send over the full financial model today. Would you be free for a follow-up call later this week?", "Absolutely, I'd be glad to share them. Shall we schedule a deeper dive for Thursday?"], keywords: ["financial", "send", "share", "follow-up"] }
    ] },

  { id: "s18", title: "Zor bir haberi vermek", cefr: "C1", icon: "😔", situation: "Bir ekip liderisin. Şirketin bütçe kesintisi yüzünden ekibindeki bir çalışanın pozisyonunun kaldırıldığını ona kendin söylemek zorundasın.",
    partner: "Ekip üyesi",
    turns: [
      { them: "Hi, you wanted to see me? Is everything okay?", themTr: "Merhaba, beni görmek istemişsin? Her şey yolunda mı?", hint: "Oturmasını rica et ve maalesef konuşmanın kolay olmayacağını söyle.",
        answers: ["Thanks for coming in. Please take a seat. I'm afraid this isn't going to be an easy conversation.", "Have a seat, Ali. I'll be honest with you, I have some difficult news."], keywords: ["seat", "easy", "difficult", "news"] },
      { them: "Oh. That doesn't sound good.", themTr: "Ah. Bu hiç iyi gelmedi kulağa.", hint: "Dolandırmadan, bütçe kesintileri nedeniyle pozisyonunun kaldırıldığını söyle.",
        answers: ["Due to the budget cuts, the company has decided to eliminate your position. I'm really sorry.", "There's no easy way to say this. Because of the cuts, your role is being made redundant."], keywords: ["position", "role", "budget", "cuts", "redundant"] },
      { them: "What? I don't understand. Was it something I did?", themTr: "Ne? Anlamıyorum. Benim yaptığım bir şey yüzünden mi?", hint: "Bunun performansıyla hiçbir ilgisi olmadığını net bir şekilde belirt ve emeğini takdir ettiğini söyle.",
        answers: ["No, not at all. This has nothing to do with your performance. You've done excellent work and I want you to know that.", "Absolutely not. It's purely a financial decision, and I genuinely value everything you've contributed."], keywords: ["performance", "nothing", "value", "work"] },
      { them: "I just bought a flat. I really don't know what I'm going to do.", themTr: "Daha yeni bir daire aldım. Gerçekten ne yapacağımı bilmiyorum.", hint: "Duygularını anladığını göster ve üç aylık tazminat ile kariyer danışmanlığı alacağını açıkla.",
        answers: ["I can only imagine how stressful this must be. You'll receive three months' severance pay, and the company will cover career coaching.", "That's completely understandable. To help with the transition, there's a three-month severance package and support from a career coach."], keywords: ["severance", "career", "understand", "imagine"] },
      { them: "And what about a reference? Will you support me?", themTr: "Peki ya referans? Bana destek olacak mısın?", hint: "Güçlü bir referans yazacağını ve ağındaki kişilere onu önereceğini söyle.",
        answers: ["Of course. I'll write you a strong reference, and I'll personally recommend you to people in my network.", "Without question. I'd be happy to be a reference and to introduce you to a few contacts who are hiring."], keywords: ["reference", "recommend", "network", "contacts"] },
      { them: "Thanks. I need some time to take this in.", themTr: "Teşekkürler. Bunu sindirmek için biraz zamana ihtiyacım var.", hint: "Anlayış göster, günün geri kalanında izin alabileceğini ve her zaman konuşmaya hazır olduğunu söyle.",
        answers: ["Of course, take all the time you need. Feel free to take the rest of the day off, and my door is always open.", "Completely understandable. Go home if you'd like, and whenever you want to talk, I'm here."], keywords: ["time", "day off", "talk", "open"] }
    ] },

  { id: "s19", title: "Müşteriye gecikmeyi açıklamak", cefr: "C1", icon: "🧯", situation: "Bir yazılım ajansında proje yöneticisisin. Önemli bir müşterinin projesi bir tedarikçi sorunu yüzünden üç hafta gecikecek. Müşteriyle görüntülü görüşmedesin.",
    partner: "Müşteri",
    turns: [
      { them: "So, are we still on track for the launch at the end of the month?", themTr: "Evet, ay sonundaki lansman için hâlâ planlandığı gibi mi gidiyoruz?", hint: "Doğrudan ama nazikçe gecikme olacağını söyle ve sorumluluğu üstlen.",
        answers: ["I'm afraid not, and I wanted to tell you directly. We're looking at a delay of about three weeks, and I take full responsibility for that.", "Unfortunately, no. I'd rather be upfront with you. The launch will be pushed back by roughly three weeks."], keywords: ["delay", "weeks", "responsibility", "pushed back"] },
      { them: "Three weeks? That's unacceptable. We've already planned a marketing campaign around that date.", themTr: "Üç hafta mı? Bu kabul edilemez. O tarihe göre bir pazarlama kampanyası bile planladık.", hint: "Hayal kırıklığını anladığını söyle ve gecikmenin nedenini kısaca açıkla.",
        answers: ["I completely understand your frustration. The delay is due to our payment provider changing their system at the last minute, which affected the checkout.", "You have every right to be frustrated. The root cause is a third-party payment provider that changed their API without notice."], keywords: ["frustration", "frustrated", "provider", "understand"] },
      { them: "Why weren't we told about this earlier?", themTr: "Bunu neden daha önce söylemediniz?", hint: "Daha erken haber vermeniz gerektiğini kabul et ve iletişimi nasıl iyileştireceğinizi anlat.",
        answers: ["That's a fair criticism. We should have flagged it sooner. From now on, you'll get a written progress update every Friday.", "You're right, we should have raised it as soon as we spotted the risk. Going forward, I'll send you weekly status reports."], keywords: ["sooner", "earlier", "update", "weekly", "reports"] },
      { them: "Is there any way to speed things up?", themTr: "İşleri hızlandırmanın bir yolu var mı?", hint: "İki seçenek sun, ya ödeme özelliği olmadan zamanında yayın ya da ekibe iki geliştirici ekleyerek gecikmeyi kısaltmak.",
        answers: ["There are two options. We could launch on time without the online payment feature, or add two more developers and cut the delay to about ten days.", "We could either go live on schedule with a limited version, or bring in extra developers to shorten the delay to under two weeks."], keywords: ["options", "launch", "developers", "feature", "version"] },
      { them: "And who pays for the extra developers?", themTr: "Peki ek geliştiricilerin parasını kim ödeyecek?", hint: "Ek maliyeti ajansın karşılayacağını söyle.",
        answers: ["We'll cover that cost ourselves. You shouldn't have to pay for a problem on our side.", "That's on us. There will be no additional charge to you."], keywords: ["cover", "cost", "charge", "us"] },
      { them: "Okay, that helps. Let's go with the extra developers.", themTr: "Tamam, bu işe yarar. Ek geliştiricilerle devam edelim.", hint: "Kararı onayla, yeni tarihi bugün yazılı olarak göndereceğini ve anlayışı için teşekkür ettiğini söyle.",
        answers: ["Great. I'll confirm the revised timeline in writing today. Thank you for being so understanding.", "Understood. You'll have the updated plan by the end of the day, and I really appreciate your patience."], keywords: ["timeline", "plan", "writing", "appreciate", "thank"] }
    ] },

  { id: "s20", title: "Performans değerlendirmesinde geri bildirim", cefr: "C1", icon: "📝", situation: "Bir yöneticisin. Yetenekli ama sık sık teslim tarihlerini kaçıran ve toplantılarda başkalarının sözünü kesen bir çalışanla yıllık değerlendirme görüşmesi yapıyorsun.",
    partner: "Çalışan",
    turns: [
      { them: "So, how do you think my year has gone?", themTr: "Peki, sence yılım nasıl geçti?", hint: "Önce güçlü yönlerinden başla, özellikle yeni müşteri portalındaki yaratıcı çözümlerini öv.",
        answers: ["Overall, it's been a strong year. Your creative solutions on the new client portal really impressed everyone.", "There's a lot to be proud of. The work you did on the client portal was genuinely outstanding."], keywords: ["strong", "portal", "creative", "outstanding"] },
      { them: "Thanks, I'm glad to hear that. But I sense there's a but coming.", themTr: "Teşekkürler, bunu duyduğuma sevindim. Ama bir ama geleceğini sezer gibiyim.", hint: "Gülümseyerek kabul et ve teslim tarihleri konusunu somut bir örnekle aç.",
        answers: ["You're right, there are a couple of areas to work on. The main one is deadlines. The last three reports were all late.", "Well, there are two things I'd like to discuss. First, deadlines. Several deliverables this quarter slipped by a week or more."], keywords: ["deadlines", "late", "slipped", "areas"] },
      { them: "To be fair, I was given way too much work at the time.", themTr: "Açıkçası, o dönemde bana çok fazla iş verilmişti.", hint: "Bunun geçerli bir nokta olabileceğini kabul et ama yükünü önceden bildirmesi gerektiğini söyle.",
        answers: ["That may well be true, and I'm partly to blame. But I'd need you to tell me early when your workload is too heavy, so we can reprioritise.", "That's a valid point. Still, if you're overloaded, I need to hear about it before a deadline is missed, not after."], keywords: ["workload", "early", "overloaded", "before"] },
      { them: "Okay, that's fair. You said there were two things?", themTr: "Tamam, bu adil. İki şey olduğunu söylemiştin?", hint: "Toplantılarda başkalarının sözünü kestiğini nazikçe ama açıkça söyle ve etkisini açıkla.",
        answers: ["Yes. In meetings, you sometimes interrupt colleagues. I know it comes from enthusiasm, but some quieter team members stop contributing.", "The second is about meetings. You tend to cut people off, and it means we miss out on ideas from quieter colleagues."], keywords: ["interrupt", "meetings", "colleagues", "cut"] },
      { them: "Wow, I honestly didn't realise I was doing that.", themTr: "Vay, bunu yaptığımın gerçekten farkında değildim.", hint: "Bunun yaygın olduğunu söyleyerek rahatlat ve somut bir öneri sun.",
        answers: ["It's more common than you think. One thing that helps is to make a note of your idea and wait until the other person has finished.", "Lots of people don't notice it. You could try summarising what the other person said before adding your own point."], keywords: ["try", "note", "wait", "finished", "summarising"] },
      { them: "I'll work on it. What would success look like by next review?", themTr: "Bunun üzerinde çalışacağım. Bir sonraki değerlendirmeye kadar başarı neye benzerdi?", hint: "Ölçülebilir iki hedef belirle ve aylık kısa görüşmeler öner.",
        answers: ["Ideally, all deliverables on time and positive feedback from the team on meetings. Let's have a short check-in every month to track progress.", "Two goals, meeting every deadline or flagging risks early, and more balanced discussions. We can review it together in monthly one-to-ones."], keywords: ["deadline", "deliverables", "monthly", "progress", "goals"] }
    ] }
);
